# KMX MTN-Specific RAGU Score Notebook
This notebook computes RAGU scores for KMX loans, broken down by MTN model (3.0, 3.1, 3.2, 4.1).
Aligned with `bareboned_ragu_new.ipynb` for diagnostic purposes.
- **Granularity:** Configurable (weekly/monthly/quarterly) via `granularity` in cell 1
- **Date handling:** Weekly uses `app_date`, monthly/quarterly use `book_date`
- **Output:** Per-model RAGU decomposition + diagnostics, exported to `new_kmx_models.xlsx`

## How to Run
1. Set `granularity`, `START_DATE`, `END_DATE` in cell 1
2. Set `run_from_pickle = True` to load pre-computed data (faster), or `False` to re-run SQL queries
3. Run All Cells
4. Results are exported to `new_kmx_models.xlsx`

In [1]:
import pandas as pd
import numpy as np
import pyodbc
import pickle
import warnings
import time
from tqdm.notebook import tqdm
from matplotlib import pyplot as plt
tqdm.pandas()
pd.set_option('display.max_columns', 100)
pd.set_option('display.min_rows', 100)
import openpyxl
import datetime as dt
import re
import os

# ── Configuration ──
granularity = 'w'                # 'q' = quarterly, 'm' = monthly, 'w' = weekly

START_DATE = '2025-12-01'
END_DATE = None                  # None = auto-detect from today's date

run_every_query = False           # True = re-run SQL, False = load pickle
run_from_pickle = not run_every_query

DATE_COL_MAP = {'q': 'book_date', 'm': 'book_date', 'w': 'app_date'}
PERIOD_FREQ_MAP = {'q': 'Q', 'm': 'M', 'w': 'W-SAT'}

BASELINES = {
    'KMX': {'ltv': 1.59, 'new_recovery_unadjusted': 0.58, 'apr': 0.25},
}

MODEL_PARAMS = {
    'mean_unit_loss': 0.5,
    'unit_loss_to_model_score': 0.02,
    'kmx_loss_scale': 0.067,
}

MTN_MODELS = [3.0, 3.1, 3.2, 4.1]
EXCEL_OUTPUT = 'new_kmx_models.xlsx'

# ── Derived values ──
date_col = DATE_COL_MAP[granularity]
start_date = pd.Timestamp(START_DATE)
end_date = pd.Timestamp(END_DATE) if END_DATE else pd.Timestamp.today().normalize()
period_freq = PERIOD_FREQ_MAP[granularity]
start_period = start_date.to_period(period_freq)
end_period = end_date.to_period(period_freq)
min_date_sql = f"'{START_DATE}'"

print(f"Granularity: {granularity}")
print(f"Date column: {date_col}")
print(f"Period range: {start_period} to {end_period}")
print(f"SQL min_date: {min_date_sql}")

Granularity: w
Date column: app_date
Period range: 2025-11-30/2025-12-06 to 2026-05-03/2026-05-09
SQL min_date: '2025-12-01'

In [2]:
# Parameters
granularity = "w"
START_DATE = "2026-01-01"
END_DATE = None
run_every_query = False
BASELINES = {"KMX": {"ltv": 1.59, "new_recovery_unadjusted": 0.58, "apr": 0.25}}
MODEL_PARAMS = {"mean_unit_loss": 0.5, "unit_loss_to_model_score": 0.02, "kmx_loss_scale": 0.067}
MTN_MODELS = [3.0, 3.1, 3.2, 4.1]

In [3]:
def run_sql(filename, sub_list=None, connection=None, filename_is_query=False):
    if sub_list is None:
        sub_list = []
    if filename_is_query:
        query = filename
    else:
        with open(filename, 'r') as file:
            query = file.read()
    for text, var in sub_list:
        query = query.replace(text, var)
    if connection is None:
        with pyodbc.connect("DSN=Redshift_prod_new") as conn:
            warnings.filterwarnings("ignore", category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings("default", category=UserWarning)
            return df
    else:
        warnings.filterwarnings("ignore", category=UserWarning)
        df = pd.read_sql_query(sql=query, con=connection)
        warnings.filterwarnings("default", category=UserWarning)
        return df


def store_pickle(data, filename):
    if isinstance(data, str):
        data, filename = filename, data
    with open(filename, 'wb') as file:
        pickle.dump(data, file)


def get_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)


def cached_sql(filename, pickle_name, sub_list=None, connection=None, force_refresh=False):
    """Fetch from SQL and cache to pickle. Reuse cache unless force_refresh=True
    or the pickle file is missing."""
    if force_refresh or not os.path.exists(pickle_name):
        df = run_sql(filename, sub_list=sub_list, connection=connection)
        store_pickle(df, pickle_name)
        return df
    return get_pickle(pickle_name)


def smooth(series):
    averaged_series = pd.Series(index=series.index, dtype=float)
    averaged_series.iloc[0] = series.iloc[0]
    averaged_series.iloc[1] = (series.iloc[0] + series.iloc[1] + series.iloc[2]) / 3
    for i in range(2, len(series) - 2):
        averaged_series.iloc[i] = series.iloc[i-2:i+3].mean()
    averaged_series.iloc[-2] = (series.iloc[-1] + series.iloc[-2] + series.iloc[-3]) / 3
    averaged_series.iloc[-1] = series.iloc[-1]
    return averaged_series


def weight_by_proceeds(metric, proceeds):
    return (metric * proceeds).sum() / proceeds.sum()


def weighted_average_and_sum(group, metrics):
    if isinstance(metrics, str):
        weighted_avg = (group[metrics] * group.amt_financed).sum() / group.amt_financed.sum()
        return pd.Series({metrics: weighted_avg, 'amt_financed': group.amt_financed.sum()})
    result_dict = {'amt_financed': group.amt_financed.sum()}
    for metric in metrics:
        weighted_avg = (group[metric] * group.amt_financed).sum() / group.amt_financed.sum()
        result_dict[metric] = weighted_avg
    return pd.Series(result_dict)


def format_vintage(period_series):
    """Convert pd.Period series to formatted vintage strings."""
    if len(period_series) == 0:
        return period_series.astype(str)
    freq = period_series.iloc[0].freqstr
    if freq == 'Q-DEC':
        return period_series.dt.year.astype(str) + ' Q' + period_series.dt.quarter.astype(str)
    elif freq == 'M':
        return period_series.dt.year.astype(str) + ' M' + period_series.dt.month.astype(str).str.zfill(2)
    return period_series.astype(str)


def rebuild_ms_df(ula_subset):
    """Recompute ms_df from a filtered ula_df subset (for per-model scoring).
    MTN 4.1 transform is already applied in-place on ula_df_total upstream."""
    ms_source = ula_subset[['lob', 'cd_model_score', 'amt_financed', 'period']].copy()
    ms_source = ms_source.rename(columns={'cd_model_score': 'model_score'})
    ms = ms_source.groupby(['period', 'lob']).apply(
        weighted_average_and_sum, 'model_score', include_groups=False
    ).reset_index()
    ms['period'] = format_vintage(ms['period'])
    return ms

In [4]:
# Per-table caches under cache/ with _v1 schema tags. When run_from_pickle=True
# (i.e. run_every_query=False) each cached_sql call reuses its pickle if present
# and falls through to SQL if missing. Delete an individual pickle to force a
# selective refresh.
#
# Note: ULA is cached under cache/ula_kmx_v1.pkl because this notebook
# applies a KMX-only filter via sub_list; that is a different schema (KMX
# subset of rows) than the full-LOB cache/ula_v1.pkl written by
# bareboned_ragu_new.ipynb. DLA and new_recovery use identical queries in both
# notebooks, so they share the same cache files.

os.makedirs('cache', exist_ok=True)
force = run_every_query

need_conn = force or not all(
    os.path.exists(p) for p in ('cache/ula_kmx_v1.pkl', 'cache/dla_v1.pkl', 'cache/new_recovery_v1.pkl')
)

if need_conn:
    with pyodbc.connect("DSN=Redshift_prod_new") as conn:
        ula_df_total = cached_sql(
            'vintage_level_ula_query.txt', 'cache/ula_kmx_v1.pkl',
            sub_list=[('{min_book_date}', f"{min_date_sql}\n  AND dru.riskdealergroup = 'KMX'")],
            connection=conn, force_refresh=force,
        )
        print('ULA ready')

        dla_df = cached_sql(
            'new_dll_query.txt', 'cache/dla_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('DLA ready')

        new_recovery = cached_sql(
            'new_recovery_queryt.txt', 'cache/new_recovery_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('New recovery ready')
else:
    ula_df_total = get_pickle('cache/ula_kmx_v1.pkl')
    dla_df = get_pickle('cache/dla_v1.pkl')
    new_recovery = get_pickle('cache/new_recovery_v1.pkl')
    print('ULA, DLA, New recovery loaded from cache')

print(f"ULA records: {len(ula_df_total):,}")
print("[PROGRESS] Data Fetch Complete")

ULA, DLA, New recovery loaded from cache
ULA records: 195,304
[PROGRESS] Data Fetch Complete

In [5]:
def get_ula_multiplier_kmx(ula_df, loss_scale=None, leave_out='None'):
    if loss_scale is None:
        loss_scale = MODEL_PARAMS['kmx_loss_scale']
    ula_df['loss_multiplier'] = 1.0

    if leave_out!='Low FICO':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_fico_flag & ~ula_df.high_model_score_flag)\
                                    + loss_scale * (ula_df.low_fico_flag & ula_df.high_model_score_flag)

    if leave_out!='Low Vantage':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_vantage_flag & ~ula_df.high_model_score_flag)\
                                    + loss_scale * (ula_df.low_vantage_flag & ula_df.high_model_score_flag)

    if leave_out!='High PTI':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0 * ula_df.normal_pti_flag \
                                    + 0.05 * ula_df.high_pti_tier_1_flag \
                                    + 0.1 * ula_df.high_pti_tier_2_flag \
                                    + (1.4 * (1 + loss_scale) - 1) * ula_df.high_pti_tier_3_flag

    ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] /= (1 + loss_scale)

    if leave_out!='Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + (-0.01 + 0.06 * ula_df.secured_credit_flag)\
                                        * ~(~ula_df.job_time_flag & ula_df.narrowed_soft_pull_flag & ula_df.secured_credit_flag)

    if leave_out!='Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 0.99 + 0.18 * ula_df.kmx_auth_tradelines_flag

    if leave_out!='Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= (
            1 + ~ula_df.job_time_flag * (~ula_df.narrowed_soft_pull_flag * -0.025
            + ula_df.narrowed_soft_pull_flag * (~ula_df.secured_credit_flag * 0.108
            + ula_df.secured_credit_flag * 0.295)))

    if leave_out != 'Fraud':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + (ula_df.fraud_adjustment - 1)

    if leave_out!='Clip':
        clipped_multiplier = np.clip(ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'], 0.8, 1.35 / (1 + loss_scale))
        ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'] = clipped_multiplier

    if leave_out!='Vehicle Age':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier']  *= 0.8593 + 0.0201 * ula_df.continuous_vehicle_age

    if leave_out !='npc':
        ula_df.loc[ula_df.kmx_npc_flag, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.high_pti_npc

    if leave_out != 'Student Loans':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.96 +  0.14 * ula_df.student_loan_flag

    if leave_out != 'high sales price':
        ula_df.loc[ula_df.mtn_model.isin([4.1]),'loss_multiplier'] *= 0.98 + 0.22 * ula_df.high_sales_price_flag

    if leave_out != 'Driver flag':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 1 + 0.15 * ula_df.driver_flag

    if leave_out!='Louisiana':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier']  *= 1 + 0.35 * ula_df.louisiana_flag

    if leave_out!='georgia':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier']  *= 1 + 0.1 * ula_df.georgia_flag

    if leave_out!='txca':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score > 140) ,'loss_multiplier']  *= 1 - 0.1 * ula_df.txca_flag
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score <= 140) &  (ula_df.cd_model_score >= 135)   ,'loss_multiplier']  *= 1 - 0.05 * ula_df.txca_flag

    if leave_out!='state_counter_adj':
        ula_df.loc[ ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1])  & (ula_df.cd_model_score < 150) & ~(ula_df.louisiana_flag | ula_df.georgia_flag | ula_df.txca_flag) ,'loss_multiplier'] *= 1.012

    if leave_out!='Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.96 + (0.01 * ula_df.soft_pull_flag  - 0.18*ula_df.chime_flag* ula_df.soft_pull_flag) + 0.46*ula_df.chime_flag

    if leave_out!='Job time':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.21 * ula_df.job_time_flag

    if leave_out!='Existing DQ':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.11 * ula_df.existing_dq_flag

    if leave_out!='Employment type':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 1 + 0.1 * ula_df.seasonal_employment_flag

    if leave_out!='Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.06 * ula_df.kmx_auth_tradelines_flag

    if leave_out!='Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ula_df.soft_pull_flag,'loss_multiplier'] *= 1.1  * (0.99 + 0.11*ula_df.low_bureau_flag)  * (0.978 + 0.172*ula_df.open_tl_flag)
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ~ula_df.soft_pull_flag,'loss_multiplier'] *= (1 * (0.98 + 0.22*ula_df.low_bureau_flag)  * (0.945 + 0.405*ula_df.open_tl_flag ) /np.maximum(ula_df.cd_perc_flag*ula_df.open_tl_flag*1.2,1))

        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) &  ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.97  + 0.15  * ula_df.cd_perc_flag
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.954 + 0.346 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1)         &  ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0   + 0.05  * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1)         & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0   + 0.10  * ula_df.cd_perc_flag


    if leave_out!='blanket adjustment':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] /= 1.1


    if leave_out!='Clip':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] = np.clip(ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'], 0.75, 1.4)

    return ula_df


def get_ula_multiplier_kmx_diag(ula_df, loss_scale=None, leave_out='None', verbose=True):
    """Identical logic to get_ula_multiplier_kmx, but also returns step-by-step loss_multiplier means and flag means."""
    if loss_scale is None:
        loss_scale = MODEL_PARAMS['kmx_loss_scale']
    steps = {}
    def _record(label, df):
        steps[label] = df.loss_multiplier.mean()

    ula_df['loss_multiplier'] = 1.0
    _record('00_initial', ula_df)
    if verbose:
        print(f"00_initial  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low FICO':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_fico_flag & ~ula_df.high_model_score_flag) \
                                    + loss_scale * (ula_df.low_fico_flag & ula_df.high_model_score_flag)
    _record('02_low_fico_3.0', ula_df)
    if verbose:
        print(f"02_low_fico | flag mean: {ula_df.low_fico_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low Vantage':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_vantage_flag & ~ula_df.high_model_score_flag) \
                                    + loss_scale * (ula_df.low_vantage_flag & ula_df.high_model_score_flag)
    _record('03_low_vantage_3.0', ula_df)
    if verbose:
        print(f"03_low_vant | flag mean: {ula_df.low_vantage_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High PTI':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0 * ula_df.normal_pti_flag \
                                    + 0.05 * ula_df.high_pti_tier_1_flag \
                                    + 0.1 * ula_df.high_pti_tier_2_flag \
                                    + (1.4 * (1 + loss_scale) - 1) * ula_df.high_pti_tier_3_flag
    _record('04_high_pti_3.0', ula_df)
    if verbose:
        print(f"04_high_pti | tier1: {ula_df.high_pti_tier_1_flag.mean():.6f}  tier2: {ula_df.high_pti_tier_2_flag.mean():.6f}  tier3: {ula_df.high_pti_tier_3_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] /= (1 + loss_scale)
    _record('07_loss_scale_div_3.0', ula_df)
    if verbose:
        print(f"07_scale_dv | dividing by (1 + {loss_scale})  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + (-0.01 + 0.06 * ula_df.secured_credit_flag) \
                                        * ~(~ula_df.job_time_flag & ula_df.narrowed_soft_pull_flag & ula_df.secured_credit_flag)
    _record('08_secured_credit_3.0', ula_df)
    if verbose:
        print(f"08_sec_cred | flag mean: {ula_df.secured_credit_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 0.99 + 0.18 * ula_df.kmx_auth_tradelines_flag
    _record('09_auth_tradelines_3.0', ula_df)
    if verbose:
        print(f"09_auth_tl  | flag mean: {ula_df.kmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= (
            1 + ~ula_df.job_time_flag * (~ula_df.narrowed_soft_pull_flag * -0.025
            + ula_df.narrowed_soft_pull_flag * (~ula_df.secured_credit_flag * 0.108
            + ula_df.secured_credit_flag * 0.295)))
    _record('11_soft_pull_3.0', ula_df)
    if verbose:
        print(f"11_soft_pll | flag mean: {ula_df.soft_pull_flag.mean():.6f}  narrowed: {ula_df.narrowed_soft_pull_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Fraud':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + (ula_df.fraud_adjustment - 1)
    _record('12_fraud_all', ula_df)
    if verbose:
        print(f"12_fraud    | fraud_adj mean: {ula_df.fraud_adjustment.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        clipped_multiplier = np.clip(ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'], 0.8, 1.35 / (1 + loss_scale))
        ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'] = clipped_multiplier
    _record('13_clip_3.0', ula_df)
    if verbose:
        print(f"13_clip_3.0 | clip [0.8, {1.35 / (1 + loss_scale):.4f}]  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Vehicle Age':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 0.8593 + 0.0201 * ula_df.continuous_vehicle_age
    _record('14_vehicle_age_3.0', ula_df)
    if verbose:
        print(f"14_veh_age  | continuous_age mean: {ula_df.continuous_vehicle_age.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'npc':
        ula_df.loc[ula_df.kmx_npc_flag, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.high_pti_npc
    _record('15_npc_all', ula_df)
    if verbose:
        print(f"15_npc      | npc_flag mean: {ula_df.kmx_npc_flag.mean():.6f}  high_pti_npc mean: {ula_df.high_pti_npc.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Student Loans':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.96 + 0.14 * ula_df.student_loan_flag
    _record('16_student_loans_all', ula_df)
    if verbose:
        print(f"16_stu_loan | flag mean: {ula_df.student_loan_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'high sales price':
        ula_df.loc[ula_df.mtn_model.isin([4.1]), 'loss_multiplier'] *= 0.98 + 0.22 * ula_df.high_sales_price_flag
    _record('17_high_sales_price_4.1', ula_df)
    if verbose:
        print(f"17_hi_price | flag mean: {ula_df.high_sales_price_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Driver flag':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.15 * ula_df.driver_flag
    _record('18_driver_flag_all', ula_df)
    if verbose:
        print(f"18_driver   | flag mean: {ula_df.driver_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Louisiana':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.35 * ula_df.louisiana_flag
    _record('19_louisiana_all', ula_df)
    if verbose:
        print(f"19_louisiana| flag mean: {ula_df.louisiana_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'georgia':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.1 * ula_df.georgia_flag
    _record('20_georgia_all', ula_df)
    if verbose:
        print(f"20_georgia  | flag mean: {ula_df.georgia_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'txca':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score > 140), 'loss_multiplier'] *= 1 - 0.1 * ula_df.txca_flag
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score <= 140) & (ula_df.cd_model_score >= 135), 'loss_multiplier'] *= 1 - 0.05 * ula_df.txca_flag
    _record('21_txca_all', ula_df)
    if verbose:
        print(f"21_txca     | flag mean: {ula_df.txca_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'state_counter_adj':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score < 150) & ~(ula_df.louisiana_flag | ula_df.georgia_flag | ula_df.txca_flag), 'loss_multiplier'] *= 1.012
    _record('22_state_counter_all', ula_df)
    if verbose:
        no_state_adj = ((~ula_df.louisiana_flag) & (~ula_df.georgia_flag) & (~ula_df.txca_flag)).mean()
        print(f"22_st_cntr  | no state adj: {no_state_adj:.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.96 + (0.01 * ula_df.soft_pull_flag - 0.18 * ula_df.chime_flag * ula_df.soft_pull_flag) + 0.46 * ula_df.chime_flag
    _record('23_secured_credit_3.1+', ula_df)
    if verbose:
        print(f"23_sec_cr31 | chime mean: {ula_df.chime_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Job time':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.21 * ula_df.job_time_flag
    _record('24_job_time_3.1+', ula_df)
    if verbose:
        print(f"24_job_t_31 | flag mean: {ula_df.job_time_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Existing DQ':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.existing_dq_flag
    _record('25_existing_dq_3.1+', ula_df)
    if verbose:
        print(f"25_dq_31    | flag mean: {ula_df.existing_dq_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Employment type':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.1 * ula_df.seasonal_employment_flag
    _record('26_employment_3.1+', ula_df)
    if verbose:
        print(f"26_emp_31   | seasonal: {ula_df.seasonal_employment_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.06 * ula_df.kmx_auth_tradelines_flag
    _record('27_auth_tradelines_3.1+', ula_df)
    if verbose:
        print(f"27_auth_31  | flag mean: {ula_df.kmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.1 * (0.99 + 0.11 * ula_df.low_bureau_flag) * (0.978 + 0.172 * ula_df.open_tl_flag)
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= (1 * (0.98 + 0.22 * ula_df.low_bureau_flag) * (0.945 + 0.405 * ula_df.open_tl_flag) / np.maximum(ula_df.cd_perc_flag * ula_df.open_tl_flag * 1.2, 1))

        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.97 + 0.15 * ula_df.cd_perc_flag
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.954 + 0.346 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1) & ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0 + 0.05 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0 + 0.10 * ula_df.cd_perc_flag
    _record('28_soft_pull_3.1+', ula_df)
    if verbose:
        mtn31_mask = ula_df.mtn_model.isin([3.1, 3.2, 4.1])
        print(f"28_soft_31  | soft_pull: {ula_df.soft_pull_flag.mean():.6f}  low_bureau: {ula_df.low_bureau_flag.mean():.6f}  cd_perc: {ula_df.cd_perc_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'blanket adjustment':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] /= 1.1
    _record('28b_blanket_3.1+', ula_df)
    if verbose:
        print(f"28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] = np.clip(ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'], 0.75, 1.4)
    _record('29_final_clip_3.1+', ula_df)
    if verbose:
        print(f"29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")
        print("\n--- Per MTN Model Means ---")
        for model in [3.0, 3.1, 3.2, 4.1]:
            mean_val = ula_df.loc[ula_df.mtn_model == model, 'loss_multiplier'].mean()
            count_val = (ula_df.mtn_model == model).sum()
            print(f"mtn_model {model}: mean loss_multiplier = {mean_val:.6f}  (n={count_val})")

    n = len(ula_df)
    flags = {
        'job_time_flag': ula_df.job_time_flag.mean(),
        'low_fico_flag': ula_df.low_fico_flag.mean(),
        'high_model_score_flag': ula_df.high_model_score_flag.mean(),
        'low_vantage_flag': ula_df.low_vantage_flag.mean(),
        'normal_pti_flag': ula_df.normal_pti_flag.mean(),
        'high_pti_tier_1_flag': ula_df.high_pti_tier_1_flag.mean(),
        'high_pti_tier_2_flag': ula_df.high_pti_tier_2_flag.mean(),
        'high_pti_tier_3_flag': ula_df.high_pti_tier_3_flag.mean(),
        'existing_dq_flag': ula_df.existing_dq_flag.mean(),
        'seasonal_employment_flag': ula_df.seasonal_employment_flag.mean(),
        'secured_credit_flag': ula_df.secured_credit_flag.mean(),
        'kmx_auth_tradelines_flag': ula_df.kmx_auth_tradelines_flag.mean(),
        'null_fico_w_vantage_flag': ula_df.null_fico_w_vantage_flag.mean(),
        'null_fico_null_vantage_flag': ula_df.null_fico_null_vantage_flag.mean(),
        'soft_pull_flag': ula_df.soft_pull_flag.mean(),
        'narrowed_soft_pull_flag': ula_df.narrowed_soft_pull_flag.mean(),
        'fraud_adjustment_mean': ula_df.fraud_adjustment.mean(),
        'continuous_vehicle_age_mean': ula_df.continuous_vehicle_age.mean(),
        'kmx_npc_flag': ula_df.kmx_npc_flag.mean(),
        'high_pti_npc': ula_df.high_pti_npc.mean(),
        'student_loan_flag': ula_df.student_loan_flag.mean(),
        'high_sales_price_flag': ula_df.high_sales_price_flag.mean(),
        'driver_flag': ula_df.driver_flag.mean(),
        'louisiana_flag': ula_df.louisiana_flag.mean(),
        'georgia_flag': ula_df.georgia_flag.mean(),
        'txca_flag': ula_df.txca_flag.mean(),
        'chime_flag': ula_df.chime_flag.mean(),
        'low_bureau_flag': ula_df.low_bureau_flag.mean(),
        'cd_perc_flag': ula_df.cd_perc_flag.mean(),
        'open_tl_flag': ula_df.open_tl_flag.mean(),
        'mtn_3_1_flag': ula_df.mtn_3_1_flag.mean(),
        'mtn_model_3.0_pct': (ula_df.mtn_model == 3.0).mean(),
        'mtn_model_3.1_pct': (ula_df.mtn_model == 3.1).mean(),
        'mtn_model_3.2_pct': (ula_df.mtn_model == 3.2).mean(),
        'mtn_model_4.1_pct': (ula_df.mtn_model == 4.1).mean(),
    }

    return ula_df, pd.Series(steps), pd.Series(flags)

In [6]:
mean_unit_loss = MODEL_PARAMS['mean_unit_loss']
unit_loss_to_model_score = MODEL_PARAMS['unit_loss_to_model_score']


def get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config, leave_out='None'):
    """Core RAGU Score calculation for a single vintage and individual LOB."""
    baseline_ltv = baseline_config['ltv']
    new_baseline_recovery_unadjusted_pct = baseline_config['new_recovery_unadjusted']
    baseline_apr = baseline_config['apr']
    ltv_mult = 17 / 0.65 if lob == 'KMX' else 17
    apr_mult = 0.7 / 0.65 if lob == 'KMX' else 0.7

    ula_df = ula_df_total[(ula_df_total.vintage == vintage) & (ula_df_total.lob == lob)].copy()

    if len(ula_df) == 0:
        return None

    if lob == 'KMX':
        ula_df = get_ula_multiplier_kmx(ula_df, leave_out=leave_out)
    else:
        raise ValueError("This notebook only supports KMX")

    ula_df = ula_df[['account_number', date_col, 'bbvalue', 'sale_price', 'amt_financed', 'lob_or_bucket', 'lob', 'loss_multiplier', 'apr']]

    nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(subset='account_number', keep='first')
    mix_df = ula_df.merge(nr.rename(columns={'new_recovery_multiplier': 'recovery_multiplier'}),
                          on='account_number', how='left').drop_duplicates(subset='account_number', keep='first')

    mix_df['ltv'] = mix_df.amt_financed / mix_df.bbvalue

    bb_populated_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0)]
    if len(bb_populated_df) == 0:
        return None

    full_pop_metrics = bb_populated_df.groupby('lob').apply(
        weighted_average_and_sum,
        ['loss_multiplier', 'ltv', 'bbvalue', 'apr'],
        include_groups=False
    )

    recovery_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0) & mix_df['recovery_multiplier'].notna()]
    recovery_df = recovery_df.copy()
    recovery_df['recovery_unadjusted_multiplier'] = recovery_df['recovery_multiplier']
    recovery_metrics = recovery_df.groupby('lob').apply(
        weighted_average_and_sum,
        ['recovery_unadjusted_multiplier'],
        include_groups=False
    )
    recovery_metrics = recovery_metrics.drop(columns='amt_financed')

    grouped_mix_df = full_pop_metrics.join(recovery_metrics)

    vintage_ms_df = ms_df[ms_df['period'] == vintage].copy()

    index_name = grouped_mix_df.index.name
    if isinstance(index_name, str) and index_name in grouped_mix_df.columns:
        grouped_mix_df = grouped_mix_df.reset_index(drop=True)
    else:
        grouped_mix_df = grouped_mix_df.reset_index()

    full_df = grouped_mix_df.merge(vintage_ms_df, on='lob')

    if len(full_df) == 0:
        return None

    full_df['est_unit_loss'] = mean_unit_loss
    full_df['unit_loss_score'] = full_df.model_score + (1 - full_df.loss_multiplier) * full_df.est_unit_loss / unit_loss_to_model_score
    full_df = full_df.set_index('lob')

    full_df['ms_original'] = full_df.model_score.copy()
    full_df['baselined_unadjusted_recovery'] = (full_df.recovery_unadjusted_multiplier / new_baseline_recovery_unadjusted_pct).copy()

    full_df['gross_loss_impact'] = full_df['unit_loss_score'] - full_df['ms_original']
    full_df['recovery_impact'] = (full_df['unit_loss_score'] * full_df['est_unit_loss']
        * full_df['recovery_unadjusted_multiplier'] * (full_df['baselined_unadjusted_recovery'] - 1))
    full_df['ltv_impact'] = ((baseline_ltv / full_df['ltv']) - 1) * ltv_mult
    full_df['apr_impact'] = (baseline_apr - full_df['apr']) / 0.01 * apr_mult
    full_df['ragu_score'] = (
        (1 - full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier) * full_df.unit_loss_score
        + full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier
        * full_df.unit_loss_score * full_df.baselined_unadjusted_recovery
        + full_df['ltv_impact']
        + full_df['apr_impact'])

    full_df['vintage'] = vintage
    return full_df

In [7]:
# Filter out Core LOB
ula_df_total = ula_df_total[ula_df_total.lob != 'Core']

# Ensure date columns are proper types
ula_df_total['app_date'] = pd.to_datetime(ula_df_total['app_date'])
ula_df_total['book_date'] = pd.to_datetime(ula_df_total['book_date'])
new_recovery['app_date'] = pd.to_datetime(new_recovery['app_date'])
new_recovery['book_date'] = pd.to_datetime(new_recovery['book_date'])

# Assign period columns using pd.to_period
for df in [ula_df_total, new_recovery]:
    df['quarter'] = pd.to_datetime(df[date_col]).dt.to_period('Q')
    df['month'] = pd.to_datetime(df[date_col]).dt.to_period('M')
    df['week'] = pd.to_datetime(df[date_col]).dt.to_period('W-SAT')
    period_key = {'q': 'quarter', 'm': 'month', 'w': 'week'}
    df['period'] = df[period_key[granularity]]

# Filter to configured date range
for df in [ula_df_total, new_recovery]:
    mask = (df['period'] >= start_period) & (df['period'] <= end_period)
    df.drop(df[~mask].index, inplace=True)

# Convert week columns to str for compatibility
for df in [ula_df_total, new_recovery]:
    df['book_week'] = df['book_week'].astype(str)
    df['app_week'] = df['app_week'].astype(str)

# String version of date_col for flag comparisons
date_col_str = f'{date_col}_str'
ula_df_total[date_col_str] = ula_df_total[date_col].astype(str)

ula_df_total['mtn_3_1_flag'] = ula_df_total.mtn_model == 'MTN3.1'
ula_df_total['vehicle_age'] = np.maximum(ula_df_total[date_col_str].str[:4].astype(int) - ula_df_total.model_year, 1/365)
ula_df_total.tradein_value = ula_df_total.tradein_value.fillna(0)
ula_df_total.make = ula_df_total.make.str.upper().str[:3]
ula_df_total.lob_or_bucket = np.select([ula_df_total.lob_or_bucket.isna() & ula_df_total.lob.isin(['Core', 'FRN']),
                                      ula_df_total.lob_or_bucket.isna() & ~ula_df_total.lob.isin(['Core', 'FRN'])],
                                     ['D', 'C'], default=ula_df_total.lob_or_bucket)
ula_df_total['continuous_vehicle_age'] = (ula_df_total[date_col_str].str[:4].astype(int)
    + ula_df_total[date_col_str].str[5:7].astype(int) / 12
    - (ula_df_total.model_year - 0.25) - 1)

# Driver flag
warnings.filterwarnings('ignore', category=UserWarning)
ula_df_total.job_company = ula_df_total.job_company.fillna('not provided')
ula_df_total['driver_flag'] = np.where(
    ula_df_total.job_company.str.contains('(LYFT)|(UBER)|(GRUB ?HUB)|(DOOR ?DASH)|(GO ?PUFF)|(POST ?MATE)|(INSTA ?CART)|(DOMINO)|(PAPA J)|(PIZZA)|(JIMMY ?JOHN)|(SELF)'),
    1, 0)
warnings.filterwarnings('default', category=UserWarning)

# Handle NA values
ula_df_total = ula_df_total.dropna(subset=['sale_price', 'cd_model_score', 'pti', 'lob'])
ula_df_total.cash_down = ula_df_total.cash_down.fillna(0)
ula_df_total.specialty_dealer = ula_df_total.specialty_dealer.fillna('not specialty')
ula_df_total.prev_co_count = ula_df_total.prev_co_count.fillna(0)

# Weekly-matching filters
ula_df_total['bbltv'] = ula_df_total.amt_financed / ula_df_total.bbvalue.replace(0, np.nan)
ula_df_total = ula_df_total[ula_df_total.amt_financed <= 75000]
ula_df_total = ula_df_total[ula_df_total.pti <= 0.6]
ula_df_total = ula_df_total[
    (ula_df_total.lob == 'MCY') |
    (ula_df_total.bbltv <= 10.0) |
    (ula_df_total.bbvalue.isna()) |
    (ula_df_total.bbvalue == 0)
]
ula_df_total = ula_df_total[ula_df_total.total_income <= 200000]

# KMX Flags
ula_df_total['secured_credit_flag'] = ula_df_total.secured_credit_card
ula_df_total['chime_flag'] = ula_df_total.chime_indicator
ula_df_total['seasonal_employment_flag'] = ula_df_total['seasonal_employment_flag'] == 1
ula_df_total['waiter_employment_flag'] = ula_df_total['waiter_employment_flag'] == 1
ula_df_total['null_fico_w_vantage_flag'] = ((ula_df_total.fico_score < 300) | (ula_df_total.fico_score > 850)) & (ula_df_total.vantage_score >= 300) & (ula_df_total.vantage_score <= 850)
ula_df_total['null_fico_null_vantage_flag'] = ((ula_df_total.fico_score < 300) | (ula_df_total.fico_score > 850)) & ((ula_df_total.vantage_score < 300) | (ula_df_total.vantage_score > 850))
ula_df_total['student_loan_flag'] = np.where(ula_df_total.student_loan_flag == 1, 1, 0)
ula_df_total['high_sales_price_flag'] = ula_df_total.sale_price > 30000
ula_df_total['kmx_npc_flag'] = ula_df_total.kmx_npc_flag == 1
ula_df_total['high_pti_npc'] = ula_df_total.pti > 0.2
ula_df_total['job_time_flag'] = ula_df_total.employed_months < 6
ula_df_total['low_fico_flag'] = (ula_df_total.fico_score > 300) & (ula_df_total.fico_score < 450)
ula_df_total['high_model_score_flag'] = ula_df_total.cd_model_score >= 146
ula_df_total['low_vantage_flag'] = (ula_df_total.fico_score < 300) & (ula_df_total.vantage_score > 4) & (ula_df_total.vantage_score < 450)
ula_df_total['louisiana_flag'] = ula_df_total.state == 'LA'
ula_df_total['txca_flag'] = ula_df_total.state.isin(['TX', 'CA'])
ula_df_total['georgia_flag'] = ula_df_total.state == 'GA'
ula_df_total['normal_pti_flag'] = ula_df_total.pti <= 0.2
ula_df_total['high_pti_tier_1_flag'] = (ula_df_total.pti > 0.2) & (ula_df_total.pti <= 0.25)
ula_df_total['high_pti_tier_2_flag'] = (ula_df_total.pti > 0.25) & (ula_df_total.pti <= 0.35)
ula_df_total['high_pti_tier_3_flag'] = ula_df_total.pti > 0.35
ula_df_total['existing_dq_flag'] = ula_df_total.existing_dq_count > 0
ula_df_total['kmx_toyho_flag'] = (ula_df_total.cd_model_score >= 130) & ula_df_total.make.isin({'HON', 'TOY'})
ula_df_total['kmx_auth_tradelines_flag'] = ula_df_total.pct_auth_tradelines >= 0.14
ula_df_total['low_bureau_flag'] = ((ula_df_total.fico_score > 300) & (ula_df_total.fico_score < 475)) | ((ula_df_total.vantage_score > 4) & (ula_df_total.vantage_score < 475))
ula_df_total['soft_pull_flag'] = ula_df_total.pull_type.isin(['softpull', 'prequal'])
ula_df_total['cd_perc_flag'] = (ula_df_total.sale_price <= 18000) & (ula_df_total.cash_down / ula_df_total.sale_price <= 0.1)
ula_df_total['open_tl_flag'] = ula_df_total.open_tl == 0
ula_df_total['narrowed_soft_pull_flag'] = (ula_df_total.sale_price <= 18000) & (ula_df_total.cash_down / ula_df_total.sale_price <= 0.1) & ula_df_total.soft_pull_flag & (~ula_df_total.job_time_flag)
ula_df_total['prev_co_flag'] = ula_df_total.prev_co_count > 0

# Deduplicate driver flags
combined_driver_flag_df = ula_df_total.groupby('account_number').driver_flag.max().reset_index()
ula_df_total = ula_df_total.drop(columns='driver_flag').merge(combined_driver_flag_df, on='account_number')
ula_df_total = ula_df_total.drop(columns='job_company').drop_duplicates()

# Vintage assignment
ula_df_total['vintage'] = format_vintage(ula_df_total['period'])
new_recovery['vintage'] = format_vintage(new_recovery['period'])

# Filter to KMX only
ula_df_total = ula_df_total[ula_df_total.lob == 'KMX'].copy()
new_recovery = new_recovery[new_recovery.lob == 'KMX'].copy()

# MTN 4.1 model score transformation (applied in-place to ULA source)
is_mtn41 = ula_df_total.mtn_model == 4.1
ula_df_total.loc[is_mtn41, 'cd_model_score'] = (
    142 + (ula_df_total.loc[is_mtn41, 'cd_model_score'] - 142) * 1.5
)

# Aggregate model scores from ULA data (same source as ltv/apr)
ms_df = ula_df_total.groupby(['period', 'lob']).apply(
    weighted_average_and_sum, 'cd_model_score', include_groups=False
).reset_index()
ms_df = ms_df.rename(columns={'cd_model_score': 'model_score'})
ms_df['period'] = format_vintage(ms_df['period'])

print(f'Data loaded: {len(ula_df_total)} ULA rows')
print(f'MTN model distribution:\n{ula_df_total.mtn_model.value_counts().sort_index()}')
print(f'ms_df: {len(ms_df)} rows')
print(f'Available KMX vintages: {sorted(ula_df_total.vintage.unique())}')

Data loaded: 31654 ULA rows
MTN model distribution:
mtn_model
3.0      246
3.1    17503
3.2    10682
4.1     3223
Name: count, dtype: int64
ms_df: 21 rows
Available KMX vintages: ['2025-11-30/2025-12-06', '2025-12-07/2025-12-13', '2025-12-14/2025-12-20', '2025-12-21/2025-12-27', '2025-12-28/2026-01-03', '2026-01-04/2026-01-10', '2026-01-11/2026-01-17', '2026-01-18/2026-01-24', '2026-01-25/2026-01-31', '2026-02-01/2026-02-07', '2026-02-08/2026-02-14', '2026-02-15/2026-02-21', '2026-02-22/2026-02-28', '2026-03-01/2026-03-07', '2026-03-08/2026-03-14', '2026-03-15/2026-03-21', '2026-03-22/2026-03-28', '2026-03-29/2026-04-04', '2026-04-05/2026-04-11', '2026-04-12/2026-04-18', '2026-04-19/2026-04-25']

In [8]:
baseline_config = BASELINES['KMX']

results_by_model = {}

all_vintages = sorted(ula_df_total['vintage'].unique())

for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    print(f'\n{"="*60}')
    print(f'  Processing: {label}')
    print(f'{"="*60}')

    # Filter DataFrames by MTN model
    if mtn_model_filter == 'All KMX':
        ula_filtered = ula_df_total.copy()
        new_rec_filtered = new_recovery.copy()
        ms_filtered = ms_df.copy()
    else:
        mtn_accounts = set(ula_df_total[ula_df_total.mtn_model == mtn_model_filter].account_number)
        ula_filtered = ula_df_total[ula_df_total.mtn_model == mtn_model_filter].copy()
        new_rec_filtered = new_recovery[new_recovery.account_number.isin(mtn_accounts)].copy()
        ms_filtered = rebuild_ms_df(ula_filtered)

    n_loans = len(ula_filtered)
    if n_loans == 0:
        print(f'  No loans found for {label}, skipping.')
        results_by_model[mtn_model_filter] = pd.DataFrame()
        continue

    print(f'  Loans: {n_loans}')

    full_df_list = []
    vintages_processed = []

    for vintage in all_vintages:
        n_vintage = len(ula_filtered[ula_filtered.vintage == vintage])
        if n_vintage == 0:
            continue

        print(f'  {vintage} KMX ({label}, n={n_vintage})')
        full_df = get_ragu_score(vintage, 'KMX', ula_filtered, new_rec_filtered, ms_filtered, baseline_config)
        if full_df is not None:
            full_df_list.append(full_df)
            vintages_processed.append(vintage)

    if full_df_list:
        all_df = pd.concat(full_df_list)
        results_by_model[mtn_model_filter] = all_df
        print(f'\n  {label}: {len(vintages_processed)} vintages processed')
    else:
        results_by_model[mtn_model_filter] = pd.DataFrame()
        print(f'\n  {label}: No vintages had data')

print(f'\n{"="*60}')
print('  All models processed.')
print(f'{"="*60}')
print("[PROGRESS] Scoring Complete")

============================================================
  Processing: MTN 3.0
============================================================
  Loans: 246
  2025-11-30/2025-12-06 KMX (MTN 3.0, n=246)

  MTN 3.0: 1 vintages processed

============================================================
  Processing: MTN 3.1
============================================================

  Loans: 17503
  2025-11-30/2025-12-06 KMX (MTN 3.1, n=674)
  2025-12-07/2025-12-13 KMX (MTN 3.1, n=965)

  2025-12-14/2025-12-20 KMX (MTN 3.1, n=1141)

  2025-12-21/2025-12-27 KMX (MTN 3.1, n=790)
  2025-12-28/2026-01-03 KMX (MTN 3.1, n=1060)
  2026-01-04/2026-01-10 KMX (MTN 3.1, n=1124)

  2026-01-11/2026-01-17 KMX (MTN 3.1, n=1149)
  2026-01-18/2026-01-24 KMX (MTN 3.1, n=1125)
  2026-01-25/2026-01-31 KMX (MTN 3.1, n=909)

  2026-02-01/2026-02-07 KMX (MTN 3.1, n=1105)
  2026-02-08/2026-02-14 KMX (MTN 3.1, n=1134)
  2026-02-15/2026-02-21 KMX (MTN 3.1, n=987)

  2026-02-22/2026-02-28 KMX (MTN 3.1, n=1274)
  2026-03-01/2026-03-07 KMX (MTN 3.1, n=1002)

  2026-03-08/2026-03-14 KMX (MTN 3.1, n=917)
  2026-03-15/2026-03-21 KMX (MTN 3.1, n=746)

  2026-03-22/2026-03-28 KMX (MTN 3.1, n=691)
  2026-03-29/2026-04-04 KMX (MTN 3.1, n=624)
  2026-04-05/2026-04-11 KMX (MTN 3.1, n=86)

  MTN 3.1: 19 vintages processed

============================================================
  Processing: MTN 3.2
============================================================
  Loans: 10682
  2026-01-25/2026-01-31 KMX (MTN 3.2, n=83)
  2026-02-01/2026-02-07 KMX (MTN 3.2, n=133)
  2026-02-08/2026-02-14 KMX (MTN 3.2, n=134)

  2026-02-15/2026-02-21 KMX (MTN 3.2, n=847)
  2026-02-22/2026-02-28 KMX (MTN 3.2, n=1830)
  2026-03-01/2026-03-07 KMX (MTN 3.2, n=1330)

  2026-03-08/2026-03-14 KMX (MTN 3.2, n=1274)
  2026-03-15/2026-03-21 KMX (MTN 3.2, n=936)
  2026-03-22/2026-03-28 KMX (MTN 3.2, n=870)
  2026-03-29/2026-04-04 KMX (MTN 3.2, n=833)

  2026-04-05/2026-04-11 KMX (MTN 3.2, n=1055)
  2026-04-12/2026-04-18 KMX (MTN 3.2, n=1080)
  2026-04-19/2026-04-25 KMX (MTN 3.2, n=277)

  MTN 3.2: 13 vintages processed

============================================================
  Processing: MTN 4.1
============================================================
  Loans: 3223
  2025-12-14/2025-12-20 KMX (MTN 4.1, n=74)
  2025-12-21/2025-12-27 KMX (MTN 4.1, n=125)
  2025-12-28/2026-01-03 KMX (MTN 4.1, n=142)

  2026-01-04/2026-01-10 KMX (MTN 4.1, n=167)
  2026-01-11/2026-01-17 KMX (MTN 4.1, n=171)
  2026-01-18/2026-01-24 KMX (MTN 4.1, n=154)
  2026-01-25/2026-01-31 KMX (MTN 4.1, n=140)
  2026-02-01/2026-02-07 KMX (MTN 4.1, n=160)

  2026-02-08/2026-02-14 KMX (MTN 4.1, n=159)
  2026-02-15/2026-02-21 KMX (MTN 4.1, n=204)
  2026-02-22/2026-02-28 KMX (MTN 4.1, n=305)
  2026-03-01/2026-03-07 KMX (MTN 4.1, n=267)
  2026-03-08/2026-03-14 KMX (MTN 4.1, n=251)

  2026-03-15/2026-03-21 KMX (MTN 4.1, n=194)
  2026-03-22/2026-03-28 KMX (MTN 4.1, n=206)
  2026-03-29/2026-04-04 KMX (MTN 4.1, n=178)
  2026-04-05/2026-04-11 KMX (MTN 4.1, n=150)
  2026-04-12/2026-04-18 KMX (MTN 4.1, n=141)
  2026-04-19/2026-04-25 KMX (MTN 4.1, n=35)

  MTN 4.1: 19 vintages processed

============================================================
  Processing: All KMX
============================================================
  Loans: 31654
  2025-11-30/2025-12-06 KMX (All KMX, n=920)
  2025-12-07/2025-12-13 KMX (All KMX, n=965)
  2025-12-14/2025-12-20 KMX (All KMX, n=1215)

  2025-12-21/2025-12-27 KMX (All KMX, n=915)
  2025-12-28/2026-01-03 KMX (All KMX, n=1202)
  2026-01-04/2026-01-10 KMX (All KMX, n=1291)
  2026-01-11/2026-01-17 KMX (All KMX, n=1320)

  2026-01-18/2026-01-24 KMX (All KMX, n=1279)
  2026-01-25/2026-01-31 KMX (All KMX, n=1132)
  2026-02-01/2026-02-07 KMX (All KMX, n=1398)
  2026-02-08/2026-02-14 KMX (All KMX, n=1427)

  2026-02-15/2026-02-21 KMX (All KMX, n=2038)
  2026-02-22/2026-02-28 KMX (All KMX, n=3409)
  2026-03-01/2026-03-07 KMX (All KMX, n=2599)
  2026-03-08/2026-03-14 KMX (All KMX, n=2442)

  2026-03-15/2026-03-21 KMX (All KMX, n=1876)
  2026-03-22/2026-03-28 KMX (All KMX, n=1767)
  2026-03-29/2026-04-04 KMX (All KMX, n=1635)
  2026-04-05/2026-04-11 KMX (All KMX, n=1291)

  2026-04-12/2026-04-18 KMX (All KMX, n=1221)
  2026-04-19/2026-04-25 KMX (All KMX, n=312)

  All KMX: 21 vintages processed

============================================================
  All models processed.
============================================================
[PROGRESS] Scoring Complete

In [9]:
"""
Diagnostics: Run get_ula_multiplier_kmx_diag for each MTN model and for All KMX combined.
Produces step-by-step loss_multiplier traces and flag means per vintage.
"""

def build_output_df(results, wtd_mults, record_counts, ragu_gli_dict=None):
    """Helper to build multiplier steps and summary DataFrame."""
    if not results:
        return None
    step_names = list(next(iter(results.values())).keys())
    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        col_data[col_name] = [step_dict.get(s) for s in step_names]
    diag_df = pd.DataFrame(col_data, index=step_names)
    summary = {}
    for (lob, vintage) in results.keys():
        col = f"{lob} | {vintage}"
        final_mult_mean = diag_df[col].iloc[-1]
        wtd_mult = wtd_mults.get((lob, vintage), float('nan'))
        if ragu_gli_dict is not None:
            gross_loss_impact = ragu_gli_dict.get((lob, vintage), 25 * (1 - wtd_mult))
        else:
            gross_loss_impact = 25 * (1 - wtd_mult)
        summary[col] = {
            '--- FINAL_MULT (mean)': final_mult_mean,
            '--- WTD_MULT_RAGU': wtd_mult,
            '--- GROSS_LOSS_IMPACT': gross_loss_impact,
            '--- N_RECORDS': record_counts.get((lob, vintage), 0),
        }
    summary_df = pd.DataFrame(summary)
    return pd.concat([diag_df, summary_df])

def build_flags_df(flag_results, record_counts):
    """Helper to build flag means DataFrame."""
    if not flag_results:
        return None
    flag_names = list(next(iter(flag_results.values())).keys())
    flag_col_data = {}
    for (lob, vintage), flag_dict in flag_results.items():
        col_name = f"{lob} | {vintage}"
        flag_col_data[col_name] = [flag_dict.get(f) for f in flag_names]
    flags_df = pd.DataFrame(flag_col_data, index=flag_names)
    n_row = {}
    for (lob, vintage) in flag_results.keys():
        n_row[f"{lob} | {vintage}"] = record_counts.get((lob, vintage), 0)
    flags_df.loc['--- N_RECORDS'] = n_row
    return flags_df


STEP_LABEL_MAP = {
    '00_initial':              'Initial (1.0)',
    '02_low_fico_3.0':         'Low FICO (3.0)',
    '03_low_vantage_3.0':      'Low Vantage (3.0)',
    '04_high_pti_3.0':         'High PTI (3.0)',
    '07_loss_scale_div_3.0':   'Loss Scale Div (3.0)',
    '08_secured_credit_3.0':   'Secured Credit (3.0)',
    '09_auth_tradelines_3.0':  'Auth Tradelines (3.0)',
    '11_soft_pull_3.0':        'Soft Pull (3.0)',
    '12_fraud_all':            'Fraud Adjustment',
    '13_clip_3.0':             'Clip (3.0)',
    '14_vehicle_age_3.0':      'Vehicle Age (3.0)',
    '15_npc_all':              'NPC',
    '16_student_loans_all':    'Student Loans',
    '17_high_sales_price_4.1': 'High Sales Price (4.1)',
    '18_driver_flag_all':      'Driver Flag',
    '19_louisiana_all':        'Louisiana',
    '20_georgia_all':          'Georgia',
    '21_txca_all':             'TX / CA',
    '22_state_counter_all':    'State Counter',
    '23_secured_credit_3.1+':  'Secured Credit / Chime (3.1+)',
    '24_job_time_3.1+':        'Job Time (3.1+)',
    '25_existing_dq_3.1+':     'Existing DQ (3.1+)',
    '26_employment_3.1+':      'Employment Type (3.1+)',
    '27_auth_tradelines_3.1+': 'Auth Tradelines (3.1+)',
    '28_soft_pull_3.1+':       'Soft Pull (3.1+)',
    '28b_blanket_3.1+':        'Blanket Adjustment (3.1+)',
    '29_final_clip_3.1+':      'Clip (3.1+)',
}


def build_attribution_df(results, ragu_gli_dict):
    """
    Decompose gross_loss_impact across multiplier steps using logarithmic attribution.

    For each vintage:
      1. Compute per-step ratios: r_i = step_i / step_{i-1}
      2. Log shares: ln(r_i) / ln(final_multiplier)  [proportional contribution]
      3. Attributed impact: share_i * gross_loss_impact

    gross_loss_impact is sourced from get_ragu_score output (results_by_model) to ensure
    the attribution decomposes the same value that appears in the RAGU score decomposition.

    When the final multiplier equals 1.0 (no net adjustment), all impacts are 0.
    """
    if not results:
        return None

    step_keys = list(next(iter(results.values())).keys())
    adjustment_keys = [k for k in step_keys if k != '00_initial']
    readable_labels = [STEP_LABEL_MAP.get(k, k) for k in adjustment_keys]

    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        gross_loss_impact = ragu_gli_dict.get((lob, vintage), float('nan'))

        cumulative = [step_dict.get(k, float('nan')) for k in step_keys]
        ratios = []
        for i, k in enumerate(step_keys):
            if k == '00_initial':
                continue
            prev = cumulative[i - 1]
            curr = cumulative[i]
            if prev and prev != 0:
                ratios.append(curr / prev)
            else:
                ratios.append(1.0)

        import math
        final_mult = cumulative[-1]
        log_final = math.log(final_mult) if final_mult and final_mult > 0 and abs(final_mult - 1.0) > 1e-12 else None

        if log_final is None or pd.isna(gross_loss_impact):
            col_data[col_name] = [0.0] * len(adjustment_keys) + [gross_loss_impact if not pd.isna(gross_loss_impact) else 0.0]
        else:
            log_ratios = [math.log(r) if r and r > 0 else 0.0 for r in ratios]
            attributed = [(lr / log_final) * gross_loss_impact for lr in log_ratios]
            col_data[col_name] = attributed + [sum(attributed)]

    index_labels = readable_labels + ['--- TOTAL (check)']
    return pd.DataFrame(col_data, index=index_labels)

diag_results_by_model = {}

for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    
    if mtn_model_filter == 'All KMX':
        ula_diag_source = ula_df_total.copy()
    else:
        ula_diag_source = ula_df_total[ula_df_total.mtn_model == mtn_model_filter].copy()
    
    if len(ula_diag_source) == 0:
        print(f'\n{label}: No data for diagnostics, skipping.')
        diag_results_by_model[mtn_model_filter] = (None, None, None)
        continue
    
    # Build ragu_gli_dict from results_by_model for this MTN model
    ragu_gli_dict = {}
    model_df = results_by_model.get(mtn_model_filter)
    if model_df is not None and len(model_df) > 0:
        for _, row in model_df.reset_index().iterrows():
            ragu_gli_dict[('KMX', row['vintage'])] = row['gross_loss_impact']
    
    # Get the most recent vintages for diagnostics
    target_vintages = sorted(ula_diag_source.vintage.unique())[-6:]
    
    kmx_results = {}
    kmx_flag_results = {}
    kmx_wtd_mults = {}
    kmx_record_counts = {}
    
    print(f'\n{"="*60}')
    print(f'  DIAGNOSTICS: {label}')
    print(f'{"="*60}')
    
    for vintage in target_vintages:
        ula_vintage = ula_diag_source[ula_diag_source.vintage == vintage].copy()
        n = len(ula_vintage)
        if n == 0:
            continue
        
        print(f'\n{"="*60}')
        print(f'  KMX {vintage} ({label})  (n={n})')
        print(f'{"="*60}')
        
        ula_vintage_diag, steps, flags = get_ula_multiplier_kmx_diag(ula_vintage, loss_scale=MODEL_PARAMS['kmx_loss_scale'], leave_out='None', verbose=True)
        
        diag_mix = ula_vintage_diag[['account_number', 'bbvalue', 'amt_financed', 'loss_multiplier']].copy()
        nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(
            subset='account_number', keep='first')
        diag_mix = diag_mix.merge(nr, on='account_number', how='left').drop_duplicates(
            subset='account_number', keep='first')
        bb_pop = diag_mix[diag_mix['bbvalue'].notna() & (diag_mix['bbvalue'] > 0)]
        if len(bb_pop) > 0 and bb_pop.amt_financed.sum() > 0:
            wtd_mult = (bb_pop.loss_multiplier * bb_pop.amt_financed).sum() / bb_pop.amt_financed.sum()
        else:
            wtd_mult = float('nan')
        
        ragu_gli = ragu_gli_dict.get(('KMX', vintage), float('nan'))
        print(f"  bb_populated: {len(bb_pop)} / {n}  wtd_mult: {wtd_mult:.6f}  ragu_gli: {ragu_gli:.4f}")
        
        kmx_results[('KMX', vintage)] = steps.to_dict()
        kmx_flag_results[('KMX', vintage)] = flags.to_dict()
        kmx_wtd_mults[('KMX', vintage)] = wtd_mult
        kmx_record_counts[('KMX', vintage)] = n
    
    kmx_output_df = build_output_df(kmx_results, kmx_wtd_mults, kmx_record_counts, ragu_gli_dict)
    kmx_flags_df = build_flags_df(kmx_flag_results, kmx_record_counts)
    kmx_attribution_df = build_attribution_df(kmx_results, ragu_gli_dict)
    diag_results_by_model[mtn_model_filter] = (kmx_output_df, kmx_flags_df, kmx_attribution_df)

    if kmx_output_df is not None:
        print(f'\n--- {label} Multiplier Steps ---')
        display(kmx_output_df)
        print(f'\n--- {label} Flag Means ---')
        display(kmx_flags_df)
    if kmx_attribution_df is not None:
        print(f'\n--- {label} Gross Loss Attribution ---')
        display(kmx_attribution_df)

============================================================
  DIAGNOSTICS: MTN 3.0
============================================================

============================================================
  KMX 2025-11-30/2025-12-06 (MTN 3.0)  (n=246)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.012195  | loss_multiplier mean: 1.002305
04_high_pti | tier1: 0.109756  tier2: 0.036585  tier3: 0.000000  | loss_multiplier mean: 1.011451
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.947939
08_sec_cred | flag mean: 0.382114  | loss_multiplier mean: 0.958046
09_auth_tl  | flag mean: 0.036585  | loss_multiplier mean: 0.954776
11_soft_pll | flag mean: 0.849593  narrowed: 0.142276  | loss_multiplier mean: 0.932097
12_fraud    | fraud_adj mean: 1.009024  | loss_multiplier mean: 0.940293
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.938785
14_veh_age  | continuous_age mean: 5.513550  | loss_multiplier mean: 0.910912
15_npc      | npc_flag mean: 0.247967  high_pti_npc mean: 0.146341  | loss_multiplier mean: 0.912195
16_stu_loan | flag mean: 0.243902  | loss_multiplier mean: 0.906374
17_hi_price | flag mean: 0.093496  | loss_multiplier mean: 0.906374
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.906374
19_louisiana| flag mean: 0.012195  | loss_multiplier mean: 0.910499
20_georgia  | flag mean: 0.097561  | loss_multiplier mean: 0.919343
21_txca     | flag mean: 0.378049  | loss_multiplier mean: 0.898811
22_st_cntr  | no state adj: 0.512195  | loss_multiplier mean: 0.903753
23_sec_cr31 | chime mean: 0.195122  | loss_multiplier mean: 0.929668
24_job_t_31 | flag mean: 0.178862  | loss_multiplier mean: 0.956992
25_dq_31    | flag mean: 0.117886  | loss_multiplier mean: 0.959114
26_emp_31   | seasonal: 0.012195  | loss_multiplier mean: 0.960241
27_auth_31  | flag mean: 0.036585  | loss_multiplier mean: 0.960241
28_soft_31  | soft_pull: 0.849593  low_bureau: 0.044715  cd_perc: 0.195122  | loss_multiplier mean: 0.960241
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.960241
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.960241

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.960241  (n=246)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 246 / 246  wtd_mult: 0.945309  ragu_gli: 1.3673

--- MTN 3.0 Multiplier Steps ---

                         KMX | 2025-11-30/2025-12-06
00_initial                                  1.000000
02_low_fico_3.0                             1.000000
03_low_vantage_3.0                          1.002305
04_high_pti_3.0                             1.011451
07_loss_scale_div_3.0                       0.947939
08_secured_credit_3.0                       0.958046
09_auth_tradelines_3.0                      0.954776
11_soft_pull_3.0                            0.932097
12_fraud_all                                0.940293
13_clip_3.0                                 0.938785
14_vehicle_age_3.0                          0.910912
15_npc_all                                  0.912195
16_student_loans_all                        0.906374
17_high_sales_price_4.1                     0.906374
18_driver_flag_all                          0.906374
19_louisiana_all                            0.910499
20_georgia_all                              0.919343
21_txca_all                                 0.898811
22_state_counter_all                        0.903753
23_secured_credit_3.1+                      0.929668
24_job_time_3.1+                            0.956992
25_existing_dq_3.1+                         0.959114
26_employment_3.1+                          0.960241
27_auth_tradelines_3.1+                     0.960241
28_soft_pull_3.1+                           0.960241
28b_blanket_3.1+                            0.960241
29_final_clip_3.1+                          0.960241
--- FINAL_MULT (mean)                       0.960241
--- WTD_MULT_RAGU                           0.945309
--- GROSS_LOSS_IMPACT                       1.367279
--- N_RECORDS                             246.000000

--- MTN 3.0 Flag Means ---

                             KMX | 2025-11-30/2025-12-06
job_time_flag                                   0.178862
low_fico_flag                                   0.000000
high_model_score_flag                           0.227642
low_vantage_flag                                0.012195
normal_pti_flag                                 0.853659
high_pti_tier_1_flag                            0.109756
high_pti_tier_2_flag                            0.036585
high_pti_tier_3_flag                            0.000000
existing_dq_flag                                0.117886
seasonal_employment_flag                        0.012195
secured_credit_flag                             0.382114
kmx_auth_tradelines_flag                        0.036585
null_fico_w_vantage_flag                        0.922764
null_fico_null_vantage_flag                     0.056911
soft_pull_flag                                  0.849593
narrowed_soft_pull_flag                         0.142276
fraud_adjustment_mean                           1.009024
continuous_vehicle_age_mean                     5.513550
kmx_npc_flag                                    0.247967
high_pti_npc                                    0.146341
student_loan_flag                               0.243902
high_sales_price_flag                           0.093496
driver_flag                                     0.000000
louisiana_flag                                  0.012195
georgia_flag                                    0.097561
txca_flag                                       0.378049
chime_flag                                      0.195122
low_bureau_flag                                 0.044715
cd_perc_flag                                    0.195122
open_tl_flag                                    0.158537
mtn_3_1_flag                                    0.000000
mtn_model_3.0_pct                               1.000000
mtn_model_3.1_pct                               0.000000
mtn_model_3.2_pct                               0.000000
mtn_model_4.1_pct                               0.000000
--- N_RECORDS                                 246.000000

--- MTN 3.0 Gross Loss Attribution ---

                               KMX | 2025-11-30/2025-12-06
Low FICO (3.0)                                   -0.000000
Low Vantage (3.0)                                -0.077587
High PTI (3.0)                                   -0.306137
Loss Scale Div (3.0)                              2.185539
Secured Credit (3.0)                             -0.357410
Auth Tradelines (3.0)                             0.115216
Soft Pull (3.0)                                   0.810189
Fraud Adjustment                                 -0.295044
Clip (3.0)                                        0.054075
Vehicle Age (3.0)                                 1.015756
NPC                                              -0.047436
Student Loans                                     0.215751
High Sales Price (4.1)                           -0.000000
Driver Flag                                      -0.000000
Louisiana                                        -0.153014
Georgia                                          -0.325786
TX / CA                                           0.761178
State Counter                                    -0.184797
Secured Credit / Chime (3.1+)                    -0.952745
Job Time (3.1+)                                  -0.976243
Existing DQ (3.1+)                               -0.074648
Employment Type (3.1+)                           -0.039575
Auth Tradelines (3.1+)                           -0.000000
Soft Pull (3.1+)                                 -0.000000
Blanket Adjustment (3.1+)                        -0.000000
Clip (3.1+)                                      -0.000000
--- TOTAL (check)                                 1.367279

============================================================
  DIAGNOSTICS: MTN 3.1
============================================================

============================================================
  KMX 2026-03-01/2026-03-07 (MTN 3.1)  (n=1002)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.010978  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066866  tier2: 0.028942  tier3: 0.000998  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.500000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.034930  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.878244  narrowed: 0.087824  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.999810  | loss_multiplier mean: 0.999810
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.999810
14_veh_age  | continuous_age mean: 4.516966  | loss_multiplier mean: 0.999810
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.096806  | loss_multiplier mean: 0.999810
16_stu_loan | flag mean: 0.239521  | loss_multiplier mean: 0.993039
17_hi_price | flag mean: 0.119760  | loss_multiplier mean: 0.993039
18_driver   | flag mean: 0.000998  | loss_multiplier mean: 0.993183
19_louisiana| flag mean: 0.010978  | loss_multiplier mean: 0.996988
20_georgia  | flag mean: 0.093812  | loss_multiplier mean: 1.006434
21_txca     | flag mean: 0.325349  | loss_multiplier mean: 0.983091
22_st_cntr  | no state adj: 0.569860  | loss_multiplier mean: 0.988811
23_sec_cr31 | chime mean: 0.324351  | loss_multiplier mean: 1.053004
24_job_t_31 | flag mean: 0.124750  | loss_multiplier mean: 1.070157
25_dq_31    | flag mean: 0.127745  | loss_multiplier mean: 1.073940
26_emp_31   | seasonal: 0.004990  | loss_multiplier mean: 1.074420
27_auth_31  | flag mean: 0.034930  | loss_multiplier mean: 1.065866
28_soft_31  | soft_pull: 0.878244  low_bureau: 0.047904  cd_perc: 0.110778  | loss_multiplier mean: 1.129063
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.026421
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.022087

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.022087  (n=1002)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 995 / 1002  wtd_mult: 1.005738  ragu_gli: -0.1434

============================================================
  KMX 2026-03-08/2026-03-14 (MTN 3.1)  (n=917)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.013086  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066521  tier2: 0.026172  tier3: 0.002181  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.504907  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.039258  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.845147  narrowed: 0.073064  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.998561  | loss_multiplier mean: 0.998561
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.998561
14_veh_age  | continuous_age mean: 4.590513  | loss_multiplier mean: 0.998561
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.094875  | loss_multiplier mean: 0.998561
16_stu_loan | flag mean: 0.238822  | loss_multiplier mean: 0.991655
17_hi_price | flag mean: 0.114504  | loss_multiplier mean: 0.991655
18_driver   | flag mean: 0.001091  | loss_multiplier mean: 0.991798
19_louisiana| flag mean: 0.005453  | loss_multiplier mean: 0.993683
20_georgia  | flag mean: 0.085060  | loss_multiplier mean: 1.002154
21_txca     | flag mean: 0.296619  | loss_multiplier mean: 0.982034
22_st_cntr  | no state adj: 0.612868  | loss_multiplier mean: 0.988347
23_sec_cr31 | chime mean: 0.291167  | loss_multiplier mean: 1.044902
24_job_t_31 | flag mean: 0.099237  | loss_multiplier mean: 1.056533
25_dq_31    | flag mean: 0.128680  | loss_multiplier mean: 1.060420
26_emp_31   | seasonal: 0.008724  | loss_multiplier mean: 1.061289
27_auth_31  | flag mean: 0.039258  | loss_multiplier mean: 1.052996
28_soft_31  | soft_pull: 0.845147  low_bureau: 0.037077  cd_perc: 0.093784  | loss_multiplier mean: 1.110139
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.009217
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.005928

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.005928  (n=917)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 912 / 917  wtd_mult: 0.993398  ragu_gli: 0.1650

============================================================
  KMX 2026-03-15/2026-03-21 (MTN 3.1)  (n=746)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.029491  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.058981  tier2: 0.024129  tier3: 0.005362  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.489276  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.037534  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.865952  narrowed: 0.092493  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.989933  | loss_multiplier mean: 0.989933
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.989933
14_veh_age  | continuous_age mean: 4.554960  | loss_multiplier mean: 0.989933
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.088472  | loss_multiplier mean: 0.989933
16_stu_loan | flag mean: 0.253351  | loss_multiplier mean: 0.985112
17_hi_price | flag mean: 0.148794  | loss_multiplier mean: 0.985112
18_driver   | flag mean: 0.001340  | loss_multiplier mean: 0.985305
19_louisiana| flag mean: 0.006702  | loss_multiplier mean: 0.987542
20_georgia  | flag mean: 0.061662  | loss_multiplier mean: 0.993687
21_txca     | flag mean: 0.340483  | loss_multiplier mean: 0.968633
22_st_cntr  | no state adj: 0.591153  | loss_multiplier mean: 0.974588
23_sec_cr31 | chime mean: 0.290885  | loss_multiplier mean: 1.027950
24_job_t_31 | flag mean: 0.112601  | loss_multiplier mean: 1.042186
25_dq_31    | flag mean: 0.139410  | loss_multiplier mean: 1.047019
26_emp_31   | seasonal: 0.009383  | loss_multiplier mean: 1.047966
27_auth_31  | flag mean: 0.037534  | loss_multiplier mean: 1.039659
28_soft_31  | soft_pull: 0.865952  low_bureau: 0.056300  cd_perc: 0.116622  | loss_multiplier mean: 1.098953
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.999049
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.996724

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.996724  (n=746)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)

  bb_populated: 743 / 746  wtd_mult: 0.983356  ragu_gli: 0.4161

============================================================
  KMX 2026-03-22/2026-03-28 (MTN 3.1)  (n=691)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.014472  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.059334  tier2: 0.037627  tier3: 0.004342  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.506512  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.043415  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.856729  narrowed: 0.086831  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000130  | loss_multiplier mean: 1.000130
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000130
14_veh_age  | continuous_age mean: 4.475398  | loss_multiplier mean: 1.000130
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.101302  | loss_multiplier mean: 1.000130
16_stu_loan | flag mean: 0.250362  | loss_multiplier mean: 0.994847
17_hi_price | flag mean: 0.157742  | loss_multiplier mean: 0.994847
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.994847
19_louisiana| flag mean: 0.004342  | loss_multiplier mean: 0.996448
20_georgia  | flag mean: 0.081042  | loss_multiplier mean: 1.004513
21_txca     | flag mean: 0.306802  | loss_multiplier mean: 0.981432
22_st_cntr  | no state adj: 0.607815  | loss_multiplier mean: 0.987534
23_sec_cr31 | chime mean: 0.322721  | loss_multiplier mean: 1.051104
24_job_t_31 | flag mean: 0.102750  | loss_multiplier mean: 1.062583
25_dq_31    | flag mean: 0.109986  | loss_multiplier mean: 1.064403
26_emp_31   | seasonal: 0.010130  | loss_multiplier mean: 1.065491
27_auth_31  | flag mean: 0.043415  | loss_multiplier mean: 1.057502

28_soft_31  | soft_pull: 0.856729  low_bureau: 0.043415  cd_perc: 0.109986  | loss_multiplier mean: 1.111921
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.010837
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.010477

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.010477  (n=691)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 690 / 691  wtd_mult: 0.993796  ragu_gli: 0.1551

============================================================
  KMX 2026-03-29/2026-04-04 (MTN 3.1)  (n=624)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.027244  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.072115  tier2: 0.025641  tier3: 0.003205  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.455128  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.036859  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.863782  narrowed: 0.089744  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.006891  | loss_multiplier mean: 1.006891
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.006891
14_veh_age  | continuous_age mean: 4.499733  | loss_multiplier mean: 1.006891
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.100962  | loss_multiplier mean: 1.006891
16_stu_loan | flag mean: 0.221154  | loss_multiplier mean: 0.997337
17_hi_price | flag mean: 0.179487  | loss_multiplier mean: 0.997337
18_driver   | flag mean: 0.003205  | loss_multiplier mean: 0.997863
19_louisiana| flag mean: 0.014423  | loss_multiplier mean: 1.003172
20_georgia  | flag mean: 0.076923  | loss_multiplier mean: 1.010932
21_txca     | flag mean: 0.299679  | loss_multiplier mean: 0.987668
22_st_cntr  | no state adj: 0.608974  | loss_multiplier mean: 0.993883
23_sec_cr31 | chime mean: 0.258013  | loss_multiplier mean: 1.041426
24_job_t_31 | flag mean: 0.112179  | loss_multiplier mean: 1.056672
25_dq_31    | flag mean: 0.107372  | loss_multiplier mean: 1.058347
26_emp_31   | seasonal: 0.008013  | loss_multiplier mean: 1.059263
27_auth_31  | flag mean: 0.036859  | loss_multiplier mean: 1.050907
28_soft_31  | soft_pull: 0.863782  low_bureau: 0.048077  cd_perc: 0.113782  | loss_multiplier mean: 1.116124
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.014658
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.007976

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.007976  (n=624)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 618 / 624  wtd_mult: 0.990763  ragu_gli: 0.2309

============================================================
  KMX 2026-04-05/2026-04-11 (MTN 3.1)  (n=86)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.011628  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.081395  tier2: 0.023256  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.430233  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.046512  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.883721  narrowed: 0.093023  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.042209  | loss_multiplier mean: 1.042209
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.042209
14_veh_age  | continuous_age mean: 4.978682  | loss_multiplier mean: 1.042209
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.104651  | loss_multiplier mean: 1.042209
16_stu_loan | flag mean: 0.255814  | loss_multiplier mean: 1.036042
17_hi_price | flag mean: 0.139535  | loss_multiplier mean: 1.036042
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.036042
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 1.036042
20_georgia  | flag mean: 0.058140  | loss_multiplier mean: 1.042099
21_txca     | flag mean: 0.348837  | loss_multiplier mean: 1.016500
22_st_cntr  | no state adj: 0.593023  | loss_multiplier mean: 1.023583
23_sec_cr31 | chime mean: 0.244186  | loss_multiplier mean: 1.066092
24_job_t_31 | flag mean: 0.069767  | loss_multiplier mean: 1.071625
25_dq_31    | flag mean: 0.127907  | loss_multiplier mean: 1.075277
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 1.075277
27_auth_31  | flag mean: 0.046512  | loss_multiplier mean: 1.067641
28_soft_31  | soft_pull: 0.883721  low_bureau: 0.034884  cd_perc: 0.116279  | loss_multiplier mean: 1.127793
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.025267
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.003863

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.003863  (n=86)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 86 / 86  wtd_mult: 0.974996  ragu_gli: 0.6251

--- MTN 3.1 Multiplier Steps ---

,KMX | 2026-03-01/2026-03-07,KMX | 2026-03-08/2026-03-14,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.999810,0.998561,0.989933,1.000130,1.006891,1.042209
13_clip_3.0,0.999810,0.998561,0.989933,1.000130,1.006891,1.042209
14_vehicle_age_3.0,0.999810,0.998561,0.989933,1.000130,1.006891,1.042209
15_npc_all,0.999810,0.998561,0.989933,1.000130,1.006891,1.042209
16_student_loans_all,0.993039,0.991655,0.985112,0.994847,0.997337,1.036042
17_high_sales_price_4.1,0.993039,0.991655,0.985112,0.994847,0.997337,1.036042
18_driver_flag_all,0.993183,0.991798,0.985305,0.994847,0.997863,1.036042
19_louisiana_all,0.996988,0.993683,0.987542,0.996448,1.003172,1.036042
20_georgia_all,1.006434,1.002154,0.993687,1.004513,1.010932,1.042099
21_txca_all,0.983091,0.982034,0.968633,0.981432,0.987668,1.016500
22_state_counter_all,0.988811,0.988347,0.974588,0.987534,0.993883,1.023583
23_secured_credit_3.1+,1.053004,1.044902,1.027950,1.051104,1.041426,1.066092
24_job_time_3.1+,1.070157,1.056533,1.042186,1.062583,1.056672,1.071625
25_existing_dq_3.1+,1.073940,1.060420,1.047019,1.064403,1.058347,1.075277
26_employment_3.1+,1.074420,1.061289,1.047966,1.065491,1.059263,1.075277
27_auth_tradelines_3.1+,1.065866,1.052996,1.039659,1.057502,1.050907,1.067641
28_soft_pull_3.1+,1.129063,1.110139,1.098953,1.111921,1.116124,1.127793
28b_blanket_3.1+,1.026421,1.009217,0.999049,1.010837,1.014658,1.025267
29_final_clip_3.1+,1.022087,1.005928,0.996724,1.010477,1.007976,1.003863
--- FINAL_MULT (mean),1.022087,1.005928,0.996724,1.010477,1.007976,1.003863
--- WTD_MULT_RAGU,1.005738,0.993398,0.983356,0.993796,0.990763,0.974996
--- GROSS_LOSS_IMPACT,-0.143444,0.165047,0.416094,0.155111,0.230932,0.625091
--- N_RECORDS,1002.000000,917.000000,746.000000,691.000000,624.000000,86.000000

--- MTN 3.1 Flag Means ---

,KMX | 2026-03-01/2026-03-07,KMX | 2026-03-08/2026-03-14,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11
job_time_flag,0.124750,0.099237,0.112601,0.102750,0.112179,0.069767
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.295409,0.300981,0.290885,0.314038,0.331731,0.383721
low_vantage_flag,0.010978,0.013086,0.029491,0.014472,0.027244,0.011628
normal_pti_flag,0.903194,0.905125,0.911528,0.898698,0.899038,0.895349
high_pti_tier_1_flag,0.066866,0.066521,0.058981,0.059334,0.072115,0.081395
high_pti_tier_2_flag,0.028942,0.026172,0.024129,0.037627,0.025641,0.023256
high_pti_tier_3_flag,0.000998,0.002181,0.005362,0.004342,0.003205,0.000000
existing_dq_flag,0.127745,0.128680,0.139410,0.109986,0.107372,0.127907
seasonal_employment_flag,0.004990,0.008724,0.009383,0.010130,0.008013,0.000000
secured_credit_flag,0.500000,0.504907,0.489276,0.506512,0.455128,0.430233
kmx_auth_tradelines_flag,0.034930,0.039258,0.037534,0.043415,0.036859,0.046512
null_fico_w_vantage_flag,0.960080,0.943293,0.966488,0.971056,0.961538,0.976744
null_fico_null_vantage_flag,0.020958,0.029444,0.033512,0.026049,0.038462,0.023256
soft_pull_flag,0.878244,0.845147,0.865952,0.856729,0.863782,0.883721
narrowed_soft_pull_flag,0.087824,0.073064,0.092493,0.086831,0.089744,0.093023
fraud_adjustment_mean,0.999810,0.998561,0.989933,1.000130,1.006891,1.042209
continuous_vehicle_age_mean,4.516966,4.590513,4.554960,4.475398,4.499733,4.978682
kmx_npc_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_pti_npc,0.096806,0.094875,0.088472,0.101302,0.100962,0.104651
student_loan_flag,0.239521,0.238822,0.253351,0.250362,0.221154,0.255814
high_sales_price_flag,0.119760,0.114504,0.148794,0.157742,0.179487,0.139535
driver_flag,0.000998,0.001091,0.001340,0.000000,0.003205,0.000000
louisiana_flag,0.010978,0.005453,0.006702,0.004342,0.014423,0.000000
georgia_flag,0.093812,0.085060,0.061662,0.081042,0.076923,0.058140
txca_flag,0.325349,0.296619,0.340483,0.306802,0.299679,0.348837
chime_flag,0.324351,0.291167,0.290885,0.322721,0.258013,0.244186
low_bureau_flag,0.047904,0.037077,0.056300,0.043415,0.048077,0.034884
cd_perc_flag,0.110778,0.093784,0.116622,0.109986,0.113782,0.116279
open_tl_flag,0.102794,0.117775,0.091153,0.075253,0.128205,0.058140
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
--- N_RECORDS,1002.000000,917.000000,746.000000,691.000000,624.000000,86.000000

--- MTN 3.1 Gross Loss Attribution ---

,KMX | 2026-03-01/2026-03-07,KMX | 2026-03-08/2026-03-14,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11
Low FICO (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Low Vantage (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
High PTI (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Loss Scale Div (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Secured Credit (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Auth Tradelines (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Soft Pull (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Fraud Adjustment,0.001245,-0.040224,1.282843,0.001938,0.199628,6.703656
Clip (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Vehicle Age (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
NPC,-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Student Loans,0.044618,-0.193784,0.618922,-0.078818,-0.277146,-0.962388
High Sales Price (4.1),-0.000000,0.000000,-0.000000,0.000000,0.000000,0.000000
Driver Flag,-0.000950,0.004024,-0.024841,0.000000,0.015332,0.000000
Louisiana,-0.025108,0.053035,-0.287479,0.023924,0.154258,0.000000
Georgia,-0.061915,0.237034,-0.786530,0.119966,0.223986,0.945165
TX / CA,0.154079,-0.566311,3.237726,-0.345944,-0.676775,-4.032784
State Counter,-0.038091,0.178928,-0.777032,0.092238,0.182350,1.125941
Secured Credit / Chime (3.1+),-0.412989,1.553784,-6.758670,0.928448,1.358298,6.597786
Job Time (3.1+),-0.106095,0.309127,-1.743806,0.161639,0.422472,0.839460
Existing DQ (3.1+),-0.023169,0.102533,-0.586603,0.025473,0.046055,0.551608
Employment Type (3.1+),-0.002939,0.022883,-0.114709,0.015206,0.025144,0.000000
Auth Tradelines (3.1+),0.052486,-0.219056,1.008995,-0.112003,-0.230234,-1.155644
Soft Pull (3.1+),-0.378203,1.475643,-7.032276,0.746778,1.750216,8.887606
Blanket Adjustment (3.1+),0.625801,-2.661410,12.084157,-1.418432,-2.770568,-15.454367
Clip (3.1+),0.027784,-0.091156,0.295399,-0.005302,-0.192083,-3.420947
--- TOTAL (check),-0.143444,0.165047,0.416094,0.155111,0.230932,0.625091

============================================================
  DIAGNOSTICS: MTN 3.2
============================================================

============================================================
  KMX 2026-03-15/2026-03-21 (MTN 3.2)  (n=936)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.018162  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.059829  tier2: 0.038462  tier3: 0.003205  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.493590  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.035256  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.869658  narrowed: 0.118590  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.995598  | loss_multiplier mean: 0.995598
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.995598
14_veh_age  | continuous_age mean: 4.918803  | loss_multiplier mean: 0.995598
15_npc      | npc_flag mean: 0.996795  high_pti_npc mean: 0.101496  | loss_multiplier mean: 0.996857
16_stu_loan | flag mean: 0.220085  | loss_multiplier mean: 0.987402
17_hi_price | flag mean: 0.146368  | loss_multiplier mean: 0.987402
18_driver   | flag mean: 0.002137  | loss_multiplier mean: 0.987706
19_louisiana| flag mean: 0.005342  | loss_multiplier mean: 0.989503
20_georgia  | flag mean: 0.075855  | loss_multiplier mean: 0.997041
21_txca     | flag mean: 0.305556  | loss_multiplier mean: 0.974603
22_st_cntr  | no state adj: 0.613248  | loss_multiplier mean: 0.980844
23_sec_cr31 | chime mean: 0.322650  | loss_multiplier mean: 1.045590
24_job_t_31 | flag mean: 0.116453  | loss_multiplier mean: 1.061189
25_dq_31    | flag mean: 0.123932  | loss_multiplier mean: 1.064144
26_emp_31   | seasonal: 0.006410  | loss_multiplier mean: 1.064879
27_auth_31  | flag mean: 0.035256  | loss_multiplier mean: 1.056342
28_soft_31  | soft_pull: 0.869658  low_bureau: 0.045940  cd_perc: 0.143162  | loss_multiplier mean: 1.118349

28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.016681

29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.014348

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.014348  (n=936)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 926 / 936  wtd_mult: 0.994809  ragu_gli: 0.1298

============================================================
  KMX 2026-03-22/2026-03-28 (MTN 3.2)  (n=870)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.013793  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.075862  tier2: 0.032184  tier3: 0.001149  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.500000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.042529  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.862069  narrowed: 0.088506  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.001759  | loss_multiplier mean: 1.001759
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.001759
14_veh_age  | continuous_age mean: 5.025287  | loss_multiplier mean: 1.001759
15_npc      | npc_flag mean: 0.997701  high_pti_npc mean: 0.109195  | loss_multiplier mean: 1.003817
16_stu_loan | flag mean: 0.229885  | loss_multiplier mean: 0.995481
17_hi_price | flag mean: 0.141379  | loss_multiplier mean: 0.995481
18_driver   | flag mean: 0.002299  | loss_multiplier mean: 0.995872
19_louisiana| flag mean: 0.005747  | loss_multiplier mean: 0.997839
20_georgia  | flag mean: 0.095402  | loss_multiplier mean: 1.007354
21_txca     | flag mean: 0.294253  | loss_multiplier mean: 0.985495
22_st_cntr  | no state adj: 0.604598  | loss_multiplier mean: 0.991660
23_sec_cr31 | chime mean: 0.312644  | loss_multiplier mean: 1.054689
24_job_t_31 | flag mean: 0.132184  | loss_multiplier mean: 1.073455
25_dq_31    | flag mean: 0.122989  | loss_multiplier mean: 1.076829
26_emp_31   | seasonal: 0.008046  | loss_multiplier mean: 1.077641
27_auth_31  | flag mean: 0.042529  | loss_multiplier mean: 1.069427
28_soft_31  | soft_pull: 0.862069  low_bureau: 0.036782  cd_perc: 0.113793  | loss_multiplier mean: 1.123702
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.021547
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.018459

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.018459  (n=870)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 869 / 870  wtd_mult: 1.000893  ragu_gli: -0.0223

============================================================
  KMX 2026-03-29/2026-04-04 (MTN 3.2)  (n=833)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.016807  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.069628  tier2: 0.028812  tier3: 0.006002  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.458583  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.045618  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.846339  narrowed: 0.106843  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.016435  | loss_multiplier mean: 1.016435
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.016435
14_veh_age  | continuous_age mean: 5.114146  | loss_multiplier mean: 1.016435
15_npc      | npc_flag mean: 0.997599  high_pti_npc mean: 0.104442  | loss_multiplier mean: 1.018363
16_stu_loan | flag mean: 0.200480  | loss_multiplier mean: 1.005506
17_hi_price | flag mean: 0.165666  | loss_multiplier mean: 1.005506
18_driver   | flag mean: 0.001200  | loss_multiplier mean: 1.005677
19_louisiana| flag mean: 0.001200  | loss_multiplier mean: 1.006077
20_georgia  | flag mean: 0.082833  | loss_multiplier mean: 1.014450
21_txca     | flag mean: 0.297719  | loss_multiplier mean: 0.991777
22_st_cntr  | no state adj: 0.618247  | loss_multiplier mean: 0.997982
23_sec_cr31 | chime mean: 0.280912  | loss_multiplier mean: 1.053836
24_job_t_31 | flag mean: 0.090036  | loss_multiplier mean: 1.063544
25_dq_31    | flag mean: 0.111645  | loss_multiplier mean: 1.065474
26_emp_31   | seasonal: 0.004802  | loss_multiplier mean: 1.065978
27_auth_31  | flag mean: 0.045618  | loss_multiplier mean: 1.058342
28_soft_31  | soft_pull: 0.846339  low_bureau: 0.042017  cd_perc: 0.123649  | loss_multiplier mean: 1.119356
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.017597
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.010529

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.010529  (n=833)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 828 / 833  wtd_mult: 0.988316  ragu_gli: 0.2921

============================================================
  KMX 2026-04-05/2026-04-11 (MTN 3.2)  (n=1055)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.008531  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.062559  tier2: 0.032227  tier3: 0.006635  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.462559  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.044550  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.848341  narrowed: 0.081517  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.014066  | loss_multiplier mean: 1.014066
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.014066
14_veh_age  | continuous_age mean: 4.797551  | loss_multiplier mean: 1.014066
15_npc      | npc_flag mean: 0.646445  high_pti_npc mean: 0.101422  | loss_multiplier mean: 1.014580
16_stu_loan | flag mean: 0.215166  | loss_multiplier mean: 1.003750

17_hi_price | flag mean: 0.155450  | loss_multiplier mean: 1.003750
18_driver   | flag mean: 0.000948  | loss_multiplier mean: 1.003887
19_louisiana| flag mean: 0.004739  | loss_multiplier mean: 1.005601
20_georgia  | flag mean: 0.074882  | loss_multiplier mean: 1.013319
21_txca     | flag mean: 0.310900  | loss_multiplier mean: 0.989253
22_st_cntr  | no state adj: 0.609479  | loss_multiplier mean: 0.995540
23_sec_cr31 | chime mean: 0.252133  | loss_multiplier mean: 1.040393
24_job_t_31 | flag mean: 0.109953  | loss_multiplier mean: 1.054273
25_dq_31    | flag mean: 0.102370  | loss_multiplier mean: 1.055007
26_emp_31   | seasonal: 0.011374  | loss_multiplier mean: 1.056338
27_auth_31  | flag mean: 0.044550  | loss_multiplier mean: 1.048449
28_soft_31  | soft_pull: 0.848341  low_bureau: 0.031280  cd_perc: 0.109953  | loss_multiplier mean: 1.105204
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.004731
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.001173

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.001173  (n=1055)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 1040 / 1055  wtd_mult: 0.980630  ragu_gli: 0.4842

============================================================
  KMX 2026-04-12/2026-04-18 (MTN 3.2)  (n=1080)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.012037  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.067593  tier2: 0.029630  tier3: 0.001852  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.454630  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.042593  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.834259  narrowed: 0.102778  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.009491  | loss_multiplier mean: 1.009491
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.009491
14_veh_age  | continuous_age mean: 4.713889  | loss_multiplier mean: 1.009491
15_npc      | npc_flag mean: 0.576852  high_pti_npc mean: 0.099074  | loss_multiplier mean: 1.010478
16_stu_loan | flag mean: 0.207407  | loss_multiplier mean: 0.998822
17_hi_price | flag mean: 0.184259  | loss_multiplier mean: 0.998822
18_driver   | flag mean: 0.000926  | loss_multiplier mean: 0.998956
19_louisiana| flag mean: 0.004630  | loss_multiplier mean: 1.000550
20_georgia  | flag mean: 0.077778  | loss_multiplier mean: 1.008385
21_txca     | flag mean: 0.319444  | loss_multiplier mean: 0.984116
22_st_cntr  | no state adj: 0.598148  | loss_multiplier mean: 0.990259
23_sec_cr31 | chime mean: 0.250926  | loss_multiplier mean: 1.034747
24_job_t_31 | flag mean: 0.091667  | loss_multiplier mean: 1.045372
25_dq_31    | flag mean: 0.137963  | loss_multiplier mean: 1.049976
26_emp_31   | seasonal: 0.005556  | loss_multiplier mean: 1.050586
27_auth_31  | flag mean: 0.042593  | loss_multiplier mean: 1.042633
28_soft_31  | soft_pull: 0.834259  low_bureau: 0.037963  cd_perc: 0.132407  | loss_multiplier mean: 1.101389
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.001262
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.998548

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.998548  (n=1080)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)

  bb_populated: 1043 / 1080  wtd_mult: 0.977821  ragu_gli: 0.5545

============================================================
  KMX 2026-04-19/2026-04-25 (MTN 3.2)  (n=277)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.003610  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.083032  tier2: 0.036101  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.429603  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.028881  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.826715  narrowed: 0.140794  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.933514  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.581227  high_pti_npc mean: 0.119134  | loss_multiplier mean: 1.001336
16_stu_loan | flag mean: 0.184116  | loss_multiplier mean: 0.987144
17_hi_price | flag mean: 0.155235  | loss_multiplier mean: 0.987144
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.987144
19_louisiana| flag mean: 0.003610  | loss_multiplier mean: 0.988345
20_georgia  | flag mean: 0.068592  | loss_multiplier mean: 0.995034
21_txca     | flag mean: 0.321300  | loss_multiplier mean: 0.971624
22_st_cntr  | no state adj: 0.606498  | loss_multiplier mean: 0.977438
23_sec_cr31 | chime mean: 0.220217  | loss_multiplier mean: 1.011121
24_job_t_31 | flag mean: 0.122744  | loss_multiplier mean: 1.026214
25_dq_31    | flag mean: 0.133574  | loss_multiplier mean: 1.030554
26_emp_31   | seasonal: 0.014440  | loss_multiplier mean: 1.032067
27_auth_31  | flag mean: 0.028881  | loss_multiplier mean: 1.023435
28_soft_31  | soft_pull: 0.826715  low_bureau: 0.043321  cd_perc: 0.173285  | loss_multiplier mean: 1.085420
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.986745
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.987264

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.987264  (n=277)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 160 / 277  wtd_mult: 0.973662  ragu_gli: 0.6585

--- MTN 3.2 Multiplier Steps ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.995598,1.001759,1.016435,1.014066,1.009491,1.000000
13_clip_3.0,0.995598,1.001759,1.016435,1.014066,1.009491,1.000000
14_vehicle_age_3.0,0.995598,1.001759,1.016435,1.014066,1.009491,1.000000
15_npc_all,0.996857,1.003817,1.018363,1.014580,1.010478,1.001336
16_student_loans_all,0.987402,0.995481,1.005506,1.003750,0.998822,0.987144
17_high_sales_price_4.1,0.987402,0.995481,1.005506,1.003750,0.998822,0.987144
18_driver_flag_all,0.987706,0.995872,1.005677,1.003887,0.998956,0.987144
19_louisiana_all,0.989503,0.997839,1.006077,1.005601,1.000550,0.988345
20_georgia_all,0.997041,1.007354,1.014450,1.013319,1.008385,0.995034
21_txca_all,0.974603,0.985495,0.991777,0.989253,0.984116,0.971624
22_state_counter_all,0.980844,0.991660,0.997982,0.995540,0.990259,0.977438
23_secured_credit_3.1+,1.045590,1.054689,1.053836,1.040393,1.034747,1.011121
24_job_time_3.1+,1.061189,1.073455,1.063544,1.054273,1.045372,1.026214
25_existing_dq_3.1+,1.064144,1.076829,1.065474,1.055007,1.049976,1.030554
26_employment_3.1+,1.064879,1.077641,1.065978,1.056338,1.050586,1.032067
27_auth_tradelines_3.1+,1.056342,1.069427,1.058342,1.048449,1.042633,1.023435
28_soft_pull_3.1+,1.118349,1.123702,1.119356,1.105204,1.101389,1.085420
28b_blanket_3.1+,1.016681,1.021547,1.017597,1.004731,1.001262,0.986745
29_final_clip_3.1+,1.014348,1.018459,1.010529,1.001173,0.998548,0.987264
--- FINAL_MULT (mean),1.014348,1.018459,1.010529,1.001173,0.998548,0.987264
--- WTD_MULT_RAGU,0.994809,1.000893,0.988316,0.980630,0.977821,0.973662
--- GROSS_LOSS_IMPACT,0.129778,-0.022333,0.292106,0.484246,0.554480,0.658462
--- N_RECORDS,936.000000,870.000000,833.000000,1055.000000,1080.000000,277.000000

--- MTN 3.2 Flag Means ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
job_time_flag,0.116453,0.132184,0.090036,0.109953,0.091667,0.122744
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.319444,0.309195,0.320528,0.298578,0.311111,0.361011
low_vantage_flag,0.018162,0.013793,0.016807,0.008531,0.012037,0.003610
normal_pti_flag,0.898504,0.890805,0.895558,0.898578,0.900926,0.880866
high_pti_tier_1_flag,0.059829,0.075862,0.069628,0.062559,0.067593,0.083032
high_pti_tier_2_flag,0.038462,0.032184,0.028812,0.032227,0.029630,0.036101
high_pti_tier_3_flag,0.003205,0.001149,0.006002,0.006635,0.001852,0.000000
existing_dq_flag,0.123932,0.122989,0.111645,0.102370,0.137963,0.133574
seasonal_employment_flag,0.006410,0.008046,0.004802,0.011374,0.005556,0.014440
secured_credit_flag,0.493590,0.500000,0.458583,0.462559,0.454630,0.429603
kmx_auth_tradelines_flag,0.035256,0.042529,0.045618,0.044550,0.042593,0.028881
null_fico_w_vantage_flag,0.970085,0.975862,0.981993,0.972512,0.977778,0.971119
null_fico_null_vantage_flag,0.026709,0.024138,0.018007,0.026540,0.021296,0.028881
soft_pull_flag,0.869658,0.862069,0.846339,0.848341,0.834259,0.826715
narrowed_soft_pull_flag,0.118590,0.088506,0.106843,0.081517,0.102778,0.140794
fraud_adjustment_mean,0.995598,1.001759,1.016435,1.014066,1.009491,1.000000
continuous_vehicle_age_mean,4.918803,5.025287,5.114146,4.797551,4.713889,4.933514
kmx_npc_flag,0.996795,0.997701,0.997599,0.646445,0.576852,0.581227
high_pti_npc,0.101496,0.109195,0.104442,0.101422,0.099074,0.119134
student_loan_flag,0.220085,0.229885,0.200480,0.215166,0.207407,0.184116
high_sales_price_flag,0.146368,0.141379,0.165666,0.155450,0.184259,0.155235
driver_flag,0.002137,0.002299,0.001200,0.000948,0.000926,0.000000
louisiana_flag,0.005342,0.005747,0.001200,0.004739,0.004630,0.003610
georgia_flag,0.075855,0.095402,0.082833,0.074882,0.077778,0.068592
txca_flag,0.305556,0.294253,0.297719,0.310900,0.319444,0.321300
chime_flag,0.322650,0.312644,0.280912,0.252133,0.250926,0.220217
low_bureau_flag,0.045940,0.036782,0.042017,0.031280,0.037963,0.043321
cd_perc_flag,0.143162,0.113793,0.123649,0.109953,0.132407,0.173285
open_tl_flag,0.087607,0.086207,0.105642,0.098578,0.093519,0.083032
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
--- N_RECORDS,936.000000,870.000000,833.000000,1055.000000,1080.000000,277.000000

--- MTN 3.2 Gross Loss Attribution ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
Low FICO (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Low Vantage (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
High PTI (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Loss Scale Div (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Secured Credit (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Auth Tradelines (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Soft Pull (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Fraud Adjustment,-0.040187,-0.002145,0.454619,5.768667,-3.603659,-0.000000
Clip (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Vehicle Age (3.0),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
NPC,0.011508,-0.002507,0.052850,0.209171,-0.373079,-0.068571
Student Loans,-0.086817,0.010182,-0.354325,-4.431907,4.426242,0.733247
High Sales Price (4.1),0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Driver Flag,0.002810,-0.000479,0.004746,0.056155,-0.050923,-0.000000
Louisiana,0.016557,-0.002410,0.011072,0.704485,-0.608532,-0.062454
Georgia,0.069132,-0.011588,0.231137,3.157546,-2.975698,-0.346490
TX / CA,-0.207355,0.026786,-0.630381,-9.926306,9.293941,1.223049
State Counter,0.058152,-0.007614,0.173936,2.616350,-2.374032,-0.306484
Secured Credit / Chime (3.1+),0.582332,-0.075238,1.518747,18.199285,-16.765048,-1.740429
Job Time (3.1+),0.134902,-0.021534,0.255759,5.473307,-3.897351,-0.761113
Existing DQ (3.1+),0.025332,-0.003832,0.050562,0.287237,-1.676728,-0.216802
Employment Type (3.1+),0.006292,-0.000920,0.013184,0.520894,-0.221422,-0.075381
Auth Tradelines (3.1+),-0.073330,0.009342,-0.200505,-3.095979,2.898874,0.431477
Soft Pull (3.1+),0.519640,-0.060445,1.563192,21.771568,-20.914837,-3.020705
Blanket Adjustment (3.1+),-0.868258,0.116372,-2.658110,-39.361355,36.360990,4.896098
Clip (3.1+),-0.020931,0.003696,-0.194378,-1.464871,1.035744,-0.026981
--- TOTAL (check),0.129778,-0.022333,0.292106,0.484246,0.554480,0.658462

============================================================
  DIAGNOSTICS: MTN 4.1
============================================================

============================================================
  KMX 2026-03-15/2026-03-21 (MTN 4.1)  (n=194)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.025773  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.056701  tier2: 0.020619  tier3: 0.005155  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.432990  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.041237  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.871134  narrowed: 0.108247  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.989948  | loss_multiplier mean: 0.989948
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.989948
14_veh_age  | continuous_age mean: 4.123711  | loss_multiplier mean: 0.989948
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.082474  | loss_multiplier mean: 0.989070
16_stu_loan | flag mean: 0.206186  | loss_multiplier mean: 0.978081
17_hi_price | flag mean: 0.128866  | loss_multiplier mean: 0.986422
18_driver   | flag mean: 0.005155  | loss_multiplier mean: 0.987142
19_louisiana| flag mean: 0.005155  | loss_multiplier mean: 0.988671
20_georgia  | flag mean: 0.061856  | loss_multiplier mean: 0.994700
21_txca     | flag mean: 0.412371  | loss_multiplier mean: 0.964290
22_st_cntr  | no state adj: 0.520619  | loss_multiplier mean: 0.968737
23_sec_cr31 | chime mean: 0.252577  | loss_multiplier mean: 1.011383
24_job_t_31 | flag mean: 0.103093  | loss_multiplier mean: 1.023353
25_dq_31    | flag mean: 0.134021  | loss_multiplier mean: 1.027597
26_emp_31   | seasonal: 0.010309  | loss_multiplier mean: 1.028568
27_auth_31  | flag mean: 0.041237  | loss_multiplier mean: 1.021034
28_soft_31  | soft_pull: 0.871134  low_bureau: 0.067010  cd_perc: 0.123711  | loss_multiplier mean: 1.111790
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.010719
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.007875

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.007875  (n=194)
  bb_populated: 193 / 194  wtd_mult: 1.017776  ragu_gli: -0.4444

============================================================
  KMX 2026-03-22/2026-03-28 (MTN 4.1)  (n=206)
============================================================
00_initial  | loss_multiplier mean: 1.000000

02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.029126  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.101942  tier2: 0.024272  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.432039  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.038835  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.873786  narrowed: 0.097087  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.001262  | loss_multiplier mean: 1.001262
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.001262
14_veh_age  | continuous_age mean: 4.344660  | loss_multiplier mean: 1.001262
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.126214  | loss_multiplier mean: 1.005240
16_stu_loan | flag mean: 0.247573  | loss_multiplier mean: 0.999191
17_hi_price | flag mean: 0.101942  | loss_multiplier mean: 1.001847
18_driver   | flag mean: 0.004854  | loss_multiplier mean: 1.002525
19_louisiana| flag mean: 0.004854  | loss_multiplier mean: 1.004108
20_georgia  | flag mean: 0.072816  | loss_multiplier mean: 1.011254
21_txca     | flag mean: 0.315534  | loss_multiplier mean: 0.985640
22_st_cntr  | no state adj: 0.606796  | loss_multiplier mean: 0.990219
23_sec_cr31 | chime mean: 0.233010  | loss_multiplier mean: 1.024820
24_job_t_31 | flag mean: 0.126214  | loss_multiplier mean: 1.041515
25_dq_31    | flag mean: 0.131068  | loss_multiplier mean: 1.046490
26_emp_31   | seasonal: 0.004854  | loss_multiplier mean: 1.047095
27_auth_31  | flag mean: 0.038835  | loss_multiplier mean: 1.038798
28_soft_31  | soft_pull: 0.873786  low_bureau: 0.043689  cd_perc: 0.121359  | loss_multiplier mean: 1.117113
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.015557
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.012517

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.012517  (n=206)
  bb_populated: 203 / 206  wtd_mult: 1.015668  ragu_gli: -0.3917

============================================================
  KMX 2026-03-29/2026-04-04 (MTN 4.1)  (n=178)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.016854  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.101124  tier2: 0.028090  tier3: 0.005618  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.415730  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.039326  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.848315  narrowed: 0.117978  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.002753  | loss_multiplier mean: 1.002753
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.002753
14_veh_age  | continuous_age mean: 4.421348  | loss_multiplier mean: 1.002753
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.134831  | loss_multiplier mean: 1.008181
16_stu_loan | flag mean: 0.191011  | loss_multiplier mean: 0.994377
17_hi_price | flag mean: 0.146067  | loss_multiplier mean: 1.006518
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.006518
19_louisiana| flag mean: 0.005618  | loss_multiplier mean: 1.008349
20_georgia  | flag mean: 0.067416  | loss_multiplier mean: 1.015218
21_txca     | flag mean: 0.320225  | loss_multiplier mean: 0.990074
22_st_cntr  | no state adj: 0.606742  | loss_multiplier mean: 0.995227
23_sec_cr31 | chime mean: 0.219101  | loss_multiplier mean: 1.028026
24_job_t_31 | flag mean: 0.089888  | loss_multiplier mean: 1.036510
25_dq_31    | flag mean: 0.123596  | loss_multiplier mean: 1.040739

26_emp_31   | seasonal: 0.005618  | loss_multiplier mean: 1.041375
27_auth_31  | flag mean: 0.039326  | loss_multiplier mean: 1.033480
28_soft_31  | soft_pull: 0.848315  low_bureau: 0.050562  cd_perc: 0.157303  | loss_multiplier mean: 1.118871
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.017156
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.008957

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.008957  (n=178)
  bb_populated: 178 / 178  wtd_mult: 1.020291  ragu_gli: -0.5073

============================================================
  KMX 2026-04-05/2026-04-11 (MTN 4.1)  (n=150)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.020000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.053333  tier2: 0.033333  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.373333  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.033333  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.886667  narrowed: 0.113333  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.010133  | loss_multiplier mean: 1.010133
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.010133
14_veh_age  | continuous_age mean: 4.330000  | loss_multiplier mean: 1.010133
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.086667  | loss_multiplier mean: 1.009815
16_stu_loan | flag mean: 0.233333  | loss_multiplier mean: 1.001737
17_hi_price | flag mean: 0.166667  | loss_multiplier mean: 1.016544
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.016544
19_louisiana| flag mean: 0.006667  | loss_multiplier mean: 1.018718
20_georgia  | flag mean: 0.033333  | loss_multiplier mean: 1.022076
21_txca     | flag mean: 0.340000  | loss_multiplier mean: 0.993730
22_st_cntr  | no state adj: 0.620000  | loss_multiplier mean: 0.999003
23_sec_cr31 | chime mean: 0.193333  | loss_multiplier mean: 1.025993
24_job_t_31 | flag mean: 0.093333  | loss_multiplier mean: 1.035377
25_dq_31    | flag mean: 0.140000  | loss_multiplier mean: 1.040960
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 1.040960
27_auth_31  | flag mean: 0.033333  | loss_multiplier mean: 1.032658
28_soft_31  | soft_pull: 0.886667  low_bureau: 0.066667  cd_perc: 0.146667  | loss_multiplier mean: 1.122893
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.020811
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.016598

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.016598  (n=150)

  bb_populated: 148 / 150  wtd_mult: 1.019581  ragu_gli: -0.4895

============================================================
  KMX 2026-04-12/2026-04-18 (MTN 4.1)  (n=141)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.007092  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.070922  tier2: 0.035461  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.375887  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.014184  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.879433  narrowed: 0.099291  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.005745  | loss_multiplier mean: 1.005745
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.005745
14_veh_age  | continuous_age mean: 4.377660  | loss_multiplier mean: 1.005745
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.106383  | loss_multiplier mean: 1.007538
16_stu_loan | flag mean: 0.276596  | loss_multiplier mean: 1.005734
17_hi_price | flag mean: 0.127660  | loss_multiplier mean: 1.012438
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.012438
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 1.012438
20_georgia  | flag mean: 0.127660  | loss_multiplier mean: 1.025563
21_txca     | flag mean: 0.361702  | loss_multiplier mean: 0.996968
22_st_cntr  | no state adj: 0.510638  | loss_multiplier mean: 1.002344
23_sec_cr31 | chime mean: 0.226950  | loss_multiplier mean: 1.039483
24_job_t_31 | flag mean: 0.070922  | loss_multiplier mean: 1.043396
25_dq_31    | flag mean: 0.177305  | loss_multiplier mean: 1.052545
26_emp_31   | seasonal: 0.021277  | loss_multiplier mean: 1.054743
27_auth_31  | flag mean: 0.014184  | loss_multiplier mean: 1.045394
28_soft_31  | soft_pull: 0.879433  low_bureau: 0.021277  cd_perc: 0.134752  | loss_multiplier mean: 1.129008
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.026371
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.023684

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.023684  (n=141)

  bb_populated: 136 / 141  wtd_mult: 1.022759  ragu_gli: -0.5690

============================================================
  KMX 2026-04-19/2026-04-25 (MTN 4.1)  (n=35)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.028571  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.057143  tier2: 0.028571  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.600000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.714286  narrowed: 0.171429  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.869048  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.085714  | loss_multiplier mean: 0.999429
16_stu_loan | flag mean: 0.342857  | loss_multiplier mean: 1.006971
17_hi_price | flag mean: 0.114286  | loss_multiplier mean: 1.011599
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.011599
19_louisiana| flag mean: 0.028571  | loss_multiplier mean: 1.022271
20_georgia  | flag mean: 0.028571  | loss_multiplier mean: 1.025320
21_txca     | flag mean: 0.257143  | loss_multiplier mean: 1.003391
22_st_cntr  | no state adj: 0.685714  | loss_multiplier mean: 1.009654
23_sec_cr31 | chime mean: 0.171429  | loss_multiplier mean: 1.029524
24_job_t_31 | flag mean: 0.000000  | loss_multiplier mean: 1.019229
25_dq_31    | flag mean: 0.142857  | loss_multiplier mean: 1.023996
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 1.023996
27_auth_31  | flag mean: 0.000000  | loss_multiplier mean: 1.013756
28_soft_31  | soft_pull: 0.714286  low_bureau: 0.028571  cd_perc: 0.200000  | loss_multiplier mean: 1.071277
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.973888
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.972157

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 0.972157  (n=35)
  bb_populated: 19 / 35  wtd_mult: 1.004056  ragu_gli: -0.1014

--- MTN 4.1 Multiplier Steps ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.989948,1.001262,1.002753,1.010133,1.005745,1.000000
13_clip_3.0,0.989948,1.001262,1.002753,1.010133,1.005745,1.000000
14_vehicle_age_3.0,0.989948,1.001262,1.002753,1.010133,1.005745,1.000000
15_npc_all,0.989070,1.005240,1.008181,1.009815,1.007538,0.999429
16_student_loans_all,0.978081,0.999191,0.994377,1.001737,1.005734,1.006971
17_high_sales_price_4.1,0.986422,1.001847,1.006518,1.016544,1.012438,1.011599
18_driver_flag_all,0.987142,1.002525,1.006518,1.016544,1.012438,1.011599
19_louisiana_all,0.988671,1.004108,1.008349,1.018718,1.012438,1.022271
20_georgia_all,0.994700,1.011254,1.015218,1.022076,1.025563,1.025320
21_txca_all,0.964290,0.985640,0.990074,0.993730,0.996968,1.003391
22_state_counter_all,0.968737,0.990219,0.995227,0.999003,1.002344,1.009654
23_secured_credit_3.1+,1.011383,1.024820,1.028026,1.025993,1.039483,1.029524
24_job_time_3.1+,1.023353,1.041515,1.036510,1.035377,1.043396,1.019229
25_existing_dq_3.1+,1.027597,1.046490,1.040739,1.040960,1.052545,1.023996
26_employment_3.1+,1.028568,1.047095,1.041375,1.040960,1.054743,1.023996
27_auth_tradelines_3.1+,1.021034,1.038798,1.033480,1.032658,1.045394,1.013756
28_soft_pull_3.1+,1.111790,1.117113,1.118871,1.122893,1.129008,1.071277
28b_blanket_3.1+,1.010719,1.015557,1.017156,1.020811,1.026371,0.973888
29_final_clip_3.1+,1.007875,1.012517,1.008957,1.016598,1.023684,0.972157
--- FINAL_MULT (mean),1.007875,1.012517,1.008957,1.016598,1.023684,0.972157
--- WTD_MULT_RAGU,1.017776,1.015668,1.020291,1.019581,1.022759,1.004056
--- GROSS_LOSS_IMPACT,-0.444409,-0.391690,-0.507266,-0.489527,-0.568986,-0.101401
--- N_RECORDS,194.000000,206.000000,178.000000,150.000000,141.000000,35.000000

--- MTN 4.1 Flag Means ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
job_time_flag,0.103093,0.126214,0.089888,0.093333,0.070922,0.000000
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.381443,0.451456,0.410112,0.413333,0.347518,0.371429
low_vantage_flag,0.025773,0.029126,0.016854,0.020000,0.007092,0.028571
normal_pti_flag,0.917526,0.873786,0.865169,0.913333,0.893617,0.914286
high_pti_tier_1_flag,0.056701,0.101942,0.101124,0.053333,0.070922,0.057143
high_pti_tier_2_flag,0.020619,0.024272,0.028090,0.033333,0.035461,0.028571
high_pti_tier_3_flag,0.005155,0.000000,0.005618,0.000000,0.000000,0.000000
existing_dq_flag,0.134021,0.131068,0.123596,0.140000,0.177305,0.142857
seasonal_employment_flag,0.010309,0.004854,0.005618,0.000000,0.021277,0.000000
secured_credit_flag,0.432990,0.432039,0.415730,0.373333,0.375887,0.600000
kmx_auth_tradelines_flag,0.041237,0.038835,0.039326,0.033333,0.014184,0.000000
null_fico_w_vantage_flag,0.953608,0.975728,0.977528,0.973333,0.957447,0.971429
null_fico_null_vantage_flag,0.046392,0.024272,0.022472,0.026667,0.042553,0.028571
soft_pull_flag,0.871134,0.873786,0.848315,0.886667,0.879433,0.714286
narrowed_soft_pull_flag,0.108247,0.097087,0.117978,0.113333,0.099291,0.171429
fraud_adjustment_mean,0.989948,1.001262,1.002753,1.010133,1.005745,1.000000
continuous_vehicle_age_mean,4.123711,4.344660,4.421348,4.330000,4.377660,4.869048
kmx_npc_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
high_pti_npc,0.082474,0.126214,0.134831,0.086667,0.106383,0.085714
student_loan_flag,0.206186,0.247573,0.191011,0.233333,0.276596,0.342857
high_sales_price_flag,0.128866,0.101942,0.146067,0.166667,0.127660,0.114286
driver_flag,0.005155,0.004854,0.000000,0.000000,0.000000,0.000000
louisiana_flag,0.005155,0.004854,0.005618,0.006667,0.000000,0.028571
georgia_flag,0.061856,0.072816,0.067416,0.033333,0.127660,0.028571
txca_flag,0.412371,0.315534,0.320225,0.340000,0.361702,0.257143
chime_flag,0.252577,0.233010,0.219101,0.193333,0.226950,0.171429
low_bureau_flag,0.067010,0.043689,0.050562,0.066667,0.021277,0.028571
cd_perc_flag,0.123711,0.121359,0.157303,0.146667,0.134752,0.200000
open_tl_flag,0.118557,0.087379,0.106742,0.113333,0.099291,0.057143
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
--- N_RECORDS,194.000000,206.000000,178.000000,150.000000,141.000000,35.000000

--- MTN 4.1 Gross Loss Attribution ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
Low FICO (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Low Vantage (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
High PTI (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Loss Scale Div (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Secured Credit (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Auth Tradelines (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Soft Pull (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Fraud Adjustment,0.572346,-0.039716,-0.156382,-0.299823,-0.139237,0.000000
Clip (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
Vehicle Age (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000000
NPC,0.050290,-0.124839,-0.307106,0.009383,-0.043293,-0.002053
Student Loans,0.633004,0.190052,0.784255,0.238818,0.043553,0.026999
High Sales Price (4.1),-0.481104,-0.083598,-0.690344,-0.436340,-0.161492,0.016464
Driver Flag,-0.041346,-0.021308,-0.000000,-0.000000,-0.000000,0.000000
Louisiana,-0.087692,-0.049662,-0.103412,-0.063507,-0.000000,0.037685
Georgia,-0.344423,-0.223315,-0.386212,-0.097872,-0.313094,0.010695
TX / CA,1.759052,0.807829,1.426683,0.836392,0.687385,-0.077635
State Counter,-0.260673,-0.145945,-0.295329,-0.157375,-0.130723,0.022343
Secured Credit / Chime (3.1+),-2.440706,-1.081468,-1.844536,-0.792761,-0.884351,0.069986
Job Time (3.1+),-0.666566,-0.508818,-0.467505,-0.270757,-0.091326,-0.036090
Existing DQ (3.1+),-0.234491,-0.150041,-0.231631,-0.159912,-0.212214,0.016755
Employment Type (3.1+),-0.053481,-0.018173,-0.034768,-0.000000,-0.050715,0.000000
Auth Tradelines (3.1+),0.416494,0.250462,0.432920,0.238104,0.216410,-0.036090
Soft Pull (3.1+),-4.824466,-2.288554,-4.516131,-2.491159,-1.870305,0.198179
Blanket Adjustment (3.1+),5.399741,3.001021,5.421846,2.834281,2.316715,-0.342250
Clip (3.1+),0.159612,0.094383,0.460387,0.123001,0.063702,-0.006389
--- TOTAL (check),-0.444409,-0.391690,-0.507266,-0.489527,-0.568986,-0.101401

============================================================
  DIAGNOSTICS: All KMX
============================================================

============================================================
  KMX 2026-03-15/2026-03-21 (All KMX)  (n=1876)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.023454  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.059168  tier2: 0.030917  tier3: 0.004264  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.485608  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.036780  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.868337  narrowed: 0.107143  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.992761  | loss_multiplier mean: 0.992761
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.992761
14_veh_age  | continuous_age mean: 4.691898  | loss_multiplier mean: 0.992761
15_npc      | npc_flag mean: 0.600746  high_pti_npc mean: 0.094350  | loss_multiplier mean: 0.993298
16_stu_loan | flag mean: 0.231876  | loss_multiplier mean: 0.985527
17_hi_price | flag mean: 0.145522  | loss_multiplier mean: 0.986390
18_driver   | flag mean: 0.002132  | loss_multiplier mean: 0.986693
19_louisiana| flag mean: 0.005864  | loss_multiplier mean: 0.988637
20_georgia  | flag mean: 0.068763  | loss_multiplier mean: 0.995465
21_txca     | flag mean: 0.330490  | loss_multiplier mean: 0.971162
22_st_cntr  | no state adj: 0.594883  | loss_multiplier mean: 0.977104
23_sec_cr31 | chime mean: 0.302772  | loss_multiplier mean: 1.035038
24_job_t_31 | flag mean: 0.113539  | loss_multiplier mean: 1.049720
25_dq_31    | flag mean: 0.131130  | loss_multiplier mean: 1.053555
26_emp_31   | seasonal: 0.007996  | loss_multiplier mean: 1.054399
27_auth_31  | flag mean: 0.036780  | loss_multiplier mean: 1.046057
28_soft_31  | soft_pull: 0.868337  low_bureau: 0.052239  cd_perc: 0.130597  | loss_multiplier mean: 1.109958
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.009053
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.006670

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.996724  (n=746)
mtn_model 3.2: mean loss_multiplier = 1.014348  (n=936)
mtn_model 4.1: mean loss_multiplier = 1.007875  (n=194)
  bb_populated: 1862 / 1876  wtd_mult: 0.992697  ragu_gli: 0.1826

============================================================
  KMX 2026-03-22/2026-03-28 (All KMX)  (n=1767)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.015846  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.072439  tier2: 0.033390  tier3: 0.002264  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.494624  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.042445  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.861347  narrowed: 0.088851  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.001064  | loss_multiplier mean: 1.001064
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.001064
14_veh_age  | continuous_age mean: 4.730900  | loss_multiplier mean: 1.001064
15_npc      | npc_flag mean: 0.607810  high_pti_npc mean: 0.108093  | loss_multiplier mean: 1.002541
16_stu_loan | flag mean: 0.239955  | loss_multiplier mean: 0.995666
17_hi_price | flag mean: 0.143181  | loss_multiplier mean: 0.995975
18_driver   | flag mean: 0.001698  | loss_multiplier mean: 0.996247
19_louisiana| flag mean: 0.005093  | loss_multiplier mean: 0.998026
20_georgia  | flag mean: 0.087153  | loss_multiplier mean: 1.006698
21_txca     | flag mean: 0.301641  | loss_multiplier mean: 0.983923
22_st_cntr  | no state adj: 0.606112  | loss_multiplier mean: 0.989878
23_sec_cr31 | chime mean: 0.307301  | loss_multiplier mean: 1.049805
24_job_t_31 | flag mean: 0.119977  | loss_multiplier mean: 1.065480
25_dq_31    | flag mean: 0.118846  | loss_multiplier mean: 1.068433

26_emp_31   | seasonal: 0.008489  | loss_multiplier mean: 1.069329
27_auth_31  | flag mean: 0.042445  | loss_multiplier mean: 1.061193
28_soft_31  | soft_pull: 0.861347  low_bureau: 0.040181  cd_perc: 0.113186  | loss_multiplier mean: 1.118327
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.016661
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.014645

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.010477  (n=691)
mtn_model 3.2: mean loss_multiplier = 1.018459  (n=870)
mtn_model 4.1: mean loss_multiplier = 1.012517  (n=206)
  bb_populated: 1762 / 1767  wtd_mult: 0.999798  ragu_gli: 0.0051

============================================================
  KMX 2026-03-29/2026-04-04 (All KMX)  (n=1635)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.020795  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.074006  tier2: 0.027523  tier3: 0.004893  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.452599  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.041590  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.853211  narrowed: 0.101529  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.011303  | loss_multiplier mean: 1.011303
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.011303
14_veh_age  | continuous_age mean: 4.804230  | loss_multiplier mean: 1.011303

15_npc      | npc_flag mean: 0.617125  high_pti_npc mean: 0.106422  | loss_multiplier mean: 1.012876
16_stu_loan | flag mean: 0.207339  | loss_multiplier mean: 1.001177
17_hi_price | flag mean: 0.168807  | loss_multiplier mean: 1.002499
18_driver   | flag mean: 0.001835  | loss_multiplier mean: 1.002787
19_louisiana| flag mean: 0.006728  | loss_multiplier mean: 1.005216
20_georgia  | flag mean: 0.078899  | loss_multiplier mean: 1.013191
21_txca     | flag mean: 0.300917  | loss_multiplier mean: 0.990023
22_st_cntr  | no state adj: 0.613456  | loss_multiplier mean: 0.996117
23_sec_cr31 | chime mean: 0.265443  | loss_multiplier mean: 1.046290
24_job_t_31 | flag mean: 0.098471  | loss_multiplier mean: 1.057978
25_dq_31    | flag mean: 0.111315  | loss_multiplier mean: 1.060061
26_emp_31   | seasonal: 0.006116  | loss_multiplier mean: 1.060737
27_auth_31  | flag mean: 0.041590  | loss_multiplier mean: 1.052797
28_soft_31  | soft_pull: 0.853211  low_bureau: 0.045260  cd_perc: 0.123547  | loss_multiplier mean: 1.118070
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.016427
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.009383

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.007976  (n=624)
mtn_model 3.2: mean loss_multiplier = 1.010529  (n=833)
mtn_model 4.1: mean loss_multiplier = 1.008957  (n=178)
  bb_populated: 1624 / 1635  wtd_mult: 0.992845  ragu_gli: 0.1789

============================================================
  KMX 2026-04-05/2026-04-11 (All KMX)  (n=1291)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.010070  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.062742  tier2: 0.031758  tier3: 0.005422  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.450039  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.043377  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.855151  narrowed: 0.085980  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.015484  | loss_multiplier mean: 1.015484
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.015484
14_veh_age  | continuous_age mean: 4.755293  | loss_multiplier mean: 1.015484
15_npc      | npc_flag mean: 0.644462  high_pti_npc mean: 0.099923  | loss_multiplier mean: 1.015867
16_stu_loan | flag mean: 0.219985  | loss_multiplier mean: 1.005668
17_hi_price | flag mean: 0.155693  | loss_multiplier mean: 1.007388
18_driver   | flag mean: 0.000775  | loss_multiplier mean: 1.007500
19_louisiana| flag mean: 0.004648  | loss_multiplier mean: 1.009153
20_georgia  | flag mean: 0.068939  | loss_multiplier mean: 1.016253
21_txca     | flag mean: 0.316809  | loss_multiplier mean: 0.991588
22_st_cntr  | no state adj: 0.609605  | loss_multiplier mean: 0.997811
23_sec_cr31 | chime mean: 0.244771  | loss_multiplier mean: 1.040432
24_job_t_31 | flag mean: 0.105345  | loss_multiplier mean: 1.053234
25_dq_31    | flag mean: 0.108443  | loss_multiplier mean: 1.054725
26_emp_31   | seasonal: 0.009295  | loss_multiplier mean: 1.055813
27_auth_31  | flag mean: 0.043377  | loss_multiplier mean: 1.047893

28_soft_31  | soft_pull: 0.855151  low_bureau: 0.035631  cd_perc: 0.114640  | loss_multiplier mean: 1.108764
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.007967
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.003145

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.003863  (n=86)
mtn_model 3.2: mean loss_multiplier = 1.001173  (n=1055)
mtn_model 4.1: mean loss_multiplier = 1.016598  (n=150)
  bb_populated: 1274 / 1291  wtd_mult: 0.984933  ragu_gli: 0.3767

============================================================
  KMX 2026-04-12/2026-04-18 (All KMX)  (n=1221)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.011466  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.067977  tier2: 0.030303  tier3: 0.001638  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.445536  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.039312  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.839476  narrowed: 0.102375  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.009058  | loss_multiplier mean: 1.009058
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.009058
14_veh_age  | continuous_age mean: 4.675061  | loss_multiplier mean: 1.009058
15_npc      | npc_flag mean: 0.625717  high_pti_npc mean: 0.099918  | loss_multiplier mean: 1.010139
16_stu_loan | flag mean: 0.215397  | loss_multiplier mean: 0.999621
17_hi_price | flag mean: 0.177723  | loss_multiplier mean: 1.000395
18_driver   | flag mean: 0.000819  | loss_multiplier mean: 1.000513
19_louisiana| flag mean: 0.004095  | loss_multiplier mean: 1.001923
20_georgia  | flag mean: 0.083538  | loss_multiplier mean: 1.010369
21_txca     | flag mean: 0.324324  | loss_multiplier mean: 0.985600
22_st_cntr  | no state adj: 0.588043  | loss_multiplier mean: 0.991655
23_sec_cr31 | chime mean: 0.248157  | loss_multiplier mean: 1.035294
24_job_t_31 | flag mean: 0.089271  | loss_multiplier mean: 1.045143
25_dq_31    | flag mean: 0.142506  | loss_multiplier mean: 1.050273
26_emp_31   | seasonal: 0.007371  | loss_multiplier mean: 1.051066
27_auth_31  | flag mean: 0.039312  | loss_multiplier mean: 1.042952
28_soft_31  | soft_pull: 0.839476  low_bureau: 0.036036  cd_perc: 0.132678  | loss_multiplier mean: 1.104578
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.004162
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.001450

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.998548  (n=1080)
mtn_model 4.1: mean loss_multiplier = 1.023684  (n=141)
  bb_populated: 1179 / 1221  wtd_mult: 0.982994  ragu_gli: 0.4252

============================================================
  KMX 2026-04-19/2026-04-25 (All KMX)  (n=312)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.006410  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.080128  tier2: 0.035256  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.448718  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.025641  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.814103  narrowed: 0.144231  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.926282  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.628205  high_pti_npc mean: 0.115385  | loss_multiplier mean: 1.001122
16_stu_loan | flag mean: 0.201923  | loss_multiplier mean: 0.989369
17_hi_price | flag mean: 0.150641  | loss_multiplier mean: 0.989888
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.989888
19_louisiana| flag mean: 0.006410  | loss_multiplier mean: 0.992151
20_georgia  | flag mean: 0.064103  | loss_multiplier mean: 0.998432
21_txca     | flag mean: 0.314103  | loss_multiplier mean: 0.975187
22_st_cntr  | no state adj: 0.615385  | loss_multiplier mean: 0.981052
23_sec_cr31 | chime mean: 0.214744  | loss_multiplier mean: 1.013185
24_job_t_31 | flag mean: 0.108974  | loss_multiplier mean: 1.025430
25_dq_31    | flag mean: 0.134615  | loss_multiplier mean: 1.029818
26_emp_31   | seasonal: 0.012821  | loss_multiplier mean: 1.031162
27_auth_31  | flag mean: 0.025641  | loss_multiplier mean: 1.022349
28_soft_31  | soft_pull: 0.814103  low_bureau: 0.041667  cd_perc: 0.176282  | loss_multiplier mean: 1.083833
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.985303
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.985569

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.987264  (n=277)
mtn_model 4.1: mean loss_multiplier = 0.972157  (n=35)

  bb_populated: 179 / 312  wtd_mult: 0.976797  ragu_gli: 0.5801

--- All KMX Multiplier Steps ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.992761,1.001064,1.011303,1.015484,1.009058,1.000000
13_clip_3.0,0.992761,1.001064,1.011303,1.015484,1.009058,1.000000
14_vehicle_age_3.0,0.992761,1.001064,1.011303,1.015484,1.009058,1.000000
15_npc_all,0.993298,1.002541,1.012876,1.015867,1.010139,1.001122
16_student_loans_all,0.985527,0.995666,1.001177,1.005668,0.999621,0.989369
17_high_sales_price_4.1,0.986390,0.995975,1.002499,1.007388,1.000395,0.989888
18_driver_flag_all,0.986693,0.996247,1.002787,1.007500,1.000513,0.989888
19_louisiana_all,0.988637,0.998026,1.005216,1.009153,1.001923,0.992151
20_georgia_all,0.995465,1.006698,1.013191,1.016253,1.010369,0.998432
21_txca_all,0.971162,0.983923,0.990023,0.991588,0.985600,0.975187
22_state_counter_all,0.977104,0.989878,0.996117,0.997811,0.991655,0.981052
23_secured_credit_3.1+,1.035038,1.049805,1.046290,1.040432,1.035294,1.013185
24_job_time_3.1+,1.049720,1.065480,1.057978,1.053234,1.045143,1.025430
25_existing_dq_3.1+,1.053555,1.068433,1.060061,1.054725,1.050273,1.029818
26_employment_3.1+,1.054399,1.069329,1.060737,1.055813,1.051066,1.031162
27_auth_tradelines_3.1+,1.046057,1.061193,1.052797,1.047893,1.042952,1.022349
28_soft_pull_3.1+,1.109958,1.118327,1.118070,1.108764,1.104578,1.083833
28b_blanket_3.1+,1.009053,1.016661,1.016427,1.007967,1.004162,0.985303
29_final_clip_3.1+,1.006670,1.014645,1.009383,1.003145,1.001450,0.985569
--- FINAL_MULT (mean),1.006670,1.014645,1.009383,1.003145,1.001450,0.985569
--- WTD_MULT_RAGU,0.992697,0.999798,0.992845,0.984933,0.982994,0.976797
--- GROSS_LOSS_IMPACT,0.182583,0.005056,0.178879,0.376676,0.425154,0.580074
--- N_RECORDS,1876.000000,1767.000000,1635.000000,1291.000000,1221.000000,312.000000

--- All KMX Flag Means ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
job_time_flag,0.113539,0.119977,0.098471,0.105345,0.089271,0.108974
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.314499,0.327674,0.334557,0.317583,0.315315,0.362179
low_vantage_flag,0.023454,0.015846,0.020795,0.010070,0.011466,0.006410
normal_pti_flag,0.905650,0.891907,0.893578,0.900077,0.900082,0.884615
high_pti_tier_1_flag,0.059168,0.072439,0.074006,0.062742,0.067977,0.080128
high_pti_tier_2_flag,0.030917,0.033390,0.027523,0.031758,0.030303,0.035256
high_pti_tier_3_flag,0.004264,0.002264,0.004893,0.005422,0.001638,0.000000
existing_dq_flag,0.131130,0.118846,0.111315,0.108443,0.142506,0.134615
seasonal_employment_flag,0.007996,0.008489,0.006116,0.009295,0.007371,0.012821
secured_credit_flag,0.485608,0.494624,0.452599,0.450039,0.445536,0.448718
kmx_auth_tradelines_flag,0.036780,0.042445,0.041590,0.043377,0.039312,0.025641
null_fico_w_vantage_flag,0.966951,0.973967,0.973700,0.972889,0.975430,0.971154
null_fico_null_vantage_flag,0.031450,0.024901,0.026300,0.026336,0.023751,0.028846
soft_pull_flag,0.868337,0.861347,0.853211,0.855151,0.839476,0.814103
narrowed_soft_pull_flag,0.107143,0.088851,0.101529,0.085980,0.102375,0.144231
fraud_adjustment_mean,0.992761,1.001064,1.011303,1.015484,1.009058,1.000000
continuous_vehicle_age_mean,4.691898,4.730900,4.804230,4.755293,4.675061,4.926282
kmx_npc_flag,0.600746,0.607810,0.617125,0.644462,0.625717,0.628205
high_pti_npc,0.094350,0.108093,0.106422,0.099923,0.099918,0.115385
student_loan_flag,0.231876,0.239955,0.207339,0.219985,0.215397,0.201923
high_sales_price_flag,0.145522,0.143181,0.168807,0.155693,0.177723,0.150641
driver_flag,0.002132,0.001698,0.001835,0.000775,0.000819,0.000000
louisiana_flag,0.005864,0.005093,0.006728,0.004648,0.004095,0.006410
georgia_flag,0.068763,0.087153,0.078899,0.068939,0.083538,0.064103
txca_flag,0.330490,0.301641,0.300917,0.316809,0.324324,0.314103
chime_flag,0.302772,0.307301,0.265443,0.244771,0.248157,0.214744
low_bureau_flag,0.052239,0.040181,0.045260,0.035631,0.036036,0.041667
cd_perc_flag,0.130597,0.113186,0.123547,0.114640,0.132678,0.176282
open_tl_flag,0.092217,0.082060,0.114373,0.097599,0.094185,0.080128
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.397655,0.391058,0.381651,0.066615,0.000000,0.000000
mtn_model_3.2_pct,0.498934,0.492360,0.509480,0.817196,0.884521,0.887821
mtn_model_4.1_pct,0.103412,0.116582,0.108869,0.116189,0.115479,0.112179
--- N_RECORDS,1876.000000,1767.000000,1635.000000,1291.000000,1221.000000,312.000000

--- All KMX Gross Loss Attribution ---

,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25
Low FICO (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Low Vantage (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
High PTI (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Loss Scale Div (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Secured Credit (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Auth Tradelines (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Soft Pull (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Fraud Adjustment,-0.199532,0.000370,0.215263,1.843466,2.645161,-0.000000
Clip (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
Vehicle Age (3.0),0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000
NPC,0.014853,0.000513,0.029771,0.045218,0.313991,-0.044741
Student Loans,-0.215704,-0.002393,-0.222508,-1.210638,-3.070474,0.471269
High Sales Price (4.1),0.024027,0.000108,0.025268,0.205066,0.227100,-0.020933
Driver Flag,0.008441,0.000095,0.005501,0.013283,0.034580,-0.000000
Louisiana,0.054057,0.000620,0.046339,0.196696,0.413268,-0.091140
Georgia,0.189028,0.003009,0.151351,0.841233,2.462353,-0.251819
TX / CA,-0.678817,-0.007958,-0.443026,-2.947760,-7.280682,0.940032
State Counter,0.167518,0.002098,0.117535,0.750495,1.796478,-0.239265
Secured Credit / Chime (3.1+),1.581948,0.020441,0.941162,5.018225,12.632746,-1.286141
Job Time (3.1+),0.386830,0.005154,0.212777,1.467203,2.777670,-0.479381
Existing DQ (3.1+),0.100158,0.000963,0.037674,0.169760,1.436153,-0.170401
Employment Type (3.1+),0.021994,0.000291,0.012200,0.123709,0.221414,-0.052031
Auth Tradelines (3.1+),-0.218148,-0.002656,-0.143891,-0.903410,-2.273295,0.342519
Soft Pull (3.1+),1.628482,0.018237,1.152088,6.774325,16.840170,-2.330563
Blanket Adjustment (3.1+),-2.617623,-0.033145,-1.825436,-11.434801,-27.958345,3.803444
Clip (3.1+),-0.064929,-0.000690,-0.133189,-0.575395,-0.793132,-0.010773
--- TOTAL (check),0.182583,0.005056,0.178879,0.376676,0.425154,0.580074

In [10]:
def build_ragu_decomposition(all_df_model, original_model_scores_df, lob='KMX'):
    '''Build RAGU decomposition table from model results.'''
    if all_df_model is None or len(all_df_model) == 0:
        return None

    raw = all_df_model.loc[[lob]][['vintage', 'ms_original', 'gross_loss_impact', 'recovery_impact',
                                   'ltv_impact', 'apr_impact', 'ragu_score', 'ltv']].reset_index(drop=True).set_index('vintage').T.copy()

    ms_for_lob = original_model_scores_df[original_model_scores_df.lob == lob].copy()
    ms_for_lob = ms_for_lob[ms_for_lob['period'].isin(raw.columns)]
    if len(ms_for_lob) > 0:
        raw = pd.concat([raw, ms_for_lob.drop(columns=['lob', 'amt_financed']).rename(columns={'period': 'vintage'}).set_index('vintage').T.rename({'model_score': 'contract_model_score'})])

    raw.index = ['Mountain3 Score', 'Gross Loss Impact', 'Recovery Impact',
                 'LTV Impact', 'APR Impact', 'RAGU Score', 'LTV', 'Contract Model Score']

    decomp = pd.DataFrame(index=['Contract Model Score', 'Mountain3 Score',
                                  'Gross Loss Adjustments', 'Recovery Adjustments',
                                  'LTV Adjustments', 'APR Adjustments',
                                  'RAGU Score', 'LTV'],
                           columns=raw.columns)

    decomp.loc['Contract Model Score'] = raw.loc['Contract Model Score']
    decomp.loc['Mountain3 Score'] = raw.loc['Mountain3 Score'] - raw.loc['Contract Model Score']
    decomp.loc['Gross Loss Adjustments'] = raw.loc['Gross Loss Impact']
    decomp.loc['Recovery Adjustments'] = raw.loc['Recovery Impact']
    decomp.loc['LTV Adjustments'] = raw.loc['LTV Impact']
    decomp.loc['APR Adjustments'] = raw.loc['APR Impact']
    decomp.loc['RAGU Score'] = raw.loc['RAGU Score']
    decomp.loc['LTV'] = raw.loc['LTV']

    return decomp

# Build original_model_scores for each MTN model subset
original_model_scores_by_model = {}
for mtn_model_filter in MTN_MODELS + ['All KMX']:
    if mtn_model_filter == 'All KMX':
        original_model_scores_by_model['All KMX'] = ms_df
    else:
        ula_subset = ula_df_total[ula_df_total.mtn_model == mtn_model_filter]
        if len(ula_subset) > 0:
            original_model_scores_by_model[mtn_model_filter] = rebuild_ms_df(ula_subset)
        else:
            original_model_scores_by_model[mtn_model_filter] = pd.DataFrame(columns=['period', 'lob', 'model_score', 'amt_financed'])

# Write to Excel
with pd.ExcelWriter(EXCEL_OUTPUT, engine='openpyxl') as writer:
    for mtn_model_filter in ['All KMX'] + MTN_MODELS:
        label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
        all_df_model = results_by_model.get(mtn_model_filter)
        orig_ms = original_model_scores_by_model.get(mtn_model_filter)

        if all_df_model is None or len(all_df_model) == 0:
            print(f'{label}: No results to export, writing empty sheet.')
            pd.DataFrame({'Note': [f'No loans found for {label}']}).to_excel(writer, sheet_name=label, index=False)
            continue

        xlsx_df = build_ragu_decomposition(all_df_model, orig_ms, lob='KMX')
        if xlsx_df is not None:
            xlsx_df.to_excel(writer, sheet_name=label)
            print(f'\n{label} RAGU Decomposition:')
            display(xlsx_df)
        else:
            pd.DataFrame({'Note': [f'Could not build decomposition for {label}']}).to_excel(writer, sheet_name=label, index=False)

    # Diagnostics sheets
    for mtn_model_filter in ['All KMX'] + MTN_MODELS:
        label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
        diag_data = diag_results_by_model.get(mtn_model_filter, (None, None, None))
        output_df, flags_df, attribution_df = diag_data

        sheet_mult = f'{label} Mult Steps'[:31]
        sheet_flags = f'{label} Flags'[:31]
        sheet_attr = f'{label} Attribution'[:31]

        if output_df is not None:
            output_df.to_excel(writer, sheet_name=sheet_mult)
        if flags_df is not None:
            flags_df.to_excel(writer, sheet_name=sheet_flags)
        if attribution_df is not None:
            attribution_df.to_excel(writer, sheet_name=sheet_attr)

print(f'\nExported to: {EXCEL_OUTPUT}')
print("[PROGRESS] Export Complete")

All KMX RAGU Decomposition:

vintage,2025-11-30/2025-12-06,2025-12-07/2025-12-13,2025-12-14/2025-12-20,2025-12-21/2025-12-27,2025-12-28/2026-01-03,2026-01-04/2026-01-10,2026-01-11/2026-01-17,2026-01-18/2026-01-24,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11,2026-04-12/2026-04-18,2026-04-19/2026-04-25
Contract Model Score,141.876946,142.139621,141.775187,141.957509,142.055772,141.774719,141.49681,141.899148,141.600977,142.161469,142.380543,142.071714,142.063357,142.386654,142.481352,142.596629,142.675067,143.04651,142.893235,142.635792,143.347729
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,1.088939,1.22983,0.741891,0.777234,0.848139,0.521478,0.505559,0.645881,0.548297,0.586527,0.595631,-0.124317,-0.432309,-0.043651,-0.00457,0.182583,0.005056,0.178879,0.376676,0.425154,0.580074
Recovery Adjustments,1.305283,0.852443,1.494383,0.887119,1.341174,0.503374,0.67308,0.656552,0.605375,0.711589,0.26478,0.374905,0.088973,0.102626,0.656406,0.773252,0.862886,0.787263,0.758972,1.020917,1.555704
LTV Adjustments,-0.326046,1.131262,0.710486,0.90732,0.60155,0.545147,0.544337,0.024191,0.650091,0.395629,0.600958,0.828224,0.511399,0.346333,0.246315,0.539406,0.546457,0.54617,0.194025,0.417503,-1.045482
APR Adjustments,0.685136,0.774791,0.812633,0.988939,0.914396,0.09685,0.104489,0.173995,0.371827,0.411511,0.690206,0.659046,0.17732,0.53722,0.8133,0.840703,0.551128,0.703962,0.614129,0.573515,0.143813
RAGU Score,144.630258,146.127947,145.53458,145.518121,145.761032,143.441568,143.324275,143.399767,143.776567,144.266725,144.532118,143.809571,142.408739,143.329182,144.192804,144.932574,144.640594,145.262784,144.837036,145.072881,144.581838
LTV,1.610072,1.524077,1.547949,1.53669,1.554252,1.557535,1.557582,1.588531,1.551437,1.566306,1.554286,1.541194,1.559506,1.56922,1.575165,1.55787,1.557459,1.557475,1.578291,1.565017,1.656206

MTN 3.0 RAGU Decomposition:

vintage                2025-11-30/2025-12-06
Contract Model Score              139.536387
Mountain3 Score                          0.0
Gross Loss Adjustments              1.367279
Recovery Adjustments                0.045978
LTV Adjustments                    -0.979686
APR Adjustments                     0.594396
RAGU Score                        140.564354
LTV                                 1.651877

MTN 3.1 RAGU Decomposition:

vintage,2025-11-30/2025-12-06,2025-12-07/2025-12-13,2025-12-14/2025-12-20,2025-12-21/2025-12-27,2025-12-28/2026-01-03,2026-01-04/2026-01-10,2026-01-11/2026-01-17,2026-01-18/2026-01-24,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11
Contract Model Score,142.641358,142.139621,141.804005,141.792301,141.865362,141.700507,141.372322,141.791998,141.117699,141.889291,142.186004,141.913026,141.406028,142.060512,141.880186,142.240622,142.176706,142.846775,143.088368
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,0.997776,1.22983,0.861088,0.862644,1.070936,0.700995,0.748261,0.823165,0.775581,0.737805,0.791221,-0.042396,-0.349698,-0.143444,0.165047,0.416094,0.155111,0.230932,0.625091
Recovery Adjustments,1.727392,0.852443,1.387904,0.962268,1.32501,0.38585,0.541744,0.632411,0.70837,0.632028,0.396456,0.457671,0.088939,0.155736,0.676048,1.13807,0.698325,0.646572,-0.158607
LTV Adjustments,-0.104521,1.131262,0.566393,0.942675,0.390383,0.472067,0.520215,-0.025233,0.583822,0.242756,0.486162,0.59966,0.383595,0.709837,0.484655,0.604148,0.737345,0.666494,-1.703802
APR Adjustments,0.714856,0.774791,0.727144,0.985017,0.786687,0.045169,0.09969,0.163558,0.40157,0.434738,0.72932,0.848262,0.306329,0.940105,0.955229,1.09707,0.658109,0.926114,0.984015
RAGU Score,145.976861,146.127947,145.346534,145.544905,145.438378,143.304589,143.282232,143.385899,143.587043,143.936618,144.589162,143.776223,141.835192,143.722745,144.161166,145.496003,144.425596,145.316886,142.835065
LTV,1.59638,1.524077,1.556297,1.534685,1.566616,1.56181,1.558991,1.591536,1.555282,1.575378,1.560984,1.554361,1.567017,1.547986,1.561072,1.554101,1.546403,1.550488,1.700799

MTN 3.2 RAGU Decomposition:

vintage,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11,2026-04-12/2026-04-18,2026-04-19/2026-04-25
Contract Model Score,142.118567,142.297686,141.383512,141.863417,141.927108,142.053173,142.388615,142.360023,142.036108,142.437178,142.346796,142.367422,143.024535
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,0.283252,0.612819,0.671006,-0.010106,-0.293954,0.189952,0.072738,0.129778,-0.022333,0.292106,0.484246,0.55448,0.658462
Recovery Adjustments,1.434241,0.825389,0.049675,0.176598,0.098091,-0.015211,0.449393,0.548123,1.070045,0.808906,0.8234,0.992817,1.964122
LTV Adjustments,-0.327164,0.572921,0.658483,0.895801,0.319903,-0.227754,-0.156724,0.160128,0.373182,0.331701,0.346624,0.370074,-0.79033
APR Adjustments,0.124431,0.041496,0.284926,0.322741,-0.058212,0.098373,0.575393,0.499423,0.20708,0.424118,0.438191,0.546934,0.108041
RAGU Score,143.633326,144.350312,143.047602,143.248452,141.992937,142.098534,143.329416,143.697476,143.664082,144.294009,144.439257,144.831727,144.96483
LTV,1.610142,1.555916,1.550951,1.537344,1.570787,1.603968,1.599585,1.580324,1.567632,1.570087,1.569203,1.567816,1.639545

MTN 4.1 RAGU Decomposition:

vintage,2025-12-14/2025-12-20,2025-12-21/2025-12-27,2025-12-28/2026-01-03,2026-01-04/2026-01-10,2026-01-11/2026-01-17,2026-01-18/2026-01-24,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11,2026-04-12/2026-04-18,2026-04-19/2026-04-25
Contract Model Score,141.366824,143.015816,143.451321,142.266283,142.30266,142.672288,144.256069,143.888991,144.476556,143.55873,145.297113,145.106952,144.987739,145.002135,146.979511,146.487574,146.490621,144.706375,145.92277
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,-0.938976,0.233329,-0.784207,-0.674341,-1.06448,-0.636178,-0.715642,-0.4848,-0.824067,-0.923423,-1.499922,-0.769102,-0.953048,-0.444409,-0.39169,-0.507266,-0.489527,-0.568986,-0.101401
Recovery Adjustments,3.023892,0.413572,1.459733,1.298141,1.536532,0.831213,-0.463144,1.170871,-0.46146,0.749835,0.038731,0.468361,1.609146,0.458366,0.555898,1.186116,0.839465,1.239843,-1.753913
LTV Adjustments,2.921514,0.684318,2.257514,1.04238,0.701439,0.387251,1.656275,1.33814,1.377146,1.646784,2.144365,1.865561,1.439133,2.141467,0.628655,1.114804,0.296649,0.787834,-3.06478
APR Adjustments,2.018163,1.013911,1.85007,0.441111,0.135537,0.249468,0.323397,0.576541,0.747007,1.057822,0.969595,1.130593,1.460847,1.441876,1.621648,1.19394,1.601882,0.77785,0.454807
RAGU Score,148.391418,145.360946,148.234431,144.373573,143.611689,143.504042,145.056955,146.489743,145.315182,146.089747,146.949882,147.802365,148.543816,148.599435,149.394023,149.47517,148.73909,146.942915,141.457482
LTV,1.430236,1.549458,1.463662,1.529058,1.54847,1.566801,1.495305,1.512609,1.510466,1.495816,1.469514,1.484136,1.507072,1.469664,1.552679,1.524997,1.572168,1.543505,1.801052

Exported to: new_kmx_models.xlsx
[PROGRESS] Export Complete

In [11]:
print("="*80)
print("  VERIFICATION: All KMX vs bareboned_ragu_new.ipynb")
print("="*80)

all_kmx_df = results_by_model.get('All KMX')
if all_kmx_df is not None and len(all_kmx_df) > 0:
    try:
        reference_df = pd.read_csv('all_df.csv')
        ref_kmx = reference_df[reference_df.lob == 'KMX'].copy() if 'lob' in reference_df.columns else pd.DataFrame()

        if len(ref_kmx) > 0:
            our_kmx = all_kmx_df.reset_index()
            our_kmx = our_kmx[our_kmx.lob == 'KMX'][['vintage', 'ms_original', 'gross_loss_impact', 'recovery_impact', 'ragu_score', 'loss_multiplier']].copy()
            our_kmx = our_kmx.set_index('vintage')

            ref_cols = ['vintage', 'ms_original', 'ragu_score', 'loss_multiplier']
            ref_available = [c for c in ref_cols if c in ref_kmx.columns]
            ref_kmx_compare = ref_kmx[ref_available].copy()
            ref_kmx_compare = ref_kmx_compare.set_index('vintage')

            common_vintages = sorted(set(our_kmx.index) & set(ref_kmx_compare.index))

            if common_vintages:
                comparison = pd.DataFrame(index=common_vintages)
                for col in [c for c in ['ragu_score', 'loss_multiplier'] if c in ref_kmx_compare.columns]:
                    comparison[f'{col}_ours'] = our_kmx.loc[common_vintages, col].values
                    comparison[f'{col}_ref'] = ref_kmx_compare.loc[common_vintages, col].values
                    comparison[f'{col}_diff'] = comparison[f'{col}_ours'] - comparison[f'{col}_ref']

                print(f"\nComparing {len(common_vintages)} common vintages:")
                display(comparison)
            else:
                print("No common vintages found.")
        else:
            print("No KMX rows found in reference all_df.csv.")
    except FileNotFoundError:
        print("all_df.csv not found. Run bareboned_ragu_new.ipynb first to generate the reference file.")
    except Exception as e:
        print(f"Error loading reference data: {e}")
        print("\nManually compare the 'All KMX' sheet in new_kmx_models.xlsx")
        print("against the KMX rows in barebones_ragu.xlsx")
else:
    print("No 'All KMX' results to verify.")

# Summary table
print("\n" + "="*80)
print("  SUMMARY: RAGU Scores by MTN Model (most recent vintage)")
print("="*80)
summary_rows = []
baseline_ltv = BASELINES['KMX']['ltv']
for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    model_df = results_by_model.get(mtn_model_filter)
    if model_df is not None and len(model_df) > 0:
        kmx_rows = model_df.reset_index()
        kmx_rows = kmx_rows[kmx_rows.lob == 'KMX']
        if len(kmx_rows) > 0:
            last_vintage = kmx_rows.vintage.max()
            last_row = kmx_rows[kmx_rows.vintage == last_vintage].iloc[0]
            summary_rows.append({
                'Model': label,
                'Latest Vintage': last_vintage,
                'Contract MS': last_row.get('ms_original', float('nan')),
                'Gross Loss Impact': last_row.get('gross_loss_impact', float('nan')),
                'Recovery Impact': last_row.get('recovery_impact', float('nan')),
                'LTV Impact': last_row.get('ltv_impact', float('nan')),
                'APR Impact': last_row.get('apr_impact', float('nan')),
                'RAGU Score': last_row.get('ragu_score', float('nan')),
                'LTV': last_row.get('ltv', float('nan')),
                'Loss Multiplier': last_row.get('loss_multiplier', float('nan')),
                'N Vintages': len(kmx_rows),
            })

if summary_rows:
    summary_df = pd.DataFrame(summary_rows).set_index('Model')
    display(summary_df)

    print(f"\nRAGU decomposition:")
    print(f"  baseline_ltv = {baseline_ltv}")
    print(f"  baseline_apr = {BASELINES['KMX']['apr']}")
    print(f"  RAGU Score = (unit_loss * recovery * baselined_recovery) + ltv_impact + apr_impact")
else:
    print("No results available.")

================================================================================
  VERIFICATION: All KMX vs bareboned_ragu_new.ipynb
================================================================================

Comparing 17 common vintages:

                       ragu_score_ours  ragu_score_ref  ragu_score_diff
2025-12-28/2026-01-03       145.761032      145.830481        -0.069450
2026-01-04/2026-01-10       143.441568      143.488082        -0.046514
2026-01-11/2026-01-17       143.324275      143.401251        -0.076976
2026-01-18/2026-01-24       143.399767      143.490878        -0.091111
2026-01-25/2026-01-31       143.776567      143.852014        -0.075447
2026-02-01/2026-02-07       144.266725      144.343523        -0.076798
2026-02-08/2026-02-14       144.532118      144.601110        -0.068992
2026-02-15/2026-02-21       143.809571      143.884296        -0.074725
2026-02-22/2026-02-28       142.408739      142.493989        -0.085249
2026-03-01/2026-03-07       143.329182      143.399015        -0.069833
2026-03-08/2026-03-14       144.192804      144.237220        -0.044416
2026-03-15/2026-03-21       144.932574      144.997440        -0.064866
2026-03-22/2026-03-28       144.640594      144.711455        -0.070861
2026-03-29/2026-04-04       145.262784      145.294603        -0.031819
2026-04-05/2026-04-11       144.837036      144.880395        -0.043359
2026-04-12/2026-04-18       145.072881      145.307584        -0.234703
2026-04-19/2026-04-25       144.581838      145.516770        -0.934932

================================================================================
  SUMMARY: RAGU Scores by MTN Model (most recent vintage)
================================================================================

,Latest Vintage,Contract MS,Gross Loss Impact,Recovery Impact,LTV Impact,APR Impact,RAGU Score,LTV,Loss Multiplier,N Vintages
Model,,,,,,,,,,
MTN 3.0,2025-11-30/2025-12-06,139.536387,1.367279,0.045978,-0.979686,0.594396,140.564354,1.651877,0.945309,1
MTN 3.1,2026-04-05/2026-04-11,143.088368,0.625091,-0.158607,-1.703802,0.984015,142.835065,1.700799,0.974996,19
MTN 3.2,2026-04-19/2026-04-25,143.024535,0.658462,1.964122,-0.790330,0.108041,144.964830,1.639545,0.973662,13
MTN 4.1,2026-04-19/2026-04-25,145.922770,-0.101401,-1.753913,-3.064780,0.454807,141.457482,1.801052,1.004056,19
All KMX,2026-04-19/2026-04-25,143.347729,0.580074,1.555704,-1.045482,0.143813,144.581838,1.656206,0.976797,21

RAGU decomposition:
  baseline_ltv = 1.59
  baseline_apr = 0.25
  RAGU Score = (unit_loss * recovery * baselined_recovery) + ltv_impact + apr_impact