In [1]:
# =============================================================================
# CELL 1: CONFIGURATION
# =============================================================================

granularity = 'w'  # 'q' = quarterly, 'm' = monthly, 'w' = weekly

START_DATE = '2026-01-01'
END_DATE = None

run_every_query = False  # True = run SQL; False = use cache/ pickles from bareboned_ragu_new

DATE_COL_MAP = {'q': 'book_date', 'm': 'book_date', 'w': 'app_date'}

LOBS = ['AN', 'FRN', 'STG', 'FLD', 'ENT']

BASELINES = {
    'AN':  {'ltv': 1.94, 'new_recovery_unadjusted': 0.58, 'apr': 0.25},
    'FRN': {'ltv': 1.94, 'new_recovery_unadjusted': 0.54, 'apr': 0.25},
    'STG': {'ltv': 1.94, 'new_recovery_unadjusted': 0.60, 'apr': 0.25},
    'FLD': {'ltv': 1.45, 'new_recovery_unadjusted': 0.54, 'apr': 0.235},
    'ENT': {'ltv': 1.45, 'new_recovery_unadjusted': 0.55, 'apr': 0.235},
}

MODEL_PARAMS = {
    'mean_unit_loss': 0.5,
    'unit_loss_to_model_score': 0.02,
}

DIAG_N_VINTAGES = 6

EXCEL_OUTPUT = 'nonkmx_gl_diagnostics.xlsx'

In [2]:
# Parameters
granularity = "w"
START_DATE = "2026-01-01"
END_DATE = None
run_every_query = False
LOBS = ["AN", "FRN", "STG", "FLD", "ENT"]
BASELINES = {"AN": {"ltv": 1.94, "new_recovery_unadjusted": 0.58, "apr": 0.25}, "FRN": {"ltv": 1.94, "new_recovery_unadjusted": 0.54, "apr": 0.25}, "STG": {"ltv": 1.94, "new_recovery_unadjusted": 0.6, "apr": 0.25}, "FLD": {"ltv": 1.45, "new_recovery_unadjusted": 0.54, "apr": 0.235}, "ENT": {"ltv": 1.45, "new_recovery_unadjusted": 0.55, "apr": 0.235}}
MODEL_PARAMS = {"mean_unit_loss": 0.5, "unit_loss_to_model_score": 0.02}
DIAG_N_VINTAGES = 6

In [3]:
# =============================================================================
# CELL 2: IMPORTS AND DERIVED CONFIGURATION
# =============================================================================
import pandas as pd
import numpy as np
import pyodbc
import pickle
import warnings
import math
import os
import openpyxl

pd.set_option('display.max_columns', 100)
pd.set_option('display.min_rows', 100)

date_col = DATE_COL_MAP[granularity]
start_date = pd.Timestamp(START_DATE)
end_date = pd.Timestamp(END_DATE) if END_DATE else pd.Timestamp.today().normalize()

PERIOD_FREQ_MAP = {'q': 'Q', 'm': 'M', 'w': 'W-SAT'}
period_freq = PERIOD_FREQ_MAP[granularity]

start_period = start_date.to_period(period_freq)
end_period = end_date.to_period(period_freq)

min_date_sql = f"'{START_DATE}'"

print(f"Granularity: {granularity}")
print(f"Date column: {date_col}")
print(f"Period range: {start_period} to {end_period}")

Granularity: w
Date column: app_date
Period range: 2025-12-28/2026-01-03 to 2026-05-03/2026-05-09

In [4]:
# =============================================================================
# CELL 3: UTILITY FUNCTIONS
# =============================================================================

def run_sql(filename, sub_list=None, connection=None, filename_is_query=False):
    if sub_list is None:
        sub_list = []
    if filename_is_query:
        query = filename
    else:
        with open(filename, 'r') as file:
            query = file.read()
    for text, var in sub_list:
        query = query.replace(text, var)
    if connection is None:
        with pyodbc.connect("DSN=Redshift_prod_new") as conn:
            warnings.filterwarnings("ignore", category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings("default", category=UserWarning)
            return df
    else:
        warnings.filterwarnings("ignore", category=UserWarning)
        df = pd.read_sql_query(sql=query, con=connection)
        warnings.filterwarnings("default", category=UserWarning)
        return df


def store_pickle(data, filename):
    if isinstance(data, str):
        data, filename = filename, data
    with open(filename, 'wb') as file:
        pickle.dump(data, file)


def get_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)


def cached_sql(filename, pickle_name, sub_list=None, connection=None, force_refresh=False):
    if force_refresh or not os.path.exists(pickle_name):
        df = run_sql(filename, sub_list=sub_list, connection=connection)
        store_pickle(df, pickle_name)
        return df
    return get_pickle(pickle_name)


def weighted_average_and_sum(group, metrics):
    if isinstance(metrics, str):
        weighted_avg = (group[metrics] * group.amt_financed).sum() / group.amt_financed.sum()
        return pd.Series({metrics: weighted_avg, 'amt_financed': group.amt_financed.sum()})
    result_dict = {'amt_financed': group.amt_financed.sum()}
    for metric in metrics:
        weighted_avg = (group[metric] * group.amt_financed).sum() / group.amt_financed.sum()
        result_dict[metric] = weighted_avg
    return pd.Series(result_dict)


def format_vintage(period_series):
    if len(period_series) == 0:
        return period_series.astype(str)
    freq = period_series.iloc[0].freqstr
    if freq == 'Q-DEC':
        return period_series.dt.year.astype(str) + ' Q' + period_series.dt.quarter.astype(str)
    elif freq == 'M':
        return period_series.dt.year.astype(str) + ' M' + period_series.dt.month.astype(str).str.zfill(2)
    return period_series.astype(str)

In [5]:
# =============================================================================
# CELL 4: ULA MULTIPLIER FUNCTIONS (NONKMX)
# =============================================================================

def get_ula_multiplier_nonkmx(ula_df, leave_out='None'):
    ula_df['loss_multiplier'] = 1.0

    if leave_out != 'Previous ACA chargeoff':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.prev_co_flag
    if leave_out != 'Small amount financed':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.small_amt_financed_flag * (1 - ula_df.pricing_change_flag)
    if leave_out != 'Zero cash down':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.zero_cash_down_flag * (1 - ula_df.pricing_change_flag)
    if leave_out != 'High mileage vehicle':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_mileage_vehicle_flag
    if leave_out != 'High PTI':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_pti_flag * (1 - ula_df.pricing_change_flag)
    if leave_out != 'Car make':
        ula_df.loss_multiplier *= (1 + 0.1 * ula_df.car_make_penalty_flag
                                   - 0.1 * ula_df.car_make_benefit_flag
                                   - 0.1 * ula_df.pricing_change_flag * ula_df.car_make_benefit_flag)
    if leave_out != 'Theft risk':
        ula_df.loss_multiplier *= (0.987 + 0.099 * ula_df.theft_risk_flag * (1 - ula_df.pricing_change_flag)
                                   + 0.013 * ula_df.pricing_change_flag)
    if leave_out != 'MCY high model score, low mileage':
        ula_df.loss_multiplier *= 1 - 0.2 * ula_df.mcy_low_mileage_flag
    if leave_out != 'Weekday/weekend decision':
        ula_df.loss_multiplier *= 1 - 0.05 * ula_df.weekend_flag + 0.02 * ula_df.weekday_flag
    if leave_out != 'Student Loans':
        ula_df.loss_multiplier *= 1 + (0.1 * ula_df.student_loan_flag
            - np.minimum(np.maximum((ula_df.cd_model_score - (130 - 2 * ula_df.ent_flag)) * 0.006, 0), 0.03)
            * (1 - ula_df.student_loan_flag)) * ula_df.student_loans_cutoff_date
    if leave_out != 'Low PTI':
        ula_df.loss_multiplier *= 1 + (-0.03 * np.minimum(ula_df.cd_model_score, 135) + 3.9) * ula_df.low_pti_flag
    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loss_multiplier *= 0.966 + 0.273 * ula_df.nonkmx_chime_flag
    if leave_out != 'Employment type':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.seasonal_employment_flag - 0.1 * ula_df.waiter_employment_flag
    if leave_out != 'Authorized tradelines':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.nonkmx_auth_tradelines_flag
    if leave_out != 'Fraud':
        ula_df.loss_multiplier *= 1 + (ula_df.fraud_adjustment - 1)
    if leave_out != 'Driver flag':
        ula_df.loss_multiplier *= 1 + 0.15 * ula_df.driver_flag
    if leave_out != 'Clip':
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.8, 2)
    if leave_out != 'Dealer Level (Non-KMX)':
        ula_df.loss_multiplier *= ula_df.pricing_scalar
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.7, 1.4)

    return ula_df


def get_ula_multiplier_nonkmx_diag(ula_df, leave_out='None', verbose=True):
    """Identical logic to get_ula_multiplier_nonkmx, plus per-step mean tracking."""
    steps = {}
    def _record(label, df):
        steps[label] = df.loss_multiplier.mean()

    ula_df['loss_multiplier'] = 1.0
    _record('00_initial', ula_df)
    if verbose:
        print(f"00_initial  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Previous ACA chargeoff':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.prev_co_flag
    _record('01_prev_aca_chargeoff', ula_df)
    if verbose:
        print(f"01_prev_co  | flag mean: {ula_df.prev_co_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Small amount financed':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.small_amt_financed_flag * (1 - ula_df.pricing_change_flag)
    _record('02_small_amt_financed', ula_df)
    if verbose:
        print(f"02_small_af | flag mean: {ula_df.small_amt_financed_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Zero cash down':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.zero_cash_down_flag * (1 - ula_df.pricing_change_flag)
    _record('03_zero_cash_down', ula_df)
    if verbose:
        print(f"03_zero_cd  | flag mean: {ula_df.zero_cash_down_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High mileage vehicle':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_mileage_vehicle_flag
    _record('04_high_mileage', ula_df)
    if verbose:
        print(f"04_high_mi  | flag mean: {ula_df.high_mileage_vehicle_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High PTI':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_pti_flag * (1 - ula_df.pricing_change_flag)
    _record('05_high_pti', ula_df)
    if verbose:
        print(f"05_high_pti | flag mean: {ula_df.high_pti_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Car make':
        ula_df.loss_multiplier *= (1 + 0.1 * ula_df.car_make_penalty_flag
                                   - 0.1 * ula_df.car_make_benefit_flag
                                   - 0.1 * ula_df.pricing_change_flag * ula_df.car_make_benefit_flag)
    _record('06_car_make', ula_df)
    if verbose:
        print(f"06_car_make | penalty: {ula_df.car_make_penalty_flag.mean():.6f}  benefit: {ula_df.car_make_benefit_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Theft risk':
        ula_df.loss_multiplier *= (0.987 + 0.099 * ula_df.theft_risk_flag * (1 - ula_df.pricing_change_flag)
                                   + 0.013 * ula_df.pricing_change_flag)
    _record('07_theft_risk', ula_df)
    if verbose:
        print(f"07_theft    | flag mean: {ula_df.theft_risk_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'MCY high model score, low mileage':
        ula_df.loss_multiplier *= 1 - 0.2 * ula_df.mcy_low_mileage_flag
    _record('08_mcy_low_mileage', ula_df)
    if verbose:
        print(f"08_mcy_low  | flag mean: {ula_df.mcy_low_mileage_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Weekday/weekend decision':
        ula_df.loss_multiplier *= 1 - 0.05 * ula_df.weekend_flag + 0.02 * ula_df.weekday_flag
    _record('09_weekend_weekday', ula_df)
    if verbose:
        print(f"09_wknd/day | weekend: {ula_df.weekend_flag.mean():.6f}  weekday: {ula_df.weekday_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Student Loans':
        ula_df.loss_multiplier *= 1 + (0.1 * ula_df.student_loan_flag
            - np.minimum(np.maximum((ula_df.cd_model_score - (130 - 2 * ula_df.ent_flag)) * 0.006, 0), 0.03)
            * (1 - ula_df.student_loan_flag)) * (ula_df.student_loans_cutoff_date)
    _record('10_student_loans', ula_df)
    if verbose:
        print(f"10_stud_ln  | flag mean: {ula_df.student_loan_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low PTI':
        ula_df.loss_multiplier *= 1 + (-0.03 * np.minimum(ula_df.cd_model_score, 135) + 3.9) * ula_df.low_pti_flag
    _record('11_low_pti', ula_df)
    if verbose:
        print(f"11_low_pti  | flag mean: {ula_df.low_pti_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loss_multiplier *= 0.966 + 0.273 * ula_df.nonkmx_chime_flag
    _record('12_chime', ula_df)
    if verbose:
        print(f"12_chime    | flag mean: {ula_df.nonkmx_chime_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Employment type':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.seasonal_employment_flag - 0.1 * ula_df.waiter_employment_flag
    _record('13_employment_type', ula_df)
    if verbose:
        n = len(ula_df)
        print(f"13_employ   | seasonal: {ula_df.seasonal_employment_flag.sum()/n:.6f}  waiter: {ula_df.waiter_employment_flag.sum()/n:.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.nonkmx_auth_tradelines_flag
    _record('14_auth_tradelines', ula_df)
    if verbose:
        print(f"14_auth_tl  | flag mean: {ula_df.nonkmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Fraud':
        ula_df.loss_multiplier *= 1 + (ula_df.fraud_adjustment - 1)
    _record('15_fraud', ula_df)
    if verbose:
        print(f"15_fraud    | fraud_adj mean: {ula_df.fraud_adjustment.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Driver flag':
        ula_df.loss_multiplier *= 1 + 0.15 * ula_df.driver_flag
    _record('16_driver_flag', ula_df)
    if verbose:
        print(f"16_driver   | flag mean: {ula_df.driver_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.8, 2)

    if leave_out != 'Dealer Level (Non-KMX)':
        ula_df.loss_multiplier *= ula_df.pricing_scalar
    _record('17_pricing_scalar', ula_df)
    if verbose:
        print(f"17_pricing  | scalar mean: {ula_df.pricing_scalar.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Dealer Level (Non-KMX)':
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.7, 1.4)
    _record('18_final', ula_df)
    if verbose:
        print(f"18_final    | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}  (post all clips)")

    n = len(ula_df)
    flags = {
        'prev_co_flag': ula_df.prev_co_flag.mean(),
        'small_amt_financed_flag': ula_df.small_amt_financed_flag.mean(),
        'pricing_change_flag': ula_df.pricing_change_flag.mean(),
        'zero_cash_down_flag': ula_df.zero_cash_down_flag.mean(),
        'high_mileage_vehicle_flag': ula_df.high_mileage_vehicle_flag.mean(),
        'high_pti_flag': ula_df.high_pti_flag.mean(),
        'car_make_penalty_flag': ula_df.car_make_penalty_flag.mean(),
        'car_make_benefit_flag': ula_df.car_make_benefit_flag.mean(),
        'theft_risk_flag': ula_df.theft_risk_flag.mean(),
        'mcy_low_mileage_flag': ula_df.mcy_low_mileage_flag.mean(),
        'weekend_flag': ula_df.weekend_flag.mean(),
        'weekday_flag': ula_df.weekday_flag.mean(),
        'student_loan_flag': ula_df.student_loan_flag.mean(),
        'student_loans_cutoff_date': ula_df.student_loans_cutoff_date.mean(),
        'low_pti_flag': ula_df.low_pti_flag.mean(),
        'nonkmx_chime_flag': ula_df.nonkmx_chime_flag.mean(),
        'seasonal_employment_pct': ula_df.seasonal_employment_flag.sum() / n,
        'waiter_employment_pct': ula_df.waiter_employment_flag.sum() / n,
        'nonkmx_auth_tradelines_flag': ula_df.nonkmx_auth_tradelines_flag.mean(),
        'fraud_adjustment_mean': ula_df.fraud_adjustment.mean(),
        'driver_flag': ula_df.driver_flag.mean(),
        'pricing_scalar_mean': ula_df.pricing_scalar.mean(),
    }

    return ula_df, pd.Series(steps), pd.Series(flags)

In [6]:
# =============================================================================
# CELL 5: DATA FETCH (shared cache/ from bareboned_ragu_new)
# =============================================================================

os.makedirs('cache', exist_ok=True)
force = run_every_query

need_conn = force or not all(
    os.path.exists(p) for p in ('cache/ula_v1.pkl', 'cache/dla_v1.pkl', 'cache/new_recovery_v1.pkl')
)

if need_conn:
    with pyodbc.connect("DSN=Redshift_prod_new") as conn:
        ula_df_total = cached_sql(
            'vintage_level_ula_query.txt', 'cache/ula_v1.pkl',
            sub_list=[('{min_book_date}', min_date_sql)], connection=conn, force_refresh=force,
        )
        print('ULA ready')
        dla_df = cached_sql(
            'new_dll_query.txt', 'cache/dla_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('DLA ready')
        new_recovery = cached_sql(
            'new_recovery_queryt.txt', 'cache/new_recovery_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('New recovery ready')
else:
    ula_df_total = get_pickle('cache/ula_v1.pkl')
    dla_df = get_pickle('cache/dla_v1.pkl')
    new_recovery = get_pickle('cache/new_recovery_v1.pkl')
    print('ULA, DLA, New recovery loaded from cache')

print(f"ULA records: {len(ula_df_total):,}")
print("[PROGRESS] Data Fetch Complete")

ULA, DLA, New recovery loaded from cache
ULA records: 752,571
[PROGRESS] Data Fetch Complete

In [7]:
# =============================================================================
# CELL 6: PERIOD ASSIGNMENT, FILTERING, FLAG CONSTRUCTION
# =============================================================================

ula_df_total = ula_df_total[ula_df_total.lob != 'Core']

ula_df_total['app_date'] = pd.to_datetime(ula_df_total['app_date'])
ula_df_total['book_date'] = pd.to_datetime(ula_df_total['book_date'])
new_recovery['app_date'] = pd.to_datetime(new_recovery['app_date'])
new_recovery['book_date'] = pd.to_datetime(new_recovery['book_date'])

for df in [ula_df_total, new_recovery]:
    df['quarter'] = pd.to_datetime(df[date_col]).dt.to_period('Q')
    df['month'] = pd.to_datetime(df[date_col]).dt.to_period('M')
    df['week'] = pd.to_datetime(df[date_col]).dt.to_period('W-SAT')
    period_key = {'q': 'quarter', 'm': 'month', 'w': 'week'}
    df['period'] = df[period_key[granularity]]

for df in [ula_df_total, new_recovery]:
    mask = (df['period'] >= start_period) & (df['period'] <= end_period)
    df.drop(df[~mask].index, inplace=True)

for df in [ula_df_total, new_recovery]:
    df['book_week'] = df['book_week'].astype(str)
    df['app_week'] = df['app_week'].astype(str)

date_col_str = f'{date_col}_str'
ula_df_total[date_col_str] = ula_df_total[date_col].astype(str)

# --- ULA Processing ---
ula_df_total['vehicle_age'] = np.maximum(ula_df_total[date_col_str].str[:4].astype(int) - ula_df_total.model_year, 1/365)
ula_df_total.tradein_value = ula_df_total.tradein_value.fillna(0)
ula_df_total.make = ula_df_total.make.str.upper().str[:3]
ula_df_total.lob_or_bucket = np.select(
    [ula_df_total.lob_or_bucket.isna() & ula_df_total.lob.isin(['Core', 'FRN']),
     ula_df_total.lob_or_bucket.isna() & ~ula_df_total.lob.isin(['Core', 'FRN'])],
    ['D', 'C'], default=ula_df_total.lob_or_bucket)

# --- DLA Merge ---
dla_df = dla_df.rename(columns={'valid_vintage': 'book_vintage'})
dla_explicit = dla_df[dla_df['book_vintage'] != 'current']
dla_current = dla_df[dla_df['book_vintage'] == 'current'].drop(columns='book_vintage')
last_explicit_vintage = dla_explicit['book_vintage'].max()
ula_df_total = ula_df_total.merge(dla_explicit, how='left', on=['dealer_number', 'book_vintage'])
new_and_missing = ula_df_total['pricing_scalar'].isna() & (ula_df_total['book_vintage'] > last_explicit_vintage)
fallback = ula_df_total.loc[new_and_missing, ['dealer_number']].merge(dla_current, on='dealer_number', how='left')
for col in ['dll_edition', 'loss_ratio', 'dealer_level', 'pricing_scalar']:
    ula_df_total.loc[new_and_missing, col] = fallback[col].values
ula_df_total['pricing_scalar'] = ula_df_total['pricing_scalar'].fillna(1)
ula_df_total.loc[ula_df_total.frni_flag == 1, 'pricing_scalar'] *= 1.05
ula_df_total.loc[ula_df_total.frni_flag == 0, 'pricing_scalar'] *= 0.95

# --- Driver Flag ---
warnings.filterwarnings('ignore', category=UserWarning)
ula_df_total.job_company = ula_df_total.job_company.fillna('not provided')
ula_df_total['driver_flag'] = np.where(
    ula_df_total.job_company.str.contains('(LYFT)|(UBER)|(GRUB ?HUB)|(DOOR ?DASH)|(GO ?PUFF)|(POST ?MATE)|(INSTA ?CART)|(DOMINO)|(PAPA J)|(PIZZA)|(JIMMY ?JOHN)|(SELF)'),
    1, 0)
warnings.filterwarnings('default', category=UserWarning)

# --- NA Handling ---
ula_df_total = ula_df_total.dropna(subset=['sale_price', 'cd_model_score', 'pti', 'lob'])
ula_df_total.cash_down = ula_df_total.cash_down.fillna(0)
ula_df_total.specialty_dealer = ula_df_total.specialty_dealer.fillna('not specialty')
ula_df_total.prev_co_count = ula_df_total.prev_co_count.fillna(0)

# --- Weekly-matching filters ---
ula_df_total['bbltv'] = ula_df_total.amt_financed / ula_df_total.bbvalue.replace(0, np.nan)
ula_df_total = ula_df_total[ula_df_total.amt_financed <= 75000]
ula_df_total = ula_df_total[ula_df_total.pti <= 0.6]
ula_df_total = ula_df_total[
    (ula_df_total.lob == 'MCY') |
    (ula_df_total.bbltv <= 10.0) |
    (ula_df_total.bbvalue.isna()) |
    (ula_df_total.bbvalue == 0)
]
ula_df_total = ula_df_total[ula_df_total.total_income <= 200000]

# --- NonKMX Flags ---
ula_df_total['ent_fld_flag'] = (ula_df_total.lob == 'ENT') | (ula_df_total.lob == 'FLD')
ula_df_total['small_amt_financed_flag'] = (ula_df_total.bbvalue < 5000) & (ula_df_total.amt_financed < 4500) & (ula_df_total.lob != 'MCY')
ula_df_total['zero_cash_down_flag'] = (ula_df_total.cash_down <= 250) & (ula_df_total.tradein_value < 3000)
ula_df_total['high_mileage_vehicle_flag'] = (ula_df_total.mileage >= 100000) & (ula_df_total.cd_model_score < 130) & (ula_df_total.lob != 'MCY')
ula_df_total['high_pti_flag'] = (ula_df_total.pti > 0.3) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally')
ula_df_total['car_make_penalty_flag'] = ula_df_total.make.isin({'CAD', 'CHR', 'BMW', 'BUI', 'SUB'}) & (ula_df_total.cd_model_score < 130) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally')
ula_df_total['car_make_benefit_flag'] = (ula_df_total.cd_model_score >= 133) & ula_df_total.make.isin({'HON', 'TOY', 'LEX'}) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally')
ula_df_total['theft_risk_flag'] = ula_df_total.make.isin({'KIA', 'HYU'}) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally') & (ula_df_total.model_year >= 2015) & (ula_df_total.model_year <= 2021) & (ula_df_total[date_col_str] >= '2022-07-01') & (ula_df_total[date_col_str] < '2025-01-01')
ula_df_total['mcy_low_mileage_flag'] = (ula_df_total.lob == 'MCY') & (ula_df_total.cd_model_score > 140) & (ula_df_total.mileage <= 20000) & (ula_df_total.vehicle_age <= 10)
ula_df_total['weekend_flag'] = ula_df_total.day_of_week.isin([0, 6])
ula_df_total['weekday_flag'] = ula_df_total.day_of_week.isin(range(1, 6))
ula_df_total['nonkmx_chime_flag'] = ula_df_total.nonkmx_chime_indicator
ula_df_total['seasonal_employment_flag'] = ula_df_total['seasonal_employment_flag'] == 1
ula_df_total['waiter_employment_flag'] = ula_df_total['waiter_employment_flag'] == 1
ula_df_total['nonkmx_auth_tradelines_flag'] = ula_df_total.pct_auth_tradelines > 0.2
ula_df_total['prev_co_flag'] = ula_df_total.prev_co_count > 0
ula_df_total['pricing_change_flag'] = ula_df_total[date_col_str] >= '2024-10-01'
ula_df_total['ent_flag'] = (ula_df_total.lob == 'ENT')
ula_df_total['student_loans_cutoff_date'] = ula_df_total[date_col_str] >= '2023-05-01'
ula_df_total['low_pti_flag'] = (ula_df_total.pti <= 0.05) & (ula_df_total.cd_model_score >= 130) & ula_df_total.lob.isin({'AN', 'FLD', 'FRN', 'STG'}) & (ula_df_total.cb_flag)
ula_df_total['student_loan_flag'] = np.where(ula_df_total.student_loan_flag == 1, 1, 0)

# --- Deduplicate driver flags ---
combined_driver_flag_df = ula_df_total.groupby('account_number').driver_flag.max().reset_index()
ula_df_total = ula_df_total.drop(columns='driver_flag').merge(combined_driver_flag_df, on='account_number')
ula_df_total = ula_df_total.drop(columns='job_company').drop_duplicates()

# --- Filter to nonKMX LOBs only ---
ula_df_total = ula_df_total[ula_df_total.lob.isin(LOBS)]

ula_df_total['vintage'] = format_vintage(ula_df_total['period'])
new_recovery['vintage'] = format_vintage(new_recovery['period'])

ms_df = ula_df_total.groupby(['period', 'lob']).apply(
    weighted_average_and_sum, 'cd_model_score', include_groups=False
).reset_index()
ms_df = ms_df.rename(columns={'cd_model_score': 'model_score'})
ms_df['period'] = format_vintage(ms_df['period'])

print(f"ULA after filters (nonKMX only): {len(ula_df_total):,}")
print(f"LOBs: {sorted(ula_df_total.lob.unique())}")
print(f"Vintages: {ula_df_total.vintage.nunique()}")
print(f"Model scores: {len(ms_df)} period-LOB combinations")

ULA after filters (nonKMX only): 29,763
LOBs: ['AN', 'ENT', 'FLD', 'FRN', 'STG']
Vintages: 19
Model scores: 95 period-LOB combinations

In [8]:
# =============================================================================
# CELL 7: RAGU SCORE COMPUTATION (NONKMX LOBs)
# =============================================================================

mean_unit_loss = MODEL_PARAMS['mean_unit_loss']
unit_loss_to_model_score = MODEL_PARAMS['unit_loss_to_model_score']


def get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config, leave_out='None'):
    baseline_ltv = baseline_config['ltv']
    new_baseline_recovery_unadjusted_pct = baseline_config['new_recovery_unadjusted']
    baseline_apr = baseline_config['apr']
    ltv_mult = 17
    apr_mult = 0.7

    ula_df = ula_df_total[(ula_df_total.vintage == vintage) & (ula_df_total.lob == lob)].copy()
    if len(ula_df) == 0:
        return None

    ula_df = get_ula_multiplier_nonkmx(ula_df, leave_out)

    ula_df = ula_df[['account_number', date_col, 'bbvalue', 'sale_price', 'amt_financed', 'lob_or_bucket', 'lob', 'loss_multiplier', 'apr']]

    nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(subset='account_number', keep='first')
    mix_df = ula_df.merge(nr.rename(columns={'new_recovery_multiplier': 'recovery_multiplier'}),
                          on='account_number', how='left').drop_duplicates(subset='account_number', keep='first')
    mix_df['ltv'] = mix_df.amt_financed / mix_df.bbvalue

    bb_populated_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0)]
    if len(bb_populated_df) == 0:
        return None

    full_pop_metrics = bb_populated_df.groupby('lob').apply(
        weighted_average_and_sum, ['loss_multiplier', 'ltv', 'bbvalue', 'apr'], include_groups=False)

    recovery_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0) & mix_df['recovery_multiplier'].notna()].copy()
    recovery_df['recovery_unadjusted_multiplier'] = recovery_df['recovery_multiplier']
    recovery_metrics = recovery_df.groupby('lob').apply(
        weighted_average_and_sum, ['recovery_unadjusted_multiplier'], include_groups=False)
    recovery_metrics = recovery_metrics.drop(columns='amt_financed')

    grouped_mix_df = full_pop_metrics.join(recovery_metrics)
    vintage_ms_df = ms_df[ms_df['period'] == vintage].copy()

    index_name = grouped_mix_df.index.name
    if isinstance(index_name, str) and index_name in grouped_mix_df.columns:
        grouped_mix_df = grouped_mix_df.reset_index(drop=True)
    else:
        grouped_mix_df = grouped_mix_df.reset_index()

    full_df = grouped_mix_df.merge(vintage_ms_df, on='lob')
    if len(full_df) == 0:
        return None

    full_df['est_unit_loss'] = mean_unit_loss
    full_df['unit_loss_score'] = full_df.model_score + (1 - full_df.loss_multiplier) * full_df.est_unit_loss / unit_loss_to_model_score
    full_df = full_df.set_index('lob')
    full_df['ms_original'] = full_df.model_score.copy()
    full_df['baselined_unadjusted_recovery'] = (full_df.recovery_unadjusted_multiplier / new_baseline_recovery_unadjusted_pct).copy()

    full_df['gross_loss_impact'] = full_df['unit_loss_score'] - full_df['ms_original']
    full_df['recovery_impact'] = (full_df['unit_loss_score'] * full_df['est_unit_loss']
        * full_df['recovery_unadjusted_multiplier'] * (full_df['baselined_unadjusted_recovery'] - 1))
    full_df['ltv_impact'] = ((baseline_ltv / full_df['ltv']) - 1) * ltv_mult
    full_df['apr_impact'] = (baseline_apr - full_df['apr']) / 0.01 * apr_mult
    full_df['ragu_score'] = (
        (1 - full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier) * full_df.unit_loss_score
        + full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier
        * full_df.unit_loss_score * full_df.baselined_unadjusted_recovery
        + full_df['ltv_impact']
        + full_df['apr_impact'])
    full_df['vintage'] = vintage
    return full_df


all_vintages = sorted(ula_df_total['vintage'].unique())
results_by_lob = {}

for lob in LOBS:
    baseline_config = BASELINES[lob]
    lob_results = []
    for vintage in all_vintages:
        try:
            result = get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config)
            if result is not None:
                lob_results.append(result)
        except Exception as e:
            print(f"Error: {vintage} {lob}: {e}")
    if lob_results:
        results_by_lob[lob] = pd.concat(lob_results)
        print(f"{lob}: {len(lob_results)} vintages")
    else:
        results_by_lob[lob] = pd.DataFrame()
        print(f"{lob}: no results")

print(f"\nAll LOBs processed.")
print("[PROGRESS] Scoring Complete")

Error: 2026-05-03/2026-05-09 AN: columns overlap but no suffix specified: Index(['loss_multiplier', 'ltv', 'bbvalue', 'apr'], dtype='str')
AN: 18 vintages

FRN: 19 vintages

STG: 19 vintages

FLD: 19 vintages

Error: 2026-05-03/2026-05-09 ENT: columns overlap but no suffix specified: Index(['loss_multiplier', 'ltv', 'bbvalue', 'apr'], dtype='str')
ENT: 18 vintages

All LOBs processed.
[PROGRESS] Scoring Complete

In [9]:
# =============================================================================
# CELL 8: DIAGNOSTICS - STEP-LEVEL ATTRIBUTION PER LOB
# =============================================================================

def build_output_df(results, wtd_mults, record_counts, ragu_gli_dict=None):
    if not results:
        return None
    step_names = list(next(iter(results.values())).keys())
    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        col_data[col_name] = [step_dict.get(s) for s in step_names]
    diag_df = pd.DataFrame(col_data, index=step_names)
    summary = {}
    for (lob, vintage) in results.keys():
        col = f"{lob} | {vintage}"
        final_mult_mean = diag_df[col].iloc[-1]
        wtd_mult = wtd_mults.get((lob, vintage), float('nan'))
        if ragu_gli_dict is not None:
            gross_loss_impact = ragu_gli_dict.get((lob, vintage), 25 * (1 - wtd_mult))
        else:
            gross_loss_impact = 25 * (1 - wtd_mult)
        summary[col] = {
            '--- FINAL_MULT (mean)': final_mult_mean,
            '--- WTD_MULT_RAGU': wtd_mult,
            '--- GROSS_LOSS_IMPACT': gross_loss_impact,
            '--- N_RECORDS': record_counts.get((lob, vintage), 0),
        }
    summary_df = pd.DataFrame(summary)
    return pd.concat([diag_df, summary_df])


def build_flags_df(flag_results, record_counts):
    if not flag_results:
        return None
    flag_names = list(next(iter(flag_results.values())).keys())
    flag_col_data = {}
    for (lob, vintage), flag_dict in flag_results.items():
        col_name = f"{lob} | {vintage}"
        flag_col_data[col_name] = [flag_dict.get(f) for f in flag_names]
    flags_df = pd.DataFrame(flag_col_data, index=flag_names)
    n_row = {}
    for (lob, vintage) in flag_results.keys():
        n_row[f"{lob} | {vintage}"] = record_counts.get((lob, vintage), 0)
    flags_df.loc['--- N_RECORDS'] = n_row
    return flags_df


STEP_LABEL_MAP = {
    '00_initial':              'Initial (1.0)',
    '01_prev_aca_chargeoff':   'Previous ACA Chargeoff',
    '02_small_amt_financed':   'Small Amount Financed',
    '03_zero_cash_down':       'Zero Cash Down',
    '04_high_mileage':         'High Mileage Vehicle',
    '05_high_pti':             'High PTI',
    '06_car_make':             'Car Make',
    '07_theft_risk':           'Theft Risk',
    '08_mcy_low_mileage':      'MCY Low Mileage',
    '09_weekend_weekday':      'Weekend / Weekday',
    '10_student_loans':        'Student Loans',
    '11_low_pti':              'Low PTI',
    '12_chime':                'Chime / Secured Credit',
    '13_employment_type':      'Employment Type',
    '14_auth_tradelines':      'Authorized Tradelines',
    '15_fraud':                'Fraud Adjustment',
    '16_driver_flag':          'Driver Flag',
    '17_pricing_scalar':       'Dealer Level (Pricing Scalar)',
    '18_final':                'Final Clip',
}


def build_attribution_df(results, ragu_gli_dict):
    """
    Decompose gross_loss_impact across multiplier steps using logarithmic attribution.
    gross_loss_impact is sourced from get_ragu_score output to ensure the attribution
    decomposes the same value that appears in the RAGU score decomposition.
    """
    if not results:
        return None

    step_keys = list(next(iter(results.values())).keys())
    adjustment_keys = [k for k in step_keys if k != '00_initial']
    readable_labels = [STEP_LABEL_MAP.get(k, k) for k in adjustment_keys]

    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        gross_loss_impact = ragu_gli_dict.get((lob, vintage), float('nan'))

        cumulative = [step_dict.get(k, float('nan')) for k in step_keys]
        ratios = []
        for i, k in enumerate(step_keys):
            if k == '00_initial':
                continue
            prev = cumulative[i - 1]
            curr = cumulative[i]
            if prev and prev != 0:
                ratios.append(curr / prev)
            else:
                ratios.append(1.0)

        final_mult = cumulative[-1]
        log_final = math.log(final_mult) if final_mult and final_mult > 0 and abs(final_mult - 1.0) > 1e-12 else None

        if log_final is None or pd.isna(gross_loss_impact):
            col_data[col_name] = [0.0] * len(adjustment_keys) + [gross_loss_impact if not pd.isna(gross_loss_impact) else 0.0]
        else:
            log_ratios = [math.log(r) if r and r > 0 else 0.0 for r in ratios]
            attributed = [(lr / log_final) * gross_loss_impact for lr in log_ratios]
            col_data[col_name] = attributed + [sum(attributed)]

    index_labels = readable_labels + ['--- TOTAL (check)']
    return pd.DataFrame(col_data, index=index_labels)


# --- Run diagnostics per LOB ---
diag_results_by_lob = {}

for lob in LOBS:
    ula_lob = ula_df_total[ula_df_total.lob == lob].copy()
    if len(ula_lob) == 0:
        print(f'\n{lob}: No data, skipping.')
        diag_results_by_lob[lob] = (None, None, None)
        continue

    ragu_gli_dict = {}
    model_df = results_by_lob.get(lob)
    if model_df is not None and len(model_df) > 0:
        for _, row in model_df.reset_index().iterrows():
            ragu_gli_dict[(row['lob'], row['vintage'])] = row['gross_loss_impact']

    target_vintages = sorted(ula_lob.vintage.unique())[-DIAG_N_VINTAGES:]

    lob_results = {}
    lob_flag_results = {}
    lob_wtd_mults = {}
    lob_record_counts = {}

    print(f'\n{"="*60}')
    print(f'  DIAGNOSTICS: {lob}')
    print(f'{"="*60}')

    for vintage in target_vintages:
        ula_vintage = ula_lob[ula_lob.vintage == vintage].copy()
        n = len(ula_vintage)
        if n == 0:
            continue

        print(f'\n{"="*60}')
        print(f'  {lob} {vintage}  (n={n})')
        print(f'{"="*60}')

        ula_vintage_diag, steps, flags = get_ula_multiplier_nonkmx_diag(ula_vintage, leave_out='None', verbose=True)

        diag_mix = ula_vintage_diag[['account_number', 'bbvalue', 'amt_financed', 'loss_multiplier']].copy()
        nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(
            subset='account_number', keep='first')
        diag_mix = diag_mix.merge(nr, on='account_number', how='left').drop_duplicates(
            subset='account_number', keep='first')
        bb_pop = diag_mix[diag_mix['bbvalue'].notna() & (diag_mix['bbvalue'] > 0)]
        if len(bb_pop) > 0 and bb_pop.amt_financed.sum() > 0:
            wtd_mult = (bb_pop.loss_multiplier * bb_pop.amt_financed).sum() / bb_pop.amt_financed.sum()
        else:
            wtd_mult = float('nan')

        ragu_gli = ragu_gli_dict.get((lob, vintage), float('nan'))
        print(f"  bb_populated: {len(bb_pop)} / {n}  wtd_mult: {wtd_mult:.6f}  ragu_gli: {ragu_gli:.4f}")

        lob_results[(lob, vintage)] = steps.to_dict()
        lob_flag_results[(lob, vintage)] = flags.to_dict()
        lob_wtd_mults[(lob, vintage)] = wtd_mult
        lob_record_counts[(lob, vintage)] = n

    output_df = build_output_df(lob_results, lob_wtd_mults, lob_record_counts, ragu_gli_dict)
    flags_df = build_flags_df(lob_flag_results, lob_record_counts)
    attribution_df = build_attribution_df(lob_results, ragu_gli_dict)
    diag_results_by_lob[lob] = (output_df, flags_df, attribution_df)

    if output_df is not None:
        print(f'\n--- {lob} Multiplier Steps ---')
        display(output_df)
        print(f'\n--- {lob} Flag Means ---')
        display(flags_df)
    if attribution_df is not None:
        print(f'\n--- {lob} Gross Loss Attribution ---')
        display(attribution_df)

============================================================
  DIAGNOSTICS: AN
============================================================

============================================================
  AN 2026-03-29/2026-04-04  (n=194)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.010309  | loss_multiplier mean: 1.001031
02_small_af | flag mean: 0.005155  | loss_multiplier mean: 1.001031
03_zero_cd  | flag mean: 0.067010  | loss_multiplier mean: 1.001031
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001031
05_high_pti | flag mean: 0.005155  | loss_multiplier mean: 1.001031
06_car_make | penalty: 0.000000  benefit: 0.298969  | loss_multiplier mean: 0.941237
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.941237
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.941237
09_wknd/day | weekend: 0.283505  weekday: 0.716495  | loss_multiplier mean: 0.941299
10_stud_ln  | flag mean: 0.113402  | loss_multiplier mean: 0.930082
11_low_pti  | flag mean: 0.025773  | loss_multiplier mean: 0.926307
12_chime    | flag mean: 0.195876  | loss_multiplier mean: 0.943150
13_employ   | seasonal: 0.020619  waiter: 0.010309  | loss_multiplier mean: 0.943877
14_auth_tl  | flag mean: 0.015464  | loss_multiplier mean: 0.945140
15_fraud    | fraud_adj mean: 0.968247  | loss_multiplier mean: 0.915907
16_driver   | flag mean: 0.020619  | loss_multiplier mean: 0.918398
17_pricing  | scalar mean: 0.928866  | loss_multiplier mean: 0.869979
18_final    | loss_multiplier mean: 0.875591  (post all clips)
  bb_populated: 193 / 194  wtd_mult: 0.867740  ragu_gli: 3.3065

============================================================
  AN 2026-04-05/2026-04-11  (n=196)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.015306  | loss_multiplier mean: 1.001531
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001531
03_zero_cd  | flag mean: 0.112245  | loss_multiplier mean: 1.001531
04_high_mi  | flag mean: 0.005102  | loss_multiplier mean: 1.002041
05_high_pti | flag mean: 0.010204  | loss_multiplier mean: 1.002041
06_car_make | penalty: 0.000000  benefit: 0.275510  | loss_multiplier mean: 0.946939
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.946939
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.946939
09_wknd/day | weekend: 0.321429  weekday: 0.678571  | loss_multiplier mean: 0.944413
10_stud_ln  | flag mean: 0.117347  | loss_multiplier mean: 0.932706
11_low_pti  | flag mean: 0.045918  | loss_multiplier mean: 0.926356
12_chime    | flag mean: 0.168367  | loss_multiplier mean: 0.936954
13_employ   | seasonal: 0.020408  waiter: 0.020408  | loss_multiplier mean: 0.936719
14_auth_tl  | flag mean: 0.035714  | loss_multiplier mean: 0.940047
15_fraud    | fraud_adj mean: 1.004235  | loss_multiplier mean: 0.944745
16_driver   | flag mean: 0.015306  | loss_multiplier mean: 0.947453
17_pricing  | scalar mean: 0.922704  | loss_multiplier mean: 0.881835
18_final    | loss_multiplier mean: 0.881921  (post all clips)
  bb_populated: 195 / 196  wtd_mult: 0.877299  ragu_gli: 3.0675

============================================================
  AN 2026-04-12/2026-04-18  (n=192)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.005208  | loss_multiplier mean: 1.000521
02_small_af | flag mean: 0.005208  | loss_multiplier mean: 1.000521
03_zero_cd  | flag mean: 0.072917  | loss_multiplier mean: 1.000521
04_high_mi  | flag mean: 0.005208  | loss_multiplier mean: 1.001042
05_high_pti | flag mean: 0.010417  | loss_multiplier mean: 1.001042
06_car_make | penalty: 0.000000  benefit: 0.322917  | loss_multiplier mean: 0.936458
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.936458
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.936458
09_wknd/day | weekend: 0.307292  weekday: 0.692708  | loss_multiplier mean: 0.934990
10_stud_ln  | flag mean: 0.140625  | loss_multiplier mean: 0.926632
11_low_pti  | flag mean: 0.041667  | loss_multiplier mean: 0.920469
12_chime    | flag mean: 0.182292  | loss_multiplier mean: 0.935751
13_employ   | seasonal: 0.015625  waiter: 0.020833  | loss_multiplier mean: 0.935508
14_auth_tl  | flag mean: 0.010417  | loss_multiplier mean: 0.936343
15_fraud    | fraud_adj mean: 0.985417  | loss_multiplier mean: 0.924118
16_driver   | flag mean: 0.036458  | loss_multiplier mean: 0.929324
17_pricing  | scalar mean: 0.914062  | loss_multiplier mean: 0.866288
18_final    | loss_multiplier mean: 0.867287  (post all clips)
  bb_populated: 191 / 192  wtd_mult: 0.863062  ragu_gli: 3.4234

============================================================
  AN 2026-04-19/2026-04-25  (n=198)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.126263  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.010101  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.333333  | loss_multiplier mean: 0.933333
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.933333
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.933333
09_wknd/day | weekend: 0.287879  weekday: 0.712121  | loss_multiplier mean: 0.932838
10_stud_ln  | flag mean: 0.141414  | loss_multiplier mean: 0.923304
11_low_pti  | flag mean: 0.060606  | loss_multiplier mean: 0.914674
12_chime    | flag mean: 0.242424  | loss_multiplier mean: 0.942819
13_employ   | seasonal: 0.015152  waiter: 0.040404  | loss_multiplier mean: 0.940798
14_auth_tl  | flag mean: 0.035354  | loss_multiplier mean: 0.943826
15_fraud    | fraud_adj mean: 0.971566  | loss_multiplier mean: 0.918557
16_driver   | flag mean: 0.010101  | loss_multiplier mean: 0.919890
17_pricing  | scalar mean: 0.924242  | loss_multiplier mean: 0.865090
18_final    | loss_multiplier mean: 0.867205  (post all clips)
  bb_populated: 198 / 198  wtd_mult: 0.852053  ragu_gli: 3.6987

============================================================
  AN 2026-04-26/2026-05-02  (n=112)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.098214  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.008929  | loss_multiplier mean: 1.000893
05_high_pti | flag mean: 0.026786  | loss_multiplier mean: 1.000893
06_car_make | penalty: 0.000000  benefit: 0.303571  | loss_multiplier mean: 0.940179
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.940179
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.940179
09_wknd/day | weekend: 0.187500  weekday: 0.812500  | loss_multiplier mean: 0.946295
10_stud_ln  | flag mean: 0.151786  | loss_multiplier mean: 0.938745
11_low_pti  | flag mean: 0.035714  | loss_multiplier mean: 0.933445
12_chime    | flag mean: 0.169643  | loss_multiplier mean: 0.944032
13_employ   | seasonal: 0.026786  waiter: 0.026786  | loss_multiplier mean: 0.944037
14_auth_tl  | flag mean: 0.008929  | loss_multiplier mean: 0.944890
15_fraud    | fraud_adj mean: 0.978929  | loss_multiplier mean: 0.925985
16_driver   | flag mean: 0.035714  | loss_multiplier mean: 0.930881
17_pricing  | scalar mean: 0.926339  | loss_multiplier mean: 0.877370
18_final    | loss_multiplier mean: 0.880769  (post all clips)
  bb_populated: 111 / 112  wtd_mult: 0.864434  ragu_gli: 3.3892

============================================================
  AN 2026-05-03/2026-05-09  (n=5)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.200000  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.800000  | loss_multiplier mean: 0.840000
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.840000
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.840000
09_wknd/day | weekend: 0.200000  weekday: 0.800000  | loss_multiplier mean: 0.845600
10_stud_ln  | flag mean: 0.000000  | loss_multiplier mean: 0.821144
11_low_pti  | flag mean: 0.200000  | loss_multiplier mean: 0.791462
12_chime    | flag mean: 0.200000  | loss_multiplier mean: 0.807769
13_employ   | seasonal: 0.000000  waiter: 0.000000  | loss_multiplier mean: 0.807769
14_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 0.807769
15_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 0.807769
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.807769

17_pricing  | scalar mean: 0.880000  | loss_multiplier mean: 0.736825
18_final    | loss_multiplier mean: 0.746718  (post all clips)
  bb_populated: 5 / 5  wtd_mult: 0.726979  ragu_gli: nan

--- AN Multiplier Steps ---

,AN | 2026-03-29/2026-04-04,AN | 2026-04-05/2026-04-11,AN | 2026-04-12/2026-04-18,AN | 2026-04-19/2026-04-25,AN | 2026-04-26/2026-05-02,AN | 2026-05-03/2026-05-09
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.001031,1.001531,1.000521,1.000000,1.000000,1.000000
02_small_amt_financed,1.001031,1.001531,1.000521,1.000000,1.000000,1.000000
03_zero_cash_down,1.001031,1.001531,1.000521,1.000000,1.000000,1.000000
04_high_mileage,1.001031,1.002041,1.001042,1.000000,1.000893,1.000000
05_high_pti,1.001031,1.002041,1.001042,1.000000,1.000893,1.000000
06_car_make,0.941237,0.946939,0.936458,0.933333,0.940179,0.840000
07_theft_risk,0.941237,0.946939,0.936458,0.933333,0.940179,0.840000
08_mcy_low_mileage,0.941237,0.946939,0.936458,0.933333,0.940179,0.840000
09_weekend_weekday,0.941299,0.944413,0.934990,0.932838,0.946295,0.845600
10_student_loans,0.930082,0.932706,0.926632,0.923304,0.938745,0.821144
11_low_pti,0.926307,0.926356,0.920469,0.914674,0.933445,0.791462
12_chime,0.943150,0.936954,0.935751,0.942819,0.944032,0.807769
13_employment_type,0.943877,0.936719,0.935508,0.940798,0.944037,0.807769
14_auth_tradelines,0.945140,0.940047,0.936343,0.943826,0.944890,0.807769
15_fraud,0.915907,0.944745,0.924118,0.918557,0.925985,0.807769
16_driver_flag,0.918398,0.947453,0.929324,0.919890,0.930881,0.807769
17_pricing_scalar,0.869979,0.881835,0.866288,0.865090,0.877370,0.736825
18_final,0.875591,0.881921,0.867287,0.867205,0.880769,0.746718
--- FINAL_MULT (mean),0.875591,0.881921,0.867287,0.867205,0.880769,0.746718
--- WTD_MULT_RAGU,0.867740,0.877299,0.863062,0.852053,0.864434,0.726979
--- GROSS_LOSS_IMPACT,3.306498,3.067531,3.423444,3.698687,3.389160,6.825517
--- N_RECORDS,194.000000,196.000000,192.000000,198.000000,112.000000,5.000000

--- AN Flag Means ---

,AN | 2026-03-29/2026-04-04,AN | 2026-04-05/2026-04-11,AN | 2026-04-12/2026-04-18,AN | 2026-04-19/2026-04-25,AN | 2026-04-26/2026-05-02,AN | 2026-05-03/2026-05-09
prev_co_flag,0.010309,0.015306,0.005208,0.000000,0.000000,0.00
small_amt_financed_flag,0.005155,0.000000,0.005208,0.000000,0.000000,0.00
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.00
zero_cash_down_flag,0.067010,0.112245,0.072917,0.126263,0.098214,0.20
high_mileage_vehicle_flag,0.000000,0.005102,0.005208,0.000000,0.008929,0.00
high_pti_flag,0.005155,0.010204,0.010417,0.010101,0.026786,0.00
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
car_make_benefit_flag,0.298969,0.275510,0.322917,0.333333,0.303571,0.80
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
weekend_flag,0.283505,0.321429,0.307292,0.287879,0.187500,0.20
weekday_flag,0.716495,0.678571,0.692708,0.712121,0.812500,0.80
student_loan_flag,0.113402,0.117347,0.140625,0.141414,0.151786,0.00
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.00
low_pti_flag,0.025773,0.045918,0.041667,0.060606,0.035714,0.20
nonkmx_chime_flag,0.195876,0.168367,0.182292,0.242424,0.169643,0.20
seasonal_employment_pct,0.020619,0.020408,0.015625,0.015152,0.026786,0.00
waiter_employment_pct,0.010309,0.020408,0.020833,0.040404,0.026786,0.00
nonkmx_auth_tradelines_flag,0.015464,0.035714,0.010417,0.035354,0.008929,0.00
fraud_adjustment_mean,0.968247,1.004235,0.985417,0.971566,0.978929,1.00
driver_flag,0.020619,0.015306,0.036458,0.010101,0.035714,0.00
pricing_scalar_mean,0.928866,0.922704,0.914062,0.924242,0.926339,0.88
--- N_RECORDS,194.000000,196.000000,192.000000,198.000000,112.000000,5.00

--- AN Gross Loss Attribution ---

,AN | 2026-03-29/2026-04-04,AN | 2026-04-05/2026-04-11,AN | 2026-04-12/2026-04-18,AN | 2026-04-19/2026-04-25,AN | 2026-04-26/2026-05-02,AN | 2026-05-03/2026-05-09
Previous ACA Chargeoff,-0.025644,-0.037338,-0.012519,-0.000000,-0.000000,0.0
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
High Mileage Vehicle,-0.000000,-0.012433,-0.012513,-0.000000,-0.023824,0.0
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Car Make,1.532860,1.380771,1.603495,1.791010,1.670499,0.0
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Weekend / Weekday,-0.001636,0.065196,0.037740,0.013770,-0.173093,0.0
Student Loans,0.298365,0.304520,0.215887,0.266682,0.213815,0.0
Low PTI,0.101207,0.166782,0.160443,0.243795,0.151151,0.0
Chime / Secured Credit,-0.448466,-0.277722,-0.395914,-0.786732,-0.301071,0.0
Employment Type,-0.019187,0.006122,0.006251,0.055705,-0.000124,0.0
Authorized Tradelines,-0.033280,-0.086569,-0.021439,-0.083435,-0.024120,0.0
Fraud Adjustment,0.781951,-0.121716,0.315986,0.704496,0.539517,0.0
Driver Flag,-0.067614,-0.069860,-0.135077,-0.037652,-0.140767,0.0
Dealer Level (Pricing Scalar),1.347976,1.752163,1.688805,1.594442,1.580396,0.0
Final Clip,-0.160033,-0.002386,-0.027701,-0.063393,-0.103222,0.0
--- TOTAL (check),3.306498,3.067531,3.423444,3.698687,3.389160,0.0

============================================================
  DIAGNOSTICS: FRN
============================================================

============================================================
  FRN 2026-03-29/2026-04-04  (n=716)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006983  | loss_multiplier mean: 1.000698
02_small_af | flag mean: 0.008380  | loss_multiplier mean: 1.000698
03_zero_cd  | flag mean: 0.027933  | loss_multiplier mean: 1.000698
04_high_mi  | flag mean: 0.002793  | loss_multiplier mean: 1.000978
05_high_pti | flag mean: 0.004190  | loss_multiplier mean: 1.000978
06_car_make | penalty: 0.000000  benefit: 0.270950  | loss_multiplier mean: 0.946760
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.946760
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.946760
09_wknd/day | weekend: 0.250000  weekday: 0.750000  | loss_multiplier mean: 0.949331
10_stud_ln  | flag mean: 0.135475  | loss_multiplier mean: 0.938009
11_low_pti  | flag mean: 0.047486  | loss_multiplier mean: 0.931157
12_chime    | flag mean: 0.238827  | loss_multiplier mean: 0.960432
13_employ   | seasonal: 0.022346  waiter: 0.011173  | loss_multiplier mean: 0.961293
14_auth_tl  | flag mean: 0.036313  | loss_multiplier mean: 0.964555
15_fraud    | fraud_adj mean: 0.994665  | loss_multiplier mean: 0.960582
16_driver   | flag mean: 0.040503  | loss_multiplier mean: 0.965787
17_pricing  | scalar mean: 0.926013  | loss_multiplier mean: 0.904894

18_final    | loss_multiplier mean: 0.906927  (post all clips)
  bb_populated: 714 / 716  wtd_mult: 0.891642  ragu_gli: 2.7090

============================================================
  FRN 2026-04-05/2026-04-11  (n=576)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.005208  | loss_multiplier mean: 1.000521
02_small_af | flag mean: 0.006944  | loss_multiplier mean: 1.000521
03_zero_cd  | flag mean: 0.022569  | loss_multiplier mean: 1.000521
04_high_mi  | flag mean: 0.003472  | loss_multiplier mean: 1.000868
05_high_pti | flag mean: 0.003472  | loss_multiplier mean: 1.000868
06_car_make | penalty: 0.000000  benefit: 0.227431  | loss_multiplier mean: 0.955347
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.955347
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.955347
09_wknd/day | weekend: 0.279514  weekday: 0.720486  | loss_multiplier mean: 0.955899
10_stud_ln  | flag mean: 0.107639  | loss_multiplier mean: 0.941236
11_low_pti  | flag mean: 0.045139  | loss_multiplier mean: 0.934796
12_chime    | flag mean: 0.223958  | loss_multiplier mean: 0.959795
13_employ   | seasonal: 0.015625  waiter: 0.008681  | loss_multiplier mean: 0.960358
14_auth_tl  | flag mean: 0.029514  | loss_multiplier mean: 0.963084
15_fraud    | fraud_adj mean: 0.992726  | loss_multiplier mean: 0.955918
16_driver   | flag mean: 0.038194  | loss_multiplier mean: 0.960987
17_pricing  | scalar mean: 0.925217  | loss_multiplier mean: 0.901939
18_final    | loss_multiplier mean: 0.902641  (post all clips)
  bb_populated: 571 / 576  wtd_mult: 0.887608  ragu_gli: 2.8098

============================================================
  FRN 2026-04-12/2026-04-18  (n=585)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.003419  | loss_multiplier mean: 1.000342
02_small_af | flag mean: 0.005128  | loss_multiplier mean: 1.000342
03_zero_cd  | flag mean: 0.023932  | loss_multiplier mean: 1.000342
04_high_mi  | flag mean: 0.001709  | loss_multiplier mean: 1.000513
05_high_pti | flag mean: 0.008547  | loss_multiplier mean: 1.000513
06_car_make | penalty: 0.000000  benefit: 0.247863  | loss_multiplier mean: 0.950940
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950940
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950940
09_wknd/day | weekend: 0.297436  weekday: 0.702564  | loss_multiplier mean: 0.950203
10_stud_ln  | flag mean: 0.088889  | loss_multiplier mean: 0.933415
11_low_pti  | flag mean: 0.035897  | loss_multiplier mean: 0.928292
12_chime    | flag mean: 0.172650  | loss_multiplier mean: 0.940099
13_employ   | seasonal: 0.022222  waiter: 0.010256  | loss_multiplier mean: 0.941276
14_auth_tl  | flag mean: 0.030769  | loss_multiplier mean: 0.944130
15_fraud    | fraud_adj mean: 0.988120  | loss_multiplier mean: 0.933193
16_driver   | flag mean: 0.039316  | loss_multiplier mean: 0.938305

17_pricing  | scalar mean: 0.921662  | loss_multiplier mean: 0.876004
18_final    | loss_multiplier mean: 0.881946  (post all clips)
  bb_populated: 583 / 585  wtd_mult: 0.871685  ragu_gli: 3.2079

============================================================
  FRN 2026-04-19/2026-04-25  (n=531)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.001883  | loss_multiplier mean: 1.000188
02_small_af | flag mean: 0.009416  | loss_multiplier mean: 1.000188
03_zero_cd  | flag mean: 0.037665  | loss_multiplier mean: 1.000188
04_high_mi  | flag mean: 0.001883  | loss_multiplier mean: 1.000377
05_high_pti | flag mean: 0.001883  | loss_multiplier mean: 1.000377
06_car_make | penalty: 0.001883  benefit: 0.224105  | loss_multiplier mean: 0.955706
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.955706
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.955706
09_wknd/day | weekend: 0.284369  weekday: 0.715631  | loss_multiplier mean: 0.955626
10_stud_ln  | flag mean: 0.116761  | loss_multiplier mean: 0.942351
11_low_pti  | flag mean: 0.039548  | loss_multiplier mean: 0.936768
12_chime    | flag mean: 0.178908  | loss_multiplier mean: 0.950731
13_employ   | seasonal: 0.016949  waiter: 0.018832  | loss_multiplier mean: 0.950554
14_auth_tl  | flag mean: 0.018832  | loss_multiplier mean: 0.952297
15_fraud    | fraud_adj mean: 0.990565  | loss_multiplier mean: 0.943818
16_driver   | flag mean: 0.037665  | loss_multiplier mean: 0.948603
17_pricing  | scalar mean: 0.929101  | loss_multiplier mean: 0.892238
18_final    | loss_multiplier mean: 0.898250  (post all clips)

  bb_populated: 530 / 531  wtd_mult: 0.881985  ragu_gli: 2.9504

============================================================
  FRN 2026-04-26/2026-05-02  (n=398)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.015075  | loss_multiplier mean: 1.001508
02_small_af | flag mean: 0.015075  | loss_multiplier mean: 1.001508
03_zero_cd  | flag mean: 0.042714  | loss_multiplier mean: 1.001508
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001508
05_high_pti | flag mean: 0.005025  | loss_multiplier mean: 1.001508
06_car_make | penalty: 0.000000  benefit: 0.286432  | loss_multiplier mean: 0.944171
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.944171
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.944171
09_wknd/day | weekend: 0.208543  weekday: 0.791457  | loss_multiplier mean: 0.949353
10_stud_ln  | flag mean: 0.118090  | loss_multiplier mean: 0.936047
11_low_pti  | flag mean: 0.030151  | loss_multiplier mean: 0.931834
12_chime    | flag mean: 0.218593  | loss_multiplier mean: 0.955589
13_employ   | seasonal: 0.010050  waiter: 0.015075  | loss_multiplier mean: 0.955104
14_auth_tl  | flag mean: 0.017588  | loss_multiplier mean: 0.956836
15_fraud    | fraud_adj mean: 0.985905  | loss_multiplier mean: 0.944250
16_driver   | flag mean: 0.055276  | loss_multiplier mean: 0.951322
17_pricing  | scalar mean: 0.931683  | loss_multiplier mean: 0.899329
18_final    | loss_multiplier mean: 0.901737  (post all clips)

  bb_populated: 398 / 398  wtd_mult: 0.891698  ragu_gli: 2.7076

============================================================
  FRN 2026-05-03/2026-05-09  (n=38)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.026316  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.026316  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.263158  | loss_multiplier mean: 0.947368
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.947368
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.947368
09_wknd/day | weekend: 0.210526  weekday: 0.789474  | loss_multiplier mean: 0.952316
10_stud_ln  | flag mean: 0.078947  | loss_multiplier mean: 0.933624
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.933624
12_chime    | flag mean: 0.157895  | loss_multiplier mean: 0.941082
13_employ   | seasonal: 0.000000  waiter: 0.026316  | loss_multiplier mean: 0.938567
14_auth_tl  | flag mean: 0.026316  | loss_multiplier mean: 0.941082
15_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 0.941082
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.941082
17_pricing  | scalar mean: 0.945724  | loss_multiplier mean: 0.894681
18_final    | loss_multiplier mean: 0.900675  (post all clips)
  bb_populated: 38 / 38  wtd_mult: 0.875964  ragu_gli: 3.1009

--- FRN Multiplier Steps ---

,FRN | 2026-03-29/2026-04-04,FRN | 2026-04-05/2026-04-11,FRN | 2026-04-12/2026-04-18,FRN | 2026-04-19/2026-04-25,FRN | 2026-04-26/2026-05-02,FRN | 2026-05-03/2026-05-09
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000698,1.000521,1.000342,1.000188,1.001508,1.000000
02_small_amt_financed,1.000698,1.000521,1.000342,1.000188,1.001508,1.000000
03_zero_cash_down,1.000698,1.000521,1.000342,1.000188,1.001508,1.000000
04_high_mileage,1.000978,1.000868,1.000513,1.000377,1.001508,1.000000
05_high_pti,1.000978,1.000868,1.000513,1.000377,1.001508,1.000000
06_car_make,0.946760,0.955347,0.950940,0.955706,0.944171,0.947368
07_theft_risk,0.946760,0.955347,0.950940,0.955706,0.944171,0.947368
08_mcy_low_mileage,0.946760,0.955347,0.950940,0.955706,0.944171,0.947368
09_weekend_weekday,0.949331,0.955899,0.950203,0.955626,0.949353,0.952316
10_student_loans,0.938009,0.941236,0.933415,0.942351,0.936047,0.933624
11_low_pti,0.931157,0.934796,0.928292,0.936768,0.931834,0.933624
12_chime,0.960432,0.959795,0.940099,0.950731,0.955589,0.941082
13_employment_type,0.961293,0.960358,0.941276,0.950554,0.955104,0.938567
14_auth_tradelines,0.964555,0.963084,0.944130,0.952297,0.956836,0.941082
15_fraud,0.960582,0.955918,0.933193,0.943818,0.944250,0.941082
16_driver_flag,0.965787,0.960987,0.938305,0.948603,0.951322,0.941082
17_pricing_scalar,0.904894,0.901939,0.876004,0.892238,0.899329,0.894681
18_final,0.906927,0.902641,0.881946,0.898250,0.901737,0.900675
--- FINAL_MULT (mean),0.906927,0.902641,0.881946,0.898250,0.901737,0.900675
--- WTD_MULT_RAGU,0.891642,0.887608,0.871685,0.881985,0.891698,0.875964
--- GROSS_LOSS_IMPACT,2.708958,2.809810,3.207887,2.950382,2.707562,3.100894
--- N_RECORDS,716.000000,576.000000,585.000000,531.000000,398.000000,38.000000

--- FRN Flag Means ---

,FRN | 2026-03-29/2026-04-04,FRN | 2026-04-05/2026-04-11,FRN | 2026-04-12/2026-04-18,FRN | 2026-04-19/2026-04-25,FRN | 2026-04-26/2026-05-02,FRN | 2026-05-03/2026-05-09
prev_co_flag,0.006983,0.005208,0.003419,0.001883,0.015075,0.000000
small_amt_financed_flag,0.008380,0.006944,0.005128,0.009416,0.015075,0.000000
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
zero_cash_down_flag,0.027933,0.022569,0.023932,0.037665,0.042714,0.026316
high_mileage_vehicle_flag,0.002793,0.003472,0.001709,0.001883,0.000000,0.000000
high_pti_flag,0.004190,0.003472,0.008547,0.001883,0.005025,0.026316
car_make_penalty_flag,0.000000,0.000000,0.000000,0.001883,0.000000,0.000000
car_make_benefit_flag,0.270950,0.227431,0.247863,0.224105,0.286432,0.263158
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
weekend_flag,0.250000,0.279514,0.297436,0.284369,0.208543,0.210526
weekday_flag,0.750000,0.720486,0.702564,0.715631,0.791457,0.789474
student_loan_flag,0.135475,0.107639,0.088889,0.116761,0.118090,0.078947
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
low_pti_flag,0.047486,0.045139,0.035897,0.039548,0.030151,0.000000
nonkmx_chime_flag,0.238827,0.223958,0.172650,0.178908,0.218593,0.157895
seasonal_employment_pct,0.022346,0.015625,0.022222,0.016949,0.010050,0.000000
waiter_employment_pct,0.011173,0.008681,0.010256,0.018832,0.015075,0.026316
nonkmx_auth_tradelines_flag,0.036313,0.029514,0.030769,0.018832,0.017588,0.026316
fraud_adjustment_mean,0.994665,0.992726,0.988120,0.990565,0.985905,1.000000
driver_flag,0.040503,0.038194,0.039316,0.037665,0.055276,0.000000
pricing_scalar_mean,0.926013,0.925217,0.921662,0.929101,0.931683,0.945724
--- N_RECORDS,716.000000,576.000000,585.000000,531.000000,398.000000,38.000000

--- FRN Gross Loss Attribution ---

,FRN | 2026-03-29/2026-04-04,FRN | 2026-04-05/2026-04-11,FRN | 2026-04-12/2026-04-18,FRN | 2026-04-19/2026-04-25,FRN | 2026-04-26/2026-05-02,FRN | 2026-05-03/2026-05-09
Previous ACA Chargeoff,-0.019357,-0.014283,-0.008729,-0.005177,-0.039433,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.007739,-0.009518,-0.004363,-0.005176,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,1.544151,1.276877,1.297630,1.256004,1.543254,1.602664
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,-0.075205,-0.015848,0.019792,0.002297,-0.143289,-0.154395
Student Loans,0.332697,0.424066,0.455188,0.384630,0.369494,0.587585
Low PTI,0.203301,0.188327,0.140543,0.163385,0.118100,-0.000000
Chime / Secured Credit,-0.858352,-0.723952,-0.322740,-0.406805,-0.658966,-0.235851
Employment Type,-0.024854,-0.016094,-0.031932,0.005116,0.013291,0.079328
Authorized Tradelines,-0.093947,-0.077743,-0.077331,-0.050360,-0.047434,-0.079328
Fraud Adjustment,0.114446,0.204863,0.297535,0.245896,0.346617,-0.000000
Driver Flag,-0.149829,-0.145080,-0.139485,-0.139045,-0.195321,-0.000000
Dealer Level (Pricing Scalar),1.805864,1.739517,1.754390,1.684260,1.471234,1.498794
Final Clip,-0.062218,-0.021320,-0.172609,-0.184643,-0.069986,-0.197903
--- TOTAL (check),2.708958,2.809810,3.207887,2.950382,2.707562,3.100894

============================================================
  DIAGNOSTICS: STG
============================================================

============================================================
  STG 2026-03-29/2026-04-04  (n=379)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.005277  | loss_multiplier mean: 1.000528
02_small_af | flag mean: 0.002639  | loss_multiplier mean: 1.000528
03_zero_cd  | flag mean: 0.100264  | loss_multiplier mean: 1.000528
04_high_mi  | flag mean: 0.002639  | loss_multiplier mean: 1.000792
05_high_pti | flag mean: 0.005277  | loss_multiplier mean: 1.000792
06_car_make | penalty: 0.000000  benefit: 0.319261  | loss_multiplier mean: 0.936939
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.936939
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.936939
09_wknd/day | weekend: 0.266491  weekday: 0.733509  | loss_multiplier mean: 0.938243
10_stud_ln  | flag mean: 0.124011  | loss_multiplier mean: 0.927458
11_low_pti  | flag mean: 0.044855  | loss_multiplier mean: 0.920859
12_chime    | flag mean: 0.197889  | loss_multiplier mean: 0.938197
13_employ   | seasonal: 0.021108  waiter: 0.021108  | loss_multiplier mean: 0.938118
14_auth_tl  | flag mean: 0.026385  | loss_multiplier mean: 0.940570
15_fraud    | fraud_adj mean: 0.969235  | loss_multiplier mean: 0.912413
16_driver   | flag mean: 0.021108  | loss_multiplier mean: 0.914858
17_pricing  | scalar mean: 0.942876  | loss_multiplier mean: 0.879460
18_final    | loss_multiplier mean: 0.881062  (post all clips)
  bb_populated: 377 / 379  wtd_mult: 0.871483  ragu_gli: 3.2129

============================================================
  STG 2026-04-05/2026-04-11  (n=370)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.005405  | loss_multiplier mean: 1.000541
02_small_af | flag mean: 0.008108  | loss_multiplier mean: 1.000541
03_zero_cd  | flag mean: 0.064865  | loss_multiplier mean: 1.000541
04_high_mi  | flag mean: 0.010811  | loss_multiplier mean: 1.001622
05_high_pti | flag mean: 0.008108  | loss_multiplier mean: 1.001622
06_car_make | penalty: 0.000000  benefit: 0.310811  | loss_multiplier mean: 0.939405
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.939405
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.939405
09_wknd/day | weekend: 0.318919  weekday: 0.681081  | loss_multiplier mean: 0.937080
10_stud_ln  | flag mean: 0.132432  | loss_multiplier mean: 0.927084
11_low_pti  | flag mean: 0.048649  | loss_multiplier mean: 0.920215
12_chime    | flag mean: 0.164865  | loss_multiplier mean: 0.930235
13_employ   | seasonal: 0.024324  waiter: 0.027027  | loss_multiplier mean: 0.929872
14_auth_tl  | flag mean: 0.024324  | loss_multiplier mean: 0.932078
15_fraud    | fraud_adj mean: 0.974622  | loss_multiplier mean: 0.909447
16_driver   | flag mean: 0.035135  | loss_multiplier mean: 0.913856
17_pricing  | scalar mean: 0.943649  | loss_multiplier mean: 0.881428
18_final    | loss_multiplier mean: 0.885871  (post all clips)

  bb_populated: 369 / 370  wtd_mult: 0.873306  ragu_gli: 3.1673

============================================================
  STG 2026-04-12/2026-04-18  (n=352)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.002841  | loss_multiplier mean: 1.000284
02_small_af | flag mean: 0.005682  | loss_multiplier mean: 1.000284
03_zero_cd  | flag mean: 0.068182  | loss_multiplier mean: 1.000284
04_high_mi  | flag mean: 0.008523  | loss_multiplier mean: 1.001136
05_high_pti | flag mean: 0.005682  | loss_multiplier mean: 1.001136
06_car_make | penalty: 0.000000  benefit: 0.357955  | loss_multiplier mean: 0.929545
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.929545
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.929545
09_wknd/day | weekend: 0.272727  weekday: 0.727273  | loss_multiplier mean: 0.930358
10_stud_ln  | flag mean: 0.156250  | loss_multiplier mean: 0.923250
11_low_pti  | flag mean: 0.036932  | loss_multiplier mean: 0.918057
12_chime    | flag mean: 0.224432  | loss_multiplier mean: 0.943382
13_employ   | seasonal: 0.008523  waiter: 0.011364  | loss_multiplier mean: 0.943038
14_auth_tl  | flag mean: 0.028409  | loss_multiplier mean: 0.945595
15_fraud    | fraud_adj mean: 0.969858  | loss_multiplier mean: 0.918972
16_driver   | flag mean: 0.019886  | loss_multiplier mean: 0.921553
17_pricing  | scalar mean: 0.940909  | loss_multiplier mean: 0.887908
18_final    | loss_multiplier mean: 0.891009  (post all clips)
  bb_populated: 350 / 352  wtd_mult: 0.880593  ragu_gli: 2.9852

============================================================
  STG 2026-04-19/2026-04-25  (n=336)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.005952  | loss_multiplier mean: 1.000595
02_small_af | flag mean: 0.002976  | loss_multiplier mean: 1.000595
03_zero_cd  | flag mean: 0.050595  | loss_multiplier mean: 1.000595
04_high_mi  | flag mean: 0.002976  | loss_multiplier mean: 1.000893
05_high_pti | flag mean: 0.014881  | loss_multiplier mean: 1.000893
06_car_make | penalty: 0.000000  benefit: 0.339286  | loss_multiplier mean: 0.932976
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.932976
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.932976
09_wknd/day | weekend: 0.229167  weekday: 0.770833  | loss_multiplier mean: 0.936619
10_stud_ln  | flag mean: 0.101190  | loss_multiplier mean: 0.923009
11_low_pti  | flag mean: 0.035714  | loss_multiplier mean: 0.918119
12_chime    | flag mean: 0.175595  | loss_multiplier mean: 0.931134
13_employ   | seasonal: 0.023810  waiter: 0.014881  | loss_multiplier mean: 0.931779
14_auth_tl  | flag mean: 0.020833  | loss_multiplier mean: 0.933850
15_fraud    | fraud_adj mean: 0.970179  | loss_multiplier mean: 0.907508
16_driver   | flag mean: 0.017857  | loss_multiplier mean: 0.909528

17_pricing  | scalar mean: 0.934226  | loss_multiplier mean: 0.871840
18_final    | loss_multiplier mean: 0.877372  (post all clips)
  bb_populated: 336 / 336  wtd_mult: 0.866575  ragu_gli: 3.3356

============================================================
  STG 2026-04-26/2026-05-02  (n=205)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.004878  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.063415  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.004878  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.375610  | loss_multiplier mean: 0.924878
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.924878
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.924878
09_wknd/day | weekend: 0.209756  weekday: 0.790244  | loss_multiplier mean: 0.929580
10_stud_ln  | flag mean: 0.107317  | loss_multiplier mean: 0.915608
11_low_pti  | flag mean: 0.009756  | loss_multiplier mean: 0.914444
12_chime    | flag mean: 0.185366  | loss_multiplier mean: 0.929746
13_employ   | seasonal: 0.019512  waiter: 0.014634  | loss_multiplier mean: 0.930270
14_auth_tl  | flag mean: 0.019512  | loss_multiplier mean: 0.931905
15_fraud    | fraud_adj mean: 0.965317  | loss_multiplier mean: 0.900811
16_driver   | flag mean: 0.009756  | loss_multiplier mean: 0.902146
17_pricing  | scalar mean: 0.936098  | loss_multiplier mean: 0.865878
18_final    | loss_multiplier mean: 0.870297  (post all clips)

  bb_populated: 205 / 205  wtd_mult: 0.863564  ragu_gli: 3.4109

============================================================
  STG 2026-05-03/2026-05-09  (n=16)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.250000  | loss_multiplier mean: 0.950000
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950000
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950000
09_wknd/day | weekend: 0.187500  weekday: 0.812500  | loss_multiplier mean: 0.956750
10_stud_ln  | flag mean: 0.187500  | loss_multiplier mean: 0.951252
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.951252
12_chime    | flag mean: 0.062500  | loss_multiplier mean: 0.938054
13_employ   | seasonal: 0.000000  waiter: 0.000000  | loss_multiplier mean: 0.938054
14_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 0.938054
15_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 0.938054
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.938054
17_pricing  | scalar mean: 0.906250  | loss_multiplier mean: 0.855602
18_final    | loss_multiplier mean: 0.864602  (post all clips)

  bb_populated: 16 / 16  wtd_mult: 0.845156  ragu_gli: 3.8711

--- STG Multiplier Steps ---

,STG | 2026-03-29/2026-04-04,STG | 2026-04-05/2026-04-11,STG | 2026-04-12/2026-04-18,STG | 2026-04-19/2026-04-25,STG | 2026-04-26/2026-05-02,STG | 2026-05-03/2026-05-09
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000528,1.000541,1.000284,1.000595,1.000000,1.000000
02_small_amt_financed,1.000528,1.000541,1.000284,1.000595,1.000000,1.000000
03_zero_cash_down,1.000528,1.000541,1.000284,1.000595,1.000000,1.000000
04_high_mileage,1.000792,1.001622,1.001136,1.000893,1.000000,1.000000
05_high_pti,1.000792,1.001622,1.001136,1.000893,1.000000,1.000000
06_car_make,0.936939,0.939405,0.929545,0.932976,0.924878,0.950000
07_theft_risk,0.936939,0.939405,0.929545,0.932976,0.924878,0.950000
08_mcy_low_mileage,0.936939,0.939405,0.929545,0.932976,0.924878,0.950000
09_weekend_weekday,0.938243,0.937080,0.930358,0.936619,0.929580,0.956750
10_student_loans,0.927458,0.927084,0.923250,0.923009,0.915608,0.951252
11_low_pti,0.920859,0.920215,0.918057,0.918119,0.914444,0.951252
12_chime,0.938197,0.930235,0.943382,0.931134,0.929746,0.938054
13_employment_type,0.938118,0.929872,0.943038,0.931779,0.930270,0.938054
14_auth_tradelines,0.940570,0.932078,0.945595,0.933850,0.931905,0.938054
15_fraud,0.912413,0.909447,0.918972,0.907508,0.900811,0.938054
16_driver_flag,0.914858,0.913856,0.921553,0.909528,0.902146,0.938054
17_pricing_scalar,0.879460,0.881428,0.887908,0.871840,0.865878,0.855602
18_final,0.881062,0.885871,0.891009,0.877372,0.870297,0.864602
--- FINAL_MULT (mean),0.881062,0.885871,0.891009,0.877372,0.870297,0.864602
--- WTD_MULT_RAGU,0.871483,0.873306,0.880593,0.866575,0.863564,0.845156
--- GROSS_LOSS_IMPACT,3.212925,3.167343,2.985166,3.335613,3.410911,3.871103
--- N_RECORDS,379.000000,370.000000,352.000000,336.000000,205.000000,16.000000

--- STG Flag Means ---

,STG | 2026-03-29/2026-04-04,STG | 2026-04-05/2026-04-11,STG | 2026-04-12/2026-04-18,STG | 2026-04-19/2026-04-25,STG | 2026-04-26/2026-05-02,STG | 2026-05-03/2026-05-09
prev_co_flag,0.005277,0.005405,0.002841,0.005952,0.000000,0.00000
small_amt_financed_flag,0.002639,0.008108,0.005682,0.002976,0.004878,0.00000
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000
zero_cash_down_flag,0.100264,0.064865,0.068182,0.050595,0.063415,0.00000
high_mileage_vehicle_flag,0.002639,0.010811,0.008523,0.002976,0.000000,0.00000
high_pti_flag,0.005277,0.008108,0.005682,0.014881,0.004878,0.00000
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
car_make_benefit_flag,0.319261,0.310811,0.357955,0.339286,0.375610,0.25000
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
weekend_flag,0.266491,0.318919,0.272727,0.229167,0.209756,0.18750
weekday_flag,0.733509,0.681081,0.727273,0.770833,0.790244,0.81250
student_loan_flag,0.124011,0.132432,0.156250,0.101190,0.107317,0.18750
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000
low_pti_flag,0.044855,0.048649,0.036932,0.035714,0.009756,0.00000
nonkmx_chime_flag,0.197889,0.164865,0.224432,0.175595,0.185366,0.06250
seasonal_employment_pct,0.021108,0.024324,0.008523,0.023810,0.019512,0.00000
waiter_employment_pct,0.021108,0.027027,0.011364,0.014881,0.014634,0.00000
nonkmx_auth_tradelines_flag,0.026385,0.024324,0.028409,0.020833,0.019512,0.00000
fraud_adjustment_mean,0.969235,0.974622,0.969858,0.970179,0.965317,1.00000
driver_flag,0.021108,0.035135,0.019886,0.017857,0.009756,0.00000
pricing_scalar_mean,0.942876,0.943649,0.940909,0.934226,0.936098,0.90625
--- N_RECORDS,379.000000,370.000000,352.000000,336.000000,205.000000,16.00000

--- STG Gross Loss Attribution ---

,STG | 2026-03-29/2026-04-04,STG | 2026-04-05/2026-04-11,STG | 2026-04-12/2026-04-18,STG | 2026-04-19/2026-04-25,STG | 2026-04-26/2026-05-02,STG | 2026-05-03/2026-05-09
Previous ACA Chargeoff,-0.013386,-0.014124,-0.007348,-0.015172,-0.000000,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.006690,-0.028225,-0.022031,-0.007583,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,1.672802,1.676108,1.919263,1.791619,1.917426,1.364821
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,-0.035274,0.064779,-0.022601,-0.099360,-0.124521,-0.188390
Student Loans,0.293332,0.280314,0.198394,0.373214,0.371867,0.153332
Low PTI,0.181183,0.194349,0.145917,0.135440,0.031226,-0.000000
Chime / Secured Credit,-0.473290,-0.283053,-0.703919,-0.358906,-0.407458,0.371769
Employment Type,0.002139,0.010219,0.009423,-0.017657,-0.013829,-0.000000
Authorized Tradelines,-0.066234,-0.061946,-0.070038,-0.056612,-0.043119,-0.000000
Fraud Adjustment,0.771177,0.642444,0.738741,0.729556,0.833219,-0.000000
Driver Flag,-0.067885,-0.126420,-0.072538,-0.056687,-0.036381,-0.000000
Dealer Level (Pricing Scalar),1.001228,0.944335,0.962063,1.079025,1.007488,2.448019
Final Clip,-0.046177,-0.131437,-0.090160,-0.161264,-0.125008,-0.278448
--- TOTAL (check),3.212925,3.167343,2.985166,3.335613,3.410911,3.871103

============================================================
  DIAGNOSTICS: FLD
============================================================

============================================================
  FLD 2026-03-29/2026-04-04  (n=230)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.008696  | loss_multiplier mean: 1.000870
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000870
03_zero_cd  | flag mean: 0.091304  | loss_multiplier mean: 1.000870
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000870
05_high_pti | flag mean: 0.004348  | loss_multiplier mean: 1.000870
06_car_make | penalty: 0.000000  benefit: 0.221739  | loss_multiplier mean: 0.956522
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.956522
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.956522
09_wknd/day | weekend: 0.247826  weekday: 0.752174  | loss_multiplier mean: 0.959096
10_stud_ln  | flag mean: 0.165217  | loss_multiplier mean: 0.952942
11_low_pti  | flag mean: 0.073913  | loss_multiplier mean: 0.942220
12_chime    | flag mean: 0.221739  | loss_multiplier mean: 0.967571
13_employ   | seasonal: 0.004348  waiter: 0.017391  | loss_multiplier mean: 0.966143
14_auth_tl  | flag mean: 0.026087  | loss_multiplier mean: 0.968341
15_fraud    | fraud_adj mean: 0.991783  | loss_multiplier mean: 0.960705
16_driver   | flag mean: 0.030435  | loss_multiplier mean: 0.965309
17_pricing  | scalar mean: 0.908043  | loss_multiplier mean: 0.886957
18_final    | loss_multiplier mean: 0.898311  (post all clips)

  bb_populated: 230 / 230  wtd_mult: 0.894195  ragu_gli: 2.6451

============================================================
  FLD 2026-04-05/2026-04-11  (n=218)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004587  | loss_multiplier mean: 1.000459
02_small_af | flag mean: 0.004587  | loss_multiplier mean: 1.000459
03_zero_cd  | flag mean: 0.133028  | loss_multiplier mean: 1.000459
04_high_mi  | flag mean: 0.004587  | loss_multiplier mean: 1.000917
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000917
06_car_make | penalty: 0.000000  benefit: 0.211009  | loss_multiplier mean: 0.958716
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.958716
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.958716
09_wknd/day | weekend: 0.229358  weekday: 0.770642  | loss_multiplier mean: 0.962284
10_stud_ln  | flag mean: 0.211009  | loss_multiplier mean: 0.960634
11_low_pti  | flag mean: 0.032110  | loss_multiplier mean: 0.955888
12_chime    | flag mean: 0.201835  | loss_multiplier mean: 0.975255
13_employ   | seasonal: 0.022936  waiter: 0.022936  | loss_multiplier mean: 0.975164
14_auth_tl  | flag mean: 0.036697  | loss_multiplier mean: 0.978238
15_fraud    | fraud_adj mean: 0.992064  | loss_multiplier mean: 0.971992
16_driver   | flag mean: 0.018349  | loss_multiplier mean: 0.974320
17_pricing  | scalar mean: 0.905734  | loss_multiplier mean: 0.885727
18_final    | loss_multiplier mean: 0.896031  (post all clips)
  bb_populated: 217 / 218  wtd_mult: 0.900177  ragu_gli: 2.4956

============================================================
  FLD 2026-04-12/2026-04-18  (n=187)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.010695  | loss_multiplier mean: 1.001070
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001070
03_zero_cd  | flag mean: 0.106952  | loss_multiplier mean: 1.001070
04_high_mi  | flag mean: 0.005348  | loss_multiplier mean: 1.001604
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001604
06_car_make | penalty: 0.000000  benefit: 0.160428  | loss_multiplier mean: 0.969519
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.969519
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.969519
09_wknd/day | weekend: 0.320856  weekday: 0.679144  | loss_multiplier mean: 0.966973
10_stud_ln  | flag mean: 0.219251  | loss_multiplier mean: 0.966802
11_low_pti  | flag mean: 0.026738  | loss_multiplier mean: 0.962997
12_chime    | flag mean: 0.203209  | loss_multiplier mean: 0.985055
13_employ   | seasonal: 0.021390  waiter: 0.037433  | loss_multiplier mean: 0.983567
14_auth_tl  | flag mean: 0.010695  | loss_multiplier mean: 0.984519
15_fraud    | fraud_adj mean: 0.993743  | loss_multiplier mean: 0.978025
16_driver   | flag mean: 0.016043  | loss_multiplier mean: 0.980525
17_pricing  | scalar mean: 0.911765  | loss_multiplier mean: 0.902104
18_final    | loss_multiplier mean: 0.902333  (post all clips)

  bb_populated: 186 / 187  wtd_mult: 0.906152  ragu_gli: 2.3462

============================================================
  FLD 2026-04-19/2026-04-25  (n=173)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.011561  | loss_multiplier mean: 1.001156
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001156
03_zero_cd  | flag mean: 0.104046  | loss_multiplier mean: 1.001156
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001156
05_high_pti | flag mean: 0.011561  | loss_multiplier mean: 1.001156
06_car_make | penalty: 0.000000  benefit: 0.213873  | loss_multiplier mean: 0.958382
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.958382
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.958382
09_wknd/day | weekend: 0.283237  weekday: 0.716763  | loss_multiplier mean: 0.958491
10_stud_ln  | flag mean: 0.179191  | loss_multiplier mean: 0.953573
11_low_pti  | flag mean: 0.034682  | loss_multiplier mean: 0.948401
12_chime    | flag mean: 0.236994  | loss_multiplier mean: 0.979448
13_employ   | seasonal: 0.011561  waiter: 0.023121  | loss_multiplier mean: 0.978436
14_auth_tl  | flag mean: 0.017341  | loss_multiplier mean: 0.980108
15_fraud    | fraud_adj mean: 1.002139  | loss_multiplier mean: 0.983337
16_driver   | flag mean: 0.046243  | loss_multiplier mean: 0.990238
17_pricing  | scalar mean: 0.911850  | loss_multiplier mean: 0.912671
18_final    | loss_multiplier mean: 0.908721  (post all clips)
  bb_populated: 171 / 173  wtd_mult: 0.908499  ragu_gli: 2.2875

============================================================
  FLD 2026-04-26/2026-05-02  (n=131)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.007634  | loss_multiplier mean: 1.000763
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000763
03_zero_cd  | flag mean: 0.152672  | loss_multiplier mean: 1.000763
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000763
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000763
06_car_make | penalty: 0.000000  benefit: 0.229008  | loss_multiplier mean: 0.954962
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.954962
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.954962
09_wknd/day | weekend: 0.206107  weekday: 0.793893  | loss_multiplier mean: 0.960382
10_stud_ln  | flag mean: 0.229008  | loss_multiplier mean: 0.961242
11_low_pti  | flag mean: 0.045802  | loss_multiplier mean: 0.955299
12_chime    | flag mean: 0.206107  | loss_multiplier mean: 0.978268
13_employ   | seasonal: 0.022901  waiter: 0.030534  | loss_multiplier mean: 0.976921
14_auth_tl  | flag mean: 0.045802  | loss_multiplier mean: 0.981296
15_fraud    | fraud_adj mean: 0.997710  | loss_multiplier mean: 0.979734
16_driver   | flag mean: 0.030534  | loss_multiplier mean: 0.984361
17_pricing  | scalar mean: 0.892748  | loss_multiplier mean: 0.888598

18_final    | loss_multiplier mean: 0.894364  (post all clips)
  bb_populated: 130 / 131  wtd_mult: 0.910607  ragu_gli: 2.2348

============================================================
  FLD 2026-05-03/2026-05-09  (n=18)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.055556  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.277778  | loss_multiplier mean: 0.944444
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.944444
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.944444
09_wknd/day | weekend: 0.333333  weekday: 0.666667  | loss_multiplier mean: 0.940778
10_stud_ln  | flag mean: 0.111111  | loss_multiplier mean: 0.928142
11_low_pti  | flag mean: 0.055556  | loss_multiplier mean: 0.920463
12_chime    | flag mean: 0.277778  | loss_multiplier mean: 0.962039
13_employ   | seasonal: 0.000000  waiter: 0.000000  | loss_multiplier mean: 0.962039
14_auth_tl  | flag mean: 0.111111  | loss_multiplier mean: 0.971930
15_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 0.971930
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.971930
17_pricing  | scalar mean: 0.808333  | loss_multiplier mean: 0.794889
18_final    | loss_multiplier mean: 0.822504  (post all clips)
  bb_populated: 18 / 18  wtd_mult: 0.812137  ragu_gli: 4.6966

--- FLD Multiplier Steps ---

,FLD | 2026-03-29/2026-04-04,FLD | 2026-04-05/2026-04-11,FLD | 2026-04-12/2026-04-18,FLD | 2026-04-19/2026-04-25,FLD | 2026-04-26/2026-05-02,FLD | 2026-05-03/2026-05-09
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000870,1.000459,1.001070,1.001156,1.000763,1.000000
02_small_amt_financed,1.000870,1.000459,1.001070,1.001156,1.000763,1.000000
03_zero_cash_down,1.000870,1.000459,1.001070,1.001156,1.000763,1.000000
04_high_mileage,1.000870,1.000917,1.001604,1.001156,1.000763,1.000000
05_high_pti,1.000870,1.000917,1.001604,1.001156,1.000763,1.000000
06_car_make,0.956522,0.958716,0.969519,0.958382,0.954962,0.944444
07_theft_risk,0.956522,0.958716,0.969519,0.958382,0.954962,0.944444
08_mcy_low_mileage,0.956522,0.958716,0.969519,0.958382,0.954962,0.944444
09_weekend_weekday,0.959096,0.962284,0.966973,0.958491,0.960382,0.940778
10_student_loans,0.952942,0.960634,0.966802,0.953573,0.961242,0.928142
11_low_pti,0.942220,0.955888,0.962997,0.948401,0.955299,0.920463
12_chime,0.967571,0.975255,0.985055,0.979448,0.978268,0.962039
13_employment_type,0.966143,0.975164,0.983567,0.978436,0.976921,0.962039
14_auth_tradelines,0.968341,0.978238,0.984519,0.980108,0.981296,0.971930
15_fraud,0.960705,0.971992,0.978025,0.983337,0.979734,0.971930
16_driver_flag,0.965309,0.974320,0.980525,0.990238,0.984361,0.971930
17_pricing_scalar,0.886957,0.885727,0.902104,0.912671,0.888598,0.794889
18_final,0.898311,0.896031,0.902333,0.908721,0.894364,0.822504
--- FINAL_MULT (mean),0.898311,0.896031,0.902333,0.908721,0.894364,0.822504
--- WTD_MULT_RAGU,0.894195,0.900177,0.906152,0.908499,0.910607,0.812137
--- GROSS_LOSS_IMPACT,2.645117,2.495566,2.346212,2.287513,2.234819,4.696566
--- N_RECORDS,230.000000,218.000000,187.000000,173.000000,131.000000,18.000000

--- FLD Flag Means ---

,FLD | 2026-03-29/2026-04-04,FLD | 2026-04-05/2026-04-11,FLD | 2026-04-12/2026-04-18,FLD | 2026-04-19/2026-04-25,FLD | 2026-04-26/2026-05-02,FLD | 2026-05-03/2026-05-09
prev_co_flag,0.008696,0.004587,0.010695,0.011561,0.007634,0.000000
small_amt_financed_flag,0.000000,0.004587,0.000000,0.000000,0.000000,0.000000
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
zero_cash_down_flag,0.091304,0.133028,0.106952,0.104046,0.152672,0.055556
high_mileage_vehicle_flag,0.000000,0.004587,0.005348,0.000000,0.000000,0.000000
high_pti_flag,0.004348,0.000000,0.000000,0.011561,0.000000,0.000000
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
car_make_benefit_flag,0.221739,0.211009,0.160428,0.213873,0.229008,0.277778
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
weekend_flag,0.247826,0.229358,0.320856,0.283237,0.206107,0.333333
weekday_flag,0.752174,0.770642,0.679144,0.716763,0.793893,0.666667
student_loan_flag,0.165217,0.211009,0.219251,0.179191,0.229008,0.111111
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
low_pti_flag,0.073913,0.032110,0.026738,0.034682,0.045802,0.055556
nonkmx_chime_flag,0.221739,0.201835,0.203209,0.236994,0.206107,0.277778
seasonal_employment_pct,0.004348,0.022936,0.021390,0.011561,0.022901,0.000000
waiter_employment_pct,0.017391,0.022936,0.037433,0.023121,0.030534,0.000000
nonkmx_auth_tradelines_flag,0.026087,0.036697,0.010695,0.017341,0.045802,0.111111
fraud_adjustment_mean,0.991783,0.992064,0.993743,1.002139,0.997710,1.000000
driver_flag,0.030435,0.018349,0.016043,0.046243,0.030534,0.000000
pricing_scalar_mean,0.908043,0.905734,0.911765,0.911850,0.892748,0.808333
--- N_RECORDS,230.000000,218.000000,187.000000,173.000000,131.000000,18.000000

--- FLD Gross Loss Attribution ---

,FLD | 2026-03-29/2026-04-04,FLD | 2026-04-05/2026-04-11,FLD | 2026-04-12/2026-04-18,FLD | 2026-04-19/2026-04-25,FLD | 2026-04-26/2026-05-02,FLD | 2026-05-03/2026-05-09
Previous ACA Chargeoff,-0.021439,-0.010425,-0.024403,-0.027613,-0.015275,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.000000,-0.010421,-0.012192,-0.000000,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,1.117876,0.979262,0.743289,1.043527,0.937766,1.373826
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,-0.066284,-0.084464,0.060017,-0.002739,-0.113288,0.093496
Student Loans,0.158755,0.039012,0.004055,0.122958,-0.017926,0.325006
Low PTI,0.279102,0.112607,0.090021,0.129971,0.124154,0.199689
Chime / Secured Credit,-0.654873,-0.455974,-0.517016,-0.769816,-0.475606,-1.061837
Employment Type,0.036439,0.002116,0.034504,0.024694,0.027581,-0.000000
Authorized Tradelines,-0.056045,-0.071559,-0.022087,-0.040799,-0.089449,-0.245847
Fraud Adjustment,0.195277,0.145627,0.151080,-0.078608,0.031885,-0.000000
Driver Flag,-0.117939,-0.054382,-0.058273,-0.167126,-0.094306,-0.000000
Dealer Level (Pricing Scalar),2.087996,2.167093,1.903005,1.949409,2.048763,4.833062
Final Clip,-0.313747,-0.262926,-0.005787,0.103653,-0.129480,-0.820828
--- TOTAL (check),2.645117,2.495566,2.346212,2.287513,2.234819,4.696566

============================================================
  DIAGNOSTICS: ENT
============================================================

============================================================
  ENT 2026-03-29/2026-04-04  (n=286)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006993  | loss_multiplier mean: 1.000699
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000699
03_zero_cd  | flag mean: 0.115385  | loss_multiplier mean: 1.000699
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000699
05_high_pti | flag mean: 0.010490  | loss_multiplier mean: 1.000699
06_car_make | penalty: 0.000000  benefit: 0.255245  | loss_multiplier mean: 0.949650
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.949650
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.949650
09_wknd/day | weekend: 0.188811  weekday: 0.811189  | loss_multiplier mean: 0.956357
10_stud_ln  | flag mean: 0.171329  | loss_multiplier mean: 0.949968
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.949968
12_chime    | flag mean: 0.279720  | loss_multiplier mean: 0.989582
13_employ   | seasonal: 0.013986  waiter: 0.003497  | loss_multiplier mean: 0.990679
14_auth_tl  | flag mean: 0.017483  | loss_multiplier mean: 0.992304
15_fraud    | fraud_adj mean: 1.000175  | loss_multiplier mean: 0.990242
16_driver   | flag mean: 0.010490  | loss_multiplier mean: 0.992015
17_pricing  | scalar mean: 0.992657  | loss_multiplier mean: 0.992730
18_final    | loss_multiplier mean: 0.986779  (post all clips)
  bb_populated: 286 / 286  wtd_mult: 0.979421  ragu_gli: 0.5145

============================================================
  ENT 2026-04-05/2026-04-11  (n=212)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.018868  | loss_multiplier mean: 1.001887
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001887
03_zero_cd  | flag mean: 0.075472  | loss_multiplier mean: 1.001887
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001887
05_high_pti | flag mean: 0.018868  | loss_multiplier mean: 1.001887
06_car_make | penalty: 0.000000  benefit: 0.250000  | loss_multiplier mean: 0.951792
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.951792
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.951792
09_wknd/day | weekend: 0.141509  weekday: 0.858491  | loss_multiplier mean: 0.961385
10_stud_ln  | flag mean: 0.169811  | loss_multiplier mean: 0.954702
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.954702
12_chime    | flag mean: 0.259434  | loss_multiplier mean: 0.988006
13_employ   | seasonal: 0.009434  waiter: 0.009434  | loss_multiplier mean: 0.987946
14_auth_tl  | flag mean: 0.009434  | loss_multiplier mean: 0.988758
15_fraud    | fraud_adj mean: 1.000755  | loss_multiplier mean: 0.988941
16_driver   | flag mean: 0.009434  | loss_multiplier mean: 0.990583
17_pricing  | scalar mean: 0.988208  | loss_multiplier mean: 0.986469
18_final    | loss_multiplier mean: 0.984121  (post all clips)
  bb_populated: 212 / 212  wtd_mult: 0.971024  ragu_gli: 0.7244

============================================================
  ENT 2026-04-12/2026-04-18  (n=202)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.024752  | loss_multiplier mean: 1.002475
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002475
03_zero_cd  | flag mean: 0.079208  | loss_multiplier mean: 1.002475
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002475
05_high_pti | flag mean: 0.004950  | loss_multiplier mean: 1.002475
06_car_make | penalty: 0.000000  benefit: 0.287129  | loss_multiplier mean: 0.944950
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.944950
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.944950
09_wknd/day | weekend: 0.222772  weekday: 0.777228  | loss_multiplier mean: 0.949156
10_stud_ln  | flag mean: 0.183168  | loss_multiplier mean: 0.943532
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.943532
12_chime    | flag mean: 0.272277  | loss_multiplier mean: 0.980792
13_employ   | seasonal: 0.004950  waiter: 0.019802  | loss_multiplier mean: 0.979158
14_auth_tl  | flag mean: 0.009901  | loss_multiplier mean: 0.980009
15_fraud    | fraud_adj mean: 1.007673  | loss_multiplier mean: 0.984672
16_driver   | flag mean: 0.004950  | loss_multiplier mean: 0.985401
17_pricing  | scalar mean: 0.993812  | loss_multiplier mean: 0.984120
18_final    | loss_multiplier mean: 0.981241  (post all clips)
  bb_populated: 202 / 202  wtd_mult: 0.978738  ragu_gli: 0.5315

============================================================
  ENT 2026-04-19/2026-04-25  (n=175)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.034286  | loss_multiplier mean: 1.003429
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.003429
03_zero_cd  | flag mean: 0.142857  | loss_multiplier mean: 1.003429
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.003429
05_high_pti | flag mean: 0.005714  | loss_multiplier mean: 1.003429
06_car_make | penalty: 0.000000  benefit: 0.245714  | loss_multiplier mean: 0.954286
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.954286
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.954286
09_wknd/day | weekend: 0.194286  weekday: 0.805714  | loss_multiplier mean: 0.960691
10_stud_ln  | flag mean: 0.125714  | loss_multiplier mean: 0.947723
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.947723
12_chime    | flag mean: 0.251429  | loss_multiplier mean: 0.981156
13_employ   | seasonal: 0.017143  waiter: 0.000000  | loss_multiplier mean: 0.983197
14_auth_tl  | flag mean: 0.028571  | loss_multiplier mean: 0.986013
15_fraud    | fraud_adj mean: 1.004000  | loss_multiplier mean: 0.989205
16_driver   | flag mean: 0.005714  | loss_multiplier mean: 0.989860
17_pricing  | scalar mean: 0.996571  | loss_multiplier mean: 0.994992
18_final    | loss_multiplier mean: 0.993881  (post all clips)

  bb_populated: 175 / 175  wtd_mult: 0.984695  ragu_gli: 0.3826

============================================================
  ENT 2026-04-26/2026-05-02  (n=132)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.007576  | loss_multiplier mean: 1.000758
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000758
03_zero_cd  | flag mean: 0.136364  | loss_multiplier mean: 1.000758
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000758
05_high_pti | flag mean: 0.007576  | loss_multiplier mean: 1.000758
06_car_make | penalty: 0.000000  benefit: 0.280303  | loss_multiplier mean: 0.944697
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.944697
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.944697
09_wknd/day | weekend: 0.060606  weekday: 0.939394  | loss_multiplier mean: 0.959455
10_stud_ln  | flag mean: 0.159091  | loss_multiplier mean: 0.951481
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.951481
12_chime    | flag mean: 0.325758  | loss_multiplier mean: 1.002484
13_employ   | seasonal: 0.007576  waiter: 0.022727  | loss_multiplier mean: 1.001384
14_auth_tl  | flag mean: 0.045455  | loss_multiplier mean: 1.005303
15_fraud    | fraud_adj mean: 1.013485  | loss_multiplier mean: 1.016504
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.016504
17_pricing  | scalar mean: 0.992424  | loss_multiplier mean: 1.012334
18_final    | loss_multiplier mean: 1.012026  (post all clips)
  bb_populated: 132 / 132  wtd_mult: 1.008853  ragu_gli: -0.2213

============================================================
  ENT 2026-05-03/2026-05-09  (n=2)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000

03_zero_cd  | flag mean: 0.500000  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.500000  | loss_multiplier mean: 0.900000
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.900000
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.900000
09_wknd/day | weekend: 0.000000  weekday: 1.000000  | loss_multiplier mean: 0.918000
10_stud_ln  | flag mean: 0.000000  | loss_multiplier mean: 0.890460
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.890460
12_chime    | flag mean: 0.000000  | loss_multiplier mean: 0.860184
13_employ   | seasonal: 0.000000  waiter: 0.000000  | loss_multiplier mean: 0.860184
14_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 0.860184
15_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 0.860184
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.860184
17_pricing  | scalar mean: 1.075000  | loss_multiplier mean: 0.937880
18_final    | loss_multiplier mean: 0.937880  (post all clips)
  bb_populated: 2 / 2  wtd_mult: 0.939157  ragu_gli: nan

--- ENT Multiplier Steps ---

,ENT | 2026-03-29/2026-04-04,ENT | 2026-04-05/2026-04-11,ENT | 2026-04-12/2026-04-18,ENT | 2026-04-19/2026-04-25,ENT | 2026-04-26/2026-05-02,ENT | 2026-05-03/2026-05-09
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000699,1.001887,1.002475,1.003429,1.000758,1.000000
02_small_amt_financed,1.000699,1.001887,1.002475,1.003429,1.000758,1.000000
03_zero_cash_down,1.000699,1.001887,1.002475,1.003429,1.000758,1.000000
04_high_mileage,1.000699,1.001887,1.002475,1.003429,1.000758,1.000000
05_high_pti,1.000699,1.001887,1.002475,1.003429,1.000758,1.000000
06_car_make,0.949650,0.951792,0.944950,0.954286,0.944697,0.900000
07_theft_risk,0.949650,0.951792,0.944950,0.954286,0.944697,0.900000
08_mcy_low_mileage,0.949650,0.951792,0.944950,0.954286,0.944697,0.900000
09_weekend_weekday,0.956357,0.961385,0.949156,0.960691,0.959455,0.918000
10_student_loans,0.949968,0.954702,0.943532,0.947723,0.951481,0.890460
11_low_pti,0.949968,0.954702,0.943532,0.947723,0.951481,0.890460
12_chime,0.989582,0.988006,0.980792,0.981156,1.002484,0.860184
13_employment_type,0.990679,0.987946,0.979158,0.983197,1.001384,0.860184
14_auth_tradelines,0.992304,0.988758,0.980009,0.986013,1.005303,0.860184
15_fraud,0.990242,0.988941,0.984672,0.989205,1.016504,0.860184
16_driver_flag,0.992015,0.990583,0.985401,0.989860,1.016504,0.860184
17_pricing_scalar,0.992730,0.986469,0.984120,0.994992,1.012334,0.937880
18_final,0.986779,0.984121,0.981241,0.993881,1.012026,0.937880
--- FINAL_MULT (mean),0.986779,0.984121,0.981241,0.993881,1.012026,0.937880
--- WTD_MULT_RAGU,0.979421,0.971024,0.978738,0.984695,1.008853,0.939157
--- GROSS_LOSS_IMPACT,0.514479,0.724392,0.531538,0.382624,-0.221324,1.521087
--- N_RECORDS,286.000000,212.000000,202.000000,175.000000,132.000000,2.000000

--- ENT Flag Means ---

,ENT | 2026-03-29/2026-04-04,ENT | 2026-04-05/2026-04-11,ENT | 2026-04-12/2026-04-18,ENT | 2026-04-19/2026-04-25,ENT | 2026-04-26/2026-05-02,ENT | 2026-05-03/2026-05-09
prev_co_flag,0.006993,0.018868,0.024752,0.034286,0.007576,0.000
small_amt_financed_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000
zero_cash_down_flag,0.115385,0.075472,0.079208,0.142857,0.136364,0.500
high_mileage_vehicle_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
high_pti_flag,0.010490,0.018868,0.004950,0.005714,0.007576,0.000
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
car_make_benefit_flag,0.255245,0.250000,0.287129,0.245714,0.280303,0.500
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
weekend_flag,0.188811,0.141509,0.222772,0.194286,0.060606,0.000
weekday_flag,0.811189,0.858491,0.777228,0.805714,0.939394,1.000
student_loan_flag,0.171329,0.169811,0.183168,0.125714,0.159091,0.000
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000
low_pti_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000
nonkmx_chime_flag,0.279720,0.259434,0.272277,0.251429,0.325758,0.000
seasonal_employment_pct,0.013986,0.009434,0.004950,0.017143,0.007576,0.000
waiter_employment_pct,0.003497,0.009434,0.019802,0.000000,0.022727,0.000
nonkmx_auth_tradelines_flag,0.017483,0.009434,0.009901,0.028571,0.045455,0.000
fraud_adjustment_mean,1.000175,1.000755,1.007673,1.004000,1.013485,1.000
driver_flag,0.010490,0.009434,0.004950,0.005714,0.000000,0.000
pricing_scalar_mean,0.992657,0.988208,0.993812,0.996571,0.992424,1.075
--- N_RECORDS,286.000000,212.000000,202.000000,175.000000,132.000000,2.000

--- ENT Gross Loss Attribution ---

,ENT | 2026-03-29/2026-04-04,ENT | 2026-04-05/2026-04-11,ENT | 2026-04-12/2026-04-18,ENT | 2026-04-19/2026-04-25,ENT | 2026-04-26/2026-05-02,ENT | 2026-05-03/2026-05-09
Previous ACA Chargeoff,-0.027023,-0.085311,-0.069391,-0.213368,-0.014020,0.0
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
High Mileage Vehicle,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Car Make,2.024051,2.321396,1.658722,3.130339,1.067275,0.0
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Weekend / Weekday,-0.272024,-0.453834,-0.124656,-0.417056,-0.286973,0.0
Student Loans,0.259078,0.315716,0.166832,0.847219,0.154498,0.0
Low PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Chime / Secured Credit,-1.579265,-1.551876,-1.087115,-2.161211,-0.966710,0.0
Employment Type,-0.042828,0.002753,0.046807,-0.129550,0.020323,0.0
Authorized Tradelines,-0.063357,-0.037159,-0.024404,-0.178294,-0.072311,0.0
Fraud Adjustment,0.080435,-0.008383,-0.133239,-0.201476,-0.205131,0.0
Driver Flag,-0.069153,-0.075078,-0.020751,-0.041288,-0.000000,0.0
Dealer Level (Pricing Scalar),-0.027877,0.188321,0.036500,-0.322344,0.076100,0.0
Final Clip,0.232442,0.107846,0.082233,0.069653,0.005625,0.0
--- TOTAL (check),0.514479,0.724392,0.531538,0.382624,-0.221324,0.0

In [10]:
# =============================================================================
# CELL 9: EXCEL EXPORT
# =============================================================================

with pd.ExcelWriter(EXCEL_OUTPUT, engine='openpyxl') as writer:
    # Per-LOB diagnostic sheets
    for lob in LOBS:
        diag_data = diag_results_by_lob.get(lob, (None, None, None))
        output_df, flags_df, attribution_df = diag_data

        sheet_mult = f'{lob} Mult Steps'[:31]
        sheet_flags = f'{lob} Flags'[:31]
        sheet_attr = f'{lob} Attribution'[:31]

        if output_df is not None:
            output_df.to_excel(writer, sheet_name=sheet_mult)
        if flags_df is not None:
            flags_df.to_excel(writer, sheet_name=sheet_flags)
        if attribution_df is not None:
            attribution_df.to_excel(writer, sheet_name=sheet_attr)

    # Summary sheet with latest vintage per LOB from RAGU output
    summary_rows = []
    for lob in LOBS:
        model_df = results_by_lob.get(lob)
        if model_df is not None and len(model_df) > 0:
            lob_rows = model_df.reset_index()
            lob_rows = lob_rows[lob_rows.lob == lob]
            if len(lob_rows) > 0:
                last_vintage = lob_rows.vintage.max()
                last_row = lob_rows[lob_rows.vintage == last_vintage].iloc[0]
                summary_rows.append({
                    'LOB': lob,
                    'Latest Vintage': last_vintage,
                    'Contract MS': last_row.get('ms_original', float('nan')),
                    'Gross Loss Impact': last_row.get('gross_loss_impact', float('nan')),
                    'Recovery Impact': last_row.get('recovery_impact', float('nan')),
                    'LTV Impact': last_row.get('ltv_impact', float('nan')),
                    'APR Impact': last_row.get('apr_impact', float('nan')),
                    'RAGU Score': last_row.get('ragu_score', float('nan')),
                    'LTV': last_row.get('ltv', float('nan')),
                    'Loss Multiplier': last_row.get('loss_multiplier', float('nan')),
                })
    if summary_rows:
        summary_df = pd.DataFrame(summary_rows).set_index('LOB')
        summary_df.to_excel(writer, sheet_name='Summary')
        display(summary_df)

print(f"\nExported to {EXCEL_OUTPUT}")
print("[PROGRESS] Export Complete")

,Latest Vintage,Contract MS,Gross Loss Impact,Recovery Impact,LTV Impact,APR Impact,RAGU Score,LTV,Loss Multiplier
LOB,,,,,,,,,
AN,2026-04-26/2026-05-02,141.587233,3.389160,3.719510,4.481750,1.716585,154.894238,1.535257,0.864434
FRN,2026-05-03/2026-05-09,143.124208,3.100894,-1.104042,4.743006,-0.017608,149.846458,1.516810,0.875964
STG,2026-05-03/2026-05-09,142.529574,3.871103,14.115735,5.105693,1.830841,167.452946,1.491923,0.845156
FLD,2026-05-03/2026-05-09,140.234221,4.696566,-1.224243,1.121377,0.071818,144.899739,1.360272,0.812137
ENT,2026-04-26/2026-05-02,140.881045,-0.221324,2.353324,2.373362,-0.069050,145.317356,1.272366,1.008853

Exported to nonkmx_gl_diagnostics.xlsx
[PROGRESS] Export Complete