# KMX MTN-Specific RAGU Score Notebook
This notebook computes RAGU scores for KMX loans, broken down by MTN model (3.0, 3.1, 3.2, 4.1).
Aligned with `bareboned_ragu_new.ipynb` for diagnostic purposes.
- **Granularity:** Configurable (weekly/monthly/quarterly) via `granularity` in cell 1
- **Date handling:** Weekly uses `app_date`, monthly/quarterly use `book_date`
- **Output:** Per-model RAGU decomposition + diagnostics, exported to `new_kmx_models.xlsx`

## How to Run
1. Set `granularity`, `START_DATE`, `END_DATE` in cell 1
2. Set `run_from_pickle = True` to load pre-computed data (faster), or `False` to re-run SQL queries
3. Run All Cells
4. Results are exported to `new_kmx_models.xlsx`

In [1]:
import pandas as pd
import numpy as np
import pyodbc
import pickle
import warnings
import time
from tqdm.notebook import tqdm
from matplotlib import pyplot as plt
tqdm.pandas()
pd.set_option('display.max_columns', 100)
pd.set_option('display.min_rows', 100)
import openpyxl
import datetime as dt
import re
import os

# ── Configuration ──
granularity = 'w'                # 'q' = quarterly, 'm' = monthly, 'w' = weekly

START_DATE = '2025-12-01'
END_DATE = None                  # None = auto-detect from today's date

run_every_query = False           # True = re-run SQL, False = load pickle
run_from_pickle = not run_every_query

DATE_COL_MAP = {'q': 'book_date', 'm': 'book_date', 'w': 'app_date'}
PERIOD_FREQ_MAP = {'q': 'Q', 'm': 'M', 'w': 'W-SAT'}

BASELINES = {
    'KMX': {'ltv': 1.59, 'new_recovery_unadjusted': 0.58, 'apr': 0.25},
}

MODEL_PARAMS = {
    'mean_unit_loss': 0.5,
    'unit_loss_to_model_score': 0.02,
    'kmx_loss_scale': 0.067,
}

MTN_MODELS = [3.0, 3.1, 3.2, 4.1]
EXCEL_OUTPUT = 'new_kmx_models.xlsx'

# ── Derived values ──
date_col = DATE_COL_MAP[granularity]
start_date = pd.Timestamp(START_DATE)
end_date = pd.Timestamp(END_DATE) if END_DATE else pd.Timestamp.today().normalize()
period_freq = PERIOD_FREQ_MAP[granularity]
start_period = start_date.to_period(period_freq)
end_period = end_date.to_period(period_freq)
min_date_sql = f"'{START_DATE}'"

print(f"Granularity: {granularity}")
print(f"Date column: {date_col}")
print(f"Period range: {start_period} to {end_period}")
print(f"SQL min_date: {min_date_sql}")

Granularity: w
Date column: app_date
Period range: 2025-11-30/2025-12-06 to 2026-05-17/2026-05-23
SQL min_date: '2025-12-01'

In [2]:
# Parameters
granularity = "w"
START_DATE = "2026-01-01"
END_DATE = None
run_every_query = True
BASELINES = {"KMX": {"ltv": 1.59, "new_recovery_unadjusted": 0.58, "apr": 0.25}}
MODEL_PARAMS = {"mean_unit_loss": 0.5, "unit_loss_to_model_score": 0.02, "kmx_loss_scale": 0.067}
MTN_MODELS = [3.0, 3.1, 3.2, 4.1]

In [3]:
def run_sql(filename, sub_list=None, connection=None, filename_is_query=False):
    if sub_list is None:
        sub_list = []
    if filename_is_query:
        query = filename
    else:
        with open(filename, 'r') as file:
            query = file.read()
    for text, var in sub_list:
        query = query.replace(text, var)
    if connection is None:
        with pyodbc.connect("DSN=Redshift_prod_new") as conn:
            warnings.filterwarnings("ignore", category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings("default", category=UserWarning)
            return df
    else:
        warnings.filterwarnings("ignore", category=UserWarning)
        df = pd.read_sql_query(sql=query, con=connection)
        warnings.filterwarnings("default", category=UserWarning)
        return df


def store_pickle(data, filename):
    if isinstance(data, str):
        data, filename = filename, data
    with open(filename, 'wb') as file:
        pickle.dump(data, file)


def get_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)


def cached_sql(filename, pickle_name, sub_list=None, connection=None, force_refresh=False):
    """Fetch from SQL and cache to pickle. Reuse cache unless force_refresh=True
    or the pickle file is missing."""
    if force_refresh or not os.path.exists(pickle_name):
        df = run_sql(filename, sub_list=sub_list, connection=connection)
        store_pickle(df, pickle_name)
        return df
    return get_pickle(pickle_name)


def smooth(series):
    averaged_series = pd.Series(index=series.index, dtype=float)
    averaged_series.iloc[0] = series.iloc[0]
    averaged_series.iloc[1] = (series.iloc[0] + series.iloc[1] + series.iloc[2]) / 3
    for i in range(2, len(series) - 2):
        averaged_series.iloc[i] = series.iloc[i-2:i+3].mean()
    averaged_series.iloc[-2] = (series.iloc[-1] + series.iloc[-2] + series.iloc[-3]) / 3
    averaged_series.iloc[-1] = series.iloc[-1]
    return averaged_series


def weight_by_proceeds(metric, proceeds):
    return (metric * proceeds).sum() / proceeds.sum()


def weighted_average_and_sum(group, metrics):
    if isinstance(metrics, str):
        weighted_avg = (group[metrics] * group.amt_financed).sum() / group.amt_financed.sum()
        return pd.Series({metrics: weighted_avg, 'amt_financed': group.amt_financed.sum()})
    result_dict = {'amt_financed': group.amt_financed.sum()}
    for metric in metrics:
        weighted_avg = (group[metric] * group.amt_financed).sum() / group.amt_financed.sum()
        result_dict[metric] = weighted_avg
    return pd.Series(result_dict)


def format_vintage(period_series):
    """Convert pd.Period series to formatted vintage strings."""
    if len(period_series) == 0:
        return period_series.astype(str)
    freq = period_series.iloc[0].freqstr
    if freq == 'Q-DEC':
        return period_series.dt.year.astype(str) + ' Q' + period_series.dt.quarter.astype(str)
    elif freq == 'M':
        return period_series.dt.year.astype(str) + ' M' + period_series.dt.month.astype(str).str.zfill(2)
    return period_series.astype(str)


def rebuild_ms_df(ula_subset):
    """Recompute ms_df from a filtered ula_df subset (for per-model scoring).
    MTN 4.1 transform is already applied in-place on ula_df_total upstream."""
    ms_source = ula_subset[['lob', 'cd_model_score', 'amt_financed', 'period']].copy()
    ms_source = ms_source.rename(columns={'cd_model_score': 'model_score'})
    ms = ms_source.groupby(['period', 'lob']).apply(
        weighted_average_and_sum, 'model_score', include_groups=False
    ).reset_index()
    ms['period'] = format_vintage(ms['period'])
    return ms

In [4]:
# Per-table caches under cache/ with _v1 schema tags. When run_from_pickle=True
# (i.e. run_every_query=False) each cached_sql call reuses its pickle if present
# and falls through to SQL if missing. Delete an individual pickle to force a
# selective refresh.
#
# Note: ULA is cached under cache/ula_kmx_v1.pkl because this notebook
# applies a KMX-only filter via sub_list; that is a different schema (KMX
# subset of rows) than the full-LOB cache/ula_v1.pkl written by
# bareboned_ragu_new.ipynb. DLA and new_recovery use identical queries in both
# notebooks, so they share the same cache files.

os.makedirs('cache', exist_ok=True)
force = run_every_query

need_conn = force or not all(
    os.path.exists(p) for p in ('cache/ula_kmx_v1.pkl', 'cache/dla_v1.pkl', 'cache/new_recovery_v1.pkl')
)

if need_conn:
    with pyodbc.connect("DSN=Redshift_prod_new") as conn:
        ula_df_total = cached_sql(
            'vintage_level_ula_query.txt', 'cache/ula_kmx_v1.pkl',
            sub_list=[('{min_book_date}', f"{min_date_sql}\n  AND dru.riskdealergroup = 'KMX'")],
            connection=conn, force_refresh=force,
        )
        print('ULA ready')

        dla_df = cached_sql(
            'new_dll_query.txt', 'cache/dla_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('DLA ready')

        new_recovery = cached_sql(
            'new_recovery_queryt.txt', 'cache/new_recovery_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('New recovery ready')
else:
    ula_df_total = get_pickle('cache/ula_kmx_v1.pkl')
    dla_df = get_pickle('cache/dla_v1.pkl')
    new_recovery = get_pickle('cache/new_recovery_v1.pkl')
    print('ULA, DLA, New recovery loaded from cache')

print(f"ULA records: {len(ula_df_total):,}")
print("[PROGRESS] Data Fetch Complete")

ULA ready

DLA ready

New recovery ready
ULA records: 222,395
[PROGRESS] Data Fetch Complete

In [5]:
def get_ula_multiplier_kmx(ula_df, loss_scale=None, leave_out='None'):
    if loss_scale is None:
        loss_scale = MODEL_PARAMS['kmx_loss_scale']
    ula_df['loss_multiplier'] = 1.0

    if leave_out!='Low FICO':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_fico_flag & ~ula_df.high_model_score_flag)\
                                    + loss_scale * (ula_df.low_fico_flag & ula_df.high_model_score_flag)

    if leave_out!='Low Vantage':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_vantage_flag & ~ula_df.high_model_score_flag)\
                                    + loss_scale * (ula_df.low_vantage_flag & ula_df.high_model_score_flag)

    if leave_out!='High PTI':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0 * ula_df.normal_pti_flag \
                                    + 0.05 * ula_df.high_pti_tier_1_flag \
                                    + 0.1 * ula_df.high_pti_tier_2_flag \
                                    + (1.4 * (1 + loss_scale) - 1) * ula_df.high_pti_tier_3_flag

    ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] /= (1 + loss_scale)

    if leave_out!='Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + (-0.01 + 0.06 * ula_df.secured_credit_flag)\
                                        * ~(~ula_df.job_time_flag & ula_df.narrowed_soft_pull_flag & ula_df.secured_credit_flag)

    if leave_out!='Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 0.99 + 0.18 * ula_df.kmx_auth_tradelines_flag

    if leave_out!='Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= (
            1 + ~ula_df.job_time_flag * (~ula_df.narrowed_soft_pull_flag * -0.025
            + ula_df.narrowed_soft_pull_flag * (~ula_df.secured_credit_flag * 0.108
            + ula_df.secured_credit_flag * 0.295)))

    if leave_out != 'Fraud':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + (ula_df.fraud_adjustment - 1)

    if leave_out!='Clip':
        clipped_multiplier = np.clip(ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'], 0.8, 1.35 / (1 + loss_scale))
        ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'] = clipped_multiplier

    if leave_out!='Vehicle Age':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier']  *= 0.8593 + 0.0201 * ula_df.continuous_vehicle_age

    if leave_out !='npc':
        ula_df.loc[ula_df.kmx_npc_flag, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.high_pti_npc

    if leave_out != 'Student Loans':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.96 +  0.14 * ula_df.student_loan_flag

    if leave_out != 'high sales price':
        ula_df.loc[ula_df.mtn_model.isin([4.1]),'loss_multiplier'] *= 0.98 + 0.22 * ula_df.high_sales_price_flag

    if leave_out != 'Driver flag':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 1 + 0.15 * ula_df.driver_flag

    if leave_out!='Louisiana':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier']  *= 1 + 0.35 * ula_df.louisiana_flag

    if leave_out!='georgia':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier']  *= 1 + 0.1 * ula_df.georgia_flag

    if leave_out!='txca':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score > 140) ,'loss_multiplier']  *= 1 - 0.1 * ula_df.txca_flag
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score <= 140) &  (ula_df.cd_model_score >= 135)   ,'loss_multiplier']  *= 1 - 0.05 * ula_df.txca_flag

    if leave_out!='state_counter_adj':
        ula_df.loc[ ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1])  & (ula_df.cd_model_score < 150) & ~(ula_df.louisiana_flag | ula_df.georgia_flag | ula_df.txca_flag) ,'loss_multiplier'] *= 1.012

    if leave_out!='Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.96 + (0.01 * ula_df.soft_pull_flag  - 0.18*ula_df.chime_flag* ula_df.soft_pull_flag) + 0.46*ula_df.chime_flag

    if leave_out!='Job time':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.21 * ula_df.job_time_flag

    if leave_out!='Existing DQ':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.11 * ula_df.existing_dq_flag

    if leave_out!='Employment type':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 1 + 0.1 * ula_df.seasonal_employment_flag

    if leave_out!='Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.06 * ula_df.kmx_auth_tradelines_flag

    if leave_out!='Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ula_df.soft_pull_flag,'loss_multiplier'] *= 1.1  * (0.99 + 0.11*ula_df.low_bureau_flag)  * (0.978 + 0.172*ula_df.open_tl_flag)
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ~ula_df.soft_pull_flag,'loss_multiplier'] *= (1 * (0.98 + 0.22*ula_df.low_bureau_flag)  * (0.945 + 0.405*ula_df.open_tl_flag ) /np.maximum(ula_df.cd_perc_flag*ula_df.open_tl_flag*1.2,1))

        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) &  ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.97  + 0.15  * ula_df.cd_perc_flag
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.954 + 0.346 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1)         &  ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0   + 0.05  * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1)         & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0   + 0.10  * ula_df.cd_perc_flag


    if leave_out!='blanket adjustment':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] /= 1.1


    if leave_out!='Clip':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] = np.clip(ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'], 0.75, 1.4)

    return ula_df


def get_ula_multiplier_kmx_diag(ula_df, loss_scale=None, leave_out='None', verbose=True):
    """Identical logic to get_ula_multiplier_kmx, but also returns step-by-step loss_multiplier means and flag means."""
    if loss_scale is None:
        loss_scale = MODEL_PARAMS['kmx_loss_scale']
    steps = {}
    def _record(label, df):
        steps[label] = df.loss_multiplier.mean()

    ula_df['loss_multiplier'] = 1.0
    _record('00_initial', ula_df)
    if verbose:
        print(f"00_initial  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low FICO':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_fico_flag & ~ula_df.high_model_score_flag) \
                                    + loss_scale * (ula_df.low_fico_flag & ula_df.high_model_score_flag)
    _record('02_low_fico_3.0', ula_df)
    if verbose:
        print(f"02_low_fico | flag mean: {ula_df.low_fico_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low Vantage':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_vantage_flag & ~ula_df.high_model_score_flag) \
                                    + loss_scale * (ula_df.low_vantage_flag & ula_df.high_model_score_flag)
    _record('03_low_vantage_3.0', ula_df)
    if verbose:
        print(f"03_low_vant | flag mean: {ula_df.low_vantage_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High PTI':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0 * ula_df.normal_pti_flag \
                                    + 0.05 * ula_df.high_pti_tier_1_flag \
                                    + 0.1 * ula_df.high_pti_tier_2_flag \
                                    + (1.4 * (1 + loss_scale) - 1) * ula_df.high_pti_tier_3_flag
    _record('04_high_pti_3.0', ula_df)
    if verbose:
        print(f"04_high_pti | tier1: {ula_df.high_pti_tier_1_flag.mean():.6f}  tier2: {ula_df.high_pti_tier_2_flag.mean():.6f}  tier3: {ula_df.high_pti_tier_3_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] /= (1 + loss_scale)
    _record('07_loss_scale_div_3.0', ula_df)
    if verbose:
        print(f"07_scale_dv | dividing by (1 + {loss_scale})  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + (-0.01 + 0.06 * ula_df.secured_credit_flag) \
                                        * ~(~ula_df.job_time_flag & ula_df.narrowed_soft_pull_flag & ula_df.secured_credit_flag)
    _record('08_secured_credit_3.0', ula_df)
    if verbose:
        print(f"08_sec_cred | flag mean: {ula_df.secured_credit_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 0.99 + 0.18 * ula_df.kmx_auth_tradelines_flag
    _record('09_auth_tradelines_3.0', ula_df)
    if verbose:
        print(f"09_auth_tl  | flag mean: {ula_df.kmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= (
            1 + ~ula_df.job_time_flag * (~ula_df.narrowed_soft_pull_flag * -0.025
            + ula_df.narrowed_soft_pull_flag * (~ula_df.secured_credit_flag * 0.108
            + ula_df.secured_credit_flag * 0.295)))
    _record('11_soft_pull_3.0', ula_df)
    if verbose:
        print(f"11_soft_pll | flag mean: {ula_df.soft_pull_flag.mean():.6f}  narrowed: {ula_df.narrowed_soft_pull_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Fraud':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + (ula_df.fraud_adjustment - 1)
    _record('12_fraud_all', ula_df)
    if verbose:
        print(f"12_fraud    | fraud_adj mean: {ula_df.fraud_adjustment.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        clipped_multiplier = np.clip(ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'], 0.8, 1.35 / (1 + loss_scale))
        ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'] = clipped_multiplier
    _record('13_clip_3.0', ula_df)
    if verbose:
        print(f"13_clip_3.0 | clip [0.8, {1.35 / (1 + loss_scale):.4f}]  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Vehicle Age':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 0.8593 + 0.0201 * ula_df.continuous_vehicle_age
    _record('14_vehicle_age_3.0', ula_df)
    if verbose:
        print(f"14_veh_age  | continuous_age mean: {ula_df.continuous_vehicle_age.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'npc':
        ula_df.loc[ula_df.kmx_npc_flag, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.high_pti_npc
    _record('15_npc_all', ula_df)
    if verbose:
        print(f"15_npc      | npc_flag mean: {ula_df.kmx_npc_flag.mean():.6f}  high_pti_npc mean: {ula_df.high_pti_npc.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Student Loans':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.96 + 0.14 * ula_df.student_loan_flag
    _record('16_student_loans_all', ula_df)
    if verbose:
        print(f"16_stu_loan | flag mean: {ula_df.student_loan_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'high sales price':
        ula_df.loc[ula_df.mtn_model.isin([4.1]), 'loss_multiplier'] *= 0.98 + 0.22 * ula_df.high_sales_price_flag
    _record('17_high_sales_price_4.1', ula_df)
    if verbose:
        print(f"17_hi_price | flag mean: {ula_df.high_sales_price_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Driver flag':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.15 * ula_df.driver_flag
    _record('18_driver_flag_all', ula_df)
    if verbose:
        print(f"18_driver   | flag mean: {ula_df.driver_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Louisiana':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.35 * ula_df.louisiana_flag
    _record('19_louisiana_all', ula_df)
    if verbose:
        print(f"19_louisiana| flag mean: {ula_df.louisiana_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'georgia':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.1 * ula_df.georgia_flag
    _record('20_georgia_all', ula_df)
    if verbose:
        print(f"20_georgia  | flag mean: {ula_df.georgia_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'txca':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score > 140), 'loss_multiplier'] *= 1 - 0.1 * ula_df.txca_flag
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score <= 140) & (ula_df.cd_model_score >= 135), 'loss_multiplier'] *= 1 - 0.05 * ula_df.txca_flag
    _record('21_txca_all', ula_df)
    if verbose:
        print(f"21_txca     | flag mean: {ula_df.txca_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'state_counter_adj':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score < 150) & ~(ula_df.louisiana_flag | ula_df.georgia_flag | ula_df.txca_flag), 'loss_multiplier'] *= 1.012
    _record('22_state_counter_all', ula_df)
    if verbose:
        no_state_adj = ((~ula_df.louisiana_flag) & (~ula_df.georgia_flag) & (~ula_df.txca_flag)).mean()
        print(f"22_st_cntr  | no state adj: {no_state_adj:.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.96 + (0.01 * ula_df.soft_pull_flag - 0.18 * ula_df.chime_flag * ula_df.soft_pull_flag) + 0.46 * ula_df.chime_flag
    _record('23_secured_credit_3.1+', ula_df)
    if verbose:
        print(f"23_sec_cr31 | chime mean: {ula_df.chime_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Job time':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.21 * ula_df.job_time_flag
    _record('24_job_time_3.1+', ula_df)
    if verbose:
        print(f"24_job_t_31 | flag mean: {ula_df.job_time_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Existing DQ':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.existing_dq_flag
    _record('25_existing_dq_3.1+', ula_df)
    if verbose:
        print(f"25_dq_31    | flag mean: {ula_df.existing_dq_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Employment type':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.1 * ula_df.seasonal_employment_flag
    _record('26_employment_3.1+', ula_df)
    if verbose:
        print(f"26_emp_31   | seasonal: {ula_df.seasonal_employment_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.06 * ula_df.kmx_auth_tradelines_flag
    _record('27_auth_tradelines_3.1+', ula_df)
    if verbose:
        print(f"27_auth_31  | flag mean: {ula_df.kmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.1 * (0.99 + 0.11 * ula_df.low_bureau_flag) * (0.978 + 0.172 * ula_df.open_tl_flag)
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= (1 * (0.98 + 0.22 * ula_df.low_bureau_flag) * (0.945 + 0.405 * ula_df.open_tl_flag) / np.maximum(ula_df.cd_perc_flag * ula_df.open_tl_flag * 1.2, 1))

        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.97 + 0.15 * ula_df.cd_perc_flag
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.954 + 0.346 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1) & ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0 + 0.05 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0 + 0.10 * ula_df.cd_perc_flag
    _record('28_soft_pull_3.1+', ula_df)
    if verbose:
        mtn31_mask = ula_df.mtn_model.isin([3.1, 3.2, 4.1])
        print(f"28_soft_31  | soft_pull: {ula_df.soft_pull_flag.mean():.6f}  low_bureau: {ula_df.low_bureau_flag.mean():.6f}  cd_perc: {ula_df.cd_perc_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'blanket adjustment':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] /= 1.1
    _record('28b_blanket_3.1+', ula_df)
    if verbose:
        print(f"28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] = np.clip(ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'], 0.75, 1.4)
    _record('29_final_clip_3.1+', ula_df)
    if verbose:
        print(f"29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")
        print("\n--- Per MTN Model Means ---")
        for model in [3.0, 3.1, 3.2, 4.1]:
            mean_val = ula_df.loc[ula_df.mtn_model == model, 'loss_multiplier'].mean()
            count_val = (ula_df.mtn_model == model).sum()
            print(f"mtn_model {model}: mean loss_multiplier = {mean_val:.6f}  (n={count_val})")

    n = len(ula_df)
    flags = {
        'job_time_flag': ula_df.job_time_flag.mean(),
        'low_fico_flag': ula_df.low_fico_flag.mean(),
        'high_model_score_flag': ula_df.high_model_score_flag.mean(),
        'low_vantage_flag': ula_df.low_vantage_flag.mean(),
        'normal_pti_flag': ula_df.normal_pti_flag.mean(),
        'high_pti_tier_1_flag': ula_df.high_pti_tier_1_flag.mean(),
        'high_pti_tier_2_flag': ula_df.high_pti_tier_2_flag.mean(),
        'high_pti_tier_3_flag': ula_df.high_pti_tier_3_flag.mean(),
        'existing_dq_flag': ula_df.existing_dq_flag.mean(),
        'seasonal_employment_flag': ula_df.seasonal_employment_flag.mean(),
        'secured_credit_flag': ula_df.secured_credit_flag.mean(),
        'kmx_auth_tradelines_flag': ula_df.kmx_auth_tradelines_flag.mean(),
        'null_fico_w_vantage_flag': ula_df.null_fico_w_vantage_flag.mean(),
        'null_fico_null_vantage_flag': ula_df.null_fico_null_vantage_flag.mean(),
        'soft_pull_flag': ula_df.soft_pull_flag.mean(),
        'narrowed_soft_pull_flag': ula_df.narrowed_soft_pull_flag.mean(),
        'fraud_adjustment_mean': ula_df.fraud_adjustment.mean(),
        'continuous_vehicle_age_mean': ula_df.continuous_vehicle_age.mean(),
        'kmx_npc_flag': ula_df.kmx_npc_flag.mean(),
        'high_pti_npc': ula_df.high_pti_npc.mean(),
        'student_loan_flag': ula_df.student_loan_flag.mean(),
        'high_sales_price_flag': ula_df.high_sales_price_flag.mean(),
        'driver_flag': ula_df.driver_flag.mean(),
        'louisiana_flag': ula_df.louisiana_flag.mean(),
        'georgia_flag': ula_df.georgia_flag.mean(),
        'txca_flag': ula_df.txca_flag.mean(),
        'chime_flag': ula_df.chime_flag.mean(),
        'low_bureau_flag': ula_df.low_bureau_flag.mean(),
        'cd_perc_flag': ula_df.cd_perc_flag.mean(),
        'open_tl_flag': ula_df.open_tl_flag.mean(),
        'mtn_3_1_flag': ula_df.mtn_3_1_flag.mean(),
        'mtn_model_3.0_pct': (ula_df.mtn_model == 3.0).mean(),
        'mtn_model_3.1_pct': (ula_df.mtn_model == 3.1).mean(),
        'mtn_model_3.2_pct': (ula_df.mtn_model == 3.2).mean(),
        'mtn_model_4.1_pct': (ula_df.mtn_model == 4.1).mean(),
    }

    return ula_df, pd.Series(steps), pd.Series(flags)

In [6]:
mean_unit_loss = MODEL_PARAMS['mean_unit_loss']
unit_loss_to_model_score = MODEL_PARAMS['unit_loss_to_model_score']


def get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config, leave_out='None'):
    """Core RAGU Score calculation for a single vintage and individual LOB."""
    baseline_ltv = baseline_config['ltv']
    new_baseline_recovery_unadjusted_pct = baseline_config['new_recovery_unadjusted']
    baseline_apr = baseline_config['apr']
    ltv_mult = 17 / 0.65 if lob == 'KMX' else 17
    apr_mult = 0.7 / 0.65 if lob == 'KMX' else 0.7

    ula_df = ula_df_total[(ula_df_total.vintage == vintage) & (ula_df_total.lob == lob)].copy()

    if len(ula_df) == 0:
        return None

    if lob == 'KMX':
        ula_df = get_ula_multiplier_kmx(ula_df, leave_out=leave_out)
    else:
        raise ValueError("This notebook only supports KMX")

    ula_df = ula_df[['account_number', date_col, 'bbvalue', 'sale_price', 'amt_financed', 'lob_or_bucket', 'lob', 'loss_multiplier', 'apr']]

    nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(subset='account_number', keep='first')
    mix_df = ula_df.merge(nr.rename(columns={'new_recovery_multiplier': 'recovery_multiplier'}),
                          on='account_number', how='left').drop_duplicates(subset='account_number', keep='first')

    mix_df['ltv'] = mix_df.amt_financed / mix_df.bbvalue

    bb_populated_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0)]
    if len(bb_populated_df) == 0:
        return None

    full_pop_metrics = bb_populated_df.groupby('lob').apply(
        weighted_average_and_sum,
        ['loss_multiplier', 'ltv', 'bbvalue', 'apr'],
        include_groups=False
    )

    recovery_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0) & mix_df['recovery_multiplier'].notna()]
    recovery_df = recovery_df.copy()
    recovery_df['recovery_unadjusted_multiplier'] = recovery_df['recovery_multiplier']
    recovery_metrics = recovery_df.groupby('lob').apply(
        weighted_average_and_sum,
        ['recovery_unadjusted_multiplier'],
        include_groups=False
    )
    recovery_metrics = recovery_metrics.drop(columns='amt_financed')

    grouped_mix_df = full_pop_metrics.join(recovery_metrics)

    vintage_ms_df = ms_df[ms_df['period'] == vintage].copy()

    index_name = grouped_mix_df.index.name
    if isinstance(index_name, str) and index_name in grouped_mix_df.columns:
        grouped_mix_df = grouped_mix_df.reset_index(drop=True)
    else:
        grouped_mix_df = grouped_mix_df.reset_index()

    full_df = grouped_mix_df.merge(vintage_ms_df, on='lob')

    if len(full_df) == 0:
        return None

    full_df['est_unit_loss'] = mean_unit_loss
    full_df['unit_loss_score'] = full_df.model_score + (1 - full_df.loss_multiplier) * full_df.est_unit_loss / unit_loss_to_model_score
    full_df = full_df.set_index('lob')

    full_df['ms_original'] = full_df.model_score.copy()
    full_df['baselined_unadjusted_recovery'] = (full_df.recovery_unadjusted_multiplier / new_baseline_recovery_unadjusted_pct).copy()

    full_df['gross_loss_impact'] = full_df['unit_loss_score'] - full_df['ms_original']
    full_df['recovery_impact'] = (full_df['unit_loss_score'] * full_df['est_unit_loss']
        * full_df['recovery_unadjusted_multiplier'] * (full_df['baselined_unadjusted_recovery'] - 1))
    full_df['ltv_impact'] = ((baseline_ltv / full_df['ltv']) - 1) * ltv_mult
    full_df['apr_impact'] = (baseline_apr - full_df['apr']) / 0.01 * apr_mult
    full_df['ragu_score'] = (
        (1 - full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier) * full_df.unit_loss_score
        + full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier
        * full_df.unit_loss_score * full_df.baselined_unadjusted_recovery
        + full_df['ltv_impact']
        + full_df['apr_impact'])

    full_df['vintage'] = vintage
    return full_df

In [7]:
# Filter out Core LOB
ula_df_total = ula_df_total[ula_df_total.lob != 'Core']

# Ensure date columns are proper types
ula_df_total['app_date'] = pd.to_datetime(ula_df_total['app_date'])
ula_df_total['book_date'] = pd.to_datetime(ula_df_total['book_date'])
new_recovery['app_date'] = pd.to_datetime(new_recovery['app_date'])
new_recovery['book_date'] = pd.to_datetime(new_recovery['book_date'])

# Assign period columns using pd.to_period
for df in [ula_df_total, new_recovery]:
    df['quarter'] = pd.to_datetime(df[date_col]).dt.to_period('Q')
    df['month'] = pd.to_datetime(df[date_col]).dt.to_period('M')
    df['week'] = pd.to_datetime(df[date_col]).dt.to_period('W-SAT')
    period_key = {'q': 'quarter', 'm': 'month', 'w': 'week'}
    df['period'] = df[period_key[granularity]]

# Filter to configured date range
for df in [ula_df_total, new_recovery]:
    mask = (df['period'] >= start_period) & (df['period'] <= end_period)
    df.drop(df[~mask].index, inplace=True)

# Convert week columns to str for compatibility
for df in [ula_df_total, new_recovery]:
    df['book_week'] = df['book_week'].astype(str)
    df['app_week'] = df['app_week'].astype(str)

# String version of date_col for flag comparisons
date_col_str = f'{date_col}_str'
ula_df_total[date_col_str] = ula_df_total[date_col].astype(str)

ula_df_total['mtn_3_1_flag'] = ula_df_total.mtn_model == 'MTN3.1'
ula_df_total['vehicle_age'] = np.maximum(ula_df_total[date_col_str].str[:4].astype(int) - ula_df_total.model_year, 1/365)
ula_df_total.tradein_value = ula_df_total.tradein_value.fillna(0)
ula_df_total.make = ula_df_total.make.str.upper().str[:3]
ula_df_total.lob_or_bucket = np.select([ula_df_total.lob_or_bucket.isna() & ula_df_total.lob.isin(['Core', 'FRN']),
                                      ula_df_total.lob_or_bucket.isna() & ~ula_df_total.lob.isin(['Core', 'FRN'])],
                                     ['D', 'C'], default=ula_df_total.lob_or_bucket)
ula_df_total['continuous_vehicle_age'] = (ula_df_total[date_col_str].str[:4].astype(int)
    + ula_df_total[date_col_str].str[5:7].astype(int) / 12
    - (ula_df_total.model_year - 0.25) - 1)

# Driver flag
warnings.filterwarnings('ignore', category=UserWarning)
ula_df_total.job_company = ula_df_total.job_company.fillna('not provided')
ula_df_total['driver_flag'] = np.where(
    ula_df_total.job_company.str.contains('(LYFT)|(UBER)|(GRUB ?HUB)|(DOOR ?DASH)|(GO ?PUFF)|(POST ?MATE)|(INSTA ?CART)|(DOMINO)|(PAPA J)|(PIZZA)|(JIMMY ?JOHN)|(SELF)'),
    1, 0)
warnings.filterwarnings('default', category=UserWarning)

# Handle NA values
ula_df_total = ula_df_total.dropna(subset=['sale_price', 'cd_model_score', 'pti', 'lob'])
ula_df_total.cash_down = ula_df_total.cash_down.fillna(0)
ula_df_total.specialty_dealer = ula_df_total.specialty_dealer.fillna('not specialty')
ula_df_total.prev_co_count = ula_df_total.prev_co_count.fillna(0)

# Weekly-matching filters
ula_df_total['bbltv'] = ula_df_total.amt_financed / ula_df_total.bbvalue.replace(0, np.nan)
ula_df_total = ula_df_total[ula_df_total.amt_financed <= 75000]
ula_df_total = ula_df_total[ula_df_total.pti <= 0.6]
ula_df_total = ula_df_total[
    (ula_df_total.lob == 'MCY') |
    (ula_df_total.bbltv <= 10.0) |
    (ula_df_total.bbvalue.isna()) |
    (ula_df_total.bbvalue == 0)
]
ula_df_total = ula_df_total[ula_df_total.total_income <= 200000]

# KMX Flags
ula_df_total['secured_credit_flag'] = ula_df_total.secured_credit_card
ula_df_total['chime_flag'] = ula_df_total.chime_indicator
ula_df_total['seasonal_employment_flag'] = ula_df_total['seasonal_employment_flag'] == 1
ula_df_total['waiter_employment_flag'] = ula_df_total['waiter_employment_flag'] == 1
ula_df_total['null_fico_w_vantage_flag'] = ((ula_df_total.fico_score < 300) | (ula_df_total.fico_score > 850)) & (ula_df_total.vantage_score >= 300) & (ula_df_total.vantage_score <= 850)
ula_df_total['null_fico_null_vantage_flag'] = ((ula_df_total.fico_score < 300) | (ula_df_total.fico_score > 850)) & ((ula_df_total.vantage_score < 300) | (ula_df_total.vantage_score > 850))
ula_df_total['student_loan_flag'] = np.where(ula_df_total.student_loan_flag == 1, 1, 0)
ula_df_total['high_sales_price_flag'] = ula_df_total.sale_price > 30000
ula_df_total['kmx_npc_flag'] = ula_df_total.kmx_npc_flag == 1
ula_df_total['high_pti_npc'] = ula_df_total.pti > 0.2
ula_df_total['job_time_flag'] = ula_df_total.employed_months < 6
ula_df_total['low_fico_flag'] = (ula_df_total.fico_score > 300) & (ula_df_total.fico_score < 450)
ula_df_total['high_model_score_flag'] = ula_df_total.cd_model_score >= 146
ula_df_total['low_vantage_flag'] = (ula_df_total.fico_score < 300) & (ula_df_total.vantage_score > 4) & (ula_df_total.vantage_score < 450)
ula_df_total['louisiana_flag'] = ula_df_total.state == 'LA'
ula_df_total['txca_flag'] = ula_df_total.state.isin(['TX', 'CA'])
ula_df_total['georgia_flag'] = ula_df_total.state == 'GA'
ula_df_total['normal_pti_flag'] = ula_df_total.pti <= 0.2
ula_df_total['high_pti_tier_1_flag'] = (ula_df_total.pti > 0.2) & (ula_df_total.pti <= 0.25)
ula_df_total['high_pti_tier_2_flag'] = (ula_df_total.pti > 0.25) & (ula_df_total.pti <= 0.35)
ula_df_total['high_pti_tier_3_flag'] = ula_df_total.pti > 0.35
ula_df_total['existing_dq_flag'] = ula_df_total.existing_dq_count > 0
ula_df_total['kmx_toyho_flag'] = (ula_df_total.cd_model_score >= 130) & ula_df_total.make.isin({'HON', 'TOY'})
ula_df_total['kmx_auth_tradelines_flag'] = ula_df_total.pct_auth_tradelines >= 0.14
ula_df_total['low_bureau_flag'] = ((ula_df_total.fico_score > 300) & (ula_df_total.fico_score < 475)) | ((ula_df_total.vantage_score > 4) & (ula_df_total.vantage_score < 475))
ula_df_total['soft_pull_flag'] = ula_df_total.pull_type.isin(['softpull', 'prequal'])
ula_df_total['cd_perc_flag'] = (ula_df_total.sale_price <= 18000) & (ula_df_total.cash_down / ula_df_total.sale_price <= 0.1)
ula_df_total['open_tl_flag'] = ula_df_total.open_tl == 0
ula_df_total['narrowed_soft_pull_flag'] = (ula_df_total.sale_price <= 18000) & (ula_df_total.cash_down / ula_df_total.sale_price <= 0.1) & ula_df_total.soft_pull_flag & (~ula_df_total.job_time_flag)
ula_df_total['prev_co_flag'] = ula_df_total.prev_co_count > 0

# Deduplicate driver flags
combined_driver_flag_df = ula_df_total.groupby('account_number').driver_flag.max().reset_index()
ula_df_total = ula_df_total.drop(columns='driver_flag').merge(combined_driver_flag_df, on='account_number')
ula_df_total = ula_df_total.drop(columns='job_company').drop_duplicates()

# Vintage assignment
ula_df_total['vintage'] = format_vintage(ula_df_total['period'])
new_recovery['vintage'] = format_vintage(new_recovery['period'])

# Filter to KMX only
ula_df_total = ula_df_total[ula_df_total.lob == 'KMX'].copy()
new_recovery = new_recovery[new_recovery.lob == 'KMX'].copy()

# MTN 4.1 model score transformation (applied in-place to ULA source)
is_mtn41 = ula_df_total.mtn_model == 4.1
ula_df_total.loc[is_mtn41, 'cd_model_score'] = (
    142 + (ula_df_total.loc[is_mtn41, 'cd_model_score'] - 142) * 1.5
)

# Aggregate model scores from ULA data (same source as ltv/apr)
ms_df = ula_df_total.groupby(['period', 'lob']).apply(
    weighted_average_and_sum, 'cd_model_score', include_groups=False
).reset_index()
ms_df = ms_df.rename(columns={'cd_model_score': 'model_score'})
ms_df['period'] = format_vintage(ms_df['period'])

print(f'Data loaded: {len(ula_df_total)} ULA rows')
print(f'MTN model distribution:\n{ula_df_total.mtn_model.value_counts().sort_index()}')
print(f'ms_df: {len(ms_df)} rows')
print(f'Available KMX vintages: {sorted(ula_df_total.vintage.unique())}')

Data loaded: 37104 ULA rows
MTN model distribution:
mtn_model
3.0      246
3.1    17510
3.2    15424
4.1     3924
Name: count, dtype: int64
ms_df: 25 rows
Available KMX vintages: ['2025-11-30/2025-12-06', '2025-12-07/2025-12-13', '2025-12-14/2025-12-20', '2025-12-21/2025-12-27', '2025-12-28/2026-01-03', '2026-01-04/2026-01-10', '2026-01-11/2026-01-17', '2026-01-18/2026-01-24', '2026-01-25/2026-01-31', '2026-02-01/2026-02-07', '2026-02-08/2026-02-14', '2026-02-15/2026-02-21', '2026-02-22/2026-02-28', '2026-03-01/2026-03-07', '2026-03-08/2026-03-14', '2026-03-15/2026-03-21', '2026-03-22/2026-03-28', '2026-03-29/2026-04-04', '2026-04-05/2026-04-11', '2026-04-12/2026-04-18', '2026-04-19/2026-04-25', '2026-04-26/2026-05-02', '2026-05-03/2026-05-09', '2026-05-10/2026-05-16', '2026-05-17/2026-05-23']

In [8]:
baseline_config = BASELINES['KMX']

results_by_model = {}

all_vintages = sorted(ula_df_total['vintage'].unique())

for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    print(f'\n{"="*60}')
    print(f'  Processing: {label}')
    print(f'{"="*60}')

    # Filter DataFrames by MTN model
    if mtn_model_filter == 'All KMX':
        ula_filtered = ula_df_total.copy()
        new_rec_filtered = new_recovery.copy()
        ms_filtered = ms_df.copy()
    else:
        mtn_accounts = set(ula_df_total[ula_df_total.mtn_model == mtn_model_filter].account_number)
        ula_filtered = ula_df_total[ula_df_total.mtn_model == mtn_model_filter].copy()
        new_rec_filtered = new_recovery[new_recovery.account_number.isin(mtn_accounts)].copy()
        ms_filtered = rebuild_ms_df(ula_filtered)

    n_loans = len(ula_filtered)
    if n_loans == 0:
        print(f'  No loans found for {label}, skipping.')
        results_by_model[mtn_model_filter] = pd.DataFrame()
        continue

    print(f'  Loans: {n_loans}')

    full_df_list = []
    vintages_processed = []

    for vintage in all_vintages:
        n_vintage = len(ula_filtered[ula_filtered.vintage == vintage])
        if n_vintage == 0:
            continue

        print(f'  {vintage} KMX ({label}, n={n_vintage})')
        full_df = get_ragu_score(vintage, 'KMX', ula_filtered, new_rec_filtered, ms_filtered, baseline_config)
        if full_df is not None:
            full_df_list.append(full_df)
            vintages_processed.append(vintage)

    if full_df_list:
        all_df = pd.concat(full_df_list)
        results_by_model[mtn_model_filter] = all_df
        print(f'\n  {label}: {len(vintages_processed)} vintages processed')
    else:
        results_by_model[mtn_model_filter] = pd.DataFrame()
        print(f'\n  {label}: No vintages had data')

print(f'\n{"="*60}')
print('  All models processed.')
print(f'{"="*60}')
print("[PROGRESS] Scoring Complete")

============================================================
  Processing: MTN 3.0
============================================================
  Loans: 246
  2025-11-30/2025-12-06 KMX (MTN 3.0, n=246)

  MTN 3.0: 1 vintages processed

============================================================
  Processing: MTN 3.1
============================================================
  Loans: 17510
  2025-11-30/2025-12-06 KMX (MTN 3.1, n=674)

  2025-12-07/2025-12-13 KMX (MTN 3.1, n=965)
  2025-12-14/2025-12-20 KMX (MTN 3.1, n=1141)
  2025-12-21/2025-12-27 KMX (MTN 3.1, n=790)
  2025-12-28/2026-01-03 KMX (MTN 3.1, n=1060)

  2026-01-04/2026-01-10 KMX (MTN 3.1, n=1124)
  2026-01-11/2026-01-17 KMX (MTN 3.1, n=1149)
  2026-01-18/2026-01-24 KMX (MTN 3.1, n=1125)
  2026-01-25/2026-01-31 KMX (MTN 3.1, n=909)

  2026-02-01/2026-02-07 KMX (MTN 3.1, n=1105)
  2026-02-08/2026-02-14 KMX (MTN 3.1, n=1134)
  2026-02-15/2026-02-21 KMX (MTN 3.1, n=987)
  2026-02-22/2026-02-28 KMX (MTN 3.1, n=1274)
  2026-03-01/2026-03-07 KMX (MTN 3.1, n=1002)

  2026-03-08/2026-03-14 KMX (MTN 3.1, n=917)
  2026-03-15/2026-03-21 KMX (MTN 3.1, n=746)
  2026-03-22/2026-03-28 KMX (MTN 3.1, n=692)
  2026-03-29/2026-04-04 KMX (MTN 3.1, n=629)
  2026-04-05/2026-04-11 KMX (MTN 3.1, n=87)

  MTN 3.1: 19 vintages processed

============================================================
  Processing: MTN 3.2
============================================================
  Loans: 15424
  2026-01-25/2026-01-31 KMX (MTN 3.2, n=83)
  2026-02-01/2026-02-07 KMX (MTN 3.2, n=133)
  2026-02-08/2026-02-14 KMX (MTN 3.2, n=134)
  2026-02-15/2026-02-21 KMX (MTN 3.2, n=847)

  2026-02-22/2026-02-28 KMX (MTN 3.2, n=1831)
  2026-03-01/2026-03-07 KMX (MTN 3.2, n=1330)
  2026-03-08/2026-03-14 KMX (MTN 3.2, n=1275)
  2026-03-15/2026-03-21 KMX (MTN 3.2, n=936)
  2026-03-22/2026-03-28 KMX (MTN 3.2, n=874)

  2026-03-29/2026-04-04 KMX (MTN 3.2, n=837)
  2026-04-05/2026-04-11 KMX (MTN 3.2, n=1080)
  2026-04-12/2026-04-18 KMX (MTN 3.2, n=1212)
  2026-04-19/2026-04-25 KMX (MTN 3.2, n=1258)
  2026-04-26/2026-05-02 KMX (MTN 3.2, n=1236)

  2026-05-03/2026-05-09 KMX (MTN 3.2, n=1220)
  2026-05-10/2026-05-16 KMX (MTN 3.2, n=932)
  2026-05-17/2026-05-23 KMX (MTN 3.2, n=206)

  MTN 3.2: 17 vintages processed

============================================================
  Processing: MTN 4.1
============================================================
  Loans: 3924
  2025-12-14/2025-12-20 KMX (MTN 4.1, n=74)

  2025-12-21/2025-12-27 KMX (MTN 4.1, n=125)
  2025-12-28/2026-01-03 KMX (MTN 4.1, n=142)
  2026-01-04/2026-01-10 KMX (MTN 4.1, n=167)
  2026-01-11/2026-01-17 KMX (MTN 4.1, n=171)
  2026-01-18/2026-01-24 KMX (MTN 4.1, n=154)

  2026-01-25/2026-01-31 KMX (MTN 4.1, n=140)
  2026-02-01/2026-02-07 KMX (MTN 4.1, n=160)
  2026-02-08/2026-02-14 KMX (MTN 4.1, n=159)
  2026-02-15/2026-02-21 KMX (MTN 4.1, n=204)

  2026-02-22/2026-02-28 KMX (MTN 4.1, n=305)
  2026-03-01/2026-03-07 KMX (MTN 4.1, n=267)
  2026-03-08/2026-03-14 KMX (MTN 4.1, n=251)
  2026-03-15/2026-03-21 KMX (MTN 4.1, n=194)

  2026-03-22/2026-03-28 KMX (MTN 4.1, n=206)
  2026-03-29/2026-04-04 KMX (MTN 4.1, n=178)
  2026-04-05/2026-04-11 KMX (MTN 4.1, n=151)
  2026-04-12/2026-04-18 KMX (MTN 4.1, n=155)
  2026-04-19/2026-04-25 KMX (MTN 4.1, n=155)

  2026-04-26/2026-05-02 KMX (MTN 4.1, n=151)
  2026-05-03/2026-05-09 KMX (MTN 4.1, n=136)
  2026-05-10/2026-05-16 KMX (MTN 4.1, n=210)
  2026-05-17/2026-05-23 KMX (MTN 4.1, n=69)

  MTN 4.1: 23 vintages processed

============================================================
  Processing: All KMX
============================================================
  Loans: 37104
  2025-11-30/2025-12-06 KMX (All KMX, n=920)

  2025-12-07/2025-12-13 KMX (All KMX, n=965)
  2025-12-14/2025-12-20 KMX (All KMX, n=1215)
  2025-12-21/2025-12-27 KMX (All KMX, n=915)
  2025-12-28/2026-01-03 KMX (All KMX, n=1202)

  2026-01-04/2026-01-10 KMX (All KMX, n=1291)
  2026-01-11/2026-01-17 KMX (All KMX, n=1320)
  2026-01-18/2026-01-24 KMX (All KMX, n=1279)
  2026-01-25/2026-01-31 KMX (All KMX, n=1132)

  2026-02-01/2026-02-07 KMX (All KMX, n=1398)
  2026-02-08/2026-02-14 KMX (All KMX, n=1427)
  2026-02-15/2026-02-21 KMX (All KMX, n=2038)
  2026-02-22/2026-02-28 KMX (All KMX, n=3410)

  2026-03-01/2026-03-07 KMX (All KMX, n=2599)
  2026-03-08/2026-03-14 KMX (All KMX, n=2443)
  2026-03-15/2026-03-21 KMX (All KMX, n=1876)
  2026-03-22/2026-03-28 KMX (All KMX, n=1772)

  2026-03-29/2026-04-04 KMX (All KMX, n=1644)
  2026-04-05/2026-04-11 KMX (All KMX, n=1318)
  2026-04-12/2026-04-18 KMX (All KMX, n=1367)
  2026-04-19/2026-04-25 KMX (All KMX, n=1413)

  2026-04-26/2026-05-02 KMX (All KMX, n=1387)
  2026-05-03/2026-05-09 KMX (All KMX, n=1356)
  2026-05-10/2026-05-16 KMX (All KMX, n=1142)
  2026-05-17/2026-05-23 KMX (All KMX, n=275)

  All KMX: 25 vintages processed

============================================================
  All models processed.
============================================================
[PROGRESS] Scoring Complete

In [9]:
"""
Diagnostics: Run get_ula_multiplier_kmx_diag for each MTN model and for All KMX combined.
Produces step-by-step loss_multiplier traces and flag means per vintage.
"""

def build_output_df(results, wtd_mults, record_counts, ragu_gli_dict=None):
    """Helper to build multiplier steps and summary DataFrame."""
    if not results:
        return None
    step_names = list(next(iter(results.values())).keys())
    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        col_data[col_name] = [step_dict.get(s) for s in step_names]
    diag_df = pd.DataFrame(col_data, index=step_names)
    summary = {}
    for (lob, vintage) in results.keys():
        col = f"{lob} | {vintage}"
        final_mult_mean = diag_df[col].iloc[-1]
        wtd_mult = wtd_mults.get((lob, vintage), float('nan'))
        if ragu_gli_dict is not None:
            gross_loss_impact = ragu_gli_dict.get((lob, vintage), 25 * (1 - wtd_mult))
        else:
            gross_loss_impact = 25 * (1 - wtd_mult)
        summary[col] = {
            '--- FINAL_MULT (mean)': final_mult_mean,
            '--- WTD_MULT_RAGU': wtd_mult,
            '--- GROSS_LOSS_IMPACT': gross_loss_impact,
            '--- N_RECORDS': record_counts.get((lob, vintage), 0),
        }
    summary_df = pd.DataFrame(summary)
    return pd.concat([diag_df, summary_df])

def build_flags_df(flag_results, record_counts):
    """Helper to build flag means DataFrame."""
    if not flag_results:
        return None
    flag_names = list(next(iter(flag_results.values())).keys())
    flag_col_data = {}
    for (lob, vintage), flag_dict in flag_results.items():
        col_name = f"{lob} | {vintage}"
        flag_col_data[col_name] = [flag_dict.get(f) for f in flag_names]
    flags_df = pd.DataFrame(flag_col_data, index=flag_names)
    n_row = {}
    for (lob, vintage) in flag_results.keys():
        n_row[f"{lob} | {vintage}"] = record_counts.get((lob, vintage), 0)
    flags_df.loc['--- N_RECORDS'] = n_row
    return flags_df


STEP_LABEL_MAP = {
    '00_initial':              'Initial (1.0)',
    '02_low_fico_3.0':         'Low FICO (3.0)',
    '03_low_vantage_3.0':      'Low Vantage (3.0)',
    '04_high_pti_3.0':         'High PTI (3.0)',
    '07_loss_scale_div_3.0':   'Loss Scale Div (3.0)',
    '08_secured_credit_3.0':   'Secured Credit (3.0)',
    '09_auth_tradelines_3.0':  'Auth Tradelines (3.0)',
    '11_soft_pull_3.0':        'Soft Pull (3.0)',
    '12_fraud_all':            'Fraud Adjustment',
    '13_clip_3.0':             'Clip (3.0)',
    '14_vehicle_age_3.0':      'Vehicle Age (3.0)',
    '15_npc_all':              'NPC',
    '16_student_loans_all':    'Student Loans',
    '17_high_sales_price_4.1': 'High Sales Price (4.1)',
    '18_driver_flag_all':      'Driver Flag',
    '19_louisiana_all':        'Louisiana',
    '20_georgia_all':          'Georgia',
    '21_txca_all':             'TX / CA',
    '22_state_counter_all':    'State Counter',
    '23_secured_credit_3.1+':  'Secured Credit / Chime (3.1+)',
    '24_job_time_3.1+':        'Job Time (3.1+)',
    '25_existing_dq_3.1+':     'Existing DQ (3.1+)',
    '26_employment_3.1+':      'Employment Type (3.1+)',
    '27_auth_tradelines_3.1+': 'Auth Tradelines (3.1+)',
    '28_soft_pull_3.1+':       'Soft Pull (3.1+)',
    '28b_blanket_3.1+':        'Blanket Adjustment (3.1+)',
    '29_final_clip_3.1+':      'Clip (3.1+)',
}


def build_attribution_df(results, ragu_gli_dict):
    """
    Decompose gross_loss_impact across multiplier steps using logarithmic attribution.

    For each vintage:
      1. Compute per-step ratios: r_i = step_i / step_{i-1}
      2. Log shares: ln(r_i) / ln(final_multiplier)  [proportional contribution]
      3. Attributed impact: share_i * gross_loss_impact

    gross_loss_impact is sourced from get_ragu_score output (results_by_model) to ensure
    the attribution decomposes the same value that appears in the RAGU score decomposition.

    When the final multiplier equals 1.0 (no net adjustment), all impacts are 0.
    """
    if not results:
        return None

    step_keys = list(next(iter(results.values())).keys())
    adjustment_keys = [k for k in step_keys if k != '00_initial']
    readable_labels = [STEP_LABEL_MAP.get(k, k) for k in adjustment_keys]

    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        gross_loss_impact = ragu_gli_dict.get((lob, vintage), float('nan'))

        cumulative = [step_dict.get(k, float('nan')) for k in step_keys]
        ratios = []
        for i, k in enumerate(step_keys):
            if k == '00_initial':
                continue
            prev = cumulative[i - 1]
            curr = cumulative[i]
            if prev and prev != 0:
                ratios.append(curr / prev)
            else:
                ratios.append(1.0)

        import math
        final_mult = cumulative[-1]
        log_final = math.log(final_mult) if final_mult and final_mult > 0 and abs(final_mult - 1.0) > 1e-12 else None

        if log_final is None or pd.isna(gross_loss_impact):
            col_data[col_name] = [0.0] * len(adjustment_keys) + [gross_loss_impact if not pd.isna(gross_loss_impact) else 0.0]
        else:
            log_ratios = [math.log(r) if r and r > 0 else 0.0 for r in ratios]
            attributed = [(lr / log_final) * gross_loss_impact for lr in log_ratios]
            col_data[col_name] = attributed + [sum(attributed)]

    index_labels = readable_labels + ['--- TOTAL (check)']
    return pd.DataFrame(col_data, index=index_labels)

diag_results_by_model = {}

for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    
    if mtn_model_filter == 'All KMX':
        ula_diag_source = ula_df_total.copy()
    else:
        ula_diag_source = ula_df_total[ula_df_total.mtn_model == mtn_model_filter].copy()
    
    if len(ula_diag_source) == 0:
        print(f'\n{label}: No data for diagnostics, skipping.')
        diag_results_by_model[mtn_model_filter] = (None, None, None)
        continue
    
    # Build ragu_gli_dict from results_by_model for this MTN model
    ragu_gli_dict = {}
    model_df = results_by_model.get(mtn_model_filter)
    if model_df is not None and len(model_df) > 0:
        for _, row in model_df.reset_index().iterrows():
            ragu_gli_dict[('KMX', row['vintage'])] = row['gross_loss_impact']
    
    # Get the most recent vintages for diagnostics
    target_vintages = sorted(ula_diag_source.vintage.unique())[-6:]
    
    kmx_results = {}
    kmx_flag_results = {}
    kmx_wtd_mults = {}
    kmx_record_counts = {}
    
    print(f'\n{"="*60}')
    print(f'  DIAGNOSTICS: {label}')
    print(f'{"="*60}')
    
    for vintage in target_vintages:
        ula_vintage = ula_diag_source[ula_diag_source.vintage == vintage].copy()
        n = len(ula_vintage)
        if n == 0:
            continue
        
        print(f'\n{"="*60}')
        print(f'  KMX {vintage} ({label})  (n={n})')
        print(f'{"="*60}')
        
        ula_vintage_diag, steps, flags = get_ula_multiplier_kmx_diag(ula_vintage, loss_scale=MODEL_PARAMS['kmx_loss_scale'], leave_out='None', verbose=True)
        
        diag_mix = ula_vintage_diag[['account_number', 'bbvalue', 'amt_financed', 'loss_multiplier']].copy()
        nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(
            subset='account_number', keep='first')
        diag_mix = diag_mix.merge(nr, on='account_number', how='left').drop_duplicates(
            subset='account_number', keep='first')
        bb_pop = diag_mix[diag_mix['bbvalue'].notna() & (diag_mix['bbvalue'] > 0)]
        if len(bb_pop) > 0 and bb_pop.amt_financed.sum() > 0:
            wtd_mult = (bb_pop.loss_multiplier * bb_pop.amt_financed).sum() / bb_pop.amt_financed.sum()
        else:
            wtd_mult = float('nan')
        
        ragu_gli = ragu_gli_dict.get(('KMX', vintage), float('nan'))
        print(f"  bb_populated: {len(bb_pop)} / {n}  wtd_mult: {wtd_mult:.6f}  ragu_gli: {ragu_gli:.4f}")
        
        kmx_results[('KMX', vintage)] = steps.to_dict()
        kmx_flag_results[('KMX', vintage)] = flags.to_dict()
        kmx_wtd_mults[('KMX', vintage)] = wtd_mult
        kmx_record_counts[('KMX', vintage)] = n
    
    kmx_output_df = build_output_df(kmx_results, kmx_wtd_mults, kmx_record_counts, ragu_gli_dict)
    kmx_flags_df = build_flags_df(kmx_flag_results, kmx_record_counts)
    kmx_attribution_df = build_attribution_df(kmx_results, ragu_gli_dict)
    diag_results_by_model[mtn_model_filter] = (kmx_output_df, kmx_flags_df, kmx_attribution_df)

    if kmx_output_df is not None:
        print(f'\n--- {label} Multiplier Steps ---')
        display(kmx_output_df)
        print(f'\n--- {label} Flag Means ---')
        display(kmx_flags_df)
    if kmx_attribution_df is not None:
        print(f'\n--- {label} Gross Loss Attribution ---')
        display(kmx_attribution_df)

============================================================
  DIAGNOSTICS: MTN 3.0
============================================================

============================================================
  KMX 2025-11-30/2025-12-06 (MTN 3.0)  (n=246)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.012195  | loss_multiplier mean: 1.002305
04_high_pti | tier1: 0.109756  tier2: 0.036585  tier3: 0.000000  | loss_multiplier mean: 1.011451
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.947939
08_sec_cred | flag mean: 0.382114  | loss_multiplier mean: 0.958046
09_auth_tl  | flag mean: 0.036585  | loss_multiplier mean: 0.954776
11_soft_pll | flag mean: 0.849593  narrowed: 0.142276  | loss_multiplier mean: 0.932097
12_fraud    | fraud_adj mean: 1.009024  | loss_multiplier mean: 0.940293
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.938785
14_veh_age  | continuous_age mean: 5.513550  | loss_multiplier mean: 0.910912
15_npc      | npc_flag mean: 0.247967  high_pti_npc mean: 0.146341  | loss_multiplier mean: 0.912195
16_stu_loan | flag mean: 0.243902  | loss_multiplier mean: 0.906374
17_hi_price | flag mean: 0.093496  | loss_multiplier mean: 0.906374
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.906374
19_louisiana| flag mean: 0.012195  | loss_multiplier mean: 0.910499
20_georgia  | flag mean: 0.097561  | loss_multiplier mean: 0.919343
21_txca     | flag mean: 0.378049  | loss_multiplier mean: 0.898811
22_st_cntr  | no state adj: 0.512195  | loss_multiplier mean: 0.903753
23_sec_cr31 | chime mean: 0.195122  | loss_multiplier mean: 0.929668
24_job_t_31 | flag mean: 0.178862  | loss_multiplier mean: 0.956992
25_dq_31    | flag mean: 0.117886  | loss_multiplier mean: 0.959114
26_emp_31   | seasonal: 0.012195  | loss_multiplier mean: 0.960241
27_auth_31  | flag mean: 0.036585  | loss_multiplier mean: 0.960241
28_soft_31  | soft_pull: 0.849593  low_bureau: 0.044715  cd_perc: 0.195122  | loss_multiplier mean: 0.960241
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.960241
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.960241

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.960241  (n=246)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 246 / 246  wtd_mult: 0.945309  ragu_gli: 1.3673

--- MTN 3.0 Multiplier Steps ---

                         KMX | 2025-11-30/2025-12-06
00_initial                                  1.000000
02_low_fico_3.0                             1.000000
03_low_vantage_3.0                          1.002305
04_high_pti_3.0                             1.011451
07_loss_scale_div_3.0                       0.947939
08_secured_credit_3.0                       0.958046
09_auth_tradelines_3.0                      0.954776
11_soft_pull_3.0                            0.932097
12_fraud_all                                0.940293
13_clip_3.0                                 0.938785
14_vehicle_age_3.0                          0.910912
15_npc_all                                  0.912195
16_student_loans_all                        0.906374
17_high_sales_price_4.1                     0.906374
18_driver_flag_all                          0.906374
19_louisiana_all                            0.910499
20_georgia_all                              0.919343
21_txca_all                                 0.898811
22_state_counter_all                        0.903753
23_secured_credit_3.1+                      0.929668
24_job_time_3.1+                            0.956992
25_existing_dq_3.1+                         0.959114
26_employment_3.1+                          0.960241
27_auth_tradelines_3.1+                     0.960241
28_soft_pull_3.1+                           0.960241
28b_blanket_3.1+                            0.960241
29_final_clip_3.1+                          0.960241
--- FINAL_MULT (mean)                       0.960241
--- WTD_MULT_RAGU                           0.945309
--- GROSS_LOSS_IMPACT                       1.367279
--- N_RECORDS                             246.000000

--- MTN 3.0 Flag Means ---

                             KMX | 2025-11-30/2025-12-06
job_time_flag                                   0.178862
low_fico_flag                                   0.000000
high_model_score_flag                           0.227642
low_vantage_flag                                0.012195
normal_pti_flag                                 0.853659
high_pti_tier_1_flag                            0.109756
high_pti_tier_2_flag                            0.036585
high_pti_tier_3_flag                            0.000000
existing_dq_flag                                0.117886
seasonal_employment_flag                        0.012195
secured_credit_flag                             0.382114
kmx_auth_tradelines_flag                        0.036585
null_fico_w_vantage_flag                        0.922764
null_fico_null_vantage_flag                     0.056911
soft_pull_flag                                  0.849593
narrowed_soft_pull_flag                         0.142276
fraud_adjustment_mean                           1.009024
continuous_vehicle_age_mean                     5.513550
kmx_npc_flag                                    0.247967
high_pti_npc                                    0.146341
student_loan_flag                               0.243902
high_sales_price_flag                           0.093496
driver_flag                                     0.000000
louisiana_flag                                  0.012195
georgia_flag                                    0.097561
txca_flag                                       0.378049
chime_flag                                      0.195122
low_bureau_flag                                 0.044715
cd_perc_flag                                    0.195122
open_tl_flag                                    0.158537
mtn_3_1_flag                                    0.000000
mtn_model_3.0_pct                               1.000000
mtn_model_3.1_pct                               0.000000
mtn_model_3.2_pct                               0.000000
mtn_model_4.1_pct                               0.000000
--- N_RECORDS                                 246.000000

--- MTN 3.0 Gross Loss Attribution ---

                               KMX | 2025-11-30/2025-12-06
Low FICO (3.0)                                   -0.000000
Low Vantage (3.0)                                -0.077587
High PTI (3.0)                                   -0.306137
Loss Scale Div (3.0)                              2.185539
Secured Credit (3.0)                             -0.357410
Auth Tradelines (3.0)                             0.115216
Soft Pull (3.0)                                   0.810189
Fraud Adjustment                                 -0.295044
Clip (3.0)                                        0.054075
Vehicle Age (3.0)                                 1.015756
NPC                                              -0.047436
Student Loans                                     0.215751
High Sales Price (4.1)                           -0.000000
Driver Flag                                      -0.000000
Louisiana                                        -0.153014
Georgia                                          -0.325786
TX / CA                                           0.761178
State Counter                                    -0.184797
Secured Credit / Chime (3.1+)                    -0.952745
Job Time (3.1+)                                  -0.976243
Existing DQ (3.1+)                               -0.074648
Employment Type (3.1+)                           -0.039575
Auth Tradelines (3.1+)                           -0.000000
Soft Pull (3.1+)                                 -0.000000
Blanket Adjustment (3.1+)                        -0.000000
Clip (3.1+)                                      -0.000000
--- TOTAL (check)                                 1.367279

============================================================
  DIAGNOSTICS: MTN 3.1
============================================================

============================================================
  KMX 2026-03-01/2026-03-07 (MTN 3.1)  (n=1002)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.010978  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066866  tier2: 0.028942  tier3: 0.000998  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.500000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.034930  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.878244  narrowed: 0.087824  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.999810  | loss_multiplier mean: 0.999810
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.999810
14_veh_age  | continuous_age mean: 4.516966  | loss_multiplier mean: 0.999810
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.096806  | loss_multiplier mean: 0.999810
16_stu_loan | flag mean: 0.239521  | loss_multiplier mean: 0.993039
17_hi_price | flag mean: 0.119760  | loss_multiplier mean: 0.993039
18_driver   | flag mean: 0.000998  | loss_multiplier mean: 0.993183
19_louisiana| flag mean: 0.010978  | loss_multiplier mean: 0.996988
20_georgia  | flag mean: 0.093812  | loss_multiplier mean: 1.006434
21_txca     | flag mean: 0.325349  | loss_multiplier mean: 0.983091
22_st_cntr  | no state adj: 0.569860  | loss_multiplier mean: 0.988811
23_sec_cr31 | chime mean: 0.324351  | loss_multiplier mean: 1.053004
24_job_t_31 | flag mean: 0.124750  | loss_multiplier mean: 1.070157
25_dq_31    | flag mean: 0.127745  | loss_multiplier mean: 1.073940
26_emp_31   | seasonal: 0.004990  | loss_multiplier mean: 1.074420
27_auth_31  | flag mean: 0.034930  | loss_multiplier mean: 1.065866
28_soft_31  | soft_pull: 0.878244  low_bureau: 0.047904  cd_perc: 0.110778  | loss_multiplier mean: 1.129063
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.026421
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.022087

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.022087  (n=1002)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 995 / 1002  wtd_mult: 1.005675  ragu_gli: -0.1419

============================================================
  KMX 2026-03-08/2026-03-14 (MTN 3.1)  (n=917)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.013086  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066521  tier2: 0.026172  tier3: 0.002181  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.504907  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.039258  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.845147  narrowed: 0.073064  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.998561  | loss_multiplier mean: 0.998561
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.998561
14_veh_age  | continuous_age mean: 4.590513  | loss_multiplier mean: 0.998561
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.094875  | loss_multiplier mean: 0.998561
16_stu_loan | flag mean: 0.238822  | loss_multiplier mean: 0.991655
17_hi_price | flag mean: 0.114504  | loss_multiplier mean: 0.991655
18_driver   | flag mean: 0.001091  | loss_multiplier mean: 0.991798
19_louisiana| flag mean: 0.005453  | loss_multiplier mean: 0.993683
20_georgia  | flag mean: 0.085060  | loss_multiplier mean: 1.002154
21_txca     | flag mean: 0.296619  | loss_multiplier mean: 0.982034
22_st_cntr  | no state adj: 0.612868  | loss_multiplier mean: 0.988347
23_sec_cr31 | chime mean: 0.291167  | loss_multiplier mean: 1.044902
24_job_t_31 | flag mean: 0.099237  | loss_multiplier mean: 1.056533
25_dq_31    | flag mean: 0.128680  | loss_multiplier mean: 1.060420
26_emp_31   | seasonal: 0.008724  | loss_multiplier mean: 1.061289
27_auth_31  | flag mean: 0.039258  | loss_multiplier mean: 1.052996
28_soft_31  | soft_pull: 0.845147  low_bureau: 0.037077  cd_perc: 0.093784  | loss_multiplier mean: 1.110139
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.009217
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.005928

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.005928  (n=917)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 912 / 917  wtd_mult: 0.993537  ragu_gli: 0.1616

============================================================
  KMX 2026-03-15/2026-03-21 (MTN 3.1)  (n=746)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.029491  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.058981  tier2: 0.024129  tier3: 0.005362  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.489276  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.037534  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.865952  narrowed: 0.092493  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.989933  | loss_multiplier mean: 0.989933
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.989933
14_veh_age  | continuous_age mean: 4.554960  | loss_multiplier mean: 0.989933

15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.088472  | loss_multiplier mean: 0.989933
16_stu_loan | flag mean: 0.253351  | loss_multiplier mean: 0.985112
17_hi_price | flag mean: 0.148794  | loss_multiplier mean: 0.985112
18_driver   | flag mean: 0.001340  | loss_multiplier mean: 0.985305
19_louisiana| flag mean: 0.006702  | loss_multiplier mean: 0.987542
20_georgia  | flag mean: 0.061662  | loss_multiplier mean: 0.993687
21_txca     | flag mean: 0.340483  | loss_multiplier mean: 0.968633
22_st_cntr  | no state adj: 0.591153  | loss_multiplier mean: 0.974588
23_sec_cr31 | chime mean: 0.290885  | loss_multiplier mean: 1.027950
24_job_t_31 | flag mean: 0.112601  | loss_multiplier mean: 1.042186
25_dq_31    | flag mean: 0.139410  | loss_multiplier mean: 1.047019
26_emp_31   | seasonal: 0.009383  | loss_multiplier mean: 1.047966
27_auth_31  | flag mean: 0.037534  | loss_multiplier mean: 1.039659
28_soft_31  | soft_pull: 0.865952  low_bureau: 0.056300  cd_perc: 0.116622  | loss_multiplier mean: 1.098953
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.999049
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.996724

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.996724  (n=746)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 743 / 746  wtd_mult: 0.983356  ragu_gli: 0.4161

============================================================
  KMX 2026-03-22/2026-03-28 (MTN 3.1)  (n=692)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.014451  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.059249  tier2: 0.037572  tier3: 0.004335  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.505780  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.044798  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.856936  narrowed: 0.086705  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000130  | loss_multiplier mean: 1.000130
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000130
14_veh_age  | continuous_age mean: 4.471098  | loss_multiplier mean: 1.000130
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.101156  | loss_multiplier mean: 1.000130
16_stu_loan | flag mean: 0.250000  | loss_multiplier mean: 0.994797
17_hi_price | flag mean: 0.158960  | loss_multiplier mean: 0.994797
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.994797
19_louisiana| flag mean: 0.004335  | loss_multiplier mean: 0.996395
20_georgia  | flag mean: 0.080925  | loss_multiplier mean: 1.004449
21_txca     | flag mean: 0.306358  | loss_multiplier mean: 0.981401
22_st_cntr  | no state adj: 0.608382  | loss_multiplier mean: 0.987510
23_sec_cr31 | chime mean: 0.322254  | loss_multiplier mean: 1.050947
24_job_t_31 | flag mean: 0.102601  | loss_multiplier mean: 1.062395
25_dq_31    | flag mean: 0.109827  | loss_multiplier mean: 1.064200
26_emp_31   | seasonal: 0.010116  | loss_multiplier mean: 1.065286
27_auth_31  | flag mean: 0.044798  | loss_multiplier mean: 1.057376
28_soft_31  | soft_pull: 0.856936  low_bureau: 0.043353  cd_perc: 0.109827  | loss_multiplier mean: 1.111762
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.010693
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.010333

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.010333  (n=692)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)

  bb_populated: 691 / 692  wtd_mult: 0.993587  ragu_gli: 0.1603

============================================================
  KMX 2026-03-29/2026-04-04 (MTN 3.1)  (n=629)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.028617  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.073132  tier2: 0.025437  tier3: 0.003180  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.453100  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.038156  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.863275  narrowed: 0.090620  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.006693  | loss_multiplier mean: 1.006693
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.006693
14_veh_age  | continuous_age mean: 4.517753  | loss_multiplier mean: 1.006693
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.101749  | loss_multiplier mean: 1.006693
16_stu_loan | flag mean: 0.219396  | loss_multiplier mean: 0.996903
17_hi_price | flag mean: 0.178060  | loss_multiplier mean: 0.996903
18_driver   | flag mean: 0.003180  | loss_multiplier mean: 0.997425
19_louisiana| flag mean: 0.015898  | loss_multiplier mean: 1.003226
20_georgia  | flag mean: 0.077901  | loss_multiplier mean: 1.011063
21_txca     | flag mean: 0.298887  | loss_multiplier mean: 0.987831
22_st_cntr  | no state adj: 0.607313  | loss_multiplier mean: 0.994033
23_sec_cr31 | chime mean: 0.255962  | loss_multiplier mean: 1.040941
24_job_t_31 | flag mean: 0.111288  | loss_multiplier mean: 1.055988
25_dq_31    | flag mean: 0.109698  | loss_multiplier mean: 1.057898
26_emp_31   | seasonal: 0.007949  | loss_multiplier mean: 1.058806
27_auth_31  | flag mean: 0.038156  | loss_multiplier mean: 1.050554
28_soft_31  | soft_pull: 0.863275  low_bureau: 0.050874  cd_perc: 0.116057  | loss_multiplier mean: 1.116814
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.015285
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.008656

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.008656  (n=629)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 624 / 629  wtd_mult: 0.991171  ragu_gli: 0.2207

============================================================
  KMX 2026-04-05/2026-04-11 (MTN 3.1)  (n=87)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.011494  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.080460  tier2: 0.022989  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.436782  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.045977  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.172414  narrowed: 0.022989  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.041724  | loss_multiplier mean: 1.041724
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.041724
14_veh_age  | continuous_age mean: 4.985632  | loss_multiplier mean: 1.041724
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.103448  | loss_multiplier mean: 1.041724
16_stu_loan | flag mean: 0.252874  | loss_multiplier mean: 1.035168
17_hi_price | flag mean: 0.137931  | loss_multiplier mean: 1.035168
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.035168
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 1.035168
20_georgia  | flag mean: 0.057471  | loss_multiplier mean: 1.041155
21_txca     | flag mean: 0.356322  | loss_multiplier mean: 1.014747
22_st_cntr  | no state adj: 0.586207  | loss_multiplier mean: 1.021749
23_sec_cr31 | chime mean: 0.252874  | loss_multiplier mean: 1.096995
24_job_t_31 | flag mean: 0.068966  | loss_multiplier mean: 1.102360
25_dq_31    | flag mean: 0.126437  | loss_multiplier mean: 1.106066
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 1.106066
27_auth_31  | flag mean: 0.045977  | loss_multiplier mean: 1.098234
28_soft_31  | soft_pull: 0.172414  low_bureau: 0.034483  cd_perc: 0.126437  | loss_multiplier mean: 1.058099
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.961909
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.951947

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.951947  (n=87)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 87 / 87  wtd_mult: 0.916490  ragu_gli: 2.0877

--- MTN 3.1 Multiplier Steps ---

,KMX | 2026-03-01/2026-03-07,KMX | 2026-03-08/2026-03-14,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.999810,0.998561,0.989933,1.000130,1.006693,1.041724
13_clip_3.0,0.999810,0.998561,0.989933,1.000130,1.006693,1.041724
14_vehicle_age_3.0,0.999810,0.998561,0.989933,1.000130,1.006693,1.041724
15_npc_all,0.999810,0.998561,0.989933,1.000130,1.006693,1.041724
16_student_loans_all,0.993039,0.991655,0.985112,0.994797,0.996903,1.035168
17_high_sales_price_4.1,0.993039,0.991655,0.985112,0.994797,0.996903,1.035168
18_driver_flag_all,0.993183,0.991798,0.985305,0.994797,0.997425,1.035168
19_louisiana_all,0.996988,0.993683,0.987542,0.996395,1.003226,1.035168
20_georgia_all,1.006434,1.002154,0.993687,1.004449,1.011063,1.041155
21_txca_all,0.983091,0.982034,0.968633,0.981401,0.987831,1.014747
22_state_counter_all,0.988811,0.988347,0.974588,0.987510,0.994033,1.021749
23_secured_credit_3.1+,1.053004,1.044902,1.027950,1.050947,1.040941,1.096995
24_job_time_3.1+,1.070157,1.056533,1.042186,1.062395,1.055988,1.102360
25_existing_dq_3.1+,1.073940,1.060420,1.047019,1.064200,1.057898,1.106066
26_employment_3.1+,1.074420,1.061289,1.047966,1.065286,1.058806,1.106066
27_auth_tradelines_3.1+,1.065866,1.052996,1.039659,1.057376,1.050554,1.098234
28_soft_pull_3.1+,1.129063,1.110139,1.098953,1.111762,1.116814,1.058099
28b_blanket_3.1+,1.026421,1.009217,0.999049,1.010693,1.015285,0.961909
29_final_clip_3.1+,1.022087,1.005928,0.996724,1.010333,1.008656,0.951947
--- FINAL_MULT (mean),1.022087,1.005928,0.996724,1.010333,1.008656,0.951947
--- WTD_MULT_RAGU,1.005675,0.993537,0.983356,0.993587,0.991171,0.916490
--- GROSS_LOSS_IMPACT,-0.141882,0.161576,0.416094,0.160319,0.220725,2.087740
--- N_RECORDS,1002.000000,917.000000,746.000000,692.000000,629.000000,87.000000

--- MTN 3.1 Flag Means ---

,KMX | 2026-03-01/2026-03-07,KMX | 2026-03-08/2026-03-14,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11
job_time_flag,0.124750,0.099237,0.112601,0.102601,0.111288,0.068966
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.295409,0.300981,0.290885,0.315029,0.333863,0.379310
low_vantage_flag,0.010978,0.013086,0.029491,0.014451,0.028617,0.011494
normal_pti_flag,0.903194,0.905125,0.911528,0.898844,0.898251,0.896552
high_pti_tier_1_flag,0.066866,0.066521,0.058981,0.059249,0.073132,0.080460
high_pti_tier_2_flag,0.028942,0.026172,0.024129,0.037572,0.025437,0.022989
high_pti_tier_3_flag,0.000998,0.002181,0.005362,0.004335,0.003180,0.000000
existing_dq_flag,0.127745,0.128680,0.139410,0.109827,0.109698,0.126437
seasonal_employment_flag,0.004990,0.008724,0.009383,0.010116,0.007949,0.000000
secured_credit_flag,0.500000,0.504907,0.489276,0.505780,0.453100,0.436782
kmx_auth_tradelines_flag,0.034930,0.039258,0.037534,0.044798,0.038156,0.045977
null_fico_w_vantage_flag,0.960080,0.943293,0.966488,0.971098,0.961844,0.977011
null_fico_null_vantage_flag,0.020958,0.029444,0.033512,0.026012,0.038156,0.022989
soft_pull_flag,0.878244,0.845147,0.865952,0.856936,0.863275,0.172414
narrowed_soft_pull_flag,0.087824,0.073064,0.092493,0.086705,0.090620,0.022989
fraud_adjustment_mean,0.999810,0.998561,0.989933,1.000130,1.006693,1.041724
continuous_vehicle_age_mean,4.516966,4.590513,4.554960,4.471098,4.517753,4.985632
kmx_npc_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_pti_npc,0.096806,0.094875,0.088472,0.101156,0.101749,0.103448
student_loan_flag,0.239521,0.238822,0.253351,0.250000,0.219396,0.252874
high_sales_price_flag,0.119760,0.114504,0.148794,0.158960,0.178060,0.137931
driver_flag,0.000998,0.001091,0.001340,0.000000,0.003180,0.000000
louisiana_flag,0.010978,0.005453,0.006702,0.004335,0.015898,0.000000
georgia_flag,0.093812,0.085060,0.061662,0.080925,0.077901,0.057471
txca_flag,0.325349,0.296619,0.340483,0.306358,0.298887,0.356322
chime_flag,0.324351,0.291167,0.290885,0.322254,0.255962,0.252874
low_bureau_flag,0.047904,0.037077,0.056300,0.043353,0.050874,0.034483
cd_perc_flag,0.110778,0.093784,0.116622,0.109827,0.116057,0.126437
open_tl_flag,0.102794,0.117775,0.091153,0.075145,0.128776,0.057471
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
--- N_RECORDS,1002.000000,917.000000,746.000000,692.000000,629.000000,87.000000

--- MTN 3.1 Gross Loss Attribution ---

,KMX | 2026-03-01/2026-03-07,KMX | 2026-03-08/2026-03-14,KMX | 2026-03-15/2026-03-21,KMX | 2026-03-22/2026-03-28,KMX | 2026-03-29/2026-04-04,KMX | 2026-04-05/2026-04-11
Low FICO (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Low Vantage (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
High PTI (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Loss Scale Div (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Secured Credit (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Auth Tradelines (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Soft Pull (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Fraud Adjustment,0.001232,-0.039378,1.282843,0.002028,0.170841,-1.732936
Clip (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Vehicle Age (3.0),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
NPC,-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Student Loans,0.044132,-0.189708,0.618922,-0.083381,-0.250287,0.267658
High Sales Price (4.1),-0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000
Driver Flag,-0.000940,0.003939,-0.024841,0.000000,0.013406,-0.000000
Louisiana,-0.024834,0.051920,-0.287479,0.025036,0.148524,-0.000000
Georgia,-0.061240,0.232049,-0.786530,0.125539,0.199279,-0.244487
TX / CA,0.152401,-0.554401,3.237726,-0.362011,-0.595331,1.089135
State Counter,-0.037676,0.175164,-0.777032,0.096784,0.160297,-0.291507
Secured Credit / Chime (3.1+),-0.408492,1.521106,-6.758670,0.970963,1.180883,-3.012451
Job Time (3.1+),-0.104939,0.302626,-1.743806,0.168965,0.367546,-0.206819
Existing DQ (3.1+),-0.022917,0.100377,-0.586603,0.026462,0.046268,-0.142292
Employment Type (3.1+),-0.002907,0.022401,-0.114709,0.015914,0.021986,-0.000000
Auth Tradelines (3.1+),0.051915,-0.214449,1.008995,-0.116237,-0.200384,0.301277
Soft Pull (3.1+),-0.374084,1.444608,-7.032276,0.782195,1.566371,1.578267
Blanket Adjustment (3.1+),0.618986,-2.605438,12.084157,-1.486389,-2.440902,4.040555
Clip (3.1+),0.027482,-0.089239,0.295399,-0.005549,-0.167774,0.441340
--- TOTAL (check),-0.141882,0.161576,0.416094,0.160319,0.220725,2.087740

============================================================
  DIAGNOSTICS: MTN 3.2
============================================================

============================================================
  KMX 2026-04-12/2026-04-18 (MTN 3.2)  (n=1212)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.012376  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066007  tier2: 0.027228  tier3: 0.001650  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.452970  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.039604  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.652640  narrowed: 0.090759  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.012855  | loss_multiplier mean: 1.012855
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.012855
14_veh_age  | continuous_age mean: 4.747525  | loss_multiplier mean: 1.012855
15_npc      | npc_flag mean: 0.574257  high_pti_npc mean: 0.094884  | loss_multiplier mean: 1.013540
16_stu_loan | flag mean: 0.212871  | loss_multiplier mean: 1.002526
17_hi_price | flag mean: 0.187294  | loss_multiplier mean: 1.002526
18_driver   | flag mean: 0.000825  | loss_multiplier mean: 1.002645
19_louisiana| flag mean: 0.004950  | loss_multiplier mean: 1.004384
20_georgia  | flag mean: 0.079208  | loss_multiplier mean: 1.012436
21_txca     | flag mean: 0.314356  | loss_multiplier mean: 0.988186
22_st_cntr  | no state adj: 0.601485  | loss_multiplier mean: 0.994357
23_sec_cr31 | chime mean: 0.254125  | loss_multiplier mean: 1.047056
24_job_t_31 | flag mean: 0.092409  | loss_multiplier mean: 1.057894
25_dq_31    | flag mean: 0.132013  | loss_multiplier mean: 1.061830
26_emp_31   | seasonal: 0.006601  | loss_multiplier mean: 1.062553
27_auth_31  | flag mean: 0.039604  | loss_multiplier mean: 1.054399
28_soft_31  | soft_pull: 0.652640  low_bureau: 0.039604  cd_perc: 0.132838  | loss_multiplier mean: 1.091034
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.991849
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.990168

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.990168  (n=1212)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 1209 / 1212  wtd_mult: 0.966953  ragu_gli: 0.8262

============================================================
  KMX 2026-04-19/2026-04-25 (MTN 3.2)  (n=1258)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.009539  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.076312  tier2: 0.032591  tier3: 0.000795  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.439587  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.045310  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.769475  narrowed: 0.094595  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.011582  | loss_multiplier mean: 1.011582
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.011582
14_veh_age  | continuous_age mean: 4.863143  | loss_multiplier mean: 1.011582

15_npc      | npc_flag mean: 0.592210  high_pti_npc mean: 0.109698  | loss_multiplier mean: 1.012960
16_stu_loan | flag mean: 0.205087  | loss_multiplier mean: 1.000995
17_hi_price | flag mean: 0.175676  | loss_multiplier mean: 1.000995
18_driver   | flag mean: 0.001590  | loss_multiplier mean: 1.001241
19_louisiana| flag mean: 0.000795  | loss_multiplier mean: 1.001505
20_georgia  | flag mean: 0.092210  | loss_multiplier mean: 1.010842
21_txca     | flag mean: 0.321940  | loss_multiplier mean: 0.985544
22_st_cntr  | no state adj: 0.585056  | loss_multiplier mean: 0.991511
23_sec_cr31 | chime mean: 0.252782  | loss_multiplier mean: 1.038255
24_job_t_31 | flag mean: 0.101749  | loss_multiplier mean: 1.049890
25_dq_31    | flag mean: 0.120032  | loss_multiplier mean: 1.052881
26_emp_31   | seasonal: 0.010334  | loss_multiplier mean: 1.053971
27_auth_31  | flag mean: 0.045310  | loss_multiplier mean: 1.046195
28_soft_31  | soft_pull: 0.769475  low_bureau: 0.028617  cd_perc: 0.143879  | loss_multiplier mean: 1.100648
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.000589
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.996852

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.996852  (n=1258)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 1249 / 1258  wtd_mult: 0.978115  ragu_gli: 0.5471

============================================================
  KMX 2026-04-26/2026-05-02 (MTN 3.2)  (n=1236)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.008900  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.061489  tier2: 0.033172  tier3: 0.001618  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.429612  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.043689  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.811489  narrowed: 0.103560  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.024911  | loss_multiplier mean: 1.024911
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.024911
14_veh_age  | continuous_age mean: 4.853492  | loss_multiplier mean: 1.024911
15_npc      | npc_flag mean: 0.567961  high_pti_npc mean: 0.096278  | loss_multiplier mean: 1.024593
16_stu_loan | flag mean: 0.211165  | loss_multiplier mean: 1.012925
17_hi_price | flag mean: 0.210356  | loss_multiplier mean: 1.012925
18_driver   | flag mean: 0.001618  | loss_multiplier mean: 1.013200
19_louisiana| flag mean: 0.004854  | loss_multiplier mean: 1.015106
20_georgia  | flag mean: 0.078479  | loss_multiplier mean: 1.023157
21_txca     | flag mean: 0.329288  | loss_multiplier mean: 0.997742
22_st_cntr  | no state adj: 0.587379  | loss_multiplier mean: 1.003805
23_sec_cr31 | chime mean: 0.236246  | loss_multiplier mean: 1.046813
24_job_t_31 | flag mean: 0.113269  | loss_multiplier mean: 1.061596
25_dq_31    | flag mean: 0.120550  | loss_multiplier mean: 1.064303
26_emp_31   | seasonal: 0.008900  | loss_multiplier mean: 1.065292
27_auth_31  | flag mean: 0.043689  | loss_multiplier mean: 1.057509
28_soft_31  | soft_pull: 0.811489  low_bureau: 0.029126  cd_perc: 0.131068  | loss_multiplier mean: 1.111896
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.010814
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.000716

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.000716  (n=1236)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 1229 / 1236  wtd_mult: 0.978114  ragu_gli: 0.5472

============================================================
  KMX 2026-05-03/2026-05-09 (MTN 3.2)  (n=1220)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.014754  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.080328  tier2: 0.031967  tier3: 0.002459  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.418033  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.032787  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.864754  narrowed: 0.094262  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.019221  | loss_multiplier mean: 1.019221
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.019221
14_veh_age  | continuous_age mean: 4.813388  | loss_multiplier mean: 1.019221
15_npc      | npc_flag mean: 0.557377  high_pti_npc mean: 0.114754  | loss_multiplier mean: 1.019855
16_stu_loan | flag mean: 0.208197  | loss_multiplier mean: 1.008129
17_hi_price | flag mean: 0.177869  | loss_multiplier mean: 1.008129
18_driver   | flag mean: 0.001639  | loss_multiplier mean: 1.008426
19_louisiana| flag mean: 0.000820  | loss_multiplier mean: 1.008701
20_georgia  | flag mean: 0.069672  | loss_multiplier mean: 1.015766
21_txca     | flag mean: 0.322131  | loss_multiplier mean: 0.991464
22_st_cntr  | no state adj: 0.607377  | loss_multiplier mean: 0.997696
23_sec_cr31 | chime mean: 0.250820  | loss_multiplier mean: 1.040671
24_job_t_31 | flag mean: 0.109836  | loss_multiplier mean: 1.054765
25_dq_31    | flag mean: 0.117213  | loss_multiplier mean: 1.056735
26_emp_31   | seasonal: 0.008197  | loss_multiplier mean: 1.057588
27_auth_31  | flag mean: 0.032787  | loss_multiplier mean: 1.049196
28_soft_31  | soft_pull: 0.864754  low_bureau: 0.028689  cd_perc: 0.113115  | loss_multiplier mean: 1.109877
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.008979
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.003204

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.003204  (n=1220)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 1212 / 1220  wtd_mult: 0.983043  ragu_gli: 0.4239

============================================================
  KMX 2026-05-10/2026-05-16 (MTN 3.2)  (n=932)
============================================================
00_initial  | loss_multiplier mean: 1.000000

02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000

03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.070815  tier2: 0.038627  tier3: 0.001073  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.083691  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.006438  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.836910  narrowed: 0.097639  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.814735  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.651288  high_pti_npc mean: 0.110515  | loss_multiplier mean: 1.002339
16_stu_loan | flag mean: 0.042918  | loss_multiplier mean: 0.968236
17_hi_price | flag mean: 0.172747  | loss_multiplier mean: 0.968236
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.968236
19_louisiana| flag mean: 0.001073  | loss_multiplier mean: 0.968593
20_georgia  | flag mean: 0.068670  | loss_multiplier mean: 0.975248
21_txca     | flag mean: 0.345494  | loss_multiplier mean: 0.949220
22_st_cntr  | no state adj: 0.584764  | loss_multiplier mean: 0.954979
23_sec_cr31 | chime mean: 0.055794  | loss_multiplier mean: 0.941013
24_job_t_31 | flag mean: 0.103004  | loss_multiplier mean: 0.952113
25_dq_31    | flag mean: 0.021459  | loss_multiplier mean: 0.945043
26_emp_31   | seasonal: 0.001073  | loss_multiplier mean: 0.945140
27_auth_31  | flag mean: 0.006438  | loss_multiplier mean: 0.936065
28_soft_31  | soft_pull: 0.836910  low_bureau: 0.003219  cd_perc: 0.129828  | loss_multiplier mean: 0.971470
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.883155
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.887811

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.887811  (n=932)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 902 / 932  wtd_mult: 0.879403  ragu_gli: 3.0149

============================================================
  KMX 2026-05-17/2026-05-23 (MTN 3.2)  (n=206)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.063107  tier2: 0.043689  tier3: 0.004854  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.000000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.825243  narrowed: 0.106796  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.530744  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.616505  high_pti_npc mean: 0.111650  | loss_multiplier mean: 1.001845
16_stu_loan | flag mean: 0.000000  | loss_multiplier mean: 0.961771
17_hi_price | flag mean: 0.223301  | loss_multiplier mean: 0.961771
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.961771
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 0.961771
20_georgia  | flag mean: 0.072816  | loss_multiplier mean: 0.968812
21_txca     | flag mean: 0.344660  | loss_multiplier mean: 0.944978
22_st_cntr  | no state adj: 0.582524  | loss_multiplier mean: 0.950424
23_sec_cr31 | chime mean: 0.000000  | loss_multiplier mean: 0.920238
24_job_t_31 | flag mean: 0.097087  | loss_multiplier mean: 0.930135
25_dq_31    | flag mean: 0.000000  | loss_multiplier mean: 0.920834
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.920834
27_auth_31  | flag mean: 0.000000  | loss_multiplier mean: 0.911625

28_soft_31  | soft_pull: 0.825243  low_bureau: 0.000000  cd_perc: 0.135922  | loss_multiplier mean: 0.940464
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.854968
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.860215

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.860215  (n=206)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 111 / 206  wtd_mult: 0.852559  ragu_gli: 3.6860

--- MTN 3.2 Multiplier Steps ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,1.012855,1.011582,1.024911,1.019221,1.000000,1.000000
13_clip_3.0,1.012855,1.011582,1.024911,1.019221,1.000000,1.000000
14_vehicle_age_3.0,1.012855,1.011582,1.024911,1.019221,1.000000,1.000000
15_npc_all,1.013540,1.012960,1.024593,1.019855,1.002339,1.001845
16_student_loans_all,1.002526,1.000995,1.012925,1.008129,0.968236,0.961771
17_high_sales_price_4.1,1.002526,1.000995,1.012925,1.008129,0.968236,0.961771
18_driver_flag_all,1.002645,1.001241,1.013200,1.008426,0.968236,0.961771
19_louisiana_all,1.004384,1.001505,1.015106,1.008701,0.968593,0.961771
20_georgia_all,1.012436,1.010842,1.023157,1.015766,0.975248,0.968812
21_txca_all,0.988186,0.985544,0.997742,0.991464,0.949220,0.944978
22_state_counter_all,0.994357,0.991511,1.003805,0.997696,0.954979,0.950424
23_secured_credit_3.1+,1.047056,1.038255,1.046813,1.040671,0.941013,0.920238
24_job_time_3.1+,1.057894,1.049890,1.061596,1.054765,0.952113,0.930135
25_existing_dq_3.1+,1.061830,1.052881,1.064303,1.056735,0.945043,0.920834
26_employment_3.1+,1.062553,1.053971,1.065292,1.057588,0.945140,0.920834
27_auth_tradelines_3.1+,1.054399,1.046195,1.057509,1.049196,0.936065,0.911625
28_soft_pull_3.1+,1.091034,1.100648,1.111896,1.109877,0.971470,0.940464
28b_blanket_3.1+,0.991849,1.000589,1.010814,1.008979,0.883155,0.854968
29_final_clip_3.1+,0.990168,0.996852,1.000716,1.003204,0.887811,0.860215
--- FINAL_MULT (mean),0.990168,0.996852,1.000716,1.003204,0.887811,0.860215
--- WTD_MULT_RAGU,0.966953,0.978115,0.978114,0.983043,0.879403,0.852559
--- GROSS_LOSS_IMPACT,0.826183,0.547130,0.547153,0.423929,3.014931,3.686029
--- N_RECORDS,1212.000000,1258.000000,1236.000000,1220.000000,932.000000,206.000000

--- MTN 3.2 Flag Means ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
job_time_flag,0.092409,0.101749,0.113269,0.109836,0.103004,0.097087
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.320132,0.325914,0.320388,0.313934,0.322961,0.325243
low_vantage_flag,0.012376,0.009539,0.008900,0.014754,0.000000,0.000000
normal_pti_flag,0.905116,0.890302,0.903722,0.885246,0.889485,0.888350
high_pti_tier_1_flag,0.066007,0.076312,0.061489,0.080328,0.070815,0.063107
high_pti_tier_2_flag,0.027228,0.032591,0.033172,0.031967,0.038627,0.043689
high_pti_tier_3_flag,0.001650,0.000795,0.001618,0.002459,0.001073,0.004854
existing_dq_flag,0.132013,0.120032,0.120550,0.117213,0.021459,0.000000
seasonal_employment_flag,0.006601,0.010334,0.008900,0.008197,0.001073,0.000000
secured_credit_flag,0.452970,0.439587,0.429612,0.418033,0.083691,0.000000
kmx_auth_tradelines_flag,0.039604,0.045310,0.043689,0.032787,0.006438,0.000000
null_fico_w_vantage_flag,0.977723,0.970588,0.961974,0.910656,0.156652,0.000000
null_fico_null_vantage_flag,0.021452,0.029412,0.038026,0.089344,0.843348,1.000000
soft_pull_flag,0.652640,0.769475,0.811489,0.864754,0.836910,0.825243
narrowed_soft_pull_flag,0.090759,0.094595,0.103560,0.094262,0.097639,0.106796
fraud_adjustment_mean,1.012855,1.011582,1.024911,1.019221,1.000000,1.000000
continuous_vehicle_age_mean,4.747525,4.863143,4.853492,4.813388,4.814735,4.530744
kmx_npc_flag,0.574257,0.592210,0.567961,0.557377,0.651288,0.616505
high_pti_npc,0.094884,0.109698,0.096278,0.114754,0.110515,0.111650
student_loan_flag,0.212871,0.205087,0.211165,0.208197,0.042918,0.000000
high_sales_price_flag,0.187294,0.175676,0.210356,0.177869,0.172747,0.223301
driver_flag,0.000825,0.001590,0.001618,0.001639,0.000000,0.000000
louisiana_flag,0.004950,0.000795,0.004854,0.000820,0.001073,0.000000
georgia_flag,0.079208,0.092210,0.078479,0.069672,0.068670,0.072816
txca_flag,0.314356,0.321940,0.329288,0.322131,0.345494,0.344660
chime_flag,0.254125,0.252782,0.236246,0.250820,0.055794,0.000000
low_bureau_flag,0.039604,0.028617,0.029126,0.028689,0.003219,0.000000
cd_perc_flag,0.132838,0.143879,0.131068,0.113115,0.129828,0.135922
open_tl_flag,0.094059,0.100159,0.092233,0.100000,0.017167,0.000000
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
--- N_RECORDS,1212.000000,1258.000000,1236.000000,1220.000000,932.000000,206.000000

--- MTN 3.2 Gross Loss Attribution ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
Low FICO (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
High PTI (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Loss Scale Div (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Secured Credit (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Auth Tradelines (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Soft Pull (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Fraud Adjustment,-1.068060,-1.998215,18.821774,2.522920,-0.000000,-0.000000
Clip (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Vehicle Age (3.0),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
NPC,-0.056525,-0.236163,-0.237525,0.082310,-0.059194,-0.045116
Student Loans,0.913611,2.061736,-8.760567,-1.532345,0.877036,0.999325
High Sales Price (4.1),-0.000000,-0.000000,0.000000,0.000000,-0.000000,-0.000000
Driver Flag,-0.009909,-0.042575,0.207273,0.038968,-0.000000,-0.000000
Louisiana,-0.144905,-0.045821,1.437550,0.036186,-0.009338,-0.000000
Georgia,-0.667701,-1.610296,6.042894,0.924941,-0.173478,-0.178577
TX / CA,2.027228,4.398183,-19.240342,-3.208913,0.685361,0.609787
State Counter,-0.520546,-1.047555,4.633823,0.830225,-0.153236,-0.140669
Secured Credit / Chime (3.1+),-4.318224,-7.993772,32.091251,5.588512,0.373252,0.790102
Job Time (3.1+),-0.861111,-1.933676,10.726834,1.782605,-0.297119,-0.261872
Existing DQ (3.1+),-0.310541,-0.493749,1.947480,0.247262,0.188862,0.246033
Employment Type (3.1+),-0.056864,-0.179501,0.710843,0.106855,-0.002603,-0.000000
Auth Tradelines (3.1+),0.644182,1.285025,-5.609184,-1.055716,0.244452,0.246033
Soft Pull (3.1+),-2.856054,-8.804619,38.361690,7.450667,-0.940636,-0.762421
Blanket Adjustment (3.1+),7.969784,16.538861,-72.905896,-12.629917,2.414814,2.333199
Clip (3.1+),0.141819,0.649269,-7.680744,-0.760630,-0.133242,-0.149795
--- TOTAL (check),0.826183,0.547130,0.547153,0.423929,3.014931,3.686029

============================================================
  DIAGNOSTICS: MTN 4.1
============================================================

============================================================
  KMX 2026-04-12/2026-04-18 (MTN 4.1)  (n=155)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.012903  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.070968  tier2: 0.032258  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.393548  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.012903  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.651613  narrowed: 0.090323  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.008065  | loss_multiplier mean: 1.008065
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.008065
14_veh_age  | continuous_age mean: 4.512366  | loss_multiplier mean: 1.008065
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.103226  | loss_multiplier mean: 1.009474
16_stu_loan | flag mean: 0.277419  | loss_multiplier mean: 1.007692
17_hi_price | flag mean: 0.129032  | loss_multiplier mean: 1.014511
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.014511
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 1.014511
20_georgia  | flag mean: 0.122581  | loss_multiplier mean: 1.027187
21_txca     | flag mean: 0.341935  | loss_multiplier mean: 0.999628
22_st_cntr  | no state adj: 0.535484  | loss_multiplier mean: 1.004987
23_sec_cr31 | chime mean: 0.225806  | loss_multiplier mean: 1.047835
24_job_t_31 | flag mean: 0.070968  | loss_multiplier mean: 1.052004
25_dq_31    | flag mean: 0.180645  | loss_multiplier mean: 1.061188
26_emp_31   | seasonal: 0.019355  | loss_multiplier mean: 1.063182
27_auth_31  | flag mean: 0.012903  | loss_multiplier mean: 1.053635
28_soft_31  | soft_pull: 0.651613  low_bureau: 0.025806  cd_perc: 0.141935  | loss_multiplier mean: 1.112628
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.011480
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.010780

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.010780  (n=155)
  bb_populated: 153 / 155  wtd_mult: 1.007169  ragu_gli: -0.1792

============================================================
  KMX 2026-04-19/2026-04-25 (MTN 4.1)  (n=155)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.019355  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.051613  tier2: 0.038710  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.412903  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.045161  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.767742  narrowed: 0.135484  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.014323  | loss_multiplier mean: 1.014323
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.014323
14_veh_age  | continuous_age mean: 4.609140  | loss_multiplier mean: 1.014323
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.090323  | loss_multiplier mean: 1.015059
16_stu_loan | flag mean: 0.277419  | loss_multiplier mean: 1.013267
17_hi_price | flag mean: 0.129032  | loss_multiplier mean: 1.020540
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.020540
19_louisiana| flag mean: 0.006452  | loss_multiplier mean: 1.022950
20_georgia  | flag mean: 0.058065  | loss_multiplier mean: 1.028734
21_txca     | flag mean: 0.270968  | loss_multiplier mean: 1.006798
22_st_cntr  | no state adj: 0.664516  | loss_multiplier mean: 1.013137
23_sec_cr31 | chime mean: 0.219355  | loss_multiplier mean: 1.047417
24_job_t_31 | flag mean: 0.051613  | loss_multiplier mean: 1.048237
25_dq_31    | flag mean: 0.161290  | loss_multiplier mean: 1.055872
26_emp_31   | seasonal: 0.006452  | loss_multiplier mean: 1.056450
27_auth_31  | flag mean: 0.045161  | loss_multiplier mean: 1.048768
28_soft_31  | soft_pull: 0.767742  low_bureau: 0.045161  cd_perc: 0.154839  | loss_multiplier mean: 1.134912
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.031738
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.027365

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.027365  (n=155)
  bb_populated: 153 / 155  wtd_mult: 1.023261  ragu_gli: -0.5815

============================================================
  KMX 2026-04-26/2026-05-02 (MTN 4.1)  (n=151)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.006623  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.052980  tier2: 0.046358  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.417219  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.033113  | loss_multiplier mean: 1.000000

11_soft_pll | flag mean: 0.874172  narrowed: 0.105960  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.005563  | loss_multiplier mean: 1.005563

13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.005563
14_veh_age  | continuous_age mean: 4.711369  | loss_multiplier mean: 1.005563
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.099338  | loss_multiplier mean: 1.006777
16_stu_loan | flag mean: 0.324503  | loss_multiplier mean: 1.011515
17_hi_price | flag mean: 0.172185  | loss_multiplier mean: 1.028279
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.028279
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 1.028279
20_georgia  | flag mean: 0.072848  | loss_multiplier mean: 1.036253
21_txca     | flag mean: 0.291391  | loss_multiplier mean: 1.009501
22_st_cntr  | no state adj: 0.635762  | loss_multiplier mean: 1.014971
23_sec_cr31 | chime mean: 0.271523  | loss_multiplier mean: 1.066461
24_job_t_31 | flag mean: 0.119205  | loss_multiplier mean: 1.083342
25_dq_31    | flag mean: 0.198675  | loss_multiplier mean: 1.095864
26_emp_31   | seasonal: 0.006623  | loss_multiplier mean: 1.096451
27_auth_31  | flag mean: 0.033113  | loss_multiplier mean: 1.087539
28_soft_31  | soft_pull: 0.874172  low_bureau: 0.039735  cd_perc: 0.139073  | loss_multiplier mean: 1.167469
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.061336
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.051007

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.051007  (n=151)
  bb_populated: 151 / 151  wtd_mult: 1.053072  ragu_gli: -1.3268

============================================================
  KMX 2026-05-03/2026-05-09 (MTN 4.1)  (n=136)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.007353  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.088235  tier2: 0.014706  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.338235  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.029412  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.830882  narrowed: 0.102941  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.001029  | loss_multiplier mean: 1.001029
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.001029
14_veh_age  | continuous_age mean: 4.468137  | loss_multiplier mean: 1.001029
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.102941  | loss_multiplier mean: 1.002270
16_stu_loan | flag mean: 0.183824  | loss_multiplier mean: 0.988110
17_hi_price | flag mean: 0.183824  | loss_multiplier mean: 1.008361
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 1.008361
19_louisiana| flag mean: 0.007353  | loss_multiplier mean: 1.010758
20_georgia  | flag mean: 0.044118  | loss_multiplier mean: 1.015045
21_txca     | flag mean: 0.279412  | loss_multiplier mean: 0.991066
22_st_cntr  | no state adj: 0.669118  | loss_multiplier mean: 0.997035
23_sec_cr31 | chime mean: 0.213235  | loss_multiplier mean: 1.027172
24_job_t_31 | flag mean: 0.080882  | loss_multiplier mean: 1.034443

25_dq_31    | flag mean: 0.176471  | loss_multiplier mean: 1.043432

26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 1.043432
27_auth_31  | flag mean: 0.029412  | loss_multiplier mean: 1.034779
28_soft_31  | soft_pull: 0.830882  low_bureau: 0.036765  cd_perc: 0.132353  | loss_multiplier mean: 1.100172
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.000156
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.001258

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.001258  (n=136)
  bb_populated: 136 / 136  wtd_mult: 1.014923  ragu_gli: -0.3731

============================================================
  KMX 2026-05-10/2026-05-16 (MTN 4.1)  (n=210)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.047619  tier2: 0.038095  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.066667  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.019048  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.828571  narrowed: 0.090476  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000

13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.142857  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.519048  high_pti_npc mean: 0.085714  | loss_multiplier mean: 0.999000
16_stu_loan | flag mean: 0.066667  | loss_multiplier mean: 0.968327
17_hi_price | flag mean: 0.161905  | loss_multiplier mean: 0.983977
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.983977
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 0.983977
20_georgia  | flag mean: 0.057143  | loss_multiplier mean: 0.989646
21_txca     | flag mean: 0.333333  | loss_multiplier mean: 0.962310
22_st_cntr  | no state adj: 0.609524  | loss_multiplier mean: 0.967443
23_sec_cr31 | chime mean: 0.047619  | loss_multiplier mean: 0.952349
24_job_t_31 | flag mean: 0.100000  | loss_multiplier mean: 0.962348
25_dq_31    | flag mean: 0.028571  | loss_multiplier mean: 0.955917
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.955917
27_auth_31  | flag mean: 0.019048  | loss_multiplier mean: 0.947539
28_soft_31  | soft_pull: 0.828571  low_bureau: 0.004762  cd_perc: 0.109524  | loss_multiplier mean: 0.993754
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.903413
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.905277

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 0.905277  (n=210)
  bb_populated: 201 / 210  wtd_mult: 0.925711  ragu_gli: 1.8572

============================================================
  KMX 2026-05-17/2026-05-23 (MTN 4.1)  (n=69)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.086957  tier2: 0.014493  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.000000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.826087  narrowed: 0.057971  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.623188  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.565217  high_pti_npc mean: 0.101449  | loss_multiplier mean: 1.005507
16_stu_loan | flag mean: 0.000000  | loss_multiplier mean: 0.965287
17_hi_price | flag mean: 0.144928  | loss_multiplier mean: 0.976774
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.976774
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 0.976774
20_georgia  | flag mean: 0.057971  | loss_multiplier mean: 0.982520
21_txca     | flag mean: 0.376812  | loss_multiplier mean: 0.953244
22_st_cntr  | no state adj: 0.565217  | loss_multiplier mean: 0.958038
23_sec_cr31 | chime mean: 0.000000  | loss_multiplier mean: 0.927643
24_job_t_31 | flag mean: 0.144928  | loss_multiplier mean: 0.946821
25_dq_31    | flag mean: 0.000000  | loss_multiplier mean: 0.937353
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.937353
27_auth_31  | flag mean: 0.000000  | loss_multiplier mean: 0.927979
28_soft_31  | soft_pull: 0.826087  low_bureau: 0.000000  cd_perc: 0.072464  | loss_multiplier mean: 0.969583
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.881439
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.885962

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 0.885962  (n=69)
  bb_populated: 46 / 69  wtd_mult: 0.916144  ragu_gli: 2.0964

--- MTN 4.1 Multiplier Steps ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,1.008065,1.014323,1.005563,1.001029,1.000000,1.000000
13_clip_3.0,1.008065,1.014323,1.005563,1.001029,1.000000,1.000000
14_vehicle_age_3.0,1.008065,1.014323,1.005563,1.001029,1.000000,1.000000
15_npc_all,1.009474,1.015059,1.006777,1.002270,0.999000,1.005507
16_student_loans_all,1.007692,1.013267,1.011515,0.988110,0.968327,0.965287
17_high_sales_price_4.1,1.014511,1.020540,1.028279,1.008361,0.983977,0.976774
18_driver_flag_all,1.014511,1.020540,1.028279,1.008361,0.983977,0.976774
19_louisiana_all,1.014511,1.022950,1.028279,1.010758,0.983977,0.976774
20_georgia_all,1.027187,1.028734,1.036253,1.015045,0.989646,0.982520
21_txca_all,0.999628,1.006798,1.009501,0.991066,0.962310,0.953244
22_state_counter_all,1.004987,1.013137,1.014971,0.997035,0.967443,0.958038
23_secured_credit_3.1+,1.047835,1.047417,1.066461,1.027172,0.952349,0.927643
24_job_time_3.1+,1.052004,1.048237,1.083342,1.034443,0.962348,0.946821
25_existing_dq_3.1+,1.061188,1.055872,1.095864,1.043432,0.955917,0.937353
26_employment_3.1+,1.063182,1.056450,1.096451,1.043432,0.955917,0.937353
27_auth_tradelines_3.1+,1.053635,1.048768,1.087539,1.034779,0.947539,0.927979
28_soft_pull_3.1+,1.112628,1.134912,1.167469,1.100172,0.993754,0.969583
28b_blanket_3.1+,1.011480,1.031738,1.061336,1.000156,0.903413,0.881439
29_final_clip_3.1+,1.010780,1.027365,1.051007,1.001258,0.905277,0.885962
--- FINAL_MULT (mean),1.010780,1.027365,1.051007,1.001258,0.905277,0.885962
--- WTD_MULT_RAGU,1.007169,1.023261,1.053072,1.014923,0.925711,0.916144
--- GROSS_LOSS_IMPACT,-0.179221,-0.581515,-1.326788,-0.373085,1.857234,2.096412
--- N_RECORDS,155.000000,155.000000,151.000000,136.000000,210.000000,69.000000

--- MTN 4.1 Flag Means ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
job_time_flag,0.070968,0.051613,0.119205,0.080882,0.100000,0.144928
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.354839,0.361290,0.456954,0.419118,0.366667,0.289855
low_vantage_flag,0.012903,0.019355,0.006623,0.007353,0.000000,0.000000
normal_pti_flag,0.896774,0.909677,0.900662,0.897059,0.914286,0.898551
high_pti_tier_1_flag,0.070968,0.051613,0.052980,0.088235,0.047619,0.086957
high_pti_tier_2_flag,0.032258,0.038710,0.046358,0.014706,0.038095,0.014493
high_pti_tier_3_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
existing_dq_flag,0.180645,0.161290,0.198675,0.176471,0.028571,0.000000
seasonal_employment_flag,0.019355,0.006452,0.006623,0.000000,0.000000,0.000000
secured_credit_flag,0.393548,0.412903,0.417219,0.338235,0.066667,0.000000
kmx_auth_tradelines_flag,0.012903,0.045161,0.033113,0.029412,0.019048,0.000000
null_fico_w_vantage_flag,0.961290,0.967742,0.940397,0.897059,0.166667,0.000000
null_fico_null_vantage_flag,0.038710,0.032258,0.059603,0.102941,0.833333,1.000000
soft_pull_flag,0.651613,0.767742,0.874172,0.830882,0.828571,0.826087
narrowed_soft_pull_flag,0.090323,0.135484,0.105960,0.102941,0.090476,0.057971
fraud_adjustment_mean,1.008065,1.014323,1.005563,1.001029,1.000000,1.000000
continuous_vehicle_age_mean,4.512366,4.609140,4.711369,4.468137,4.142857,4.623188
kmx_npc_flag,1.000000,1.000000,1.000000,1.000000,0.519048,0.565217
high_pti_npc,0.103226,0.090323,0.099338,0.102941,0.085714,0.101449
student_loan_flag,0.277419,0.277419,0.324503,0.183824,0.066667,0.000000
high_sales_price_flag,0.129032,0.129032,0.172185,0.183824,0.161905,0.144928
driver_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
louisiana_flag,0.000000,0.006452,0.000000,0.007353,0.000000,0.000000
georgia_flag,0.122581,0.058065,0.072848,0.044118,0.057143,0.057971
txca_flag,0.341935,0.270968,0.291391,0.279412,0.333333,0.376812
chime_flag,0.225806,0.219355,0.271523,0.213235,0.047619,0.000000
low_bureau_flag,0.025806,0.045161,0.039735,0.036765,0.004762,0.000000
cd_perc_flag,0.141935,0.154839,0.139073,0.132353,0.109524,0.072464
open_tl_flag,0.103226,0.135484,0.072848,0.051471,0.004762,0.000000
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
--- N_RECORDS,155.000000,155.000000,151.000000,136.000000,210.000000,69.000000

--- MTN 4.1 Gross Loss Attribution ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
Low FICO (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High PTI (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Loss Scale Div (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Secured Credit (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Auth Tradelines (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Soft Pull (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Fraud Adjustment,-0.134256,-0.306315,-0.147951,-0.305249,-0.000000,-0.000000
Clip (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Vehicle Age (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
NPC,-0.023347,-0.015626,-0.032176,-0.367408,0.018672,-0.095091
Student Loans,0.029525,0.038047,-0.125210,4.221339,0.582011,0.706794
High Sales Price (4.1),-0.112730,-0.154051,-0.438403,-6.019001,-0.299221,-0.204816
Driver Flag,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Louisiana,-0.000000,-0.050803,-0.000000,-0.704398,-0.000000,-0.000000
Georgia,-0.207546,-0.121453,-0.206001,-1.255734,-0.107209,-0.101560
TX / CA,0.454566,0.464280,0.697545,7.092827,0.522745,0.523738
State Counter,-0.089355,-0.135199,-0.144108,-1.781544,-0.099270,-0.086851
Secured Credit / Chime (3.1+),-0.697875,-0.716741,-1.319791,-8.834726,0.293476,0.558218
Job Time (3.1+),-0.066377,-0.016864,-0.418865,-2.092692,-0.194943,-0.354298
Existing DQ (3.1+),-0.145286,-0.156310,-0.306492,-2.566736,0.125141,0.174012
Employment Type (3.1+),-0.031375,-0.011790,-0.014267,-0.000000,-0.000000,-0.000000
Auth Tradelines (3.1+),0.150772,0.157193,0.217637,2.470583,0.164295,0.174012
Soft Pull (3.1+),-0.910606,-1.700322,-1.891448,-18.180157,-0.888772,-0.759334
Blanket Adjustment (3.1+),1.593093,2.052946,2.541917,28.276628,1.778774,1.650206
Clip (3.1+),0.011576,0.091494,0.260825,-0.326818,-0.038466,-0.088619
--- TOTAL (check),-0.179221,-0.581515,-1.326788,-0.373085,1.857234,2.096412

============================================================
  DIAGNOSTICS: All KMX
============================================================

============================================================
  KMX 2026-04-12/2026-04-18 (All KMX)  (n=1367)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.012436  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066569  tier2: 0.027798  tier3: 0.001463  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.446233  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.036576  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.652524  narrowed: 0.090710  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.012312  | loss_multiplier mean: 1.012312
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.012312
14_veh_age  | continuous_age mean: 4.720861  | loss_multiplier mean: 1.012312
15_npc      | npc_flag mean: 0.622531  high_pti_npc mean: 0.095830  | loss_multiplier mean: 1.013079
16_stu_loan | flag mean: 0.220190  | loss_multiplier mean: 1.003112
17_hi_price | flag mean: 0.180688  | loss_multiplier mean: 1.003885
18_driver   | flag mean: 0.000732  | loss_multiplier mean: 1.003990
19_louisiana| flag mean: 0.004389  | loss_multiplier mean: 1.005532
20_georgia  | flag mean: 0.084126  | loss_multiplier mean: 1.014109
21_txca     | flag mean: 0.317484  | loss_multiplier mean: 0.989484
22_st_cntr  | no state adj: 0.594001  | loss_multiplier mean: 0.995562
23_sec_cr31 | chime mean: 0.250914  | loss_multiplier mean: 1.047144
24_job_t_31 | flag mean: 0.089978  | loss_multiplier mean: 1.057227
25_dq_31    | flag mean: 0.137527  | loss_multiplier mean: 1.061758
26_emp_31   | seasonal: 0.008047  | loss_multiplier mean: 1.062624
27_auth_31  | flag mean: 0.036576  | loss_multiplier mean: 1.054312
28_soft_31  | soft_pull: 0.652524  low_bureau: 0.038040  cd_perc: 0.133870  | loss_multiplier mean: 1.093483
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.994075
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.992505

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.990168  (n=1212)
mtn_model 4.1: mean loss_multiplier = 1.010780  (n=155)
  bb_populated: 1362 / 1367  wtd_mult: 0.971473  ragu_gli: 0.7132

============================================================
  KMX 2026-04-19/2026-04-25 (All KMX)  (n=1413)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.010616  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.073602  tier2: 0.033263  tier3: 0.000708  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.436660  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.045294  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.769285  narrowed: 0.099080  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.011883  | loss_multiplier mean: 1.011883
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.011883
14_veh_age  | continuous_age mean: 4.835280  | loss_multiplier mean: 1.011883

15_npc      | npc_flag mean: 0.636943  high_pti_npc mean: 0.107573  | loss_multiplier mean: 1.013190
16_stu_loan | flag mean: 0.213022  | loss_multiplier mean: 1.002342
17_hi_price | flag mean: 0.170559  | loss_multiplier mean: 1.003139
18_driver   | flag mean: 0.001415  | loss_multiplier mean: 1.003358
19_louisiana| flag mean: 0.001415  | loss_multiplier mean: 1.003858
20_georgia  | flag mean: 0.088464  | loss_multiplier mean: 1.012805
21_txca     | flag mean: 0.316348  | loss_multiplier mean: 0.987875
22_st_cntr  | no state adj: 0.593772  | loss_multiplier mean: 0.993884
23_sec_cr31 | chime mean: 0.249115  | loss_multiplier mean: 1.039260
24_job_t_31 | flag mean: 0.096249  | loss_multiplier mean: 1.049708
25_dq_31    | flag mean: 0.124558  | loss_multiplier mean: 1.053209
26_emp_31   | seasonal: 0.009908  | loss_multiplier mean: 1.054243
27_auth_31  | flag mean: 0.045294  | loss_multiplier mean: 1.046477
28_soft_31  | soft_pull: 0.769285  low_bureau: 0.030432  cd_perc: 0.145081  | loss_multiplier mean: 1.104406
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.004006
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.000199

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.996852  (n=1258)
mtn_model 4.1: mean loss_multiplier = 1.027365  (n=155)

  bb_populated: 1402 / 1413  wtd_mult: 0.983018  ragu_gli: 0.4245

============================================================
  KMX 2026-04-26/2026-05-02 (All KMX)  (n=1387)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.008652  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.060562  tier2: 0.034607  tier3: 0.001442  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.428262  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.042538  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.818313  narrowed: 0.103821  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.022805  | loss_multiplier mean: 1.022805
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.022805
14_veh_age  | continuous_age mean: 4.838020  | loss_multiplier mean: 1.022805
15_npc      | npc_flag mean: 0.614996  high_pti_npc mean: 0.096611  | loss_multiplier mean: 1.022653
16_stu_loan | flag mean: 0.223504  | loss_multiplier mean: 1.012772
17_hi_price | flag mean: 0.206200  | loss_multiplier mean: 1.014597
18_driver   | flag mean: 0.001442  | loss_multiplier mean: 1.014842
19_louisiana| flag mean: 0.004326  | loss_multiplier mean: 1.016540
20_georgia  | flag mean: 0.077866  | loss_multiplier mean: 1.024582
21_txca     | flag mean: 0.325162  | loss_multiplier mean: 0.999022
22_st_cntr  | no state adj: 0.592646  | loss_multiplier mean: 1.005020
23_sec_cr31 | chime mean: 0.240087  | loss_multiplier mean: 1.048952
24_job_t_31 | flag mean: 0.113915  | loss_multiplier mean: 1.063964
25_dq_31    | flag mean: 0.129056  | loss_multiplier mean: 1.067739
26_emp_31   | seasonal: 0.008652  | loss_multiplier mean: 1.068684
27_auth_31  | flag mean: 0.042538  | loss_multiplier mean: 1.060778
28_soft_31  | soft_pull: 0.818313  low_bureau: 0.030281  cd_perc: 0.131939  | loss_multiplier mean: 1.117946
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.016315
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.006191

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.000716  (n=1236)
mtn_model 4.1: mean loss_multiplier = 1.051007  (n=151)
  bb_populated: 1380 / 1387  wtd_mult: 0.986223  ragu_gli: 0.3444

============================================================
  KMX 2026-05-03/2026-05-09 (All KMX)  (n=1356)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.014012  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.081121  tier2: 0.030236  tier3: 0.002212  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.410029  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.032448  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.861357  narrowed: 0.095133  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.017397  | loss_multiplier mean: 1.017397
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.017397
14_veh_age  | continuous_age mean: 4.778761  | loss_multiplier mean: 1.017397
15_npc      | npc_flag mean: 0.601770  high_pti_npc mean: 0.113569  | loss_multiplier mean: 1.018091
16_stu_loan | flag mean: 0.205752  | loss_multiplier mean: 1.006121
17_hi_price | flag mean: 0.178466  | loss_multiplier mean: 1.008153
18_driver   | flag mean: 0.001475  | loss_multiplier mean: 1.008419
19_louisiana| flag mean: 0.001475  | loss_multiplier mean: 1.008907
20_georgia  | flag mean: 0.067109  | loss_multiplier mean: 1.015694
21_txca     | flag mean: 0.317847  | loss_multiplier mean: 0.991425
22_st_cntr  | no state adj: 0.613569  | loss_multiplier mean: 0.997629
23_sec_cr31 | chime mean: 0.247050  | loss_multiplier mean: 1.039317
24_job_t_31 | flag mean: 0.106932  | loss_multiplier mean: 1.052727
25_dq_31    | flag mean: 0.123156  | loss_multiplier mean: 1.055401
26_emp_31   | seasonal: 0.007375  | loss_multiplier mean: 1.056168
27_auth_31  | flag mean: 0.032448  | loss_multiplier mean: 1.047750
28_soft_31  | soft_pull: 0.861357  low_bureau: 0.029499  cd_perc: 0.115044  | loss_multiplier mean: 1.108904
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 1.008094
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.003009

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.003204  (n=1220)
mtn_model 4.1: mean loss_multiplier = 1.001258  (n=136)

  bb_populated: 1348 / 1356  wtd_mult: 0.986278  ragu_gli: 0.3431

============================================================
  KMX 2026-05-10/2026-05-16 (All KMX)  (n=1142)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.066550  tier2: 0.038529  tier3: 0.000876  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.080560  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.008757  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.835377  narrowed: 0.096322  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.691185  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.626970  high_pti_npc mean: 0.105954  | loss_multiplier mean: 1.001725
16_stu_loan | flag mean: 0.047285  | loss_multiplier mean: 0.968253
17_hi_price | flag mean: 0.170753  | loss_multiplier mean: 0.971131
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.971131
19_louisiana| flag mean: 0.000876  | loss_multiplier mean: 0.971422
20_georgia  | flag mean: 0.066550  | loss_multiplier mean: 0.977895
21_txca     | flag mean: 0.343257  | loss_multiplier mean: 0.951627
22_st_cntr  | no state adj: 0.589317  | loss_multiplier mean: 0.957271
23_sec_cr31 | chime mean: 0.054291  | loss_multiplier mean: 0.943098
24_job_t_31 | flag mean: 0.102452  | loss_multiplier mean: 0.953996
25_dq_31    | flag mean: 0.022767  | loss_multiplier mean: 0.947042
26_emp_31   | seasonal: 0.000876  | loss_multiplier mean: 0.947122
27_auth_31  | flag mean: 0.008757  | loss_multiplier mean: 0.938175
28_soft_31  | soft_pull: 0.835377  low_bureau: 0.003503  cd_perc: 0.126095  | loss_multiplier mean: 0.975568
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.886880
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.891023

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.887811  (n=932)
mtn_model 4.1: mean loss_multiplier = 0.905277  (n=210)
  bb_populated: 1103 / 1142  wtd_mult: 0.888079  ragu_gli: 2.7980

============================================================
  KMX 2026-05-17/2026-05-23 (All KMX)  (n=275)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.069091  tier2: 0.036364  tier3: 0.003636  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.000000  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.825455  narrowed: 0.094545  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.000000  | loss_multiplier mean: 1.000000
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.000000
14_veh_age  | continuous_age mean: 4.553939  | loss_multiplier mean: 1.000000
15_npc      | npc_flag mean: 0.603636  high_pti_npc mean: 0.109091  | loss_multiplier mean: 1.002764
16_stu_loan | flag mean: 0.000000  | loss_multiplier mean: 0.962653
17_hi_price | flag mean: 0.203636  | loss_multiplier mean: 0.965535
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.965535
19_louisiana| flag mean: 0.000000  | loss_multiplier mean: 0.965535
20_georgia  | flag mean: 0.069091  | loss_multiplier mean: 0.972252
21_txca     | flag mean: 0.352727  | loss_multiplier mean: 0.947052
22_st_cntr  | no state adj: 0.578182  | loss_multiplier mean: 0.952334
23_sec_cr31 | chime mean: 0.000000  | loss_multiplier mean: 0.922096
24_job_t_31 | flag mean: 0.109091  | loss_multiplier mean: 0.934322
25_dq_31    | flag mean: 0.000000  | loss_multiplier mean: 0.924978
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.924978
27_auth_31  | flag mean: 0.000000  | loss_multiplier mean: 0.915729
28_soft_31  | soft_pull: 0.825455  low_bureau: 0.000000  cd_perc: 0.120000  | loss_multiplier mean: 0.947770
28b_blanket | MTN 3.1+ /= 1.1  | loss_multiplier mean: 0.861609
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.866675

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.860215  (n=206)
mtn_model 4.1: mean loss_multiplier = 0.885962  (n=69)
  bb_populated: 157 / 275  wtd_mult: 0.871550  ragu_gli: 3.2112

--- All KMX Multiplier Steps ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,1.012312,1.011883,1.022805,1.017397,1.000000,1.000000
13_clip_3.0,1.012312,1.011883,1.022805,1.017397,1.000000,1.000000
14_vehicle_age_3.0,1.012312,1.011883,1.022805,1.017397,1.000000,1.000000
15_npc_all,1.013079,1.013190,1.022653,1.018091,1.001725,1.002764
16_student_loans_all,1.003112,1.002342,1.012772,1.006121,0.968253,0.962653
17_high_sales_price_4.1,1.003885,1.003139,1.014597,1.008153,0.971131,0.965535
18_driver_flag_all,1.003990,1.003358,1.014842,1.008419,0.971131,0.965535
19_louisiana_all,1.005532,1.003858,1.016540,1.008907,0.971422,0.965535
20_georgia_all,1.014109,1.012805,1.024582,1.015694,0.977895,0.972252
21_txca_all,0.989484,0.987875,0.999022,0.991425,0.951627,0.947052
22_state_counter_all,0.995562,0.993884,1.005020,0.997629,0.957271,0.952334
23_secured_credit_3.1+,1.047144,1.039260,1.048952,1.039317,0.943098,0.922096
24_job_time_3.1+,1.057227,1.049708,1.063964,1.052727,0.953996,0.934322
25_existing_dq_3.1+,1.061758,1.053209,1.067739,1.055401,0.947042,0.924978
26_employment_3.1+,1.062624,1.054243,1.068684,1.056168,0.947122,0.924978
27_auth_tradelines_3.1+,1.054312,1.046477,1.060778,1.047750,0.938175,0.915729
28_soft_pull_3.1+,1.093483,1.104406,1.117946,1.108904,0.975568,0.947770
28b_blanket_3.1+,0.994075,1.004006,1.016315,1.008094,0.886880,0.861609
29_final_clip_3.1+,0.992505,1.000199,1.006191,1.003009,0.891023,0.866675
--- FINAL_MULT (mean),0.992505,1.000199,1.006191,1.003009,0.891023,0.866675
--- WTD_MULT_RAGU,0.971473,0.983018,0.986223,0.986278,0.888079,0.871550
--- GROSS_LOSS_IMPACT,0.713164,0.424542,0.344418,0.343055,2.798026,3.211240
--- N_RECORDS,1367.000000,1413.000000,1387.000000,1356.000000,1142.000000,275.000000

--- All KMX Flag Means ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
job_time_flag,0.089978,0.096249,0.113915,0.106932,0.102452,0.109091
low_fico_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.324067,0.329795,0.335256,0.324484,0.330998,0.316364
low_vantage_flag,0.012436,0.010616,0.008652,0.014012,0.000000,0.000000
normal_pti_flag,0.904170,0.892427,0.903389,0.886431,0.894046,0.890909
high_pti_tier_1_flag,0.066569,0.073602,0.060562,0.081121,0.066550,0.069091
high_pti_tier_2_flag,0.027798,0.033263,0.034607,0.030236,0.038529,0.036364
high_pti_tier_3_flag,0.001463,0.000708,0.001442,0.002212,0.000876,0.003636
existing_dq_flag,0.137527,0.124558,0.129056,0.123156,0.022767,0.000000
seasonal_employment_flag,0.008047,0.009908,0.008652,0.007375,0.000876,0.000000
secured_credit_flag,0.446233,0.436660,0.428262,0.410029,0.080560,0.000000
kmx_auth_tradelines_flag,0.036576,0.045294,0.042538,0.032448,0.008757,0.000000
null_fico_w_vantage_flag,0.975860,0.970276,0.959625,0.909292,0.158494,0.000000
null_fico_null_vantage_flag,0.023409,0.029724,0.040375,0.090708,0.841506,1.000000
soft_pull_flag,0.652524,0.769285,0.818313,0.861357,0.835377,0.825455
narrowed_soft_pull_flag,0.090710,0.099080,0.103821,0.095133,0.096322,0.094545
fraud_adjustment_mean,1.012312,1.011883,1.022805,1.017397,1.000000,1.000000
continuous_vehicle_age_mean,4.720861,4.835280,4.838020,4.778761,4.691185,4.553939
kmx_npc_flag,0.622531,0.636943,0.614996,0.601770,0.626970,0.603636
high_pti_npc,0.095830,0.107573,0.096611,0.113569,0.105954,0.109091
student_loan_flag,0.220190,0.213022,0.223504,0.205752,0.047285,0.000000
high_sales_price_flag,0.180688,0.170559,0.206200,0.178466,0.170753,0.203636
driver_flag,0.000732,0.001415,0.001442,0.001475,0.000000,0.000000
louisiana_flag,0.004389,0.001415,0.004326,0.001475,0.000876,0.000000
georgia_flag,0.084126,0.088464,0.077866,0.067109,0.066550,0.069091
txca_flag,0.317484,0.316348,0.325162,0.317847,0.343257,0.352727
chime_flag,0.250914,0.249115,0.240087,0.247050,0.054291,0.000000
low_bureau_flag,0.038040,0.030432,0.030281,0.029499,0.003503,0.000000
cd_perc_flag,0.133870,0.145081,0.131939,0.115044,0.126095,0.120000
open_tl_flag,0.095099,0.104034,0.090123,0.095133,0.014886,0.000000
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,0.886613,0.890304,0.891132,0.899705,0.816112,0.749091
mtn_model_4.1_pct,0.113387,0.109696,0.108868,0.100295,0.183888,0.250909
--- N_RECORDS,1367.000000,1413.000000,1387.000000,1356.000000,1142.000000,275.000000

--- All KMX Gross Loss Attribution ---

,KMX | 2026-04-12/2026-04-18,KMX | 2026-04-19/2026-04-25,KMX | 2026-04-26/2026-05-02,KMX | 2026-05-03/2026-05-09,KMX | 2026-05-10/2026-05-16,KMX | 2026-05-17/2026-05-23
Low FICO (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
High PTI (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Loss Scale Div (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Secured Credit (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Auth Tradelines (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Soft Pull (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Fraud Adjustment,-1.160026,25.186169,1.258368,1.969246,-0.000000,-0.000000
Clip (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
Vehicle Age (3.0),-0.000000,0.000000,0.000000,0.000000,-0.000000,-0.000000
NPC,-0.071801,2.752849,-0.008262,0.077878,-0.041795,-0.061936
Student Loans,0.937271,-22.952210,-0.541863,-1.350322,0.824136,0.916125
High Sales Price (4.1),-0.073045,1.696394,0.100482,0.230265,-0.071968,-0.067089
Driver Flag,-0.009947,0.464760,0.013454,0.030208,-0.000000,-0.000000
Louisiana,-0.145473,1.061750,0.093320,0.055262,-0.007272,-0.000000
Georgia,-0.805143,18.919676,0.439791,0.765478,-0.161059,-0.155573
TX / CA,2.330400,-53.139410,-1.409871,-2.761368,0.660287,0.589343
State Counter,-0.580607,12.928761,0.334053,0.712368,-0.143376,-0.124821
Secured Credit / Chime (3.1+),-4.788801,95.189118,2.387659,4.674171,0.361714,0.724125
Job Time (3.1+),-0.908394,21.328570,0.792997,1.463739,-0.278606,-0.295592
Existing DQ (3.1+),-0.405432,7.099201,0.197646,0.289638,0.177391,0.225549
Employment Type (3.1+),-0.077335,2.091397,0.049403,0.082943,-0.002029,-0.000000
Auth Tradelines (3.1+),0.744471,-15.764226,-0.414386,-0.913716,0.230161,0.225549
Soft Pull (3.1+),-3.458256,114.878274,2.929331,6.477001,-0.947758,-0.771827
Blanket Adjustment (3.1+),9.035479,-203.217189,-5.318999,-10.882321,2.311221,2.138947
Clip (3.1+),0.149803,-8.099344,-0.558706,-0.577413,-0.113019,-0.131561
--- TOTAL (check),0.713164,0.424542,0.344418,0.343055,2.798026,3.211240

In [10]:
def build_ragu_decomposition(all_df_model, original_model_scores_df, lob='KMX'):
    '''Build RAGU decomposition table from model results.'''
    if all_df_model is None or len(all_df_model) == 0:
        return None

    raw = all_df_model.loc[[lob]][['vintage', 'ms_original', 'gross_loss_impact', 'recovery_impact',
                                   'ltv_impact', 'apr_impact', 'ragu_score', 'ltv']].reset_index(drop=True).set_index('vintage').T.copy()

    ms_for_lob = original_model_scores_df[original_model_scores_df.lob == lob].copy()
    ms_for_lob = ms_for_lob[ms_for_lob['period'].isin(raw.columns)]
    if len(ms_for_lob) > 0:
        raw = pd.concat([raw, ms_for_lob.drop(columns=['lob', 'amt_financed']).rename(columns={'period': 'vintage'}).set_index('vintage').T.rename({'model_score': 'contract_model_score'})])

    raw.index = ['Mountain3 Score', 'Gross Loss Impact', 'Recovery Impact',
                 'LTV Impact', 'APR Impact', 'RAGU Score', 'LTV', 'Contract Model Score']

    decomp = pd.DataFrame(index=['Contract Model Score', 'Mountain3 Score',
                                  'Gross Loss Adjustments', 'Recovery Adjustments',
                                  'LTV Adjustments', 'APR Adjustments',
                                  'RAGU Score', 'LTV'],
                           columns=raw.columns)

    decomp.loc['Contract Model Score'] = raw.loc['Contract Model Score']
    decomp.loc['Mountain3 Score'] = raw.loc['Mountain3 Score'] - raw.loc['Contract Model Score']
    decomp.loc['Gross Loss Adjustments'] = raw.loc['Gross Loss Impact']
    decomp.loc['Recovery Adjustments'] = raw.loc['Recovery Impact']
    decomp.loc['LTV Adjustments'] = raw.loc['LTV Impact']
    decomp.loc['APR Adjustments'] = raw.loc['APR Impact']
    decomp.loc['RAGU Score'] = raw.loc['RAGU Score']
    decomp.loc['LTV'] = raw.loc['LTV']

    return decomp

# Build original_model_scores for each MTN model subset
original_model_scores_by_model = {}
for mtn_model_filter in MTN_MODELS + ['All KMX']:
    if mtn_model_filter == 'All KMX':
        original_model_scores_by_model['All KMX'] = ms_df
    else:
        ula_subset = ula_df_total[ula_df_total.mtn_model == mtn_model_filter]
        if len(ula_subset) > 0:
            original_model_scores_by_model[mtn_model_filter] = rebuild_ms_df(ula_subset)
        else:
            original_model_scores_by_model[mtn_model_filter] = pd.DataFrame(columns=['period', 'lob', 'model_score', 'amt_financed'])

# Write to Excel
with pd.ExcelWriter(EXCEL_OUTPUT, engine='openpyxl') as writer:
    for mtn_model_filter in ['All KMX'] + MTN_MODELS:
        label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
        all_df_model = results_by_model.get(mtn_model_filter)
        orig_ms = original_model_scores_by_model.get(mtn_model_filter)

        if all_df_model is None or len(all_df_model) == 0:
            print(f'{label}: No results to export, writing empty sheet.')
            pd.DataFrame({'Note': [f'No loans found for {label}']}).to_excel(writer, sheet_name=label, index=False)
            continue

        xlsx_df = build_ragu_decomposition(all_df_model, orig_ms, lob='KMX')
        if xlsx_df is not None:
            xlsx_df.to_excel(writer, sheet_name=label)
            print(f'\n{label} RAGU Decomposition:')
            display(xlsx_df)
        else:
            pd.DataFrame({'Note': [f'Could not build decomposition for {label}']}).to_excel(writer, sheet_name=label, index=False)

    # Diagnostics sheets
    for mtn_model_filter in ['All KMX'] + MTN_MODELS:
        label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
        diag_data = diag_results_by_model.get(mtn_model_filter, (None, None, None))
        output_df, flags_df, attribution_df = diag_data

        sheet_mult = f'{label} Mult Steps'[:31]
        sheet_flags = f'{label} Flags'[:31]
        sheet_attr = f'{label} Attribution'[:31]

        if output_df is not None:
            output_df.to_excel(writer, sheet_name=sheet_mult)
        if flags_df is not None:
            flags_df.to_excel(writer, sheet_name=sheet_flags)
        if attribution_df is not None:
            attribution_df.to_excel(writer, sheet_name=sheet_attr)

print(f'\nExported to: {EXCEL_OUTPUT}')
print("[PROGRESS] Export Complete")

All KMX RAGU Decomposition:

vintage,2025-11-30/2025-12-06,2025-12-07/2025-12-13,2025-12-14/2025-12-20,2025-12-21/2025-12-27,2025-12-28/2026-01-03,2026-01-04/2026-01-10,2026-01-11/2026-01-17,2026-01-18/2026-01-24,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11,2026-04-12/2026-04-18,2026-04-19/2026-04-25,2026-04-26/2026-05-02,2026-05-03/2026-05-09,2026-05-10/2026-05-16,2026-05-17/2026-05-23
Contract Model Score,141.876946,142.139621,141.775187,141.957509,142.055772,141.774719,141.49681,141.899148,141.600977,142.161469,142.380543,142.071714,142.061998,142.386654,142.479797,142.596629,142.681611,143.054067,142.941315,142.735321,142.779579,142.881051,142.906452,143.304192,142.8916
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,1.086122,1.23488,0.739525,0.777234,1.320884,1.01981,0.706455,0.734824,0.559958,0.588202,0.597023,-0.124953,-0.433156,-0.044022,-0.002267,0.181845,0.01588,0.167584,1.211476,0.713164,0.424542,0.344418,0.343055,2.798026,3.21124
Recovery Adjustments,1.602058,1.277148,1.884743,1.357884,1.776315,0.936074,1.154949,1.075469,0.975747,1.141665,0.674724,0.769911,0.482942,0.529244,1.075175,1.236999,1.324129,1.186408,1.155511,1.501622,1.623783,1.172871,1.509721,1.454723,1.819865
LTV Adjustments,-0.326046,1.131262,0.710486,0.90732,0.60155,0.545147,0.544337,0.024191,0.650091,0.395629,0.600958,0.828224,0.512015,0.346333,0.246908,0.539406,0.546199,0.523913,0.195093,0.62804,0.669718,0.627998,1.036038,1.225101,2.301254
APR Adjustments,0.685136,0.774791,0.812633,0.988939,0.914396,0.09685,0.104489,0.173995,0.371827,0.411511,0.690206,0.659046,0.178251,0.53722,0.812143,0.840703,0.557454,0.701973,0.609506,0.608753,0.652211,0.727688,0.686193,0.901052,0.718387
RAGU Score,144.924216,146.557702,145.922573,145.988885,146.668917,144.372599,144.007039,143.907626,144.158599,144.698475,144.943454,144.203941,142.802051,143.755429,144.611756,145.395584,145.125273,145.633943,146.112901,146.1869,146.149832,145.754026,146.481459,149.683094,150.942347
LTV,1.610072,1.524077,1.547949,1.53669,1.554252,1.557535,1.557582,1.588531,1.551437,1.566306,1.554286,1.541194,1.55947,1.56922,1.57513,1.55787,1.557474,1.558775,1.578227,1.552714,1.550302,1.552717,1.529415,1.518854,1.461412

MTN 3.0 RAGU Decomposition:

vintage                2025-11-30/2025-12-06
Contract Model Score              139.536387
Mountain3 Score                          0.0
Gross Loss Adjustments              1.367279
Recovery Adjustments                0.284278
LTV Adjustments                    -0.979686
APR Adjustments                     0.594396
RAGU Score                        140.802654
LTV                                 1.651877

MTN 3.1 RAGU Decomposition:

vintage,2025-11-30/2025-12-06,2025-12-07/2025-12-13,2025-12-14/2025-12-20,2025-12-21/2025-12-27,2025-12-28/2026-01-03,2026-01-04/2026-01-10,2026-01-11/2026-01-17,2026-01-18/2026-01-24,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11
Contract Model Score,142.641358,142.139621,141.804005,141.792301,141.865362,141.700507,141.372322,141.791998,141.117699,141.889291,142.186004,141.913026,141.406028,142.060512,141.880186,142.240622,142.188799,142.849743,143.107478
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,0.994037,1.23488,0.858554,0.862644,1.523831,1.211001,0.934991,0.908706,0.785679,0.737805,0.791221,-0.046036,-0.351128,-0.141882,0.161576,0.416094,0.160319,0.220725,2.08774
Recovery Adjustments,2.044023,1.277148,1.773233,1.443467,1.767444,0.822379,1.014802,1.032028,1.069303,1.061506,0.811959,0.888132,0.470614,0.54539,1.114268,1.636329,1.186056,1.025383,0.25182
LTV Adjustments,-0.104521,1.131262,0.566393,0.942675,0.390383,0.472067,0.520215,-0.025233,0.583822,0.242756,0.486162,0.59966,0.383595,0.709837,0.484655,0.604148,0.746691,0.608153,-1.713643
APR Adjustments,0.714856,0.774791,0.727144,0.985017,0.786687,0.045169,0.09969,0.163558,0.40157,0.434738,0.72932,0.848262,0.306329,0.940105,0.955229,1.09707,0.667271,0.918943,0.983868
RAGU Score,146.289752,146.557702,145.729329,146.026105,146.333707,144.251123,143.942019,143.871058,143.958074,144.366097,145.004665,144.203044,142.215438,144.113961,144.595915,145.994263,144.949136,145.622947,144.717263
LTV,1.59638,1.524077,1.556297,1.534685,1.566616,1.56181,1.558991,1.591536,1.555282,1.575378,1.560984,1.554361,1.567017,1.547986,1.561072,1.554101,1.545866,1.553868,1.701484

MTN 3.2 RAGU Decomposition:

vintage,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11,2026-04-12/2026-04-18,2026-04-19/2026-04-25,2026-04-26/2026-05-02,2026-05-03/2026-05-09,2026-05-10/2026-05-16,2026-05-17/2026-05-23
Contract Model Score,142.118567,142.297686,141.383512,141.863417,141.924607,142.053173,142.385677,142.360023,142.04436,142.453334,142.41553,142.44406,142.552948,142.469225,142.449591,142.629474,142.555658
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,0.283252,0.612819,0.671006,-0.007266,-0.294608,0.188009,0.079626,0.128277,-0.004509,0.276696,1.256309,0.826183,0.54713,0.547153,0.423929,3.014931,3.686029
Recovery Adjustments,1.935688,1.222282,0.541592,0.521429,0.497582,0.438332,0.82994,0.961852,1.524587,1.237174,1.215584,1.512073,1.652588,1.2303,1.526042,1.474338,1.357187
LTV Adjustments,-0.327164,0.572921,0.658483,0.895801,0.321128,-0.227754,-0.155397,0.160128,0.365856,0.332098,0.337518,0.585476,0.718729,0.504227,0.958482,1.174244,1.700474
APR Adjustments,0.124431,0.041496,0.284926,0.322741,-0.056359,0.098373,0.573294,0.499423,0.214342,0.425485,0.436678,0.586916,0.595895,0.665874,0.592603,0.565993,0.316023
RAGU Score,144.134773,144.747205,143.539519,143.596123,142.39235,142.550132,143.71314,144.109703,144.144636,144.724787,145.66162,145.954707,146.06729,145.416778,145.950647,148.858979,149.615371
LTV,1.610142,1.555916,1.550951,1.537344,1.570714,1.603968,1.599504,1.580324,1.568065,1.570064,1.569742,1.555186,1.547474,1.559926,1.53379,1.52168,1.492932

MTN 4.1 RAGU Decomposition:

vintage,2025-12-14/2025-12-20,2025-12-21/2025-12-27,2025-12-28/2026-01-03,2026-01-04/2026-01-10,2026-01-11/2026-01-17,2026-01-18/2026-01-24,2026-01-25/2026-01-31,2026-02-01/2026-02-07,2026-02-08/2026-02-14,2026-02-15/2026-02-21,2026-02-22/2026-02-28,2026-03-01/2026-03-07,2026-03-08/2026-03-14,2026-03-15/2026-03-21,2026-03-22/2026-03-28,2026-03-29/2026-04-04,2026-04-05/2026-04-11,2026-04-12/2026-04-18,2026-04-19/2026-04-25,2026-04-26/2026-05-02,2026-05-03/2026-05-09,2026-05-10/2026-05-16,2026-05-17/2026-05-23
Contract Model Score,141.366824,143.015816,143.451321,142.266283,142.30266,142.672288,144.256069,143.888991,144.476556,143.55873,145.297113,145.106952,144.987739,145.002135,146.979511,146.487574,146.48111,145.015868,144.631845,146.296946,146.986442,146.21033,143.903015
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,-0.938976,0.233329,-0.16603,-0.253774,-0.771943,-0.522634,-0.687881,-0.470046,-0.811883,-0.923423,-1.499922,-0.769102,-0.953048,-0.444409,-0.39169,-0.507266,0.420736,-0.179221,-0.581515,-1.326788,-0.373085,1.857234,2.096412
Recovery Adjustments,3.487539,0.819257,1.841366,1.7034,2.077529,1.390888,-0.104586,1.634653,-0.154812,1.174378,0.449647,0.901667,2.151009,1.025818,0.949059,1.52608,1.246228,1.418062,1.38709,0.698815,1.361627,1.367985,2.941937
LTV Adjustments,2.921514,0.684318,2.257514,1.04238,0.701439,0.387251,1.656275,1.33814,1.377146,1.646784,2.144365,1.865561,1.439133,2.141467,0.628655,1.114804,0.352884,0.968945,0.274149,1.693814,1.742663,1.447897,3.81922
APR Adjustments,2.018163,1.013911,1.85007,0.441111,0.135537,0.249468,0.323397,0.576541,0.747007,1.057822,0.969595,1.130593,1.460847,1.441876,1.621648,1.19394,1.593392,0.781178,1.114383,1.237237,1.514935,2.354326,1.663159
RAGU Score,148.855066,145.76663,149.234241,145.1994,144.445223,144.17726,145.443274,146.96828,145.634014,146.51429,147.360798,148.235672,149.08568,149.166887,149.787184,149.815133,150.094349,148.004832,146.825952,148.600024,151.232581,153.237772,154.423742
LTV,1.430236,1.549458,1.463662,1.529058,1.54847,1.566801,1.495305,1.512609,1.510466,1.495816,1.469514,1.484136,1.507072,1.469664,1.552679,1.524997,1.568832,1.533198,1.573506,1.493289,1.490675,1.506594,1.387399

Exported to: new_kmx_models.xlsx
[PROGRESS] Export Complete

In [11]:
print("="*80)
print("  VERIFICATION: All KMX vs bareboned_ragu_new.ipynb")
print("="*80)

all_kmx_df = results_by_model.get('All KMX')
if all_kmx_df is not None and len(all_kmx_df) > 0:
    try:
        reference_df = pd.read_csv('all_df.csv')
        ref_kmx = reference_df[reference_df.lob == 'KMX'].copy() if 'lob' in reference_df.columns else pd.DataFrame()

        if len(ref_kmx) > 0:
            our_kmx = all_kmx_df.reset_index()
            our_kmx = our_kmx[our_kmx.lob == 'KMX'][['vintage', 'ms_original', 'gross_loss_impact', 'recovery_impact', 'ragu_score', 'loss_multiplier']].copy()
            our_kmx = our_kmx.set_index('vintage')

            ref_cols = ['vintage', 'ms_original', 'ragu_score', 'loss_multiplier']
            ref_available = [c for c in ref_cols if c in ref_kmx.columns]
            ref_kmx_compare = ref_kmx[ref_available].copy()
            ref_kmx_compare = ref_kmx_compare.set_index('vintage')

            common_vintages = sorted(set(our_kmx.index) & set(ref_kmx_compare.index))

            if common_vintages:
                comparison = pd.DataFrame(index=common_vintages)
                for col in [c for c in ['ragu_score', 'loss_multiplier'] if c in ref_kmx_compare.columns]:
                    comparison[f'{col}_ours'] = our_kmx.loc[common_vintages, col].values
                    comparison[f'{col}_ref'] = ref_kmx_compare.loc[common_vintages, col].values
                    comparison[f'{col}_diff'] = comparison[f'{col}_ours'] - comparison[f'{col}_ref']

                print(f"\nComparing {len(common_vintages)} common vintages:")
                display(comparison)
            else:
                print("No common vintages found.")
        else:
            print("No KMX rows found in reference all_df.csv.")
    except FileNotFoundError:
        print("all_df.csv not found. Run bareboned_ragu_new.ipynb first to generate the reference file.")
    except Exception as e:
        print(f"Error loading reference data: {e}")
        print("\nManually compare the 'All KMX' sheet in new_kmx_models.xlsx")
        print("against the KMX rows in barebones_ragu.xlsx")
else:
    print("No 'All KMX' results to verify.")

# Summary table
print("\n" + "="*80)
print("  SUMMARY: RAGU Scores by MTN Model (most recent vintage)")
print("="*80)
summary_rows = []
baseline_ltv = BASELINES['KMX']['ltv']
for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    model_df = results_by_model.get(mtn_model_filter)
    if model_df is not None and len(model_df) > 0:
        kmx_rows = model_df.reset_index()
        kmx_rows = kmx_rows[kmx_rows.lob == 'KMX']
        if len(kmx_rows) > 0:
            last_vintage = kmx_rows.vintage.max()
            last_row = kmx_rows[kmx_rows.vintage == last_vintage].iloc[0]
            summary_rows.append({
                'Model': label,
                'Latest Vintage': last_vintage,
                'Contract MS': last_row.get('ms_original', float('nan')),
                'Gross Loss Impact': last_row.get('gross_loss_impact', float('nan')),
                'Recovery Impact': last_row.get('recovery_impact', float('nan')),
                'LTV Impact': last_row.get('ltv_impact', float('nan')),
                'APR Impact': last_row.get('apr_impact', float('nan')),
                'RAGU Score': last_row.get('ragu_score', float('nan')),
                'LTV': last_row.get('ltv', float('nan')),
                'Loss Multiplier': last_row.get('loss_multiplier', float('nan')),
                'N Vintages': len(kmx_rows),
            })

if summary_rows:
    summary_df = pd.DataFrame(summary_rows).set_index('Model')
    display(summary_df)

    print(f"\nRAGU decomposition:")
    print(f"  baseline_ltv = {baseline_ltv}")
    print(f"  baseline_apr = {BASELINES['KMX']['apr']}")
    print(f"  RAGU Score = (unit_loss * recovery * baselined_recovery) + ltv_impact + apr_impact")
else:
    print("No results available.")

================================================================================
  VERIFICATION: All KMX vs bareboned_ragu_new.ipynb
================================================================================
No common vintages found.

================================================================================
  SUMMARY: RAGU Scores by MTN Model (most recent vintage)
================================================================================

,Latest Vintage,Contract MS,Gross Loss Impact,Recovery Impact,LTV Impact,APR Impact,RAGU Score,LTV,Loss Multiplier,N Vintages
Model,,,,,,,,,,
MTN 3.0,2025-11-30/2025-12-06,139.536387,1.367279,0.284278,-0.979686,0.594396,140.802654,1.651877,0.945309,1
MTN 3.1,2026-04-05/2026-04-11,143.107478,2.087740,0.251820,-1.713643,0.983868,144.717263,1.701484,0.916490,19
MTN 3.2,2026-05-17/2026-05-23,142.555658,3.686029,1.357187,1.700474,0.316023,149.615371,1.492932,0.852559,17
MTN 4.1,2026-05-17/2026-05-23,143.903015,2.096412,2.941937,3.819220,1.663159,154.423742,1.387399,0.916144,23
All KMX,2026-05-17/2026-05-23,142.891600,3.211240,1.819865,2.301254,0.718387,150.942347,1.461412,0.871550,25

RAGU decomposition:
  baseline_ltv = 1.59
  baseline_apr = 0.25
  RAGU Score = (unit_loss * recovery * baselined_recovery) + ltv_impact + apr_impact