In [1]:
import pandas as pd
import numpy as np
import pyodbc
import warnings
from IPython.display import display

pd.set_option('display.max_columns', 80)
pd.set_option('display.min_rows', 40)
pd.set_option('display.width', 200)

DSN = 'Redshift_prod_new'


def run_sql(query, connection=None):
    if connection is None:
        with pyodbc.connect(f'DSN={DSN}') as conn:
            warnings.filterwarnings('ignore', category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings('default', category=UserWarning)
            return df
    else:
        warnings.filterwarnings('ignore', category=UserWarning)
        df = pd.read_sql_query(sql=query, con=connection)
        warnings.filterwarnings('default', category=UserWarning)
        return df


print(f'Imports loaded, DSN={DSN}')

Imports loaded, DSN=Redshift_prod_new

## Step 1: Introspect `sandbox.rds_rec_model_originations`
Pull all column names and types from the information schema to understand what vehicle-level data is available.

In [2]:
introspect_query = """
SELECT column_name,
       data_type,
       ordinal_position
FROM information_schema.columns
WHERE table_schema = 'sandbox'
  AND table_name   = 'rds_rec_model_originations'
ORDER BY ordinal_position
"""

schema_df = run_sql(introspect_query)
print(f'{len(schema_df)} columns in sandbox.rds_rec_model_originations\n')
display(schema_df)

43 columns in sandbox.rds_rec_model_originations

                       column_name          data_type  ordinal_position
0                   account_number             bigint                 1
1                         con_date               date                 2
2                              lob  character varying                 3
3                         state_pb  character varying                 4
4                      driver_flag            integer                 5
5                     retired_flag            integer                 6
6                    military_flag            integer                 7
7                     job_category  character varying                 8
8                       trade_flag            numeric                 9
9                              vin  character varying                10
10                           vin10  character varying                11
11                        veh_year            integer                12
12                        veh_make  character varying                13
13                    veh_make_grp  character varying                14
14                       veh_model  character varying                15
15                    veh_age_orig            numeric                16
16                    mileage_orig            numeric                17
17             mileage_orig_capped            numeric                18
18                        bb_value   double precision                19
19                  kmx_sale_price            numeric                20
20                   veh_class_raw  character varying                21
21                   veh_class_grp  character varying                22
22                        veh_trim  character varying                23
23                    veh_fuel_raw  character varying                24
24                    veh_fuel_grp  character varying                25
25               vin10_mapped_flag            integer                26
26                    impound_flag            integer                27
27                        mmi_orig   double precision                28
28                         mmi_auc   double precision                29
29                         auc_amt            numeric                30
30                        auc_date               date                31
31                       auc_grade            numeric                32
32                     mileage_auc            integer                33
33             pred_t0_adj_impound   double precision                34
34          pred_t0_adj_no_impound   double precision                35
35              pred_depr_rate_raw   double precision                36
36              pred_depr_rate_std   double precision                37
37      pred_depr_rate_raw_current   double precision                38
38      pred_depr_rate_std_current   double precision                39
39         pred_depr_rate_raw_prod   double precision                40
40         pred_depr_rate_std_prod   double precision                41
41  pred_t0_adj_no_impound_current   double precision                42
42     pred_t0_adj_impound_current   double precision                43

## Step 2: Fetch data with vehicle-related columns

After reviewing the schema above, adjust the column list below to include every
vehicle-descriptive column available (make, model year, fuel type, body style,
new/used, mileage, etc.).  The query also pulls the current standardised
depreciation rate so we can bucket contracts.

In [3]:
# ---------------------------------------------------------------------------
# After running the introspection cell above, paste the vehicle-related column
# names you found into this query.  The template below is a best-guess from the
# columns seen across the repo; uncomment / adjust as needed once you see the
# actual schema output.
# ---------------------------------------------------------------------------

vehicle_cols = [c for c in schema_df.column_name.tolist() if any(
    kw in c.lower() for kw in [
        'make', 'model', 'year', 'fuel', 'body', 'type', 'new_used',
        'mileage', 'odometer', 'vin', 'class', 'drivetrain', 'engine',
        'transmission', 'trim', 'ev', 'electric', 'hybrid', 'vehicle',
        'msrp', 'bb_value', 'bbvalue', 'sale', 'price',
    ]
)]

core_cols = [
    'account_number', 'con_date', 'lob',
    'pred_depr_rate_std', 'pred_depr_rate_std_current',
    'pred_depr_rate_raw_current',
]

all_cols = core_cols + [c for c in vehicle_cols if c not in core_cols]
col_list = ',\n       '.join(all_cols)

print(f'Vehicle-related columns found: {vehicle_cols}')
print(f'\nTotal columns to fetch: {len(all_cols)}')

data_query = f"""
SELECT {col_list}
FROM sandbox.rds_rec_model_originations
WHERE con_date >= '2022-01-01'
  AND con_date <  '2026-07-01'
  AND pred_depr_rate_std_current IS NOT NULL
"""

print(f'\nQuery:\n{data_query}')
df = run_sql(data_query)

df['con_date'] = pd.to_datetime(df['con_date'])
print(f'\nFetched {len(df):,} records')
print(f'Date range: {df.con_date.min().date()} to {df.con_date.max().date()}')
print(f'\npred_depr_rate_std_current summary:')
display(df['pred_depr_rate_std_current'].describe().round(4))

Vehicle-related columns found: ['vin', 'vin10', 'veh_year', 'veh_make', 'veh_make_grp', 'veh_model', 'mileage_orig', 'mileage_orig_capped', 'bb_value', 'kmx_sale_price', 'veh_class_raw', 'veh_class_grp', 'veh_trim', 'veh_fuel_raw', 'veh_fuel_grp', 'vin10_mapped_flag', 'mileage_auc']

Total columns to fetch: 23

Query:

SELECT account_number,
       con_date,
       lob,
       pred_depr_rate_std,
       pred_depr_rate_std_current,
       pred_depr_rate_raw_current,
       vin,
       vin10,
       veh_year,
       veh_make,
       veh_make_grp,
       veh_model,
       mileage_orig,
       mileage_orig_capped,
       bb_value,
       kmx_sale_price,
       veh_class_raw,
       veh_class_grp,
       veh_trim,
       veh_fuel_raw,
       veh_fuel_grp,
       vin10_mapped_flag,
       mileage_auc
FROM sandbox.rds_rec_model_originations
WHERE con_date >= '2022-01-01'
  AND con_date <  '2026-07-01'
  AND pred_depr_rate_std_current IS NOT NULL


Fetched 571,454 records
Date range: 2022-01-01 to 2026-06-30

pred_depr_rate_std_current summary:

count    571454.0000
mean          0.2062
std           0.0476
min           0.0193
25%           0.1660
50%           0.2216
75%           0.2370
max           0.3605
Name: pred_depr_rate_std_current, dtype: float64

## Step 3: Bucket into Low (<20%) and High (>25%) depreciation

In [4]:
LOW_THRESHOLD  = 0.20
HIGH_THRESHOLD = 0.25

df['depr_bucket'] = np.where(
    df['pred_depr_rate_std_current'] < LOW_THRESHOLD, 'Low (<20%)',
    np.where(
        df['pred_depr_rate_std_current'] > HIGH_THRESHOLD, 'High (>25%)',
        'Middle (20-25%)'
    )
)

bucket_counts = df['depr_bucket'].value_counts()
bucket_pcts   = df['depr_bucket'].value_counts(normalize=True).mul(100).round(2)

summary = pd.DataFrame({'count': bucket_counts, 'pct': bucket_pcts})
print('Depreciation bucket distribution:')
display(summary)

low_df  = df[df['depr_bucket'] == 'Low (<20%)'].copy()
high_df = df[df['depr_bucket'] == 'High (>25%)'].copy()

print(f'\nLow  depreciation contracts: {len(low_df):,}')
print(f'High depreciation contracts: {len(high_df):,}')

Depreciation bucket distribution:

                  count    pct
depr_bucket
Middle (20-25%)  304350  53.26
Low (<20%)       180935  31.66
High (>25%)       86169  15.08

Low  depreciation contracts: 180,935
High depreciation contracts: 86,169

## Step 4: Profile extreme buckets by vehicle attributes

The cells below automatically use whichever vehicle columns were found during
introspection.  Each categorical column is summarised as a frequency table within
each bucket; numerical columns get descriptive statistics.

In [5]:
extreme_df = df[df['depr_bucket'].isin(['Low (<20%)', 'High (>25%)'])].copy()

profile_cols = [c for c in vehicle_cols if c in extreme_df.columns]

for col in profile_cols:
    print('=' * 80)
    print(f'  {col}')
    print('=' * 80)

    if extreme_df[col].dtype in ('object', 'category') or extreme_df[col].nunique() <= 30:
        tbl = (
            extreme_df
            .groupby(['depr_bucket', col])
            .size()
            .unstack(fill_value=0)
            .T
        )
        tbl['total'] = tbl.sum(axis=1)
        tbl = tbl.sort_values('total', ascending=False)
        for bucket in ['Low (<20%)', 'High (>25%)']:
            if bucket in tbl.columns:
                tbl[f'{bucket} %'] = (tbl[bucket] / tbl[bucket].sum() * 100).round(2)
        display(tbl.head(30))
    else:
        display(
            extreme_df
            .groupby('depr_bucket')[col]
            .describe()
            .round(4)
        )
    print()

================================================================================
  vin
================================================================================

              count  unique                top freq
depr_bucket
High (>25%)   86169   85202  KL8CL6S07FC760866    5
Low (<20%)   180935  179349  5YFBURHE4EP080689    3

================================================================================
  vin10
================================================================================

              count unique         top freq
depr_bucket
High (>25%)   86169  35039  5YJ3E1EA6P   59
Low (<20%)   180935  56137  5YFEPMAE9N  412

================================================================================
  veh_year
================================================================================

                count       mean     std     min     25%     50%     75%     max
depr_bucket
High (>25%)   86169.0  2017.7108  9.8550    23.0  2015.0  2018.0  2020.0  2026.0
Low (<20%)   180935.0  2018.4141  4.5342  1986.0  2015.0  2019.0  2022.0  2026.0

================================================================================
  veh_make
================================================================================

              count unique     top   freq
depr_bucket
High (>25%)   86169     69    FORD  15252
Low (<20%)   180935     65  TOYOTA  66827

================================================================================
  veh_make_grp
================================================================================

depr_bucket   High (>25%)  Low (<20%)   total  Low (<20%) %  High (>25%) %
veh_make_grp
ToyHo                   1      121922  121923         67.38           0.00
Other               46198        2622   48820          1.45          53.61
Ford                17795       12372   30167          6.84          20.65
GM                   6785       19406   26191         10.73           7.87
Stellantis           1362       20201   21563         11.16           1.58
Nissan              11659        1817   13476          1.00          13.53
Korean               2220        1725    3945          0.95           2.58
Japanese              149         870    1019          0.48           0.17

================================================================================
  veh_model
================================================================================

              count unique      top   freq
depr_bucket
High (>25%)   80771    678   FUSION   5665
Low (<20%)   174062    832  COROLLA  25489

================================================================================
  mileage_orig
================================================================================

                count        mean         std  min      25%      50%       75%        max
depr_bucket
High (>25%)   86169.0  68588.1227  35497.5979  0.0  43962.0  62517.0   89770.0   882757.0
Low (<20%)   180935.0  75639.7046  49595.8990  0.0  41890.5  65637.0  105875.0  1685174.0

================================================================================
  mileage_orig_capped
================================================================================

                count        mean         std  min      25%      50%       75%       max
depr_bucket
High (>25%)   86169.0  68582.6741  35418.8691  0.0  43962.0  62517.0   89766.0  517860.0
Low (<20%)   180935.0  75602.9928  49307.2298  0.0  41890.5  65635.0  105866.5  977410.0

================================================================================
  bb_value
================================================================================

                count        mean         std    min      25%      50%      75%       max
depr_bucket
High (>25%)   78721.0  18084.0997  12051.3694  375.0   9700.0  15725.0  23400.0  219775.0
Low (<20%)   163577.0  18638.8342  11004.8576  250.0  11100.0  16700.0  22950.0  208400.0

================================================================================
  kmx_sale_price
================================================================================

               count        mean           std           min      25%      50%      75%       max
depr_bucket
High (>25%)  46365.0  -9750.0137  7.762627e+06 -1.671462e+09  18998.0  23998.0  30998.0  103998.0
Low (<20%)   69954.0 -14507.5141  9.780265e+06 -2.581561e+09  17998.0  21998.0  27998.0  144398.0

================================================================================
  veh_class_raw
================================================================================

depr_bucket                 High (>25%)  Low (<20%)  total  Low (<20%) %  High (>25%) %
veh_class_raw
Small Car                          2594       43777  46371         24.19           3.01
Pickup                                4       44908  44912         24.82           0.00
Mid-Size Car                       6585       33260  39845         18.38           7.64
Luxury Car                        31494        5490  36984          3.03          36.55
Large Crossover/SUV               13986        8521  22507          4.71          16.23
Small Crossover/SUV                1536       17842  19378          9.86           1.78
Small Luxury Crossover/SUV        15268        2037  17305          1.13          17.72
Large Luxury Crossover/SUV        13651        3273  16924          1.81          15.84
Sporty Car                            5       16381  16386          9.05           0.01
Minivan                             198        2929   3127          1.62           0.23
Full-Size Car                       845        1051   1896          0.58           0.98
Full-Size Van                         3        1181   1184          0.65           0.00
Compact Van                           0         285    285          0.16           0.00

================================================================================
  veh_class_grp
================================================================================

depr_bucket    High (>25%)  Low (<20%)  total  Low (<20%) %  High (>25%) %
veh_class_grp
Car                  38924       39801  78725         22.00          45.17
Compact               2594       43777  46371         24.19           3.01
Truck                    4       44908  44912         24.82           0.00
SUV Large            27637       11794  39431          6.52          32.07
SUV Small            16804       19879  36683         10.99          19.50
Sporty                   5       16381  16386          9.05           0.01
Minivan                198        2929   3127          1.62           0.23
Work Van                 3        1466   1469          0.81           0.00

================================================================================
  veh_trim
================================================================================

depr_bucket  High (>25%)  Low (<20%)   total  Low (<20%) %  High (>25%) %
veh_trim
Standard           25756      170135  195891         94.03          29.89
Luxury             60413       10800   71213          5.97          70.11

================================================================================
  veh_fuel_raw
================================================================================

depr_bucket     High (>25%)  Low (<20%)   total  Low (<20%) %  High (>25%) %
veh_fuel_raw
Gas                   75104      163375  238479         90.29          87.16
Hybrid                 1026        7400    8426          4.09           1.19
Electric               7078         238    7316          0.13           8.21
Diesel                  580        5891    6471          3.26           0.67
Flex                    564        3611    4175          2.00           0.65
PHEV                   1655         223    1878          0.12           1.92
Plug-in Hybrid          144          12     156          0.01           0.17
Hydrogen                  5         109     114          0.06           0.01
diesel                    1          51      52          0.03           0.00
hybrid                    0          13      13          0.01           0.00
phev                     12           0      12          0.00           0.01
CNG                       0           6       6          0.00           0.00
Hyb/Elec                  0           3       3          0.00           0.00
electric                  0           2       2          0.00           0.00
LPG                       0           1       1          0.00           0.00

================================================================================
  veh_fuel_grp
================================================================================

depr_bucket   High (>25%)  Low (<20%)   total  Low (<20%) %  High (>25%) %
veh_fuel_grp
Gas                 75104      163382  238486         90.30          87.16
EV                   8894         584    9478          0.32          10.32
Hybrid               1026        7416    8442          4.10           1.19
Diesel                580        5891    6471          3.26           0.67
Flex                  564        3611    4175          2.00           0.65
diesel                  1          51      52          0.03           0.00

================================================================================
  vin10_mapped_flag
================================================================================

depr_bucket        High (>25%)  Low (<20%)   total  Low (<20%) %  High (>25%) %
vin10_mapped_flag
0                        75519      159352  234871         88.07          87.64
1                        10650       21583   32233         11.93          12.36

================================================================================
  mileage_auc
================================================================================

               count         mean         std  min       25%       50%        75%       max
depr_bucket
High (>25%)  16909.0  104047.9485  41291.8982  1.0  74855.00  100569.0  130546.00  339349.0
Low (<20%)   29562.0  108605.2164  53774.5861  1.0  70835.75  102752.0  140434.25  777777.0

## Step 5: Combined comparison table

A single side-by-side table showing how each vehicle attribute distributes across
the two extreme depreciation buckets.

In [6]:
cat_cols = [c for c in profile_cols
            if extreme_df[c].dtype in ('object', 'category') or extreme_df[c].nunique() <= 30]

rows = []
for col in cat_cols:
    for bucket_label in ['Low (<20%)', 'High (>25%)']:
        subset = extreme_df[extreme_df['depr_bucket'] == bucket_label]
        top = subset[col].value_counts(normalize=True).head(10)
        for val, pct in top.items():
            rows.append({
                'attribute': col,
                'value': val,
                'bucket': bucket_label,
                'pct': round(pct * 100, 2),
                'count': int(subset[col].eq(val).sum()),
            })

comparison_df = pd.DataFrame(rows)

if not comparison_df.empty:
    pivot = comparison_df.pivot_table(
        index=['attribute', 'value'],
        columns='bucket',
        values='pct',
        fill_value=0,
    ).reset_index()

    count_pivot = comparison_df.pivot_table(
        index=['attribute', 'value'],
        columns='bucket',
        values='count',
        fill_value=0,
    ).reset_index()

    combined = pivot.copy()
    for bucket_label in ['Low (<20%)', 'High (>25%)']:
        if bucket_label in count_pivot.columns:
            combined[f'{bucket_label} n'] = count_pivot[bucket_label]

    print('Top values per attribute by depreciation bucket (% within bucket):\n')
    display(combined)
else:
    print('No categorical vehicle columns found for comparison.')

Top values per attribute by depreciation bucket (% within bucket):

bucket          attribute                       value  High (>25%)  Low (<20%)  Low (<20%) n  High (>25%) n
0           veh_class_grp                         Car        45.17       22.00       39801.0        38924.0
1           veh_class_grp                     Compact         3.01       24.19       43777.0         2594.0
2           veh_class_grp                     Minivan         0.23        1.62        2929.0          198.0
3           veh_class_grp                   SUV Large        32.07        6.52       11794.0        27637.0
4           veh_class_grp                   SUV Small        19.50       10.99       19879.0        16804.0
5           veh_class_grp                      Sporty         0.01        9.05       16381.0            5.0
6           veh_class_grp                       Truck         0.00       24.82       44908.0            4.0
7           veh_class_grp                    Work Van         0.00        0.81        1466.0            3.0
8           veh_class_raw               Full-Size Car         0.98        0.00           0.0          845.0
9           veh_class_raw         Large Crossover/SUV        16.23        4.71        8521.0        13986.0
10          veh_class_raw  Large Luxury Crossover/SUV        15.84        1.81        3273.0        13651.0
11          veh_class_raw                  Luxury Car        36.55        3.03        5490.0        31494.0
12          veh_class_raw                Mid-Size Car         7.64       18.38       33260.0         6585.0
13          veh_class_raw                     Minivan         0.23        1.62        2929.0          198.0
14          veh_class_raw                      Pickup         0.00       24.82       44908.0            0.0
15          veh_class_raw                   Small Car         3.01       24.19       43777.0         2594.0
16          veh_class_raw         Small Crossover/SUV         1.78        9.86       17842.0         1536.0
17          veh_class_raw  Small Luxury Crossover/SUV        17.72        1.13        2037.0        15268.0
18          veh_class_raw                  Sporty Car         0.01        9.05       16381.0            5.0
19           veh_fuel_grp                      Diesel         0.67        3.26        5891.0          580.0
20           veh_fuel_grp                          EV        10.32        0.32         584.0         8894.0
21           veh_fuel_grp                        Flex         0.65        2.00        3611.0          564.0
22           veh_fuel_grp                         Gas        87.16       90.30      163382.0        75104.0
23           veh_fuel_grp                      Hybrid         1.19        4.10        7416.0         1026.0
24           veh_fuel_grp                      diesel         0.00        0.03          51.0            1.0
25           veh_fuel_raw                      Diesel         0.67        3.26        5891.0          580.0
26           veh_fuel_raw                    Electric         8.21        0.13         238.0         7078.0
27           veh_fuel_raw                        Flex         0.65        2.00        3611.0          564.0
28           veh_fuel_raw                         Gas        87.16       90.29      163375.0        75104.0
29           veh_fuel_raw                      Hybrid         1.19        4.09        7400.0         1026.0
30           veh_fuel_raw                    Hydrogen         0.01        0.06         109.0            5.0
31           veh_fuel_raw                        PHEV         1.92        0.12         223.0         1655.0
32           veh_fuel_raw              Plug-in Hybrid         0.17        0.01          12.0          144.0
33           veh_fuel_raw                      diesel         0.00        0.03          51.0            1.0
34           veh_fuel_raw                      hybrid         0.00        0.01          13.0            0.0
35           veh_fuel_raw                        phev         0.01        0.00           0.0           12.0
36           veh_make_grp                        Ford        20.65        6.84       12372.0        17795.0
37           veh_make_grp                          GM         7.87       10.73       19406.0         6785.0
38           veh_make_grp                    Japanese         0.17        0.48         870.0          149.0
39           veh_make_grp                      Korean         2.58        0.95        1725.0         2220.0
40           veh_make_grp                      Nissan        13.53        1.00        1817.0        11659.0
41           veh_make_grp                       Other        53.61        1.45        2622.0        46198.0
42           veh_make_grp                  Stellantis         1.58       11.16       20201.0         1362.0
43           veh_make_grp                       ToyHo         0.00       67.38      121922.0            1.0
44               veh_trim                      Luxury        70.11        5.97       10800.0        60413.0
45               veh_trim                    Standard        29.89       94.03      170135.0        25756.0
46      vin10_mapped_flag                           0        87.64       88.07      159352.0        75519.0
47      vin10_mapped_flag                           1        12.36       11.93       21583.0        10650.0

## Step 6: LOB breakdown within each extreme bucket

In [7]:
lob_breakdown = (
    extreme_df
    .groupby(['depr_bucket', 'lob'])
    .agg(
        n=('account_number', 'count'),
        mean_depr=('pred_depr_rate_std_current', 'mean'),
    )
    .reset_index()
)

lob_breakdown['pct_within_bucket'] = (
    lob_breakdown.groupby('depr_bucket')['n']
    .transform(lambda x: x / x.sum() * 100)
    .round(2)
)
lob_breakdown['mean_depr'] = lob_breakdown['mean_depr'].round(4)

print('LOB distribution within each extreme depreciation bucket:\n')
display(
    lob_breakdown.pivot_table(
        index='lob',
        columns='depr_bucket',
        values=['n', 'pct_within_bucket', 'mean_depr'],
    ).fillna(0)
)

LOB distribution within each extreme depreciation bucket:

              mean_depr                      n            pct_within_bucket
depr_bucket High (>25%) Low (<20%) High (>25%) Low (<20%)       High (>25%) Low (<20%)
lob
AN               0.2634     0.1437      6021.0    14571.0              6.99       8.05
ENT              0.2742     0.1339      4715.0    18787.0              5.47      10.38
FLD              0.2642     0.1436      4305.0     7880.0              5.00       4.36
FRN              0.2642     0.1464     14627.0    34703.0             16.97      19.18
KMX              0.2622     0.1452     46366.0    69954.0             53.81      38.66
SFS              0.2614     0.1561      2993.0     9972.0              3.47       5.51
STG              0.2631     0.1421      7142.0    25068.0              8.29      13.85