# KMX MTN-Specific RAGU Score Notebook
This notebook computes RAGU scores for KMX loans, broken down by MTN model (3.0, 3.1, 3.2, 4.1).
Aligned with `bareboned_ragu_new.ipynb` for diagnostic purposes.
- **Granularity:** Configurable (weekly/monthly/quarterly) via `granularity` in cell 1
- **Date handling:** Weekly uses `app_date`, monthly/quarterly use `book_date`
- **Output:** Per-model RAGU decomposition + diagnostics, exported to `new_kmx_models.xlsx`

## How to Run
1. Set `granularity`, `START_DATE`, `END_DATE` in cell 1
2. Set `run_from_pickle = True` to load pre-computed data (faster), or `False` to re-run SQL queries
3. Run All Cells
4. Results are exported to `new_kmx_models.xlsx`

In [1]:
import pandas as pd
import numpy as np
import pyodbc
import pickle
import warnings
import time
from tqdm.notebook import tqdm
from matplotlib import pyplot as plt
tqdm.pandas()
pd.set_option('display.max_columns', 100)
pd.set_option('display.min_rows', 100)
import openpyxl
import datetime as dt
import re
import os

# ── Configuration ──
granularity = 'q'                # 'q' = quarterly, 'm' = monthly, 'w' = weekly

START_DATE = '2023-01-01'
END_DATE = None                  # None = auto-detect from today's date

run_every_query = True           # True = re-run SQL, False = load pickle
run_from_pickle = not run_every_query

DATE_COL_MAP = {'q': 'book_date', 'm': 'book_date', 'w': 'app_date'}
PERIOD_FREQ_MAP = {'q': 'Q', 'm': 'M', 'w': 'W-SAT'}

BASELINES = {
    'KMX': {'ltv': 1.59, 'new_recovery_unadjusted': 0.58, 'apr': 0.25},
}

MODEL_PARAMS = {
    'mean_unit_loss': 0.5,
    'unit_loss_to_model_score': 0.02,
    'kmx_loss_scale': 0.067,
}

MTN_MODELS = [3.0, 3.1, 3.2, 4.1]
EXCEL_OUTPUT = '../output/new_kmx_models.xlsx'

# ── Derived values ──
date_col = DATE_COL_MAP[granularity]
start_date = pd.Timestamp(START_DATE)
end_date = pd.Timestamp(END_DATE) if END_DATE else pd.Timestamp.today().normalize()
period_freq = PERIOD_FREQ_MAP[granularity]
start_period = start_date.to_period(period_freq)
end_period = end_date.to_period(period_freq)
min_date_sql = f"'{START_DATE}'"

print(f"Granularity: {granularity}")
print(f"Date column: {date_col}")
print(f"Period range: {start_period} to {end_period}")
print(f"SQL min_date: {min_date_sql}")

Granularity: q
Date column: book_date
Period range: 2023Q1 to 2026Q3
SQL min_date: '2023-01-01'

In [2]:
def run_sql(filename, sub_list=None, connection=None, filename_is_query=False):
    if sub_list is None:
        sub_list = []
    if filename_is_query:
        query = filename
    else:
        with open(filename, 'r') as file:
            query = file.read()
    for text, var in sub_list:
        query = query.replace(text, var)
    if connection is None:
        with pyodbc.connect("DSN=Redshift_prod_new") as conn:
            warnings.filterwarnings("ignore", category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings("default", category=UserWarning)
            return df
    else:
        warnings.filterwarnings("ignore", category=UserWarning)
        df = pd.read_sql_query(sql=query, con=connection)
        warnings.filterwarnings("default", category=UserWarning)
        return df


def store_pickle(data, filename):
    if isinstance(data, str):
        data, filename = filename, data
    with open(filename, 'wb') as file:
        pickle.dump(data, file)


def get_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)


def cached_sql(filename, pickle_name, sub_list=None, connection=None, force_refresh=False):
    """Fetch from SQL and cache to pickle. Reuse cache unless force_refresh=True
    or the pickle file is missing."""
    if force_refresh or not os.path.exists(pickle_name):
        df = run_sql(filename, sub_list=sub_list, connection=connection)
        store_pickle(df, pickle_name)
        return df
    return get_pickle(pickle_name)


def smooth(series):
    averaged_series = pd.Series(index=series.index, dtype=float)
    averaged_series.iloc[0] = series.iloc[0]
    averaged_series.iloc[1] = (series.iloc[0] + series.iloc[1] + series.iloc[2]) / 3
    for i in range(2, len(series) - 2):
        averaged_series.iloc[i] = series.iloc[i-2:i+3].mean()
    averaged_series.iloc[-2] = (series.iloc[-1] + series.iloc[-2] + series.iloc[-3]) / 3
    averaged_series.iloc[-1] = series.iloc[-1]
    return averaged_series


def weight_by_proceeds(metric, proceeds):
    return (metric * proceeds).sum() / proceeds.sum()


def weighted_average_and_sum(group, metrics):
    if isinstance(metrics, str):
        weighted_avg = (group[metrics] * group.amt_financed).sum() / group.amt_financed.sum()
        return pd.Series({metrics: weighted_avg, 'amt_financed': group.amt_financed.sum()})
    result_dict = {'amt_financed': group.amt_financed.sum()}
    for metric in metrics:
        weighted_avg = (group[metric] * group.amt_financed).sum() / group.amt_financed.sum()
        result_dict[metric] = weighted_avg
    return pd.Series(result_dict)


def format_vintage(period_series):
    """Convert pd.Period series to formatted vintage strings."""
    if len(period_series) == 0:
        return period_series.astype(str)
    freq = period_series.iloc[0].freqstr
    if freq == 'Q-DEC':
        return period_series.dt.year.astype(str) + ' Q' + period_series.dt.quarter.astype(str)
    elif freq == 'M':
        return period_series.dt.year.astype(str) + ' M' + period_series.dt.month.astype(str).str.zfill(2)
    return period_series.astype(str)


def rebuild_ms_df(ula_subset):
    """Recompute ms_df from a filtered ula_df subset (for per-model scoring).
    MTN 4.1 transform is already applied in-place on ula_df_total upstream."""
    ms_source = ula_subset[['lob', 'cd_model_score', 'amt_financed', 'period']].copy()
    ms_source = ms_source.rename(columns={'cd_model_score': 'model_score'})
    ms = ms_source.groupby(['period', 'lob']).apply(
        weighted_average_and_sum, 'model_score', include_groups=False
    ).reset_index()
    ms['period'] = format_vintage(ms['period'])
    return ms

In [3]:
# Per-table caches under cache/ with _v1 schema tags. When run_from_pickle=True
# (i.e. run_every_query=False) each cached_sql call reuses its pickle if present
# and falls through to SQL if missing. Delete an individual pickle to force a
# selective refresh.
#
# Note: ULA is cached under cache/ula_kmx_v1.pkl because this notebook
# applies a KMX-only filter via sub_list; that is a different schema (KMX
# subset of rows) than the full-LOB cache/ula_v1.pkl written by
# bareboned_ragu_new.ipynb. DLA and new_recovery use identical queries in both
# notebooks, so they share the same cache files.

os.makedirs('cache', exist_ok=True)
force = run_every_query

need_conn = force or not all(
    os.path.exists(p) for p in ('../../cache/ula_kmx_v1.pkl', '../../cache/dla_v1.pkl', '../../cache/new_recovery_v1.pkl')
)

if need_conn:
    with pyodbc.connect("DSN=Redshift_prod_new") as conn:
        ula_df_total = cached_sql(
            '../queries/vintage_level_ula_query.txt', '../../cache/ula_kmx_v1.pkl',
            sub_list=[('{min_book_date}', f"{min_date_sql}\n  AND dru.riskdealergroup = 'KMX'")],
            connection=conn, force_refresh=force,
        )
        print('ULA ready')

        dla_df = cached_sql(
            '../queries/new_dll_query.txt', '../../cache/dla_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('DLA ready')

        new_recovery = cached_sql(
            '../queries/new_recovery_queryt.txt', '../../cache/new_recovery_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('New recovery ready')
else:
    ula_df_total = get_pickle('../../cache/ula_kmx_v1.pkl')
    dla_df = get_pickle('../../cache/dla_v1.pkl')
    new_recovery = get_pickle('../../cache/new_recovery_v1.pkl')
    print('ULA, DLA, New recovery loaded from cache')

print(f"ULA records: {len(ula_df_total):,}")
print("[PROGRESS] Data Fetch Complete")

ULA ready
DLA ready
New recovery ready
ULA records: 604,002
[PROGRESS] Data Fetch Complete

In [4]:
def get_ula_multiplier_kmx(ula_df, loss_scale=None, leave_out='None'):
    if loss_scale is None:
        loss_scale = MODEL_PARAMS['kmx_loss_scale']
    ula_df['loss_multiplier'] = 1.0

    if leave_out!='Low FICO':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_fico_flag & ~ula_df.high_model_score_flag)\
                                    + loss_scale * (ula_df.low_fico_flag & ula_df.high_model_score_flag)

    if leave_out!='Low Vantage':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_vantage_flag & ~ula_df.high_model_score_flag)\
                                    + loss_scale * (ula_df.low_vantage_flag & ula_df.high_model_score_flag)

    if leave_out!='High PTI':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + 0 * ula_df.normal_pti_flag \
                                    + 0.05 * ula_df.high_pti_tier_1_flag \
                                    + 0.1 * ula_df.high_pti_tier_2_flag \
                                    + (1.4 * (1 + loss_scale) - 1) * ula_df.high_pti_tier_3_flag

    ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] /= (1 + loss_scale)

    if leave_out!='Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 1 + (-0.01 + 0.06 * ula_df.secured_credit_flag)\
                                        * ~(~ula_df.job_time_flag & ula_df.narrowed_soft_pull_flag & ula_df.secured_credit_flag)

    if leave_out!='Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= 0.99 + 0.18 * ula_df.kmx_auth_tradelines_flag

    if leave_out!='Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier'] *= (
            1 + ~ula_df.job_time_flag * (~ula_df.narrowed_soft_pull_flag * -0.025
            + ula_df.narrowed_soft_pull_flag * (~ula_df.secured_credit_flag * 0.108
            + ula_df.secured_credit_flag * 0.295)))

    if leave_out != 'Fraud':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + (ula_df.fraud_adjustment - 1)

    if leave_out!='Clip':
        clipped_multiplier = np.clip(ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'], 0.8, 1.35 / (1 + loss_scale))
        ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'] = clipped_multiplier

    if leave_out!='Vehicle Age':
        ula_df.loc[ula_df.mtn_model.isin([3.0]),'loss_multiplier']  *= 0.8593 + 0.0201 * ula_df.continuous_vehicle_age

    if leave_out !='npc':
        ula_df.loc[ula_df.kmx_npc_flag, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.high_pti_npc

    if leave_out != 'Student Loans':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.96 +  0.14 * ula_df.student_loan_flag

    if leave_out != 'high sales price':
        ula_df.loc[ula_df.mtn_model.isin([4.1]),'loss_multiplier'] *= 0.98 + 0.22 * ula_df.high_sales_price_flag

    if leave_out != 'Driver flag':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 1 + 0.15 * ula_df.driver_flag

    if leave_out!='Louisiana':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier']  *= 1 + 0.35 * ula_df.louisiana_flag

    if leave_out!='georgia':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier']  *= 1 + 0.1 * ula_df.georgia_flag

    if leave_out!='txca':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score > 140) ,'loss_multiplier']  *= 1 - 0.1 * ula_df.txca_flag
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score <= 140) &  (ula_df.cd_model_score >= 135)   ,'loss_multiplier']  *= 1 - 0.05 * ula_df.txca_flag

    if leave_out!='state_counter_adj':
        ula_df.loc[ ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1])  & (ula_df.cd_model_score < 150) & ~(ula_df.louisiana_flag | ula_df.georgia_flag | ula_df.txca_flag) ,'loss_multiplier'] *= 1.012

    if leave_out!='Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.96 + (0.01 * ula_df.soft_pull_flag  - 0.18*ula_df.chime_flag* ula_df.soft_pull_flag) + 0.46*ula_df.chime_flag

    if leave_out!='Job time':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.21 * ula_df.job_time_flag

    if leave_out!='Existing DQ':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.11 * ula_df.existing_dq_flag

    if leave_out!='Employment type':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]),'loss_multiplier'] *= 1 + 0.1 * ula_df.seasonal_employment_flag

    if leave_out!='Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]),'loss_multiplier'] *= 0.99 + 0.06 * ula_df.kmx_auth_tradelines_flag

    if leave_out!='Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ula_df.soft_pull_flag,'loss_multiplier'] *= 1.1  * (0.99 + 0.11*ula_df.low_bureau_flag)  * (0.978 + 0.172*ula_df.open_tl_flag)
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]) & ~ula_df.soft_pull_flag,'loss_multiplier'] *= (1 * (0.98 + 0.22*ula_df.low_bureau_flag)  * (0.945 + 0.405*ula_df.open_tl_flag ) /np.maximum(ula_df.cd_perc_flag*ula_df.open_tl_flag*1.2,1))

        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) &  ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.97  + 0.15  * ula_df.cd_perc_flag
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2]) & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 0.954 + 0.346 * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1)         &  ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0   + 0.05  * ula_df.cd_perc_flag
        ula_df.loc[(ula_df.mtn_model == 4.1)         & ~ula_df.soft_pull_flag, 'loss_multiplier'] *= 1.0   + 0.10  * ula_df.cd_perc_flag


    if leave_out!='blanket adjustment':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] /= 1.1


    if leave_out!='Clip':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] = np.clip(ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'], 0.75, 1.4)

    return ula_df


def get_ula_multiplier_kmx_diag(ula_df, loss_scale=None, leave_out='None', verbose=True):
    """Identical logic to get_ula_multiplier_kmx, but also returns step-by-step loss_multiplier means and flag means."""
    if loss_scale is None:
        loss_scale = MODEL_PARAMS['kmx_loss_scale']
    steps = {}
    def _record(label, df):
        steps[label] = df.loss_multiplier.mean()

    ula_df['loss_multiplier'] = 1.0
    _record('00_initial', ula_df)
    if verbose:
        print(f"00_initial  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low FICO':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_fico_flag & ~ula_df.high_model_score_flag) \
                                    + loss_scale * (ula_df.low_fico_flag & ula_df.high_model_score_flag)
    _record('02_low_fico_3.0', ula_df)
    if verbose:
        print(f"02_low_fico | flag mean: {ula_df.low_fico_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low Vantage':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0.25 * (ula_df.low_vantage_flag & ~ula_df.high_model_score_flag) \
                                    + loss_scale * (ula_df.low_vantage_flag & ula_df.high_model_score_flag)
    _record('03_low_vantage_3.0', ula_df)
    if verbose:
        print(f"03_low_vant | flag mean: {ula_df.low_vantage_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High PTI':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + 0 * ula_df.normal_pti_flag \
                                    + 0.05 * ula_df.high_pti_tier_1_flag \
                                    + 0.1 * ula_df.high_pti_tier_2_flag \
                                    + (1.4 * (1 + loss_scale) - 1) * ula_df.high_pti_tier_3_flag
    _record('04_high_pti_3.0', ula_df)
    if verbose:
        print(f"04_high_pti | tier1: {ula_df.high_pti_tier_1_flag.mean():.6f}  tier2: {ula_df.high_pti_tier_2_flag.mean():.6f}  tier3: {ula_df.high_pti_tier_3_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] /= (1 + loss_scale)
    _record('07_loss_scale_div_3.0', ula_df)
    if verbose:
        print(f"07_scale_dv | dividing by (1 + {loss_scale})  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 1 + (-0.01 + 0.06 * ula_df.secured_credit_flag) \
                                        * ~(~ula_df.job_time_flag & ula_df.narrowed_soft_pull_flag & ula_df.secured_credit_flag)
    _record('08_secured_credit_3.0', ula_df)
    if verbose:
        print(f"08_sec_cred | flag mean: {ula_df.secured_credit_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 0.99 + 0.18 * ula_df.kmx_auth_tradelines_flag
    _record('09_auth_tradelines_3.0', ula_df)
    if verbose:
        print(f"09_auth_tl  | flag mean: {ula_df.kmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= (
            1 + ~ula_df.job_time_flag * (~ula_df.narrowed_soft_pull_flag * -0.025
            + ula_df.narrowed_soft_pull_flag * (~ula_df.secured_credit_flag * 0.108
            + ula_df.secured_credit_flag * 0.295)))
    _record('11_soft_pull_3.0', ula_df)
    if verbose:
        print(f"11_soft_pll | flag mean: {ula_df.soft_pull_flag.mean():.6f}  narrowed: {ula_df.narrowed_soft_pull_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Fraud':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + (ula_df.fraud_adjustment - 1)
    _record('12_fraud_all', ula_df)
    if verbose:
        print(f"12_fraud    | fraud_adj mean: {ula_df.fraud_adjustment.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        clipped_multiplier = np.clip(ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'], 0.8, 1.35 / (1 + loss_scale))
        ula_df.loc[(ula_df.mtn_model.isin([3.0])) & (~ula_df.high_pti_tier_3_flag), 'loss_multiplier'] = clipped_multiplier
    _record('13_clip_3.0', ula_df)
    if verbose:
        print(f"13_clip_3.0 | clip [0.8, {1.35 / (1 + loss_scale):.4f}]  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Vehicle Age':
        ula_df.loc[ula_df.mtn_model.isin([3.0]), 'loss_multiplier'] *= 0.8593 + 0.0201 * ula_df.continuous_vehicle_age
    _record('14_vehicle_age_3.0', ula_df)
    if verbose:
        print(f"14_veh_age  | continuous_age mean: {ula_df.continuous_vehicle_age.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'npc':
        ula_df.loc[ula_df.kmx_npc_flag, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.high_pti_npc
    _record('15_npc_all', ula_df)
    if verbose:
        print(f"15_npc      | npc_flag mean: {ula_df.kmx_npc_flag.mean():.6f}  high_pti_npc mean: {ula_df.high_pti_npc.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Student Loans':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.96 + 0.14 * ula_df.student_loan_flag
    _record('16_student_loans_all', ula_df)
    if verbose:
        print(f"16_stu_loan | flag mean: {ula_df.student_loan_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'high sales price':
        ula_df.loc[ula_df.mtn_model.isin([4.1]), 'loss_multiplier'] *= 0.98 + 0.22 * ula_df.high_sales_price_flag
    _record('17_high_sales_price_4.1', ula_df)
    if verbose:
        print(f"17_hi_price | flag mean: {ula_df.high_sales_price_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Driver flag':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.15 * ula_df.driver_flag
    _record('18_driver_flag_all', ula_df)
    if verbose:
        print(f"18_driver   | flag mean: {ula_df.driver_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Louisiana':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.35 * ula_df.louisiana_flag
    _record('19_louisiana_all', ula_df)
    if verbose:
        print(f"19_louisiana| flag mean: {ula_df.louisiana_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'georgia':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.1 * ula_df.georgia_flag
    _record('20_georgia_all', ula_df)
    if verbose:
        print(f"20_georgia  | flag mean: {ula_df.georgia_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'txca':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score > 140), 'loss_multiplier'] *= 1 - 0.1 * ula_df.txca_flag
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score <= 140) & (ula_df.cd_model_score >= 135), 'loss_multiplier'] *= 1 - 0.05 * ula_df.txca_flag
    _record('21_txca_all', ula_df)
    if verbose:
        print(f"21_txca     | flag mean: {ula_df.txca_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'state_counter_adj':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]) & (ula_df.cd_model_score < 150) & ~(ula_df.louisiana_flag | ula_df.georgia_flag | ula_df.txca_flag), 'loss_multiplier'] *= 1.012
    _record('22_state_counter_all', ula_df)
    if verbose:
        no_state_adj = ((~ula_df.louisiana_flag) & (~ula_df.georgia_flag) & (~ula_df.txca_flag)).mean()
        print(f"22_st_cntr  | no state adj: {no_state_adj:.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.96 + (0.01 * ula_df.soft_pull_flag - 0.18 * ula_df.chime_flag * ula_df.soft_pull_flag) + 0.46 * ula_df.chime_flag
    _record('23_secured_credit_3.1+', ula_df)
    if verbose:
        print(f"23_sec_cr31 | chime mean: {ula_df.chime_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Job time':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.21 * ula_df.job_time_flag
    _record('24_job_time_3.1+', ula_df)
    if verbose:
        print(f"24_job_t_31 | flag mean: {ula_df.job_time_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Existing DQ':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.existing_dq_flag
    _record('25_existing_dq_3.1+', ula_df)
    if verbose:
        print(f"25_dq_31    | flag mean: {ula_df.existing_dq_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Employment type':
        ula_df.loc[ula_df.mtn_model.isin([3.0, 3.1, 3.2, 4.1]), 'loss_multiplier'] *= 1 + 0.1 * ula_df.seasonal_employment_flag
    _record('26_employment_3.1+', ula_df)
    if verbose:
        print(f"26_emp_31   | seasonal: {ula_df.seasonal_employment_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] *= 0.99 + 0.06 * ula_df.kmx_auth_tradelines_flag
    _record('27_auth_tradelines_3.1+', ula_df)
    if verbose:
        print(f"27_auth_31  | flag mean: {ula_df.kmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    mtn31_mask = ula_df.mtn_model.isin([3.1, 3.2, 4.1])
    sp_mask_31 = mtn31_mask & ula_df.soft_pull_flag
    hp_mask_31 = mtn31_mask & ~ula_df.soft_pull_flag

    if leave_out != 'Soft pull':
        ula_df.loc[sp_mask_31, 'loss_multiplier'] *= 0.99 + 0.11 * ula_df.low_bureau_flag
    _record('28a_sp_low_bureau_3.1+', ula_df)
    if verbose:
        sp_pop = ula_df[sp_mask_31]
        print(f"28a_sp_lb   | SP pct: {sp_mask_31.mean():.6f}  low_bureau(SP): {sp_pop.low_bureau_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[sp_mask_31, 'loss_multiplier'] *= 0.978 + 0.172 * ula_df.open_tl_flag
    _record('28b_sp_open_tl_3.1+', ula_df)
    if verbose:
        print(f"28b_sp_otl  | open_tl(SP): {sp_pop.open_tl_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[hp_mask_31, 'loss_multiplier'] *= 0.98 + 0.22 * ula_df.low_bureau_flag
    _record('28c_hp_low_bureau_3.1+', ula_df)
    if verbose:
        hp_pop = ula_df[hp_mask_31]
        print(f"28c_hp_lb   | HP pct: {hp_mask_31.mean():.6f}  low_bureau(HP): {hp_pop.low_bureau_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[hp_mask_31, 'loss_multiplier'] *= 0.945 + 0.405 * ula_df.open_tl_flag
    _record('28d_hp_open_tl_3.1+', ula_df)
    if verbose:
        print(f"28d_hp_otl  | open_tl(HP): {hp_pop.open_tl_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[hp_mask_31, 'loss_multiplier'] /= np.maximum(ula_df.cd_perc_flag * ula_df.open_tl_flag * 1.2, 1)
    _record('28e_hp_interaction_3.1+', ula_df)
    if verbose:
        hp_both = (hp_mask_31 & ula_df.cd_perc_flag.astype(bool) & ula_df.open_tl_flag.astype(bool)).mean()
        print(f"28e_hp_int  | HP cd_perc & open_tl pct: {hp_both:.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    sp_mask_312 = ula_df.mtn_model.isin([3.1, 3.2]) & ula_df.soft_pull_flag
    hp_mask_312 = ula_df.mtn_model.isin([3.1, 3.2]) & ~ula_df.soft_pull_flag
    sp_mask_41 = (ula_df.mtn_model == 4.1) & ula_df.soft_pull_flag
    hp_mask_41 = (ula_df.mtn_model == 4.1) & ~ula_df.soft_pull_flag

    if leave_out != 'Soft pull':
        ula_df.loc[sp_mask_312, 'loss_multiplier'] *= 0.97 + 0.15 * ula_df.cd_perc_flag
    _record('28f_sp_cd_perc_3.1/3.2', ula_df)
    if verbose:
        sp_312 = ula_df[sp_mask_312]
        print(f"28f_sp_cdp  | SP 3.1/3.2 pct: {sp_mask_312.mean():.6f}  cd_perc(SP): {sp_312.cd_perc_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[hp_mask_312, 'loss_multiplier'] *= 0.954 + 0.346 * ula_df.cd_perc_flag
    _record('28g_hp_cd_perc_3.1/3.2', ula_df)
    if verbose:
        hp_312 = ula_df[hp_mask_312]
        print(f"28g_hp_cdp  | HP 3.1/3.2 pct: {hp_mask_312.mean():.6f}  cd_perc(HP): {hp_312.cd_perc_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[sp_mask_41, 'loss_multiplier'] *= 1.0 + 0.05 * ula_df.cd_perc_flag
    _record('28h_sp_cd_perc_4.1', ula_df)
    if verbose:
        sp_41 = ula_df[sp_mask_41]
        print(f"28h_sp_cdp  | SP 4.1 pct: {sp_mask_41.mean():.6f}  cd_perc(SP): {sp_41.cd_perc_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Soft pull':
        ula_df.loc[hp_mask_41, 'loss_multiplier'] *= 1.0 + 0.10 * ula_df.cd_perc_flag
    _record('28i_hp_cd_perc_4.1', ula_df)
    if verbose:
        hp_41 = ula_df[hp_mask_41]
        print(f"28i_hp_cdp  | HP 4.1 pct: {hp_mask_41.mean():.6f}  cd_perc(HP): {hp_41.cd_perc_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'blanket adjustment':
        ula_df.loc[hp_mask_31, 'loss_multiplier'] /= 1.1
    _record('28j_blanket_hp_3.1+', ula_df)
    if verbose:
        print(f"28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'] = np.clip(ula_df.loc[ula_df.mtn_model.isin([3.1, 3.2, 4.1]), 'loss_multiplier'], 0.75, 1.4)
    _record('29_final_clip_3.1+', ula_df)
    if verbose:
        print(f"29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")
        print("\n--- Per MTN Model Means ---")
        for model in [3.0, 3.1, 3.2, 4.1]:
            mean_val = ula_df.loc[ula_df.mtn_model == model, 'loss_multiplier'].mean()
            count_val = (ula_df.mtn_model == model).sum()
            print(f"mtn_model {model}: mean loss_multiplier = {mean_val:.6f}  (n={count_val})")

    n = len(ula_df)
    flags = {
        'job_time_flag': ula_df.job_time_flag.mean(),
        'low_fico_flag': ula_df.low_fico_flag.mean(),
        'high_model_score_flag': ula_df.high_model_score_flag.mean(),
        'low_vantage_flag': ula_df.low_vantage_flag.mean(),
        'normal_pti_flag': ula_df.normal_pti_flag.mean(),
        'high_pti_tier_1_flag': ula_df.high_pti_tier_1_flag.mean(),
        'high_pti_tier_2_flag': ula_df.high_pti_tier_2_flag.mean(),
        'high_pti_tier_3_flag': ula_df.high_pti_tier_3_flag.mean(),
        'existing_dq_flag': ula_df.existing_dq_flag.mean(),
        'seasonal_employment_flag': ula_df.seasonal_employment_flag.mean(),
        'secured_credit_flag': ula_df.secured_credit_flag.mean(),
        'kmx_auth_tradelines_flag': ula_df.kmx_auth_tradelines_flag.mean(),
        'null_fico_w_vantage_flag': ula_df.null_fico_w_vantage_flag.mean(),
        'null_fico_null_vantage_flag': ula_df.null_fico_null_vantage_flag.mean(),
        'soft_pull_flag': ula_df.soft_pull_flag.mean(),
        'narrowed_soft_pull_flag': ula_df.narrowed_soft_pull_flag.mean(),
        'fraud_adjustment_mean': ula_df.fraud_adjustment.mean(),
        'continuous_vehicle_age_mean': ula_df.continuous_vehicle_age.mean(),
        'kmx_npc_flag': ula_df.kmx_npc_flag.mean(),
        'high_pti_npc': ula_df.high_pti_npc.mean(),
        'student_loan_flag': ula_df.student_loan_flag.mean(),
        'high_sales_price_flag': ula_df.high_sales_price_flag.mean(),
        'driver_flag': ula_df.driver_flag.mean(),
        'louisiana_flag': ula_df.louisiana_flag.mean(),
        'georgia_flag': ula_df.georgia_flag.mean(),
        'txca_flag': ula_df.txca_flag.mean(),
        'chime_flag': ula_df.chime_flag.mean(),
        'low_bureau_flag': ula_df.low_bureau_flag.mean(),
        'cd_perc_flag': ula_df.cd_perc_flag.mean(),
        'open_tl_flag': ula_df.open_tl_flag.mean(),
        'mtn_3_1_flag': ula_df.mtn_3_1_flag.mean(),
        'mtn_model_3.0_pct': (ula_df.mtn_model == 3.0).mean(),
        'mtn_model_3.1_pct': (ula_df.mtn_model == 3.1).mean(),
        'mtn_model_3.2_pct': (ula_df.mtn_model == 3.2).mean(),
        'mtn_model_4.1_pct': (ula_df.mtn_model == 4.1).mean(),
        'soft_pull_pct_3.1+': ula_df.loc[mtn31_mask, 'soft_pull_flag'].mean() if mtn31_mask.any() else float('nan'),
        'low_bureau_flag_sp': ula_df.loc[sp_mask_31, 'low_bureau_flag'].mean() if sp_mask_31.any() else float('nan'),
        'low_bureau_flag_hp': ula_df.loc[hp_mask_31, 'low_bureau_flag'].mean() if hp_mask_31.any() else float('nan'),
        'open_tl_flag_sp': ula_df.loc[sp_mask_31, 'open_tl_flag'].mean() if sp_mask_31.any() else float('nan'),
        'open_tl_flag_hp': ula_df.loc[hp_mask_31, 'open_tl_flag'].mean() if hp_mask_31.any() else float('nan'),
        'cd_perc_flag_sp': ula_df.loc[sp_mask_31, 'cd_perc_flag'].mean() if sp_mask_31.any() else float('nan'),
        'cd_perc_flag_hp': ula_df.loc[hp_mask_31, 'cd_perc_flag'].mean() if hp_mask_31.any() else float('nan'),
    }

    return ula_df, pd.Series(steps), pd.Series(flags)

In [5]:
mean_unit_loss = MODEL_PARAMS['mean_unit_loss']
unit_loss_to_model_score = MODEL_PARAMS['unit_loss_to_model_score']


def get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config, leave_out='None'):
    """Core RAGU Score calculation for a single vintage and individual LOB."""
    baseline_ltv = baseline_config['ltv']
    new_baseline_recovery_unadjusted_pct = baseline_config['new_recovery_unadjusted']
    baseline_apr = baseline_config['apr']
    ltv_mult = 17 / 0.65 if lob == 'KMX' else 17
    apr_mult = 0.7 / 0.65 if lob == 'KMX' else 0.7

    ula_df = ula_df_total[(ula_df_total.vintage == vintage) & (ula_df_total.lob == lob)].copy()

    if len(ula_df) == 0:
        return None

    if lob == 'KMX':
        ula_df = get_ula_multiplier_kmx(ula_df, leave_out=leave_out)
    else:
        raise ValueError("This notebook only supports KMX")

    ula_df = ula_df[['account_number', date_col, 'bbvalue', 'sale_price', 'amt_financed', 'lob_or_bucket', 'lob', 'loss_multiplier', 'apr']]

    nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(subset='account_number', keep='first')
    mix_df = ula_df.merge(nr.rename(columns={'new_recovery_multiplier': 'recovery_multiplier'}),
                          on='account_number', how='left').drop_duplicates(subset='account_number', keep='first')

    mix_df['ltv'] = mix_df.amt_financed / mix_df.bbvalue

    bb_populated_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0)]
    if len(bb_populated_df) == 0:
        return None

    full_pop_metrics = bb_populated_df.groupby('lob').apply(
        weighted_average_and_sum,
        ['loss_multiplier', 'ltv', 'bbvalue', 'apr'],
        include_groups=False
    )

    recovery_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0) & mix_df['recovery_multiplier'].notna()]
    recovery_df = recovery_df.copy()
    recovery_df['recovery_unadjusted_multiplier'] = recovery_df['recovery_multiplier']
    recovery_metrics = recovery_df.groupby('lob').apply(
        weighted_average_and_sum,
        ['recovery_unadjusted_multiplier'],
        include_groups=False
    )
    recovery_metrics = recovery_metrics.drop(columns='amt_financed')

    grouped_mix_df = full_pop_metrics.join(recovery_metrics)

    vintage_ms_df = ms_df[ms_df['period'] == vintage].copy()

    index_name = grouped_mix_df.index.name
    if isinstance(index_name, str) and index_name in grouped_mix_df.columns:
        grouped_mix_df = grouped_mix_df.reset_index(drop=True)
    else:
        grouped_mix_df = grouped_mix_df.reset_index()

    full_df = grouped_mix_df.merge(vintage_ms_df, on='lob')

    if len(full_df) == 0:
        return None

    full_df['est_unit_loss'] = mean_unit_loss
    full_df['unit_loss_score'] = full_df.model_score + (1 - full_df.loss_multiplier) * full_df.est_unit_loss / unit_loss_to_model_score
    full_df = full_df.set_index('lob')

    full_df['ms_original'] = full_df.model_score.copy()
    full_df['baselined_unadjusted_recovery'] = (full_df.recovery_unadjusted_multiplier / new_baseline_recovery_unadjusted_pct).copy()

    full_df['gross_loss_impact'] = full_df['unit_loss_score'] - full_df['ms_original']
    full_df['recovery_impact'] = (full_df['unit_loss_score'] * full_df['est_unit_loss']
        * full_df['recovery_unadjusted_multiplier'] * (full_df['baselined_unadjusted_recovery'] - 1))
    full_df['ltv_impact'] = ((baseline_ltv / full_df['ltv']) - 1) * ltv_mult
    full_df['apr_impact'] = (baseline_apr - full_df['apr']) / 0.01 * apr_mult
    full_df['ragu_score'] = (
        (1 - full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier) * full_df.unit_loss_score
        + full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier
        * full_df.unit_loss_score * full_df.baselined_unadjusted_recovery
        + full_df['ltv_impact']
        + full_df['apr_impact'])

    full_df['vintage'] = vintage
    return full_df

In [6]:
# Filter out Core LOB
ula_df_total = ula_df_total[ula_df_total.lob != 'Core']

# Ensure date columns are proper types
ula_df_total['app_date'] = pd.to_datetime(ula_df_total['app_date'])
ula_df_total['book_date'] = pd.to_datetime(ula_df_total['book_date'])
new_recovery['app_date'] = pd.to_datetime(new_recovery['app_date'])
new_recovery['book_date'] = pd.to_datetime(new_recovery['book_date'])

# Assign period columns using pd.to_period
for df in [ula_df_total, new_recovery]:
    df['quarter'] = pd.to_datetime(df[date_col]).dt.to_period('Q')
    df['month'] = pd.to_datetime(df[date_col]).dt.to_period('M')
    df['week'] = pd.to_datetime(df[date_col]).dt.to_period('W-SAT')
    period_key = {'q': 'quarter', 'm': 'month', 'w': 'week'}
    df['period'] = df[period_key[granularity]]

# Filter to configured date range
for df in [ula_df_total, new_recovery]:
    mask = (df['period'] >= start_period) & (df['period'] <= end_period)
    df.drop(df[~mask].index, inplace=True)

# Convert week columns to str for compatibility
for df in [ula_df_total, new_recovery]:
    df['book_week'] = df['book_week'].astype(str)
    df['app_week'] = df['app_week'].astype(str)

# String version of date_col for flag comparisons
date_col_str = f'{date_col}_str'
ula_df_total[date_col_str] = ula_df_total[date_col].astype(str)

ula_df_total['mtn_3_1_flag'] = ula_df_total.mtn_model == 'MTN3.1'
ula_df_total['vehicle_age'] = np.maximum(ula_df_total[date_col_str].str[:4].astype(int) - ula_df_total.model_year, 1/365)
ula_df_total.tradein_value = ula_df_total.tradein_value.fillna(0)
ula_df_total.make = ula_df_total.make.str.upper().str[:3]
ula_df_total.lob_or_bucket = np.select([ula_df_total.lob_or_bucket.isna() & ula_df_total.lob.isin(['Core', 'FRN']),
                                      ula_df_total.lob_or_bucket.isna() & ~ula_df_total.lob.isin(['Core', 'FRN'])],
                                     ['D', 'C'], default=ula_df_total.lob_or_bucket)
ula_df_total['continuous_vehicle_age'] = (ula_df_total[date_col_str].str[:4].astype(int)
    + ula_df_total[date_col_str].str[5:7].astype(int) / 12
    - (ula_df_total.model_year - 0.25) - 1)

# Driver flag
warnings.filterwarnings('ignore', category=UserWarning)
ula_df_total.job_company = ula_df_total.job_company.fillna('not provided')
ula_df_total['driver_flag'] = np.where(
    ula_df_total.job_company.str.contains('(LYFT)|(UBER)|(GRUB ?HUB)|(DOOR ?DASH)|(GO ?PUFF)|(POST ?MATE)|(INSTA ?CART)|(DOMINO)|(PAPA J)|(PIZZA)|(JIMMY ?JOHN)|(SELF)'),
    1, 0)
warnings.filterwarnings('default', category=UserWarning)

# Handle NA values
ula_df_total = ula_df_total.dropna(subset=['sale_price', 'cd_model_score', 'pti', 'lob'])
ula_df_total.cash_down = ula_df_total.cash_down.fillna(0)
ula_df_total.specialty_dealer = ula_df_total.specialty_dealer.fillna('not specialty')
ula_df_total.prev_co_count = ula_df_total.prev_co_count.fillna(0)

# Weekly-matching filters
ula_df_total['bbltv'] = ula_df_total.amt_financed / ula_df_total.bbvalue.replace(0, np.nan)
ula_df_total = ula_df_total[ula_df_total.amt_financed <= 75000]
ula_df_total = ula_df_total[ula_df_total.pti <= 0.6]
ula_df_total = ula_df_total[
    (ula_df_total.lob == 'MCY') |
    (ula_df_total.bbltv <= 10.0) |
    (ula_df_total.bbvalue.isna()) |
    (ula_df_total.bbvalue == 0)
]
ula_df_total = ula_df_total[ula_df_total.total_income <= 200000]

# KMX Flags
ula_df_total['secured_credit_flag'] = ula_df_total.secured_credit_card
ula_df_total['chime_flag'] = ula_df_total.chime_indicator
ula_df_total['seasonal_employment_flag'] = ula_df_total['seasonal_employment_flag'] == 1
ula_df_total['waiter_employment_flag'] = ula_df_total['waiter_employment_flag'] == 1
ula_df_total['null_fico_w_vantage_flag'] = ((ula_df_total.fico_score < 300) | (ula_df_total.fico_score > 850)) & (ula_df_total.vantage_score >= 300) & (ula_df_total.vantage_score <= 850)
ula_df_total['null_fico_null_vantage_flag'] = ((ula_df_total.fico_score < 300) | (ula_df_total.fico_score > 850)) & ((ula_df_total.vantage_score < 300) | (ula_df_total.vantage_score > 850))
ula_df_total['student_loan_flag'] = np.where(ula_df_total.student_loan_flag == 1, 1, 0)
ula_df_total['high_sales_price_flag'] = ula_df_total.sale_price > 30000
ula_df_total['kmx_npc_flag'] = ula_df_total.kmx_npc_flag == 1
ula_df_total['high_pti_npc'] = ula_df_total.pti > 0.2
ula_df_total['job_time_flag'] = ula_df_total.employed_months < 6
ula_df_total['low_fico_flag'] = (ula_df_total.fico_score > 300) & (ula_df_total.fico_score < 450)
ula_df_total['high_model_score_flag'] = ula_df_total.cd_model_score >= 146
ula_df_total['low_vantage_flag'] = (ula_df_total.fico_score < 300) & (ula_df_total.vantage_score > 4) & (ula_df_total.vantage_score < 450)
ula_df_total['louisiana_flag'] = ula_df_total.state == 'LA'
ula_df_total['txca_flag'] = ula_df_total.state.isin(['TX', 'CA'])
ula_df_total['georgia_flag'] = ula_df_total.state == 'GA'
ula_df_total['normal_pti_flag'] = ula_df_total.pti <= 0.2
ula_df_total['high_pti_tier_1_flag'] = (ula_df_total.pti > 0.2) & (ula_df_total.pti <= 0.25)
ula_df_total['high_pti_tier_2_flag'] = (ula_df_total.pti > 0.25) & (ula_df_total.pti <= 0.35)
ula_df_total['high_pti_tier_3_flag'] = ula_df_total.pti > 0.35
ula_df_total['existing_dq_flag'] = ula_df_total.existing_dq_count > 0
ula_df_total['kmx_toyho_flag'] = (ula_df_total.cd_model_score >= 130) & ula_df_total.make.isin({'HON', 'TOY'})
ula_df_total['kmx_auth_tradelines_flag'] = ula_df_total.pct_auth_tradelines >= 0.14
ula_df_total['low_bureau_flag'] = ((ula_df_total.fico_score > 300) & (ula_df_total.fico_score < 475)) | ((ula_df_total.vantage_score > 4) & (ula_df_total.vantage_score < 475))
ula_df_total['soft_pull_flag'] = ula_df_total.pull_type.isin(['softpull', 'prequal'])
ula_df_total['cd_perc_flag'] = (ula_df_total.sale_price <= 18000) & (ula_df_total.cash_down / ula_df_total.sale_price <= 0.1)
ula_df_total['open_tl_flag'] = ula_df_total.open_tl == 0
ula_df_total['narrowed_soft_pull_flag'] = (ula_df_total.sale_price <= 18000) & (ula_df_total.cash_down / ula_df_total.sale_price <= 0.1) & ula_df_total.soft_pull_flag & (~ula_df_total.job_time_flag)
ula_df_total['prev_co_flag'] = ula_df_total.prev_co_count > 0

# Deduplicate driver flags
combined_driver_flag_df = ula_df_total.groupby('account_number').driver_flag.max().reset_index()
ula_df_total = ula_df_total.drop(columns='driver_flag').merge(combined_driver_flag_df, on='account_number')
ula_df_total = ula_df_total.drop(columns='job_company').drop_duplicates()

# Vintage assignment
ula_df_total['vintage'] = format_vintage(ula_df_total['period'])
new_recovery['vintage'] = format_vintage(new_recovery['period'])

# Filter to KMX only
ula_df_total = ula_df_total[ula_df_total.lob == 'KMX'].copy()
new_recovery = new_recovery[new_recovery.lob == 'KMX'].copy()

# MTN 4.1 model score transformation (applied in-place to ULA source)
is_mtn41 = ula_df_total.mtn_model == 4.1
ula_df_total.loc[is_mtn41, 'cd_model_score'] = (
    142 + (ula_df_total.loc[is_mtn41, 'cd_model_score'] - 142) * 1.5
)

# Aggregate model scores from ULA data (same source as ltv/apr)
ms_df = ula_df_total.groupby(['period', 'lob']).apply(
    weighted_average_and_sum, 'cd_model_score', include_groups=False
).reset_index()
ms_df = ms_df.rename(columns={'cd_model_score': 'model_score'})
ms_df['period'] = format_vintage(ms_df['period'])

print(f'Data loaded: {len(ula_df_total)} ULA rows')
print(f'MTN model distribution:\n{ula_df_total.mtn_model.value_counts().sort_index()}')
print(f'ms_df: {len(ms_df)} rows')
print(f'Available KMX vintages: {sorted(ula_df_total.vintage.unique())}')

Data loaded: 222183 ULA rows
MTN model distribution:
mtn_model
3.0    132720
3.1     51883
3.2     29746
4.1      7834
Name: count, dtype: int64
ms_df: 15 rows
Available KMX vintages: ['2023 Q1', '2023 Q2', '2023 Q3', '2023 Q4', '2024 Q1', '2024 Q2', '2024 Q3', '2024 Q4', '2025 Q1', '2025 Q2', '2025 Q3', '2025 Q4', '2026 Q1', '2026 Q2', '2026 Q3']

In [7]:
baseline_config = BASELINES['KMX']

results_by_model = {}

all_vintages = sorted(ula_df_total['vintage'].unique())

for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    print(f'\n{"="*60}')
    print(f'  Processing: {label}')
    print(f'{"="*60}')

    # Filter DataFrames by MTN model
    if mtn_model_filter == 'All KMX':
        ula_filtered = ula_df_total.copy()
        new_rec_filtered = new_recovery.copy()
        ms_filtered = ms_df.copy()
    else:
        mtn_accounts = set(ula_df_total[ula_df_total.mtn_model == mtn_model_filter].account_number)
        ula_filtered = ula_df_total[ula_df_total.mtn_model == mtn_model_filter].copy()
        new_rec_filtered = new_recovery[new_recovery.account_number.isin(mtn_accounts)].copy()
        ms_filtered = rebuild_ms_df(ula_filtered)

    n_loans = len(ula_filtered)
    if n_loans == 0:
        print(f'  No loans found for {label}, skipping.')
        results_by_model[mtn_model_filter] = pd.DataFrame()
        continue

    print(f'  Loans: {n_loans}')

    full_df_list = []
    vintages_processed = []

    for vintage in all_vintages:
        n_vintage = len(ula_filtered[ula_filtered.vintage == vintage])
        if n_vintage == 0:
            continue

        print(f'  {vintage} KMX ({label}, n={n_vintage})')
        full_df = get_ragu_score(vintage, 'KMX', ula_filtered, new_rec_filtered, ms_filtered, baseline_config)
        if full_df is not None:
            full_df_list.append(full_df)
            vintages_processed.append(vintage)

    if full_df_list:
        all_df = pd.concat(full_df_list)
        results_by_model[mtn_model_filter] = all_df
        print(f'\n  {label}: {len(vintages_processed)} vintages processed')
    else:
        results_by_model[mtn_model_filter] = pd.DataFrame()
        print(f'\n  {label}: No vintages had data')

print(f'\n{"="*60}')
print('  All models processed.')
print(f'{"="*60}')
print("[PROGRESS] Scoring Complete")

============================================================
  Processing: MTN 3.0
============================================================
  Loans: 132720
  2023 Q1 KMX (MTN 3.0, n=14355)
  2023 Q2 KMX (MTN 3.0, n=12711)
  2023 Q3 KMX (MTN 3.0, n=12892)
  2023 Q4 KMX (MTN 3.0, n=10521)
  2024 Q1 KMX (MTN 3.0, n=18128)
  2024 Q2 KMX (MTN 3.0, n=13833)
  2024 Q3 KMX (MTN 3.0, n=12991)
  2024 Q4 KMX (MTN 3.0, n=8929)
  2025 Q1 KMX (MTN 3.0, n=8813)
  2025 Q2 KMX (MTN 3.0, n=7452)
  2025 Q3 KMX (MTN 3.0, n=7250)
  2025 Q4 KMX (MTN 3.0, n=4799)
  2026 Q3 KMX (MTN 3.0, n=46)

  MTN 3.0: 13 vintages processed

============================================================
  Processing: MTN 3.1
============================================================
  Loans: 51883
  2024 Q4 KMX (MTN 3.1, n=3231)
  2025 Q1 KMX (MTN 3.1, n=9947)
  2025 Q2 KMX (MTN 3.1, n=8172)
  2025 Q3 KMX (MTN 3.1, n=8190)
  2025 Q4 KMX (MTN 3.1, n=8612)
  2026 Q1 KMX (MTN 3.1, n=13018)
  2026 Q2 KMX (MTN 3.1, n=713)

  MTN 3.1: 7 vintages processed

============================================================
  Processing: MTN 3.2
============================================================
  Loans: 29746
  2026 Q1 KMX (MTN 3.2, n=7451)
  2026 Q2 KMX (MTN 3.2, n=14603)
  2026 Q3 KMX (MTN 3.2, n=7692)

  MTN 3.2: 3 vintages processed

============================================================
  Processing: MTN 4.1
============================================================
  Loans: 7834
  2025 Q4 KMX (MTN 4.1, n=218)
  2026 Q1 KMX (MTN 4.1, n=2505)
  2026 Q2 KMX (MTN 4.1, n=3041)
  2026 Q3 KMX (MTN 4.1, n=2070)

  MTN 4.1: 4 vintages processed

============================================================
  Processing: All KMX
============================================================
  Loans: 222183
  2023 Q1 KMX (All KMX, n=14355)
  2023 Q2 KMX (All KMX, n=12711)
  2023 Q3 KMX (All KMX, n=12892)
  2023 Q4 KMX (All KMX, n=10521)
  2024 Q1 KMX (All KMX, n=18128)
  2024 Q2 KMX (All KMX, n=13833)
  2024 Q3 KMX (All KMX, n=12991)
  2024 Q4 KMX (All KMX, n=12160)
  2025 Q1 KMX (All KMX, n=18760)
  2025 Q2 KMX (All KMX, n=15624)
  2025 Q3 KMX (All KMX, n=15440)
  2025 Q4 KMX (All KMX, n=13629)
  2026 Q1 KMX (All KMX, n=22974)
  2026 Q2 KMX (All KMX, n=18357)
  2026 Q3 KMX (All KMX, n=9808)

  All KMX: 15 vintages processed

============================================================
  All models processed.
============================================================
[PROGRESS] Scoring Complete

In [8]:
"""
Diagnostics: Run get_ula_multiplier_kmx_diag for each MTN model and for All KMX combined.
Produces step-by-step loss_multiplier traces and flag means per vintage.
"""

def build_output_df(results, wtd_mults, record_counts, ragu_gli_dict=None):
    """Helper to build multiplier steps and summary DataFrame."""
    if not results:
        return None
    step_names = list(next(iter(results.values())).keys())
    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        col_data[col_name] = [step_dict.get(s) for s in step_names]
    diag_df = pd.DataFrame(col_data, index=step_names)
    summary = {}
    for (lob, vintage) in results.keys():
        col = f"{lob} | {vintage}"
        final_mult_mean = diag_df[col].iloc[-1]
        wtd_mult = wtd_mults.get((lob, vintage), float('nan'))
        if ragu_gli_dict is not None:
            gross_loss_impact = ragu_gli_dict.get((lob, vintage), 25 * (1 - wtd_mult))
        else:
            gross_loss_impact = 25 * (1 - wtd_mult)
        summary[col] = {
            '--- FINAL_MULT (mean)': final_mult_mean,
            '--- WTD_MULT_RAGU': wtd_mult,
            '--- GROSS_LOSS_IMPACT': gross_loss_impact,
            '--- N_RECORDS': record_counts.get((lob, vintage), 0),
        }
    summary_df = pd.DataFrame(summary)
    return pd.concat([diag_df, summary_df])

def build_flags_df(flag_results, record_counts):
    """Helper to build flag means DataFrame."""
    if not flag_results:
        return None
    flag_names = list(next(iter(flag_results.values())).keys())
    flag_col_data = {}
    for (lob, vintage), flag_dict in flag_results.items():
        col_name = f"{lob} | {vintage}"
        flag_col_data[col_name] = [flag_dict.get(f) for f in flag_names]
    flags_df = pd.DataFrame(flag_col_data, index=flag_names)
    n_row = {}
    for (lob, vintage) in flag_results.keys():
        n_row[f"{lob} | {vintage}"] = record_counts.get((lob, vintage), 0)
    flags_df.loc['--- N_RECORDS'] = n_row
    return flags_df


STEP_LABEL_MAP = {
    '00_initial':              'Initial (1.0)',
    '02_low_fico_3.0':         'Low FICO (3.0)',
    '03_low_vantage_3.0':      'Low Vantage (3.0)',
    '04_high_pti_3.0':         'High PTI (3.0)',
    '07_loss_scale_div_3.0':   'Loss Scale Div (3.0)',
    '08_secured_credit_3.0':   'Secured Credit (3.0)',
    '09_auth_tradelines_3.0':  'Auth Tradelines (3.0)',
    '11_soft_pull_3.0':        'Soft Pull (3.0)',
    '12_fraud_all':            'Fraud Adjustment',
    '13_clip_3.0':             'Clip (3.0)',
    '14_vehicle_age_3.0':      'Vehicle Age (3.0)',
    '15_npc_all':              'NPC',
    '16_student_loans_all':    'Student Loans',
    '17_high_sales_price_4.1': 'High Sales Price (4.1)',
    '18_driver_flag_all':      'Driver Flag',
    '19_louisiana_all':        'Louisiana',
    '20_georgia_all':          'Georgia',
    '21_txca_all':             'TX / CA',
    '22_state_counter_all':    'State Counter',
    '23_secured_credit_3.1+':  'Secured Credit / Chime (3.1+)',
    '24_job_time_3.1+':        'Job Time (3.1+)',
    '25_existing_dq_3.1+':     'Existing DQ (3.1+)',
    '26_employment_3.1+':      'Employment Type (3.1+)',
    '27_auth_tradelines_3.1+': 'Auth Tradelines (3.1+)',
    '28a_sp_low_bureau_3.1+':   'Low Bureau (SP, 3.1+)',
    '28b_sp_open_tl_3.1+':     'Open TL (SP, 3.1+)',
    '28c_hp_low_bureau_3.1+':  'Low Bureau (HP, 3.1+)',
    '28d_hp_open_tl_3.1+':     'Open TL (HP, 3.1+)',
    '28e_hp_interaction_3.1+': 'HP Interaction (3.1+)',
    '28f_sp_cd_perc_3.1/3.2':  'CD Perc (SP, 3.1/3.2)',
    '28g_hp_cd_perc_3.1/3.2':  'CD Perc (HP, 3.1/3.2)',
    '28h_sp_cd_perc_4.1':      'CD Perc (SP, 4.1)',
    '28i_hp_cd_perc_4.1':      'CD Perc (HP, 4.1)',
    '28j_blanket_hp_3.1+':     'Blanket Adjustment (HP, 3.1+)',
    '29_final_clip_3.1+':      'Clip (3.1+)',
}


def build_attribution_df(results, ragu_gli_dict):
    """
    Decompose gross_loss_impact across multiplier steps using logarithmic attribution.

    For each vintage:
      1. Compute per-step ratios: r_i = step_i / step_{i-1}
      2. Log shares: ln(r_i) / ln(final_multiplier)  [proportional contribution]
      3. Derive equal-weighted GLI from the diagnostic chain: 25 * (1 - final_mult)
      4. Attributed impact: share_i * diag_gli
      5. Population Weighting row: ragu_gli - subtotal (bridges equal-weighted
         to the amount-financed-weighted RAGU GLI)

    Step attributions use the diagnostic chain's own final multiplier so that
    signs are always consistent: reducing the multiplier yields positive
    attribution (lower mult -> higher GLI -> higher RAGU score).

    The Population Weighting row captures the effect of dollar-weighting and
    bb-population filtering.  The TOTAL row matches the RAGU GLI exactly.
    """
    if not results:
        return None

    step_keys = list(next(iter(results.values())).keys())
    adjustment_keys = [k for k in step_keys if k != '00_initial']
    readable_labels = [STEP_LABEL_MAP.get(k, k) for k in adjustment_keys]

    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        ragu_gli = ragu_gli_dict.get((lob, vintage), float('nan'))

        cumulative = [step_dict.get(k, float('nan')) for k in step_keys]
        ratios = []
        for i, k in enumerate(step_keys):
            if k == '00_initial':
                continue
            prev = cumulative[i - 1]
            curr = cumulative[i]
            if prev and prev != 0:
                ratios.append(curr / prev)
            else:
                ratios.append(1.0)

        import math
        final_mult = cumulative[-1]
        log_final = math.log(final_mult) if final_mult and final_mult > 0 and abs(final_mult - 1.0) > 1e-12 else None
        diag_gli = 25.0 * (1.0 - final_mult) if final_mult and not pd.isna(final_mult) else 0.0

        ragu_gli_val = ragu_gli if not pd.isna(ragu_gli) else 0.0
        if log_final is None:
            weighting_adj = ragu_gli_val - diag_gli
            col_data[col_name] = [0.0] * len(adjustment_keys) + [weighting_adj, ragu_gli_val]
        else:
            log_ratios = [math.log(r) if r and r > 0 else 0.0 for r in ratios]
            attributed = [(lr / log_final) * diag_gli for lr in log_ratios]
            weighting_adj = ragu_gli_val - sum(attributed)
            col_data[col_name] = attributed + [weighting_adj, ragu_gli_val]

    index_labels = readable_labels + ['--- Population Weighting', '--- TOTAL (RAGU GLI)']
    return pd.DataFrame(col_data, index=index_labels)

diag_results_by_model = {}

for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    
    if mtn_model_filter == 'All KMX':
        ula_diag_source = ula_df_total.copy()
    else:
        ula_diag_source = ula_df_total[ula_df_total.mtn_model == mtn_model_filter].copy()
    
    if len(ula_diag_source) == 0:
        print(f'\n{label}: No data for diagnostics, skipping.')
        diag_results_by_model[mtn_model_filter] = (None, None, None)
        continue
    
    # Build ragu_gli_dict from results_by_model for this MTN model
    ragu_gli_dict = {}
    model_df = results_by_model.get(mtn_model_filter)
    if model_df is not None and len(model_df) > 0:
        for _, row in model_df.reset_index().iterrows():
            ragu_gli_dict[('KMX', row['vintage'])] = row['gross_loss_impact']
    
    # Get all vintages for diagnostics
    target_vintages = sorted(ula_diag_source.vintage.unique())
    
    kmx_results = {}
    kmx_flag_results = {}
    kmx_wtd_mults = {}
    kmx_record_counts = {}
    
    print(f'\n{"="*60}')
    print(f'  DIAGNOSTICS: {label}')
    print(f'{"="*60}')
    
    for vintage in target_vintages:
        ula_vintage = ula_diag_source[ula_diag_source.vintage == vintage].copy()
        n = len(ula_vintage)
        if n == 0:
            continue
        
        print(f'\n{"="*60}')
        print(f'  KMX {vintage} ({label})  (n={n})')
        print(f'{"="*60}')
        
        ula_vintage_diag, steps, flags = get_ula_multiplier_kmx_diag(ula_vintage, loss_scale=MODEL_PARAMS['kmx_loss_scale'], leave_out='None', verbose=True)
        
        diag_mix = ula_vintage_diag[['account_number', 'bbvalue', 'amt_financed', 'loss_multiplier']].copy()
        nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(
            subset='account_number', keep='first')
        diag_mix = diag_mix.merge(nr, on='account_number', how='left').drop_duplicates(
            subset='account_number', keep='first')
        bb_pop = diag_mix[diag_mix['bbvalue'].notna() & (diag_mix['bbvalue'] > 0)]
        if len(bb_pop) > 0 and bb_pop.amt_financed.sum() > 0:
            wtd_mult = (bb_pop.loss_multiplier * bb_pop.amt_financed).sum() / bb_pop.amt_financed.sum()
        else:
            wtd_mult = float('nan')
        
        ragu_gli = ragu_gli_dict.get(('KMX', vintage), float('nan'))
        print(f"  bb_populated: {len(bb_pop)} / {n}  wtd_mult: {wtd_mult:.6f}  ragu_gli: {ragu_gli:.4f}")
        
        kmx_results[('KMX', vintage)] = steps.to_dict()
        kmx_flag_results[('KMX', vintage)] = flags.to_dict()
        kmx_wtd_mults[('KMX', vintage)] = wtd_mult
        kmx_record_counts[('KMX', vintage)] = n
    
    kmx_output_df = build_output_df(kmx_results, kmx_wtd_mults, kmx_record_counts, ragu_gli_dict)
    kmx_flags_df = build_flags_df(kmx_flag_results, kmx_record_counts)
    kmx_attribution_df = build_attribution_df(kmx_results, ragu_gli_dict)
    diag_results_by_model[mtn_model_filter] = (kmx_output_df, kmx_flags_df, kmx_attribution_df)

    if kmx_output_df is not None:
        print(f'\n--- {label} Multiplier Steps ---')
        display(kmx_output_df)
        print(f'\n--- {label} Flag Means ---')
        display(kmx_flags_df)
    if kmx_attribution_df is not None:
        print(f'\n--- {label} Gross Loss Attribution ---')
        display(kmx_attribution_df)

============================================================
  DIAGNOSTICS: MTN 3.0
============================================================

============================================================
  KMX 2023 Q1 (MTN 3.0)  (n=14355)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.082132  | loss_multiplier mean: 1.019539
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.019539
04_high_pti | tier1: 0.099060  tier2: 0.047092  tier3: 0.003622  | loss_multiplier mean: 1.031056
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.966313
08_sec_cred | flag mean: 0.182375  | loss_multiplier mean: 0.966580
09_auth_tl  | flag mean: 0.039429  | loss_multiplier mean: 0.963798
11_soft_pll | flag mean: 0.635040  narrowed: 0.099060  | loss_multiplier mean: 0.940376
12_fraud    | fraud_adj mean: 1.003439  | loss_multiplier mean: 0.943189
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.941898
14_veh_age  | continuous_age mean: 6.565430  | loss_multiplier mean: 0.934088
15_npc      | npc_flag mean: 0.641519  high_pti_npc mean: 0.149774  | loss_multiplier mean: 0.938013
16_stu_loan | flag mean: 0.042076  | loss_multiplier mean: 0.905938
17_hi_price | flag mean: 0.081574  | loss_multiplier mean: 0.905938
18_driver   | flag mean: 0.008638  | loss_multiplier mean: 0.907121
19_louisiana| flag mean: 0.009822  | loss_multiplier mean: 0.910278
20_georgia  | flag mean: 0.097388  | loss_multiplier mean: 0.919294
21_txca     | flag mean: 0.277255  | loss_multiplier mean: 0.904945
22_st_cntr  | no state adj: 0.615535  | loss_multiplier mean: 0.910862
23_sec_cr31 | chime mean: 0.179519  | loss_multiplier mean: 0.935816
24_job_t_31 | flag mean: 0.246883  | loss_multiplier mean: 0.977190
25_dq_31    | flag mean: 0.084291  | loss_multiplier mean: 0.976281
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.976281
27_auth_31  | flag mean: 0.039429  | loss_multiplier mean: 0.976281
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.976281
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.976281
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.976281
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.976281
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.976281
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.976281
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.976281
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.976281
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.976281
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.976281
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.976281

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.976281  (n=14355)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 12624 / 14355  wtd_mult: 0.956887  ragu_gli: 1.0778

============================================================
  KMX 2023 Q2 (MTN 3.0)  (n=12711)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.061600  | loss_multiplier mean: 1.014565
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.014565
04_high_pti | tier1: 0.104319  tier2: 0.042247  tier3: 0.004878  | loss_multiplier mean: 1.026466
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.962011
08_sec_cred | flag mean: 0.253167  | loss_multiplier mean: 0.965348
09_auth_tl  | flag mean: 0.046023  | loss_multiplier mean: 0.963671
11_soft_pll | flag mean: 0.655338  narrowed: 0.118795  | loss_multiplier mean: 0.941918
12_fraud    | fraud_adj mean: 1.003718  | loss_multiplier mean: 0.945137
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.943470
14_veh_age  | continuous_age mean: 6.538267  | loss_multiplier mean: 0.935178
15_npc      | npc_flag mean: 0.638738  high_pti_npc mean: 0.151444  | loss_multiplier mean: 0.939283
16_stu_loan | flag mean: 0.051215  | loss_multiplier mean: 0.908314
17_hi_price | flag mean: 0.122335  | loss_multiplier mean: 0.908314
18_driver   | flag mean: 0.009126  | loss_multiplier mean: 0.909531
19_louisiana| flag mean: 0.009126  | loss_multiplier mean: 0.912457
20_georgia  | flag mean: 0.096216  | loss_multiplier mean: 0.921457
21_txca     | flag mean: 0.268508  | loss_multiplier mean: 0.906401
22_st_cntr  | no state adj: 0.626151  | loss_multiplier mean: 0.912323
23_sec_cr31 | chime mean: 0.168515  | loss_multiplier mean: 0.934826
24_job_t_31 | flag mean: 0.227519  | loss_multiplier mean: 0.972689
25_dq_31    | flag mean: 0.073716  | loss_multiplier mean: 0.970635
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.970635
27_auth_31  | flag mean: 0.046023  | loss_multiplier mean: 0.970635
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.970635
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.970635
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.970635
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.970635
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.970635
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.970635
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.970635
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.970635
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.970635
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.970635
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.970635

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.970635  (n=12711)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 11597 / 12711  wtd_mult: 0.948335  ragu_gli: 1.2916

============================================================
  KMX 2023 Q3 (MTN 3.0)  (n=12892)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.052280  | loss_multiplier mean: 1.012375
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.012375
04_high_pti | tier1: 0.111154  tier2: 0.046385  tier3: 0.005197  | loss_multiplier mean: 1.025155
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.960783
08_sec_cred | flag mean: 0.241390  | loss_multiplier mean: 0.963220
09_auth_tl  | flag mean: 0.049410  | loss_multiplier mean: 0.962134
11_soft_pll | flag mean: 0.685386  narrowed: 0.134657  | loss_multiplier mean: 0.939997
12_fraud    | fraud_adj mean: 1.003496  | loss_multiplier mean: 0.943049
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.941399
14_veh_age  | continuous_age mean: 6.554944  | loss_multiplier mean: 0.933347
15_npc      | npc_flag mean: 0.634735  high_pti_npc mean: 0.162737  | loss_multiplier mean: 0.938359
16_stu_loan | flag mean: 0.023193  | loss_multiplier mean: 0.903832
17_hi_price | flag mean: 0.122014  | loss_multiplier mean: 0.903832
18_driver   | flag mean: 0.009696  | loss_multiplier mean: 0.905136
19_louisiana| flag mean: 0.008688  | loss_multiplier mean: 0.907902
20_georgia  | flag mean: 0.106655  | loss_multiplier mean: 0.917642
21_txca     | flag mean: 0.266056  | loss_multiplier mean: 0.902651
22_st_cntr  | no state adj: 0.618601  | loss_multiplier mean: 0.908509
23_sec_cr31 | chime mean: 0.155911  | loss_multiplier mean: 0.926275
24_job_t_31 | flag mean: 0.235805  | loss_multiplier mean: 0.965305
25_dq_31    | flag mean: 0.068647  | loss_multiplier mean: 0.962555
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.962555
27_auth_31  | flag mean: 0.049410  | loss_multiplier mean: 0.962555
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.962555
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.962555
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.962555
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.962555
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.962555
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.962555
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.962555
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.962555
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.962555
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.962555
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.962555

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.962555  (n=12892)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 6455 / 12892  wtd_mult: 0.941626  ragu_gli: 1.4594

============================================================
  KMX 2023 Q4 (MTN 3.0)  (n=10521)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.048379  | loss_multiplier mean: 1.010877
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.010877
04_high_pti | tier1: 0.101796  tier2: 0.055508  tier3: 0.006558  | loss_multiplier mean: 1.024821
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.960470
08_sec_cred | flag mean: 0.228781  | loss_multiplier mean: 0.962390
09_auth_tl  | flag mean: 0.043342  | loss_multiplier mean: 0.960322
11_soft_pll | flag mean: 0.703640  narrowed: 0.133637  | loss_multiplier mean: 0.937221
12_fraud    | fraud_adj mean: 1.003709  | loss_multiplier mean: 0.940616
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.938917
14_veh_age  | continuous_age mean: 6.162453  | loss_multiplier mean: 0.923440
15_npc      | npc_flag mean: 0.627222  high_pti_npc mean: 0.163863  | loss_multiplier mean: 0.927403
16_stu_loan | flag mean: 0.036689  | loss_multiplier mean: 0.894829
17_hi_price | flag mean: 0.118905  | loss_multiplier mean: 0.894829
18_driver   | flag mean: 0.008079  | loss_multiplier mean: 0.895965
19_louisiana| flag mean: 0.008744  | loss_multiplier mean: 0.898652
20_georgia  | flag mean: 0.098185  | loss_multiplier mean: 0.907540
21_txca     | flag mean: 0.260241  | loss_multiplier mean: 0.892781
22_st_cntr  | no state adj: 0.632830  | loss_multiplier mean: 0.898701
23_sec_cr31 | chime mean: 0.151316  | loss_multiplier mean: 0.914987
24_job_t_31 | flag mean: 0.224693  | loss_multiplier mean: 0.951809
25_dq_31    | flag mean: 0.070145  | loss_multiplier mean: 0.949285
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.949285
27_auth_31  | flag mean: 0.043342  | loss_multiplier mean: 0.949285
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.949285
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.949285
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.949285
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.949285
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.949285
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.949285
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.949285
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.949285
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.949285
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.949285
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.949285

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.949285  (n=10521)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 5463 / 10521  wtd_mult: 0.931097  ragu_gli: 1.7226

============================================================
  KMX 2024 Q1 (MTN 3.0)  (n=18128)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.039331  | loss_multiplier mean: 1.008490
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.008490
04_high_pti | tier1: 0.081973  tier2: 0.044572  tier3: 0.003199  | loss_multiplier mean: 1.018635
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.954672
08_sec_cred | flag mean: 0.275044  | loss_multiplier mean: 0.959284
09_auth_tl  | flag mean: 0.032988  | loss_multiplier mean: 0.955397
11_soft_pll | flag mean: 0.750386  narrowed: 0.133936  | loss_multiplier mean: 0.931381
12_fraud    | fraud_adj mean: 0.992429  | loss_multiplier mean: 0.924281
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.923856
14_veh_age  | continuous_age mean: 6.131413  | loss_multiplier mean: 0.908135
15_npc      | npc_flag mean: 0.655174  high_pti_npc mean: 0.129744  | loss_multiplier mean: 0.910838
16_stu_loan | flag mean: 0.275485  | loss_multiplier mean: 0.908330
17_hi_price | flag mean: 0.085724  | loss_multiplier mean: 0.908330
18_driver   | flag mean: 0.005902  | loss_multiplier mean: 0.909122
19_louisiana| flag mean: 0.008385  | loss_multiplier mean: 0.911850
20_georgia  | flag mean: 0.097529  | loss_multiplier mean: 0.920952
21_txca     | flag mean: 0.271955  | loss_multiplier mean: 0.905966
22_st_cntr  | no state adj: 0.622132  | loss_multiplier mean: 0.912122
23_sec_cr31 | chime mean: 0.202560  | loss_multiplier mean: 0.944090
24_job_t_31 | flag mean: 0.186176  | loss_multiplier mean: 0.973827
25_dq_31    | flag mean: 0.081311  | loss_multiplier mean: 0.972452
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.972452
27_auth_31  | flag mean: 0.032988  | loss_multiplier mean: 0.972452
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.972452
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.972452
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.972452
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.972452
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.972452
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.972452
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.972452
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.972452
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.972452
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.972452
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.972452

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.972452  (n=18128)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 18120 / 18128  wtd_mult: 0.949570  ragu_gli: 1.2608

============================================================
  KMX 2024 Q2 (MTN 3.0)  (n=13833)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.032242  | loss_multiplier mean: 1.006261
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.006261
04_high_pti | tier1: 0.081544  tier2: 0.047857  tier3: 0.005494  | loss_multiplier mean: 1.017855
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.953941
08_sec_cred | flag mean: 0.262055  | loss_multiplier mean: 0.958631
09_auth_tl  | flag mean: 0.039615  | loss_multiplier mean: 0.955863
11_soft_pll | flag mean: 0.748139  narrowed: 0.086749  | loss_multiplier mean: 0.931932
12_fraud    | fraud_adj mean: 0.989544  | loss_multiplier mean: 0.922186
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.921131
14_veh_age  | continuous_age mean: 5.257518  | loss_multiplier mean: 0.889292
15_npc      | npc_flag mean: 0.646787  high_pti_npc mean: 0.134895  | loss_multiplier mean: 0.892668
16_stu_loan | flag mean: 0.260609  | loss_multiplier mean: 0.888273
17_hi_price | flag mean: 0.125786  | loss_multiplier mean: 0.888273
18_driver   | flag mean: 0.005060  | loss_multiplier mean: 0.888973
19_louisiana| flag mean: 0.008892  | loss_multiplier mean: 0.891803
20_georgia  | flag mean: 0.096291  | loss_multiplier mean: 0.900581
21_txca     | flag mean: 0.276224  | loss_multiplier mean: 0.883894
22_st_cntr  | no state adj: 0.618593  | loss_multiplier mean: 0.889714
23_sec_cr31 | chime mean: 0.180800  | loss_multiplier mean: 0.914276
24_job_t_31 | flag mean: 0.163233  | loss_multiplier mean: 0.938786
25_dq_31    | flag mean: 0.080026  | loss_multiplier mean: 0.937249
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.937249
27_auth_31  | flag mean: 0.039615  | loss_multiplier mean: 0.937249
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.937249
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.937249
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.937249
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.937249
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.937249
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.937249
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.937249
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.937249
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.937249
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.937249
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.937249

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.937249  (n=13833)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 13831 / 13833  wtd_mult: 0.912917  ragu_gli: 2.1771

============================================================
  KMX 2024 Q3 (MTN 3.0)  (n=12991)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.029559  | loss_multiplier mean: 1.005939
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.005939
04_high_pti | tier1: 0.077900  tier2: 0.046263  tier3: 0.005465  | loss_multiplier mean: 1.017173
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.953302
08_sec_cred | flag mean: 0.267108  | loss_multiplier mean: 0.958222
09_auth_tl  | flag mean: 0.040028  | loss_multiplier mean: 0.955562
11_soft_pll | flag mean: 0.755908  narrowed: 0.100377  | loss_multiplier mean: 0.931227
12_fraud    | fraud_adj mean: 0.995378  | loss_multiplier mean: 0.926978
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.925740
14_veh_age  | continuous_age mean: 5.451806  | loss_multiplier mean: 0.897287
15_npc      | npc_flag mean: 0.642137  high_pti_npc mean: 0.129628  | loss_multiplier mean: 0.899995
16_stu_loan | flag mean: 0.251482  | loss_multiplier mean: 0.894445
17_hi_price | flag mean: 0.117389  | loss_multiplier mean: 0.894445
18_driver   | flag mean: 0.004850  | loss_multiplier mean: 0.895115
19_louisiana| flag mean: 0.006389  | loss_multiplier mean: 0.897230
20_georgia  | flag mean: 0.100531  | loss_multiplier mean: 0.906479
21_txca     | flag mean: 0.282349  | loss_multiplier mean: 0.890029

,KMX | 2023 Q1,KMX | 2023 Q2,KMX | 2023 Q3,KMX | 2023 Q4,KMX | 2024 Q1,KMX | 2024 Q2,KMX | 2024 Q3,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q3
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.019539,1.014565,1.012375,1.010877,1.008490,1.006261,1.005939,1.005517,1.000263,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.019539,1.014565,1.012375,1.010877,1.008490,1.006261,1.005939,1.005524,1.001902,1.002054,1.001778,1.001793,1.000000
04_high_pti_3.0,1.031056,1.026466,1.025155,1.024821,1.018635,1.017855,1.017173,1.016710,1.012209,1.010900,1.010491,1.012196,1.006522
07_loss_scale_div_3.0,0.966313,0.962011,0.960783,0.960470,0.954672,0.953941,0.953302,0.952868,0.948650,0.947423,0.947039,0.948637,0.943319
08_secured_credit_3.0,0.966580,0.965348,0.963220,0.962390,0.959284,0.958631,0.958222,0.958243,0.961675,0.954237,0.955275,0.957093,0.935109
09_auth_tradelines_3.0,0.963798,0.963671,0.962134,0.960322,0.955397,0.955863,0.955562,0.954559,0.957559,0.950509,0.951328,0.954659,0.925758
11_soft_pull_3.0,0.940376,0.941918,0.939997,0.937221,0.931381,0.931932,0.931227,0.930319,0.934869,0.926877,0.928611,0.931218,0.902658
12_fraud_all,0.943189,0.945137,0.943049,0.940616,0.924281,0.922186,0.926978,0.928134,0.935783,0.926924,0.928073,0.936525,0.906270
13_clip_3.0,0.941898,0.943470,0.941399,0.938917,0.923856,0.921131,0.925740,0.925953,0.934176,0.926259,0.927291,0.935196,0.906270
14_vehicle_age_3.0,0.934088,0.935178,0.933347,0.923440,0.908135,0.889292,0.897287,0.894650,0.900486,0.896571,0.901700,0.909394,0.840273
15_npc_all,0.938013,0.939283,0.938359,0.927403,0.910838,0.892668,0.899995,0.896434,0.901484,0.896954,0.902182,0.909906,0.841890
16_student_loans_all,0.905938,0.908314,0.903832,0.894829,0.908330,0.888273,0.894445,0.895870,0.899885,0.889881,0.894916,0.897109,0.808214
17_high_sales_price_4.1,0.905938,0.908314,0.903832,0.894829,0.908330,0.888273,0.894445,0.895870,0.899885,0.889881,0.894916,0.897109,0.808214
18_driver_flag_all,0.907121,0.909531,0.905136,0.895965,0.909122,0.888973,0.895115,0.896251,0.900146,0.890132,0.895099,0.897334,0.808214
19_louisiana_all,0.910278,0.912457,0.907902,0.898652,0.911850,0.891803,0.897230,0.898305,0.901859,0.892157,0.897328,0.900564,0.814810
20_georgia_all,0.919294,0.921457,0.917642,0.907540,0.920952,0.900581,0.906479,0.908414,0.913416,0.902102,0.906944,0.908121,0.818315
21_txca_all,0.904945,0.906401,0.902651,0.892781,0.905966,0.883894,0.890029,0.894481,0.900946,0.888897,0.893178,0.893513,0.796015
22_state_counter_all,0.910862,0.912323,0.908509,0.898701,0.912122,0.889714,0.895857,0.900430,0.906957,0.894663,0.899009,0.899442,0.801683
23_secured_credit_3.1+,0.935816,0.934826,0.926275,0.914987,0.944090,0.914276,0.924400,0.932219,0.966642,0.908002,0.926690,0.926168,0.776799
24_job_time_3.1+,0.977190,0.972689,0.965305,0.951809,0.973827,0.938786,0.953457,0.956797,0.984629,0.924715,0.947650,0.954176,0.802865
25_existing_dq_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.982800,0.923461,0.946334,0.952698,0.794836
26_employment_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
27_auth_tradelines_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28a_sp_low_bureau_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28b_sp_open_tl_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28c_hp_low_bureau_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28d_hp_open_tl_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28e_hp_interaction_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28f_sp_cd_perc_3.1/3.2,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28g_hp_cd_perc_3.1/3.2,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28h_sp_cd_perc_4.1,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28i_hp_cd_perc_4.1,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
28j_blanket_hp_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
29_final_clip_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
--- FINAL_MULT (mean),0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.954409,0.983421,0.924116,0.947088,0.953561,0.794836
--- WTD_MULT_RAGU,0.956887,0.948335,0.941626,0.931097,0.949570,0.912917,0.924909,0.929510,0.959633,0.900673,0.925461,0.929008,0.781002
--- GROSS_LOSS_IMPACT,1.077815,1.291630,1.459354,1.722564,1.260756,2.177068,1.877280,1.762248,1.009167,2.483169,1.863475,1.774811,5.474959
--- N_RECORDS,14355.000000,12711.000000,12892.000000,10521.000000,18128.000000,13833.000000,12991.000000,8929.000000,8813.000000,7452.000000,7250.000000,4799.000000,46.000000

--- MTN 3.0 Flag Means ---

,KMX | 2023 Q1,KMX | 2023 Q2,KMX | 2023 Q3,KMX | 2023 Q4,KMX | 2024 Q1,KMX | 2024 Q2,KMX | 2024 Q3,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q3
job_time_flag,0.246883,0.227519,0.235805,0.224693,0.186176,0.163233,0.181741,0.162728,0.128560,0.128288,0.146483,0.181079,0.217391
low_fico_flag,0.082132,0.061600,0.052280,0.048379,0.039331,0.032242,0.029559,0.027887,0.001135,0.000000,0.000000,0.000000,0.000000
high_model_score_flag,0.221665,0.241916,0.234021,0.241422,0.197981,0.246873,0.230929,0.222869,0.218200,0.231616,0.222621,0.209002,0.543478
low_vantage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000112,0.008964,0.010870,0.008828,0.008543,0.000000
normal_pti_flag,0.850226,0.848556,0.837263,0.836137,0.870256,0.865105,0.870372,0.878934,0.873028,0.882448,0.884138,0.876016,0.891304
high_pti_tier_1_flag,0.099060,0.104319,0.111154,0.101796,0.081973,0.081544,0.077900,0.071117,0.083626,0.076355,0.073793,0.076058,0.086957
high_pti_tier_2_flag,0.047092,0.042247,0.046385,0.055508,0.044572,0.047857,0.046263,0.043342,0.038806,0.038916,0.040000,0.043342,0.021739
high_pti_tier_3_flag,0.003622,0.004878,0.005197,0.006558,0.003199,0.005494,0.005465,0.006608,0.004539,0.002281,0.002069,0.004584,0.000000
existing_dq_flag,0.084291,0.073716,0.068647,0.070145,0.081311,0.080026,0.073282,0.070669,0.077726,0.081991,0.081793,0.081059,0.000000
seasonal_employment_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.006581,0.007246,0.007724,0.009377,0.000000
secured_credit_flag,0.182375,0.253167,0.241390,0.228781,0.275044,0.262055,0.267108,0.276851,0.408261,0.310655,0.348414,0.351323,0.021739
kmx_auth_tradelines_flag,0.039429,0.046023,0.049410,0.043342,0.032988,0.039615,0.040028,0.034494,0.031998,0.033951,0.032690,0.041467,0.000000
null_fico_w_vantage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036734,0.910587,0.863392,0.912276,0.905605,0.130435
null_fico_null_vantage_flag,0.202786,0.189836,0.196556,0.197985,0.138625,0.146389,0.146101,0.129914,0.070464,0.136339,0.087724,0.092936,0.869565
soft_pull_flag,0.635040,0.655338,0.685386,0.703640,0.750386,0.748139,0.755908,0.744652,0.758425,0.806763,0.805517,0.832048,0.891304
narrowed_soft_pull_flag,0.099060,0.118795,0.134657,0.133637,0.133936,0.086749,0.100377,0.097323,0.054692,0.099839,0.128966,0.145447,0.065217
fraud_adjustment_mean,1.003439,1.003718,1.003496,1.003709,0.992429,0.989544,0.995378,0.997477,1.000778,0.999893,0.999039,1.005212,1.004130
continuous_vehicle_age_mean,6.565430,6.538267,6.554944,6.162453,6.131413,5.257518,5.451806,5.311074,5.202315,5.397992,5.628609,5.623463,3.416667
kmx_npc_flag,0.641519,0.638738,0.634735,0.627222,0.655174,0.646787,0.642137,0.506776,0.200840,0.199275,0.199310,0.207335,1.000000
high_pti_npc,0.149774,0.151444,0.162737,0.163863,0.129744,0.134895,0.129628,0.121066,0.126972,0.117552,0.115862,0.123984,0.108696
student_loan_flag,0.042076,0.051215,0.023193,0.036689,0.275485,0.260609,0.251482,0.289842,0.276977,0.234031,0.231448,0.188373,0.000000
high_sales_price_flag,0.081574,0.122335,0.122014,0.118905,0.085724,0.125786,0.117389,0.115354,0.098377,0.130837,0.117793,0.119608,0.152174
driver_flag,0.008638,0.009126,0.009696,0.008079,0.005902,0.005060,0.004850,0.003024,0.001929,0.001879,0.001379,0.001667,0.000000
louisiana_flag,0.009822,0.009126,0.008688,0.008744,0.008385,0.008892,0.006389,0.006496,0.005446,0.006307,0.007172,0.009794,0.021739
georgia_flag,0.097388,0.096216,0.106655,0.098185,0.097529,0.096291,0.100531,0.110987,0.125723,0.110843,0.106345,0.082100,0.043478
txca_flag,0.277255,0.268508,0.266056,0.260241,0.271955,0.276224,0.282349,0.258148,0.239306,0.265030,0.265793,0.293186,0.326087
chime_flag,0.179519,0.168515,0.155911,0.151316,0.202560,0.180800,0.194673,0.203606,0.296834,0.143049,0.191862,0.189831,0.000000
low_bureau_flag,0.174573,0.136260,0.122557,0.122327,0.128089,0.110099,0.105150,0.099451,0.035175,0.041868,0.040138,0.040633,0.000000
cd_perc_flag,0.205085,0.231610,0.251939,0.234578,0.217895,0.159329,0.186437,0.184455,0.105186,0.162104,0.208552,0.227339,0.086957
open_tl_flag,0.286311,0.260404,0.261868,0.258245,0.215192,0.215571,0.220383,0.209654,0.196868,0.213097,0.202897,0.212544,0.021739
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
soft_pull_pct_3.1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
low_bureau_flag_sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
low_bureau_flag_hp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
open_tl_flag_sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
open_tl_flag_hp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cd_perc_flag_sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cd_perc_flag_hp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
--- N_RECORDS,14355.000000,12711.000000,12892.000000,10521.000000,18128.000000,13833.000000,12991.000000,8929.000000,8813.000000,7452.000000,7250.000000,4799.000000,46.000000

--- MTN 3.0 Gross Loss Attribution ---

,KMX | 2023 Q1,KMX | 2023 Q2,KMX | 2023 Q3,KMX | 2023 Q4,KMX | 2024 Q1,KMX | 2024 Q2,KMX | 2024 Q3,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q3
Low FICO (3.0),-0.477993,-0.356165,-0.301673,-0.263546,-0.208435,-0.151095,-0.144388,-0.134374,-0.006517,-0.000000,-0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000182,-0.040586,-0.049334,-0.043220,-0.043729,-0.000000
High PTI (3.0),-0.277491,-0.287250,-0.307722,-0.333731,-0.246767,-0.277318,-0.270816,-0.270228,-0.253756,-0.211279,-0.210720,-0.252237,-0.145206
Loss Scale Div (3.0),1.601970,1.597352,1.590727,1.579806,1.598839,1.569857,1.581375,1.584029,1.607797,1.558951,1.577993,1.583331,1.448601
Secured Credit (3.0),-0.006812,-0.085275,-0.062147,-0.048660,-0.118825,-0.118722,-0.125535,-0.137385,-0.338091,-0.172283,-0.210678,-0.216651,0.195278
Auth Tradelines (3.0),0.071188,0.042821,0.027663,0.052412,0.100122,0.069994,0.067795,0.094086,0.106328,0.094104,0.100729,0.062155,0.224498
Soft Pull (3.0),0.607725,0.562381,0.570964,0.593155,0.627634,0.613782,0.629037,0.628264,0.594558,0.605239,0.588094,0.606976,0.564422
Fraud Adjustment,-0.073788,-0.084049,-0.079508,-0.088069,0.188681,0.254483,0.111511,0.057430,-0.024245,-0.001221,0.014107,-0.138739,-0.089195
Clip (3.0),0.033836,0.043482,0.042960,0.044036,0.011338,0.027696,0.032586,0.057469,0.042611,0.017243,0.020518,0.034660,-0.000000
Vehicle Age (3.0),0.205696,0.217430,0.210691,0.404903,0.423132,0.851541,0.761230,0.840029,0.910642,0.783103,0.680943,0.683087,1.688950
NPC,-0.103598,-0.107862,-0.131365,-0.104315,-0.073277,-0.091715,-0.073478,-0.048668,-0.027457,-0.010256,-0.012980,-0.013736,-0.042952
Student Loans,0.859465,0.825786,0.919569,0.871024,0.067991,0.119471,0.150843,0.015376,0.043997,0.190301,0.196738,0.345806,0.911857
High Sales Price (4.1),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Driver Flag,-0.032241,-0.032962,-0.035352,-0.030899,-0.021492,-0.019064,-0.018250,-0.010382,-0.007181,-0.006787,-0.004965,-0.006127,-0.000000
Louisiana,-0.085806,-0.079139,-0.074850,-0.072967,-0.073862,-0.076954,-0.057544,-0.055919,-0.047137,-0.054607,-0.060513,-0.087715,-0.181550
Georgia,-0.243476,-0.241757,-0.261731,-0.239746,-0.244887,-0.237096,-0.250093,-0.273337,-0.315692,-0.266485,-0.259361,-0.204035,-0.095879
TX / CA,0.388607,0.405802,0.404005,0.399434,0.404478,0.452743,0.446585,0.377531,0.340802,0.354472,0.372141,0.395934,0.617176
State Counter,-0.160966,-0.160402,-0.158678,-0.161017,-0.166963,-0.158886,-0.159160,-0.161906,-0.164853,-0.155416,-0.158323,-0.161481,-0.158503
Secured Credit / Chime (3.1+),-0.667653,-0.600194,-0.475037,-0.437487,-0.849257,-0.659199,-0.764811,-0.847442,-1.580098,-0.355773,-0.737898,-0.714882,0.704339
Job Time (3.1+),-1.068673,-0.977953,-1.012368,-0.961143,-0.764582,-0.640415,-0.754681,-0.635661,-0.457082,-0.438436,-0.544239,-0.727375,-0.737233
Existing DQ (3.1+),0.022988,0.052070,0.069973,0.064685,0.034842,0.039662,0.058095,0.061045,0.046088,0.032617,0.033813,0.037852,0.224498
Employment Type (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.015659,-0.017059,-0.019374,-0.022110,-0.000000
Auth Tradelines (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"Low Bureau (SP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"Open TL (SP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"Low Bureau (HP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"Open TL (HP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
HP Interaction (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (SP, 3.1/3.2)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (HP, 3.1/3.2)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (SP, 4.1)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (HP, 4.1)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"Blanket Adjustment (HP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Clip (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
--- Population Weighting,0.484836,0.557515,0.523232,0.454689,0.572048,0.608301,0.656979,0.622474,0.594697,0.586076,0.540671,0.613827,0.345855
--- TOTAL (RAGU GLI),1.077815,1.291630,1.459354,1.722564,1.260756,2.177068,1.877280,1.762248,1.009167,2.483169,1.863475,1.774811,5.474959

============================================================
  DIAGNOSTICS: MTN 3.1
============================================================

============================================================
  KMX 2024 Q4 (MTN 3.1)  (n=3231)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.072114  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.002476  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.083256  tier2: 0.064686  tier3: 0.009285  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.175178  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.057258  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.721139  narrowed: 0.067162  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.991637  | loss_multiplier mean: 0.991637
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.991637
14_veh_age  | continuous_age mean: 4.997524  | loss_multiplier mean: 0.991637
15_npc      | npc_flag mean: 0.999381  high_pti_npc mean: 0.157227  | loss_multiplier mean: 0.998836
16_stu_loan | flag mean: 0.341690  | loss_multiplier mean: 1.005921
17_hi_price | flag mean: 0.154751  | loss_multiplier mean: 1.005921
18_driver   | flag mean: 0.003405  | loss_multiplier mean: 1.006472
19_louisiana| flag mean: 0.005881  | loss_multiplier mean: 1.008562
20_georgia  | flag mean: 0.104921  | loss_multiplier mean: 1.019305
21_txca     | flag mean: 0.276076  | loss_multiplier mean: 0.999327
22_st_cntr  | no state adj: 0.613123  | loss_multiplier mean: 1.005822
23_sec_cr31 | chime mean: 0.133086  | loss_multiplier mean: 1.016004
24_job_t_31 | flag mean: 0.221913  | loss_multiplier mean: 1.054200
25_dq_31    | flag mean: 0.162179  | loss_multiplier mean: 1.061885
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 1.061885
27_auth_31  | flag mean: 0.057258  | loss_multiplier mean: 1.054844
28a_sp_lb   | SP pct: 0.721139  low_bureau(SP): 0.172961  | loss_multiplier mean: 1.061653
28b_sp_otl  | open_tl(SP): 0.108584  | loss_multiplier mean: 1.058194
28c_hp_lb   | HP pct: 0.278861  low_bureau(HP): 0.093230  | loss_multiplier mean: 1.058181
28d_hp_otl  | open_tl(HP): 0.128746  | loss_multiplier mean: 1.056025
28e_hp_int  | HP cd_perc & open_tl pct: 0.005262  | loss_multiplier mean: 1.054967
28f_sp_cdp  | SP 3.1/3.2 pct: 0.721139  cd_perc(SP): 0.121030  | loss_multiplier mean: 1.045440
28g_hp_cdp  | HP 3.1/3.2 pct: 0.278861  cd_perc(HP): 0.166482  | loss_multiplier mean: 1.047984
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.047984
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.047984
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.021528
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.016096

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.016096  (n=3231)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 3215 / 3231  wtd_mult: 0.997813  ragu_gli: 0.0547

============================================================
  KMX 2025 Q1 (MTN 3.1)  (n=9947)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.001609  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.019805  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.085051  tier2: 0.058912  tier3: 0.007439  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.258973  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.043430  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.745752  narrowed: 0.040213  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.990185  | loss_multiplier mean: 0.990185
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.990185
14_veh_age  | continuous_age mean: 4.655533  | loss_multiplier mean: 0.990185
15_npc      | npc_flag mean: 0.998090  high_pti_npc mean: 0.151402  | loss_multiplier mean: 0.996829
16_stu_loan | flag mean: 0.361114  | loss_multiplier mean: 1.006849
17_hi_price | flag mean: 0.145873  | loss_multiplier mean: 1.006849
18_driver   | flag mean: 0.003016  | loss_multiplier mean: 1.007303
19_louisiana| flag mean: 0.005228  | loss_multiplier mean: 1.009145
20_georgia  | flag mean: 0.106665  | loss_multiplier mean: 1.019978
21_txca     | flag mean: 0.268925  | loss_multiplier mean: 1.000882
22_st_cntr  | no state adj: 0.619182  | loss_multiplier mean: 1.007575
23_sec_cr31 | chime mean: 0.192922  | loss_multiplier mean: 1.037286
24_job_t_31 | flag mean: 0.191917  | loss_multiplier mean: 1.069582
25_dq_31    | flag mean: 0.177541  | loss_multiplier mean: 1.079278
26_emp_31   | seasonal: 0.009651  | loss_multiplier mean: 1.080360
27_auth_31  | flag mean: 0.043430  | loss_multiplier mean: 1.072211
28a_sp_lb   | SP pct: 0.745752  low_bureau(SP): 0.065112  | loss_multiplier mean: 1.069812
28b_sp_otl  | open_tl(SP): 0.106767  | loss_multiplier mean: 1.065644
28c_hp_lb   | HP pct: 0.254248  low_bureau(HP): 0.035192  | loss_multiplier mean: 1.062230
28d_hp_otl  | open_tl(HP): 0.108343  | loss_multiplier mean: 1.057859
28e_hp_int  | HP cd_perc & open_tl pct: 0.003318  | loss_multiplier mean: 1.057176
28f_sp_cdp  | SP 3.1/3.2 pct: 0.745752  cd_perc(SP): 0.065382  | loss_multiplier mean: 1.040673
28g_hp_cdp  | HP 3.1/3.2 pct: 0.254248  cd_perc(HP): 0.103203  | loss_multiplier mean: 1.037193
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.037193
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.037193
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.013737
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.009956

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 1.009956  (n=9947)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 9816 / 9947  wtd_mult: 0.993625  ragu_gli: 0.1594

============================================================
  KMX 2025 Q2 (MTN 3.1)  (n=8172)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.015541  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.078683  tier2: 0.054454  tier3: 0.003549  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.313877  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.048091  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.786466  narrowed: 0.078806  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.988385  | loss_multiplier mean: 0.988385
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.988385
14_veh_age  | continuous_age mean: 4.849088  | loss_multiplier mean: 0.988385
15_npc      | npc_flag mean: 0.997797  high_pti_npc mean: 0.136686  | loss_multiplier mean: 0.993459
16_stu_loan | flag mean: 0.297724  | loss_multiplier mean: 0.994707
17_hi_price | flag mean: 0.187592  | loss_multiplier mean: 0.994707
18_driver   | flag mean: 0.002203  | loss_multiplier mean: 0.995053
19_louisiana| flag mean: 0.004161  | loss_multiplier mean: 0.996528
20_georgia  | flag mean: 0.096182  | loss_multiplier mean: 1.006212
21_txca     | flag mean: 0.290259  | loss_multiplier mean: 0.985776
22_st_cntr  | no state adj: 0.609398  | loss_multiplier mean: 0.992028
23_sec_cr31 | chime mean: 0.126774  | loss_multiplier mean: 0.999825
24_job_t_31 | flag mean: 0.106706  | loss_multiplier mean: 1.012346
25_dq_31    | flag mean: 0.119555  | loss_multiplier mean: 1.015298
26_emp_31   | seasonal: 0.006486  | loss_multiplier mean: 1.015948
27_auth_31  | flag mean: 0.048091  | loss_multiplier mean: 1.008697
28a_sp_lb   | SP pct: 0.786466  low_bureau(SP): 0.043099  | loss_multiplier mean: 1.004565
28b_sp_otl  | open_tl(SP): 0.109382  | loss_multiplier mean: 1.001012
28c_hp_lb   | HP pct: 0.213534  low_bureau(HP): 0.029799  | loss_multiplier mean: 0.998071
28d_hp_otl  | open_tl(HP): 0.122063  | loss_multiplier mean: 0.996154
28e_hp_int  | HP cd_perc & open_tl pct: 0.004038  | loss_multiplier mean: 0.995363
28f_sp_cdp  | SP 3.1/3.2 pct: 0.786466  cd_perc(SP): 0.108449  | loss_multiplier mean: 0.984061
28g_hp_cdp  | HP 3.1/3.2 pct: 0.213534  cd_perc(HP): 0.137536  | loss_multiplier mean: 0.983829
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.983829
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.983829
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.964750
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.966036

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.966036  (n=8172)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 8000 / 8172  wtd_mult: 0.952012  ragu_gli: 1.1997

============================================================
  KMX 2025 Q3 (MTN 3.1)  (n=8190)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.011966  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.073626  tier2: 0.049206  tier3: 0.004274  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.369109  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.046154  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.805006  narrowed: 0.100488  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.991386  | loss_multiplier mean: 0.991386
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.991386
14_veh_age  | continuous_age mean: 5.073626  | loss_multiplier mean: 0.991386
15_npc      | npc_flag mean: 0.997314  high_pti_npc mean: 0.127106  | loss_multiplier mean: 0.995400
16_stu_loan | flag mean: 0.303541  | loss_multiplier mean: 0.997362
17_hi_price | flag mean: 0.182662  | loss_multiplier mean: 0.997362
18_driver   | flag mean: 0.001221  | loss_multiplier mean: 0.997550
19_louisiana| flag mean: 0.004396  | loss_multiplier mean: 0.999048
20_georgia  | flag mean: 0.095604  | loss_multiplier mean: 1.008714
21_txca     | flag mean: 0.283394  | loss_multiplier mean: 0.988933
22_st_cntr  | no state adj: 0.616606  | loss_multiplier mean: 0.995261
23_sec_cr31 | chime mean: 0.178632  | loss_multiplier mean: 1.018670
24_job_t_31 | flag mean: 0.108059  | loss_multiplier mean: 1.032067
25_dq_31    | flag mean: 0.119658  | loss_multiplier mean: 1.035000
26_emp_31   | seasonal: 0.007082  | loss_multiplier mean: 1.035789
27_auth_31  | flag mean: 0.046154  | loss_multiplier mean: 1.028203
28a_sp_lb   | SP pct: 0.805006  low_bureau(SP): 0.037464  | loss_multiplier mean: 1.023297
28b_sp_otl  | open_tl(SP): 0.095556  | loss_multiplier mean: 1.017644
28c_hp_lb   | HP pct: 0.194994  low_bureau(HP): 0.040075  | loss_multiplier mean: 1.015357
28d_hp_otl  | open_tl(HP): 0.117095  | loss_multiplier mean: 1.012826
28e_hp_int  | HP cd_perc & open_tl pct: 0.003541  | loss_multiplier mean: 1.012113
28f_sp_cdp  | SP 3.1/3.2 pct: 0.805006  cd_perc(SP): 0.134233  | loss_multiplier mean: 1.003798
28g_hp_cdp  | HP 3.1/3.2 pct: 0.194994  cd_perc(HP): 0.165936  | loss_multiplier mean: 1.005402
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.005402
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.005402
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.987564
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.984844

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.984844  (n=8190)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 7999 / 8190  wtd_mult: 0.970540  ragu_gli: 0.7365

============================================================
  KMX 2025 Q4 (MTN 3.1)  (n=8612)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.013470  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.075476  tier2: 0.043892  tier3: 0.004064  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.362169  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.044124  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.835462  narrowed: 0.115188  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.996688  | loss_multiplier mean: 0.996688
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.996688
14_veh_age  | continuous_age mean: 4.891073  | loss_multiplier mean: 0.996688
15_npc      | npc_flag mean: 0.832211  high_pti_npc mean: 0.123432  | loss_multiplier mean: 0.999667
16_stu_loan | flag mean: 0.211797  | loss_multiplier mean: 0.988969
17_hi_price | flag mean: 0.170460  | loss_multiplier mean: 0.988969
18_driver   | flag mean: 0.001626  | loss_multiplier mean: 0.989216
19_louisiana| flag mean: 0.004877  | loss_multiplier mean: 0.990889
20_georgia  | flag mean: 0.078379  | loss_multiplier mean: 0.998712
21_txca     | flag mean: 0.328611  | loss_multiplier mean: 0.975347
22_st_cntr  | no state adj: 0.588133  | loss_multiplier mean: 0.981254
23_sec_cr31 | chime mean: 0.160125  | loss_multiplier mean: 0.998413
24_job_t_31 | flag mean: 0.120529  | loss_multiplier mean: 1.014031
25_dq_31    | flag mean: 0.131212  | loss_multiplier mean: 1.017983
26_emp_31   | seasonal: 0.007083  | loss_multiplier mean: 1.018691
27_auth_31  | flag mean: 0.044124  | loss_multiplier mean: 1.011169
28a_sp_lb   | SP pct: 0.835462  low_bureau(SP): 0.039750  | loss_multiplier mean: 1.006386
28b_sp_otl  | open_tl(SP): 0.113273  | loss_multiplier mean: 1.003328
28c_hp_lb   | HP pct: 0.164538  low_bureau(HP): 0.032463  | loss_multiplier mean: 1.001155
28d_hp_otl  | open_tl(HP): 0.116443  | loss_multiplier mean: 0.999258
28e_hp_int  | HP cd_perc & open_tl pct: 0.002322  | loss_multiplier mean: 0.998780
28f_sp_cdp  | SP 3.1/3.2 pct: 0.835462  cd_perc(SP): 0.150243  | loss_multiplier mean: 0.992070
28g_hp_cdp  | HP 3.1/3.2 pct: 0.164538  cd_perc(HP): 0.155963  | loss_multiplier mean: 0.992858
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.992858
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.992858
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.977940
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.976574

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.976574  (n=8612)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 8562 / 8612  wtd_mult: 0.959685  ragu_gli: 1.0079

============================================================
  KMX 2026 Q1 (MTN 3.1)  (n=13018)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000307  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.016439  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.062222  tier2: 0.030880  tier3: 0.002612  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.448763  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.039868  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.866569  narrowed: 0.109617  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.996694  | loss_multiplier mean: 0.996694
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.996694
14_veh_age  | continuous_age mean: 4.676986  | loss_multiplier mean: 0.996694
15_npc      | npc_flag mean: 0.317330  high_pti_npc mean: 0.095714  | loss_multiplier mean: 0.996728
16_stu_loan | flag mean: 0.232447  | loss_multiplier mean: 0.988990
17_hi_price | flag mean: 0.132893  | loss_multiplier mean: 0.988990
18_driver   | flag mean: 0.001152  | loss_multiplier mean: 0.989155
19_louisiana| flag mean: 0.005300  | loss_multiplier mean: 0.990974
20_georgia  | flag mean: 0.078353  | loss_multiplier mean: 0.998749
21_txca     | flag mean: 0.329621  | loss_multiplier mean: 0.975604
22_st_cntr  | no state adj: 0.586726  | loss_multiplier mean: 0.981606
23_sec_cr31 | chime mean: 0.250269  | loss_multiplier mean: 1.024269
24_job_t_31 | flag mean: 0.110309  | loss_multiplier mean: 1.037933
25_dq_31    | flag mean: 0.133123  | loss_multiplier mean: 1.042201
26_emp_31   | seasonal: 0.007528  | loss_multiplier mean: 1.042967
27_auth_31  | flag mean: 0.039868  | loss_multiplier mean: 1.034897
28a_sp_lb   | SP pct: 0.866569  low_bureau(SP): 0.047957  | loss_multiplier mean: 1.030522
28b_sp_otl  | open_tl(SP): 0.093875  | loss_multiplier mean: 1.024093
28c_hp_lb   | HP pct: 0.133431  low_bureau(HP): 0.037421  | loss_multiplier mean: 1.022455
28d_hp_otl  | open_tl(HP): 0.105930  | loss_multiplier mean: 1.020220
28e_hp_int  | HP cd_perc & open_tl pct: 0.001767  | loss_multiplier mean: 1.019884
28f_sp_cdp  | SP 3.1/3.2 pct: 0.866569  cd_perc(SP): 0.138020  | loss_multiplier mean: 1.010789
28g_hp_cdp  | HP 3.1/3.2 pct: 0.133431  cd_perc(HP): 0.147381  | loss_multiplier mean: 1.010683
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.010683
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.010683
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.998649
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.997080

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = 0.997080  (n=13018)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 12948 / 13018  wtd_mult: 0.981385  ragu_gli: 0.4654

============================================================
  KMX 2026 Q2 (MTN 3.1)  (n=713)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.018233  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.071529  tier2: 0.023843  tier3: 0.002805  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.461431  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.046283  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.868163  narrowed: 0.091164  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.012651  | loss_multiplier mean: 1.012651
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.012651
14_veh_age  | continuous_age mean: 4.649369  | loss_multiplier mean: 1.012651
15_npc      | npc_flag mean: 0.000000  high_pti_npc mean: 0.098177  | loss_multiplier mean: 1.012651
16_stu_loan | flag mean: 0.214586  | loss_multiplier mean: 1.002010
17_hi_price | flag mean: 0.187938  | loss_multiplier mean: 1.002010
18_driver   | flag mean: 0.002805  | loss_multiplier mean: 1.002471
19_louisiana| flag mean: 0.016830  | loss_multiplier mean: 1.008626

,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.991637,0.990185,0.988385,0.991386,0.996688,0.996694,1.012651
13_clip_3.0,0.991637,0.990185,0.988385,0.991386,0.996688,0.996694,1.012651
14_vehicle_age_3.0,0.991637,0.990185,0.988385,0.991386,0.996688,0.996694,1.012651
15_npc_all,0.998836,0.996829,0.993459,0.995400,0.999667,0.996728,1.012651
16_student_loans_all,1.005921,1.006849,0.994707,0.997362,0.988969,0.988990,1.002010
17_high_sales_price_4.1,1.005921,1.006849,0.994707,0.997362,0.988969,0.988990,1.002010
18_driver_flag_all,1.006472,1.007303,0.995053,0.997550,0.989216,0.989155,1.002471
19_louisiana_all,1.008562,1.009145,0.996528,0.999048,0.990889,0.990974,1.008626
20_georgia_all,1.019305,1.019978,1.006212,1.008714,0.998712,0.998749,1.015649
21_txca_all,0.999327,1.000882,0.985776,0.988933,0.975347,0.975604,0.992544
22_state_counter_all,1.005822,1.007575,0.992028,0.995261,0.981254,0.981606,0.998834
23_secured_credit_3.1+,1.016004,1.037286,0.999825,1.018670,0.998413,1.024269,1.049127
24_job_time_3.1+,1.054200,1.069582,1.012346,1.032067,1.014031,1.037933,1.061833
25_existing_dq_3.1+,1.061885,1.079278,1.015298,1.035000,1.017983,1.042201,1.064797
26_employment_3.1+,1.061885,1.080360,1.015948,1.035789,1.018691,1.042967,1.065461
27_auth_tradelines_3.1+,1.054844,1.072211,1.008697,1.028203,1.011169,1.034897,1.057644
28a_sp_low_bureau_3.1+,1.061653,1.069812,1.004565,1.023297,1.006386,1.030522,1.052356
28b_sp_open_tl_3.1+,1.058194,1.065644,1.001012,1.017644,1.003328,1.024093,1.051065
28c_hp_low_bureau_3.1+,1.058181,1.062230,0.998071,1.015357,1.001155,1.022455,1.048867
28d_hp_open_tl_3.1+,1.056025,1.057859,0.996154,1.012826,0.999258,1.020220,1.049348
28e_hp_interaction_3.1+,1.054967,1.057176,0.995363,1.012113,0.998780,1.019884,1.048962
28f_sp_cd_perc_3.1/3.2,1.045440,1.040673,0.984061,1.003798,0.992070,1.010789,1.036571
28g_hp_cd_perc_3.1/3.2,1.047984,1.037193,0.983829,1.005402,0.992858,1.010683,1.034197
28h_sp_cd_perc_4.1,1.047984,1.037193,0.983829,1.005402,0.992858,1.010683,1.034197
28i_hp_cd_perc_4.1,1.047984,1.037193,0.983829,1.005402,0.992858,1.010683,1.034197
28j_blanket_hp_3.1+,1.021528,1.013737,0.964750,0.987564,0.977940,0.998649,1.021976
29_final_clip_3.1+,1.016096,1.009956,0.966036,0.984844,0.976574,0.997080,1.014107
--- FINAL_MULT (mean),1.016096,1.009956,0.966036,0.984844,0.976574,0.997080,1.014107
--- WTD_MULT_RAGU,0.997813,0.993625,0.952012,0.970540,0.959685,0.981385,0.997170
--- GROSS_LOSS_IMPACT,0.054665,0.159380,1.199691,0.736501,1.007884,0.465385,0.070744
--- N_RECORDS,3231.000000,9947.000000,8172.000000,8190.000000,8612.000000,13018.000000,713.000000

--- MTN 3.1 Flag Means ---

,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2
job_time_flag,0.221913,0.191917,0.106706,0.108059,0.120529,0.110309,0.103787
low_fico_flag,0.072114,0.001609,0.000000,0.000000,0.000000,0.000307,0.000000
high_model_score_flag,0.292170,0.255152,0.300906,0.292430,0.296795,0.294131,0.353436
low_vantage_flag,0.002476,0.019805,0.015541,0.011966,0.013470,0.016439,0.018233
normal_pti_flag,0.842773,0.848598,0.863314,0.872894,0.876568,0.904286,0.901823
high_pti_tier_1_flag,0.083256,0.085051,0.078683,0.073626,0.075476,0.062222,0.071529
high_pti_tier_2_flag,0.064686,0.058912,0.054454,0.049206,0.043892,0.030880,0.023843
high_pti_tier_3_flag,0.009285,0.007439,0.003549,0.004274,0.004064,0.002612,0.002805
existing_dq_flag,0.162179,0.177541,0.119555,0.119658,0.131212,0.133123,0.117812
seasonal_employment_flag,0.000000,0.009651,0.006486,0.007082,0.007083,0.007528,0.005610
secured_credit_flag,0.175178,0.258973,0.313877,0.369109,0.362169,0.448763,0.461431
kmx_auth_tradelines_flag,0.057258,0.043430,0.048091,0.046154,0.044124,0.039868,0.046283
null_fico_w_vantage_flag,0.141133,0.930130,0.887788,0.940171,0.939039,0.955446,0.959327
null_fico_null_vantage_flag,0.079542,0.054187,0.112212,0.059829,0.052253,0.022815,0.040673
soft_pull_flag,0.721139,0.745752,0.786466,0.805006,0.835462,0.866569,0.868163
narrowed_soft_pull_flag,0.067162,0.040213,0.078806,0.100488,0.115188,0.109617,0.091164
fraud_adjustment_mean,0.991637,0.990185,0.988385,0.991386,0.996688,0.996694,1.012651
continuous_vehicle_age_mean,4.997524,4.655533,4.849088,5.073626,4.891073,4.676986,4.649369
kmx_npc_flag,0.999381,0.998090,0.997797,0.997314,0.832211,0.317330,0.000000
high_pti_npc,0.157227,0.151402,0.136686,0.127106,0.123432,0.095714,0.098177
student_loan_flag,0.341690,0.361114,0.297724,0.303541,0.211797,0.232447,0.214586
high_sales_price_flag,0.154751,0.145873,0.187592,0.182662,0.170460,0.132893,0.187938
driver_flag,0.003405,0.003016,0.002203,0.001221,0.001626,0.001152,0.002805
louisiana_flag,0.005881,0.005228,0.004161,0.004396,0.004877,0.005300,0.016830
georgia_flag,0.104921,0.106665,0.096182,0.095604,0.078379,0.078353,0.070126
txca_flag,0.276076,0.268925,0.290259,0.283394,0.328611,0.329621,0.302945
chime_flag,0.133086,0.192922,0.126774,0.178632,0.160125,0.250269,0.267882
low_bureau_flag,0.150727,0.057505,0.040259,0.037973,0.038551,0.046551,0.039271
cd_perc_flag,0.133705,0.074997,0.114660,0.140415,0.151184,0.139269,0.112202
open_tl_flag,0.114206,0.107168,0.112090,0.099756,0.113795,0.095483,0.130435
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
soft_pull_pct_3.1+,0.721139,0.745752,0.786466,0.805006,0.835462,0.866569,0.868163
low_bureau_flag_sp,0.172961,0.065112,0.043099,0.037464,0.039750,0.047957,0.042003
low_bureau_flag_hp,0.093230,0.035192,0.029799,0.040075,0.032463,0.037421,0.021277
open_tl_flag_sp,0.108584,0.106767,0.109382,0.095556,0.113273,0.093875,0.127625
open_tl_flag_hp,0.128746,0.108343,0.122063,0.117095,0.116443,0.105930,0.148936
cd_perc_flag_sp,0.121030,0.065382,0.108449,0.134233,0.150243,0.138020,0.114701
cd_perc_flag_hp,0.166482,0.103203,0.137536,0.165936,0.155963,0.147381,0.095745
--- N_RECORDS,3231.000000,9947.000000,8172.000000,8190.000000,8612.000000,13018.000000,713.000000

--- MTN 3.1 Gross Loss Attribution ---

,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2
Low FICO (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High PTI (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Loss Scale Div (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Secured Credit (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Auth Tradelines (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Soft Pull (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Fraud Adjustment,0.211633,0.247813,0.287093,0.214644,0.081954,0.082671,-0.316497
Clip (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Vehicle Age (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
NPC,-0.182273,-0.168008,-0.125825,-0.100256,-0.073724,-0.000848,-0.000000
Student Loans,-0.178132,-0.251288,-0.030865,-0.048842,0.265829,0.194559,0.265942
High Sales Price (4.1),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Driver Flag,-0.013792,-0.011344,-0.008543,-0.004684,-0.006188,-0.004179,-0.011567
Louisiana,-0.052274,-0.045891,-0.036388,-0.037242,-0.041742,-0.045861,-0.154113
Georgia,-0.267023,-0.268263,-0.237655,-0.238885,-0.194286,-0.195081,-0.174692
TX / CA,0.498819,0.474836,0.504230,0.491370,0.584860,0.585288,0.579331
State Counter,-0.163248,-0.167463,-0.155378,-0.158249,-0.149158,-0.153104,-0.159033
Secured Credit / Chime (3.1+),-0.253818,-0.730141,-0.192376,-0.576784,-0.428293,-1.062042,-1.236759
Job Time (3.1+),-0.930042,-0.770313,-0.305825,-0.324165,-0.383484,-0.330816,-0.303082
Existing DQ (3.1+),-0.183044,-0.226716,-0.071537,-0.070410,-0.096103,-0.102443,-0.070186
Employment Type (3.1+),-0.000000,-0.025179,-0.015726,-0.018897,-0.017189,-0.018352,-0.015693
Auth Tradelines (3.1+),0.167650,0.190213,0.176007,0.182374,0.183120,0.193912,0.185396
"Low Bureau (SP, 3.1+)",-0.162145,0.056281,0.100855,0.118659,0.117141,0.105748,0.126195
"Open TL (SP, 3.1+)",0.082254,0.098080,0.087079,0.137446,0.075168,0.156240,0.030889
"Low Bureau (HP, 3.1+)",0.000302,0.080616,0.072304,0.055821,0.053566,0.039961,0.052721
"Open TL (HP, 3.1+)",0.051388,0.103598,0.047243,0.061900,0.046881,0.054627,-0.011545
HP Interaction (3.1+),0.025270,0.016236,0.019527,0.017491,0.011806,0.008227,0.009268
"CD Perc (SP, 3.1/3.2)",0.228604,0.395294,0.280608,0.204657,0.166538,0.223613,0.299143
"CD Perc (HP, 3.1/3.2)",-0.061232,0.084144,0.005792,-0.039617,-0.019602,0.002614,0.057728
"CD Perc (SP, 4.1)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (HP, 4.1)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
"Blanket Adjustment (HP, 3.1+)",0.644351,0.574713,0.481219,0.444142,0.374017,0.299005,0.299289
Clip (3.1+),0.134346,0.093868,-0.032732,0.068431,0.034551,0.039266,0.194585
--- Population Weighting,0.457072,0.408291,0.350583,0.357597,0.422223,0.392380,0.423427
--- TOTAL (RAGU GLI),0.054665,0.159380,1.199691,0.736501,1.007884,0.465385,0.070744

============================================================
  DIAGNOSTICS: MTN 3.2
============================================================

============================================================
  KMX 2026 Q1 (MTN 3.2)  (n=7451)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000134  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.016508  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.064018  tier2: 0.030600  tier3: 0.003087  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.507851  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.035029  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.874379  narrowed: 0.096900  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.999423  | loss_multiplier mean: 0.999423
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.999423
14_veh_age  | continuous_age mean: 4.966145  | loss_multiplier mean: 0.999423
15_npc      | npc_flag mean: 0.997718  high_pti_npc mean: 0.097705  | loss_multiplier mean: 1.000305
16_stu_loan | flag mean: 0.226010  | loss_multiplier mean: 0.991543
17_hi_price | flag mean: 0.117568  | loss_multiplier mean: 0.991543
18_driver   | flag mean: 0.001476  | loss_multiplier mean: 0.991773
19_louisiana| flag mean: 0.005368  | loss_multiplier mean: 0.993654
20_georgia  | flag mean: 0.083613  | loss_multiplier mean: 1.002005
21_txca     | flag mean: 0.321299  | loss_multiplier mean: 0.977757
22_st_cntr  | no state adj: 0.589720  | loss_multiplier mean: 0.983767
23_sec_cr31 | chime mean: 0.323447  | loss_multiplier mean: 1.048062
24_job_t_31 | flag mean: 0.115689  | loss_multiplier mean: 1.063496
25_dq_31    | flag mean: 0.130050  | loss_multiplier mean: 1.067360
26_emp_31   | seasonal: 0.007247  | loss_multiplier mean: 1.068157
27_auth_31  | flag mean: 0.035029  | loss_multiplier mean: 1.059632
28a_sp_lb   | SP pct: 0.874379  low_bureau(SP): 0.043592  | loss_multiplier mean: 1.054702
28b_sp_otl  | open_tl(SP): 0.094551  | loss_multiplier mean: 1.048208
28c_hp_lb   | HP pct: 0.125621  low_bureau(HP): 0.038462  | loss_multiplier mean: 1.046569
28d_hp_otl  | open_tl(HP): 0.112179  | loss_multiplier mean: 1.044540
28e_hp_int  | HP cd_perc & open_tl pct: 0.002416  | loss_multiplier mean: 1.044061
28f_sp_cdp  | SP 3.1/3.2 pct: 0.874379  cd_perc(SP): 0.120798  | loss_multiplier mean: 1.032415
28g_hp_cdp  | HP 3.1/3.2 pct: 0.125621  cd_perc(HP): 0.120726  | loss_multiplier mean: 1.031446
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.031446
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.031446
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.019622
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.014980

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.014980  (n=7451)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 7391 / 7451  wtd_mult: 0.998957  ragu_gli: 0.0261

============================================================
  KMX 2026 Q2 (MTN 3.2)  (n=14603)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.011641  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.070876  tier2: 0.031980  tier3: 0.002465  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.451825  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.045813  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.844621  narrowed: 0.099979  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.017747  | loss_multiplier mean: 1.017747
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.017747
14_veh_age  | continuous_age mean: 4.794637  | loss_multiplier mean: 1.017747
15_npc      | npc_flag mean: 0.627268  high_pti_npc mean: 0.105321  | loss_multiplier mean: 1.018659
16_stu_loan | flag mean: 0.210231  | loss_multiplier mean: 1.007123
17_hi_price | flag mean: 0.182086  | loss_multiplier mean: 1.007123
18_driver   | flag mean: 0.001027  | loss_multiplier mean: 1.007285
19_louisiana| flag mean: 0.002808  | loss_multiplier mean: 1.008278
20_georgia  | flag mean: 0.077313  | loss_multiplier mean: 1.016166
21_txca     | flag mean: 0.317880  | loss_multiplier mean: 0.992074
22_st_cntr  | no state adj: 0.602000  | loss_multiplier mean: 0.998239
23_sec_cr31 | chime mean: 0.255632  | loss_multiplier mean: 1.043900
24_job_t_31 | flag mean: 0.112374  | loss_multiplier mean: 1.058689
25_dq_31    | flag mean: 0.133055  | loss_multiplier mean: 1.062881
26_emp_31   | seasonal: 0.008834  | loss_multiplier mean: 1.063855
27_auth_31  | flag mean: 0.045813  | loss_multiplier mean: 1.056127
28a_sp_lb   | SP pct: 0.844621  low_bureau(SP): 0.033404  | loss_multiplier mean: 1.050390
28b_sp_otl  | open_tl(SP): 0.089752  | loss_multiplier mean: 1.043949
28c_hp_lb   | HP pct: 0.155379  low_bureau(HP): 0.032173  | loss_multiplier mean: 1.041835
28d_hp_otl  | open_tl(HP): 0.117232  | loss_multiplier mean: 1.040121
28e_hp_int  | HP cd_perc & open_tl pct: 0.002191  | loss_multiplier mean: 1.039676
28f_sp_cdp  | SP 3.1/3.2 pct: 0.844621  cd_perc(SP): 0.129479  | loss_multiplier mean: 1.029992
28g_hp_cdp  | HP 3.1/3.2 pct: 0.155379  cd_perc(HP): 0.128691  | loss_multiplier mean: 1.029313
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.029313
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.029313
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.014898
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.007608

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 1.007608  (n=14603)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 14532 / 14603  wtd_mult: 0.987728  ragu_gli: 0.3068

============================================================
  KMX 2026 Q3 (MTN 3.2)  (n=7692)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.009360  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.067733  tier2: 0.037702  tier3: 0.003250  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.401586  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.046022  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.840874  narrowed: 0.112454  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.014585  | loss_multiplier mean: 1.014585
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.014585
14_veh_age  | continuous_age mean: 4.808546  | loss_multiplier mean: 1.014585
15_npc      | npc_flag mean: 0.614015  high_pti_npc mean: 0.108684  | loss_multiplier mean: 1.015983
16_stu_loan | flag mean: 0.192148  | loss_multiplier mean: 1.002051
17_hi_price | flag mean: 0.187467  | loss_multiplier mean: 1.002051
18_driver   | flag mean: 0.001300  | loss_multiplier mean: 1.002248
19_louisiana| flag mean: 0.003900  | loss_multiplier mean: 1.003587
20_georgia  | flag mean: 0.069813  | loss_multiplier mean: 1.010638
21_txca     | flag mean: 0.325143  | loss_multiplier mean: 0.985933
22_st_cntr  | no state adj: 0.601144  | loss_multiplier mean: 0.991867
23_sec_cr31 | chime mean: 0.232449  | loss_multiplier mean: 1.030379
24_job_t_31 | flag mean: 0.119085  | loss_multiplier mean: 1.046245
25_dq_31    | flag mean: 0.123115  | loss_multiplier mean: 1.049481
26_emp_31   | seasonal: 0.008190  | loss_multiplier mean: 1.050379
27_auth_31  | flag mean: 0.046022  | loss_multiplier mean: 1.042781
28a_sp_lb   | SP pct: 0.840874  low_bureau(SP): 0.027211  | loss_multiplier mean: 1.036542
28b_sp_otl  | open_tl(SP): 0.084570  | loss_multiplier mean: 1.029775
28c_hp_lb   | HP pct: 0.159126  low_bureau(HP): 0.031046  | loss_multiplier mean: 1.027590
28d_hp_otl  | open_tl(HP): 0.080882  | loss_multiplier mean: 1.023699
28e_hp_int  | HP cd_perc & open_tl pct: 0.001430  | loss_multiplier mean: 1.023404
28f_sp_cdp  | SP 3.1/3.2 pct: 0.840874  cd_perc(SP): 0.145331  | loss_multiplier mean: 1.015624
28g_hp_cdp  | HP 3.1/3.2 pct: 0.159126  cd_perc(HP): 0.142157  | loss_multiplier mean: 1.015576
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.015576
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.015576
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.001253
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.994730

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = 0.994730  (n=7692)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 7108 / 7692  wtd_mult: 0.984115  ragu_gli: 0.3971

--- MTN 3.2 Multiplier Steps ---

                         KMX | 2026 Q1  KMX | 2026 Q2  KMX | 2026 Q3
00_initial                    1.000000       1.000000       1.000000
02_low_fico_3.0               1.000000       1.000000       1.000000
03_low_vantage_3.0            1.000000       1.000000       1.000000
04_high_pti_3.0               1.000000       1.000000       1.000000
07_loss_scale_div_3.0         1.000000       1.000000       1.000000
08_secured_credit_3.0         1.000000       1.000000       1.000000
09_auth_tradelines_3.0        1.000000       1.000000       1.000000
11_soft_pull_3.0              1.000000       1.000000       1.000000
12_fraud_all                  0.999423       1.017747       1.014585
13_clip_3.0                   0.999423       1.017747       1.014585
14_vehicle_age_3.0            0.999423       1.017747       1.014585
15_npc_all                    1.000305       1.018659       1.015983
16_student_loans_all          0.991543       1.007123       1.002051
17_high_sales_price_4.1       0.991543       1.007123       1.002051
18_driver_flag_all            0.991773       1.007285       1.002248
19_louisiana_all              0.993654       1.008278       1.003587
20_georgia_all                1.002005       1.016166       1.010638
21_txca_all                   0.977757       0.992074       0.985933
22_state_counter_all          0.983767       0.998239       0.991867
23_secured_credit_3.1+        1.048062       1.043900       1.030379
24_job_time_3.1+              1.063496       1.058689       1.046245
25_existing_dq_3.1+           1.067360       1.062881       1.049481
26_employment_3.1+            1.068157       1.063855       1.050379
27_auth_tradelines_3.1+       1.059632       1.056127       1.042781
28a_sp_low_bureau_3.1+        1.054702       1.050390       1.036542
28b_sp_open_tl_3.1+           1.048208       1.043949       1.029775
28c_hp_low_bureau_3.1+        1.046569       1.041835       1.027590
28d_hp_open_tl_3.1+           1.044540       1.040121       1.023699
28e_hp_interaction_3.1+       1.044061       1.039676       1.023404
28f_sp_cd_perc_3.1/3.2        1.032415       1.029992       1.015624
28g_hp_cd_perc_3.1/3.2        1.031446       1.029313       1.015576
28h_sp_cd_perc_4.1            1.031446       1.029313       1.015576
28i_hp_cd_perc_4.1            1.031446       1.029313       1.015576
28j_blanket_hp_3.1+           1.019622       1.014898       1.001253
29_final_clip_3.1+            1.014980       1.007608       0.994730
--- FINAL_MULT (mean)         1.014980       1.007608       0.994730
--- WTD_MULT_RAGU             0.998957       0.987728       0.984115
--- GROSS_LOSS_IMPACT         0.026080       0.306795       0.397136
--- N_RECORDS              7451.000000   14603.000000    7692.000000

--- MTN 3.2 Flag Means ---

                             KMX | 2026 Q1  KMX | 2026 Q2  KMX | 2026 Q3
job_time_flag                     0.115689       0.112374       0.119085
low_fico_flag                     0.000134       0.000000       0.000000
high_model_score_flag             0.309489       0.316579       0.345424
low_vantage_flag                  0.016508       0.011641       0.009360
normal_pti_flag                   0.902295       0.894679       0.891316
high_pti_tier_1_flag              0.064018       0.070876       0.067733
high_pti_tier_2_flag              0.030600       0.031980       0.037702
high_pti_tier_3_flag              0.003087       0.002465       0.003250
existing_dq_flag                  0.130050       0.133055       0.123115
seasonal_employment_flag          0.007247       0.008834       0.008190
secured_credit_flag               0.507851       0.451825       0.401586
kmx_auth_tradelines_flag          0.035029       0.045813       0.046022
null_fico_w_vantage_flag          0.960945       0.974389       0.879485
null_fico_null_vantage_flag       0.025097       0.025063       0.120125
soft_pull_flag                    0.874379       0.844621       0.840874
narrowed_soft_pull_flag           0.096900       0.099979       0.112454
fraud_adjustment_mean             0.999423       1.017747       1.014585
continuous_vehicle_age_mean       4.966145       4.794637       4.808546
kmx_npc_flag                      0.997718       0.627268       0.614015
high_pti_npc                      0.097705       0.105321       0.108684
student_loan_flag                 0.226010       0.210231       0.192148
high_sales_price_flag             0.117568       0.182086       0.187467
driver_flag                       0.001476       0.001027       0.001300
louisiana_flag                    0.005368       0.002808       0.003900
georgia_flag                      0.083613       0.077313       0.069813
txca_flag                         0.321299       0.317880       0.325143
chime_flag                        0.323447       0.255632       0.232449
low_bureau_flag                   0.042947       0.033212       0.027821
cd_perc_flag                      0.120789       0.129357       0.144826
open_tl_flag                      0.096766       0.094022       0.083983
mtn_3_1_flag                      0.000000       0.000000       0.000000
mtn_model_3.0_pct                 0.000000       0.000000       0.000000
mtn_model_3.1_pct                 0.000000       0.000000       0.000000
mtn_model_3.2_pct                 1.000000       1.000000       1.000000
mtn_model_4.1_pct                 0.000000       0.000000       0.000000
soft_pull_pct_3.1+                0.874379       0.844621       0.840874
low_bureau_flag_sp                0.043592       0.033404       0.027211
low_bureau_flag_hp                0.038462       0.032173       0.031046
open_tl_flag_sp                   0.094551       0.089752       0.084570
open_tl_flag_hp                   0.112179       0.117232       0.080882
cd_perc_flag_sp                   0.120798       0.129479       0.145331
cd_perc_flag_hp                   0.120726       0.128691       0.142157
--- N_RECORDS                  7451.000000   14603.000000    7692.000000

--- MTN 3.2 Gross Loss Attribution ---

                               KMX | 2026 Q1  KMX | 2026 Q2  KMX | 2026 Q3
Low FICO (3.0)                     -0.000000      -0.000000      -0.000000
Low Vantage (3.0)                  -0.000000      -0.000000      -0.000000
High PTI (3.0)                     -0.000000      -0.000000      -0.000000
Loss Scale Div (3.0)               -0.000000      -0.000000      -0.000000
Secured Credit (3.0)               -0.000000      -0.000000      -0.000000
Auth Tradelines (3.0)              -0.000000      -0.000000      -0.000000
Soft Pull (3.0)                    -0.000000      -0.000000      -0.000000
Fraud Adjustment                    0.014540      -0.441456      -0.361044
Clip (3.0)                         -0.000000      -0.000000      -0.000000
Vehicle Age (3.0)                  -0.000000      -0.000000      -0.000000
NPC                                -0.022224      -0.022476      -0.034315
Student Loans                       0.221595       0.285804       0.344271
High Sales Price (4.1)             -0.000000      -0.000000      -0.000000
Driver Flag                        -0.005842      -0.004029      -0.004900
Louisiana                          -0.047729      -0.024729      -0.033292
Georgia                            -0.210800      -0.195558      -0.174557
TX / CA                             0.617026       0.602151       0.617085
State Counter                      -0.154361      -0.155478      -0.149622
Secured Credit / Chime (3.1+)      -1.594548      -1.122399      -0.949824
Job Time (3.1+)                    -0.368205      -0.353024      -0.381000
Existing DQ (3.1+)                 -0.091329      -0.099179      -0.077018
Employment Type (3.1+)             -0.018815      -0.022995      -0.021323
Auth Tradelines (3.1+)              0.201832       0.182970       0.181029
Low Bureau (SP, 3.1+)               0.117444       0.136696       0.149613
Open TL (SP, 3.1+)                  0.155565       0.154352       0.163320
Low Bureau (HP, 3.1+)               0.039416       0.050871       0.052954
Open TL (HP, 3.1+)                  0.048873       0.041318       0.094600
HP Interaction (3.1+)               0.011552       0.010730       0.007179
CD Perc (SP, 3.1/3.2)               0.282534       0.234847       0.190296
CD Perc (HP, 3.1/3.2)               0.023653       0.016552       0.001180
CD Perc (SP, 4.1)                  -0.000000      -0.000000      -0.000000
CD Perc (HP, 4.1)                  -0.000000      -0.000000      -0.000000
Blanket Adjustment (HP, 3.1+)       0.290400       0.353913       0.354149
Clip (3.1+)                         0.114926       0.180908       0.162958
--- Population Weighting            0.400577       0.497007       0.265397
--- TOTAL (RAGU GLI)                0.026080       0.306795       0.397136

============================================================
  DIAGNOSTICS: MTN 4.1
============================================================

============================================================
  KMX 2025 Q4 (MTN 4.1)  (n=218)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.013761  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.073394  tier2: 0.064220  tier3: 0.000000  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.307339  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.032110  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.876147  narrowed: 0.133028  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.987752  | loss_multiplier mean: 0.987752
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.987752
14_veh_age  | continuous_age mean: 4.291284  | loss_multiplier mean: 0.987752
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.137615  | loss_multiplier mean: 0.992831
16_stu_loan | flag mean: 0.201835  | loss_multiplier mean: 0.980903
17_hi_price | flag mean: 0.091743  | loss_multiplier mean: 0.980731
18_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.980731
19_louisiana| flag mean: 0.004587  | loss_multiplier mean: 0.982226
20_georgia  | flag mean: 0.087156  | loss_multiplier mean: 0.990611
21_txca     | flag mean: 0.334862  | loss_multiplier mean: 0.967414
22_st_cntr  | no state adj: 0.573394  | loss_multiplier mean: 0.972927
23_sec_cr31 | chime mean: 0.137615  | loss_multiplier mean: 0.983961
24_job_t_31 | flag mean: 0.142202  | loss_multiplier mean: 1.003028
25_dq_31    | flag mean: 0.165138  | loss_multiplier mean: 1.011707
26_emp_31   | seasonal: 0.009174  | loss_multiplier mean: 1.012726
27_auth_31  | flag mean: 0.032110  | loss_multiplier mean: 1.004506
28a_sp_lb   | SP pct: 0.876147  low_bureau(SP): 0.078534  | loss_multiplier mean: 1.003493
28b_sp_otl  | open_tl(SP): 0.162304  | loss_multiplier mean: 1.006712
28c_hp_lb   | HP pct: 0.123853  low_bureau(HP): 0.111111  | loss_multiplier mean: 1.006679
28d_hp_otl  | open_tl(HP): 0.111111  | loss_multiplier mean: 1.004754
28e_hp_int  | HP cd_perc & open_tl pct: 0.009174  | loss_multiplier mean: 1.002977
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.002977
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.002977
28h_sp_cdp  | SP 4.1 pct: 0.876147  cd_perc(SP): 0.178010  | loss_multiplier mean: 1.010701
28i_hp_cdp  | HP 4.1 pct: 0.123853  cd_perc(HP): 0.259259  | loss_multiplier mean: 1.013681
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.002369
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.001191

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.001191  (n=218)
  bb_populated: 218 / 218  wtd_mult: 1.006222  ragu_gli: -0.1556

============================================================
  KMX 2026 Q1 (MTN 4.1)  (n=2505)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000399  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.019960  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.086627  tier2: 0.031936  tier3: 0.002395  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.427146  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.035130  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.876248  narrowed: 0.097804  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 0.995800  | loss_multiplier mean: 0.995800
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.995800
14_veh_age  | continuous_age mean: 4.249900  | loss_multiplier mean: 0.995800
15_npc      | npc_flag mean: 1.000000  high_pti_npc mean: 0.120958  | loss_multiplier mean: 0.999133
16_stu_loan | flag mean: 0.235130  | loss_multiplier mean: 0.991718
17_hi_price | flag mean: 0.130539  | loss_multiplier mean: 1.000469
18_driver   | flag mean: 0.001996  | loss_multiplier mean: 1.000757
19_louisiana| flag mean: 0.009182  | loss_multiplier mean: 1.003979
20_georgia  | flag mean: 0.076647  | loss_multiplier mean: 1.011569
21_txca     | flag mean: 0.305389  | loss_multiplier mean: 0.987962
22_st_cntr  | no state adj: 0.608782  | loss_multiplier mean: 0.993562
23_sec_cr31 | chime mean: 0.236327  | loss_multiplier mean: 1.031392
24_job_t_31 | flag mean: 0.120958  | loss_multiplier mean: 1.047219
25_dq_31    | flag mean: 0.160479  | loss_multiplier mean: 1.054889
26_emp_31   | seasonal: 0.007186  | loss_multiplier mean: 1.055619
27_auth_31  | flag mean: 0.035130  | loss_multiplier mean: 1.047268
28a_sp_lb   | SP pct: 0.876248  low_bureau(SP): 0.048747  | loss_multiplier mean: 1.042989
28b_sp_otl  | open_tl(SP): 0.102506  | loss_multiplier mean: 1.037772
28c_hp_lb   | HP pct: 0.123752  low_bureau(HP): 0.045161  | loss_multiplier mean: 1.036441
28d_hp_otl  | open_tl(HP): 0.100000  | loss_multiplier mean: 1.034017
28e_hp_int  | HP cd_perc & open_tl pct: 0.001597  | loss_multiplier mean: 1.033730
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.033730
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.033730
28h_sp_cdp  | SP 4.1 pct: 0.876248  cd_perc(SP): 0.121185  | loss_multiplier mean: 1.038785
28i_hp_cdp  | HP 4.1 pct: 0.123752  cd_perc(HP): 0.161290  | loss_multiplier mean: 1.040568
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.028892
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.023606

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.023606  (n=2505)
  bb_populated: 2478 / 2505  wtd_mult: 1.032710  ragu_gli: -0.8178

============================================================
  KMX 2026 Q2 (MTN 4.1)  (n=3041)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.013811  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.060506  tier2: 0.033870  tier3: 0.001644  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.399540  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.036830  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.846761  narrowed: 0.109175  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.011010  | loss_multiplier mean: 1.011010
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.011010
14_veh_age  | continuous_age mean: 4.398608  | loss_multiplier mean: 1.011010
15_npc      | npc_flag mean: 0.648471  high_pti_npc mean: 0.096021  | loss_multiplier mean: 1.011809
16_stu_loan | flag mean: 0.257481  | loss_multiplier mean: 1.007036
17_hi_price | flag mean: 0.150937  | loss_multiplier mean: 1.019482
18_driver   | flag mean: 0.000329  | loss_multiplier mean: 1.019528
19_louisiana| flag mean: 0.005261  | loss_multiplier mean: 1.021360
20_georgia  | flag mean: 0.067083  | loss_multiplier mean: 1.028245
21_txca     | flag mean: 0.317001  | loss_multiplier mean: 1.002416
22_st_cntr  | no state adj: 0.610654  | loss_multiplier mean: 1.007885
23_sec_cr31 | chime mean: 0.220322  | loss_multiplier mean: 1.042442
24_job_t_31 | flag mean: 0.109175  | loss_multiplier mean: 1.055839
25_dq_31    | flag mean: 0.157514  | loss_multiplier mean: 1.063275
26_emp_31   | seasonal: 0.007892  | loss_multiplier mean: 1.064060
27_auth_31  | flag mean: 0.036830  | loss_multiplier mean: 1.055721
28a_sp_lb   | SP pct: 0.846761  low_bureau(SP): 0.043107  | loss_multiplier mean: 1.050820
28b_sp_otl  | open_tl(SP): 0.102524  | loss_multiplier mean: 1.046201
28c_hp_lb   | HP pct: 0.153239  low_bureau(HP): 0.047210  | loss_multiplier mean: 1.044634
28d_hp_otl  | open_tl(HP): 0.113734  | loss_multiplier mean: 1.042750
28e_hp_int  | HP cd_perc & open_tl pct: 0.002960  | loss_multiplier mean: 1.042134
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.042134
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.042134
28h_sp_cdp  | SP 4.1 pct: 0.846761  cd_perc(SP): 0.140971  | loss_multiplier mean: 1.048033
28i_hp_cdp  | HP 4.1 pct: 0.153239  cd_perc(HP): 0.145923  | loss_multiplier mean: 1.050062
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.035630
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.027943

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.027943  (n=3041)
  bb_populated: 3025 / 3041  wtd_mult: 1.031611  ragu_gli: -0.7903

============================================================
  KMX 2026 Q3 (MTN 4.1)  (n=2070)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_low_vant | flag mean: 0.006763  | loss_multiplier mean: 1.000000
04_high_pti | tier1: 0.069565  tier2: 0.032850  tier3: 0.002415  | loss_multiplier mean: 1.000000
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 1.000000
08_sec_cred | flag mean: 0.367633  | loss_multiplier mean: 1.000000
09_auth_tl  | flag mean: 0.036232  | loss_multiplier mean: 1.000000
11_soft_pll | flag mean: 0.840580  narrowed: 0.121739  | loss_multiplier mean: 1.000000
12_fraud    | fraud_adj mean: 1.009473  | loss_multiplier mean: 1.009473
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 1.009473
14_veh_age  | continuous_age mean: 4.510306  | loss_multiplier mean: 1.009473
15_npc      | npc_flag mean: 0.495169  high_pti_npc mean: 0.104831  | loss_multiplier mean: 1.010621
16_stu_loan | flag mean: 0.249275  | loss_multiplier mean: 1.004782
17_hi_price | flag mean: 0.151208  | loss_multiplier mean: 1.017767
18_driver   | flag mean: 0.000966  | loss_multiplier mean: 1.017919
19_louisiana| flag mean: 0.010628  | loss_multiplier mean: 1.021582
20_georgia  | flag mean: 0.060386  | loss_multiplier mean: 1.027850
21_txca     | flag mean: 0.334300  | loss_multiplier mean: 1.001773
22_st_cntr  | no state adj: 0.594686  | loss_multiplier mean: 1.007047
23_sec_cr31 | chime mean: 0.201932  | loss_multiplier mean: 1.035580
24_job_t_31 | flag mean: 0.125604  | loss_multiplier mean: 1.052806
25_dq_31    | flag mean: 0.150725  | loss_multiplier mean: 1.059438
26_emp_31   | seasonal: 0.007246  | loss_multiplier mean: 1.060190
27_auth_31  | flag mean: 0.036232  | loss_multiplier mean: 1.051788
28a_sp_lb   | SP pct: 0.840580  low_bureau(SP): 0.037931  | loss_multiplier mean: 1.046531
28b_sp_otl  | open_tl(SP): 0.098276  | loss_multiplier mean: 1.041044
28c_hp_lb   | HP pct: 0.159420  low_bureau(HP): 0.027273  | loss_multiplier mean: 1.038667
28d_hp_otl  | open_tl(HP): 0.081818  | loss_multiplier mean: 1.034766
28e_hp_int  | HP cd_perc & open_tl pct: 0.002899  | loss_multiplier mean: 1.034214
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 1.034214
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 1.034214
28h_sp_cdp  | SP 4.1 pct: 0.840580  cd_perc(SP): 0.157471  | loss_multiplier mean: 1.040612
28i_hp_cdp  | HP 4.1 pct: 0.159420  cd_perc(HP): 0.184848  | loss_multiplier mean: 1.043255
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 1.028492
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 1.021891

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = nan  (n=0)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = 1.021891  (n=2070)
  bb_populated: 1963 / 2070  wtd_mult: 1.032802  ragu_gli: -0.8201

--- MTN 4.1 Multiplier Steps ---

,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2,KMX | 2026 Q3
00_initial,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.000000,1.000000,1.000000,1.000000
04_high_pti_3.0,1.000000,1.000000,1.000000,1.000000
07_loss_scale_div_3.0,1.000000,1.000000,1.000000,1.000000
08_secured_credit_3.0,1.000000,1.000000,1.000000,1.000000
09_auth_tradelines_3.0,1.000000,1.000000,1.000000,1.000000
11_soft_pull_3.0,1.000000,1.000000,1.000000,1.000000
12_fraud_all,0.987752,0.995800,1.011010,1.009473
13_clip_3.0,0.987752,0.995800,1.011010,1.009473
14_vehicle_age_3.0,0.987752,0.995800,1.011010,1.009473
15_npc_all,0.992831,0.999133,1.011809,1.010621
16_student_loans_all,0.980903,0.991718,1.007036,1.004782
17_high_sales_price_4.1,0.980731,1.000469,1.019482,1.017767
18_driver_flag_all,0.980731,1.000757,1.019528,1.017919
19_louisiana_all,0.982226,1.003979,1.021360,1.021582
20_georgia_all,0.990611,1.011569,1.028245,1.027850
21_txca_all,0.967414,0.987962,1.002416,1.001773
22_state_counter_all,0.972927,0.993562,1.007885,1.007047
23_secured_credit_3.1+,0.983961,1.031392,1.042442,1.035580
24_job_time_3.1+,1.003028,1.047219,1.055839,1.052806
25_existing_dq_3.1+,1.011707,1.054889,1.063275,1.059438
26_employment_3.1+,1.012726,1.055619,1.064060,1.060190
27_auth_tradelines_3.1+,1.004506,1.047268,1.055721,1.051788
28a_sp_low_bureau_3.1+,1.003493,1.042989,1.050820,1.046531
28b_sp_open_tl_3.1+,1.006712,1.037772,1.046201,1.041044
28c_hp_low_bureau_3.1+,1.006679,1.036441,1.044634,1.038667
28d_hp_open_tl_3.1+,1.004754,1.034017,1.042750,1.034766
28e_hp_interaction_3.1+,1.002977,1.033730,1.042134,1.034214
28f_sp_cd_perc_3.1/3.2,1.002977,1.033730,1.042134,1.034214
28g_hp_cd_perc_3.1/3.2,1.002977,1.033730,1.042134,1.034214
28h_sp_cd_perc_4.1,1.010701,1.038785,1.048033,1.040612
28i_hp_cd_perc_4.1,1.013681,1.040568,1.050062,1.043255
28j_blanket_hp_3.1+,1.002369,1.028892,1.035630,1.028492
29_final_clip_3.1+,1.001191,1.023606,1.027943,1.021891
--- FINAL_MULT (mean),1.001191,1.023606,1.027943,1.021891
--- WTD_MULT_RAGU,1.006222,1.032710,1.031611,1.032802
--- GROSS_LOSS_IMPACT,-0.155561,-0.817758,-0.790265,-0.820050
--- N_RECORDS,218.000000,2505.000000,3041.000000,2070.000000

--- MTN 4.1 Flag Means ---

,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2,KMX | 2026 Q3
job_time_flag,0.142202,0.120958,0.109175,0.125604
low_fico_flag,0.000000,0.000399,0.000000,0.000000
high_model_score_flag,0.298165,0.340918,0.381782,0.389855
low_vantage_flag,0.013761,0.019960,0.013811,0.006763
normal_pti_flag,0.862385,0.879042,0.903979,0.895169
high_pti_tier_1_flag,0.073394,0.086627,0.060506,0.069565
high_pti_tier_2_flag,0.064220,0.031936,0.033870,0.032850
high_pti_tier_3_flag,0.000000,0.002395,0.001644,0.002415
existing_dq_flag,0.165138,0.160479,0.157514,0.150725
seasonal_employment_flag,0.009174,0.007186,0.007892,0.007246
secured_credit_flag,0.307339,0.427146,0.399540,0.367633
kmx_auth_tradelines_flag,0.032110,0.035130,0.036830,0.036232
null_fico_w_vantage_flag,0.894495,0.950898,0.969747,0.902415
null_fico_null_vantage_flag,0.073394,0.025549,0.029924,0.097101
soft_pull_flag,0.876147,0.876248,0.846761,0.840580
narrowed_soft_pull_flag,0.133028,0.097804,0.109175,0.121739
fraud_adjustment_mean,0.987752,0.995800,1.011010,1.009473
continuous_vehicle_age_mean,4.291284,4.249900,4.398608,4.510306
kmx_npc_flag,1.000000,1.000000,0.648471,0.495169
high_pti_npc,0.137615,0.120958,0.096021,0.104831
student_loan_flag,0.201835,0.235130,0.257481,0.249275
high_sales_price_flag,0.091743,0.130539,0.150937,0.151208
driver_flag,0.000000,0.001996,0.000329,0.000966
louisiana_flag,0.004587,0.009182,0.005261,0.010628
georgia_flag,0.087156,0.076647,0.067083,0.060386
txca_flag,0.334862,0.305389,0.317001,0.334300
chime_flag,0.137615,0.236327,0.220322,0.201932
low_bureau_flag,0.082569,0.048303,0.043736,0.036232
cd_perc_flag,0.188073,0.126148,0.141730,0.161836
open_tl_flag,0.155963,0.102196,0.104242,0.095652
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,0.000000,0.000000,0.000000,0.000000
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000
mtn_model_4.1_pct,1.000000,1.000000,1.000000,1.000000
soft_pull_pct_3.1+,0.876147,0.876248,0.846761,0.840580
low_bureau_flag_sp,0.078534,0.048747,0.043107,0.037931
low_bureau_flag_hp,0.111111,0.045161,0.047210,0.027273
open_tl_flag_sp,0.162304,0.102506,0.102524,0.098276
open_tl_flag_hp,0.111111,0.100000,0.113734,0.081818
cd_perc_flag_sp,0.178010,0.121185,0.140971,0.157471
cd_perc_flag_hp,0.259259,0.161290,0.145923,0.184848
--- N_RECORDS,218.000000,2505.000000,3041.000000,2070.000000

--- MTN 4.1 Gross Loss Attribution ---

,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2,KMX | 2026 Q3
Low FICO (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,-0.000000,-0.000000,-0.000000
High PTI (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Loss Scale Div (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Secured Credit (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Auth Tradelines (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Soft Pull (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Fraud Adjustment,0.308267,0.106448,-0.277541,-0.238292
Clip (3.0),-0.000000,-0.000000,-0.000000,-0.000000
Vehicle Age (3.0),-0.000000,-0.000000,-0.000000,-0.000000
NPC,-0.128282,-0.084516,-0.020026,-0.028722
Student Loans,0.302340,0.188418,0.119850,0.146450
High Sales Price (4.1),0.004395,-0.222215,-0.311358,-0.324518
Driver Flag,-0.000000,-0.007270,-0.001154,-0.003765
Louisiana,-0.038112,-0.081317,-0.045499,-0.090783
Georgia,-0.212637,-0.190493,-0.170301,-0.154582
TX / CA,0.592736,0.597291,0.644851,0.649440
State Counter,-0.142147,-0.142981,-0.137898,-0.132692
Secured Credit / Chime (3.1+),-0.282098,-0.945188,-0.854533,-0.706106
Job Time (3.1+),-0.480087,-0.385189,-0.323665,-0.416945
Existing DQ (3.1+),-0.215514,-0.184584,-0.177892,-0.158689
Employment Type (3.1+),-0.025183,-0.017489,-0.018710,-0.017942
Auth Tradelines (3.1+),0.203853,0.200877,0.199425,0.201099
"Low Bureau (SP, 3.1+)",0.025255,0.103571,0.117957,0.126637
"Open TL (SP, 3.1+)",-0.080128,0.126835,0.111657,0.132841
"Low Bureau (HP, 3.1+)",0.000819,0.032455,0.037980,0.057778
"Open TL (HP, 3.1+)",0.047896,0.059225,0.045768,0.095080
HP Interaction (3.1+),0.044268,0.007029,0.014984,0.013499
"CD Perc (SP, 3.1/3.2)",-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (HP, 3.1/3.2)",-0.000000,-0.000000,-0.000000,-0.000000
"CD Perc (SP, 4.1)",-0.191906,-0.123395,-0.143069,-0.155867
"CD Perc (HP, 4.1)",-0.073642,-0.043380,-0.049047,-0.064101
"Blanket Adjustment (HP, 3.1+)",0.280717,0.285432,0.350798,0.360192
Clip (3.1+),0.029406,0.130289,0.188858,0.162711
--- Population Weighting,-0.125776,-0.227611,-0.091698,-0.272773
--- TOTAL (RAGU GLI),-0.155561,-0.817758,-0.790265,-0.820050

============================================================
  DIAGNOSTICS: All KMX
============================================================

============================================================
  KMX 2023 Q1 (All KMX)  (n=14355)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.082132  | loss_multiplier mean: 1.019539
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.019539
04_high_pti | tier1: 0.099060  tier2: 0.047092  tier3: 0.003622  | loss_multiplier mean: 1.031056
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.966313
08_sec_cred | flag mean: 0.182375  | loss_multiplier mean: 0.966580
09_auth_tl  | flag mean: 0.039429  | loss_multiplier mean: 0.963798
11_soft_pll | flag mean: 0.635040  narrowed: 0.099060  | loss_multiplier mean: 0.940376
12_fraud    | fraud_adj mean: 1.003439  | loss_multiplier mean: 0.943189
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.941898
14_veh_age  | continuous_age mean: 6.565430  | loss_multiplier mean: 0.934088
15_npc      | npc_flag mean: 0.641519  high_pti_npc mean: 0.149774  | loss_multiplier mean: 0.938013
16_stu_loan | flag mean: 0.042076  | loss_multiplier mean: 0.905938
17_hi_price | flag mean: 0.081574  | loss_multiplier mean: 0.905938
18_driver   | flag mean: 0.008638  | loss_multiplier mean: 0.907121
19_louisiana| flag mean: 0.009822  | loss_multiplier mean: 0.910278
20_georgia  | flag mean: 0.097388  | loss_multiplier mean: 0.919294
21_txca     | flag mean: 0.277255  | loss_multiplier mean: 0.904945
22_st_cntr  | no state adj: 0.615535  | loss_multiplier mean: 0.910862
23_sec_cr31 | chime mean: 0.179519  | loss_multiplier mean: 0.935816
24_job_t_31 | flag mean: 0.246883  | loss_multiplier mean: 0.977190
25_dq_31    | flag mean: 0.084291  | loss_multiplier mean: 0.976281
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.976281
27_auth_31  | flag mean: 0.039429  | loss_multiplier mean: 0.976281
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.976281
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.976281
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.976281
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.976281
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.976281
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.976281
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.976281
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.976281
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.976281
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.976281
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.976281

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.976281  (n=14355)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 12624 / 14355  wtd_mult: 0.956887  ragu_gli: 1.0778

============================================================
  KMX 2023 Q2 (All KMX)  (n=12711)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.061600  | loss_multiplier mean: 1.014565
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.014565
04_high_pti | tier1: 0.104319  tier2: 0.042247  tier3: 0.004878  | loss_multiplier mean: 1.026466
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.962011
08_sec_cred | flag mean: 0.253167  | loss_multiplier mean: 0.965348
09_auth_tl  | flag mean: 0.046023  | loss_multiplier mean: 0.963671
11_soft_pll | flag mean: 0.655338  narrowed: 0.118795  | loss_multiplier mean: 0.941918
12_fraud    | fraud_adj mean: 1.003718  | loss_multiplier mean: 0.945137
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.943470
14_veh_age  | continuous_age mean: 6.538267  | loss_multiplier mean: 0.935178
15_npc      | npc_flag mean: 0.638738  high_pti_npc mean: 0.151444  | loss_multiplier mean: 0.939283
16_stu_loan | flag mean: 0.051215  | loss_multiplier mean: 0.908314
17_hi_price | flag mean: 0.122335  | loss_multiplier mean: 0.908314
18_driver   | flag mean: 0.009126  | loss_multiplier mean: 0.909531
19_louisiana| flag mean: 0.009126  | loss_multiplier mean: 0.912457
20_georgia  | flag mean: 0.096216  | loss_multiplier mean: 0.921457
21_txca     | flag mean: 0.268508  | loss_multiplier mean: 0.906401
22_st_cntr  | no state adj: 0.626151  | loss_multiplier mean: 0.912323
23_sec_cr31 | chime mean: 0.168515  | loss_multiplier mean: 0.934826
24_job_t_31 | flag mean: 0.227519  | loss_multiplier mean: 0.972689
25_dq_31    | flag mean: 0.073716  | loss_multiplier mean: 0.970635
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.970635
27_auth_31  | flag mean: 0.046023  | loss_multiplier mean: 0.970635
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.970635
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.970635
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.970635
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.970635
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.970635
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.970635
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.970635
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.970635
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.970635
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.970635
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.970635

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.970635  (n=12711)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 11597 / 12711  wtd_mult: 0.948335  ragu_gli: 1.2916

============================================================
  KMX 2023 Q3 (All KMX)  (n=12892)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.052280  | loss_multiplier mean: 1.012375
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.012375
04_high_pti | tier1: 0.111154  tier2: 0.046385  tier3: 0.005197  | loss_multiplier mean: 1.025155
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.960783
08_sec_cred | flag mean: 0.241390  | loss_multiplier mean: 0.963220
09_auth_tl  | flag mean: 0.049410  | loss_multiplier mean: 0.962134
11_soft_pll | flag mean: 0.685386  narrowed: 0.134657  | loss_multiplier mean: 0.939997
12_fraud    | fraud_adj mean: 1.003496  | loss_multiplier mean: 0.943049
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.941399
14_veh_age  | continuous_age mean: 6.554944  | loss_multiplier mean: 0.933347
15_npc      | npc_flag mean: 0.634735  high_pti_npc mean: 0.162737  | loss_multiplier mean: 0.938359
16_stu_loan | flag mean: 0.023193  | loss_multiplier mean: 0.903832
17_hi_price | flag mean: 0.122014  | loss_multiplier mean: 0.903832
18_driver   | flag mean: 0.009696  | loss_multiplier mean: 0.905136
19_louisiana| flag mean: 0.008688  | loss_multiplier mean: 0.907902
20_georgia  | flag mean: 0.106655  | loss_multiplier mean: 0.917642
21_txca     | flag mean: 0.266056  | loss_multiplier mean: 0.902651
22_st_cntr  | no state adj: 0.618601  | loss_multiplier mean: 0.908509
23_sec_cr31 | chime mean: 0.155911  | loss_multiplier mean: 0.926275
24_job_t_31 | flag mean: 0.235805  | loss_multiplier mean: 0.965305
25_dq_31    | flag mean: 0.068647  | loss_multiplier mean: 0.962555
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.962555
27_auth_31  | flag mean: 0.049410  | loss_multiplier mean: 0.962555
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.962555
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.962555
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.962555
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.962555
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.962555
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.962555
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.962555
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.962555
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.962555
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.962555
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.962555

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.962555  (n=12892)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 6455 / 12892  wtd_mult: 0.941626  ragu_gli: 1.4594

============================================================
  KMX 2023 Q4 (All KMX)  (n=10521)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.048379  | loss_multiplier mean: 1.010877
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.010877
04_high_pti | tier1: 0.101796  tier2: 0.055508  tier3: 0.006558  | loss_multiplier mean: 1.024821
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.960470
08_sec_cred | flag mean: 0.228781  | loss_multiplier mean: 0.962390
09_auth_tl  | flag mean: 0.043342  | loss_multiplier mean: 0.960322
11_soft_pll | flag mean: 0.703640  narrowed: 0.133637  | loss_multiplier mean: 0.937221
12_fraud    | fraud_adj mean: 1.003709  | loss_multiplier mean: 0.940616
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.938917
14_veh_age  | continuous_age mean: 6.162453  | loss_multiplier mean: 0.923440
15_npc      | npc_flag mean: 0.627222  high_pti_npc mean: 0.163863  | loss_multiplier mean: 0.927403
16_stu_loan | flag mean: 0.036689  | loss_multiplier mean: 0.894829
17_hi_price | flag mean: 0.118905  | loss_multiplier mean: 0.894829
18_driver   | flag mean: 0.008079  | loss_multiplier mean: 0.895965
19_louisiana| flag mean: 0.008744  | loss_multiplier mean: 0.898652
20_georgia  | flag mean: 0.098185  | loss_multiplier mean: 0.907540
21_txca     | flag mean: 0.260241  | loss_multiplier mean: 0.892781
22_st_cntr  | no state adj: 0.632830  | loss_multiplier mean: 0.898701
23_sec_cr31 | chime mean: 0.151316  | loss_multiplier mean: 0.914987
24_job_t_31 | flag mean: 0.224693  | loss_multiplier mean: 0.951809
25_dq_31    | flag mean: 0.070145  | loss_multiplier mean: 0.949285
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.949285
27_auth_31  | flag mean: 0.043342  | loss_multiplier mean: 0.949285
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.949285
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.949285
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.949285
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.949285
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.949285
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.949285
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.949285
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.949285
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.949285
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.949285
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.949285

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.949285  (n=10521)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 5463 / 10521  wtd_mult: 0.931097  ragu_gli: 1.7226

============================================================
  KMX 2024 Q1 (All KMX)  (n=18128)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.039331  | loss_multiplier mean: 1.008490
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.008490
04_high_pti | tier1: 0.081973  tier2: 0.044572  tier3: 0.003199  | loss_multiplier mean: 1.018635
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.954672
08_sec_cred | flag mean: 0.275044  | loss_multiplier mean: 0.959284
09_auth_tl  | flag mean: 0.032988  | loss_multiplier mean: 0.955397
11_soft_pll | flag mean: 0.750386  narrowed: 0.133936  | loss_multiplier mean: 0.931381
12_fraud    | fraud_adj mean: 0.992429  | loss_multiplier mean: 0.924281
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.923856
14_veh_age  | continuous_age mean: 6.131413  | loss_multiplier mean: 0.908135
15_npc      | npc_flag mean: 0.655174  high_pti_npc mean: 0.129744  | loss_multiplier mean: 0.910838
16_stu_loan | flag mean: 0.275485  | loss_multiplier mean: 0.908330
17_hi_price | flag mean: 0.085724  | loss_multiplier mean: 0.908330
18_driver   | flag mean: 0.005902  | loss_multiplier mean: 0.909122
19_louisiana| flag mean: 0.008385  | loss_multiplier mean: 0.911850
20_georgia  | flag mean: 0.097529  | loss_multiplier mean: 0.920952
21_txca     | flag mean: 0.271955  | loss_multiplier mean: 0.905966
22_st_cntr  | no state adj: 0.622132  | loss_multiplier mean: 0.912122
23_sec_cr31 | chime mean: 0.202560  | loss_multiplier mean: 0.944090
24_job_t_31 | flag mean: 0.186176  | loss_multiplier mean: 0.973827
25_dq_31    | flag mean: 0.081311  | loss_multiplier mean: 0.972452
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.972452
27_auth_31  | flag mean: 0.032988  | loss_multiplier mean: 0.972452
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.972452
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.972452
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.972452
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.972452
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.972452
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.972452
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.972452
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.972452
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.972452
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.972452
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.972452

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.972452  (n=18128)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 18120 / 18128  wtd_mult: 0.949570  ragu_gli: 1.2608

============================================================
  KMX 2024 Q2 (All KMX)  (n=13833)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.032242  | loss_multiplier mean: 1.006261
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.006261
04_high_pti | tier1: 0.081544  tier2: 0.047857  tier3: 0.005494  | loss_multiplier mean: 1.017855
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.953941
08_sec_cred | flag mean: 0.262055  | loss_multiplier mean: 0.958631
09_auth_tl  | flag mean: 0.039615  | loss_multiplier mean: 0.955863
11_soft_pll | flag mean: 0.748139  narrowed: 0.086749  | loss_multiplier mean: 0.931932
12_fraud    | fraud_adj mean: 0.989544  | loss_multiplier mean: 0.922186
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.921131
14_veh_age  | continuous_age mean: 5.257518  | loss_multiplier mean: 0.889292
15_npc      | npc_flag mean: 0.646787  high_pti_npc mean: 0.134895  | loss_multiplier mean: 0.892668
16_stu_loan | flag mean: 0.260609  | loss_multiplier mean: 0.888273
17_hi_price | flag mean: 0.125786  | loss_multiplier mean: 0.888273
18_driver   | flag mean: 0.005060  | loss_multiplier mean: 0.888973
19_louisiana| flag mean: 0.008892  | loss_multiplier mean: 0.891803
20_georgia  | flag mean: 0.096291  | loss_multiplier mean: 0.900581
21_txca     | flag mean: 0.276224  | loss_multiplier mean: 0.883894
22_st_cntr  | no state adj: 0.618593  | loss_multiplier mean: 0.889714
23_sec_cr31 | chime mean: 0.180800  | loss_multiplier mean: 0.914276
24_job_t_31 | flag mean: 0.163233  | loss_multiplier mean: 0.938786
25_dq_31    | flag mean: 0.080026  | loss_multiplier mean: 0.937249
26_emp_31   | seasonal: 0.000000  | loss_multiplier mean: 0.937249
27_auth_31  | flag mean: 0.039615  | loss_multiplier mean: 0.937249
28a_sp_lb   | SP pct: 0.000000  low_bureau(SP): nan  | loss_multiplier mean: 0.937249
28b_sp_otl  | open_tl(SP): nan  | loss_multiplier mean: 0.937249
28c_hp_lb   | HP pct: 0.000000  low_bureau(HP): nan  | loss_multiplier mean: 0.937249
28d_hp_otl  | open_tl(HP): nan  | loss_multiplier mean: 0.937249
28e_hp_int  | HP cd_perc & open_tl pct: 0.000000  | loss_multiplier mean: 0.937249
28f_sp_cdp  | SP 3.1/3.2 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.937249
28g_hp_cdp  | HP 3.1/3.2 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.937249
28h_sp_cdp  | SP 4.1 pct: 0.000000  cd_perc(SP): nan  | loss_multiplier mean: 0.937249
28i_hp_cdp  | HP 4.1 pct: 0.000000  cd_perc(HP): nan  | loss_multiplier mean: 0.937249
28j_blanket | HP 3.1+ /= 1.1  | loss_multiplier mean: 0.937249
29_final_31 | clip [0.75, 1.4] for MTN 3.1+  | loss_multiplier mean: 0.937249

--- Per MTN Model Means ---
mtn_model 3.0: mean loss_multiplier = 0.937249  (n=13833)
mtn_model 3.1: mean loss_multiplier = nan  (n=0)
mtn_model 3.2: mean loss_multiplier = nan  (n=0)
mtn_model 4.1: mean loss_multiplier = nan  (n=0)
  bb_populated: 13831 / 13833  wtd_mult: 0.912917  ragu_gli: 2.1771

============================================================
  KMX 2024 Q3 (All KMX)  (n=12991)
============================================================
00_initial  | loss_multiplier mean: 1.000000
02_low_fico | flag mean: 0.029559  | loss_multiplier mean: 1.005939
03_low_vant | flag mean: 0.000000  | loss_multiplier mean: 1.005939
04_high_pti | tier1: 0.077900  tier2: 0.046263  tier3: 0.005465  | loss_multiplier mean: 1.017173
07_scale_dv | dividing by (1 + 0.067)  | loss_multiplier mean: 0.953302
08_sec_cred | flag mean: 0.267108  | loss_multiplier mean: 0.958222
09_auth_tl  | flag mean: 0.040028  | loss_multiplier mean: 0.955562
11_soft_pll | flag mean: 0.755908  narrowed: 0.100377  | loss_multiplier mean: 0.931227
12_fraud    | fraud_adj mean: 0.995378  | loss_multiplier mean: 0.926978
13_clip_3.0 | clip [0.8, 1.2652]  | loss_multiplier mean: 0.925740
14_veh_age  | continuous_age mean: 5.451806  | loss_multiplier mean: 0.897287
15_npc      | npc_flag mean: 0.642137  high_pti_npc mean: 0.129628  | loss_multiplier mean: 0.899995
16_stu_loan | flag mean: 0.251482  | loss_multiplier mean: 0.894445
17_hi_price | flag mean: 0.117389  | loss_multiplier mean: 0.894445
18_driver   | flag mean: 0.004850  | loss_multiplier mean: 0.895115
19_louisiana| flag mean: 0.006389  | loss_multiplier mean: 0.897230
20_georgia  | flag mean: 0.100531  | loss_multiplier mean: 0.906479
21_txca     | flag mean: 0.282349  | loss_multiplier mean: 0.890029

,KMX | 2023 Q1,KMX | 2023 Q2,KMX | 2023 Q3,KMX | 2023 Q4,KMX | 2024 Q1,KMX | 2024 Q2,KMX | 2024 Q3,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2,KMX | 2026 Q3
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
02_low_fico_3.0,1.019539,1.014565,1.012375,1.010877,1.008490,1.006261,1.005939,1.004051,1.000124,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
03_low_vantage_3.0,1.019539,1.014565,1.012375,1.010877,1.008490,1.006261,1.005939,1.004056,1.000893,1.000980,1.000835,1.000631,1.000000,1.000000,1.000000
04_high_pti_3.0,1.031056,1.026466,1.025155,1.024821,1.018635,1.017855,1.017173,1.012270,1.005736,1.005199,1.004926,1.004294,1.000000,1.000000,1.000031
07_loss_scale_div_3.0,0.966313,0.962011,0.960783,0.960470,0.954672,0.953941,0.953302,0.965391,0.975877,0.974923,0.975132,0.981914,1.000000,1.000000,0.999734
08_secured_credit_3.0,0.966580,0.965348,0.963220,0.962390,0.959284,0.958631,0.958222,0.969338,0.981996,0.978173,0.978999,0.984892,1.000000,1.000000,0.999696
09_auth_tradelines_3.0,0.963798,0.963671,0.962134,0.960322,0.955397,0.955863,0.955562,0.966633,0.980062,0.976395,0.977146,0.984035,1.000000,1.000000,0.999652
11_soft_pull_3.0,0.940376,0.941918,0.939997,0.937221,0.931381,0.931932,0.931227,0.948834,0.969403,0.965123,0.966479,0.975781,1.000000,1.000000,0.999543
12_fraud_all,0.943189,0.945137,0.943049,0.940616,0.924281,0.922186,0.926978,0.945007,0.964628,0.959070,0.961657,0.975361,0.997482,1.016433,1.012998
13_clip_3.0,0.941898,0.943470,0.941399,0.938917,0.923856,0.921131,0.925740,0.943406,0.963873,0.958753,0.961289,0.974893,0.997482,1.016433,1.012998
14_vehicle_age_3.0,0.934088,0.935178,0.933347,0.923440,0.908135,0.889292,0.897287,0.920420,0.948046,0.944593,0.949273,0.965808,0.997482,1.016433,1.012689
15_npc_all,0.938013,0.939283,0.938359,0.927403,0.910838,0.892668,0.899995,0.923643,0.952038,0.947430,0.951628,0.967951,0.998150,1.017291,1.014035
16_student_loans_all,0.905938,0.908314,0.903832,0.894829,0.908330,0.888273,0.894445,0.925111,0.956600,0.944710,0.949258,0.956494,0.990115,1.006910,1.001718
17_high_sales_price_4.1,0.905938,0.908314,0.903832,0.894829,0.908330,0.888273,0.894445,0.925111,0.956600,0.944710,0.949258,0.956491,0.991069,1.008972,1.004459
18_driver_flag_all,0.907121,0.909531,0.905136,0.895965,0.909122,0.888973,0.895115,0.925537,0.956963,0.945010,0.949443,0.956727,0.991269,1.009126,1.004645
19_louisiana_all,0.910278,0.912457,0.907902,0.898652,0.911850,0.891803,0.897230,0.927601,0.958745,0.946747,0.951285,0.958945,0.993261,1.010459,1.006500
20_georgia_all,0.919294,0.921457,0.917642,0.907540,0.920952,0.900581,0.906479,0.937879,0.969918,0.956556,0.960927,0.966684,1.001203,1.018147,1.013368
21_txca_all,0.904945,0.906401,0.902651,0.892781,0.905966,0.883894,0.890029,0.922340,0.953934,0.939569,0.943971,0.946405,0.977650,0.993805,0.988385
22_state_counter_all,0.910862,0.912323,0.908509,0.898701,0.912122,0.889714,0.895857,0.928433,0.960307,0.945589,0.950065,0.952313,0.983611,0.999860,0.994178
23_secured_credit_3.1+,0.935816,0.934826,0.926275,0.914987,0.944090,0.914276,0.924400,0.954481,1.004099,0.956029,0.975480,0.972743,1.032762,1.043861,1.030287
24_job_time_3.1+,0.977190,0.972689,0.965305,0.951809,0.973827,0.938786,0.953457,0.982678,1.029673,0.970550,0.992428,0.992779,1.047236,1.058339,1.046488
25_existing_dq_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.982966,1.033955,0.971495,0.993366,0.994894,1.051744,1.063021,1.050388
26_employment_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.982966,1.034820,0.972148,0.994138,0.995662,1.052516,1.063952,1.051251
27_auth_tradelines_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.981095,1.030500,0.968355,0.990114,0.990777,1.044268,1.056119,1.043519
28a_sp_low_bureau_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.982905,1.029228,0.966195,0.987512,0.987739,1.039724,1.050537,1.037517
28b_sp_open_tl_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.981985,1.027018,0.964336,0.984513,0.985858,1.033406,1.044598,1.031052
28c_hp_low_bureau_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.981982,1.025208,0.962798,0.983300,0.984485,1.031801,1.042572,1.028836
28d_hp_open_tl_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.981409,1.022890,0.961795,0.981958,0.983255,1.029612,1.040915,1.024962
28e_hp_interaction_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.981128,1.022528,0.961381,0.981580,0.982925,1.029235,1.040444,1.024614
28f_sp_cd_perc_3.1/3.2,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.978597,1.013777,0.955470,0.977169,0.978685,1.020304,1.032259,1.018512
28g_hp_cd_perc_3.1/3.2,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.979272,1.011932,0.955348,0.978020,0.979182,1.019930,1.031627,1.018474
28h_sp_cd_perc_4.1,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.979272,1.011932,0.955348,0.978020,0.979306,1.020481,1.032604,1.019824
28i_hp_cd_perc_4.1,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.979272,1.011932,0.955348,0.978020,0.979354,1.020675,1.032940,1.020382
28j_blanket_hp_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.972243,0.999495,0.945369,0.968558,0.969747,1.008749,1.018608,1.006034
29_final_clip_3.1+,0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.970800,0.997491,0.946042,0.967115,0.968864,1.005778,1.011229,0.999525
--- FINAL_MULT (mean),0.976281,0.970635,0.962555,0.949285,0.972452,0.937249,0.951188,0.970800,0.997491,0.946042,0.967115,0.968864,1.005778,1.011229,0.999525
--- WTD_MULT_RAGU,0.956887,0.948335,0.941626,0.931097,0.949570,0.912917,0.924909,0.948547,0.978399,0.928593,0.950425,0.950245,0.992746,0.995388,0.994137
--- GROSS_LOSS_IMPACT,1.077815,1.291630,1.459354,1.722564,1.260756,2.177068,1.877280,1.286326,0.540014,1.785166,1.239374,1.243884,0.181344,0.115290,0.146563
--- N_RECORDS,14355.000000,12711.000000,12892.000000,10521.000000,18128.000000,13833.000000,12991.000000,12160.000000,18760.000000,15624.000000,15440.000000,13629.000000,22974.000000,18357.000000,9808.000000

--- All KMX Flag Means ---

,KMX | 2023 Q1,KMX | 2023 Q2,KMX | 2023 Q3,KMX | 2023 Q4,KMX | 2024 Q1,KMX | 2024 Q2,KMX | 2024 Q3,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2,KMX | 2026 Q3
job_time_flag,0.246883,0.227519,0.235805,0.224693,0.186176,0.163233,0.181741,0.178454,0.162154,0.116999,0.126101,0.142197,0.113215,0.111511,0.120922
low_fico_flag,0.082132,0.061600,0.052280,0.048379,0.039331,0.032242,0.029559,0.039638,0.001386,0.000000,0.000000,0.000000,0.000261,0.000000,0.000000
high_model_score_flag,0.221665,0.241916,0.234021,0.241422,0.197981,0.246873,0.230929,0.241283,0.237793,0.267857,0.259650,0.265904,0.304213,0.328812,0.355730
low_vantage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000740,0.014712,0.013313,0.010492,0.011740,0.016845,0.012257,0.008768
normal_pti_flag,0.850226,0.848556,0.837263,0.836137,0.870256,0.865105,0.870372,0.869326,0.860075,0.872440,0.878174,0.876146,0.900888,0.896497,0.892129
high_pti_tier_1_flag,0.099060,0.104319,0.111154,0.101796,0.081973,0.081544,0.077900,0.074342,0.084382,0.077573,0.073705,0.075648,0.065465,0.069183,0.068210
high_pti_tier_2_flag,0.047092,0.042247,0.046385,0.055508,0.044572,0.047857,0.046263,0.049013,0.049467,0.047043,0.044883,0.044024,0.030905,0.031977,0.036603
high_pti_tier_3_flag,0.003622,0.004878,0.005197,0.006558,0.003199,0.005494,0.005465,0.007319,0.006077,0.002944,0.003238,0.004182,0.002742,0.002342,0.003059
existing_dq_flag,0.084291,0.073716,0.068647,0.070145,0.081311,0.080026,0.073282,0.094984,0.130650,0.101639,0.101878,0.114095,0.135109,0.136515,0.128365
seasonal_employment_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008209,0.006848,0.007383,0.007924,0.007400,0.008553,0.007953
secured_credit_flag,0.182375,0.253167,0.241390,0.228781,0.275044,0.262055,0.267108,0.249836,0.329104,0.312340,0.359391,0.357473,0.465570,0.443537,0.392639
kmx_auth_tradelines_flag,0.039429,0.046023,0.049410,0.043342,0.032988,0.039615,0.040028,0.040543,0.038060,0.041347,0.039832,0.042997,0.037782,0.044343,0.043740
null_fico_w_vantage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.064474,0.920949,0.876152,0.927073,0.926554,0.956734,0.973035,0.880812
null_fico_null_vantage_flag,0.202786,0.189836,0.196556,0.197985,0.138625,0.146389,0.146101,0.116530,0.061834,0.123720,0.072927,0.066916,0.023853,0.026475,0.118781
soft_pull_flag,0.635040,0.655338,0.685386,0.703640,0.750386,0.748139,0.755908,0.738405,0.751706,0.796147,0.805246,0.834911,0.870158,0.845890,0.841048
narrowed_soft_pull_flag,0.099060,0.118795,0.134657,0.133637,0.133936,0.086749,0.100377,0.089309,0.047015,0.088838,0.113860,0.126128,0.104205,0.101160,0.114192
fraud_adjustment_mean,1.003439,1.003718,1.003496,1.003709,0.992429,0.989544,0.995378,0.995925,0.995162,0.993874,0.994979,0.999547,0.997482,1.016433,1.013457
continuous_vehicle_age_mean,6.565430,6.538267,6.554944,6.162453,6.131413,5.257518,5.451806,5.227762,4.912398,5.110892,5.334224,5.139366,4.724199,4.723389,4.739074
kmx_npc_flag,0.641519,0.638738,0.634735,0.627222,0.655174,0.646787,0.642137,0.637664,0.623561,0.616935,0.622604,0.614865,0.612431,0.606417,0.590742
high_pti_npc,0.149774,0.151444,0.162737,0.163863,0.129744,0.134895,0.129628,0.130674,0.139925,0.127560,0.121826,0.123854,0.099112,0.103503,0.107871
student_loan_flag,0.042076,0.051215,0.023193,0.036689,0.275485,0.260609,0.251482,0.303618,0.321588,0.267345,0.269689,0.203390,0.230652,0.218227,0.203303
high_sales_price_flag,0.081574,0.122335,0.122014,0.118905,0.085724,0.125786,0.117389,0.125822,0.123561,0.160522,0.152202,0.151295,0.127666,0.177153,0.179649
driver_flag,0.008638,0.009126,0.009696,0.008079,0.005902,0.005060,0.004850,0.003125,0.002505,0.002048,0.001295,0.001614,0.001349,0.000981,0.001223
louisiana_flag,0.009822,0.009126,0.008688,0.008744,0.008385,0.008892,0.006389,0.006332,0.005330,0.005184,0.005699,0.006604,0.005746,0.003759,0.005404
georgia_flag,0.097388,0.096216,0.106655,0.098185,0.097529,0.096291,0.100531,0.109375,0.115618,0.103175,0.100648,0.079830,0.079873,0.075339,0.067700
txca_flag,0.277255,0.268508,0.266056,0.260241,0.271955,0.276224,0.282349,0.262911,0.255011,0.278226,0.275130,0.316237,0.324280,0.317154,0.327080
chime_flag,0.179519,0.168515,0.155911,0.151316,0.202560,0.180800,0.194673,0.184868,0.241738,0.134537,0.184845,0.170225,0.272482,0.250259,0.224918
low_bureau_flag,0.174573,0.136260,0.122557,0.122327,0.128089,0.110099,0.105150,0.113076,0.047015,0.041027,0.038990,0.039988,0.045573,0.035191,0.029466
cd_perc_flag,0.205085,0.231610,0.251939,0.234578,0.217895,0.159329,0.186437,0.170970,0.089179,0.137289,0.172409,0.178590,0.131845,0.130740,0.148144
open_tl_flag,0.286311,0.260404,0.261868,0.258245,0.215192,0.215571,0.220383,0.184293,0.149307,0.160266,0.148187,0.149241,0.096631,0.097129,0.086154
mtn_3_1_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mtn_model_3.0_pct,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.734293,0.469776,0.476959,0.469560,0.352117,0.000000,0.000000,0.004690
mtn_model_3.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.265707,0.530224,0.523041,0.530440,0.631888,0.566641,0.038841,0.000000
mtn_model_3.2_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324323,0.795500,0.784258
mtn_model_4.1_pct,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015995,0.109036,0.165659,0.211052
soft_pull_pct_3.1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.721139,0.745752,0.786466,0.805006,0.836467,0.870158,0.845890,0.840811
low_bureau_flag_sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.172961,0.065112,0.043099,0.037464,0.040753,0.046621,0.035355,0.029483
low_bureau_flag_hp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.093230,0.035192,0.029799,0.040075,0.033934,0.038552,0.034288,0.030245
open_tl_flag_sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.108584,0.106767,0.109382,0.095556,0.114541,0.095043,0.093380,0.087476
open_tl_flag_hp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.128746,0.108343,0.122063,0.117095,0.116343,0.107275,0.117709,0.081081
cd_perc_flag_sp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.121030,0.065382,0.108449,0.134233,0.150961,0.130559,0.130796,0.147904
cd_perc_flag_hp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166482,0.103203,0.137536,0.165936,0.157895,0.140463,0.130435,0.151223
--- N_RECORDS,14355.000000,12711.000000,12892.000000,10521.000000,18128.000000,13833.000000,12991.000000,12160.000000,18760.000000,15624.000000,15440.000000,13629.000000,22974.000000,18357.000000,9808.000000

--- All KMX Gross Loss Attribution ---

,KMX | 2023 Q1,KMX | 2023 Q2,KMX | 2023 Q3,KMX | 2023 Q4,KMX | 2024 Q1,KMX | 2024 Q2,KMX | 2024 Q3,KMX | 2024 Q4,KMX | 2025 Q1,KMX | 2025 Q2,KMX | 2025 Q3,KMX | 2025 Q4,KMX | 2026 Q1,KMX | 2026 Q2,KMX | 2026 Q3
Low FICO (3.0),-0.477993,-0.356165,-0.301673,-0.263546,-0.208435,-0.151095,-0.144388,-0.099581,-0.003084,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Low Vantage (3.0),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000135,-0.019213,-0.023817,-0.020516,-0.015529,-0.000000,-0.000000,-0.000000
High PTI (3.0),-0.277491,-0.287250,-0.307722,-0.333731,-0.246767,-0.277318,-0.270816,-0.200698,-0.120504,-0.102290,-0.100302,-0.089926,-0.000000,-0.000000,-0.000764
Loss Scale Div (3.0),1.601970,1.597352,1.590727,1.579806,1.598839,1.569857,1.581375,1.168038,0.752507,0.743742,0.739976,0.554594,-0.000000,-0.000000,0.007410
Secured Credit (3.0),-0.006812,-0.085275,-0.062147,-0.048660,-0.118825,-0.118722,-0.125535,-0.100496,-0.156071,-0.080940,-0.097308,-0.074504,-0.000000,-0.000000,0.000963
Auth Tradelines (3.0),0.071188,0.042821,0.027663,0.052412,0.100122,0.069994,0.067795,0.068840,0.049208,0.044249,0.046582,0.021419,-0.000000,-0.000000,0.001097
Soft Pull (3.0),0.607725,0.562381,0.570964,0.593155,0.627634,0.613782,0.629037,0.457807,0.273056,0.282382,0.269875,0.207287,-0.000000,-0.000000,0.002709
Fraud Adjustment,-0.073788,-0.084049,-0.079508,-0.088069,0.188681,0.254483,0.111511,0.099539,0.123278,0.153000,0.122976,0.010592,0.063224,-0.409769,-0.334203
Clip (3.0),0.033836,0.043482,0.042960,0.044036,0.011338,0.027696,0.032586,0.041784,0.019548,0.008040,0.009393,0.011806,-0.000000,-0.000000,-0.000000
Vehicle Age (3.0),0.205696,0.217430,0.210691,0.404903,0.423132,0.851541,0.761230,0.607612,0.413396,0.361853,0.309271,0.230416,-0.000000,-0.000000,0.007638
NPC,-0.103598,-0.107862,-0.131365,-0.104315,-0.073277,-0.091715,-0.073478,-0.086104,-0.104900,-0.072915,-0.060926,-0.054558,-0.016803,-0.021208,-0.033190
Student Loans,0.859465,0.825786,0.919569,0.871024,0.067991,0.119471,0.150843,-0.039130,-0.119360,0.069925,0.061332,0.293014,0.202644,0.257849,0.305432
High Sales Price (4.1),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000071,-0.024150,-0.051426,-0.068287
Driver Flag,-0.032241,-0.032962,-0.035352,-0.030899,-0.021492,-0.019064,-0.018250,-0.011341,-0.009488,-0.007741,-0.004808,-0.006067,-0.005054,-0.003842,-0.004639
Louisiana,-0.085806,-0.079139,-0.074850,-0.072967,-0.073862,-0.076954,-0.057544,-0.054863,-0.046431,-0.044654,-0.047640,-0.056988,-0.050336,-0.033175,-0.046088
Georgia,-0.243476,-0.241757,-0.261731,-0.239746,-0.244887,-0.237096,-0.250093,-0.271428,-0.289300,-0.250664,-0.247958,-0.197791,-0.199661,-0.190558,-0.169988
TX / CA,0.388607,0.405802,0.404005,0.399434,0.404478,0.452743,0.446585,0.411546,0.414889,0.435762,0.437726,0.521722,0.596861,0.608350,0.623916
State Counter,-0.160966,-0.160402,-0.158678,-0.161017,-0.166963,-0.158886,-0.159160,-0.162214,-0.166248,-0.155332,-0.158225,-0.153147,-0.152407,-0.152704,-0.146075
Secured Credit / Chime (3.1+),-0.667653,-0.600194,-0.475037,-0.437487,-0.849257,-0.659199,-0.764811,-0.681572,-1.113430,-0.267041,-0.649060,-0.522336,-1.222568,-1.082700,-0.891698
Job Time (3.1+),-1.068673,-0.977953,-1.012368,-0.961143,-0.764582,-0.640415,-0.754681,-0.717168,-0.627973,-0.366588,-0.423515,-0.501725,-0.348940,-0.346271,-0.389955
Existing DQ (3.1+),0.022988,0.052070,0.069973,0.064685,0.034842,0.039662,0.058095,-0.007226,-0.103610,-0.023685,-0.023225,-0.052386,-0.107690,-0.110973,-0.092981
Employment Type (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.020892,-0.016332,-0.019107,-0.018987,-0.018410,-0.022008,-0.020526
Auth Tradelines (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.046927,0.104465,0.095059,0.099720,0.121032,0.197259,0.185771,0.184525
"Low Bureau (SP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.045383,0.030842,0.054331,0.064704,0.075586,0.109342,0.133212,0.144172
"Open TL (SP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.023048,0.053673,0.046828,0.074775,0.046893,0.152827,0.142526,0.156235
"Low Bureau (HP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.000084,0.044045,0.038825,0.030315,0.034312,0.038967,0.048822,0.053754
"Open TL (HP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.014372,0.056509,0.025340,0.033580,0.030767,0.053241,0.039986,0.094314
HP Interaction (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.007060,0.008847,0.010467,0.009482,0.008263,0.009186,0.011373,0.008481
"CD Perc (SP, 3.1/3.2)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.063636,0.214588,0.149995,0.110720,0.106382,0.218502,0.198557,0.149300
"CD Perc (HP, 3.1/3.2)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.017004,0.045480,0.003088,-0.021400,-0.012508,0.009199,0.015408,0.000925
"CD Perc (SP, 4.1)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.003105,-0.013546,-0.023802,-0.033116
"CD Perc (HP, 4.1)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.001198,-0.004776,-0.008185,-0.013666
"Blanket Adjustment (HP, 3.1+)",-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.177463,0.308777,0.255365,0.239029,0.242594,0.294694,0.351266,0.353958
Clip (3.1+),-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.036591,0.050124,-0.017296,0.036654,0.022403,0.073958,0.182766,0.162218
--- Population Weighting,0.484836,0.557515,0.523232,0.454689,0.572048,0.608301,0.656979,0.556320,0.477284,0.436213,0.417253,0.465486,0.325782,0.396026,0.134694
--- TOTAL (RAGU GLI),1.077815,1.291630,1.459354,1.722564,1.260756,2.177068,1.877280,1.286326,0.540014,1.785166,1.239374,1.243884,0.181344,0.115290,0.146563

In [9]:
def build_ragu_decomposition(all_df_model, original_model_scores_df, lob='KMX'):
    '''Build RAGU decomposition table from model results.'''
    if all_df_model is None or len(all_df_model) == 0:
        return None

    raw = all_df_model.loc[[lob]][['vintage', 'ms_original', 'gross_loss_impact', 'recovery_impact',
                                   'ltv_impact', 'apr_impact', 'ragu_score', 'ltv']].reset_index(drop=True).set_index('vintage').T.copy()

    ms_for_lob = original_model_scores_df[original_model_scores_df.lob == lob].copy()
    ms_for_lob = ms_for_lob[ms_for_lob['period'].isin(raw.columns)]
    if len(ms_for_lob) > 0:
        raw = pd.concat([raw, ms_for_lob.drop(columns=['lob', 'amt_financed']).rename(columns={'period': 'vintage'}).set_index('vintage').T.rename({'model_score': 'contract_model_score'})])

    raw.index = ['Mountain3 Score', 'Gross Loss Impact', 'Recovery Impact',
                 'LTV Impact', 'APR Impact', 'RAGU Score', 'LTV', 'Contract Model Score']

    decomp = pd.DataFrame(index=['Contract Model Score', 'Mountain3 Score',
                                  'Gross Loss Adjustments', 'Recovery Adjustments',
                                  'LTV Adjustments', 'APR Adjustments',
                                  'RAGU Score', 'LTV'],
                           columns=raw.columns)

    decomp.loc['Contract Model Score'] = raw.loc['Contract Model Score']
    decomp.loc['Mountain3 Score'] = raw.loc['Mountain3 Score'] - raw.loc['Contract Model Score']
    decomp.loc['Gross Loss Adjustments'] = raw.loc['Gross Loss Impact']
    decomp.loc['Recovery Adjustments'] = raw.loc['Recovery Impact']
    decomp.loc['LTV Adjustments'] = raw.loc['LTV Impact']
    decomp.loc['APR Adjustments'] = raw.loc['APR Impact']
    decomp.loc['RAGU Score'] = raw.loc['RAGU Score']
    decomp.loc['LTV'] = raw.loc['LTV']

    return decomp

# Build original_model_scores for each MTN model subset
original_model_scores_by_model = {}
for mtn_model_filter in MTN_MODELS + ['All KMX']:
    if mtn_model_filter == 'All KMX':
        original_model_scores_by_model['All KMX'] = ms_df
    else:
        ula_subset = ula_df_total[ula_df_total.mtn_model == mtn_model_filter]
        if len(ula_subset) > 0:
            original_model_scores_by_model[mtn_model_filter] = rebuild_ms_df(ula_subset)
        else:
            original_model_scores_by_model[mtn_model_filter] = pd.DataFrame(columns=['period', 'lob', 'model_score', 'amt_financed'])

# Write to Excel
with pd.ExcelWriter(EXCEL_OUTPUT, engine='openpyxl') as writer:
    for mtn_model_filter in ['All KMX'] + MTN_MODELS:
        label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
        all_df_model = results_by_model.get(mtn_model_filter)
        orig_ms = original_model_scores_by_model.get(mtn_model_filter)

        if all_df_model is None or len(all_df_model) == 0:
            print(f'{label}: No results to export, writing empty sheet.')
            pd.DataFrame({'Note': [f'No loans found for {label}']}).to_excel(writer, sheet_name=label, index=False)
            continue

        xlsx_df = build_ragu_decomposition(all_df_model, orig_ms, lob='KMX')
        if xlsx_df is not None:
            xlsx_df.to_excel(writer, sheet_name=label)
            print(f'\n{label} RAGU Decomposition:')
            display(xlsx_df)
        else:
            pd.DataFrame({'Note': [f'Could not build decomposition for {label}']}).to_excel(writer, sheet_name=label, index=False)

    # Diagnostics sheets
    for mtn_model_filter in ['All KMX'] + MTN_MODELS:
        label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
        diag_data = diag_results_by_model.get(mtn_model_filter, (None, None, None))
        output_df, flags_df, attribution_df = diag_data

        sheet_mult = f'{label} Mult Steps'[:31]
        sheet_flags = f'{label} Flags'[:31]
        sheet_attr = f'{label} Attribution'[:31]

        if output_df is not None:
            output_df.to_excel(writer, sheet_name=sheet_mult)
        if flags_df is not None:
            flags_df.to_excel(writer, sheet_name=sheet_flags)
        if attribution_df is not None:
            attribution_df.to_excel(writer, sheet_name=sheet_attr)

print(f'\nExported to: {EXCEL_OUTPUT}')
print("[PROGRESS] Export Complete")

All KMX RAGU Decomposition:

vintage,2023 Q1,2023 Q2,2023 Q3,2023 Q4,2024 Q1,2024 Q2,2024 Q3,2024 Q4,2025 Q1,2025 Q2,2025 Q3,2025 Q4,2026 Q1,2026 Q2,2026 Q3
Contract Model Score,140.103626,140.658174,140.490951,140.569789,139.563853,140.439796,139.879652,139.789069,139.725861,139.866194,139.908574,140.934457,142.167407,142.946899,143.525531
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,1.077815,1.29163,1.459354,1.722564,1.260756,2.177068,1.87728,1.286326,0.540014,1.785166,1.239374,1.243884,0.181344,0.11529,0.146563
Recovery Adjustments,-0.873258,-0.258316,-0.302404,0.30539,-0.058021,0.279748,-0.358544,-0.489204,-0.540677,0.129312,0.64011,0.953646,0.819743,0.938954,0.760866
LTV Adjustments,-2.674912,-1.396738,-3.69043,-4.7719,-4.080808,-0.950288,-1.55379,-1.482701,-0.727484,-0.313402,-0.53154,-0.229127,0.476485,1.077952,1.345625
APR Adjustments,-0.246162,-0.167757,0.002127,-0.003132,-0.197908,0.335081,0.211894,0.25139,-0.087742,-0.054187,0.032568,0.696048,0.476706,0.698584,0.963382
RAGU Score,137.387109,140.126993,137.959597,137.822711,136.487872,142.281406,140.056493,139.354879,138.909971,141.413084,141.289086,143.598908,144.121685,145.777679,146.741967
LTV,1.771146,1.679704,1.851215,1.944847,1.883955,1.64995,1.690428,1.685557,1.635492,1.609284,1.622985,1.604053,1.561551,1.527061,1.512197

MTN 3.0 RAGU Decomposition:

vintage,2023 Q1,2023 Q2,2023 Q3,2023 Q4,2024 Q1,2024 Q2,2024 Q3,2024 Q4,2025 Q1,2025 Q2,2025 Q3,2025 Q4,2026 Q3
Contract Model Score,140.103626,140.658174,140.490951,140.569789,139.563853,140.439796,139.879652,139.141183,138.624949,138.351644,138.576206,138.920424,145.598432
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,1.077815,1.29163,1.459354,1.722564,1.260756,2.177068,1.87728,1.762248,1.009167,2.483169,1.863475,1.774811,5.474959
Recovery Adjustments,-0.873258,-0.258316,-0.302404,0.30539,-0.058021,0.279748,-0.358544,-0.524075,-0.832419,-0.170839,0.010354,0.292765,2.999967
LTV Adjustments,-2.674912,-1.396738,-3.69043,-4.7719,-4.080808,-0.950288,-1.55379,-1.60455,-1.195346,-0.878184,-1.394356,-1.457236,3.76413
APR Adjustments,-0.246162,-0.167757,0.002127,-0.003132,-0.197908,0.335081,0.211894,0.337147,-0.247797,-0.218601,-0.050674,0.794204,1.887093
RAGU Score,137.387109,140.126993,137.959597,137.822711,136.487872,142.281406,140.056493,139.111952,137.358554,139.567189,139.005005,140.324967,159.724581
LTV,1.771146,1.679704,1.851215,1.944847,1.883955,1.64995,1.690428,1.693923,1.66615,1.645243,1.679542,1.683819,1.389954

MTN 3.1 RAGU Decomposition:

vintage,2024 Q4,2025 Q1,2025 Q2,2025 Q3,2025 Q4,2026 Q1,2026 Q2
Contract Model Score,141.46136,140.614397,141.129864,140.977033,141.91771,141.795374,142.989623
Mountain3 Score,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gross Loss Adjustments,0.054665,0.15938,1.199691,0.736501,1.007884,0.465385,0.070744
Recovery Adjustments,-0.398243,-0.298619,0.387163,1.165816,1.288865,0.871124,0.56506
LTV Adjustments,-1.161674,-0.33481,0.180166,0.208692,0.412318,0.457733,0.316308
APR Adjustments,0.029455,0.042114,0.083721,0.09964,0.623929,0.523632,0.985432
RAGU Score,139.985563,140.182462,142.980605,143.187681,145.250707,144.113247,144.927166
LTV,1.663906,1.610618,1.579122,1.577413,1.565323,1.562651,1.571

MTN 3.2 RAGU Decomposition:

vintage                    2026 Q1     2026 Q2     2026 Q3
Contract Model Score    142.080076  142.346376  142.909828
Mountain3 Score                0.0         0.0         0.0
Gross Loss Adjustments     0.02608    0.306795    0.397136
Recovery Adjustments      0.658454    0.991434    0.780448
LTV Adjustments           0.161948    1.001182    1.424252
APR Adjustments           0.225608    0.542783    0.828788
RAGU Score              143.152166   145.18857  146.340452
LTV                       1.580215    1.531378    1.507886

MTN 4.1 RAGU Decomposition:

vintage                    2025 Q4     2026 Q1     2026 Q2     2026 Q3
Contract Model Score    142.786061  144.262919  145.809776  145.794362
Mountain3 Score                0.0         0.0         0.0         0.0
Gross Loss Adjustments   -0.155561   -0.817758   -0.790265    -0.82005
Recovery Adjustments      1.573313    1.010585    0.772464    0.670097
LTV Adjustments           1.153641    1.484573    1.637395    1.041599
APR Adjustments           1.560127    0.932848     1.37773    1.448682
RAGU Score              146.917582  146.873167    148.8071  148.134688
LTV                       1.522828    1.504595    1.496321    1.529102

Exported to: ../output/new_kmx_models.xlsx
[PROGRESS] Export Complete

In [10]:
print("="*80)
print("  VERIFICATION: All KMX vs bareboned_ragu_new.ipynb")
print("="*80)

all_kmx_df = results_by_model.get('All KMX')
if all_kmx_df is not None and len(all_kmx_df) > 0:
    try:
        reference_df = pd.read_csv('../output/all_df.csv')
        ref_kmx = reference_df[reference_df.lob == 'KMX'].copy() if 'lob' in reference_df.columns else pd.DataFrame()

        if len(ref_kmx) > 0:
            our_kmx = all_kmx_df.reset_index()
            our_kmx = our_kmx[our_kmx.lob == 'KMX'][['vintage', 'ms_original', 'gross_loss_impact', 'recovery_impact', 'ragu_score', 'loss_multiplier']].copy()
            our_kmx = our_kmx.set_index('vintage')

            ref_cols = ['vintage', 'ms_original', 'ragu_score', 'loss_multiplier']
            ref_available = [c for c in ref_cols if c in ref_kmx.columns]
            ref_kmx_compare = ref_kmx[ref_available].copy()
            ref_kmx_compare = ref_kmx_compare.set_index('vintage')

            common_vintages = sorted(set(our_kmx.index) & set(ref_kmx_compare.index))

            if common_vintages:
                comparison = pd.DataFrame(index=common_vintages)
                for col in [c for c in ['ragu_score', 'loss_multiplier'] if c in ref_kmx_compare.columns]:
                    comparison[f'{col}_ours'] = our_kmx.loc[common_vintages, col].values
                    comparison[f'{col}_ref'] = ref_kmx_compare.loc[common_vintages, col].values
                    comparison[f'{col}_diff'] = comparison[f'{col}_ours'] - comparison[f'{col}_ref']

                print(f"\nComparing {len(common_vintages)} common vintages:")
                display(comparison)
            else:
                print("No common vintages found.")
        else:
            print("No KMX rows found in reference all_df.csv.")
    except FileNotFoundError:
        print("all_df.csv not found. Run bareboned_ragu_new.ipynb first to generate the reference file.")
    except Exception as e:
        print(f"Error loading reference data: {e}")
        print("\nManually compare the 'All KMX' sheet in new_kmx_models.xlsx")
        print("against the KMX rows in barebones_ragu.xlsx")
else:
    print("No 'All KMX' results to verify.")

# Summary table
print("\n" + "="*80)
print("  SUMMARY: RAGU Scores by MTN Model (most recent vintage)")
print("="*80)
summary_rows = []
baseline_ltv = BASELINES['KMX']['ltv']
for mtn_model_filter in MTN_MODELS + ['All KMX']:
    label = f'MTN {mtn_model_filter}' if mtn_model_filter != 'All KMX' else 'All KMX'
    model_df = results_by_model.get(mtn_model_filter)
    if model_df is not None and len(model_df) > 0:
        kmx_rows = model_df.reset_index()
        kmx_rows = kmx_rows[kmx_rows.lob == 'KMX']
        if len(kmx_rows) > 0:
            last_vintage = kmx_rows.vintage.max()
            last_row = kmx_rows[kmx_rows.vintage == last_vintage].iloc[0]
            summary_rows.append({
                'Model': label,
                'Latest Vintage': last_vintage,
                'Contract MS': last_row.get('ms_original', float('nan')),
                'Gross Loss Impact': last_row.get('gross_loss_impact', float('nan')),
                'Recovery Impact': last_row.get('recovery_impact', float('nan')),
                'LTV Impact': last_row.get('ltv_impact', float('nan')),
                'APR Impact': last_row.get('apr_impact', float('nan')),
                'RAGU Score': last_row.get('ragu_score', float('nan')),
                'LTV': last_row.get('ltv', float('nan')),
                'Loss Multiplier': last_row.get('loss_multiplier', float('nan')),
                'N Vintages': len(kmx_rows),
            })

if summary_rows:
    summary_df = pd.DataFrame(summary_rows).set_index('Model')
    display(summary_df)

    print(f"\nRAGU decomposition:")
    print(f"  baseline_ltv = {baseline_ltv}")
    print(f"  baseline_apr = {BASELINES['KMX']['apr']}")
    print(f"  RAGU Score = (unit_loss * recovery * baselined_recovery) + ltv_impact + apr_impact")
else:
    print("No results available.")

================================================================================
  VERIFICATION: All KMX vs bareboned_ragu_new.ipynb
================================================================================
No common vintages found.

================================================================================
  SUMMARY: RAGU Scores by MTN Model (most recent vintage)
================================================================================

,Latest Vintage,Contract MS,Gross Loss Impact,Recovery Impact,LTV Impact,APR Impact,RAGU Score,LTV,Loss Multiplier,N Vintages
Model,,,,,,,,,,
MTN 3.0,2026 Q3,145.598432,5.474959,2.999967,3.764130,1.887093,159.724581,1.389954,0.781002,13
MTN 3.1,2026 Q2,142.989623,0.070744,0.565060,0.316308,0.985432,144.927166,1.571000,0.997170,7
MTN 3.2,2026 Q3,142.909828,0.397136,0.780448,1.424252,0.828788,146.340452,1.507886,0.984115,3
MTN 4.1,2026 Q3,145.794362,-0.820050,0.670097,1.041599,1.448682,148.134688,1.529102,1.032802,4
All KMX,2026 Q3,143.525531,0.146563,0.760866,1.345625,0.963382,146.741967,1.512197,0.994137,15

RAGU decomposition:
  baseline_ltv = 1.59
  baseline_apr = 0.25
  RAGU Score = (unit_loss * recovery * baselined_recovery) + ltv_impact + apr_impact