# Model Name / Version Distribution
Monthly percent of booked loans by `risk_model_name` and `risk_model_version`,
split into two tables:
1. **KMX** (Mountain models)
2. **nonKMX** (Franchise models and any legacy names)

Data pulled from `edwnpi.los_deal_current_fact` from 2020-01-01 onward.

In [6]:
import pandas as pd
import numpy as np
import pyodbc
import pickle
import warnings
import os

pd.set_option('display.max_columns', 100)
pd.set_option('display.min_rows', 100)
pd.set_option('display.max_rows', 200)

START_DATE = '2020-01-01'
END_DATE = None

run_every_query = True
PICKLE_PATH = '../../cache/model_mix_v1.pkl'


def run_sql(query, connection=None):
    if connection is None:
        with pyodbc.connect("DSN=Redshift_prod_new") as conn:
            warnings.filterwarnings("ignore", category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings("default", category=UserWarning)
            return df
    warnings.filterwarnings("ignore", category=UserWarning)
    df = pd.read_sql_query(sql=query, con=connection)
    warnings.filterwarnings("default", category=UserWarning)
    return df


def store_pickle(data, filename):
    with open(filename, 'wb') as file:
        pickle.dump(data, file)


def get_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)

In [7]:
QUERY = f"""
SELECT
    cd.book_date,
    cd.risk_model_name,
    cd.risk_model_version,
    dru.riskdealergroup AS lob,
    cd.con_amount_financed_back AS amt_financed,
    cd.con_risk_model_score AS model_score,
    cd.account_number
FROM edwnpi.los_deal_current_fact AS cd
LEFT JOIN edwnpi.dealer_rollup_scd_current AS dru
    ON dru.dealer_number = cd.dealer_number
WHERE dru.riskdealergroup IN ('FRN','AN','STG','FLD','ENT','KMX')
  AND cd.data_source_name != 'SPARTAN'
  AND cd.con_amount_financed_back <= 100000
  AND cd.con_risk_model_score > 0
  AND cd.book_date IS NOT NULL
  AND cd.book_date >= '{START_DATE}'
"""

os.makedirs('cache', exist_ok=True)

if run_every_query or not os.path.exists(PICKLE_PATH):
    with pyodbc.connect("DSN=Redshift_prod_new") as conn:
        df = run_sql(QUERY, connection=conn)
    store_pickle(df, PICKLE_PATH)
    print('Query complete, cached to pickle')
else:
    df = get_pickle(PICKLE_PATH)
    print('Loaded from pickle')

df['book_date'] = pd.to_datetime(df['book_date'])
end_date = pd.Timestamp(END_DATE) if END_DATE else pd.Timestamp.today().normalize()
df = df[df['book_date'] <= end_date].copy()

df['month'] = df['book_date'].dt.to_period('M')
df['risk_model_name'] = df['risk_model_name'].fillna('UNKNOWN').astype(str).str.strip()
df['risk_model_version'] = df['risk_model_version'].fillna(0)
df['model_label'] = df['risk_model_name'] + ' ' + df['risk_model_version'].astype(str)
df['is_kmx'] = df['lob'] == 'KMX'

df['month_str'] = df['month'].dt.year.astype(str) + ' M' + df['month'].dt.month.astype(str).str.zfill(2)

print(f"Total rows: {len(df):,}")
print(f"Date range: {df['book_date'].min().date()} to {df['book_date'].max().date()}")
print(f"\nDistinct model labels: {sorted(df['model_label'].unique())}")
print(f"\nKMX rows: {df['is_kmx'].sum():,}  |  nonKMX rows: {(~df['is_kmx']).sum():,}")

Query complete, cached to pickle
Total rows: 822,617
Date range: 2020-01-02 to 2026-08-13

Distinct model labels: ['FRANCHISE 3.0', 'FRANCHISE 3.1', 'Franchise 3.1', 'Franchise 4.0', 'Franchise 4.1', 'MOUNTAIN 1.0', 'MOUNTAIN 2.0', 'MOUNTAIN 2.1', 'MOUNTAIN 3.0', 'MOUNTAIN 3.1', 'Mountain 3.0', 'Mountain 3.1', 'Mountain 3.2', 'Mountain 4.1', 'Mountain 4.2', 'PANDA 1.0', 'PANDA 2.0', 'UNKNOWN 0.0']

KMX rows: 431,833  |  nonKMX rows: 390,784

In [8]:
# --- KMX Model Mix Table ---
kmx = df[df['is_kmx']].copy()

kmx_counts = kmx.groupby(['month_str', 'model_label']).size().unstack(fill_value=0)
kmx_totals = kmx_counts.sum(axis=1)
kmx_pct = kmx_counts.div(kmx_totals, axis=0) * 100
kmx_pct['total_loans'] = kmx_totals

kmx_pct = kmx_pct.round(1)
kmx_pct['total_loans'] = kmx_pct['total_loans'].astype(int)

print('KMX Model Mix (% of monthly loans)')
print('=' * 80)
display(kmx_pct)

# --- KMX Weighted Average Model Score per model_label ---
kmx_wtd_ms = kmx.groupby(['month_str', 'model_label']).apply(
    lambda g: np.average(g['model_score'], weights=g['amt_financed']),
    include_groups=False,
).unstack()

kmx_all_ms = kmx.groupby('month_str').apply(
    lambda g: np.average(g['model_score'], weights=g['amt_financed']),
    include_groups=False,
)
kmx_wtd_ms['All KMX'] = kmx_all_ms
kmx_wtd_ms = kmx_wtd_ms.round(1)

print('\nKMX Weighted Avg Model Score (by amt_financed)')
print('=' * 80)
kmx_wtd_ms

KMX Model Mix (% of monthly loans)
================================================================================

model_label,FRANCHISE 3.0,MOUNTAIN 1.0,MOUNTAIN 2.0,MOUNTAIN 2.1,MOUNTAIN 3.0,MOUNTAIN 3.1,Mountain 3.0,Mountain 3.1,Mountain 3.2,Mountain 4.1,Mountain 4.2,total_loans
month_str,,,,,,,,,,,,
2020 M01,0.0,35.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5661
2020 M02,0.0,0.2,99.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7079
2020 M03,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9749
2020 M04,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3633
2020 M05,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6444
2020 M06,0.0,0.0,96.7,3.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7816
2020 M07,0.0,0.0,90.3,9.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8559
2020 M08,0.0,0.0,79.5,20.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7406
2020 M09,0.0,0.0,50.6,49.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6565
2020 M10,0.0,0.0,49.3,50.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6005
2020 M11,0.0,0.0,2.0,98.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6222
2020 M12,0.0,0.0,0.1,99.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5224
2021 M01,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6308
2021 M02,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6768
2021 M03,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12979
2021 M04,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8704
2021 M05,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6056
2021 M06,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5736
2021 M07,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5973
2021 M08,0.0,0.0,0.0,94.4,5.6,0.0,0.0,0.0,0.0,0.0,0.0,5681
2021 M09,0.0,0.0,0.0,90.3,9.7,0.0,0.0,0.0,0.0,0.0,0.0,5292
2021 M10,0.0,0.0,0.0,90.1,9.9,0.0,0.0,0.0,0.0,0.0,0.0,4845
2021 M11,0.0,0.0,0.0,81.8,18.2,0.0,0.0,0.0,0.0,0.0,0.0,4977
2021 M12,0.0,0.0,0.0,76.7,23.3,0.0,0.0,0.0,0.0,0.0,0.0,3762
2022 M01,0.0,0.0,0.0,71.4,28.6,0.0,0.0,0.0,0.0,0.0,0.0,3975
2022 M02,0.0,0.0,0.0,46.5,53.5,0.0,0.0,0.0,0.0,0.0,0.0,5249
2022 M03,0.0,0.0,0.0,46.1,53.9,0.0,0.0,0.0,0.0,0.0,0.0,6997
2022 M04,0.0,0.0,0.0,1.3,98.7,0.0,0.0,0.0,0.0,0.0,0.0,4931
2022 M05,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,5381
2022 M06,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4591
2022 M07,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4243
2022 M08,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4363
2022 M09,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3898
2022 M10,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3460
2022 M11,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3384
2022 M12,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3149
2023 M01,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3383
2023 M02,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4651
2023 M03,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,6341
2023 M04,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4113
2023 M05,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4565
2023 M06,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4039
2023 M07,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4039
2023 M08,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4546
2023 M09,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4327
2023 M10,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4222
2023 M11,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3444
2023 M12,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,2883
2024 M01,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3725
2024 M02,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,6929
2024 M03,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,7496
2024 M04,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4783
2024 M05,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4675
2024 M06,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4394
2024 M07,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4649
2024 M08,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4519
2024 M09,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3852
2024 M10,0.0,0.0,0.0,0.0,94.7,5.3,0.0,0.0,0.0,0.0,0.0,3899
2024 M11,0.0,0.0,0.0,0.0,70.3,29.7,0.0,0.0,0.0,0.0,0.0,4187
2024 M12,0.0,0.0,0.0,0.0,21.9,12.5,34.4,31.1,0.0,0.0,0.0,4061
2025 M01,0.0,0.0,0.0,0.0,0.1,0.0,42.8,57.0,0.0,0.0,0.0,4015
2025 M02,0.0,0.0,0.0,0.0,0.0,0.0,47.6,52.4,0.0,0.0,0.0,5968
2025 M03,0.0,0.0,0.0,0.0,0.0,0.0,48.6,51.4,0.0,0.0,0.0,8645
2025 M04,0.0,0.0,0.0,0.0,0.0,0.0,47.8,52.2,0.0,0.0,0.0,5463
2025 M05,0.0,0.0,0.0,0.0,0.0,0.0,47.9,52.1,0.0,0.0,0.0,5194
2025 M06,0.0,0.0,0.0,0.0,0.0,0.0,47.7,52.3,0.0,0.0,0.0,4840
2025 M07,0.0,0.0,0.0,0.0,0.0,0.0,48.4,51.6,0.0,0.0,0.0,4800
2025 M08,0.0,0.0,0.0,0.0,0.0,0.0,48.2,51.8,0.0,0.0,0.0,5063
2025 M09,0.0,0.0,0.0,0.0,0.0,0.0,44.8,55.2,0.0,0.0,0.0,5480
2025 M10,0.0,0.0,0.0,0.0,0.0,0.0,48.5,51.5,0.0,0.0,0.0,4847
2025 M11,0.0,0.0,0.0,0.0,0.0,0.0,48.6,51.4,0.0,0.0,0.0,4193
2025 M12,0.0,0.0,0.0,0.0,0.0,0.0,8.8,86.4,0.0,4.8,0.0,4551
2026 M01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,86.9,0.7,12.4,0.0,5299
2026 M02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,61.2,28.3,10.5,0.0,6960
2026 M03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.7,51.0,10.3,0.0,10618
2026 M04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.8,77.2,11.1,0.0,6044
2026 M05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.8,16.2,0.0,5919
2026 M06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.9,22.1,0.0,6372
2026 M07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,78.1,21.9,0.0,6198
2026 M08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,78.4,21.4,0.2,2577

KMX Weighted Avg Model Score (by amt_financed)
================================================================================

model_label,FRANCHISE 3.0,MOUNTAIN 1.0,MOUNTAIN 2.0,MOUNTAIN 2.1,MOUNTAIN 3.0,MOUNTAIN 3.1,Mountain 3.0,Mountain 3.1,Mountain 3.2,Mountain 4.1,Mountain 4.2,All KMX
month_str,,,,,,,,,,,,
2020 M01,NaN,135.2,136.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.1
2020 M02,NaN,137.1,136.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.1
2020 M03,NaN,NaN,135.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.6
2020 M04,NaN,NaN,136.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.5
2020 M05,NaN,NaN,138.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.4
2020 M06,NaN,NaN,139.2,139.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.2
2020 M07,NaN,NaN,139.4,138.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139.3
2020 M08,NaN,NaN,138.8,138.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.6
2020 M09,NaN,NaN,138.3,138.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,138.3
2020 M10,NaN,NaN,137.7,137.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.4
2020 M11,NaN,NaN,137.9,136.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.5
2020 M12,NaN,NaN,148.5,136.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.9
2021 M01,NaN,NaN,NaN,136.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.3
2021 M02,NaN,NaN,NaN,135.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.3
2021 M03,NaN,NaN,NaN,135.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.2
2021 M04,NaN,NaN,NaN,135.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.8
2021 M05,NaN,NaN,NaN,135.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.8
2021 M06,NaN,NaN,NaN,135.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.5
2021 M07,NaN,NaN,NaN,133.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.8
2021 M08,NaN,NaN,NaN,136.4,129.8,NaN,NaN,NaN,NaN,NaN,NaN,136.0
2021 M09,NaN,NaN,NaN,134.1,130.0,NaN,NaN,NaN,NaN,NaN,NaN,133.7
2021 M10,NaN,NaN,NaN,134.2,130.4,NaN,NaN,NaN,NaN,NaN,NaN,133.8
2021 M11,NaN,NaN,NaN,133.7,130.2,NaN,NaN,NaN,NaN,NaN,NaN,133.0
2021 M12,NaN,NaN,NaN,133.1,131.0,NaN,NaN,NaN,NaN,NaN,NaN,132.6
2022 M01,NaN,NaN,NaN,132.4,131.3,NaN,NaN,NaN,NaN,NaN,NaN,132.1
2022 M02,NaN,NaN,NaN,131.9,134.7,NaN,NaN,NaN,NaN,NaN,NaN,133.4
2022 M03,NaN,NaN,NaN,132.9,134.6,NaN,NaN,NaN,NaN,NaN,NaN,133.8
2022 M04,NaN,NaN,NaN,136.0,134.7,NaN,NaN,NaN,NaN,NaN,NaN,134.7
2022 M05,NaN,NaN,NaN,133.0,134.3,NaN,NaN,NaN,NaN,NaN,NaN,134.3
2022 M06,NaN,NaN,NaN,127.0,135.1,NaN,NaN,NaN,NaN,NaN,NaN,135.1
2022 M07,NaN,NaN,NaN,NaN,135.8,NaN,NaN,NaN,NaN,NaN,NaN,135.8
2022 M08,NaN,NaN,NaN,NaN,136.3,NaN,NaN,NaN,NaN,NaN,NaN,136.3
2022 M09,NaN,NaN,NaN,NaN,136.1,NaN,NaN,NaN,NaN,NaN,NaN,136.1
2022 M10,NaN,NaN,NaN,NaN,137.3,NaN,NaN,NaN,NaN,NaN,NaN,137.3
2022 M11,NaN,NaN,NaN,NaN,138.6,NaN,NaN,NaN,NaN,NaN,NaN,138.6
2022 M12,NaN,NaN,NaN,NaN,139.3,NaN,NaN,NaN,NaN,NaN,NaN,139.3
2023 M01,NaN,NaN,NaN,NaN,140.4,NaN,NaN,NaN,NaN,NaN,NaN,140.4
2023 M02,NaN,NaN,NaN,NaN,139.8,NaN,NaN,NaN,NaN,NaN,NaN,139.8
2023 M03,NaN,NaN,NaN,NaN,140.1,NaN,NaN,NaN,NaN,NaN,NaN,140.1
2023 M04,NaN,NaN,NaN,NaN,140.4,NaN,NaN,NaN,NaN,NaN,NaN,140.4
2023 M05,NaN,NaN,NaN,NaN,140.7,NaN,NaN,NaN,NaN,NaN,NaN,140.7
2023 M06,NaN,NaN,NaN,NaN,140.8,NaN,NaN,NaN,NaN,NaN,NaN,140.8
2023 M07,NaN,NaN,NaN,NaN,140.7,NaN,NaN,NaN,NaN,NaN,NaN,140.7
2023 M08,NaN,NaN,NaN,NaN,140.6,NaN,NaN,NaN,NaN,NaN,NaN,140.6
2023 M09,NaN,NaN,NaN,NaN,140.2,NaN,NaN,NaN,NaN,NaN,NaN,140.2
2023 M10,155.0,NaN,NaN,NaN,140.1,NaN,NaN,NaN,NaN,NaN,NaN,140.1
2023 M11,NaN,NaN,NaN,NaN,140.9,NaN,NaN,NaN,NaN,NaN,NaN,140.9
2023 M12,NaN,NaN,NaN,NaN,140.8,NaN,NaN,NaN,NaN,NaN,NaN,140.8
2024 M01,NaN,NaN,NaN,NaN,140.4,NaN,NaN,NaN,NaN,NaN,NaN,140.4
2024 M02,NaN,NaN,NaN,NaN,138.5,NaN,NaN,NaN,NaN,NaN,NaN,138.5
2024 M03,NaN,NaN,NaN,NaN,140.1,NaN,NaN,NaN,NaN,NaN,NaN,140.1
2024 M04,NaN,NaN,NaN,NaN,140.6,NaN,NaN,NaN,NaN,NaN,NaN,140.6
2024 M05,NaN,NaN,NaN,NaN,140.6,NaN,NaN,NaN,NaN,NaN,NaN,140.6
2024 M06,NaN,NaN,NaN,NaN,140.1,NaN,NaN,NaN,NaN,NaN,NaN,140.1
2024 M07,NaN,NaN,NaN,NaN,139.7,NaN,NaN,NaN,NaN,NaN,NaN,139.7
2024 M08,NaN,NaN,NaN,NaN,139.7,NaN,NaN,NaN,NaN,NaN,NaN,139.7
2024 M09,NaN,NaN,NaN,NaN,140.3,NaN,NaN,NaN,NaN,NaN,NaN,140.3
2024 M10,NaN,NaN,NaN,NaN,140.1,142.7,NaN,NaN,NaN,NaN,NaN,140.2
2024 M11,NaN,NaN,NaN,NaN,138.4,142.1,NaN,NaN,NaN,NaN,NaN,139.6
2024 M12,NaN,NaN,NaN,NaN,138.5,141.4,138.5,140.6,NaN,NaN,NaN,139.6
2025 M01,NaN,NaN,NaN,NaN,146.8,133.0,139.3,140.4,NaN,NaN,NaN,140.0
2025 M02,NaN,NaN,NaN,NaN,NaN,NaN,138.5,140.5,NaN,NaN,NaN,139.6
2025 M03,NaN,NaN,NaN,NaN,NaN,NaN,138.4,140.7,NaN,NaN,NaN,139.7
2025 M04,NaN,NaN,NaN,NaN,NaN,NaN,138.0,141.3,NaN,NaN,NaN,139.8
2025 M05,NaN,NaN,NaN,NaN,NaN,NaN,138.4,140.9,NaN,NaN,NaN,139.8
2025 M06,NaN,NaN,NaN,NaN,NaN,NaN,138.8,141.1,NaN,NaN,NaN,140.0
2025 M07,NaN,NaN,NaN,NaN,NaN,NaN,138.9,141.2,NaN,NaN,NaN,140.1
2025 M08,NaN,NaN,NaN,NaN,NaN,NaN,138.5,140.9,NaN,NaN,NaN,139.8
2025 M09,NaN,NaN,NaN,NaN,NaN,NaN,138.3,141.0,NaN,NaN,NaN,139.8
2025 M10,NaN,NaN,NaN,NaN,NaN,NaN,138.8,141.5,NaN,NaN,NaN,140.2
2025 M11,NaN,NaN,NaN,NaN,NaN,NaN,139.0,142.3,NaN,NaN,NaN,140.8
2025 M12,NaN,NaN,NaN,NaN,NaN,NaN,139.5,142.0,NaN,142.5,NaN,141.8
2026 M01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.6,141.1,142.4,NaN,141.7
2026 M02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.8,141.8,143.4,NaN,142.0
2026 M03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.0,142.2,144.2,NaN,142.3
2026 M04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.0,142.5,144.5,NaN,142.8
2026 M05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.0,142.4,144.6,NaN,142.8
2026 M06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.1,144.5,NaN,142.7
2026 M07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.8,144.1,NaN,143.1
2026 M08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143.2,145.4,144.9,143.7

In [9]:
# --- NonKMX Model Mix Table ---
nonkmx = df[~df['is_kmx']].copy()

nonkmx_counts = nonkmx.groupby(['month_str', 'model_label']).size().unstack(fill_value=0)
nonkmx_totals = nonkmx_counts.sum(axis=1)
nonkmx_pct = nonkmx_counts.div(nonkmx_totals, axis=0) * 100
nonkmx_pct['total_loans'] = nonkmx_totals

nonkmx_pct = nonkmx_pct.round(1)
nonkmx_pct['total_loans'] = nonkmx_pct['total_loans'].astype(int)

print('NonKMX Model Mix (% of monthly loans)')
print('=' * 80)
display(nonkmx_pct)

# --- NonKMX Weighted Average Model Score per model_label ---
nonkmx_wtd_ms = nonkmx.groupby(['month_str', 'model_label']).apply(
    lambda g: np.average(g['model_score'], weights=g['amt_financed']),
    include_groups=False,
).unstack()

nonkmx_all_ms = nonkmx.groupby('month_str').apply(
    lambda g: np.average(g['model_score'], weights=g['amt_financed']),
    include_groups=False,
)
nonkmx_wtd_ms['All nonKMX'] = nonkmx_all_ms
nonkmx_wtd_ms = nonkmx_wtd_ms.round(1)

print('\nNonKMX Weighted Avg Model Score (by amt_financed)')
print('=' * 80)
nonkmx_wtd_ms

NonKMX Model Mix (% of monthly loans)
================================================================================

model_label,FRANCHISE 3.0,FRANCHISE 3.1,Franchise 3.1,Franchise 4.0,Franchise 4.1,PANDA 1.0,PANDA 2.0,UNKNOWN 0.0,total_loans
month_str,,,,,,,,,
2020 M01,0.0,0.0,0.0,0.0,0.0,70.3,29.7,0.0,3729
2020 M02,0.0,0.0,0.0,0.0,0.0,63.8,36.2,0.0,3683
2020 M03,0.0,0.0,0.0,0.0,0.0,59.0,41.0,0.0,6237
2020 M04,0.0,0.0,0.0,0.0,0.0,57.2,42.8,0.0,3702
2020 M05,0.0,0.0,0.0,0.0,0.0,24.6,75.4,0.0,4389
2020 M06,0.0,0.0,0.0,0.0,0.0,16.3,83.7,0.0,5041
2020 M07,0.0,0.0,0.0,0.0,0.0,0.8,99.2,0.0,4984
2020 M08,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,4242
2020 M09,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,3688
2020 M10,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,3574
2020 M11,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,3117
2020 M12,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,3276
2021 M01,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,3694
2021 M02,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,3712
2021 M03,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,8358
2021 M04,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,7949
2021 M05,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,5916
2021 M06,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,5777
2021 M07,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,4993
2021 M08,3.2,0.0,0.0,0.0,0.0,0.0,96.8,0.0,4658
2021 M09,11.5,0.0,0.0,0.0,0.0,0.0,88.5,0.0,4368
2021 M10,11.3,0.0,0.0,0.0,0.0,0.0,88.7,0.0,3959
2021 M11,19.1,0.0,0.0,0.0,0.0,0.0,80.9,0.0,3784
2021 M12,27.0,0.0,0.0,0.0,0.0,0.0,73.0,0.0,3676
2022 M01,28.6,0.0,0.0,0.0,0.0,0.0,71.4,0.0,3008
2022 M02,49.5,0.0,0.0,0.0,0.0,0.0,50.5,0.0,3224
2022 M03,56.0,0.0,0.0,0.0,0.0,0.0,44.0,0.0,5218
2022 M04,91.8,0.0,0.0,0.0,0.0,0.0,8.2,0.0,4027
2022 M05,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3626
2022 M06,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3428
2022 M07,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2928
2022 M08,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3404
2022 M09,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3287
2022 M10,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2890
2022 M11,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2310
2022 M12,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2227
2023 M01,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2319
2023 M02,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2180
2023 M03,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4069
2023 M04,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2730
2023 M05,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2726
2023 M06,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2968
2023 M07,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2845
2023 M08,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3312
2023 M09,90.6,9.3,0.0,0.0,0.0,0.0,0.0,0.0,3020
2023 M10,75.4,24.6,0.0,0.0,0.0,0.0,0.0,0.0,3600
2023 M11,32.9,67.1,0.0,0.0,0.0,0.0,0.0,0.0,4401
2023 M12,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,3864
2024 M01,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4465
2024 M02,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,5610
2024 M03,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,9970
2024 M04,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,7751
2024 M05,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,6661
2024 M06,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,5849
2024 M07,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,5850
2024 M08,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4574
2024 M09,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4592
2024 M10,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,5634
2024 M11,0.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,4711
2024 M12,0.0,62.1,37.9,0.0,0.0,0.0,0.0,0.0,5235
2025 M01,0.0,1.1,98.9,0.0,0.0,0.0,0.0,0.0,6382
2025 M02,0.0,0.0,98.5,1.5,0.0,0.0,0.0,0.0,6669
2025 M03,0.0,0.0,95.3,4.7,0.0,0.0,0.0,0.0,12233
2025 M04,0.0,0.0,94.1,5.9,0.0,0.0,0.0,0.0,8951
2025 M05,0.0,0.0,90.2,9.8,0.0,0.0,0.0,0.0,7499
2025 M06,0.0,0.0,78.7,21.3,0.0,0.0,0.0,0.0,6775
2025 M07,0.0,0.0,78.7,21.3,0.0,0.0,0.0,0.0,6920
2025 M08,0.0,0.0,71.8,28.2,0.0,0.0,0.0,0.0,6105
2025 M09,0.0,0.0,58.9,41.1,0.0,0.0,0.0,0.0,5928
2025 M10,0.0,0.0,57.6,42.4,0.0,0.0,0.0,0.0,5904
2025 M11,0.0,0.0,54.7,45.3,0.0,0.0,0.0,0.0,4457
2025 M12,0.0,0.0,14.8,83.1,2.1,0.0,0.0,0.0,4851
2026 M01,0.0,0.0,11.5,77.8,10.8,0.0,0.0,0.0,4843
2026 M02,0.0,0.0,9.7,68.2,22.1,0.0,0.0,0.0,6103
2026 M03,0.0,0.0,9.2,41.2,49.6,0.0,0.0,0.0,10433
2026 M04,0.0,0.0,8.0,43.0,49.0,0.0,0.0,0.0,7387
2026 M05,0.0,0.0,4.0,26.4,69.6,0.0,0.0,0.0,6311
2026 M06,0.0,0.0,0.2,0.8,99.1,0.0,0.0,0.0,5982
2026 M07,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,5805
2026 M08,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,2227

NonKMX Weighted Avg Model Score (by amt_financed)
================================================================================

model_label,FRANCHISE 3.0,FRANCHISE 3.1,Franchise 3.1,Franchise 4.0,Franchise 4.1,PANDA 1.0,PANDA 2.0,UNKNOWN 0.0,All nonKMX
month_str,,,,,,,,,
2020 M01,NaN,NaN,NaN,NaN,NaN,129.9,132.1,NaN,130.6
2020 M02,NaN,NaN,NaN,NaN,NaN,131.6,131.9,NaN,131.7
2020 M03,NaN,NaN,NaN,NaN,NaN,131.2,131.5,NaN,131.3
2020 M04,NaN,NaN,NaN,NaN,NaN,130.8,131.4,NaN,131.0
2020 M05,NaN,NaN,NaN,NaN,NaN,132.8,134.1,NaN,133.8
2020 M06,NaN,NaN,NaN,NaN,NaN,134.0,135.3,NaN,135.1
2020 M07,NaN,NaN,NaN,NaN,NaN,134.7,135.6,NaN,135.6
2020 M08,NaN,NaN,NaN,NaN,NaN,130.0,135.7,NaN,135.7
2020 M09,NaN,NaN,NaN,NaN,NaN,NaN,135.5,NaN,135.5
2020 M10,NaN,NaN,NaN,NaN,NaN,NaN,135.2,NaN,135.2
2020 M11,NaN,NaN,NaN,NaN,NaN,NaN,134.9,NaN,134.9
2020 M12,NaN,NaN,NaN,NaN,NaN,NaN,135.3,NaN,135.3
2021 M01,NaN,NaN,NaN,NaN,NaN,NaN,135.3,NaN,135.3
2021 M02,NaN,NaN,NaN,NaN,NaN,NaN,134.9,NaN,134.9
2021 M03,NaN,NaN,NaN,NaN,NaN,NaN,134.5,NaN,134.5
2021 M04,NaN,NaN,NaN,NaN,NaN,NaN,134.2,NaN,134.2
2021 M05,NaN,NaN,NaN,NaN,NaN,NaN,134.3,NaN,134.3
2021 M06,NaN,NaN,NaN,NaN,NaN,NaN,133.9,NaN,133.9
2021 M07,NaN,NaN,NaN,NaN,NaN,NaN,133.2,NaN,133.2
2021 M08,132.8,NaN,NaN,NaN,NaN,NaN,134.8,NaN,134.7
2021 M09,133.2,NaN,NaN,NaN,NaN,NaN,133.4,NaN,133.3
2021 M10,133.0,NaN,NaN,NaN,NaN,NaN,133.2,NaN,133.2
2021 M11,131.8,NaN,NaN,NaN,NaN,NaN,131.9,NaN,131.9
2021 M12,132.1,NaN,NaN,NaN,NaN,NaN,131.8,NaN,131.9
2022 M01,132.2,NaN,NaN,NaN,NaN,NaN,132.4,NaN,132.3
2022 M02,132.4,NaN,NaN,NaN,NaN,NaN,132.5,NaN,132.5
2022 M03,133.4,NaN,NaN,NaN,NaN,NaN,132.5,NaN,133.0
2022 M04,134.5,NaN,NaN,NaN,NaN,NaN,132.3,NaN,134.3
2022 M05,135.3,NaN,NaN,NaN,NaN,NaN,122.0,NaN,135.3
2022 M06,135.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.5
2022 M07,135.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.9
2022 M08,135.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.8
2022 M09,135.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.4
2022 M10,134.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.8
2022 M11,135.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.8
2022 M12,135.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.5
2023 M01,135.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.5
2023 M02,135.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.8
2023 M03,135.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.7
2023 M04,136.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.3
2023 M05,136.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.7
2023 M06,135.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.6
2023 M07,135.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,135.4
2023 M08,137.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.2
2023 M09,137.9,138.8,NaN,NaN,NaN,NaN,NaN,134.0,137.9
2023 M10,137.4,138.4,NaN,NaN,NaN,NaN,NaN,NaN,137.7
2023 M11,136.7,137.4,NaN,NaN,NaN,NaN,NaN,NaN,137.1
2023 M12,NaN,137.3,NaN,NaN,NaN,NaN,NaN,NaN,137.3
2024 M01,NaN,137.5,NaN,NaN,NaN,NaN,NaN,NaN,137.5
2024 M02,NaN,137.3,NaN,NaN,NaN,NaN,NaN,NaN,137.3
2024 M03,NaN,136.9,NaN,NaN,NaN,NaN,NaN,NaN,136.9
2024 M04,NaN,137.8,NaN,NaN,NaN,NaN,NaN,NaN,137.8
2024 M05,NaN,138.3,NaN,NaN,NaN,NaN,NaN,NaN,138.3
2024 M06,NaN,138.8,NaN,NaN,NaN,NaN,NaN,NaN,138.8
2024 M07,NaN,138.9,NaN,NaN,NaN,NaN,NaN,NaN,138.9
2024 M08,NaN,139.5,NaN,NaN,NaN,NaN,NaN,NaN,139.5
2024 M09,NaN,139.3,NaN,NaN,NaN,NaN,NaN,NaN,139.3
2024 M10,NaN,138.3,NaN,NaN,NaN,NaN,NaN,NaN,138.3
2024 M11,NaN,137.4,NaN,NaN,NaN,NaN,NaN,NaN,137.4
2024 M12,NaN,137.0,137.2,NaN,NaN,NaN,NaN,NaN,137.1
2025 M01,NaN,135.5,137.1,NaN,NaN,NaN,NaN,146.0,137.1
2025 M02,NaN,NaN,137.0,137.8,NaN,NaN,NaN,NaN,137.0
2025 M03,NaN,NaN,137.2,138.4,NaN,NaN,NaN,NaN,137.3
2025 M04,NaN,NaN,138.0,140.2,NaN,NaN,NaN,NaN,138.1
2025 M05,NaN,NaN,138.4,141.0,NaN,NaN,NaN,NaN,138.7
2025 M06,NaN,NaN,138.2,141.1,NaN,NaN,NaN,NaN,138.9
2025 M07,NaN,NaN,138.5,141.3,NaN,NaN,NaN,NaN,139.1
2025 M08,NaN,NaN,137.9,140.9,NaN,NaN,NaN,NaN,138.8
2025 M09,NaN,NaN,137.6,141.1,NaN,NaN,NaN,NaN,139.1
2025 M10,NaN,NaN,137.8,141.0,NaN,NaN,NaN,NaN,139.2
2025 M11,NaN,NaN,137.7,141.3,NaN,NaN,NaN,NaN,139.3
2025 M12,NaN,NaN,136.3,141.5,143.6,NaN,NaN,NaN,140.8
2026 M01,NaN,NaN,137.0,141.8,142.8,NaN,NaN,NaN,141.3
2026 M02,NaN,NaN,137.2,141.5,142.4,NaN,NaN,NaN,141.3
2026 M03,NaN,NaN,137.3,141.4,142.1,NaN,NaN,NaN,141.4
2026 M04,NaN,NaN,137.7,141.9,142.4,NaN,NaN,NaN,141.8
2026 M05,NaN,NaN,137.5,141.6,142.4,NaN,NaN,NaN,142.0
2026 M06,NaN,NaN,136.7,140.1,142.5,NaN,NaN,NaN,142.4
2026 M07,NaN,NaN,NaN,NaN,142.5,NaN,NaN,NaN,142.5
2026 M08,NaN,NaN,NaN,NaN,142.9,NaN,NaN,NaN,142.9

In [10]:
# --- Combined (KMX + nonKMX) Model Mix Table ---
combined_counts = df.groupby(['month_str', 'model_label']).size().unstack(fill_value=0)
combined_totals = combined_counts.sum(axis=1)
combined_pct = combined_counts.div(combined_totals, axis=0) * 100
combined_pct['total_loans'] = combined_totals

combined_pct = combined_pct.round(1)
combined_pct['total_loans'] = combined_pct['total_loans'].astype(int)

print('Combined (KMX + nonKMX) Model Mix (% of monthly loans)')
print('=' * 80)
combined_pct

Combined (KMX + nonKMX) Model Mix (% of monthly loans)
================================================================================

model_label,FRANCHISE 3.0,FRANCHISE 3.1,Franchise 3.1,Franchise 4.0,Franchise 4.1,MOUNTAIN 1.0,MOUNTAIN 2.0,MOUNTAIN 2.1,MOUNTAIN 3.0,MOUNTAIN 3.1,Mountain 3.0,Mountain 3.1,Mountain 3.2,Mountain 4.1,Mountain 4.2,PANDA 1.0,PANDA 2.0,UNKNOWN 0.0,total_loans
month_str,,,,,,,,,,,,,,,,,,,
2020 M01,0.0,0.0,0.0,0.0,0.0,21.1,39.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.9,11.8,0.0,9390
2020 M02,0.0,0.0,0.0,0.0,0.0,0.1,65.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.8,12.4,0.0,10762
2020 M03,0.0,0.0,0.0,0.0,0.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0,16.0,0.0,15986
2020 M04,0.0,0.0,0.0,0.0,0.0,0.0,49.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.9,21.6,0.0,7335
2020 M05,0.0,0.0,0.0,0.0,0.0,0.0,59.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,30.5,0.0,10833
2020 M06,0.0,0.0,0.0,0.0,0.0,0.0,58.8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.4,32.8,0.0,12857
2020 M07,0.0,0.0,0.0,0.0,0.0,0.0,57.1,6.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,36.5,0.0,13543
2020 M08,0.0,0.0,0.0,0.0,0.0,0.0,50.5,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.4,0.0,11648
2020 M09,0.0,0.0,0.0,0.0,0.0,0.0,32.4,31.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0,0.0,10253
2020 M10,0.0,0.0,0.0,0.0,0.0,0.0,30.9,31.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.3,0.0,9579
2020 M11,0.0,0.0,0.0,0.0,0.0,0.0,1.4,65.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.4,0.0,9339
2020 M12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,61.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.5,0.0,8500
2021 M01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.9,0.0,10002
2021 M02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.4,0.0,10480
2021 M03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.2,0.0,21337
2021 M04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,52.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.7,0.0,16653
2021 M05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.4,0.0,11972
2021 M06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.2,0.0,11513
2021 M07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.5,0.0,10966
2021 M08,1.5,0.0,0.0,0.0,0.0,0.0,0.0,51.9,3.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.6,0.0,10339
2021 M09,5.2,0.0,0.0,0.0,0.0,0.0,0.0,49.5,5.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0,9660
2021 M10,5.1,0.0,0.0,0.0,0.0,0.0,0.0,49.6,5.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.9,0.0,8804
2021 M11,8.3,0.0,0.0,0.0,0.0,0.0,0.0,46.5,10.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.9,0.0,8761
2021 M12,13.3,0.0,0.0,0.0,0.0,0.0,0.0,38.8,11.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.1,0.0,7438
2022 M01,12.3,0.0,0.0,0.0,0.0,0.0,0.0,40.7,16.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.7,0.0,6983
2022 M02,18.8,0.0,0.0,0.0,0.0,0.0,0.0,28.8,33.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.2,0.0,8473
2022 M03,23.9,0.0,0.0,0.0,0.0,0.0,0.0,26.4,30.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.8,0.0,12215
2022 M04,41.3,0.0,0.0,0.0,0.0,0.0,0.0,0.7,54.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.7,0.0,8958
2022 M05,40.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9007
2022 M06,42.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8019
2022 M07,40.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7171
2022 M08,43.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,56.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7767
2022 M09,45.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7185
2022 M10,45.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6350
2022 M11,40.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5694
2022 M12,41.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5376
2023 M01,40.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5702
2023 M02,31.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6831
2023 M03,39.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10410
2023 M04,39.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6843
2023 M05,37.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7291
2023 M06,42.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7007
2023 M07,41.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6884
2023 M08,42.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7858
2023 M09,37.3,3.8,0.0,0.0,0.0,0.0,0.0,0.0,58.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7347
2023 M10,34.7,11.3,0.0,0.0,0.0,0.0,0.0,0.0,54.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7822
2023 M11,18.5,37.6,0.0,0.0,0.0,0.0,0.0,0.0,43.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7845
2023 M12,0.0,57.3,0.0,0.0,0.0,0.0,0.0,0.0,42.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6747
2024 M01,0.0,54.5,0.0,0.0,0.0,0.0,0.0,0.0,45.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8190
2024 M02,0.0,44.7,0.0,0.0,0.0,0.0,0.0,0.0,55.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12539
2024 M03,0.0,57.1,0.0,0.0,0.0,0.0,0.0,0.0,42.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17466
2024 M04,0.0,61.8,0.0,0.0,0.0,0.0,0.0,0.0,38.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12534
2024 M05,0.0,58.8,0.0,0.0,0.0,0.0,0.0,0.0,41.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11336
2024 M06,0.0,57.1,0.0,0.0,0.0,0.0,0.0,0.0,42.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10243
2024 M07,0.0,55.7,0.0,0.0,0.0,0.0,0.0,0.0,44.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10499
2024 M08,0.0,50.3,0.0,0.0,0.0,0.0,0.0,0.0,49.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9093
2024 M09,0.0,54.4,0.0,0.0,0.0,0.0,0.0,0.0,45.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8444
2024 M10,0.0,59.1,0.0,0.0,0.0,0.0,0.0,0.0,38.7,2.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9533
2024 M11,0.0,52.9,0.0,0.0,0.0,0.0,0.0,0.0,33.1,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8898
2024 M12,0.0,35.0,21.4,0.0,0.0,0.0,0.0,0.0,9.6,5.5,15.0,13.6,0.0,0.0,0.0,0.0,0.0,0.0,9296
2025 M01,0.0,0.7,60.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.5,22.0,0.0,0.0,0.0,0.0,0.0,0.0,10397
2025 M02,0.0,0.0,52.0,0.8,0.0,0.0,0.0,0.0,0.0,0.0,22.5,24.8,0.0,0.0,0.0,0.0,0.0,0.0,12637
2025 M03,0.0,0.0,55.8,2.8,0.0,0.0,0.0,0.0,0.0,0.0,20.1,21.3,0.0,0.0,0.0,0.0,0.0,0.0,20878
2025 M04,0.0,0.0,58.5,3.6,0.0,0.0,0.0,0.0,0.0,0.0,18.1,19.8,0.0,0.0,0.0,0.0,0.0,0.0,14414
2025 M05,0.0,0.0,53.3,5.8,0.0,0.0,0.0,0.0,0.0,0.0,19.6,21.3,0.0,0.0,0.0,0.0,0.0,0.0,12693
2025 M06,0.0,0.0,45.9,12.4,0.0,0.0,0.0,0.0,0.0,0.0,19.9,21.8,0.0,0.0,0.0,0.0,0.0,0.0,11615
2025 M07,0.0,0.0,46.5,12.6,0.0,0.0,0.0,0.0,0.0,0.0,19.8,21.1,0.0,0.0,0.0,0.0,0.0,0.0,11720
2025 M08,0.0,0.0,39.2,15.4,0.0,0.0,0.0,0.0,0.0,0.0,21.8,23.5,0.0,0.0,0.0,0.0,0.0,0.0,11168
2025 M09,0.0,0.0,30.6,21.4,0.0,0.0,0.0,0.0,0.0,0.0,21.5,26.5,0.0,0.0,0.0,0.0,0.0,0.0,11408
2025 M10,0.0,0.0,31.6,23.3,0.0,0.0,0.0,0.0,0.0,0.0,21.9,23.2,0.0,0.0,0.0,0.0,0.0,0.0,10751
2025 M11,0.0,0.0,28.2,23.3,0.0,0.0,0.0,0.0,0.0,0.0,23.5,24.9,0.0,0.0,0.0,0.0,0.0,0.0,8650
2025 M12,0.0,0.0,7.6,42.9,1.1,0.0,0.0,0.0,0.0,0.0,4.2,41.8,0.0,2.3,0.0,0.0,0.0,0.0,9402
2026 M01,0.0,0.0,5.5,37.1,5.1,0.0,0.0,0.0,0.0,0.0,0.0,45.4,0.3,6.5,0.0,0.0,0.0,0.0,10142
2026 M02,0.0,0.0,4.5,31.9,10.3,0.0,0.0,0.0,0.0,0.0,0.0,32.6,15.1,5.6,0.0,0.0,0.0,0.0,13063
2026 M03,0.0,0.0,4.6,20.4,24.6,0.0,0.0,0.0,0.0,0.0,0.0,19.5,25.7,5.2,0.0,0.0,0.0,0.0,21051
2026 M04,0.0,0.0,4.4,23.7,27.0,0.0,0.0,0.0,0.0,0.0,0.0,5.3,34.7,5.0,0.0,0.0,0.0,0.0,13431
2026 M05,0.0,0.0,2.0,13.6,35.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.6,7.8,0.0,0.0,0.0,0.0,12230
2026 M06,0.0,0.0,0.1,0.4,48.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.2,11.4,0.0,0.0,0.0,0.0,12354
2026 M07,0.0,0.0,0.0,0.0,48.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.3,11.3,0.0,0.0,0.0,0.0,12003
2026 M08,0.0,0.0,0.0,0.0,46.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.1,11.5,0.1,0.0,0.0,0.0,4804

In [11]:
EXCEL_OUTPUT = '../output/model_mix_distribution.xlsx'

with pd.ExcelWriter(EXCEL_OUTPUT, engine='openpyxl') as writer:
    kmx_pct.to_excel(writer, sheet_name='KMX Pct')
    kmx_wtd_ms.to_excel(writer, sheet_name='KMX Avg Score')
    nonkmx_pct.to_excel(writer, sheet_name='NonKMX Pct')
    nonkmx_wtd_ms.to_excel(writer, sheet_name='NonKMX Avg Score')
    combined_pct.to_excel(writer, sheet_name='Combined Pct')

print(f'Exported to {EXCEL_OUTPUT}')

Exported to ../output/model_mix_distribution.xlsx