In [1]:
# =============================================================================
# CELL 1: CONFIGURATION
# =============================================================================

granularity = 'w'  # 'q' = quarterly, 'm' = monthly, 'w' = weekly

START_DATE = '2026-06-01'
END_DATE = None

run_every_query = True  # True = run SQL; False = use cache/ pickles from bareboned_ragu_new

DATE_COL_MAP = {'q': 'book_date', 'm': 'book_date', 'w': 'app_date'}

LOBS = ['AN', 'FRN', 'STG', 'FLD', 'ENT']

BASELINES = {
    'AN':  {'ltv': 1.94, 'new_recovery_unadjusted': 0.58, 'apr': 0.25},
    'FRN': {'ltv': 1.94, 'new_recovery_unadjusted': 0.54, 'apr': 0.25},
    'STG': {'ltv': 1.94, 'new_recovery_unadjusted': 0.60, 'apr': 0.25},
    'FLD': {'ltv': 1.45, 'new_recovery_unadjusted': 0.54, 'apr': 0.235},
    'ENT': {'ltv': 1.45, 'new_recovery_unadjusted': 0.55, 'apr': 0.235},
}

MODEL_PARAMS = {
    'mean_unit_loss': 0.5,
    'unit_loss_to_model_score': 0.02,
}

DIAG_N_VINTAGES = None  # None = all vintages; set to an integer to limit (e.g. 6)

EXCEL_OUTPUT = '../output/nonkmx_gl_diagnostics.xlsx'

In [2]:
# =============================================================================
# CELL 2: IMPORTS AND DERIVED CONFIGURATION
# =============================================================================
import pandas as pd
import numpy as np
import pyodbc
import pickle
import warnings
import math
import os
import openpyxl

pd.set_option('display.max_columns', 100)
pd.set_option('display.min_rows', 100)

date_col = DATE_COL_MAP[granularity]
start_date = pd.Timestamp(START_DATE)
end_date = pd.Timestamp(END_DATE) if END_DATE else pd.Timestamp.today().normalize()

PERIOD_FREQ_MAP = {'q': 'Q', 'm': 'M', 'w': 'W-SAT'}
period_freq = PERIOD_FREQ_MAP[granularity]

start_period = start_date.to_period(period_freq)
end_period = end_date.to_period(period_freq)

min_date_sql = f"'{START_DATE}'"

print(f"Granularity: {granularity}")
print(f"Date column: {date_col}")
print(f"Period range: {start_period} to {end_period}")

Granularity: w
Date column: app_date
Period range: 2026-05-31/2026-06-06 to 2026-09-20/2026-09-26

In [3]:
# =============================================================================
# CELL 3: UTILITY FUNCTIONS
# =============================================================================

def run_sql(filename, sub_list=None, connection=None, filename_is_query=False):
    if sub_list is None:
        sub_list = []
    if filename_is_query:
        query = filename
    else:
        with open(filename, 'r') as file:
            query = file.read()
    for text, var in sub_list:
        query = query.replace(text, var)
    if connection is None:
        with pyodbc.connect("DSN=Redshift_prod_new") as conn:
            warnings.filterwarnings("ignore", category=UserWarning)
            df = pd.read_sql_query(sql=query, con=conn)
            warnings.filterwarnings("default", category=UserWarning)
            return df
    else:
        warnings.filterwarnings("ignore", category=UserWarning)
        df = pd.read_sql_query(sql=query, con=connection)
        warnings.filterwarnings("default", category=UserWarning)
        return df


def store_pickle(data, filename):
    if isinstance(data, str):
        data, filename = filename, data
    with open(filename, 'wb') as file:
        pickle.dump(data, file)


def get_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)


def cached_sql(filename, pickle_name, sub_list=None, connection=None, force_refresh=False):
    if force_refresh or not os.path.exists(pickle_name):
        df = run_sql(filename, sub_list=sub_list, connection=connection)
        store_pickle(df, pickle_name)
        return df
    return get_pickle(pickle_name)


def weighted_average_and_sum(group, metrics):
    if isinstance(metrics, str):
        weighted_avg = (group[metrics] * group.amt_financed).sum() / group.amt_financed.sum()
        return pd.Series({metrics: weighted_avg, 'amt_financed': group.amt_financed.sum()})
    result_dict = {'amt_financed': group.amt_financed.sum()}
    for metric in metrics:
        weighted_avg = (group[metric] * group.amt_financed).sum() / group.amt_financed.sum()
        result_dict[metric] = weighted_avg
    return pd.Series(result_dict)


def format_vintage(period_series):
    if len(period_series) == 0:
        return period_series.astype(str)
    freq = period_series.iloc[0].freqstr
    if freq == 'Q-DEC':
        return period_series.dt.year.astype(str) + ' Q' + period_series.dt.quarter.astype(str)
    elif freq == 'M':
        return period_series.dt.year.astype(str) + ' M' + period_series.dt.month.astype(str).str.zfill(2)
    return period_series.astype(str)

In [4]:
# =============================================================================
# CELL 4: ULA MULTIPLIER FUNCTIONS (NONKMX)
# =============================================================================

def get_ula_multiplier_nonkmx(ula_df, leave_out='None'):
    ula_df['loss_multiplier'] = 1.0

    if leave_out != 'Previous ACA chargeoff':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.prev_co_flag
    if leave_out != 'Small amount financed':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.small_amt_financed_flag * (1 - ula_df.pricing_change_flag)
    if leave_out != 'Zero cash down':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.zero_cash_down_flag * (1 - ula_df.pricing_change_flag)
    if leave_out != 'High mileage vehicle':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_mileage_vehicle_flag
    if leave_out != 'High PTI':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_pti_flag * (1 - ula_df.pricing_change_flag)
    if leave_out != 'Car make':
        ula_df.loss_multiplier *= (1 + 0.1 * ula_df.car_make_penalty_flag
                                   - 0.1 * ula_df.car_make_benefit_flag
                                   - 0.1 * ula_df.pricing_change_flag * ula_df.car_make_benefit_flag)
    if leave_out != 'Theft risk':
        ula_df.loss_multiplier *= (0.987 + 0.099 * ula_df.theft_risk_flag * (1 - ula_df.pricing_change_flag)
                                   + 0.013 * ula_df.pricing_change_flag)
    if leave_out != 'MCY high model score, low mileage':
        ula_df.loss_multiplier *= 1 - 0.2 * ula_df.mcy_low_mileage_flag
    if leave_out != 'Weekday/weekend decision':
        ula_df.loss_multiplier *= 1 - 0.05 * ula_df.weekend_flag + 0.02 * ula_df.weekday_flag
    if leave_out != 'Student Loans':
        ula_df.loss_multiplier *= 1 + (0.1 * ula_df.student_loan_flag
            - np.minimum(np.maximum((ula_df.cd_model_score - (130 - 2 * ula_df.ent_flag)) * 0.006, 0), 0.03)
            * (1 - ula_df.student_loan_flag)) * ula_df.student_loans_cutoff_date
    if leave_out != 'Low PTI':
        ula_df.loss_multiplier *= 1 + (-0.03 * np.minimum(ula_df.cd_model_score, 135) + 3.9) * ula_df.low_pti_flag
    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loss_multiplier *= 0.966 + 0.273 * ula_df.nonkmx_chime_flag
    if leave_out != 'Employment type':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.seasonal_employment_flag - 0.1 * ula_df.waiter_employment_flag
    if leave_out != 'Authorized tradelines':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.nonkmx_auth_tradelines_flag
    if leave_out != 'Fraud':
        ula_df.loss_multiplier *= 1 + (ula_df.fraud_adjustment - 1)
    if leave_out != 'Driver flag':
        ula_df.loss_multiplier *= 1 + 0.15 * ula_df.driver_flag
    if leave_out != 'Clip':
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.8, 2)
    if leave_out != 'Dealer Level (Non-KMX)':
        ula_df.loss_multiplier *= ula_df.pricing_scalar
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.7, 1.4)

    return ula_df


def get_ula_multiplier_nonkmx_diag(ula_df, leave_out='None', verbose=True):
    """Identical logic to get_ula_multiplier_nonkmx, plus per-step mean tracking."""
    steps = {}
    def _record(label, df):
        steps[label] = df.loss_multiplier.mean()

    ula_df['loss_multiplier'] = 1.0
    _record('00_initial', ula_df)
    if verbose:
        print(f"00_initial  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Previous ACA chargeoff':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.prev_co_flag
    _record('01_prev_aca_chargeoff', ula_df)
    if verbose:
        print(f"01_prev_co  | flag mean: {ula_df.prev_co_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Small amount financed':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.small_amt_financed_flag * (1 - ula_df.pricing_change_flag)
    _record('02_small_amt_financed', ula_df)
    if verbose:
        print(f"02_small_af | flag mean: {ula_df.small_amt_financed_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Zero cash down':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.zero_cash_down_flag * (1 - ula_df.pricing_change_flag)
    _record('03_zero_cash_down', ula_df)
    if verbose:
        print(f"03_zero_cd  | flag mean: {ula_df.zero_cash_down_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High mileage vehicle':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_mileage_vehicle_flag
    _record('04_high_mileage', ula_df)
    if verbose:
        print(f"04_high_mi  | flag mean: {ula_df.high_mileage_vehicle_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'High PTI':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.high_pti_flag * (1 - ula_df.pricing_change_flag)
    _record('05_high_pti', ula_df)
    if verbose:
        print(f"05_high_pti | flag mean: {ula_df.high_pti_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Car make':
        ula_df.loss_multiplier *= (1 + 0.1 * ula_df.car_make_penalty_flag
                                   - 0.1 * ula_df.car_make_benefit_flag
                                   - 0.1 * ula_df.pricing_change_flag * ula_df.car_make_benefit_flag)
    _record('06_car_make', ula_df)
    if verbose:
        print(f"06_car_make | penalty: {ula_df.car_make_penalty_flag.mean():.6f}  benefit: {ula_df.car_make_benefit_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Theft risk':
        ula_df.loss_multiplier *= (0.987 + 0.099 * ula_df.theft_risk_flag * (1 - ula_df.pricing_change_flag)
                                   + 0.013 * ula_df.pricing_change_flag)
    _record('07_theft_risk', ula_df)
    if verbose:
        print(f"07_theft    | flag mean: {ula_df.theft_risk_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'MCY high model score, low mileage':
        ula_df.loss_multiplier *= 1 - 0.2 * ula_df.mcy_low_mileage_flag
    _record('08_mcy_low_mileage', ula_df)
    if verbose:
        print(f"08_mcy_low  | flag mean: {ula_df.mcy_low_mileage_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Weekday/weekend decision':
        ula_df.loss_multiplier *= 1 - 0.05 * ula_df.weekend_flag + 0.02 * ula_df.weekday_flag
    _record('09_weekend_weekday', ula_df)
    if verbose:
        print(f"09_wknd/day | weekend: {ula_df.weekend_flag.mean():.6f}  weekday: {ula_df.weekday_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Student Loans':
        ula_df.loss_multiplier *= 1 + (0.1 * ula_df.student_loan_flag
            - np.minimum(np.maximum((ula_df.cd_model_score - (130 - 2 * ula_df.ent_flag)) * 0.006, 0), 0.03)
            * (1 - ula_df.student_loan_flag)) * (ula_df.student_loans_cutoff_date)
    _record('10_student_loans', ula_df)
    if verbose:
        print(f"10_stud_ln  | flag mean: {ula_df.student_loan_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Low PTI':
        ula_df.loss_multiplier *= 1 + (-0.03 * np.minimum(ula_df.cd_model_score, 135) + 3.9) * ula_df.low_pti_flag
    _record('11_low_pti', ula_df)
    if verbose:
        print(f"11_low_pti  | flag mean: {ula_df.low_pti_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Secured credit (Chime, etc.)':
        ula_df.loss_multiplier *= 0.966 + 0.273 * ula_df.nonkmx_chime_flag
    _record('12_chime', ula_df)
    if verbose:
        print(f"12_chime    | flag mean: {ula_df.nonkmx_chime_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Employment type':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.seasonal_employment_flag - 0.1 * ula_df.waiter_employment_flag
    _record('13_employment_type', ula_df)
    if verbose:
        n = len(ula_df)
        print(f"13_employ   | seasonal: {ula_df.seasonal_employment_flag.sum()/n:.6f}  waiter: {ula_df.waiter_employment_flag.sum()/n:.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Authorized tradelines':
        ula_df.loss_multiplier *= 1 + 0.1 * ula_df.nonkmx_auth_tradelines_flag
    _record('14_auth_tradelines', ula_df)
    if verbose:
        print(f"14_auth_tl  | flag mean: {ula_df.nonkmx_auth_tradelines_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Fraud':
        ula_df.loss_multiplier *= 1 + (ula_df.fraud_adjustment - 1)
    _record('15_fraud', ula_df)
    if verbose:
        print(f"15_fraud    | fraud_adj mean: {ula_df.fraud_adjustment.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Driver flag':
        ula_df.loss_multiplier *= 1 + 0.15 * ula_df.driver_flag
    _record('16_driver_flag', ula_df)
    if verbose:
        print(f"16_driver   | flag mean: {ula_df.driver_flag.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Clip':
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.8, 2)

    if leave_out != 'Dealer Level (Non-KMX)':
        ula_df.loss_multiplier *= ula_df.pricing_scalar
    _record('17_pricing_scalar', ula_df)
    if verbose:
        print(f"17_pricing  | scalar mean: {ula_df.pricing_scalar.mean():.6f}  | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}")

    if leave_out != 'Dealer Level (Non-KMX)':
        ula_df.loss_multiplier = np.clip(ula_df.loss_multiplier, 0.7, 1.4)
    _record('18_final', ula_df)
    if verbose:
        print(f"18_final    | loss_multiplier mean: {ula_df.loss_multiplier.mean():.6f}  (post all clips)")

    n = len(ula_df)
    flags = {
        'prev_co_flag': ula_df.prev_co_flag.mean(),
        'small_amt_financed_flag': ula_df.small_amt_financed_flag.mean(),
        'pricing_change_flag': ula_df.pricing_change_flag.mean(),
        'zero_cash_down_flag': ula_df.zero_cash_down_flag.mean(),
        'high_mileage_vehicle_flag': ula_df.high_mileage_vehicle_flag.mean(),
        'high_pti_flag': ula_df.high_pti_flag.mean(),
        'car_make_penalty_flag': ula_df.car_make_penalty_flag.mean(),
        'car_make_benefit_flag': ula_df.car_make_benefit_flag.mean(),
        'theft_risk_flag': ula_df.theft_risk_flag.mean(),
        'mcy_low_mileage_flag': ula_df.mcy_low_mileage_flag.mean(),
        'weekend_flag': ula_df.weekend_flag.mean(),
        'weekday_flag': ula_df.weekday_flag.mean(),
        'student_loan_flag': ula_df.student_loan_flag.mean(),
        'student_loans_cutoff_date': ula_df.student_loans_cutoff_date.mean(),
        'low_pti_flag': ula_df.low_pti_flag.mean(),
        'nonkmx_chime_flag': ula_df.nonkmx_chime_flag.mean(),
        'seasonal_employment_pct': ula_df.seasonal_employment_flag.sum() / n,
        'waiter_employment_pct': ula_df.waiter_employment_flag.sum() / n,
        'nonkmx_auth_tradelines_flag': ula_df.nonkmx_auth_tradelines_flag.mean(),
        'fraud_adjustment_mean': ula_df.fraud_adjustment.mean(),
        'driver_flag': ula_df.driver_flag.mean(),
        'pricing_scalar_mean': ula_df.pricing_scalar.mean(),
    }

    return ula_df, pd.Series(steps), pd.Series(flags)

In [5]:
# =============================================================================
# CELL 5: DATA FETCH (shared cache/ from bareboned_ragu_new)
# =============================================================================

os.makedirs('cache', exist_ok=True)
force = run_every_query

need_conn = force or not all(
    os.path.exists(p) for p in ('../../cache/ula_v1.pkl', '../../cache/dla_v1.pkl', '../../cache/new_recovery_v1.pkl')
)

if need_conn:
    with pyodbc.connect("DSN=Redshift_prod_new") as conn:
        ula_df_total = cached_sql(
            '../queries/vintage_level_ula_query.txt', '../../cache/ula_v1.pkl',
            sub_list=[('{min_book_date}', min_date_sql)], connection=conn, force_refresh=force,
        )
        print('ULA ready')
        dla_df = cached_sql(
            '../queries/new_dll_query.txt', '../../cache/dla_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('DLA ready')
        new_recovery = cached_sql(
            '../queries/new_recovery_queryt.txt', '../../cache/new_recovery_v1.pkl',
            connection=conn, force_refresh=force,
        )
        print('New recovery ready')
else:
    ula_df_total = get_pickle('../../cache/ula_v1.pkl')
    dla_df = get_pickle('../../cache/dla_v1.pkl')
    new_recovery = get_pickle('../../cache/new_recovery_v1.pkl')
    print('ULA, DLA, New recovery loaded from cache')

print(f"ULA records: {len(ula_df_total):,}")
print("[PROGRESS] Data Fetch Complete")

ULA ready
DLA ready
New recovery ready
ULA records: 1,068,973
[PROGRESS] Data Fetch Complete

In [6]:
# =============================================================================
# CELL 6: PERIOD ASSIGNMENT, FILTERING, FLAG CONSTRUCTION
# =============================================================================

ula_df_total = ula_df_total[ula_df_total.lob != 'Core']

ula_df_total['app_date'] = pd.to_datetime(ula_df_total['app_date'])
ula_df_total['book_date'] = pd.to_datetime(ula_df_total['book_date'])
new_recovery['app_date'] = pd.to_datetime(new_recovery['app_date'])
new_recovery['book_date'] = pd.to_datetime(new_recovery['book_date'])

for df in [ula_df_total, new_recovery]:
    df['quarter'] = pd.to_datetime(df[date_col]).dt.to_period('Q')
    df['month'] = pd.to_datetime(df[date_col]).dt.to_period('M')
    df['week'] = pd.to_datetime(df[date_col]).dt.to_period('W-SAT')
    period_key = {'q': 'quarter', 'm': 'month', 'w': 'week'}
    df['period'] = df[period_key[granularity]]

for df in [ula_df_total, new_recovery]:
    mask = (df['period'] >= start_period) & (df['period'] <= end_period)
    df.drop(df[~mask].index, inplace=True)

for df in [ula_df_total, new_recovery]:
    df['book_week'] = df['book_week'].astype(str)
    df['app_week'] = df['app_week'].astype(str)

date_col_str = f'{date_col}_str'
ula_df_total[date_col_str] = ula_df_total[date_col].astype(str)

# --- ULA Processing ---
ula_df_total['vehicle_age'] = np.maximum(ula_df_total[date_col_str].str[:4].astype(int) - ula_df_total.model_year, 1/365)
ula_df_total.tradein_value = ula_df_total.tradein_value.fillna(0)
ula_df_total.make = ula_df_total.make.str.upper().str[:3]
ula_df_total.lob_or_bucket = np.select(
    [ula_df_total.lob_or_bucket.isna() & ula_df_total.lob.isin(['Core', 'FRN']),
     ula_df_total.lob_or_bucket.isna() & ~ula_df_total.lob.isin(['Core', 'FRN'])],
    ['D', 'C'], default=ula_df_total.lob_or_bucket)

# --- DLA Merge ---
dla_df = dla_df.rename(columns={'valid_vintage': 'book_vintage'})
dla_explicit = dla_df[dla_df['book_vintage'] != 'current']
dla_current = dla_df[dla_df['book_vintage'] == 'current'].drop(columns='book_vintage')
last_explicit_vintage = dla_explicit['book_vintage'].max()
ula_df_total = ula_df_total.merge(dla_explicit, how='left', on=['dealer_number', 'book_vintage'])
new_and_missing = ula_df_total['pricing_scalar'].isna() & (ula_df_total['book_vintage'] > last_explicit_vintage)
fallback = ula_df_total.loc[new_and_missing, ['dealer_number']].merge(dla_current, on='dealer_number', how='left')
for col in ['dll_edition', 'loss_ratio', 'dealer_level', 'pricing_scalar']:
    ula_df_total.loc[new_and_missing, col] = fallback[col].values
ula_df_total['pricing_scalar'] = ula_df_total['pricing_scalar'].fillna(1)
ula_df_total.loc[ula_df_total.frni_flag == 1, 'pricing_scalar'] *= 1.05
ula_df_total.loc[ula_df_total.frni_flag == 0, 'pricing_scalar'] *= 0.95

# --- Driver Flag ---
warnings.filterwarnings('ignore', category=UserWarning)
ula_df_total.job_company = ula_df_total.job_company.fillna('not provided')
ula_df_total['driver_flag'] = np.where(
    ula_df_total.job_company.str.contains('(LYFT)|(UBER)|(GRUB ?HUB)|(DOOR ?DASH)|(GO ?PUFF)|(POST ?MATE)|(INSTA ?CART)|(DOMINO)|(PAPA J)|(PIZZA)|(JIMMY ?JOHN)|(SELF)'),
    1, 0)
warnings.filterwarnings('default', category=UserWarning)

# --- NA Handling ---
ula_df_total = ula_df_total.dropna(subset=['sale_price', 'cd_model_score', 'pti', 'lob'])
ula_df_total.cash_down = ula_df_total.cash_down.fillna(0)
ula_df_total.specialty_dealer = ula_df_total.specialty_dealer.fillna('not specialty')
ula_df_total.prev_co_count = ula_df_total.prev_co_count.fillna(0)

# --- Weekly-matching filters ---
ula_df_total['bbltv'] = ula_df_total.amt_financed / ula_df_total.bbvalue.replace(0, np.nan)
ula_df_total = ula_df_total[ula_df_total.amt_financed <= 75000]
ula_df_total = ula_df_total[ula_df_total.pti <= 0.6]
ula_df_total = ula_df_total[
    (ula_df_total.lob == 'MCY') |
    (ula_df_total.bbltv <= 10.0) |
    (ula_df_total.bbvalue.isna()) |
    (ula_df_total.bbvalue == 0)
]
ula_df_total = ula_df_total[ula_df_total.total_income <= 200000]

# --- NonKMX Flags ---
ula_df_total['ent_fld_flag'] = (ula_df_total.lob == 'ENT') | (ula_df_total.lob == 'FLD')
ula_df_total['small_amt_financed_flag'] = (ula_df_total.bbvalue < 5000) & (ula_df_total.amt_financed < 4500) & (ula_df_total.lob != 'MCY')
ula_df_total['zero_cash_down_flag'] = (ula_df_total.cash_down <= 250) & (ula_df_total.tradein_value < 3000)
ula_df_total['high_mileage_vehicle_flag'] = (ula_df_total.mileage >= 100000) & (ula_df_total.cd_model_score < 130) & (ula_df_total.lob != 'MCY')
ula_df_total['high_pti_flag'] = (ula_df_total.pti > 0.3) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally')
ula_df_total['car_make_penalty_flag'] = ula_df_total.make.isin({'CAD', 'CHR', 'BMW', 'BUI', 'SUB'}) & (ula_df_total.cd_model_score < 130) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally')
ula_df_total['car_make_benefit_flag'] = (ula_df_total.cd_model_score >= 133) & ula_df_total.make.isin({'HON', 'TOY', 'LEX'}) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally')
ula_df_total['theft_risk_flag'] = ula_df_total.make.isin({'KIA', 'HYU'}) & (ula_df_total.lob != 'MCY') & (ula_df_total.specialty_dealer != 'Ally') & (ula_df_total.model_year >= 2015) & (ula_df_total.model_year <= 2021) & (ula_df_total[date_col_str] >= '2022-07-01') & (ula_df_total[date_col_str] < '2025-01-01')
ula_df_total['mcy_low_mileage_flag'] = (ula_df_total.lob == 'MCY') & (ula_df_total.cd_model_score > 140) & (ula_df_total.mileage <= 20000) & (ula_df_total.vehicle_age <= 10)
ula_df_total['weekend_flag'] = ula_df_total.day_of_week.isin([0, 6])
ula_df_total['weekday_flag'] = ula_df_total.day_of_week.isin(range(1, 6))
ula_df_total['nonkmx_chime_flag'] = ula_df_total.nonkmx_chime_indicator
ula_df_total['seasonal_employment_flag'] = ula_df_total['seasonal_employment_flag'] == 1
ula_df_total['waiter_employment_flag'] = ula_df_total['waiter_employment_flag'] == 1
ula_df_total['nonkmx_auth_tradelines_flag'] = ula_df_total.pct_auth_tradelines > 0.2
ula_df_total['prev_co_flag'] = ula_df_total.prev_co_count > 0
ula_df_total['pricing_change_flag'] = ula_df_total[date_col_str] >= '2024-10-01'
ula_df_total['ent_flag'] = (ula_df_total.lob == 'ENT')
ula_df_total['student_loans_cutoff_date'] = ula_df_total[date_col_str] >= '2023-05-01'
ula_df_total['low_pti_flag'] = (ula_df_total.pti <= 0.05) & (ula_df_total.cd_model_score >= 130) & ula_df_total.lob.isin({'AN', 'FLD', 'FRN', 'STG'}) & (ula_df_total.cb_flag)
ula_df_total['student_loan_flag'] = np.where(ula_df_total.student_loan_flag == 1, 1, 0)

# --- Deduplicate driver flags ---
combined_driver_flag_df = ula_df_total.groupby('account_number').driver_flag.max().reset_index()
ula_df_total = ula_df_total.drop(columns='driver_flag').merge(combined_driver_flag_df, on='account_number')
ula_df_total = ula_df_total.drop(columns='job_company').drop_duplicates()

# --- Filter to nonKMX LOBs only ---
ula_df_total = ula_df_total[ula_df_total.lob.isin(LOBS)]

ula_df_total['vintage'] = format_vintage(ula_df_total['period'])
new_recovery['vintage'] = format_vintage(new_recovery['period'])

ms_df = ula_df_total.groupby(['period', 'lob']).apply(
    weighted_average_and_sum, 'cd_model_score', include_groups=False
).reset_index()
ms_df = ms_df.rename(columns={'cd_model_score': 'model_score'})
ms_df['period'] = format_vintage(ms_df['period'])

print(f"ULA after filters (nonKMX only): {len(ula_df_total):,}")
print(f"LOBs: {sorted(ula_df_total.lob.unique())}")
print(f"Vintages: {ula_df_total.vintage.nunique()}")
print(f"Model scores: {len(ms_df)} period-LOB combinations")

ULA after filters (nonKMX only): 18,394
LOBs: ['AN', 'ENT', 'FLD', 'FRN', 'STG']
Vintages: 17
Model scores: 85 period-LOB combinations

In [7]:
# =============================================================================
# CELL 7: RAGU SCORE COMPUTATION (NONKMX LOBs)
# =============================================================================

mean_unit_loss = MODEL_PARAMS['mean_unit_loss']
unit_loss_to_model_score = MODEL_PARAMS['unit_loss_to_model_score']


def get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config, leave_out='None'):
    baseline_ltv = baseline_config['ltv']
    new_baseline_recovery_unadjusted_pct = baseline_config['new_recovery_unadjusted']
    baseline_apr = baseline_config['apr']
    ltv_mult = 17
    apr_mult = 0.7

    ula_df = ula_df_total[(ula_df_total.vintage == vintage) & (ula_df_total.lob == lob)].copy()
    if len(ula_df) == 0:
        return None

    ula_df = get_ula_multiplier_nonkmx(ula_df, leave_out)

    ula_df = ula_df[['account_number', date_col, 'bbvalue', 'sale_price', 'amt_financed', 'lob_or_bucket', 'lob', 'loss_multiplier', 'apr']]

    nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(subset='account_number', keep='first')
    mix_df = ula_df.merge(nr.rename(columns={'new_recovery_multiplier': 'recovery_multiplier'}),
                          on='account_number', how='left').drop_duplicates(subset='account_number', keep='first')
    mix_df['ltv'] = mix_df.amt_financed / mix_df.bbvalue

    bb_populated_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0)]
    if len(bb_populated_df) == 0:
        return None

    full_pop_metrics = bb_populated_df.groupby('lob').apply(
        weighted_average_and_sum, ['loss_multiplier', 'ltv', 'bbvalue', 'apr'], include_groups=False)

    recovery_df = mix_df[mix_df['bbvalue'].notna() & (mix_df['bbvalue'] > 0) & mix_df['recovery_multiplier'].notna()].copy()
    recovery_df['recovery_unadjusted_multiplier'] = recovery_df['recovery_multiplier']
    recovery_metrics = recovery_df.groupby('lob').apply(
        weighted_average_and_sum, ['recovery_unadjusted_multiplier'], include_groups=False)
    recovery_metrics = recovery_metrics.drop(columns='amt_financed')

    grouped_mix_df = full_pop_metrics.join(recovery_metrics)
    vintage_ms_df = ms_df[ms_df['period'] == vintage].copy()

    index_name = grouped_mix_df.index.name
    if isinstance(index_name, str) and index_name in grouped_mix_df.columns:
        grouped_mix_df = grouped_mix_df.reset_index(drop=True)
    else:
        grouped_mix_df = grouped_mix_df.reset_index()

    full_df = grouped_mix_df.merge(vintage_ms_df, on='lob')
    if len(full_df) == 0:
        return None

    full_df['est_unit_loss'] = mean_unit_loss
    full_df['unit_loss_score'] = full_df.model_score + (1 - full_df.loss_multiplier) * full_df.est_unit_loss / unit_loss_to_model_score
    full_df = full_df.set_index('lob')
    full_df['ms_original'] = full_df.model_score.copy()
    full_df['baselined_unadjusted_recovery'] = (full_df.recovery_unadjusted_multiplier / new_baseline_recovery_unadjusted_pct).copy()

    full_df['gross_loss_impact'] = full_df['unit_loss_score'] - full_df['ms_original']
    full_df['recovery_impact'] = (full_df['unit_loss_score'] * full_df['est_unit_loss']
        * full_df['recovery_unadjusted_multiplier'] * (full_df['baselined_unadjusted_recovery'] - 1))
    full_df['ltv_impact'] = ((baseline_ltv / full_df['ltv']) - 1) * ltv_mult
    full_df['apr_impact'] = (baseline_apr - full_df['apr']) / 0.01 * apr_mult
    full_df['ragu_score'] = (
        (1 - full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier) * full_df.unit_loss_score
        + full_df.est_unit_loss * full_df.recovery_unadjusted_multiplier
        * full_df.unit_loss_score * full_df.baselined_unadjusted_recovery
        + full_df['ltv_impact']
        + full_df['apr_impact'])
    full_df['vintage'] = vintage
    return full_df


all_vintages = sorted(ula_df_total['vintage'].unique())
results_by_lob = {}

for lob in LOBS:
    baseline_config = BASELINES[lob]
    lob_results = []
    for vintage in all_vintages:
        try:
            result = get_ragu_score(vintage, lob, ula_df_total, new_recovery, ms_df, baseline_config)
            if result is not None:
                lob_results.append(result)
        except Exception as e:
            print(f"Error: {vintage} {lob}: {e}")
    if lob_results:
        results_by_lob[lob] = pd.concat(lob_results)
        print(f"{lob}: {len(lob_results)} vintages")
    else:
        results_by_lob[lob] = pd.DataFrame()
        print(f"{lob}: no results")

print(f"\nAll LOBs processed.")
print("[PROGRESS] Scoring Complete")

AN: 17 vintages
FRN: 17 vintages
STG: 17 vintages
FLD: 17 vintages
Error: 2026-09-20/2026-09-26 ENT: columns overlap but no suffix specified: Index(['loss_multiplier', 'ltv', 'bbvalue', 'apr'], dtype='str')
ENT: 16 vintages

All LOBs processed.
[PROGRESS] Scoring Complete

In [8]:
# =============================================================================
# CELL 8: DIAGNOSTICS - STEP-LEVEL ATTRIBUTION PER LOB
# =============================================================================

def build_output_df(results, wtd_mults, record_counts, ragu_gli_dict=None):
    if not results:
        return None
    step_names = list(next(iter(results.values())).keys())
    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        col_data[col_name] = [step_dict.get(s) for s in step_names]
    diag_df = pd.DataFrame(col_data, index=step_names)
    summary = {}
    for (lob, vintage) in results.keys():
        col = f"{lob} | {vintage}"
        final_mult_mean = diag_df[col].iloc[-1]
        wtd_mult = wtd_mults.get((lob, vintage), float('nan'))
        if ragu_gli_dict is not None:
            gross_loss_impact = ragu_gli_dict.get((lob, vintage), 25 * (1 - wtd_mult))
        else:
            gross_loss_impact = 25 * (1 - wtd_mult)
        summary[col] = {
            '--- FINAL_MULT (mean)': final_mult_mean,
            '--- WTD_MULT_RAGU': wtd_mult,
            '--- GROSS_LOSS_IMPACT': gross_loss_impact,
            '--- N_RECORDS': record_counts.get((lob, vintage), 0),
        }
    summary_df = pd.DataFrame(summary)
    return pd.concat([diag_df, summary_df])


def build_flags_df(flag_results, record_counts):
    if not flag_results:
        return None
    flag_names = list(next(iter(flag_results.values())).keys())
    flag_col_data = {}
    for (lob, vintage), flag_dict in flag_results.items():
        col_name = f"{lob} | {vintage}"
        flag_col_data[col_name] = [flag_dict.get(f) for f in flag_names]
    flags_df = pd.DataFrame(flag_col_data, index=flag_names)
    n_row = {}
    for (lob, vintage) in flag_results.keys():
        n_row[f"{lob} | {vintage}"] = record_counts.get((lob, vintage), 0)
    flags_df.loc['--- N_RECORDS'] = n_row
    return flags_df


STEP_LABEL_MAP = {
    '00_initial':              'Initial (1.0)',
    '01_prev_aca_chargeoff':   'Previous ACA Chargeoff',
    '02_small_amt_financed':   'Small Amount Financed',
    '03_zero_cash_down':       'Zero Cash Down',
    '04_high_mileage':         'High Mileage Vehicle',
    '05_high_pti':             'High PTI',
    '06_car_make':             'Car Make',
    '07_theft_risk':           'Theft Risk',
    '08_mcy_low_mileage':      'MCY Low Mileage',
    '09_weekend_weekday':      'Weekend / Weekday',
    '10_student_loans':        'Student Loans',
    '11_low_pti':              'Low PTI',
    '12_chime':                'Chime / Secured Credit',
    '13_employment_type':      'Employment Type',
    '14_auth_tradelines':      'Authorized Tradelines',
    '15_fraud':                'Fraud Adjustment',
    '16_driver_flag':          'Driver Flag',
    '17_pricing_scalar':       'Dealer Level (Pricing Scalar)',
    '18_final':                'Final Clip',
}


def build_attribution_df(results, ragu_gli_dict):
    """
    Decompose gross_loss_impact across multiplier steps using logarithmic attribution.
    gross_loss_impact is sourced from get_ragu_score output to ensure the attribution
    decomposes the same value that appears in the RAGU score decomposition.
    """
    if not results:
        return None

    step_keys = list(next(iter(results.values())).keys())
    adjustment_keys = [k for k in step_keys if k != '00_initial']
    readable_labels = [STEP_LABEL_MAP.get(k, k) for k in adjustment_keys]

    col_data = {}
    for (lob, vintage), step_dict in results.items():
        col_name = f"{lob} | {vintage}"
        gross_loss_impact = ragu_gli_dict.get((lob, vintage), float('nan'))

        cumulative = [step_dict.get(k, float('nan')) for k in step_keys]
        ratios = []
        for i, k in enumerate(step_keys):
            if k == '00_initial':
                continue
            prev = cumulative[i - 1]
            curr = cumulative[i]
            if prev and prev != 0:
                ratios.append(curr / prev)
            else:
                ratios.append(1.0)

        final_mult = cumulative[-1]
        log_final = math.log(final_mult) if final_mult and final_mult > 0 and abs(final_mult - 1.0) > 1e-12 else None

        if log_final is None or pd.isna(gross_loss_impact):
            col_data[col_name] = [0.0] * len(adjustment_keys) + [gross_loss_impact if not pd.isna(gross_loss_impact) else 0.0]
        else:
            log_ratios = [math.log(r) if r and r > 0 else 0.0 for r in ratios]
            attributed = [(lr / log_final) * gross_loss_impact for lr in log_ratios]
            col_data[col_name] = attributed + [sum(attributed)]

    index_labels = readable_labels + ['--- TOTAL (check)']
    return pd.DataFrame(col_data, index=index_labels)


# --- Run diagnostics per LOB ---
diag_results_by_lob = {}

for lob in LOBS:
    ula_lob = ula_df_total[ula_df_total.lob == lob].copy()
    if len(ula_lob) == 0:
        print(f'\n{lob}: No data, skipping.')
        diag_results_by_lob[lob] = (None, None, None)
        continue

    ragu_gli_dict = {}
    model_df = results_by_lob.get(lob)
    if model_df is not None and len(model_df) > 0:
        for _, row in model_df.reset_index().iterrows():
            ragu_gli_dict[(row['lob'], row['vintage'])] = row['gross_loss_impact']

    all_vintages = sorted(ula_lob.vintage.unique())
    target_vintages = all_vintages[-DIAG_N_VINTAGES:] if DIAG_N_VINTAGES else all_vintages

    lob_results = {}
    lob_flag_results = {}
    lob_wtd_mults = {}
    lob_record_counts = {}

    print(f'\n{"="*60}')
    print(f'  DIAGNOSTICS: {lob}')
    print(f'{"="*60}')

    for vintage in target_vintages:
        ula_vintage = ula_lob[ula_lob.vintage == vintage].copy()
        n = len(ula_vintage)
        if n == 0:
            continue

        print(f'\n{"="*60}')
        print(f'  {lob} {vintage}  (n={n})')
        print(f'{"="*60}')

        ula_vintage_diag, steps, flags = get_ula_multiplier_nonkmx_diag(ula_vintage, leave_out='None', verbose=True)

        diag_mix = ula_vintage_diag[['account_number', 'bbvalue', 'amt_financed', 'loss_multiplier']].copy()
        nr = new_recovery[['account_number', 'new_recovery_multiplier']].drop_duplicates(
            subset='account_number', keep='first')
        diag_mix = diag_mix.merge(nr, on='account_number', how='left').drop_duplicates(
            subset='account_number', keep='first')
        bb_pop = diag_mix[diag_mix['bbvalue'].notna() & (diag_mix['bbvalue'] > 0)]
        if len(bb_pop) > 0 and bb_pop.amt_financed.sum() > 0:
            wtd_mult = (bb_pop.loss_multiplier * bb_pop.amt_financed).sum() / bb_pop.amt_financed.sum()
        else:
            wtd_mult = float('nan')

        ragu_gli = ragu_gli_dict.get((lob, vintage), float('nan'))
        print(f"  bb_populated: {len(bb_pop)} / {n}  wtd_mult: {wtd_mult:.6f}  ragu_gli: {ragu_gli:.4f}")

        lob_results[(lob, vintage)] = steps.to_dict()
        lob_flag_results[(lob, vintage)] = flags.to_dict()
        lob_wtd_mults[(lob, vintage)] = wtd_mult
        lob_record_counts[(lob, vintage)] = n

    output_df = build_output_df(lob_results, lob_wtd_mults, lob_record_counts, ragu_gli_dict)
    flags_df = build_flags_df(lob_flag_results, lob_record_counts)
    attribution_df = build_attribution_df(lob_results, ragu_gli_dict)
    diag_results_by_lob[lob] = (output_df, flags_df, attribution_df)

    if output_df is not None:
        print(f'\n--- {lob} Multiplier Steps ---')
        display(output_df)
        print(f'\n--- {lob} Flag Means ---')
        display(flags_df)
    if attribution_df is not None:
        print(f'\n--- {lob} Gross Loss Attribution ---')
        display(attribution_df)

============================================================
  DIAGNOSTICS: AN
============================================================

============================================================
  AN 2026-05-31/2026-06-06  (n=188)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.005319  | loss_multiplier mean: 1.000532
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000532
03_zero_cd  | flag mean: 0.196809  | loss_multiplier mean: 1.000532
04_high_mi  | flag mean: 0.010638  | loss_multiplier mean: 1.001596
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001596
06_car_make | penalty: 0.000000  benefit: 0.250000  | loss_multiplier mean: 0.951596
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.951596
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.951596
09_wknd/day | weekend: 0.329787  weekday: 0.670213  | loss_multiplier mean: 0.948920
10_stud_ln  | flag mean: 0.111702  | loss_multiplier mean: 0.936821
11_low_pti  | flag mean: 0.037234  | loss_multiplier mean: 0.931394
12_chime    | flag mean: 0.164894  | loss_multiplier mean: 0.941649
13_employ   | seasonal: 0.015957  waiter: 0.015957  | loss_multiplier mean: 0.941375
14_auth_tl  | flag mean: 0.037234  | loss_multiplier mean: 0.945023
15_fraud    | fraud_adj mean: 0.973191  | loss_multiplier mean: 0.922061
16_driver   | flag mean: 0.026596  | loss_multiplier mean: 0.925790
17_pricing  | scalar mean: 0.911436  | loss_multiplier mean: 0.860194
18_final    | loss_multiplier mean: 0.863334  (post all clips)
  bb_populated: 187 / 188  wtd_mult: 0.855729  ragu_gli: 3.6068

============================================================
  AN 2026-06-07/2026-06-13  (n=195)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.015385  | loss_multiplier mean: 1.001538
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001538
03_zero_cd  | flag mean: 0.164103  | loss_multiplier mean: 1.001538
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001538
05_high_pti | flag mean: 0.020513  | loss_multiplier mean: 1.001538
06_car_make | penalty: 0.000000  benefit: 0.276923  | loss_multiplier mean: 0.946051
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.946051
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.946051
09_wknd/day | weekend: 0.266667  weekday: 0.733333  | loss_multiplier mean: 0.947311
10_stud_ln  | flag mean: 0.148718  | loss_multiplier mean: 0.938929
11_low_pti  | flag mean: 0.030769  | loss_multiplier mean: 0.934615
12_chime    | flag mean: 0.164103  | loss_multiplier mean: 0.944621
13_employ   | seasonal: 0.020513  waiter: 0.000000  | loss_multiplier mean: 0.946357
14_auth_tl  | flag mean: 0.010256  | loss_multiplier mean: 0.947476
15_fraud    | fraud_adj mean: 0.986872  | loss_multiplier mean: 0.936868
16_driver   | flag mean: 0.025641  | loss_multiplier mean: 0.940517
17_pricing  | scalar mean: 0.907692  | loss_multiplier mean: 0.868601
18_final    | loss_multiplier mean: 0.871432  (post all clips)
  bb_populated: 193 / 195  wtd_mult: 0.859238  ragu_gli: 3.5191

============================================================
  AN 2026-06-14/2026-06-20  (n=205)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004878  | loss_multiplier mean: 1.000488
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000488
03_zero_cd  | flag mean: 0.165854  | loss_multiplier mean: 1.000488
04_high_mi  | flag mean: 0.009756  | loss_multiplier mean: 1.001463
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001463
06_car_make | penalty: 0.000000  benefit: 0.239024  | loss_multiplier mean: 0.953659
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.953659
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.953659
09_wknd/day | weekend: 0.360976  weekday: 0.639024  | loss_multiplier mean: 0.949034
10_stud_ln  | flag mean: 0.190244  | loss_multiplier mean: 0.945977
11_low_pti  | flag mean: 0.034146  | loss_multiplier mean: 0.941554
12_chime    | flag mean: 0.209756  | loss_multiplier mean: 0.964243
13_employ   | seasonal: 0.004878  waiter: 0.009756  | loss_multiplier mean: 0.963658
14_auth_tl  | flag mean: 0.029268  | loss_multiplier mean: 0.966452
15_fraud    | fraud_adj mean: 0.965268  | loss_multiplier mean: 0.934357
16_driver   | flag mean: 0.039024  | loss_multiplier mean: 0.939662
17_pricing  | scalar mean: 0.901220  | loss_multiplier mean: 0.859912
18_final    | loss_multiplier mean: 0.867434  (post all clips)
  bb_populated: 205 / 205  wtd_mult: 0.858753  ragu_gli: 3.5312

============================================================
  AN 2026-06-21/2026-06-27  (n=194)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.154639  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.005155  | loss_multiplier mean: 1.000515
05_high_pti | flag mean: 0.010309  | loss_multiplier mean: 1.000515
06_car_make | penalty: 0.000000  benefit: 0.257732  | loss_multiplier mean: 0.948969
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.948969
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.948969
09_wknd/day | weekend: 0.293814  weekday: 0.706186  | loss_multiplier mean: 0.948175
10_stud_ln  | flag mean: 0.123711  | loss_multiplier mean: 0.936642
11_low_pti  | flag mean: 0.030928  | loss_multiplier mean: 0.931797
12_chime    | flag mean: 0.180412  | loss_multiplier mean: 0.944942
13_employ   | seasonal: 0.036082  waiter: 0.041237  | loss_multiplier mean: 0.944349
14_auth_tl  | flag mean: 0.025773  | loss_multiplier mean: 0.946601
15_fraud    | fraud_adj mean: 0.981340  | loss_multiplier mean: 0.928863
16_driver   | flag mean: 0.036082  | loss_multiplier mean: 0.933596
17_pricing  | scalar mean: 0.927320  | loss_multiplier mean: 0.876469
18_final    | loss_multiplier mean: 0.882136  (post all clips)
  bb_populated: 194 / 194  wtd_mult: 0.869021  ragu_gli: 3.2745

============================================================
  AN 2026-06-28/2026-07-04  (n=222)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004505  | loss_multiplier mean: 1.000450
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000450
03_zero_cd  | flag mean: 0.153153  | loss_multiplier mean: 1.000450
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000450
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000450
06_car_make | penalty: 0.000000  benefit: 0.283784  | loss_multiplier mean: 0.943694
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.943694
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.943694
09_wknd/day | weekend: 0.229730  weekday: 0.770270  | loss_multiplier mean: 0.947338
10_stud_ln  | flag mean: 0.130631  | loss_multiplier mean: 0.936688
11_low_pti  | flag mean: 0.036036  | loss_multiplier mean: 0.931296
12_chime    | flag mean: 0.144144  | loss_multiplier mean: 0.936953
13_employ   | seasonal: 0.013514  waiter: 0.004505  | loss_multiplier mean: 0.937825
14_auth_tl  | flag mean: 0.018018  | loss_multiplier mean: 0.939432
15_fraud    | fraud_adj mean: 0.978694  | loss_multiplier mean: 0.918621
16_driver   | flag mean: 0.004505  | loss_multiplier mean: 0.919267
17_pricing  | scalar mean: 0.896396  | loss_multiplier mean: 0.838018
18_final    | loss_multiplier mean: 0.844933  (post all clips)
  bb_populated: 220 / 222  wtd_mult: 0.839683  ragu_gli: 4.0079

============================================================
  AN 2026-07-05/2026-07-11  (n=220)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.009091  | loss_multiplier mean: 1.000909
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000909
03_zero_cd  | flag mean: 0.086364  | loss_multiplier mean: 1.000909
04_high_mi  | flag mean: 0.009091  | loss_multiplier mean: 1.001818
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001818
06_car_make | penalty: 0.000000  benefit: 0.300000  | loss_multiplier mean: 0.941818
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.941818
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.941818
09_wknd/day | weekend: 0.277273  weekday: 0.722727  | loss_multiplier mean: 0.942136
10_stud_ln  | flag mean: 0.163636  | loss_multiplier mean: 0.935720
11_low_pti  | flag mean: 0.036364  | loss_multiplier mean: 0.930338
12_chime    | flag mean: 0.200000  | loss_multiplier mean: 0.949928
13_employ   | seasonal: 0.004545  waiter: 0.009091  | loss_multiplier mean: 0.949571
14_auth_tl  | flag mean: 0.040909  | loss_multiplier mean: 0.952999
15_fraud    | fraud_adj mean: 0.973409  | loss_multiplier mean: 0.929683
16_driver   | flag mean: 0.022727  | loss_multiplier mean: 0.932588
17_pricing  | scalar mean: 0.898409  | loss_multiplier mean: 0.855696
18_final    | loss_multiplier mean: 0.863790  (post all clips)
  bb_populated: 220 / 220  wtd_mult: 0.852064  ragu_gli: 3.6984

============================================================
  AN 2026-07-12/2026-07-18  (n=233)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.150215  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.004292  | loss_multiplier mean: 1.000429
05_high_pti | flag mean: 0.012876  | loss_multiplier mean: 1.000429
06_car_make | penalty: 0.004292  benefit: 0.253219  | loss_multiplier mean: 0.950215
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950215
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950215
09_wknd/day | weekend: 0.309013  weekday: 0.690987  | loss_multiplier mean: 0.948519
10_stud_ln  | flag mean: 0.124464  | loss_multiplier mean: 0.936891
11_low_pti  | flag mean: 0.042918  | loss_multiplier mean: 0.930773
12_chime    | flag mean: 0.240343  | loss_multiplier mean: 0.959618
13_employ   | seasonal: 0.025751  waiter: 0.004292  | loss_multiplier mean: 0.961641
14_auth_tl  | flag mean: 0.017167  | loss_multiplier mean: 0.963178
15_fraud    | fraud_adj mean: 0.985193  | loss_multiplier mean: 0.950625
16_driver   | flag mean: 0.004292  | loss_multiplier mean: 0.951118
17_pricing  | scalar mean: 0.911159  | loss_multiplier mean: 0.877955
18_final    | loss_multiplier mean: 0.884512  (post all clips)
  bb_populated: 233 / 233  wtd_mult: 0.879203  ragu_gli: 3.0199

============================================================
  AN 2026-07-19/2026-07-25  (n=237)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.016878  | loss_multiplier mean: 1.001688
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001688
03_zero_cd  | flag mean: 0.113924  | loss_multiplier mean: 1.001688
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001688
05_high_pti | flag mean: 0.008439  | loss_multiplier mean: 1.001688
06_car_make | penalty: 0.000000  benefit: 0.257384  | loss_multiplier mean: 0.950211
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950211
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950211
09_wknd/day | weekend: 0.341772  weekday: 0.658228  | loss_multiplier mean: 0.946354
10_stud_ln  | flag mean: 0.135021  | loss_multiplier mean: 0.936305
11_low_pti  | flag mean: 0.050633  | loss_multiplier mean: 0.928992
12_chime    | flag mean: 0.232068  | loss_multiplier mean: 0.956360
13_employ   | seasonal: 0.016878  waiter: 0.016878  | loss_multiplier mean: 0.956385
14_auth_tl  | flag mean: 0.046414  | loss_multiplier mean: 0.960675
15_fraud    | fraud_adj mean: 0.980422  | loss_multiplier mean: 0.943847
16_driver   | flag mean: 0.021097  | loss_multiplier mean: 0.946761
17_pricing  | scalar mean: 0.906118  | loss_multiplier mean: 0.869467
18_final    | loss_multiplier mean: 0.877271  (post all clips)
  bb_populated: 233 / 237  wtd_mult: 0.872180  ragu_gli: 3.1955

============================================================
  AN 2026-07-26/2026-08-01  (n=213)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.009390  | loss_multiplier mean: 1.000939
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000939
03_zero_cd  | flag mean: 0.126761  | loss_multiplier mean: 1.000939
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000939
05_high_pti | flag mean: 0.004695  | loss_multiplier mean: 1.000939
06_car_make | penalty: 0.004695  benefit: 0.305164  | loss_multiplier mean: 0.940376
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.940376
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.940376
09_wknd/day | weekend: 0.314554  weekday: 0.685446  | loss_multiplier mean: 0.938150
10_stud_ln  | flag mean: 0.192488  | loss_multiplier mean: 0.935195
11_low_pti  | flag mean: 0.042254  | loss_multiplier mean: 0.928810
12_chime    | flag mean: 0.211268  | loss_multiplier mean: 0.950824
13_employ   | seasonal: 0.014085  waiter: 0.014085  | loss_multiplier mean: 0.950950
14_auth_tl  | flag mean: 0.028169  | loss_multiplier mean: 0.953662
15_fraud    | fraud_adj mean: 1.004085  | loss_multiplier mean: 0.958794
16_driver   | flag mean: 0.018779  | loss_multiplier mean: 0.961550
17_pricing  | scalar mean: 0.903991  | loss_multiplier mean: 0.886800
18_final    | loss_multiplier mean: 0.888433  (post all clips)
  bb_populated: 210 / 213  wtd_mult: 0.873885  ragu_gli: 3.1529

============================================================
  AN 2026-08-02/2026-08-08  (n=171)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.011696  | loss_multiplier mean: 1.001170
02_small_af | flag mean: 0.005848  | loss_multiplier mean: 1.001170
03_zero_cd  | flag mean: 0.134503  | loss_multiplier mean: 1.001170
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001170
05_high_pti | flag mean: 0.005848  | loss_multiplier mean: 1.001170
06_car_make | penalty: 0.000000  benefit: 0.269006  | loss_multiplier mean: 0.947251
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.947251
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.947251
09_wknd/day | weekend: 0.327485  weekday: 0.672515  | loss_multiplier mean: 0.944427
10_stud_ln  | flag mean: 0.187135  | loss_multiplier mean: 0.940558
11_low_pti  | flag mean: 0.035088  | loss_multiplier mean: 0.935326
12_chime    | flag mean: 0.175439  | loss_multiplier mean: 0.948031
13_employ   | seasonal: 0.011696  waiter: 0.005848  | loss_multiplier mean: 0.948810
14_auth_tl  | flag mean: 0.023392  | loss_multiplier mean: 0.950969
15_fraud    | fraud_adj mean: 0.977544  | loss_multiplier mean: 0.931594
16_driver   | flag mean: 0.017544  | loss_multiplier mean: 0.933756
17_pricing  | scalar mean: 0.916374  | loss_multiplier mean: 0.876314
18_final    | loss_multiplier mean: 0.884397  (post all clips)
  bb_populated: 170 / 171  wtd_mult: 0.869657  ragu_gli: 3.2586

============================================================
  AN 2026-08-09/2026-08-15  (n=177)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.016949  | loss_multiplier mean: 1.001695
02_small_af | flag mean: 0.011299  | loss_multiplier mean: 1.001695
03_zero_cd  | flag mean: 0.112994  | loss_multiplier mean: 1.001695
04_high_mi  | flag mean: 0.005650  | loss_multiplier mean: 1.002260
05_high_pti | flag mean: 0.005650  | loss_multiplier mean: 1.002260
06_car_make | penalty: 0.000000  benefit: 0.276836  | loss_multiplier mean: 0.946780
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.946780
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.946780
09_wknd/day | weekend: 0.338983  weekday: 0.661017  | loss_multiplier mean: 0.942856
10_stud_ln  | flag mean: 0.129944  | loss_multiplier mean: 0.931440
11_low_pti  | flag mean: 0.090395  | loss_multiplier mean: 0.918927
12_chime    | flag mean: 0.180791  | loss_multiplier mean: 0.934352
13_employ   | seasonal: 0.028249  waiter: 0.016949  | loss_multiplier mean: 0.935547
14_auth_tl  | flag mean: 0.056497  | loss_multiplier mean: 0.940507
15_fraud    | fraud_adj mean: 0.970565  | loss_multiplier mean: 0.914498
16_driver   | flag mean: 0.028249  | loss_multiplier mean: 0.917667
17_pricing  | scalar mean: 0.898023  | loss_multiplier mean: 0.841159
18_final    | loss_multiplier mean: 0.853532  (post all clips)
  bb_populated: 176 / 177  wtd_mult: 0.849661  ragu_gli: 3.7585

============================================================
  AN 2026-08-16/2026-08-22  (n=169)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.017751  | loss_multiplier mean: 1.001775
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001775
03_zero_cd  | flag mean: 0.147929  | loss_multiplier mean: 1.001775
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001775
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001775
06_car_make | penalty: 0.005917  benefit: 0.272189  | loss_multiplier mean: 0.947811
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.947811
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.947811
09_wknd/day | weekend: 0.325444  weekday: 0.674556  | loss_multiplier mean: 0.944947
10_stud_ln  | flag mean: 0.177515  | loss_multiplier mean: 0.940112
11_low_pti  | flag mean: 0.059172  | loss_multiplier mean: 0.930881
12_chime    | flag mean: 0.124260  | loss_multiplier mean: 0.930673
13_employ   | seasonal: 0.017751  waiter: 0.017751  | loss_multiplier mean: 0.930557
14_auth_tl  | flag mean: 0.035503  | loss_multiplier mean: 0.934012
15_fraud    | fraud_adj mean: 0.978639  | loss_multiplier mean: 0.913730
16_driver   | flag mean: 0.029586  | loss_multiplier mean: 0.917633
17_pricing  | scalar mean: 0.910355  | loss_multiplier mean: 0.851342
18_final    | loss_multiplier mean: 0.860507  (post all clips)
  bb_populated: 169 / 169  wtd_mult: 0.847761  ragu_gli: 3.8060

============================================================
  AN 2026-08-23/2026-08-29  (n=144)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006944  | loss_multiplier mean: 1.000694
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000694
03_zero_cd  | flag mean: 0.125000  | loss_multiplier mean: 1.000694
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000694
05_high_pti | flag mean: 0.006944  | loss_multiplier mean: 1.000694
06_car_make | penalty: 0.000000  benefit: 0.263889  | loss_multiplier mean: 0.947917
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.947917
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.947917
09_wknd/day | weekend: 0.340278  weekday: 0.659722  | loss_multiplier mean: 0.944174
10_stud_ln  | flag mean: 0.152778  | loss_multiplier mean: 0.936726
11_low_pti  | flag mean: 0.006944  | loss_multiplier mean: 0.935696
12_chime    | flag mean: 0.159722  | loss_multiplier mean: 0.945212
13_employ   | seasonal: 0.027778  waiter: 0.020833  | loss_multiplier mean: 0.945683
14_auth_tl  | flag mean: 0.006944  | loss_multiplier mean: 0.946347
15_fraud    | fraud_adj mean: 0.981042  | loss_multiplier mean: 0.929100

,AN | 2026-05-31/2026-06-06,AN | 2026-06-07/2026-06-13,AN | 2026-06-14/2026-06-20,AN | 2026-06-21/2026-06-27,AN | 2026-06-28/2026-07-04,AN | 2026-07-05/2026-07-11,AN | 2026-07-12/2026-07-18,AN | 2026-07-19/2026-07-25,AN | 2026-07-26/2026-08-01,AN | 2026-08-02/2026-08-08,AN | 2026-08-09/2026-08-15,AN | 2026-08-16/2026-08-22,AN | 2026-08-23/2026-08-29,AN | 2026-08-30/2026-09-05,AN | 2026-09-06/2026-09-12,AN | 2026-09-13/2026-09-19,AN | 2026-09-20/2026-09-26
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000532,1.001538,1.000488,1.000000,1.000450,1.000909,1.000000,1.001688,1.000939,1.001170,1.001695,1.001775,1.000694,1.000806,1.000000,1.001333,1.000000
02_small_amt_financed,1.000532,1.001538,1.000488,1.000000,1.000450,1.000909,1.000000,1.001688,1.000939,1.001170,1.001695,1.001775,1.000694,1.000806,1.000000,1.001333,1.000000
03_zero_cash_down,1.000532,1.001538,1.000488,1.000000,1.000450,1.000909,1.000000,1.001688,1.000939,1.001170,1.001695,1.001775,1.000694,1.000806,1.000000,1.001333,1.000000
04_high_mileage,1.001596,1.001538,1.001463,1.000515,1.000450,1.001818,1.000429,1.001688,1.000939,1.001170,1.002260,1.001775,1.000694,1.001613,1.000000,1.001333,1.000000
05_high_pti,1.001596,1.001538,1.001463,1.000515,1.000450,1.001818,1.000429,1.001688,1.000939,1.001170,1.002260,1.001775,1.000694,1.001613,1.000000,1.001333,1.000000
06_car_make,0.951596,0.946051,0.953659,0.948969,0.943694,0.941818,0.950215,0.950211,0.940376,0.947251,0.946780,0.947811,0.947917,0.935484,0.938182,0.956000,0.920000
07_theft_risk,0.951596,0.946051,0.953659,0.948969,0.943694,0.941818,0.950215,0.950211,0.940376,0.947251,0.946780,0.947811,0.947917,0.935484,0.938182,0.956000,0.920000
08_mcy_low_mileage,0.951596,0.946051,0.953659,0.948969,0.943694,0.941818,0.950215,0.950211,0.940376,0.947251,0.946780,0.947811,0.947917,0.935484,0.938182,0.956000,0.920000
09_weekend_weekday,0.948920,0.947311,0.949034,0.948175,0.947338,0.942136,0.948519,0.946354,0.938150,0.944427,0.942856,0.944947,0.944174,0.934153,0.933145,0.953653,0.927200
10_student_loans,0.936821,0.938929,0.945977,0.936642,0.936688,0.935720,0.936891,0.936305,0.935195,0.940558,0.931440,0.940112,0.936726,0.924706,0.926292,0.926283,0.899384
11_low_pti,0.931394,0.934615,0.941554,0.931797,0.931296,0.930338,0.930773,0.928992,0.928810,0.935326,0.918927,0.930881,0.935696,0.922245,0.918017,0.920482,0.884543
12_chime,0.941649,0.944621,0.964243,0.944942,0.936953,0.949928,0.959618,0.956360,0.950824,0.948031,0.934352,0.930673,0.945212,0.935699,0.925322,0.899383,0.854469
13_employment_type,0.941375,0.946357,0.963658,0.944349,0.937825,0.949571,0.961641,0.956385,0.950950,0.948810,0.935547,0.930557,0.945683,0.935024,0.926713,0.899383,0.854469
14_auth_tradelines,0.945023,0.947476,0.966452,0.946601,0.939432,0.952999,0.963178,0.960675,0.953662,0.950969,0.940507,0.934012,0.946347,0.936411,0.928703,0.901352,0.854469
15_fraud,0.922061,0.936868,0.934357,0.928863,0.918621,0.929683,0.950625,0.943847,0.958794,0.931594,0.914498,0.913730,0.929100,0.913844,0.917739,0.901352,0.854469
16_driver_flag,0.925790,0.940517,0.939662,0.933596,0.919267,0.932588,0.951118,0.946761,0.961550,0.933756,0.917667,0.917633,0.930821,0.916940,0.920044,0.906704,0.854469
17_pricing_scalar,0.860194,0.868601,0.859912,0.876469,0.838018,0.855696,0.877955,0.869467,0.886800,0.876314,0.841159,0.851342,0.878750,0.856527,0.850507,0.839155,0.773774
18_final,0.863334,0.871432,0.867434,0.882136,0.844933,0.863790,0.884512,0.877271,0.888433,0.884397,0.853532,0.860507,0.882328,0.860625,0.857305,0.846837,0.781774
--- FINAL_MULT (mean),0.863334,0.871432,0.867434,0.882136,0.844933,0.863790,0.884512,0.877271,0.888433,0.884397,0.853532,0.860507,0.882328,0.860625,0.857305,0.846837,0.781774
--- WTD_MULT_RAGU,0.855729,0.859238,0.858753,0.869021,0.839683,0.852064,0.879203,0.872180,0.873885,0.869657,0.849661,0.847761,0.876318,0.851379,0.850134,0.845111,0.763329
--- GROSS_LOSS_IMPACT,3.606769,3.519057,3.531180,3.274468,4.007925,3.698407,3.019928,3.195495,3.152866,3.258575,3.758474,3.805967,3.092060,3.715513,3.746658,3.872215,5.916765
--- N_RECORDS,188.000000,195.000000,205.000000,194.000000,222.000000,220.000000,233.000000,237.000000,213.000000,171.000000,177.000000,169.000000,144.000000,124.000000,110.000000,75.000000,10.000000

--- AN Flag Means ---

,AN | 2026-05-31/2026-06-06,AN | 2026-06-07/2026-06-13,AN | 2026-06-14/2026-06-20,AN | 2026-06-21/2026-06-27,AN | 2026-06-28/2026-07-04,AN | 2026-07-05/2026-07-11,AN | 2026-07-12/2026-07-18,AN | 2026-07-19/2026-07-25,AN | 2026-07-26/2026-08-01,AN | 2026-08-02/2026-08-08,AN | 2026-08-09/2026-08-15,AN | 2026-08-16/2026-08-22,AN | 2026-08-23/2026-08-29,AN | 2026-08-30/2026-09-05,AN | 2026-09-06/2026-09-12,AN | 2026-09-13/2026-09-19,AN | 2026-09-20/2026-09-26
prev_co_flag,0.005319,0.015385,0.004878,0.000000,0.004505,0.009091,0.000000,0.016878,0.009390,0.011696,0.016949,0.017751,0.006944,0.008065,0.000000,0.013333,0.00
small_amt_financed_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005848,0.011299,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00
zero_cash_down_flag,0.196809,0.164103,0.165854,0.154639,0.153153,0.086364,0.150215,0.113924,0.126761,0.134503,0.112994,0.147929,0.125000,0.129032,0.136364,0.066667,0.10
high_mileage_vehicle_flag,0.010638,0.000000,0.009756,0.005155,0.000000,0.009091,0.004292,0.000000,0.000000,0.000000,0.005650,0.000000,0.000000,0.008065,0.000000,0.000000,0.00
high_pti_flag,0.000000,0.020513,0.000000,0.010309,0.000000,0.000000,0.012876,0.008439,0.004695,0.005848,0.005650,0.000000,0.006944,0.000000,0.009091,0.000000,0.00
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.004292,0.000000,0.004695,0.000000,0.000000,0.005917,0.000000,0.000000,0.000000,0.000000,0.00
car_make_benefit_flag,0.250000,0.276923,0.239024,0.257732,0.283784,0.300000,0.253219,0.257384,0.305164,0.269006,0.276836,0.272189,0.263889,0.330645,0.309091,0.226667,0.40
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
weekend_flag,0.329787,0.266667,0.360976,0.293814,0.229730,0.277273,0.309013,0.341772,0.314554,0.327485,0.338983,0.325444,0.340278,0.306452,0.363636,0.320000,0.20
weekday_flag,0.670213,0.733333,0.639024,0.706186,0.770270,0.722727,0.690987,0.658228,0.685446,0.672515,0.661017,0.674556,0.659722,0.693548,0.636364,0.680000,0.80
student_loan_flag,0.111702,0.148718,0.190244,0.123711,0.130631,0.163636,0.124464,0.135021,0.192488,0.187135,0.129944,0.177515,0.152778,0.145161,0.163636,0.000000,0.00
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00
low_pti_flag,0.037234,0.030769,0.034146,0.030928,0.036036,0.036364,0.042918,0.050633,0.042254,0.035088,0.090395,0.059172,0.006944,0.016129,0.054545,0.040000,0.10
nonkmx_chime_flag,0.164894,0.164103,0.209756,0.180412,0.144144,0.200000,0.240343,0.232068,0.211268,0.175439,0.180791,0.124260,0.159722,0.169355,0.154545,0.040000,0.00
seasonal_employment_pct,0.015957,0.020513,0.004878,0.036082,0.013514,0.004545,0.025751,0.016878,0.014085,0.011696,0.028249,0.017751,0.027778,0.016129,0.018182,0.000000,0.00
waiter_employment_pct,0.015957,0.000000,0.009756,0.041237,0.004505,0.009091,0.004292,0.016878,0.014085,0.005848,0.016949,0.017751,0.020833,0.024194,0.000000,0.000000,0.00
nonkmx_auth_tradelines_flag,0.037234,0.010256,0.029268,0.025773,0.018018,0.040909,0.017167,0.046414,0.028169,0.023392,0.056497,0.035503,0.006944,0.016129,0.027273,0.026667,0.00
fraud_adjustment_mean,0.973191,0.986872,0.965268,0.981340,0.978694,0.973409,0.985193,0.980422,1.004085,0.977544,0.970565,0.978639,0.981042,0.974435,0.988000,1.000000,1.00
driver_flag,0.026596,0.025641,0.039024,0.036082,0.004505,0.022727,0.004292,0.021097,0.018779,0.017544,0.028249,0.029586,0.013889,0.024194,0.018182,0.040000,0.00
pricing_scalar_mean,0.911436,0.907692,0.901220,0.927320,0.896396,0.898409,0.911159,0.906118,0.903991,0.916374,0.898023,0.910355,0.929514,0.911290,0.912727,0.915333,0.88
--- N_RECORDS,188.000000,195.000000,205.000000,194.000000,222.000000,220.000000,233.000000,237.000000,213.000000,171.000000,177.000000,169.000000,144.000000,124.000000,110.000000,75.000000,10.00

--- AN Gross Loss Attribution ---

,AN | 2026-05-31/2026-06-06,AN | 2026-06-07/2026-06-13,AN | 2026-06-14/2026-06-20,AN | 2026-06-21/2026-06-27,AN | 2026-06-28/2026-07-04,AN | 2026-07-05/2026-07-11,AN | 2026-07-12/2026-07-18,AN | 2026-07-19/2026-07-25,AN | 2026-07-26/2026-08-01,AN | 2026-08-02/2026-08-08,AN | 2026-08-09/2026-08-15,AN | 2026-08-16/2026-08-22,AN | 2026-08-23/2026-08-29,AN | 2026-08-30/2026-09-05,AN | 2026-09-06/2026-09-12,AN | 2026-09-13/2026-09-19,AN | 2026-09-20/2026-09-26
Previous ACA Chargeoff,-0.013052,-0.039310,-0.012109,-0.000000,-0.010712,-0.022951,-0.000000,-0.041154,-0.025014,-0.031005,-0.040189,-0.044931,-0.017146,-0.019955,-0.000000,-0.031035,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.026082,-0.000000,-0.024201,-0.013455,-0.000000,-0.022931,-0.010559,-0.000000,-0.000000,-0.000000,-0.013381,-0.000000,-0.000000,-0.019939,-0.000000,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,1.256865,1.457451,1.214470,1.381087,1.389213,1.559923,1.267252,1.287519,1.663493,1.468412,1.351437,1.402830,1.338245,1.690780,1.552859,1.079111,2.003943
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,0.069105,-0.034021,0.120695,0.021850,-0.091676,-0.008532,0.043943,0.099250,0.063146,0.079212,0.098542,0.076664,0.097721,0.035236,0.130988,0.057244,-0.187355
Student Loans,0.314943,0.227264,0.080110,0.319544,0.268912,0.172594,0.303555,0.260548,0.084080,0.108877,0.289098,0.129961,0.195591,0.251628,0.179388,0.678281,0.732038
Low PTI,0.142619,0.117768,0.116359,0.135414,0.137322,0.145700,0.161215,0.191360,0.182614,0.147972,0.320983,0.249971,0.027189,0.065967,0.218377,0.146318,0.399891
Chime / Secured Credit,-0.268762,-0.272327,-0.591228,-0.365763,-0.144046,-0.526323,-0.751048,-0.708584,-0.624342,-0.357880,-0.395056,0.005672,-0.249931,-0.358531,-0.192892,0.540116,0.831350
Employment Type,0.007123,-0.046943,0.015070,0.016373,-0.022133,0.009483,-0.051814,-0.000622,-0.003534,-0.021800,-0.030320,0.003149,-0.012301,0.017879,-0.036533,-0.000000,-0.000000
Authorized Tradelines,-0.094927,-0.030212,-0.071892,-0.062172,-0.040710,-0.091016,-0.039298,-0.109221,-0.075887,-0.060288,-0.125490,-0.093886,-0.017329,-0.036703,-0.052198,-0.050937,-0.000000
Fraud Adjustment,0.603740,0.287891,0.838579,0.493897,0.532840,0.625660,0.322813,0.431272,-0.143044,0.546026,0.665540,0.556167,0.454261,0.603874,0.289003,-0.000000,-0.000000
Driver Flag,-0.099071,-0.099380,-0.140574,-0.132689,-0.016716,-0.078820,-0.012739,-0.075230,-0.076518,-0.061490,-0.082111,-0.107979,-0.045691,-0.083729,-0.061055,-0.137899,-0.000000
Dealer Level (Pricing Scalar),1.803691,2.034062,2.202157,1.648665,2.201125,2.173421,1.969729,2.078419,2.156902,1.684084,2.065955,1.899613,1.421825,1.687162,1.912467,1.803264,2.384103
Final Clip,-0.089423,-0.083185,-0.216255,-0.168284,-0.195494,-0.237802,-0.183121,-0.218062,-0.049032,-0.243544,-0.346533,-0.271263,-0.100375,-0.118156,-0.193746,-0.212247,-0.247204
--- TOTAL (check),3.606769,3.519057,3.531180,3.274468,4.007925,3.698407,3.019928,3.195495,3.152866,3.258575,3.758474,3.805967,3.092060,3.715513,3.746658,3.872215,5.916765

============================================================
  DIAGNOSTICS: FRN
============================================================

============================================================
  FRN 2026-05-31/2026-06-06  (n=494)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.012146  | loss_multiplier mean: 1.001215
02_small_af | flag mean: 0.004049  | loss_multiplier mean: 1.001215
03_zero_cd  | flag mean: 0.046559  | loss_multiplier mean: 1.001215
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001215
05_high_pti | flag mean: 0.008097  | loss_multiplier mean: 1.001215
06_car_make | penalty: 0.000000  benefit: 0.267206  | loss_multiplier mean: 0.947733
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.947733
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.947733
09_wknd/day | weekend: 0.303644  weekday: 0.696356  | loss_multiplier mean: 0.946637
10_stud_ln  | flag mean: 0.097166  | loss_multiplier mean: 0.930808
11_low_pti  | flag mean: 0.034413  | loss_multiplier mean: 0.926012
12_chime    | flag mean: 0.196356  | loss_multiplier mean: 0.945081
13_employ   | seasonal: 0.022267  waiter: 0.006073  | loss_multiplier mean: 0.946583
14_auth_tl  | flag mean: 0.032389  | loss_multiplier mean: 0.949668
15_fraud    | fraud_adj mean: 0.991700  | loss_multiplier mean: 0.941271
16_driver   | flag mean: 0.054656  | loss_multiplier mean: 0.948362
17_pricing  | scalar mean: 0.921103  | loss_multiplier mean: 0.887702
18_final    | loss_multiplier mean: 0.894267  (post all clips)
  bb_populated: 492 / 494  wtd_mult: 0.894703  ragu_gli: 2.6324

============================================================
  FRN 2026-06-07/2026-06-13  (n=452)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004425  | loss_multiplier mean: 1.000442
02_small_af | flag mean: 0.017699  | loss_multiplier mean: 1.000442
03_zero_cd  | flag mean: 0.070796  | loss_multiplier mean: 1.000442
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000442
05_high_pti | flag mean: 0.004425  | loss_multiplier mean: 1.000442
06_car_make | penalty: 0.000000  benefit: 0.250000  | loss_multiplier mean: 0.950442
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950442
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950442
09_wknd/day | weekend: 0.269912  weekday: 0.730088  | loss_multiplier mean: 0.951580
10_stud_ln  | flag mean: 0.115044  | loss_multiplier mean: 0.937511
11_low_pti  | flag mean: 0.055310  | loss_multiplier mean: 0.929507
12_chime    | flag mean: 0.205752  | loss_multiplier mean: 0.949940
13_employ   | seasonal: 0.019912  waiter: 0.019912  | loss_multiplier mean: 0.950051
14_auth_tl  | flag mean: 0.026549  | loss_multiplier mean: 0.952487
15_fraud    | fraud_adj mean: 0.990907  | loss_multiplier mean: 0.944140
16_driver   | flag mean: 0.044248  | loss_multiplier mean: 0.949832
17_pricing  | scalar mean: 0.924469  | loss_multiplier mean: 0.889549
18_final    | loss_multiplier mean: 0.893761  (post all clips)
  bb_populated: 447 / 452  wtd_mult: 0.888226  ragu_gli: 2.7944

============================================================
  FRN 2026-06-14/2026-06-20  (n=492)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004065  | loss_multiplier mean: 1.000407
02_small_af | flag mean: 0.006098  | loss_multiplier mean: 1.000407
03_zero_cd  | flag mean: 0.036585  | loss_multiplier mean: 1.000407
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000407
05_high_pti | flag mean: 0.006098  | loss_multiplier mean: 1.000407
06_car_make | penalty: 0.000000  benefit: 0.250000  | loss_multiplier mean: 0.950407
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950407
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950407
09_wknd/day | weekend: 0.319106  weekday: 0.680894  | loss_multiplier mean: 0.948315
10_stud_ln  | flag mean: 0.107724  | loss_multiplier mean: 0.933514
11_low_pti  | flag mean: 0.032520  | loss_multiplier mean: 0.928634
12_chime    | flag mean: 0.219512  | loss_multiplier mean: 0.953228
13_employ   | seasonal: 0.016260  waiter: 0.014228  | loss_multiplier mean: 0.953274
14_auth_tl  | flag mean: 0.028455  | loss_multiplier mean: 0.955872
15_fraud    | fraud_adj mean: 0.989736  | loss_multiplier mean: 0.945463
16_driver   | flag mean: 0.048780  | loss_multiplier mean: 0.952047
17_pricing  | scalar mean: 0.912424  | loss_multiplier mean: 0.879894
18_final    | loss_multiplier mean: 0.887678  (post all clips)
  bb_populated: 488 / 492  wtd_mult: 0.874992  ragu_gli: 3.1252

============================================================
  FRN 2026-06-21/2026-06-27  (n=463)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006479  | loss_multiplier mean: 1.000648
02_small_af | flag mean: 0.010799  | loss_multiplier mean: 1.000648
03_zero_cd  | flag mean: 0.043197  | loss_multiplier mean: 1.000648
04_high_mi  | flag mean: 0.004320  | loss_multiplier mean: 1.001080
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001080
06_car_make | penalty: 0.000000  benefit: 0.226782  | loss_multiplier mean: 0.955724
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.955724
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.955724
09_wknd/day | weekend: 0.308855  weekday: 0.691145  | loss_multiplier mean: 0.954549
10_stud_ln  | flag mean: 0.095032  | loss_multiplier mean: 0.938602
11_low_pti  | flag mean: 0.036717  | loss_multiplier mean: 0.933348
12_chime    | flag mean: 0.207343  | loss_multiplier mean: 0.954901
13_employ   | seasonal: 0.023758  waiter: 0.004320  | loss_multiplier mean: 0.956681
14_auth_tl  | flag mean: 0.025918  | loss_multiplier mean: 0.959155
15_fraud    | fraud_adj mean: 0.990842  | loss_multiplier mean: 0.951128
16_driver   | flag mean: 0.038877  | loss_multiplier mean: 0.956178
17_pricing  | scalar mean: 0.907316  | loss_multiplier mean: 0.877421
18_final    | loss_multiplier mean: 0.882750  (post all clips)
  bb_populated: 461 / 463  wtd_mult: 0.874502  ragu_gli: 3.1375

============================================================
  FRN 2026-06-28/2026-07-04  (n=434)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006912  | loss_multiplier mean: 1.000691
02_small_af | flag mean: 0.004608  | loss_multiplier mean: 1.000691
03_zero_cd  | flag mean: 0.046083  | loss_multiplier mean: 1.000691
04_high_mi  | flag mean: 0.002304  | loss_multiplier mean: 1.000922
05_high_pti | flag mean: 0.002304  | loss_multiplier mean: 1.000922
06_car_make | penalty: 0.000000  benefit: 0.207373  | loss_multiplier mean: 0.959401
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.959401
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.959401
09_wknd/day | weekend: 0.207373  weekday: 0.792627  | loss_multiplier mean: 0.964605
10_stud_ln  | flag mean: 0.103687  | loss_multiplier mean: 0.948928
11_low_pti  | flag mean: 0.066820  | loss_multiplier mean: 0.939287
12_chime    | flag mean: 0.179724  | loss_multiplier mean: 0.953609
13_employ   | seasonal: 0.020737  waiter: 0.009217  | loss_multiplier mean: 0.954650
14_auth_tl  | flag mean: 0.023041  | loss_multiplier mean: 0.956740
15_fraud    | fraud_adj mean: 0.984171  | loss_multiplier mean: 0.942165
16_driver   | flag mean: 0.032258  | loss_multiplier mean: 0.946612
17_pricing  | scalar mean: 0.916740  | loss_multiplier mean: 0.878781
18_final    | loss_multiplier mean: 0.883157  (post all clips)
  bb_populated: 432 / 434  wtd_mult: 0.873772  ragu_gli: 3.1557

============================================================
  FRN 2026-07-05/2026-07-11  (n=448)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004464  | loss_multiplier mean: 1.000446
02_small_af | flag mean: 0.013393  | loss_multiplier mean: 1.000446
03_zero_cd  | flag mean: 0.066964  | loss_multiplier mean: 1.000446
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000446
05_high_pti | flag mean: 0.006696  | loss_multiplier mean: 1.000446
06_car_make | penalty: 0.000000  benefit: 0.247768  | loss_multiplier mean: 0.950893
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.950893
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.950893
09_wknd/day | weekend: 0.265625  weekday: 0.734375  | loss_multiplier mean: 0.952411
10_stud_ln  | flag mean: 0.111607  | loss_multiplier mean: 0.937687
11_low_pti  | flag mean: 0.053571  | loss_multiplier mean: 0.929962
12_chime    | flag mean: 0.243304  | loss_multiplier mean: 0.960747
13_employ   | seasonal: 0.006696  waiter: 0.011161  | loss_multiplier mean: 0.960263
14_auth_tl  | flag mean: 0.029018  | loss_multiplier mean: 0.963068
15_fraud    | fraud_adj mean: 0.985357  | loss_multiplier mean: 0.949434
16_driver   | flag mean: 0.022321  | loss_multiplier mean: 0.952636
17_pricing  | scalar mean: 0.905809  | loss_multiplier mean: 0.873263
18_final    | loss_multiplier mean: 0.880666  (post all clips)
  bb_populated: 445 / 448  wtd_mult: 0.868957  ragu_gli: 3.2761

============================================================
  FRN 2026-07-12/2026-07-18  (n=401)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.009975  | loss_multiplier mean: 1.000998
02_small_af | flag mean: 0.019950  | loss_multiplier mean: 1.000998
03_zero_cd  | flag mean: 0.062344  | loss_multiplier mean: 1.000998
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000998
05_high_pti | flag mean: 0.007481  | loss_multiplier mean: 1.000998
06_car_make | penalty: 0.000000  benefit: 0.226933  | loss_multiplier mean: 0.955611
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.955611
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.955611
09_wknd/day | weekend: 0.284289  weekday: 0.715711  | loss_multiplier mean: 0.955800
10_stud_ln  | flag mean: 0.099751  | loss_multiplier mean: 0.939630
11_low_pti  | flag mean: 0.049875  | loss_multiplier mean: 0.932350
12_chime    | flag mean: 0.201995  | loss_multiplier mean: 0.951917
13_employ   | seasonal: 0.019950  waiter: 0.022444  | loss_multiplier mean: 0.951682
14_auth_tl  | flag mean: 0.022444  | loss_multiplier mean: 0.953708
15_fraud    | fraud_adj mean: 0.994214  | loss_multiplier mean: 0.947328
16_driver   | flag mean: 0.037406  | loss_multiplier mean: 0.952388
17_pricing  | scalar mean: 0.924158  | loss_multiplier mean: 0.888465
18_final    | loss_multiplier mean: 0.890534  (post all clips)
  bb_populated: 401 / 401  wtd_mult: 0.885954  ragu_gli: 2.8511

============================================================
  FRN 2026-07-19/2026-07-25  (n=434)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006912  | loss_multiplier mean: 1.000691
02_small_af | flag mean: 0.009217  | loss_multiplier mean: 1.000691
03_zero_cd  | flag mean: 0.043779  | loss_multiplier mean: 1.000691
04_high_mi  | flag mean: 0.002304  | loss_multiplier mean: 1.000922
05_high_pti | flag mean: 0.004608  | loss_multiplier mean: 1.000922
06_car_make | penalty: 0.000000  benefit: 0.235023  | loss_multiplier mean: 0.953917
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.953917
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.953917
09_wknd/day | weekend: 0.299539  weekday: 0.700461  | loss_multiplier mean: 0.953012
10_stud_ln  | flag mean: 0.108295  | loss_multiplier mean: 0.938413
11_low_pti  | flag mean: 0.043779  | loss_multiplier mean: 0.932083
12_chime    | flag mean: 0.202765  | loss_multiplier mean: 0.951002
13_employ   | seasonal: 0.006912  waiter: 0.013825  | loss_multiplier mean: 0.950331
14_auth_tl  | flag mean: 0.018433  | loss_multiplier mean: 0.952040
15_fraud    | fraud_adj mean: 0.993180  | loss_multiplier mean: 0.943684
16_driver   | flag mean: 0.023041  | loss_multiplier mean: 0.946960
17_pricing  | scalar mean: 0.911486  | loss_multiplier mean: 0.873197
18_final    | loss_multiplier mean: 0.876607  (post all clips)
  bb_populated: 432 / 434  wtd_mult: 0.873482  ragu_gli: 3.1630

============================================================
  FRN 2026-07-26/2026-08-01  (n=447)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006711  | loss_multiplier mean: 1.000671
02_small_af | flag mean: 0.006711  | loss_multiplier mean: 1.000671
03_zero_cd  | flag mean: 0.064877  | loss_multiplier mean: 1.000671
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000671
05_high_pti | flag mean: 0.011186  | loss_multiplier mean: 1.000671
06_car_make | penalty: 0.000000  benefit: 0.259508  | loss_multiplier mean: 0.948680
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.948680
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.948680
09_wknd/day | weekend: 0.277405  weekday: 0.722595  | loss_multiplier mean: 0.949081
10_stud_ln  | flag mean: 0.087248  | loss_multiplier mean: 0.931934
11_low_pti  | flag mean: 0.046980  | loss_multiplier mean: 0.925191
12_chime    | flag mean: 0.228188  | loss_multiplier mean: 0.951478
13_employ   | seasonal: 0.033557  waiter: 0.011186  | loss_multiplier mean: 0.953568
14_auth_tl  | flag mean: 0.035794  | loss_multiplier mean: 0.956957
15_fraud    | fraud_adj mean: 0.991879  | loss_multiplier mean: 0.949673
16_driver   | flag mean: 0.026846  | loss_multiplier mean: 0.952858
17_pricing  | scalar mean: 0.911890  | loss_multiplier mean: 0.881260
18_final    | loss_multiplier mean: 0.887072  (post all clips)
  bb_populated: 439 / 447  wtd_mult: 0.882399  ragu_gli: 2.9400

============================================================
  FRN 2026-08-02/2026-08-08  (n=432)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006944  | loss_multiplier mean: 1.000694
02_small_af | flag mean: 0.011574  | loss_multiplier mean: 1.000694
03_zero_cd  | flag mean: 0.046296  | loss_multiplier mean: 1.000694
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000694
05_high_pti | flag mean: 0.009259  | loss_multiplier mean: 1.000694
06_car_make | penalty: 0.000000  benefit: 0.240741  | loss_multiplier mean: 0.952500
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.952500
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.952500
09_wknd/day | weekend: 0.307870  weekday: 0.692130  | loss_multiplier mean: 0.951036
10_stud_ln  | flag mean: 0.085648  | loss_multiplier mean: 0.934238
11_low_pti  | flag mean: 0.025463  | loss_multiplier mean: 0.930428
12_chime    | flag mean: 0.222222  | loss_multiplier mean: 0.954792
13_employ   | seasonal: 0.020833  waiter: 0.013889  | loss_multiplier mean: 0.955342
14_auth_tl  | flag mean: 0.027778  | loss_multiplier mean: 0.957908
15_fraud    | fraud_adj mean: 0.990764  | loss_multiplier mean: 0.949060
16_driver   | flag mean: 0.023148  | loss_multiplier mean: 0.951861
17_pricing  | scalar mean: 0.911730  | loss_multiplier mean: 0.877312
18_final    | loss_multiplier mean: 0.885238  (post all clips)
  bb_populated: 428 / 432  wtd_mult: 0.871356  ragu_gli: 3.2161

============================================================
  FRN 2026-08-09/2026-08-15  (n=401)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.004988  | loss_multiplier mean: 1.000499
02_small_af | flag mean: 0.009975  | loss_multiplier mean: 1.000499
03_zero_cd  | flag mean: 0.079800  | loss_multiplier mean: 1.000499
04_high_mi  | flag mean: 0.004988  | loss_multiplier mean: 1.000998
05_high_pti | flag mean: 0.002494  | loss_multiplier mean: 1.000998
06_car_make | penalty: 0.000000  benefit: 0.236908  | loss_multiplier mean: 0.953616
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.953616
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.953616
09_wknd/day | weekend: 0.289277  weekday: 0.710723  | loss_multiplier mean: 0.953469
10_stud_ln  | flag mean: 0.109726  | loss_multiplier mean: 0.939215
11_low_pti  | flag mean: 0.062344  | loss_multiplier mean: 0.929789
12_chime    | flag mean: 0.256858  | loss_multiplier mean: 0.962676
13_employ   | seasonal: 0.022444  waiter: 0.012469  | loss_multiplier mean: 0.963542
14_auth_tl  | flag mean: 0.037406  | loss_multiplier mean: 0.967086
15_fraud    | fraud_adj mean: 0.984913  | loss_multiplier mean: 0.952325
16_driver   | flag mean: 0.049875  | loss_multiplier mean: 0.958587
17_pricing  | scalar mean: 0.911976  | loss_multiplier mean: 0.883468
18_final    | loss_multiplier mean: 0.888778  (post all clips)
  bb_populated: 390 / 401  wtd_mult: 0.880598  ragu_gli: 2.9850

============================================================
  FRN 2026-08-16/2026-08-22  (n=379)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.002639  | loss_multiplier mean: 1.000264
02_small_af | flag mean: 0.013193  | loss_multiplier mean: 1.000264
03_zero_cd  | flag mean: 0.055409  | loss_multiplier mean: 1.000264
04_high_mi  | flag mean: 0.002639  | loss_multiplier mean: 1.000528
05_high_pti | flag mean: 0.002639  | loss_multiplier mean: 1.000528
06_car_make | penalty: 0.000000  benefit: 0.266491  | loss_multiplier mean: 0.947230
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.947230
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.947230
09_wknd/day | weekend: 0.266491  weekday: 0.733509  | loss_multiplier mean: 0.948554
10_stud_ln  | flag mean: 0.113456  | loss_multiplier mean: 0.934703
11_low_pti  | flag mean: 0.036939  | loss_multiplier mean: 0.929298
12_chime    | flag mean: 0.229551  | loss_multiplier mean: 0.956522
13_employ   | seasonal: 0.018470  waiter: 0.007916  | loss_multiplier mean: 0.957692
14_auth_tl  | flag mean: 0.021108  | loss_multiplier mean: 0.959488
15_fraud    | fraud_adj mean: 0.985567  | loss_multiplier mean: 0.946334
16_driver   | flag mean: 0.036939  | loss_multiplier mean: 0.951230
17_pricing  | scalar mean: 0.913918  | loss_multiplier mean: 0.884212
18_final    | loss_multiplier mean: 0.891723  (post all clips)
  bb_populated: 371 / 379  wtd_mult: 0.880084  ragu_gli: 2.9979

============================================================
  FRN 2026-08-23/2026-08-29  (n=428)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.002336  | loss_multiplier mean: 1.000234
02_small_af | flag mean: 0.007009  | loss_multiplier mean: 1.000234
03_zero_cd  | flag mean: 0.044393  | loss_multiplier mean: 1.000234
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000234
05_high_pti | flag mean: 0.004673  | loss_multiplier mean: 1.000234
06_car_make | penalty: 0.000000  benefit: 0.235981  | loss_multiplier mean: 0.953037
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.953037
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.953037
09_wknd/day | weekend: 0.306075  weekday: 0.693925  | loss_multiplier mean: 0.951850
10_stud_ln  | flag mean: 0.098131  | loss_multiplier mean: 0.935841
11_low_pti  | flag mean: 0.042056  | loss_multiplier mean: 0.929745
12_chime    | flag mean: 0.226636  | loss_multiplier mean: 0.955573
13_employ   | seasonal: 0.032710  waiter: 0.004673  | loss_multiplier mean: 0.958048
14_auth_tl  | flag mean: 0.028037  | loss_multiplier mean: 0.960892
15_fraud    | fraud_adj mean: 0.992430  | loss_multiplier mean: 0.953647

,FRN | 2026-05-31/2026-06-06,FRN | 2026-06-07/2026-06-13,FRN | 2026-06-14/2026-06-20,FRN | 2026-06-21/2026-06-27,FRN | 2026-06-28/2026-07-04,FRN | 2026-07-05/2026-07-11,FRN | 2026-07-12/2026-07-18,FRN | 2026-07-19/2026-07-25,FRN | 2026-07-26/2026-08-01,FRN | 2026-08-02/2026-08-08,FRN | 2026-08-09/2026-08-15,FRN | 2026-08-16/2026-08-22,FRN | 2026-08-23/2026-08-29,FRN | 2026-08-30/2026-09-05,FRN | 2026-09-06/2026-09-12,FRN | 2026-09-13/2026-09-19,FRN | 2026-09-20/2026-09-26
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.001215,1.000442,1.000407,1.000648,1.000691,1.000446,1.000998,1.000691,1.000671,1.000694,1.000499,1.000264,1.000234,1.000575,1.000331,1.000000,1.000000
02_small_amt_financed,1.001215,1.000442,1.000407,1.000648,1.000691,1.000446,1.000998,1.000691,1.000671,1.000694,1.000499,1.000264,1.000234,1.000575,1.000331,1.000000,1.000000
03_zero_cash_down,1.001215,1.000442,1.000407,1.000648,1.000691,1.000446,1.000998,1.000691,1.000671,1.000694,1.000499,1.000264,1.000234,1.000575,1.000331,1.000000,1.000000
04_high_mileage,1.001215,1.000442,1.000407,1.001080,1.000922,1.000446,1.000998,1.000922,1.000671,1.000694,1.000998,1.000528,1.000234,1.001437,1.000331,1.000000,1.000000
05_high_pti,1.001215,1.000442,1.000407,1.001080,1.000922,1.000446,1.000998,1.000922,1.000671,1.000694,1.000998,1.000528,1.000234,1.001437,1.000331,1.000000,1.000000
06_car_make,0.947733,0.950442,0.950407,0.955724,0.959401,0.950893,0.955611,0.953917,0.948680,0.952500,0.953616,0.947230,0.953037,0.952011,0.940066,0.948858,0.940000
07_theft_risk,0.947733,0.950442,0.950407,0.955724,0.959401,0.950893,0.955611,0.953917,0.948680,0.952500,0.953616,0.947230,0.953037,0.952011,0.940066,0.948858,0.940000
08_mcy_low_mileage,0.947733,0.950442,0.950407,0.955724,0.959401,0.950893,0.955611,0.953917,0.948680,0.952500,0.953616,0.947230,0.953037,0.952011,0.940066,0.948858,0.940000
09_weekend_weekday,0.946637,0.951580,0.948315,0.954549,0.964605,0.952411,0.955800,0.953012,0.949081,0.951036,0.953469,0.948554,0.951850,0.954517,0.938748,0.951726,0.936400
10_student_loans,0.930808,0.937511,0.933514,0.938602,0.948928,0.937687,0.939630,0.938413,0.931934,0.934238,0.939215,0.934703,0.935841,0.942493,0.924514,0.930179,0.908308
11_low_pti,0.926012,0.929507,0.928634,0.933348,0.939287,0.929962,0.932350,0.932083,0.925191,0.930428,0.929789,0.929298,0.929745,0.933517,0.920217,0.924218,0.895446
12_chime,0.945081,0.949940,0.953228,0.954901,0.953609,0.960747,0.951917,0.951002,0.951478,0.954792,0.962676,0.956522,0.955573,0.972743,0.949523,0.904511,0.865001
13_employment_type,0.946583,0.950051,0.953274,0.956681,0.954650,0.960263,0.951682,0.950331,0.953568,0.955342,0.963542,0.957692,0.958048,0.973599,0.948823,0.904511,0.865001
14_auth_tradelines,0.949668,0.952487,0.955872,0.959155,0.956740,0.963068,0.953708,0.952040,0.956957,0.957908,0.967086,0.959488,0.960892,0.975067,0.949456,0.904948,0.865001
15_fraud,0.941271,0.944140,0.945463,0.951128,0.942165,0.949434,0.947328,0.943684,0.949673,0.949060,0.952325,0.946334,0.953647,0.960143,0.936343,0.904948,0.865001
16_driver_flag,0.948362,0.949832,0.952047,0.956178,0.946612,0.952636,0.952388,0.946960,0.952858,0.951861,0.958587,0.951230,0.956806,0.963594,0.940085,0.908144,0.873012
17_pricing_scalar,0.887702,0.889549,0.879894,0.877421,0.878781,0.873263,0.888465,0.873197,0.881260,0.877312,0.883468,0.884212,0.882436,0.874046,0.858317,0.847564,0.824459
18_final,0.894267,0.893761,0.887678,0.882750,0.883157,0.880666,0.890534,0.876607,0.887072,0.885238,0.888778,0.891723,0.887311,0.881033,0.867779,0.853617,0.829920
--- FINAL_MULT (mean),0.894267,0.893761,0.887678,0.882750,0.883157,0.880666,0.890534,0.876607,0.887072,0.885238,0.888778,0.891723,0.887311,0.881033,0.867779,0.853617,0.829920
--- WTD_MULT_RAGU,0.894703,0.888226,0.874992,0.874502,0.873772,0.868957,0.885954,0.873482,0.882399,0.871356,0.880598,0.880084,0.877364,0.868272,0.860238,0.847488,0.839684
--- GROSS_LOSS_IMPACT,2.632436,2.794359,3.125208,3.137453,3.155705,3.276077,2.851147,3.162957,2.940014,3.216103,2.985049,2.997901,3.065902,3.293195,3.494057,3.812804,4.007899
--- N_RECORDS,494.000000,452.000000,492.000000,463.000000,434.000000,448.000000,401.000000,434.000000,447.000000,432.000000,401.000000,379.000000,428.000000,348.000000,302.000000,219.000000,30.000000

--- FRN Flag Means ---

,FRN | 2026-05-31/2026-06-06,FRN | 2026-06-07/2026-06-13,FRN | 2026-06-14/2026-06-20,FRN | 2026-06-21/2026-06-27,FRN | 2026-06-28/2026-07-04,FRN | 2026-07-05/2026-07-11,FRN | 2026-07-12/2026-07-18,FRN | 2026-07-19/2026-07-25,FRN | 2026-07-26/2026-08-01,FRN | 2026-08-02/2026-08-08,FRN | 2026-08-09/2026-08-15,FRN | 2026-08-16/2026-08-22,FRN | 2026-08-23/2026-08-29,FRN | 2026-08-30/2026-09-05,FRN | 2026-09-06/2026-09-12,FRN | 2026-09-13/2026-09-19,FRN | 2026-09-20/2026-09-26
prev_co_flag,0.012146,0.004425,0.004065,0.006479,0.006912,0.004464,0.009975,0.006912,0.006711,0.006944,0.004988,0.002639,0.002336,0.005747,0.003311,0.000000,0.000000
small_amt_financed_flag,0.004049,0.017699,0.006098,0.010799,0.004608,0.013393,0.019950,0.009217,0.006711,0.011574,0.009975,0.013193,0.007009,0.014368,0.016556,0.018265,0.033333
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
zero_cash_down_flag,0.046559,0.070796,0.036585,0.043197,0.046083,0.066964,0.062344,0.043779,0.064877,0.046296,0.079800,0.055409,0.044393,0.040230,0.059603,0.045662,0.166667
high_mileage_vehicle_flag,0.000000,0.000000,0.000000,0.004320,0.002304,0.000000,0.000000,0.002304,0.000000,0.000000,0.004988,0.002639,0.000000,0.008621,0.000000,0.000000,0.000000
high_pti_flag,0.008097,0.004425,0.006098,0.000000,0.002304,0.006696,0.007481,0.004608,0.011186,0.009259,0.002494,0.002639,0.004673,0.005747,0.003311,0.004566,0.000000
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
car_make_benefit_flag,0.267206,0.250000,0.250000,0.226782,0.207373,0.247768,0.226933,0.235023,0.259508,0.240741,0.236908,0.266491,0.235981,0.247126,0.301325,0.255708,0.300000
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
weekend_flag,0.303644,0.269912,0.319106,0.308855,0.207373,0.265625,0.284289,0.299539,0.277405,0.307870,0.289277,0.266491,0.306075,0.250000,0.307947,0.242009,0.333333
weekday_flag,0.696356,0.730088,0.680894,0.691145,0.792627,0.734375,0.715711,0.700461,0.722595,0.692130,0.710723,0.733509,0.693925,0.750000,0.692053,0.757991,0.666667
student_loan_flag,0.097166,0.115044,0.107724,0.095032,0.103687,0.111607,0.099751,0.108295,0.087248,0.085648,0.109726,0.113456,0.098131,0.126437,0.109272,0.054795,0.000000
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
low_pti_flag,0.034413,0.055310,0.032520,0.036717,0.066820,0.053571,0.049875,0.043779,0.046980,0.025463,0.062344,0.036939,0.042056,0.060345,0.029801,0.041096,0.100000
nonkmx_chime_flag,0.196356,0.205752,0.219512,0.207343,0.179724,0.243304,0.201995,0.202765,0.228188,0.222222,0.256858,0.229551,0.226636,0.278736,0.241722,0.050228,0.000000
seasonal_employment_pct,0.022267,0.019912,0.016260,0.023758,0.020737,0.006696,0.019950,0.006912,0.033557,0.020833,0.022444,0.018470,0.032710,0.017241,0.003311,0.000000,0.000000
waiter_employment_pct,0.006073,0.019912,0.014228,0.004320,0.009217,0.011161,0.022444,0.013825,0.011186,0.013889,0.012469,0.007916,0.004673,0.008621,0.009934,0.000000,0.000000
nonkmx_auth_tradelines_flag,0.032389,0.026549,0.028455,0.025918,0.023041,0.029018,0.022444,0.018433,0.035794,0.027778,0.037406,0.021108,0.028037,0.014368,0.006623,0.004566,0.000000
fraud_adjustment_mean,0.991700,0.990907,0.989736,0.990842,0.984171,0.985357,0.994214,0.993180,0.991879,0.990764,0.984913,0.985567,0.992430,0.984253,0.986921,1.000000,1.000000
driver_flag,0.054656,0.044248,0.048780,0.038877,0.032258,0.022321,0.037406,0.023041,0.026846,0.023148,0.049875,0.036939,0.021028,0.025862,0.029801,0.022831,0.066667
pricing_scalar_mean,0.921103,0.924469,0.912424,0.907316,0.916740,0.905809,0.924158,0.911486,0.911890,0.911730,0.911976,0.913918,0.911203,0.899073,0.901714,0.922968,0.927750
--- N_RECORDS,494.000000,452.000000,492.000000,463.000000,434.000000,448.000000,401.000000,434.000000,447.000000,432.000000,401.000000,379.000000,428.000000,348.000000,302.000000,219.000000,30.000000

--- FRN Gross Loss Attribution ---

,FRN | 2026-05-31/2026-06-06,FRN | 2026-06-07/2026-06-13,FRN | 2026-06-14/2026-06-20,FRN | 2026-06-21/2026-06-27,FRN | 2026-06-28/2026-07-04,FRN | 2026-07-05/2026-07-11,FRN | 2026-07-12/2026-07-18,FRN | 2026-07-19/2026-07-25,FRN | 2026-07-26/2026-08-01,FRN | 2026-08-02/2026-08-08,FRN | 2026-08-09/2026-08-15,FRN | 2026-08-16/2026-08-22,FRN | 2026-08-23/2026-08-29,FRN | 2026-08-30/2026-09-05,FRN | 2026-09-06/2026-09-12,FRN | 2026-09-13/2026-09-19,FRN | 2026-09-20/2026-09-26
Previous ACA Chargeoff,-0.028594,-0.011006,-0.010660,-0.016295,-0.017550,-0.011506,-0.024519,-0.016596,-0.016461,-0.018316,-0.012624,-0.006901,-0.005991,-0.014938,-0.008157,-0.000000,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.000000,-0.000000,-0.000000,-0.010858,-0.005847,-0.000000,-0.000000,-0.005529,-0.000000,-0.000000,-0.012617,-0.006900,-0.000000,-0.022391,-0.000000,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,1.293164,1.275554,1.344865,1.166447,1.076034,1.309642,1.141139,1.155211,1.309060,1.302274,1.227644,1.432016,1.239461,1.315974,1.530886,1.264627,1.330234
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,0.027256,-0.029749,0.057785,0.030947,-0.137394,-0.041119,-0.004877,0.022810,-0.010366,0.040580,0.003906,-0.036554,0.031956,-0.068344,0.034564,-0.072694,0.082493
Student Loans,0.397219,0.370578,0.412618,0.423840,0.416171,0.401658,0.419639,0.370755,0.447322,0.470186,0.381329,0.384822,0.434962,0.329614,0.376445,0.551670,0.654830
Low PTI,0.121699,0.213324,0.137473,0.141216,0.259348,0.213267,0.191271,0.162556,0.178181,0.107795,0.255352,0.151685,0.167593,0.248810,0.114786,0.154885,0.306609
Chime / Secured Credit,-0.480162,-0.540999,-0.685631,-0.574334,-0.384327,-0.839588,-0.510772,-0.482623,-0.687396,-0.681982,-0.879969,-0.755328,-0.702645,-1.070195,-0.772401,0.519213,0.743667
Employment Type,-0.037428,-0.002893,-0.001268,-0.046872,-0.027716,0.012979,0.006060,0.016949,-0.053836,-0.015187,-0.022765,-0.031987,-0.066333,-0.022862,0.018162,-0.000000,-0.000000
Authorized Tradelines,-0.076624,-0.063720,-0.071390,-0.064974,-0.055540,-0.075181,-0.052295,-0.043135,-0.087038,-0.070761,-0.092962,-0.049020,-0.075999,-0.039195,-0.016430,-0.011621,-0.000000
Fraud Adjustment,0.209191,0.218980,0.287210,0.211443,0.389890,0.367554,0.165065,0.211714,0.187476,0.244837,0.389408,0.361136,0.194070,0.401048,0.342651,-0.000000,-0.000000
Driver Flag,-0.176785,-0.149534,-0.182033,-0.133221,-0.119593,-0.086781,-0.131020,-0.083226,-0.082145,-0.077748,-0.165939,-0.135005,-0.084815,-0.093301,-0.098280,-0.084937,-0.198201
Dealer Level (Pricing Scalar),1.557086,1.631345,2.067273,2.162469,1.888383,2.242779,1.708654,1.947667,1.916515,2.151740,2.065992,1.911195,2.074928,2.535993,2.241951,1.663110,1.230188
Final Clip,-0.173587,-0.117521,-0.231034,-0.152354,-0.126154,-0.217627,-0.057199,-0.093594,-0.161299,-0.237314,-0.151706,-0.221258,-0.141287,-0.207016,-0.270119,-0.171450,-0.141921
--- TOTAL (check),2.632436,2.794359,3.125208,3.137453,3.155705,3.276077,2.851147,3.162957,2.940014,3.216103,2.985049,2.997901,3.065902,3.293195,3.494057,3.812804,4.007899

============================================================
  DIAGNOSTICS: STG
============================================================

============================================================
  STG 2026-05-31/2026-06-06  (n=335)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.002985  | loss_multiplier mean: 1.000299
02_small_af | flag mean: 0.002985  | loss_multiplier mean: 1.000299
03_zero_cd  | flag mean: 0.083582  | loss_multiplier mean: 1.000299
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000299
05_high_pti | flag mean: 0.011940  | loss_multiplier mean: 1.000299
06_car_make | penalty: 0.000000  benefit: 0.331343  | loss_multiplier mean: 0.934030
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.934030
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.934030
09_wknd/day | weekend: 0.322388  weekday: 0.677612  | loss_multiplier mean: 0.931773
10_stud_ln  | flag mean: 0.125373  | loss_multiplier mean: 0.920260
11_low_pti  | flag mean: 0.035821  | loss_multiplier mean: 0.915409
12_chime    | flag mean: 0.220896  | loss_multiplier mean: 0.939171
13_employ   | seasonal: 0.008955  waiter: 0.014925  | loss_multiplier mean: 0.938694
14_auth_tl  | flag mean: 0.035821  | loss_multiplier mean: 0.941926
15_fraud    | fraud_adj mean: 0.983104  | loss_multiplier mean: 0.928124
16_driver   | flag mean: 0.026866  | loss_multiplier mean: 0.931996
17_pricing  | scalar mean: 0.946418  | loss_multiplier mean: 0.902404
18_final    | loss_multiplier mean: 0.899666  (post all clips)
  bb_populated: 333 / 335  wtd_mult: 0.887753  ragu_gli: 2.8062

============================================================
  STG 2026-06-07/2026-06-13  (n=341)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.002933  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.123167  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.002933  | loss_multiplier mean: 1.000293
05_high_pti | flag mean: 0.008798  | loss_multiplier mean: 1.000293
06_car_make | penalty: 0.000000  benefit: 0.354839  | loss_multiplier mean: 0.929326
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.929326
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.929326
09_wknd/day | weekend: 0.328446  weekday: 0.671554  | loss_multiplier mean: 0.926645
10_stud_ln  | flag mean: 0.131965  | loss_multiplier mean: 0.916635
11_low_pti  | flag mean: 0.032258  | loss_multiplier mean: 0.911775
12_chime    | flag mean: 0.199413  | loss_multiplier mean: 0.930963
13_employ   | seasonal: 0.014663  waiter: 0.014663  | loss_multiplier mean: 0.930864
14_auth_tl  | flag mean: 0.017595  | loss_multiplier mean: 0.932624
15_fraud    | fraud_adj mean: 0.973578  | loss_multiplier mean: 0.908125
16_driver   | flag mean: 0.032258  | loss_multiplier mean: 0.911826
17_pricing  | scalar mean: 0.932405  | loss_multiplier mean: 0.869938
18_final    | loss_multiplier mean: 0.877182  (post all clips)
  bb_populated: 341 / 341  wtd_mult: 0.867710  ragu_gli: 3.3073

============================================================
  STG 2026-06-14/2026-06-20  (n=327)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.009174  | loss_multiplier mean: 1.000917
02_small_af | flag mean: 0.009174  | loss_multiplier mean: 1.000917
03_zero_cd  | flag mean: 0.122324  | loss_multiplier mean: 1.000917
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000917
05_high_pti | flag mean: 0.003058  | loss_multiplier mean: 1.000917
06_car_make | penalty: 0.000000  benefit: 0.311927  | loss_multiplier mean: 0.938471
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.938471
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.938471
09_wknd/day | weekend: 0.314985  weekday: 0.685015  | loss_multiplier mean: 0.936412
10_stud_ln  | flag mean: 0.171254  | loss_multiplier mean: 0.931038
11_low_pti  | flag mean: 0.055046  | loss_multiplier mean: 0.922944
12_chime    | flag mean: 0.192661  | loss_multiplier mean: 0.941191
13_employ   | seasonal: 0.009174  waiter: 0.015291  | loss_multiplier mean: 0.940466
14_auth_tl  | flag mean: 0.021407  | loss_multiplier mean: 0.942510
15_fraud    | fraud_adj mean: 0.978226  | loss_multiplier mean: 0.921834
16_driver   | flag mean: 0.021407  | loss_multiplier mean: 0.924449
17_pricing  | scalar mean: 0.941437  | loss_multiplier mean: 0.888995
18_final    | loss_multiplier mean: 0.890289  (post all clips)
  bb_populated: 323 / 327  wtd_mult: 0.877915  ragu_gli: 3.0521

============================================================
  STG 2026-06-21/2026-06-27  (n=347)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.008646  | loss_multiplier mean: 1.000865
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000865
03_zero_cd  | flag mean: 0.115274  | loss_multiplier mean: 1.000865
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000865
05_high_pti | flag mean: 0.008646  | loss_multiplier mean: 1.000865
06_car_make | penalty: 0.000000  benefit: 0.319885  | loss_multiplier mean: 0.936888
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.936888
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.936888
09_wknd/day | weekend: 0.291066  weekday: 0.708934  | loss_multiplier mean: 0.936179
10_stud_ln  | flag mean: 0.097983  | loss_multiplier mean: 0.921428
11_low_pti  | flag mean: 0.048991  | loss_multiplier mean: 0.915002
12_chime    | flag mean: 0.230548  | loss_multiplier mean: 0.940569
13_employ   | seasonal: 0.011527  waiter: 0.011527  | loss_multiplier mean: 0.940518
14_auth_tl  | flag mean: 0.025937  | loss_multiplier mean: 0.942967
15_fraud    | fraud_adj mean: 0.977291  | loss_multiplier mean: 0.922505
16_driver   | flag mean: 0.005764  | loss_multiplier mean: 0.923364
17_pricing  | scalar mean: 0.944236  | loss_multiplier mean: 0.890005
18_final    | loss_multiplier mean: 0.892409  (post all clips)
  bb_populated: 344 / 347  wtd_mult: 0.874107  ragu_gli: 3.1473

============================================================
  STG 2026-06-28/2026-07-04  (n=335)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.002985  | loss_multiplier mean: 1.000299
02_small_af | flag mean: 0.005970  | loss_multiplier mean: 1.000299
03_zero_cd  | flag mean: 0.071642  | loss_multiplier mean: 1.000299
04_high_mi  | flag mean: 0.002985  | loss_multiplier mean: 1.000597
05_high_pti | flag mean: 0.005970  | loss_multiplier mean: 1.000597
06_car_make | penalty: 0.000000  benefit: 0.331343  | loss_multiplier mean: 0.934328
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.934328
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.934328
09_wknd/day | weekend: 0.208955  weekday: 0.791045  | loss_multiplier mean: 0.939224
10_stud_ln  | flag mean: 0.119403  | loss_multiplier mean: 0.927011
11_low_pti  | flag mean: 0.029851  | loss_multiplier mean: 0.922964
12_chime    | flag mean: 0.244776  | loss_multiplier mean: 0.952282
13_employ   | seasonal: 0.017910  waiter: 0.011940  | loss_multiplier mean: 0.952772
14_auth_tl  | flag mean: 0.023881  | loss_multiplier mean: 0.954959
15_fraud    | fraud_adj mean: 0.963045  | loss_multiplier mean: 0.919542
16_driver   | flag mean: 0.029851  | loss_multiplier mean: 0.923293
17_pricing  | scalar mean: 0.934925  | loss_multiplier mean: 0.879078
18_final    | loss_multiplier mean: 0.882766  (post all clips)
  bb_populated: 334 / 335  wtd_mult: 0.865358  ragu_gli: 3.3661

============================================================
  STG 2026-07-05/2026-07-11  (n=330)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.009091  | loss_multiplier mean: 1.000909
02_small_af | flag mean: 0.009091  | loss_multiplier mean: 1.000909
03_zero_cd  | flag mean: 0.100000  | loss_multiplier mean: 1.000909
04_high_mi  | flag mean: 0.006061  | loss_multiplier mean: 1.001515
05_high_pti | flag mean: 0.003030  | loss_multiplier mean: 1.001515
06_car_make | penalty: 0.000000  benefit: 0.284848  | loss_multiplier mean: 0.944485
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.944485
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.944485
09_wknd/day | weekend: 0.254545  weekday: 0.745455  | loss_multiplier mean: 0.946468
10_stud_ln  | flag mean: 0.127273  | loss_multiplier mean: 0.936065
11_low_pti  | flag mean: 0.042424  | loss_multiplier mean: 0.929558
12_chime    | flag mean: 0.233333  | loss_multiplier mean: 0.957910
13_employ   | seasonal: 0.009091  waiter: 0.030303  | loss_multiplier mean: 0.955976
14_auth_tl  | flag mean: 0.033333  | loss_multiplier mean: 0.959072
15_fraud    | fraud_adj mean: 0.982636  | loss_multiplier mean: 0.943932
16_driver   | flag mean: 0.048485  | loss_multiplier mean: 0.950781
17_pricing  | scalar mean: 0.932121  | loss_multiplier mean: 0.902401
18_final    | loss_multiplier mean: 0.902980  (post all clips)
  bb_populated: 330 / 330  wtd_mult: 0.886942  ragu_gli: 2.8265

============================================================
  STG 2026-07-12/2026-07-18  (n=341)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.002933  | loss_multiplier mean: 1.000293
02_small_af | flag mean: 0.002933  | loss_multiplier mean: 1.000293
03_zero_cd  | flag mean: 0.090909  | loss_multiplier mean: 1.000293
04_high_mi  | flag mean: 0.002933  | loss_multiplier mean: 1.000587
05_high_pti | flag mean: 0.002933  | loss_multiplier mean: 1.000587
06_car_make | penalty: 0.000000  benefit: 0.319648  | loss_multiplier mean: 0.936657
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.936657
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.936657
09_wknd/day | weekend: 0.316716  weekday: 0.683284  | loss_multiplier mean: 0.934698
10_stud_ln  | flag mean: 0.123167  | loss_multiplier mean: 0.922618
11_low_pti  | flag mean: 0.041056  | loss_multiplier mean: 0.916795
12_chime    | flag mean: 0.234604  | loss_multiplier mean: 0.944902
13_employ   | seasonal: 0.008798  waiter: 0.005865  | loss_multiplier mean: 0.944993
14_auth_tl  | flag mean: 0.014663  | loss_multiplier mean: 0.946227
15_fraud    | fraud_adj mean: 0.985161  | loss_multiplier mean: 0.933762
16_driver   | flag mean: 0.014663  | loss_multiplier mean: 0.935496
17_pricing  | scalar mean: 0.937537  | loss_multiplier mean: 0.891208
18_final    | loss_multiplier mean: 0.889864  (post all clips)
  bb_populated: 340 / 341  wtd_mult: 0.877520  ragu_gli: 3.0620

============================================================
  STG 2026-07-19/2026-07-25  (n=336)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.008929  | loss_multiplier mean: 1.000893
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000893
03_zero_cd  | flag mean: 0.119048  | loss_multiplier mean: 1.000893
04_high_mi  | flag mean: 0.002976  | loss_multiplier mean: 1.001190
05_high_pti | flag mean: 0.005952  | loss_multiplier mean: 1.001190
06_car_make | penalty: 0.002976  benefit: 0.303571  | loss_multiplier mean: 0.940655
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.940655
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.940655
09_wknd/day | weekend: 0.342262  weekday: 0.657738  | loss_multiplier mean: 0.937076
10_stud_ln  | flag mean: 0.145833  | loss_multiplier mean: 0.927836
11_low_pti  | flag mean: 0.050595  | loss_multiplier mean: 0.920585
12_chime    | flag mean: 0.235119  | loss_multiplier mean: 0.949146
13_employ   | seasonal: 0.005952  waiter: 0.008929  | loss_multiplier mean: 0.948850
14_auth_tl  | flag mean: 0.008929  | loss_multiplier mean: 0.949692
15_fraud    | fraud_adj mean: 0.978929  | loss_multiplier mean: 0.930587
16_driver   | flag mean: 0.029762  | loss_multiplier mean: 0.934702
17_pricing  | scalar mean: 0.932738  | loss_multiplier mean: 0.890239
18_final    | loss_multiplier mean: 0.893757  (post all clips)
  bb_populated: 335 / 336  wtd_mult: 0.877791  ragu_gli: 3.0552

============================================================
  STG 2026-07-26/2026-08-01  (n=351)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.014245  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.096866  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.002849  | loss_multiplier mean: 1.000285
05_high_pti | flag mean: 0.011396  | loss_multiplier mean: 1.000285
06_car_make | penalty: 0.000000  benefit: 0.313390  | loss_multiplier mean: 0.937607
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.937607
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.937607
09_wknd/day | weekend: 0.262108  weekday: 0.737892  | loss_multiplier mean: 0.939368
10_stud_ln  | flag mean: 0.119658  | loss_multiplier mean: 0.927556
11_low_pti  | flag mean: 0.045584  | loss_multiplier mean: 0.921431
12_chime    | flag mean: 0.230769  | loss_multiplier mean: 0.946895
13_employ   | seasonal: 0.011396  waiter: 0.011396  | loss_multiplier mean: 0.946723
14_auth_tl  | flag mean: 0.022792  | loss_multiplier mean: 0.948859
15_fraud    | fraud_adj mean: 0.982450  | loss_multiplier mean: 0.931588
16_driver   | flag mean: 0.028490  | loss_multiplier mean: 0.935611
17_pricing  | scalar mean: 0.929345  | loss_multiplier mean: 0.885773
18_final    | loss_multiplier mean: 0.890863  (post all clips)
  bb_populated: 349 / 351  wtd_mult: 0.882469  ragu_gli: 2.9383

============================================================
  STG 2026-08-02/2026-08-08  (n=296)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.003378  | loss_multiplier mean: 1.000338
02_small_af | flag mean: 0.010135  | loss_multiplier mean: 1.000338
03_zero_cd  | flag mean: 0.091216  | loss_multiplier mean: 1.000338
04_high_mi  | flag mean: 0.003378  | loss_multiplier mean: 1.000676
05_high_pti | flag mean: 0.003378  | loss_multiplier mean: 1.000676
06_car_make | penalty: 0.000000  benefit: 0.347973  | loss_multiplier mean: 0.931014
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.931014
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.931014
09_wknd/day | weekend: 0.270270  weekday: 0.729730  | loss_multiplier mean: 0.932162
10_stud_ln  | flag mean: 0.172297  | loss_multiplier mean: 0.925943
11_low_pti  | flag mean: 0.033784  | loss_multiplier mean: 0.920997
12_chime    | flag mean: 0.273649  | loss_multiplier mean: 0.958806
13_employ   | seasonal: 0.006757  waiter: 0.020270  | loss_multiplier mean: 0.957463
14_auth_tl  | flag mean: 0.020270  | loss_multiplier mean: 0.959334
15_fraud    | fraud_adj mean: 0.974831  | loss_multiplier mean: 0.935307
16_driver   | flag mean: 0.030405  | loss_multiplier mean: 0.939212
17_pricing  | scalar mean: 0.934966  | loss_multiplier mean: 0.896123
18_final    | loss_multiplier mean: 0.900449  (post all clips)
  bb_populated: 295 / 296  wtd_mult: 0.891308  ragu_gli: 2.7173

============================================================
  STG 2026-08-09/2026-08-15  (n=294)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006803  | loss_multiplier mean: 1.000680
02_small_af | flag mean: 0.003401  | loss_multiplier mean: 1.000680
03_zero_cd  | flag mean: 0.153061  | loss_multiplier mean: 1.000680
04_high_mi  | flag mean: 0.006803  | loss_multiplier mean: 1.001361
05_high_pti | flag mean: 0.006803  | loss_multiplier mean: 1.001361
06_car_make | penalty: 0.000000  benefit: 0.367347  | loss_multiplier mean: 0.927891
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.927891
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.927891
09_wknd/day | weekend: 0.326531  weekday: 0.673469  | loss_multiplier mean: 0.924806
10_stud_ln  | flag mean: 0.139456  | loss_multiplier mean: 0.915334
11_low_pti  | flag mean: 0.044218  | loss_multiplier mean: 0.909185
12_chime    | flag mean: 0.241497  | loss_multiplier mean: 0.938785
13_employ   | seasonal: 0.010204  waiter: 0.003401  | loss_multiplier mean: 0.939559
14_auth_tl  | flag mean: 0.023810  | loss_multiplier mean: 0.941822
15_fraud    | fraud_adj mean: 0.965952  | loss_multiplier mean: 0.911620
16_driver   | flag mean: 0.020408  | loss_multiplier mean: 0.914296
17_pricing  | scalar mean: 0.922279  | loss_multiplier mean: 0.863083
18_final    | loss_multiplier mean: 0.869515  (post all clips)
  bb_populated: 294 / 294  wtd_mult: 0.851020  ragu_gli: 3.7245

============================================================
  STG 2026-08-16/2026-08-22  (n=294)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.003401  | loss_multiplier mean: 1.000340
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000340
03_zero_cd  | flag mean: 0.095238  | loss_multiplier mean: 1.000340
04_high_mi  | flag mean: 0.006803  | loss_multiplier mean: 1.001020
05_high_pti | flag mean: 0.010204  | loss_multiplier mean: 1.001020
06_car_make | penalty: 0.000000  benefit: 0.329932  | loss_multiplier mean: 0.934966
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.934966
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.934966
09_wknd/day | weekend: 0.323129  weekday: 0.676871  | loss_multiplier mean: 0.932456
10_stud_ln  | flag mean: 0.132653  | loss_multiplier mean: 0.922030
11_low_pti  | flag mean: 0.017007  | loss_multiplier mean: 0.919641
12_chime    | flag mean: 0.244898  | loss_multiplier mean: 0.949166
13_employ   | seasonal: 0.000000  waiter: 0.010204  | loss_multiplier mean: 0.948147
14_auth_tl  | flag mean: 0.020408  | loss_multiplier mean: 0.949971
15_fraud    | fraud_adj mean: 0.981939  | loss_multiplier mean: 0.931996
16_driver   | flag mean: 0.017007  | loss_multiplier mean: 0.934277
17_pricing  | scalar mean: 0.939966  | loss_multiplier mean: 0.897589
18_final    | loss_multiplier mean: 0.897552  (post all clips)
  bb_populated: 292 / 294  wtd_mult: 0.875387  ragu_gli: 3.1153

============================================================
  STG 2026-08-23/2026-08-29  (n=269)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.007435  | loss_multiplier mean: 1.000743
02_small_af | flag mean: 0.003717  | loss_multiplier mean: 1.000743
03_zero_cd  | flag mean: 0.107807  | loss_multiplier mean: 1.000743
04_high_mi  | flag mean: 0.007435  | loss_multiplier mean: 1.001487
05_high_pti | flag mean: 0.003717  | loss_multiplier mean: 1.001487
06_car_make | penalty: 0.003717  benefit: 0.364312  | loss_multiplier mean: 0.929033
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.929033
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.929033
09_wknd/day | weekend: 0.334572  weekday: 0.665428  | loss_multiplier mean: 0.926068
10_stud_ln  | flag mean: 0.115242  | loss_multiplier mean: 0.914309
11_low_pti  | flag mean: 0.037175  | loss_multiplier mean: 0.908815
12_chime    | flag mean: 0.163569  | loss_multiplier mean: 0.918288
13_employ   | seasonal: 0.018587  waiter: 0.011152  | loss_multiplier mean: 0.919007
14_auth_tl  | flag mean: 0.029740  | loss_multiplier mean: 0.921640
15_fraud    | fraud_adj mean: 0.989368  | loss_multiplier mean: 0.913497

,STG | 2026-05-31/2026-06-06,STG | 2026-06-07/2026-06-13,STG | 2026-06-14/2026-06-20,STG | 2026-06-21/2026-06-27,STG | 2026-06-28/2026-07-04,STG | 2026-07-05/2026-07-11,STG | 2026-07-12/2026-07-18,STG | 2026-07-19/2026-07-25,STG | 2026-07-26/2026-08-01,STG | 2026-08-02/2026-08-08,STG | 2026-08-09/2026-08-15,STG | 2026-08-16/2026-08-22,STG | 2026-08-23/2026-08-29,STG | 2026-08-30/2026-09-05,STG | 2026-09-06/2026-09-12,STG | 2026-09-13/2026-09-19,STG | 2026-09-20/2026-09-26
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000299,1.000000,1.000917,1.000865,1.000299,1.000909,1.000293,1.000893,1.000000,1.000338,1.000680,1.000340,1.000743,1.000820,1.000000,1.000000,1.000000
02_small_amt_financed,1.000299,1.000000,1.000917,1.000865,1.000299,1.000909,1.000293,1.000893,1.000000,1.000338,1.000680,1.000340,1.000743,1.000820,1.000000,1.000000,1.000000
03_zero_cash_down,1.000299,1.000000,1.000917,1.000865,1.000299,1.000909,1.000293,1.000893,1.000000,1.000338,1.000680,1.000340,1.000743,1.000820,1.000000,1.000000,1.000000
04_high_mileage,1.000299,1.000293,1.000917,1.000865,1.000597,1.001515,1.000587,1.001190,1.000285,1.000676,1.001361,1.001020,1.001487,1.000820,1.000000,1.000000,1.000000
05_high_pti,1.000299,1.000293,1.000917,1.000865,1.000597,1.001515,1.000587,1.001190,1.000285,1.000676,1.001361,1.001020,1.001487,1.000820,1.000000,1.000000,1.000000
06_car_make,0.934030,0.929326,0.938471,0.936888,0.934328,0.944485,0.936657,0.940655,0.937607,0.931014,0.927891,0.934966,0.929033,0.932377,0.935931,0.930435,0.945455
07_theft_risk,0.934030,0.929326,0.938471,0.936888,0.934328,0.944485,0.936657,0.940655,0.937607,0.931014,0.927891,0.934966,0.929033,0.932377,0.935931,0.930435,0.945455
08_mcy_low_mileage,0.934030,0.929326,0.938471,0.936888,0.934328,0.944485,0.936657,0.940655,0.937607,0.931014,0.927891,0.934966,0.929033,0.932377,0.935931,0.930435,0.945455
09_weekend_weekday,0.931773,0.926645,0.936412,0.936179,0.939224,0.946468,0.934698,0.937076,0.939368,0.932162,0.924806,0.932456,0.926068,0.930111,0.936225,0.935348,0.951636
10_student_loans,0.920260,0.916635,0.931038,0.921428,0.927011,0.936065,0.922618,0.927836,0.927556,0.925943,0.915334,0.922030,0.914309,0.914712,0.926210,0.913872,0.923087
11_low_pti,0.915409,0.911775,0.922944,0.915002,0.922964,0.929558,0.916795,0.920585,0.921431,0.920997,0.909185,0.919641,0.908815,0.909337,0.919786,0.911936,0.923087
12_chime,0.939171,0.930963,0.941191,0.940569,0.952282,0.957910,0.944902,0.949146,0.946895,0.958806,0.938785,0.949166,0.918288,0.944455,0.939606,0.907371,0.891702
13_employment_type,0.938694,0.930864,0.940466,0.940518,0.952772,0.955976,0.944993,0.948850,0.946723,0.957463,0.939559,0.948147,0.919007,0.944151,0.939710,0.907371,0.891702
14_auth_tradelines,0.941926,0.932624,0.942510,0.942967,0.954959,0.959072,0.946227,0.949692,0.948859,0.959334,0.941822,0.949971,0.921640,0.945765,0.941784,0.907371,0.891702
15_fraud,0.928124,0.908125,0.921834,0.922505,0.919542,0.943932,0.933762,0.930587,0.931588,0.935307,0.911620,0.931996,0.913497,0.921537,0.933998,0.907371,0.891702
16_driver_flag,0.931996,0.911826,0.924449,0.923364,0.923293,0.950781,0.935496,0.934702,0.935611,0.939212,0.914296,0.934277,0.917517,0.926424,0.937198,0.912301,0.891702
17_pricing_scalar,0.902404,0.869938,0.888995,0.890005,0.879078,0.902401,0.891208,0.890239,0.885773,0.896123,0.863083,0.897589,0.875231,0.893180,0.903923,0.866950,0.902584
18_final,0.899666,0.877182,0.890289,0.892409,0.882766,0.902980,0.889864,0.893757,0.890863,0.900449,0.869515,0.897552,0.877089,0.895198,0.904303,0.872494,0.904402
--- FINAL_MULT (mean),0.899666,0.877182,0.890289,0.892409,0.882766,0.902980,0.889864,0.893757,0.890863,0.900449,0.869515,0.897552,0.877089,0.895198,0.904303,0.872494,0.904402
--- WTD_MULT_RAGU,0.887753,0.867710,0.877915,0.874107,0.865358,0.886942,0.877520,0.877791,0.882469,0.891308,0.851020,0.875387,0.866064,0.876218,0.884042,0.854280,0.897182
--- GROSS_LOSS_IMPACT,2.806163,3.307258,3.052130,3.147334,3.366060,2.826458,3.062003,3.055230,2.938275,2.717294,3.724500,3.115319,3.348410,3.094555,2.898953,3.643008,2.570445
--- N_RECORDS,335.000000,341.000000,327.000000,347.000000,335.000000,330.000000,341.000000,336.000000,351.000000,296.000000,294.000000,294.000000,269.000000,244.000000,231.000000,138.000000,11.000000

--- STG Flag Means ---

,STG | 2026-05-31/2026-06-06,STG | 2026-06-07/2026-06-13,STG | 2026-06-14/2026-06-20,STG | 2026-06-21/2026-06-27,STG | 2026-06-28/2026-07-04,STG | 2026-07-05/2026-07-11,STG | 2026-07-12/2026-07-18,STG | 2026-07-19/2026-07-25,STG | 2026-07-26/2026-08-01,STG | 2026-08-02/2026-08-08,STG | 2026-08-09/2026-08-15,STG | 2026-08-16/2026-08-22,STG | 2026-08-23/2026-08-29,STG | 2026-08-30/2026-09-05,STG | 2026-09-06/2026-09-12,STG | 2026-09-13/2026-09-19,STG | 2026-09-20/2026-09-26
prev_co_flag,0.002985,0.000000,0.009174,0.008646,0.002985,0.009091,0.002933,0.008929,0.000000,0.003378,0.006803,0.003401,0.007435,0.008197,0.000000,0.000000,0.000000
small_amt_financed_flag,0.002985,0.002933,0.009174,0.000000,0.005970,0.009091,0.002933,0.000000,0.014245,0.010135,0.003401,0.000000,0.003717,0.004098,0.021645,0.007246,0.090909
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
zero_cash_down_flag,0.083582,0.123167,0.122324,0.115274,0.071642,0.100000,0.090909,0.119048,0.096866,0.091216,0.153061,0.095238,0.107807,0.086066,0.095238,0.101449,0.090909
high_mileage_vehicle_flag,0.000000,0.002933,0.000000,0.000000,0.002985,0.006061,0.002933,0.002976,0.002849,0.003378,0.006803,0.006803,0.007435,0.000000,0.000000,0.000000,0.000000
high_pti_flag,0.011940,0.008798,0.003058,0.008646,0.005970,0.003030,0.002933,0.005952,0.011396,0.003378,0.006803,0.010204,0.003717,0.016393,0.000000,0.021739,0.090909
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002976,0.000000,0.000000,0.000000,0.000000,0.003717,0.004098,0.000000,0.000000,0.000000
car_make_benefit_flag,0.331343,0.354839,0.311927,0.319885,0.331343,0.284848,0.319648,0.303571,0.313390,0.347973,0.367347,0.329932,0.364312,0.344262,0.320346,0.347826,0.272727
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
weekend_flag,0.322388,0.328446,0.314985,0.291066,0.208955,0.254545,0.316716,0.342262,0.262108,0.270270,0.326531,0.323129,0.334572,0.323770,0.281385,0.210145,0.181818
weekday_flag,0.677612,0.671554,0.685015,0.708934,0.791045,0.745455,0.683284,0.657738,0.737892,0.729730,0.673469,0.676871,0.665428,0.676230,0.718615,0.789855,0.818182
student_loan_flag,0.125373,0.131965,0.171254,0.097983,0.119403,0.127273,0.123167,0.145833,0.119658,0.172297,0.139456,0.132653,0.115242,0.098361,0.138528,0.043478,0.000000
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
low_pti_flag,0.035821,0.032258,0.055046,0.048991,0.029851,0.042424,0.041056,0.050595,0.045584,0.033784,0.044218,0.017007,0.037175,0.045082,0.043290,0.014493,0.000000
nonkmx_chime_flag,0.220896,0.199413,0.192661,0.230548,0.244776,0.233333,0.234604,0.235119,0.230769,0.273649,0.241497,0.244898,0.163569,0.262295,0.199134,0.101449,0.000000
seasonal_employment_pct,0.008955,0.014663,0.009174,0.011527,0.017910,0.009091,0.008798,0.005952,0.011396,0.006757,0.010204,0.000000,0.018587,0.008197,0.004329,0.000000,0.000000
waiter_employment_pct,0.014925,0.014663,0.015291,0.011527,0.011940,0.030303,0.005865,0.008929,0.011396,0.020270,0.003401,0.010204,0.011152,0.008197,0.004329,0.000000,0.000000
nonkmx_auth_tradelines_flag,0.035821,0.017595,0.021407,0.025937,0.023881,0.033333,0.014663,0.008929,0.022792,0.020270,0.023810,0.020408,0.029740,0.016393,0.021645,0.000000,0.000000
fraud_adjustment_mean,0.983104,0.973578,0.978226,0.977291,0.963045,0.982636,0.985161,0.978929,0.982450,0.974831,0.965952,0.981939,0.989368,0.974344,0.990736,1.000000,1.000000
driver_flag,0.026866,0.032258,0.021407,0.005764,0.029851,0.048485,0.014663,0.029762,0.028490,0.030405,0.020408,0.017007,0.029740,0.036885,0.025974,0.043478,0.000000
pricing_scalar_mean,0.946418,0.932405,0.941437,0.944236,0.934925,0.932121,0.937537,0.932738,0.929345,0.934966,0.922279,0.939966,0.934201,0.942213,0.951299,0.937319,1.000000
--- N_RECORDS,335.000000,341.000000,327.000000,347.000000,335.000000,330.000000,341.000000,336.000000,351.000000,296.000000,294.000000,294.000000,269.000000,244.000000,231.000000,138.000000,11.000000

--- STG Gross Loss Attribution ---

,STG | 2026-05-31/2026-06-06,STG | 2026-06-07/2026-06-13,STG | 2026-06-14/2026-06-20,STG | 2026-06-21/2026-06-27,STG | 2026-06-28/2026-07-04,STG | 2026-07-05/2026-07-11,STG | 2026-07-12/2026-07-18,STG | 2026-07-19/2026-07-25,STG | 2026-07-26/2026-08-01,STG | 2026-08-02/2026-08-08,STG | 2026-08-09/2026-08-15,STG | 2026-08-16/2026-08-22,STG | 2026-08-23/2026-08-29,STG | 2026-08-30/2026-09-05,STG | 2026-09-06/2026-09-12,STG | 2026-09-13/2026-09-19,STG | 2026-09-20/2026-09-26
Previous ACA Chargeoff,-0.007921,-0.000000,-0.024084,-0.023894,-0.008057,-0.025166,-0.007694,-0.024275,-0.000000,-0.008753,-0.018115,-0.009802,-0.018976,-0.022902,-0.000000,-0.000000,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.000000,-0.007400,-0.000000,-0.000000,-0.008054,-0.016765,-0.007692,-0.008087,-0.007243,-0.008750,-0.018103,-0.019594,-0.018962,-0.000000,-0.000000,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,1.819213,1.857283,1.691938,1.826401,1.849761,1.623773,1.732572,1.696476,1.645267,1.869806,2.029816,1.967614,1.917337,1.980032,1.908234,1.925760,1.434848
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,0.064202,0.072898,0.057696,0.020930,-0.141070,-0.058106,0.054939,0.103678,-0.047700,-0.031951,0.088713,0.077489,0.081636,0.068027,-0.009063,-0.140659,-0.166719
Student Loans,0.329988,0.274118,0.151151,0.439112,0.353321,0.306123,0.341361,0.269554,0.321733,0.173463,0.274241,0.324102,0.326248,0.466642,0.309944,0.620380,0.779190
Low PTI,0.140275,0.134185,0.229325,0.193508,0.118111,0.193170,0.166126,0.213412,0.168434,0.138798,0.179546,0.074759,0.153906,0.164729,0.200590,0.056634,-0.000000
Chime / Secured Credit,-0.680161,-0.525640,-0.514195,-0.761984,-0.844158,-0.832082,-0.792413,-0.831073,-0.693100,-1.042544,-0.853421,-0.910820,-0.264769,-1.059169,-0.614418,0.134038,0.884898
Employment Type,0.013507,0.002688,0.020259,0.001497,-0.013881,0.055962,-0.002531,0.008469,0.004609,0.036321,-0.021953,0.030949,-0.019989,0.009021,-0.003176,-0.000000,-0.000000
Authorized Tradelines,-0.091241,-0.047657,-0.057031,-0.071891,-0.061890,-0.089541,-0.034233,-0.024119,-0.057291,-0.050589,-0.064083,-0.055366,-0.073044,-0.047768,-0.063540,-0.000000,-0.000000
Fraud Adjustment,0.391763,0.671844,0.582586,0.606567,1.020187,0.440680,0.347985,0.552788,0.467057,0.657268,0.868224,0.550603,0.226588,0.725392,0.239245,-0.000000,-0.000000
Driver Flag,-0.110479,-0.102654,-0.074418,-0.025710,-0.109897,-0.200225,-0.048681,-0.120020,-0.109558,-0.107953,-0.078091,-0.070467,-0.112096,-0.147826,-0.098590,-0.144708,-0.000000
Dealer Level (Pricing Scalar),0.856341,1.186886,1.027093,1.017366,1.324711,1.446385,1.272659,1.325688,1.391771,1.216954,1.535509,1.154665,1.204646,1.021473,1.041840,1.361818,-0.310292
Final Clip,0.080675,-0.209293,-0.038189,-0.074567,-0.113022,-0.017749,0.039606,-0.107261,-0.145706,-0.124776,-0.197784,0.001188,-0.054117,-0.063096,-0.012114,-0.170256,-0.051480
--- TOTAL (check),2.806163,3.307258,3.052130,3.147334,3.366060,2.826458,3.062003,3.055230,2.938275,2.717294,3.724500,3.115319,3.348410,3.094555,2.898953,3.643008,2.570445

============================================================
  DIAGNOSTICS: FLD
============================================================

============================================================
  FLD 2026-05-31/2026-06-06  (n=141)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.007092  | loss_multiplier mean: 1.000709
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000709
03_zero_cd  | flag mean: 0.106383  | loss_multiplier mean: 1.000709
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000709
05_high_pti | flag mean: 0.014184  | loss_multiplier mean: 1.000709
06_car_make | penalty: 0.000000  benefit: 0.141844  | loss_multiplier mean: 0.972340
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.972340
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.972340
09_wknd/day | weekend: 0.262411  weekday: 0.737589  | loss_multiplier mean: 0.974014
10_stud_ln  | flag mean: 0.170213  | loss_multiplier mean: 0.966581
11_low_pti  | flag mean: 0.063830  | loss_multiplier mean: 0.957698
12_chime    | flag mean: 0.248227  | loss_multiplier mean: 0.989951
13_employ   | seasonal: 0.021277  waiter: 0.021277  | loss_multiplier mean: 0.990127
14_auth_tl  | flag mean: 0.021277  | loss_multiplier mean: 0.991907
15_fraud    | fraud_adj mean: 0.992553  | loss_multiplier mean: 0.984545
16_driver   | flag mean: 0.049645  | loss_multiplier mean: 0.992820
17_pricing  | scalar mean: 0.890426  | loss_multiplier mean: 0.892367
18_final    | loss_multiplier mean: 0.889256  (post all clips)
  bb_populated: 141 / 141  wtd_mult: 0.901134  ragu_gli: 2.4717

============================================================
  FLD 2026-06-07/2026-06-13  (n=140)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.021429  | loss_multiplier mean: 1.002143
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002143
03_zero_cd  | flag mean: 0.071429  | loss_multiplier mean: 1.002143
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002143
05_high_pti | flag mean: 0.014286  | loss_multiplier mean: 1.002143
06_car_make | penalty: 0.000000  benefit: 0.164286  | loss_multiplier mean: 0.969286
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.969286
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.969286
09_wknd/day | weekend: 0.271429  weekday: 0.728571  | loss_multiplier mean: 0.970271
10_stud_ln  | flag mean: 0.164286  | loss_multiplier mean: 0.963206
11_low_pti  | flag mean: 0.028571  | loss_multiplier mean: 0.958907
12_chime    | flag mean: 0.250000  | loss_multiplier mean: 0.991034
13_employ   | seasonal: 0.014286  waiter: 0.014286  | loss_multiplier mean: 0.991181
14_auth_tl  | flag mean: 0.035714  | loss_multiplier mean: 0.994838
15_fraud    | fraud_adj mean: 0.997714  | loss_multiplier mean: 0.991847
16_driver   | flag mean: 0.035714  | loss_multiplier mean: 0.996841
17_pricing  | scalar mean: 0.863571  | loss_multiplier mean: 0.864955
18_final    | loss_multiplier mean: 0.878263  (post all clips)
  bb_populated: 140 / 140  wtd_mult: 0.871312  ragu_gli: 3.2172

============================================================
  FLD 2026-06-14/2026-06-20  (n=147)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.156463  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.163265  | loss_multiplier mean: 0.967347
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.967347
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.967347
09_wknd/day | weekend: 0.265306  weekday: 0.734694  | loss_multiplier mean: 0.968694
10_stud_ln  | flag mean: 0.204082  | loss_multiplier mean: 0.965580
11_low_pti  | flag mean: 0.054422  | loss_multiplier mean: 0.956963
12_chime    | flag mean: 0.265306  | loss_multiplier mean: 0.993064
13_employ   | seasonal: 0.020408  waiter: 0.013605  | loss_multiplier mean: 0.994217
14_auth_tl  | flag mean: 0.020408  | loss_multiplier mean: 0.996184
15_fraud    | fraud_adj mean: 0.991905  | loss_multiplier mean: 0.987976
16_driver   | flag mean: 0.040816  | loss_multiplier mean: 0.993641
17_pricing  | scalar mean: 0.884014  | loss_multiplier mean: 0.885138
18_final    | loss_multiplier mean: 0.896117  (post all clips)
  bb_populated: 146 / 147  wtd_mult: 0.898460  ragu_gli: 2.5385

============================================================
  FLD 2026-06-21/2026-06-27  (n=170)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.017647  | loss_multiplier mean: 1.001765
02_small_af | flag mean: 0.017647  | loss_multiplier mean: 1.001765
03_zero_cd  | flag mean: 0.152941  | loss_multiplier mean: 1.001765
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001765
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001765
06_car_make | penalty: 0.000000  benefit: 0.158824  | loss_multiplier mean: 0.970000
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.970000
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.970000
09_wknd/day | weekend: 0.282353  weekday: 0.717647  | loss_multiplier mean: 0.970171
10_stud_ln  | flag mean: 0.182353  | loss_multiplier mean: 0.965604
11_low_pti  | flag mean: 0.058824  | loss_multiplier mean: 0.957161
12_chime    | flag mean: 0.247059  | loss_multiplier mean: 0.988701
13_employ   | seasonal: 0.011765  waiter: 0.005882  | loss_multiplier mean: 0.989263
14_auth_tl  | flag mean: 0.011765  | loss_multiplier mean: 0.990459
15_fraud    | fraud_adj mean: 0.993941  | loss_multiplier mean: 0.986572
16_driver   | flag mean: 0.041176  | loss_multiplier mean: 0.992844
17_pricing  | scalar mean: 0.892647  | loss_multiplier mean: 0.899200
18_final    | loss_multiplier mean: 0.893996  (post all clips)
  bb_populated: 167 / 170  wtd_mult: 0.893008  ragu_gli: 2.6748

============================================================
  FLD 2026-06-28/2026-07-04  (n=139)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.014388  | loss_multiplier mean: 1.001439
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001439
03_zero_cd  | flag mean: 0.151079  | loss_multiplier mean: 1.001439
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001439
05_high_pti | flag mean: 0.007194  | loss_multiplier mean: 1.001439
06_car_make | penalty: 0.000000  benefit: 0.115108  | loss_multiplier mean: 0.978417
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.978417
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.978417
09_wknd/day | weekend: 0.143885  weekday: 0.856115  | loss_multiplier mean: 0.988518
10_stud_ln  | flag mean: 0.230216  | loss_multiplier mean: 0.988993
11_low_pti  | flag mean: 0.028777  | loss_multiplier mean: 0.984722
12_chime    | flag mean: 0.201439  | loss_multiplier mean: 1.006849
13_employ   | seasonal: 0.007194  waiter: 0.007194  | loss_multiplier mean: 1.007043
14_auth_tl  | flag mean: 0.043165  | loss_multiplier mean: 1.011675
15_fraud    | fraud_adj mean: 1.002662  | loss_multiplier mean: 1.014232
16_driver   | flag mean: 0.035971  | loss_multiplier mean: 1.019232
17_pricing  | scalar mean: 0.893885  | loss_multiplier mean: 0.916084
18_final    | loss_multiplier mean: 0.924309  (post all clips)
  bb_populated: 139 / 139  wtd_mult: 0.922115  ragu_gli: 1.9471

============================================================
  FLD 2026-07-05/2026-07-11  (n=143)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.006993  | loss_multiplier mean: 1.000699
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000699
03_zero_cd  | flag mean: 0.174825  | loss_multiplier mean: 1.000699
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000699
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000699
06_car_make | penalty: 0.000000  benefit: 0.139860  | loss_multiplier mean: 0.972727
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.972727
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.972727
09_wknd/day | weekend: 0.307692  weekday: 0.692308  | loss_multiplier mean: 0.971231
10_stud_ln  | flag mean: 0.167832  | loss_multiplier mean: 0.963967
11_low_pti  | flag mean: 0.020979  | loss_multiplier mean: 0.960783
12_chime    | flag mean: 0.258741  | loss_multiplier mean: 0.995871
13_employ   | seasonal: 0.000000  waiter: 0.006993  | loss_multiplier mean: 0.995373
14_auth_tl  | flag mean: 0.013986  | loss_multiplier mean: 0.996319
15_fraud    | fraud_adj mean: 1.000979  | loss_multiplier mean: 0.997636
16_driver   | flag mean: 0.020979  | loss_multiplier mean: 1.001025
17_pricing  | scalar mean: 0.876923  | loss_multiplier mean: 0.881456
18_final    | loss_multiplier mean: 0.892723  (post all clips)
  bb_populated: 143 / 143  wtd_mult: 0.893246  ragu_gli: 2.6689

============================================================
  FLD 2026-07-12/2026-07-18  (n=142)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.021127  | loss_multiplier mean: 1.002113
02_small_af | flag mean: 0.014085  | loss_multiplier mean: 1.002113
03_zero_cd  | flag mean: 0.147887  | loss_multiplier mean: 1.002113
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002113
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.002113
06_car_make | penalty: 0.000000  benefit: 0.154930  | loss_multiplier mean: 0.971127
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.971127
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.971127
09_wknd/day | weekend: 0.274648  weekday: 0.725352  | loss_multiplier mean: 0.971620
10_stud_ln  | flag mean: 0.204225  | loss_multiplier mean: 0.969298
11_low_pti  | flag mean: 0.042254  | loss_multiplier mean: 0.963111
12_chime    | flag mean: 0.239437  | loss_multiplier mean: 0.994096
13_employ   | seasonal: 0.021127  waiter: 0.021127  | loss_multiplier mean: 0.994287
14_auth_tl  | flag mean: 0.049296  | loss_multiplier mean: 0.998996
15_fraud    | fraud_adj mean: 1.006056  | loss_multiplier mean: 1.003345
16_driver   | flag mean: 0.042254  | loss_multiplier mean: 1.010540
17_pricing  | scalar mean: 0.910915  | loss_multiplier mean: 0.929855
18_final    | loss_multiplier mean: 0.921371  (post all clips)
  bb_populated: 141 / 142  wtd_mult: 0.917720  ragu_gli: 2.0570

============================================================
  FLD 2026-07-19/2026-07-25  (n=165)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.012121  | loss_multiplier mean: 1.001212
02_small_af | flag mean: 0.006061  | loss_multiplier mean: 1.001212
03_zero_cd  | flag mean: 0.121212  | loss_multiplier mean: 1.001212
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001212
05_high_pti | flag mean: 0.012121  | loss_multiplier mean: 1.001212
06_car_make | penalty: 0.000000  benefit: 0.200000  | loss_multiplier mean: 0.961212
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.961212
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.961212
09_wknd/day | weekend: 0.254545  weekday: 0.745455  | loss_multiplier mean: 0.963891
10_stud_ln  | flag mean: 0.212121  | loss_multiplier mean: 0.962296
11_low_pti  | flag mean: 0.024242  | loss_multiplier mean: 0.958841
12_chime    | flag mean: 0.248485  | loss_multiplier mean: 0.991047
13_employ   | seasonal: 0.018182  waiter: 0.006061  | loss_multiplier mean: 0.992355
14_auth_tl  | flag mean: 0.036364  | loss_multiplier mean: 0.995982
15_fraud    | fraud_adj mean: 0.995697  | loss_multiplier mean: 0.993341
16_driver   | flag mean: 0.042424  | loss_multiplier mean: 0.999301
17_pricing  | scalar mean: 0.909394  | loss_multiplier mean: 0.915447
18_final    | loss_multiplier mean: 0.917308  (post all clips)
  bb_populated: 165 / 165  wtd_mult: 0.903148  ragu_gli: 2.4213

============================================================
  FLD 2026-07-26/2026-08-01  (n=119)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.033613  | loss_multiplier mean: 1.003361
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.003361
03_zero_cd  | flag mean: 0.100840  | loss_multiplier mean: 1.003361
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.003361
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.003361
06_car_make | penalty: 0.008403  benefit: 0.176471  | loss_multiplier mean: 0.968908
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.968908
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.968908
09_wknd/day | weekend: 0.302521  weekday: 0.697479  | loss_multiplier mean: 0.968050
10_stud_ln  | flag mean: 0.235294  | loss_multiplier mean: 0.969416
11_low_pti  | flag mean: 0.067227  | loss_multiplier mean: 0.959605
12_chime    | flag mean: 0.285714  | loss_multiplier mean: 1.002338
13_employ   | seasonal: 0.000000  waiter: 0.025210  | loss_multiplier mean: 0.999644
14_auth_tl  | flag mean: 0.016807  | loss_multiplier mean: 1.001197
15_fraud    | fraud_adj mean: 0.985798  | loss_multiplier mean: 0.988566
16_driver   | flag mean: 0.025210  | loss_multiplier mean: 0.992234
17_pricing  | scalar mean: 0.856723  | loss_multiplier mean: 0.859336
18_final    | loss_multiplier mean: 0.873872  (post all clips)
  bb_populated: 118 / 119  wtd_mult: 0.877372  ragu_gli: 3.0657

============================================================
  FLD 2026-08-02/2026-08-08  (n=89)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.112360  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.235955  | loss_multiplier mean: 0.952809
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.952809
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.952809
09_wknd/day | weekend: 0.213483  weekday: 0.786517  | loss_multiplier mean: 0.958022
10_stud_ln  | flag mean: 0.123596  | loss_multiplier mean: 0.945483
11_low_pti  | flag mean: 0.022472  | loss_multiplier mean: 0.942169
12_chime    | flag mean: 0.146067  | loss_multiplier mean: 0.946809
13_employ   | seasonal: 0.011236  waiter: 0.000000  | loss_multiplier mean: 0.947669
14_auth_tl  | flag mean: 0.011236  | loss_multiplier mean: 0.948479
15_fraud    | fraud_adj mean: 0.987079  | loss_multiplier mean: 0.936057
16_driver   | flag mean: 0.044944  | loss_multiplier mean: 0.943437
17_pricing  | scalar mean: 0.856180  | loss_multiplier mean: 0.822171
18_final    | loss_multiplier mean: 0.841795  (post all clips)
  bb_populated: 88 / 89  wtd_mult: 0.847212  ragu_gli: 3.8197

============================================================
  FLD 2026-08-09/2026-08-15  (n=99)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.010101  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.131313  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.161616  | loss_multiplier mean: 0.967677
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.967677
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.967677
09_wknd/day | weekend: 0.212121  weekday: 0.787879  | loss_multiplier mean: 0.972465
10_stud_ln  | flag mean: 0.303030  | loss_multiplier mean: 0.983280
11_low_pti  | flag mean: 0.050505  | loss_multiplier mean: 0.976765
12_chime    | flag mean: 0.313131  | loss_multiplier mean: 1.028714
13_employ   | seasonal: 0.000000  waiter: 0.030303  | loss_multiplier mean: 1.025415
14_auth_tl  | flag mean: 0.020202  | loss_multiplier mean: 1.027153
15_fraud    | fraud_adj mean: 1.019293  | loss_multiplier mean: 1.043167
16_driver   | flag mean: 0.070707  | loss_multiplier mean: 1.054113
17_pricing  | scalar mean: 0.906061  | loss_multiplier mean: 0.958697
18_final    | loss_multiplier mean: 0.949054  (post all clips)
  bb_populated: 98 / 99  wtd_mult: 0.929534  ragu_gli: 1.7616

============================================================
  FLD 2026-08-16/2026-08-22  (n=83)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.012048  | loss_multiplier mean: 1.001205
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001205
03_zero_cd  | flag mean: 0.084337  | loss_multiplier mean: 1.001205
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001205
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001205
06_car_make | penalty: 0.000000  benefit: 0.216867  | loss_multiplier mean: 0.957831
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.957831
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.957831
09_wknd/day | weekend: 0.253012  weekday: 0.746988  | loss_multiplier mean: 0.959783
10_stud_ln  | flag mean: 0.240964  | loss_multiplier mean: 0.961418
11_low_pti  | flag mean: 0.084337  | loss_multiplier mean: 0.948943
12_chime    | flag mean: 0.204819  | loss_multiplier mean: 0.969026
13_employ   | seasonal: 0.000000  waiter: 0.000000  | loss_multiplier mean: 0.969026
14_auth_tl  | flag mean: 0.024096  | loss_multiplier mean: 0.971171
15_fraud    | fraud_adj mean: 0.986145  | loss_multiplier mean: 0.958087
16_driver   | flag mean: 0.024096  | loss_multiplier mean: 0.962209
17_pricing  | scalar mean: 0.872892  | loss_multiplier mean: 0.852064
18_final    | loss_multiplier mean: 0.871558  (post all clips)
  bb_populated: 83 / 83  wtd_mult: 0.875477  ragu_gli: 3.1131

============================================================
  FLD 2026-08-23/2026-08-29  (n=107)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.018692  | loss_multiplier mean: 1.001869
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001869
03_zero_cd  | flag mean: 0.205607  | loss_multiplier mean: 1.001869
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001869
05_high_pti | flag mean: 0.009346  | loss_multiplier mean: 1.001869
06_car_make | penalty: 0.000000  benefit: 0.102804  | loss_multiplier mean: 0.981308
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.981308
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.981308
09_wknd/day | weekend: 0.308411  weekday: 0.691589  | loss_multiplier mean: 0.979607
10_stud_ln  | flag mean: 0.214953  | loss_multiplier mean: 0.978595
11_low_pti  | flag mean: 0.065421  | loss_multiplier mean: 0.968998
12_chime    | flag mean: 0.317757  | loss_multiplier mean: 1.018715
13_employ   | seasonal: 0.037383  waiter: 0.028037  | loss_multiplier mean: 1.019677
14_auth_tl  | flag mean: 0.028037  | loss_multiplier mean: 1.022357
15_fraud    | fraud_adj mean: 0.996729  | loss_multiplier mean: 1.017190

,FLD | 2026-05-31/2026-06-06,FLD | 2026-06-07/2026-06-13,FLD | 2026-06-14/2026-06-20,FLD | 2026-06-21/2026-06-27,FLD | 2026-06-28/2026-07-04,FLD | 2026-07-05/2026-07-11,FLD | 2026-07-12/2026-07-18,FLD | 2026-07-19/2026-07-25,FLD | 2026-07-26/2026-08-01,FLD | 2026-08-02/2026-08-08,FLD | 2026-08-09/2026-08-15,FLD | 2026-08-16/2026-08-22,FLD | 2026-08-23/2026-08-29,FLD | 2026-08-30/2026-09-05,FLD | 2026-09-06/2026-09-12,FLD | 2026-09-13/2026-09-19,FLD | 2026-09-20/2026-09-26
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000709,1.002143,1.000000,1.001765,1.001439,1.000699,1.002113,1.001212,1.003361,1.000000,1.000000,1.001205,1.001869,1.000000,1.002273,1.001562,1.000000
02_small_amt_financed,1.000709,1.002143,1.000000,1.001765,1.001439,1.000699,1.002113,1.001212,1.003361,1.000000,1.000000,1.001205,1.001869,1.000000,1.002273,1.001562,1.000000
03_zero_cash_down,1.000709,1.002143,1.000000,1.001765,1.001439,1.000699,1.002113,1.001212,1.003361,1.000000,1.000000,1.001205,1.001869,1.000000,1.002273,1.001562,1.000000
04_high_mileage,1.000709,1.002143,1.000000,1.001765,1.001439,1.000699,1.002113,1.001212,1.003361,1.000000,1.000000,1.001205,1.001869,1.000000,1.002273,1.001562,1.000000
05_high_pti,1.000709,1.002143,1.000000,1.001765,1.001439,1.000699,1.002113,1.001212,1.003361,1.000000,1.000000,1.001205,1.001869,1.000000,1.002273,1.001562,1.000000
06_car_make,0.972340,0.969286,0.967347,0.970000,0.978417,0.972727,0.971127,0.961212,0.968908,0.952809,0.967677,0.957831,0.981308,0.960396,0.974773,0.951562,0.933333
07_theft_risk,0.972340,0.969286,0.967347,0.970000,0.978417,0.972727,0.971127,0.961212,0.968908,0.952809,0.967677,0.957831,0.981308,0.960396,0.974773,0.951562,0.933333
08_mcy_low_mileage,0.972340,0.969286,0.967347,0.970000,0.978417,0.972727,0.971127,0.961212,0.968908,0.952809,0.967677,0.957831,0.981308,0.960396,0.974773,0.951562,0.933333
09_weekend_weekday,0.974014,0.970271,0.968694,0.970171,0.988518,0.971231,0.971620,0.963891,0.968050,0.958022,0.972465,0.959783,0.979607,0.961030,0.978200,0.962281,0.916222
10_student_loans,0.966581,0.963206,0.965580,0.965604,0.988993,0.963967,0.969298,0.962296,0.969416,0.945483,0.983280,0.961418,0.978595,0.950656,0.970735,0.948936,0.888736
11_low_pti,0.957698,0.958907,0.956963,0.957161,0.984722,0.960783,0.963111,0.958841,0.959605,0.942169,0.976765,0.948943,0.968998,0.942517,0.962077,0.941358,0.888736
12_chime,0.989951,0.991034,0.993064,0.988701,1.006849,0.995871,0.994096,0.991047,1.002338,0.946809,1.028714,0.969026,1.018715,0.970612,0.968506,0.929118,0.858519
13_employment_type,0.990127,0.991181,0.994217,0.989263,1.007043,0.995373,0.994287,0.992355,0.999644,0.947669,1.025415,0.969026,1.019677,0.968994,0.967203,0.929118,0.858519
14_auth_tradelines,0.991907,0.994838,0.996184,0.990459,1.011675,0.996319,0.998996,0.995982,1.001197,0.948479,1.027153,0.971171,1.022357,0.971237,0.970244,0.929118,0.858519
15_fraud,0.984545,0.991847,0.987976,0.986572,1.014232,0.997636,1.003345,0.993341,0.988566,0.936057,1.043167,0.958087,1.017190,0.955953,0.946383,0.929118,0.858519
16_driver_flag,0.992820,0.996841,0.993641,0.992844,1.019232,1.001025,1.010540,0.999301,0.992234,0.943437,1.054113,0.962209,1.025810,0.968880,0.952828,0.937924,0.871262
17_pricing_scalar,0.892367,0.864955,0.885138,0.899200,0.916084,0.881456,0.929855,0.915447,0.859336,0.822171,0.958697,0.852064,0.861380,0.836763,0.838462,0.838161,0.827908
18_final,0.889256,0.878263,0.896117,0.893996,0.924309,0.892723,0.921371,0.917308,0.873872,0.841795,0.949054,0.871558,0.872625,0.851418,0.856052,0.849568,0.849126
--- FINAL_MULT (mean),0.889256,0.878263,0.896117,0.893996,0.924309,0.892723,0.921371,0.917308,0.873872,0.841795,0.949054,0.871558,0.872625,0.851418,0.856052,0.849568,0.849126
--- WTD_MULT_RAGU,0.901134,0.871312,0.898460,0.893008,0.922115,0.893246,0.917720,0.903148,0.877372,0.847212,0.929534,0.875477,0.871153,0.859790,0.863584,0.847802,0.825935
--- GROSS_LOSS_IMPACT,2.471661,3.217192,2.538498,2.674799,1.947116,2.668862,2.057001,2.421300,3.065704,3.819690,1.761642,3.113065,3.221187,3.505255,3.410389,3.804950,4.351620
--- N_RECORDS,141.000000,140.000000,147.000000,170.000000,139.000000,143.000000,142.000000,165.000000,119.000000,89.000000,99.000000,83.000000,107.000000,101.000000,88.000000,64.000000,9.000000

--- FLD Flag Means ---

,FLD | 2026-05-31/2026-06-06,FLD | 2026-06-07/2026-06-13,FLD | 2026-06-14/2026-06-20,FLD | 2026-06-21/2026-06-27,FLD | 2026-06-28/2026-07-04,FLD | 2026-07-05/2026-07-11,FLD | 2026-07-12/2026-07-18,FLD | 2026-07-19/2026-07-25,FLD | 2026-07-26/2026-08-01,FLD | 2026-08-02/2026-08-08,FLD | 2026-08-09/2026-08-15,FLD | 2026-08-16/2026-08-22,FLD | 2026-08-23/2026-08-29,FLD | 2026-08-30/2026-09-05,FLD | 2026-09-06/2026-09-12,FLD | 2026-09-13/2026-09-19,FLD | 2026-09-20/2026-09-26
prev_co_flag,0.007092,0.021429,0.000000,0.017647,0.014388,0.006993,0.021127,0.012121,0.033613,0.000000,0.000000,0.012048,0.018692,0.000000,0.022727,0.015625,0.000000
small_amt_financed_flag,0.000000,0.000000,0.000000,0.017647,0.000000,0.000000,0.014085,0.006061,0.000000,0.000000,0.010101,0.000000,0.000000,0.000000,0.011364,0.000000,0.000000
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
zero_cash_down_flag,0.106383,0.071429,0.156463,0.152941,0.151079,0.174825,0.147887,0.121212,0.100840,0.112360,0.131313,0.084337,0.205607,0.207921,0.204545,0.156250,0.111111
high_mileage_vehicle_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
high_pti_flag,0.014184,0.014286,0.000000,0.000000,0.007194,0.000000,0.000000,0.012121,0.000000,0.000000,0.000000,0.000000,0.009346,0.019802,0.000000,0.000000,0.000000
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008403,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
car_make_benefit_flag,0.141844,0.164286,0.163265,0.158824,0.115108,0.139860,0.154930,0.200000,0.176471,0.235955,0.161616,0.216867,0.102804,0.198020,0.136364,0.250000,0.333333
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
weekend_flag,0.262411,0.271429,0.265306,0.282353,0.143885,0.307692,0.274648,0.254545,0.302521,0.213483,0.212121,0.253012,0.308411,0.277228,0.238636,0.125000,0.555556
weekday_flag,0.737589,0.728571,0.734694,0.717647,0.856115,0.692308,0.725352,0.745455,0.697479,0.786517,0.787879,0.746988,0.691589,0.722772,0.761364,0.875000,0.444444
student_loan_flag,0.170213,0.164286,0.204082,0.182353,0.230216,0.167832,0.204225,0.212121,0.235294,0.123596,0.303030,0.240964,0.214953,0.148515,0.170455,0.125000,0.000000
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
low_pti_flag,0.063830,0.028571,0.054422,0.058824,0.028777,0.020979,0.042254,0.024242,0.067227,0.022472,0.050505,0.084337,0.065421,0.059406,0.056818,0.046875,0.000000
nonkmx_chime_flag,0.248227,0.250000,0.265306,0.247059,0.201439,0.258741,0.239437,0.248485,0.285714,0.146067,0.313131,0.204819,0.317757,0.227723,0.147727,0.078125,0.000000
seasonal_employment_pct,0.021277,0.014286,0.020408,0.011765,0.007194,0.000000,0.021127,0.018182,0.000000,0.011236,0.000000,0.000000,0.037383,0.029703,0.011364,0.000000,0.000000
waiter_employment_pct,0.021277,0.014286,0.013605,0.005882,0.007194,0.006993,0.021127,0.006061,0.025210,0.000000,0.030303,0.000000,0.028037,0.049505,0.022727,0.000000,0.000000
nonkmx_auth_tradelines_flag,0.021277,0.035714,0.020408,0.011765,0.043165,0.013986,0.049296,0.036364,0.016807,0.011236,0.020202,0.024096,0.028037,0.029703,0.034091,0.000000,0.000000
fraud_adjustment_mean,0.992553,0.997714,0.991905,0.993941,1.002662,1.000979,1.006056,0.995697,0.985798,0.987079,1.019293,0.986145,0.996729,0.983663,0.975682,1.000000,1.000000
driver_flag,0.049645,0.035714,0.040816,0.041176,0.035971,0.020979,0.042254,0.042424,0.025210,0.044944,0.070707,0.024096,0.056075,0.089109,0.045455,0.062500,0.111111
pricing_scalar_mean,0.890426,0.863571,0.884014,0.892647,0.893885,0.876923,0.910915,0.909394,0.856723,0.856180,0.906061,0.872892,0.837850,0.849505,0.872159,0.889062,0.927778
--- N_RECORDS,141.000000,140.000000,147.000000,170.000000,139.000000,143.000000,142.000000,165.000000,119.000000,89.000000,99.000000,83.000000,107.000000,101.000000,88.000000,64.000000,9.000000

--- FLD Gross Loss Attribution ---

,FLD | 2026-05-31/2026-06-06,FLD | 2026-06-07/2026-06-13,FLD | 2026-06-14/2026-06-20,FLD | 2026-06-21/2026-06-27,FLD | 2026-06-28/2026-07-04,FLD | 2026-07-05/2026-07-11,FLD | 2026-07-12/2026-07-18,FLD | 2026-07-19/2026-07-25,FLD | 2026-07-26/2026-08-01,FLD | 2026-08-02/2026-08-08,FLD | 2026-08-09/2026-08-15,FLD | 2026-08-16/2026-08-22,FLD | 2026-08-23/2026-08-29,FLD | 2026-08-30/2026-09-05,FLD | 2026-09-06/2026-09-12,FLD | 2026-09-13/2026-09-19,FLD | 2026-09-20/2026-09-26
Previous ACA Chargeoff,-0.014930,-0.053052,-0.000000,-0.042087,-0.035569,-0.016441,-0.053011,-0.033983,-0.076305,-0.000000,-0.000000,-0.027267,-0.044149,-0.000000,-0.049813,-0.036439,-0.000000
Small Amount Financed,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Zero Cash Down,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High Mileage Vehicle,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
High PTI,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Car Make,0.605611,0.826214,0.768324,0.769165,0.575330,0.666767,0.788929,1.143761,0.794539,1.072169,1.106951,1.002894,0.490234,0.880596,0.610465,1.195233,1.835741
Theft Risk,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
MCY Low Mileage,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
Weekend / Weekday,-0.036219,-0.025191,-0.032203,-0.004198,-0.254075,0.036210,-0.012747,-0.078072,0.020125,-0.121028,-0.166280,-0.046098,0.041015,-0.014373,-0.077014,-0.261433,0.492335
Student Loans,0.161336,0.181124,0.074504,0.112624,-0.011873,0.176556,0.060105,0.046449,-0.032052,0.292224,-0.372621,-0.038536,0.024453,0.236510,0.168089,0.325944,0.810449
Low PTI,0.194406,0.110887,0.207488,0.209624,0.107058,0.077814,0.160820,0.100915,0.231300,0.077885,0.223986,0.295746,0.232988,0.187381,0.196593,0.187138,-0.000000
Chime / Secured Credit,-0.697508,-0.816758,-0.857023,-0.773884,-0.549717,-0.843592,-0.795367,-0.926791,-0.990715,-0.108984,-1.745769,-0.474241,-1.182918,-0.640100,-0.146142,0.305456,0.920399
Employment Type,-0.003748,-0.003671,-0.026853,-0.013570,-0.004774,0.011764,-0.004806,-0.037004,0.061206,-0.020116,0.108196,-0.000000,-0.022315,0.036364,0.029548,-0.000000,-0.000000
Authorized Tradelines,-0.037826,-0.091298,-0.045755,-0.028823,-0.113535,-0.022346,-0.118704,-0.102319,-0.035306,-0.018950,-0.057045,-0.050070,-0.062049,-0.050379,-0.068883,-0.000000,-0.000000
Fraud Adjustment,0.156876,0.074643,0.191477,0.093853,-0.062440,-0.031080,-0.109100,0.074465,0.288696,0.292379,-0.521182,0.307166,0.119796,0.345634,0.546359,-0.000000,-0.000000
Driver Flag,-0.176252,-0.124485,-0.132322,-0.151264,-0.121649,-0.079749,-0.179484,-0.167794,-0.084198,-0.174168,-0.351687,-0.097231,-0.199497,-0.292704,-0.148921,-0.220177,-0.392050
Dealer Level (Pricing Scalar),2.246367,3.517221,2.676170,2.364788,2.639479,2.991685,2.090130,2.458649,3.269830,3.051469,3.196475,2.752968,4.130271,3.194674,2.805684,2.624717,1.358089
Final Clip,0.073546,-0.378441,-0.285309,0.138571,-0.221121,-0.298727,0.230237,-0.056976,-0.381414,-0.523189,0.340618,-0.512267,-0.306641,-0.378348,-0.455576,-0.315489,-0.673342
--- TOTAL (check),2.471661,3.217192,2.538498,2.674799,1.947116,2.668862,2.057001,2.421300,3.065704,3.819690,1.761642,3.113065,3.221187,3.505255,3.410389,3.804950,4.351620

============================================================
  DIAGNOSTICS: ENT
============================================================

============================================================
  ENT 2026-05-31/2026-06-06  (n=137)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000000
03_zero_cd  | flag mean: 0.153285  | loss_multiplier mean: 1.000000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000000
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.000000
06_car_make | penalty: 0.000000  benefit: 0.226277  | loss_multiplier mean: 0.954745
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.954745
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.954745
09_wknd/day | weekend: 0.167883  weekday: 0.832117  | loss_multiplier mean: 0.962599
10_stud_ln  | flag mean: 0.189781  | loss_multiplier mean: 0.956952
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.956952
12_chime    | flag mean: 0.211679  | loss_multiplier mean: 0.980405
13_employ   | seasonal: 0.014599  waiter: 0.021898  | loss_multiplier mean: 0.979592
14_auth_tl  | flag mean: 0.014599  | loss_multiplier mean: 0.980987
15_fraud    | fraud_adj mean: 1.010365  | loss_multiplier mean: 0.989111
16_driver   | flag mean: 0.021898  | loss_multiplier mean: 0.992550
17_pricing  | scalar mean: 1.003285  | loss_multiplier mean: 1.001310
18_final    | loss_multiplier mean: 1.001445  (post all clips)
  bb_populated: 137 / 137  wtd_mult: 0.992511  ragu_gli: 0.1872

============================================================
  ENT 2026-06-07/2026-06-13  (n=152)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.039474  | loss_multiplier mean: 1.003947
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.003947
03_zero_cd  | flag mean: 0.177632  | loss_multiplier mean: 1.003947
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.003947
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.003947
06_car_make | penalty: 0.000000  benefit: 0.236842  | loss_multiplier mean: 0.956579
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.956579
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.956579
09_wknd/day | weekend: 0.184211  weekday: 0.815789  | loss_multiplier mean: 0.963368
10_stud_ln  | flag mean: 0.157895  | loss_multiplier mean: 0.954317
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.954317
12_chime    | flag mean: 0.236842  | loss_multiplier mean: 0.983809
13_employ   | seasonal: 0.019737  waiter: 0.019737  | loss_multiplier mean: 0.983549
14_auth_tl  | flag mean: 0.019737  | loss_multiplier mean: 0.985266
15_fraud    | fraud_adj mean: 1.019211  | loss_multiplier mean: 1.003143
16_driver   | flag mean: 0.006579  | loss_multiplier mean: 1.003898
17_pricing  | scalar mean: 0.992105  | loss_multiplier mean: 0.998530
18_final    | loss_multiplier mean: 0.992018  (post all clips)
  bb_populated: 152 / 152  wtd_mult: 0.987849  ragu_gli: 0.3038

============================================================
  ENT 2026-06-14/2026-06-20  (n=168)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.023810  | loss_multiplier mean: 1.002381
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002381
03_zero_cd  | flag mean: 0.196429  | loss_multiplier mean: 1.002381
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002381
05_high_pti | flag mean: 0.005952  | loss_multiplier mean: 1.002381
06_car_make | penalty: 0.000000  benefit: 0.226190  | loss_multiplier mean: 0.957143
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.957143
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.957143
09_wknd/day | weekend: 0.232143  weekday: 0.767857  | loss_multiplier mean: 0.960661
10_stud_ln  | flag mean: 0.214286  | loss_multiplier mean: 0.958113
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.958113
12_chime    | flag mean: 0.315476  | loss_multiplier mean: 1.007196
13_employ   | seasonal: 0.005952  waiter: 0.000000  | loss_multiplier mean: 1.007765
14_auth_tl  | flag mean: 0.023810  | loss_multiplier mean: 1.010016
15_fraud    | fraud_adj mean: 0.998869  | loss_multiplier mean: 1.011470
16_driver   | flag mean: 0.011905  | loss_multiplier mean: 1.013100
17_pricing  | scalar mean: 0.991964  | loss_multiplier mean: 1.012063
18_final    | loss_multiplier mean: 1.004011  (post all clips)
  bb_populated: 168 / 168  wtd_mult: 0.995330  ragu_gli: 0.1168

============================================================
  ENT 2026-06-21/2026-06-27  (n=162)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.018519  | loss_multiplier mean: 1.001852
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001852
03_zero_cd  | flag mean: 0.135802  | loss_multiplier mean: 1.001852
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001852
05_high_pti | flag mean: 0.006173  | loss_multiplier mean: 1.001852
06_car_make | penalty: 0.000000  benefit: 0.253086  | loss_multiplier mean: 0.951235
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.951235
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.951235
09_wknd/day | weekend: 0.271605  weekday: 0.728395  | loss_multiplier mean: 0.952543
10_stud_ln  | flag mean: 0.222222  | loss_multiplier mean: 0.951324
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.951324
12_chime    | flag mean: 0.253086  | loss_multiplier mean: 0.987175
13_employ   | seasonal: 0.000000  waiter: 0.012346  | loss_multiplier mean: 0.985995
14_auth_tl  | flag mean: 0.006173  | loss_multiplier mean: 0.986530
15_fraud    | fraud_adj mean: 1.001049  | loss_multiplier mean: 0.985862
16_driver   | flag mean: 0.012346  | loss_multiplier mean: 0.987802
17_pricing  | scalar mean: 1.002469  | loss_multiplier mean: 0.999142
18_final    | loss_multiplier mean: 0.997135  (post all clips)
  bb_populated: 162 / 162  wtd_mult: 0.994904  ragu_gli: 0.1274

============================================================
  ENT 2026-06-28/2026-07-04  (n=151)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.019868  | loss_multiplier mean: 1.001987
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001987
03_zero_cd  | flag mean: 0.205298  | loss_multiplier mean: 1.001987
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001987
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001987
06_car_make | penalty: 0.000000  benefit: 0.264901  | loss_multiplier mean: 0.949007
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.949007
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.949007
09_wknd/day | weekend: 0.145695  weekday: 0.854305  | loss_multiplier mean: 0.958298
10_stud_ln  | flag mean: 0.231788  | loss_multiplier mean: 0.958260
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.958260
12_chime    | flag mean: 0.205298  | loss_multiplier mean: 0.978986
13_employ   | seasonal: 0.006623  waiter: 0.013245  | loss_multiplier mean: 0.978353
14_auth_tl  | flag mean: 0.006623  | loss_multiplier mean: 0.978943
15_fraud    | fraud_adj mean: 0.996689  | loss_multiplier mean: 0.973566
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.973566
17_pricing  | scalar mean: 0.991722  | loss_multiplier mean: 0.975288
18_final    | loss_multiplier mean: 0.974385  (post all clips)
  bb_populated: 151 / 151  wtd_mult: 0.966961  ragu_gli: 0.8260

============================================================
  ENT 2026-07-05/2026-07-11  (n=138)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.014493  | loss_multiplier mean: 1.001449
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001449
03_zero_cd  | flag mean: 0.115942  | loss_multiplier mean: 1.001449
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001449
05_high_pti | flag mean: 0.000000  | loss_multiplier mean: 1.001449
06_car_make | penalty: 0.000000  benefit: 0.202899  | loss_multiplier mean: 0.960870
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.960870
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.960870
09_wknd/day | weekend: 0.188406  weekday: 0.811594  | loss_multiplier mean: 0.967609
10_stud_ln  | flag mean: 0.137681  | loss_multiplier mean: 0.955831
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.955831
12_chime    | flag mean: 0.224638  | loss_multiplier mean: 0.983777
13_employ   | seasonal: 0.000000  waiter: 0.000000  | loss_multiplier mean: 0.983777
14_auth_tl  | flag mean: 0.021739  | loss_multiplier mean: 0.986003
15_fraud    | fraud_adj mean: 0.996667  | loss_multiplier mean: 0.981276
16_driver   | flag mean: 0.007246  | loss_multiplier mean: 0.982419
17_pricing  | scalar mean: 0.994203  | loss_multiplier mean: 0.988405
18_final    | loss_multiplier mean: 0.985862  (post all clips)
  bb_populated: 138 / 138  wtd_mult: 0.988769  ragu_gli: 0.2808

============================================================
  ENT 2026-07-12/2026-07-18  (n=134)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.007463  | loss_multiplier mean: 1.000746
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.000746
03_zero_cd  | flag mean: 0.149254  | loss_multiplier mean: 1.000746
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.000746
05_high_pti | flag mean: 0.014925  | loss_multiplier mean: 1.000746
06_car_make | penalty: 0.000000  benefit: 0.223881  | loss_multiplier mean: 0.955970
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.955970
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.955970
09_wknd/day | weekend: 0.186567  weekday: 0.813433  | loss_multiplier mean: 0.962552
10_stud_ln  | flag mean: 0.149254  | loss_multiplier mean: 0.951984
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.951984
12_chime    | flag mean: 0.223881  | loss_multiplier mean: 0.977753
13_employ   | seasonal: 0.000000  waiter: 0.007463  | loss_multiplier mean: 0.977040
14_auth_tl  | flag mean: 0.022388  | loss_multiplier mean: 0.979337
15_fraud    | fraud_adj mean: 0.990373  | loss_multiplier mean: 0.968866
16_driver   | flag mean: 0.022388  | loss_multiplier mean: 0.972365
17_pricing  | scalar mean: 0.994030  | loss_multiplier mean: 0.974030
18_final    | loss_multiplier mean: 0.969278  (post all clips)
  bb_populated: 134 / 134  wtd_mult: 0.963663  ragu_gli: 0.9084

============================================================
  ENT 2026-07-19/2026-07-25  (n=142)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.021127  | loss_multiplier mean: 1.002113
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002113
03_zero_cd  | flag mean: 0.154930  | loss_multiplier mean: 1.002113
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002113
05_high_pti | flag mean: 0.007042  | loss_multiplier mean: 1.002113
06_car_make | penalty: 0.000000  benefit: 0.253521  | loss_multiplier mean: 0.951408
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.951408
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.951408
09_wknd/day | weekend: 0.239437  weekday: 0.760563  | loss_multiplier mean: 0.954120
10_stud_ln  | flag mean: 0.218310  | loss_multiplier mean: 0.952701
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.952701
12_chime    | flag mean: 0.267606  | loss_multiplier mean: 0.990774
13_employ   | seasonal: 0.007042  waiter: 0.000000  | loss_multiplier mean: 0.991385
14_auth_tl  | flag mean: 0.028169  | loss_multiplier mean: 0.994031
15_fraud    | fraud_adj mean: 0.999225  | loss_multiplier mean: 0.993676
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.993676
17_pricing  | scalar mean: 0.997535  | loss_multiplier mean: 1.000512
18_final    | loss_multiplier mean: 0.998125  (post all clips)
  bb_populated: 142 / 142  wtd_mult: 0.989489  ragu_gli: 0.2628

============================================================
  ENT 2026-07-26/2026-08-01  (n=126)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.023810  | loss_multiplier mean: 1.002381
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002381
03_zero_cd  | flag mean: 0.142857  | loss_multiplier mean: 1.002381
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002381
05_high_pti | flag mean: 0.015873  | loss_multiplier mean: 1.002381
06_car_make | penalty: 0.000000  benefit: 0.198413  | loss_multiplier mean: 0.962698
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.962698
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.962698
09_wknd/day | weekend: 0.182540  weekday: 0.817460  | loss_multiplier mean: 0.969952
10_stud_ln  | flag mean: 0.111111  | loss_multiplier mean: 0.954050
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.954050
12_chime    | flag mean: 0.246032  | loss_multiplier mean: 0.985223
13_employ   | seasonal: 0.007937  waiter: 0.023810  | loss_multiplier mean: 0.983857
14_auth_tl  | flag mean: 0.031746  | loss_multiplier mean: 0.986892
15_fraud    | fraud_adj mean: 1.005873  | loss_multiplier mean: 0.993930
16_driver   | flag mean: 0.000000  | loss_multiplier mean: 0.993930
17_pricing  | scalar mean: 0.999206  | loss_multiplier mean: 1.001621
18_final    | loss_multiplier mean: 0.991825  (post all clips)
  bb_populated: 126 / 126  wtd_mult: 0.983673  ragu_gli: 0.4082

============================================================
  ENT 2026-08-02/2026-08-08  (n=120)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.025000  | loss_multiplier mean: 1.002500
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002500
03_zero_cd  | flag mean: 0.158333  | loss_multiplier mean: 1.002500
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002500
05_high_pti | flag mean: 0.016667  | loss_multiplier mean: 1.002500
06_car_make | penalty: 0.000000  benefit: 0.125000  | loss_multiplier mean: 0.977500
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.977500
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.977500
09_wknd/day | weekend: 0.283333  weekday: 0.716667  | loss_multiplier mean: 0.977742
10_stud_ln  | flag mean: 0.250000  | loss_multiplier mean: 0.980297
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.980297
12_chime    | flag mean: 0.258333  | loss_multiplier mean: 1.014758
13_employ   | seasonal: 0.016667  waiter: 0.008333  | loss_multiplier mean: 1.015710
14_auth_tl  | flag mean: 0.016667  | loss_multiplier mean: 1.017248
15_fraud    | fraud_adj mean: 1.007417  | loss_multiplier mean: 1.027409
16_driver   | flag mean: 0.025000  | loss_multiplier mean: 1.031514
17_pricing  | scalar mean: 0.984167  | loss_multiplier mean: 1.007948
18_final    | loss_multiplier mean: 0.998813  (post all clips)
  bb_populated: 120 / 120  wtd_mult: 0.998282  ragu_gli: 0.0430

============================================================
  ENT 2026-08-09/2026-08-15  (n=150)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.020000  | loss_multiplier mean: 1.002000
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.002000
03_zero_cd  | flag mean: 0.146667  | loss_multiplier mean: 1.002000
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.002000
05_high_pti | flag mean: 0.013333  | loss_multiplier mean: 1.002000
06_car_make | penalty: 0.000000  benefit: 0.140000  | loss_multiplier mean: 0.974000
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.974000
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.974000
09_wknd/day | weekend: 0.206667  weekday: 0.793333  | loss_multiplier mean: 0.979340
10_stud_ln  | flag mean: 0.220000  | loss_multiplier mean: 0.977345
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.977345
12_chime    | flag mean: 0.240000  | loss_multiplier mean: 1.007477
13_employ   | seasonal: 0.013333  waiter: 0.013333  | loss_multiplier mean: 1.007299
14_auth_tl  | flag mean: 0.033333  | loss_multiplier mean: 1.010461
15_fraud    | fraud_adj mean: 0.976867  | loss_multiplier mean: 0.985778
16_driver   | flag mean: 0.006667  | loss_multiplier mean: 0.987034
17_pricing  | scalar mean: 1.001667  | loss_multiplier mean: 0.992044
18_final    | loss_multiplier mean: 0.992232  (post all clips)
  bb_populated: 150 / 150  wtd_mult: 0.987649  ragu_gli: 0.3088

============================================================
  ENT 2026-08-16/2026-08-22  (n=137)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.014599  | loss_multiplier mean: 1.001460
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.001460
03_zero_cd  | flag mean: 0.167883  | loss_multiplier mean: 1.001460
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.001460
05_high_pti | flag mean: 0.014599  | loss_multiplier mean: 1.001460
06_car_make | penalty: 0.000000  benefit: 0.175182  | loss_multiplier mean: 0.966423
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.966423
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.966423
09_wknd/day | weekend: 0.255474  weekday: 0.744526  | loss_multiplier mean: 0.968328
10_stud_ln  | flag mean: 0.189781  | loss_multiplier mean: 0.963218
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.963218
12_chime    | flag mean: 0.211679  | loss_multiplier mean: 0.984676
13_employ   | seasonal: 0.007299  waiter: 0.007299  | loss_multiplier mean: 0.984768
14_auth_tl  | flag mean: 0.021898  | loss_multiplier mean: 0.986813
15_fraud    | fraud_adj mean: 0.993431  | loss_multiplier mean: 0.978730
16_driver   | flag mean: 0.007299  | loss_multiplier mean: 0.979777
17_pricing  | scalar mean: 0.996715  | loss_multiplier mean: 0.981176
18_final    | loss_multiplier mean: 0.981239  (post all clips)
  bb_populated: 137 / 137  wtd_mult: 0.976334  ragu_gli: 0.5917

============================================================
  ENT 2026-08-23/2026-08-29  (n=133)
============================================================
00_initial  | loss_multiplier mean: 1.000000
01_prev_co  | flag mean: 0.030075  | loss_multiplier mean: 1.003008
02_small_af | flag mean: 0.000000  | loss_multiplier mean: 1.003008
03_zero_cd  | flag mean: 0.195489  | loss_multiplier mean: 1.003008
04_high_mi  | flag mean: 0.000000  | loss_multiplier mean: 1.003008
05_high_pti | flag mean: 0.007519  | loss_multiplier mean: 1.003008
06_car_make | penalty: 0.000000  benefit: 0.218045  | loss_multiplier mean: 0.959398
07_theft    | flag mean: 0.000000  | loss_multiplier mean: 0.959398
08_mcy_low  | flag mean: 0.000000  | loss_multiplier mean: 0.959398
09_wknd/day | weekend: 0.248120  weekday: 0.751880  | loss_multiplier mean: 0.961850
10_stud_ln  | flag mean: 0.157895  | loss_multiplier mean: 0.952843
11_low_pti  | flag mean: 0.000000  | loss_multiplier mean: 0.952843
12_chime    | flag mean: 0.270677  | loss_multiplier mean: 0.989577
13_employ   | seasonal: 0.015038  waiter: 0.000000  | loss_multiplier mean: 0.991168
14_auth_tl  | flag mean: 0.030075  | loss_multiplier mean: 0.994230
15_fraud    | fraud_adj mean: 0.991654  | loss_multiplier mean: 0.986202

,ENT | 2026-05-31/2026-06-06,ENT | 2026-06-07/2026-06-13,ENT | 2026-06-14/2026-06-20,ENT | 2026-06-21/2026-06-27,ENT | 2026-06-28/2026-07-04,ENT | 2026-07-05/2026-07-11,ENT | 2026-07-12/2026-07-18,ENT | 2026-07-19/2026-07-25,ENT | 2026-07-26/2026-08-01,ENT | 2026-08-02/2026-08-08,ENT | 2026-08-09/2026-08-15,ENT | 2026-08-16/2026-08-22,ENT | 2026-08-23/2026-08-29,ENT | 2026-08-30/2026-09-05,ENT | 2026-09-06/2026-09-12,ENT | 2026-09-13/2026-09-19,ENT | 2026-09-20/2026-09-26
00_initial,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
01_prev_aca_chargeoff,1.000000,1.003947,1.002381,1.001852,1.001987,1.001449,1.000746,1.002113,1.002381,1.002500,1.002000,1.001460,1.003008,1.000820,1.002778,1.000000,1.000000
02_small_amt_financed,1.000000,1.003947,1.002381,1.001852,1.001987,1.001449,1.000746,1.002113,1.002381,1.002500,1.002000,1.001460,1.003008,1.000820,1.002778,1.000000,1.000000
03_zero_cash_down,1.000000,1.003947,1.002381,1.001852,1.001987,1.001449,1.000746,1.002113,1.002381,1.002500,1.002000,1.001460,1.003008,1.000820,1.002778,1.000000,1.000000
04_high_mileage,1.000000,1.003947,1.002381,1.001852,1.001987,1.001449,1.000746,1.002113,1.002381,1.002500,1.002000,1.001460,1.003008,1.000820,1.002778,1.000000,1.000000
05_high_pti,1.000000,1.003947,1.002381,1.001852,1.001987,1.001449,1.000746,1.002113,1.002381,1.002500,1.002000,1.001460,1.003008,1.000820,1.002778,1.000000,1.000000
06_car_make,0.954745,0.956579,0.957143,0.951235,0.949007,0.960870,0.955970,0.951408,0.962698,0.977500,0.974000,0.966423,0.959398,0.974590,0.973148,0.965385,1.000000
07_theft_risk,0.954745,0.956579,0.957143,0.951235,0.949007,0.960870,0.955970,0.951408,0.962698,0.977500,0.974000,0.966423,0.959398,0.974590,0.973148,0.965385,1.000000
08_mcy_low_mileage,0.954745,0.956579,0.957143,0.951235,0.949007,0.960870,0.955970,0.951408,0.962698,0.977500,0.974000,0.966423,0.959398,0.974590,0.973148,0.965385,1.000000
09_weekend_weekday,0.962599,0.963368,0.960661,0.952543,0.958298,0.967609,0.962552,0.954120,0.969952,0.977742,0.979340,0.968328,0.961850,0.981459,0.975630,0.970423,1.020000
10_student_loans,0.956952,0.954317,0.958113,0.951324,0.958260,0.955831,0.951984,0.952701,0.954050,0.980297,0.977345,0.963218,0.952843,0.977794,0.971930,0.958475,0.989400
11_low_pti,0.956952,0.954317,0.958113,0.951324,0.958260,0.955831,0.951984,0.952701,0.954050,0.980297,0.977345,0.963218,0.952843,0.977794,0.971930,0.958475,0.989400
12_chime,0.980405,0.983809,1.007196,0.987175,0.978986,0.983777,0.977753,0.990774,0.985223,1.014758,1.007477,0.984676,0.989577,0.994162,1.017390,0.962119,0.955760
13_employment_type,0.979592,0.983549,1.007765,0.985995,0.978353,0.983777,0.977040,0.991385,0.983857,1.015710,1.007299,0.984768,0.991168,0.995897,1.020235,0.962119,0.955760
14_auth_tradelines,0.980987,0.985266,1.010016,0.986530,0.978943,0.986003,0.979337,0.994031,0.986892,1.017248,1.010461,0.986813,0.994230,1.000688,1.021120,0.963957,0.955760
15_fraud,0.989111,1.003143,1.011470,0.985862,0.973566,0.981276,0.968866,0.993676,0.993930,1.027409,0.985778,0.978730,0.986202,0.981926,1.010611,0.963957,0.955760
16_driver_flag,0.992550,1.003898,1.013100,0.987802,0.973566,0.982419,0.972365,0.993676,0.993930,1.031514,0.987034,0.979777,0.988170,0.982802,1.011939,0.966714,0.955760
17_pricing_scalar,1.001310,0.998530,1.012063,0.999142,0.975288,0.988405,0.974030,1.000512,1.001621,1.007948,0.992044,0.981176,0.993793,0.976046,1.018451,0.959395,0.965318
18_final,1.001445,0.992018,1.004011,0.997135,0.974385,0.985862,0.969278,0.998125,0.991825,0.998813,0.992232,0.981239,0.990300,0.969329,1.016657,0.959208,0.965318
--- FINAL_MULT (mean),1.001445,0.992018,1.004011,0.997135,0.974385,0.985862,0.969278,0.998125,0.991825,0.998813,0.992232,0.981239,0.990300,0.969329,1.016657,0.959208,0.965318
--- WTD_MULT_RAGU,0.992511,0.987849,0.995330,0.994904,0.966961,0.988769,0.963663,0.989489,0.983673,0.998282,0.987649,0.976334,0.982150,0.963723,1.012491,0.955747,0.956062
--- GROSS_LOSS_IMPACT,0.187227,0.303786,0.116760,0.127398,0.825983,0.280768,0.908424,0.262768,0.408177,0.042955,0.308767,0.591659,0.446239,0.906922,-0.312271,1.106320,1.098446
--- N_RECORDS,137.000000,152.000000,168.000000,162.000000,151.000000,138.000000,134.000000,142.000000,126.000000,120.000000,150.000000,137.000000,133.000000,122.000000,108.000000,52.000000,5.000000

--- ENT Flag Means ---

,ENT | 2026-05-31/2026-06-06,ENT | 2026-06-07/2026-06-13,ENT | 2026-06-14/2026-06-20,ENT | 2026-06-21/2026-06-27,ENT | 2026-06-28/2026-07-04,ENT | 2026-07-05/2026-07-11,ENT | 2026-07-12/2026-07-18,ENT | 2026-07-19/2026-07-25,ENT | 2026-07-26/2026-08-01,ENT | 2026-08-02/2026-08-08,ENT | 2026-08-09/2026-08-15,ENT | 2026-08-16/2026-08-22,ENT | 2026-08-23/2026-08-29,ENT | 2026-08-30/2026-09-05,ENT | 2026-09-06/2026-09-12,ENT | 2026-09-13/2026-09-19,ENT | 2026-09-20/2026-09-26
prev_co_flag,0.000000,0.039474,0.023810,0.018519,0.019868,0.014493,0.007463,0.021127,0.023810,0.025000,0.020000,0.014599,0.030075,0.008197,0.027778,0.000000,0.00
small_amt_financed_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
pricing_change_flag,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00
zero_cash_down_flag,0.153285,0.177632,0.196429,0.135802,0.205298,0.115942,0.149254,0.154930,0.142857,0.158333,0.146667,0.167883,0.195489,0.155738,0.175926,0.134615,0.00
high_mileage_vehicle_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
high_pti_flag,0.000000,0.000000,0.005952,0.006173,0.000000,0.000000,0.014925,0.007042,0.015873,0.016667,0.013333,0.014599,0.007519,0.000000,0.000000,0.000000,0.00
car_make_penalty_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
car_make_benefit_flag,0.226277,0.236842,0.226190,0.253086,0.264901,0.202899,0.223881,0.253521,0.198413,0.125000,0.140000,0.175182,0.218045,0.131148,0.148148,0.173077,0.00
theft_risk_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
mcy_low_mileage_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
weekend_flag,0.167883,0.184211,0.232143,0.271605,0.145695,0.188406,0.186567,0.239437,0.182540,0.283333,0.206667,0.255474,0.248120,0.188525,0.250000,0.211538,0.00
weekday_flag,0.832117,0.815789,0.767857,0.728395,0.854305,0.811594,0.813433,0.760563,0.817460,0.716667,0.793333,0.744526,0.751880,0.811475,0.750000,0.788462,1.00
student_loan_flag,0.189781,0.157895,0.214286,0.222222,0.231788,0.137681,0.149254,0.218310,0.111111,0.250000,0.220000,0.189781,0.157895,0.196721,0.203704,0.134615,0.00
student_loans_cutoff_date,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00
low_pti_flag,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00
nonkmx_chime_flag,0.211679,0.236842,0.315476,0.253086,0.205298,0.224638,0.223881,0.267606,0.246032,0.258333,0.240000,0.211679,0.270677,0.180328,0.287037,0.134615,0.00
seasonal_employment_pct,0.014599,0.019737,0.005952,0.000000,0.006623,0.000000,0.000000,0.007042,0.007937,0.016667,0.013333,0.007299,0.015038,0.024590,0.027778,0.000000,0.00
waiter_employment_pct,0.021898,0.019737,0.000000,0.012346,0.013245,0.000000,0.007463,0.000000,0.023810,0.008333,0.013333,0.007299,0.000000,0.008197,0.000000,0.000000,0.00
nonkmx_auth_tradelines_flag,0.014599,0.019737,0.023810,0.006173,0.006623,0.021739,0.022388,0.028169,0.031746,0.016667,0.033333,0.021898,0.030075,0.049180,0.009259,0.019231,0.00
fraud_adjustment_mean,1.010365,1.019211,0.998869,1.001049,0.996689,0.996667,0.990373,0.999225,1.005873,1.007417,0.976867,0.993431,0.991654,0.981885,0.990000,1.000000,1.00
driver_flag,0.021898,0.006579,0.011905,0.012346,0.000000,0.007246,0.022388,0.000000,0.000000,0.025000,0.006667,0.007299,0.015038,0.008197,0.009259,0.019231,0.00
pricing_scalar_mean,1.003285,0.992105,0.991964,1.002469,0.991722,0.994203,0.994030,0.997535,0.999206,0.984167,1.001667,0.996715,0.997744,0.986475,1.000926,0.985577,1.01
--- N_RECORDS,137.000000,152.000000,168.000000,162.000000,151.000000,138.000000,134.000000,142.000000,126.000000,120.000000,150.000000,137.000000,133.000000,122.000000,108.000000,52.000000,5.00

--- ENT Gross Loss Attribution ---

,ENT | 2026-05-31/2026-06-06,ENT | 2026-06-07/2026-06-13,ENT | 2026-06-14/2026-06-20,ENT | 2026-06-21/2026-06-27,ENT | 2026-06-28/2026-07-04,ENT | 2026-07-05/2026-07-11,ENT | 2026-07-12/2026-07-18,ENT | 2026-07-19/2026-07-25,ENT | 2026-07-26/2026-08-01,ENT | 2026-08-02/2026-08-08,ENT | 2026-08-09/2026-08-15,ENT | 2026-08-16/2026-08-22,ENT | 2026-08-23/2026-08-29,ENT | 2026-08-30/2026-09-05,ENT | 2026-09-06/2026-09-12,ENT | 2026-09-13/2026-09-19,ENT | 2026-09-20/2026-09-26
Previous ACA Chargeoff,0.000000,-0.149342,0.069358,-0.082141,-0.063178,-0.028557,-0.021718,-0.295535,-0.118246,-0.090334,-0.079106,-0.045574,-0.137484,-0.023854,-0.052435,-0.000000,0.0
Small Amount Financed,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Zero Cash Down,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
High Mileage Vehicle,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
High PTI,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Car Make,-6.004805,1.832145,-1.346872,2.301754,1.729219,0.815649,1.332625,7.270897,2.008455,0.913650,1.122135,1.112547,2.035098,0.773187,0.566952,0.935813,0.0
Theft Risk,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
MCY Low Mileage,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Weekend / Weekday,1.062269,-0.268107,0.106997,-0.061036,-0.310134,-0.137814,-0.199762,-0.398494,-0.373257,-0.008943,-0.216476,-0.061524,-0.116818,-0.204471,-0.048140,-0.138280,0.0
Student Loans,-0.762867,0.357836,-0.077460,0.056865,0.001276,0.241487,0.321416,0.208390,0.821967,-0.094442,0.080747,0.165326,0.430714,0.108928,0.071820,0.329081,0.0
Low PTI,0.000000,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,0.0
Chime / Secured Credit,3.139410,-1.153727,1.457108,-1.642361,-0.681158,-0.568255,-0.777582,-5.487342,-1.598675,-1.249957,-1.202228,-0.688344,-1.731831,-0.483331,-0.864100,-0.100795,0.0
Employment Type,-0.107520,0.010020,0.016469,0.053099,0.020587,-0.000000,0.021245,-0.086277,0.068956,-0.033906,0.006988,-0.002908,-0.073548,-0.050749,-0.052772,-0.000000,0.0
Authorized Tradelines,0.184550,-0.066136,0.065059,-0.024094,-0.019175,-0.044565,-0.068368,-0.373266,-0.153106,-0.054750,-0.124095,-0.064809,-0.141184,-0.139746,-0.016389,-0.050698,0.0
Fraud Adjustment,1.069278,-0.681646,0.041956,0.030090,0.175317,0.094761,0.312965,0.050028,-0.353348,-0.359588,0.979179,0.256940,0.371168,0.551035,0.195534,-0.000000,0.0
Driver Flag,0.450152,-0.028503,0.046960,-0.087297,-0.000000,-0.022950,-0.104979,-0.000000,-0.000000,-0.144271,-0.050410,-0.033385,-0.091287,-0.025949,-0.024813,-0.075867,0.0
Dealer Level (Pricing Scalar),1.139319,0.203239,-0.029863,-0.506776,-0.056242,-0.119778,-0.049792,-0.960042,-0.383297,0.836118,-0.200464,-0.044587,-0.259784,0.200838,-0.121250,0.201876,0.0
Final Clip,0.017441,0.248007,-0.232953,0.089295,0.029471,0.050790,0.142375,0.334410,0.488728,0.329379,-0.007503,-0.002024,0.161194,0.201034,0.033321,0.005190,0.0
--- TOTAL (check),0.187227,0.303786,0.116760,0.127398,0.825983,0.280768,0.908424,0.262768,0.408177,0.042955,0.308767,0.591659,0.446239,0.906922,-0.312271,1.106320,0.0

In [9]:
# =============================================================================
# CELL 9: EXCEL EXPORT
# =============================================================================

with pd.ExcelWriter(EXCEL_OUTPUT, engine='openpyxl') as writer:
    # Per-LOB diagnostic sheets
    for lob in LOBS:
        diag_data = diag_results_by_lob.get(lob, (None, None, None))
        output_df, flags_df, attribution_df = diag_data

        sheet_mult = f'{lob} Mult Steps'[:31]
        sheet_flags = f'{lob} Flags'[:31]
        sheet_attr = f'{lob} Attribution'[:31]

        if output_df is not None:
            output_df.to_excel(writer, sheet_name=sheet_mult)
        if flags_df is not None:
            flags_df.to_excel(writer, sheet_name=sheet_flags)
        if attribution_df is not None:
            attribution_df.to_excel(writer, sheet_name=sheet_attr)

    # Summary sheet with latest vintage per LOB from RAGU output
    summary_rows = []
    for lob in LOBS:
        model_df = results_by_lob.get(lob)
        if model_df is not None and len(model_df) > 0:
            lob_rows = model_df.reset_index()
            lob_rows = lob_rows[lob_rows.lob == lob]
            if len(lob_rows) > 0:
                last_vintage = lob_rows.vintage.max()
                last_row = lob_rows[lob_rows.vintage == last_vintage].iloc[0]
                summary_rows.append({
                    'LOB': lob,
                    'Latest Vintage': last_vintage,
                    'Contract MS': last_row.get('ms_original', float('nan')),
                    'Gross Loss Impact': last_row.get('gross_loss_impact', float('nan')),
                    'Recovery Impact': last_row.get('recovery_impact', float('nan')),
                    'LTV Impact': last_row.get('ltv_impact', float('nan')),
                    'APR Impact': last_row.get('apr_impact', float('nan')),
                    'RAGU Score': last_row.get('ragu_score', float('nan')),
                    'LTV': last_row.get('ltv', float('nan')),
                    'Loss Multiplier': last_row.get('loss_multiplier', float('nan')),
                })
    if summary_rows:
        summary_df = pd.DataFrame(summary_rows).set_index('LOB')
        summary_df.to_excel(writer, sheet_name='Summary')
        display(summary_df)

print(f"\nExported to {EXCEL_OUTPUT}")
print("[PROGRESS] Export Complete")

,Latest Vintage,Contract MS,Gross Loss Impact,Recovery Impact,LTV Impact,APR Impact,RAGU Score,LTV,Loss Multiplier
LOB,,,,,,,,,
AN,2026-09-20/2026-09-26,140.950932,5.916765,-2.728392,3.034236,1.646735,148.820276,1.646182,0.763329
FRN,2026-09-20/2026-09-26,145.707821,4.007899,1.707851,2.190719,-0.947783,152.666507,1.718539,0.839684
STG,2026-09-20/2026-09-26,143.419055,2.570445,-2.349836,7.688152,-0.461971,150.865845,1.335863,0.897182
FLD,2026-09-20/2026-09-26,143.940993,4.351620,-6.124615,1.876569,0.987348,145.031915,1.305852,0.825935
ENT,2026-09-13/2026-09-19,145.970888,1.106320,-0.320828,1.873664,-0.063295,148.566749,1.306053,0.955747

Exported to ../output/nonkmx_gl_diagnostics.xlsx
[PROGRESS] Export Complete